In [1]:
import pandas as pd
import numpy as np

In [2]:
from datetime import datetime
from datetime import timedelta
import time

In [5]:
df = pd.read_csv(r'd:\temp\marathon_results_2016.csv', index_col='Bib',usecols=['Bib','40K','Half','Pace','Age','M/F','Country','State','City'])
df['40K'] = df['40K'].apply(pd.to_timedelta)
df['Half'] = df['Half'].apply(pd.to_timedelta)
df['TotalSeconds'] = df['40K'].apply(lambda x: timedelta.total_seconds(x))
df['HalfSeconds'] = df['Half'].apply(lambda x: timedelta.total_seconds(x))
df.head()

,Age,M/F,City,State,Country,Half,40K,Pace,TotalSeconds,HalfSeconds
Bib,,,,,,,,,,
5,21,M,Addis Ababa,NaN,ETH,0 days 01:06:45,0 days 02:05:59,0:05:04,7559.0,4005.0
1,26,M,Ambo,NaN,ETH,0 days 01:06:46,0 days 02:05:59,0:05:06,7559.0,4006.0
6,31,M,Addis Ababa,NaN,ETH,0 days 01:06:44,0 days 02:06:47,0:05:07,7607.0,4004.0
11,33,M,Kitale,NaN,KEN,0 days 01:06:46,0 days 02:06:47,0:05:07,7607.0,4006.0
14,23,M,Eldoret,NaN,KEN,0 days 01:06:46,0 days 02:08:11,0:05:11,7691.0,4006.0

In [6]:
groupCity=df.groupby(by="City")

In [7]:
groupCity.head()

,Age,M/F,City,State,Country,Half,40K,Pace,TotalSeconds,HalfSeconds
Bib,,,,,,,,,,
5,21,M,Addis Ababa,NaN,ETH,0 days 01:06:45,0 days 02:05:59,0:05:04,7559.0,4005.0
1,26,M,Ambo,NaN,ETH,0 days 01:06:46,0 days 02:05:59,0:05:06,7559.0,4006.0
6,31,M,Addis Ababa,NaN,ETH,0 days 01:06:44,0 days 02:06:47,0:05:07,7607.0,4004.0
11,33,M,Kitale,NaN,KEN,0 days 01:06:46,0 days 02:06:47,0:05:07,7607.0,4006.0
14,23,M,Eldoret,NaN,KEN,0 days 01:06:46,0 days 02:08:11,0:05:11,7691.0,4006.0
...,...,...,...,...,...,...,...,...,...,...
15529,68,M,East Sandwich,MA,USA,0 days 02:48:31,0 days 06:18:58,0:15:11,22738.0,10111.0
26144,52,F,Justin,TX,USA,0 days 03:11:00,0 days 06:36:56,0:15:59,23816.0,11460.0
4358,43,M,Yardley,PA,USA,0 days 01:28:18,0 days 06:54:20,0:16:53,24860.0,5298.0
31985,46,F,Rossmoor,CA,USA,0 days 03:40:16,0 days 00:00:00,0:17:51,0.0,13216.0
29403,39,M,Reedsburg,WI,USA,0 days 03:37:49,0 days 07:54:21,0:19:13,28461.0,13069.0

In [32]:
for row, content in groupCity:
    print(row,"\n",content.loc[content["TotalSeconds"].idxmin()])

0851 Oslo
 Age                          39
M/F                           F
City                  0851 Oslo
State                       NaN
Country                     NOR
Half            0 days 01:35:31
40K             0 days 03:15:24
Pace                    0:07:55
TotalSeconds            11724.0
HalfSeconds              5731.0
Name: 6229, dtype: object
20832
 Age                          35
M/F                           M
City                      20832
State                        MD
Country                     USA
Half            0 days 01:35:57
40K             0 days 03:14:00
Pace                    0:07:51
TotalSeconds            11640.0
HalfSeconds              5757.0
Name: 4186, dtype: object
34-120 Andrychow
 Age                           44
M/F                            F
City            34-120 Andrychow
State                        NaN
Country                      POL
Half             0 days 01:58:39
40K              0 days 03:55:09
Pace                     0:09:28
TotalSeconds             14109.0
HalfSeconds               7119.0
Name: 31786, dtype: object
5700 Svendborg
 Age                          58
M/F                           M
City             5700 Svendborg
State                       NaN
Country                     DEN
Half            0 days 01:49:12
40K             0 days 03:44:58
Pace                    0:09:05
TotalSeconds            13498.0
HalfSeconds              6552.0
Name: 15350, dtype: object
95630
 Age                          46
M/F                           F
City                      95630
State                        CA
Country                     USA
Half            0 days 01:50:25
40K             0 days 03:37:23
Pace                    0:08:44
TotalSeconds            13043.0
HalfSeconds              6625.0
Name: 20668, dtype: object
APO
 Age                          49
M/F                           F
City                        APO
State                        AE
Country                     USA
Half            0 days 02:49:56
40K             0 days 05:43:39
Pace                    0:13:46
TotalSeconds            20619.0
HalfSeconds             10196.0
Name: 28408, dtype: object
Aabyhoj
 Age                          46
M/F                           F
City                    Aabyhoj
State                       NaN
Country                     DEN
Half            0 days 01:50:22
40K             0 days 03:37:42
Pace                    0:08:45
TotalSeconds            13062.0
HalfSeconds              6622.0
Name: 21774, dtype: object
Aalborg
 Age                          54
M/F                           M
City                    Aalborg
State                       NaN
Country                     DEN
Half            0 days 01:56:09
40K             0 days 03:48:16
Pace                    0:09:13
TotalSeconds            13696.0
HalfSeconds              6969.0
Name: 30604, dtype: object
Aarhus C
 Age                          49
M/F                           M
City                   Aarhus C
State                       NaN
Country                     DEN
Half            0 days 02:07:17
40K             0 days 04:43:05
Pace                    0:11:27
TotalSeconds            16985.0
HalfSeconds              7637.0
Name: 30621, dtype: object
Abbotsford
 Age                          60
M/F                           M
City                 Abbotsford
State                        WI
Country                     USA
Half            0 days 01:33:52
40K             0 days 03:07:23
Pace                    0:07:35
TotalSeconds            11243.0
HalfSeconds              5632.0
Name: 8196, dtype: object
Aberdeen
 Age                          37
M/F                           M
City                   Aberdeen
State                        SD
Country                     USA
Half            0 days 01:13:17
40K             0 days 02:26:45
Pace                    0:05:57
TotalSeconds             8805.0
HalfSeconds              4397.0
Name: 139, dtype: object
Aberdeen City
 Age                          34
M/F                           M
City              Aberdeen City
State                       NaN
Country                     GBR
Half            0 days 01:46:27
40K             0 days 03:28:03
Pace                    0:08:25
TotalSeconds            12483.0
HalfSeconds              6387.0
Name: 31481, dtype: object
Aberdeenshire
 Age                          48
M/F                           M
City              Aberdeenshire
State                       NaN
Country                     GBR
Half            0 days 01:44:29
40K             0 days 03:34:49
Pace                    0:08:41
TotalSeconds            12889.0
HalfSeconds              6269.0
Name: 31475, dtype: object
Abilene
 Age                          55
M/F                           M
City                    Abilene
State                        TX
Country                     USA
Half            0 days 01:35:16
40K             0 days 03:09:04
Pace                    0:07:43
TotalSeconds            11344.0
HalfSeconds              5716.0
Name: 16342, dtype: object
Abingdon
 Age                          40
M/F                           M
City                   Abingdon
State                        MD
Country                     USA
Half            0 days 01:30:47
40K             0 days 02:58:22
Pace                    0:07:12
TotalSeconds            10702.0
HalfSeconds              5447.0
Name: 5764, dtype: object
Abington
 Age                          26
M/F                           F
City                   Abington
State                        MA
Country                     USA
Half            0 days 01:37:19
40K             0 days 03:10:36
Pace                    0:07:40
TotalSeconds            11436.0
HalfSeconds              5839.0
Name: 13037, dtype: object
Abu Dhabi
 Age                          29
M/F                           F
City                  Abu Dhabi
State                       NaN
Country                     UAE
Half            0 days 01:42:03
40K             0 days 03:21:53
Pace                    0:08:11
TotalSeconds            12113.0
HalfSeconds              6123.0
Name: 16488, dtype: object
Abu Dhabi, Uae
 Age                          62
M/F                           M
City             Abu Dhabi, Uae
State                       NaN
Country                     UAE
Half            0 days 01:50:24
40K             0 days 03:51:40
Pace                    0:09:26
TotalSeconds            13900.0
HalfSeconds              6624.0
Name: 19652, dtype: object
Acapulco
 Age                          55
M/F                           M
City                   Acapulco
State                       NaN
Country                     MEX
Half            0 days 01:20:30
40K             0 days 02:49:55
Pace                    0:07:02
TotalSeconds            10195.0
HalfSeconds              4830.0
Name: 966, dtype: object
Act
 Age                          40
M/F                           M
City                        Act
State                       NaN
Country                     AUS
Half            0 days 01:27:24
40K             0 days 02:53:20
Pace                    0:07:03
TotalSeconds            10400.0
HalfSeconds              5244.0
Name: 3336, dtype: object
Acton
 Age                          32
M/F                           M
City                      Acton
State                        MA
Country                     USA
Half            0 days 01:26:29
40K             0 days 02:51:09
Pace                    0:06:56
TotalSeconds            10269.0
HalfSeconds              5189.0
Name: 1828, dtype: object
Acton Vale
 Age                          38
M/F                           M
City                 Acton Vale
State                        QC
Country                     CAN
Half            0 days 01:34:20
40K             0 days 03:19:24
Pace                    0:08:05
TotalSeconds            11964.0
HalfSeconds              5660.0
Name: 5609, dtype: object
Acushnet
 Age                          37
M/F                           F
City                   Acushnet
State                        MA
Country                     USA
Half            0 days 02:02:28
40K             0 days 04:43:24
Pace                    0:11:32
TotalSeconds            17004.0
HalfSeconds              7348.0
Name: 11781, dtype: object
Acworth
 Age                          45
M/F                           M
City                    Acworth
State                        GA
Country                     USA
Half            0 days 01:30:53
40K             0 days 03:02:51
Pace                    0:07:26
TotalSeconds            10971.0
HalfSeconds              5453.0
Name: 8897, dtype: object
Ada
 Age                          49
M/F                           M
City                        Ada
State                        MI
Country                     USA
Half            0 days 01:31:50
40K             0 days 02:58:42
Pace                    0:07:12
TotalSeconds            10722.0
HalfSeconds              5510.0
Name: 5282, dtype: object
Adams Basin
 Age                          44
M/F                           M
City                Adams Basin
State                        NY
Country                     USA
Half            0 days 01:56:15
40K             0 days 04:08:52
Pace                    0:10:25
TotalSeconds            14932.0
HalfSeconds              6975.0
Name: 6287, dtype: object
Addis Ababa
 Age                          21
M/F                           M
City                Addis Ababa
State                       NaN
Country                     ETH
Half            0 days 01:06:45
40K             0 days 02:05:59
Pace                    0:05:04
TotalSeconds             7559.0
HalfSeconds              4005.0
Name: 5, dtype: object
Adel
 Age                          24
M/F                           M
City                       Adel
State                        IA
Country                     USA
Half            0 days 01:23:26
40K             0 days 02:46:49
Pace                    0:06:44
TotalSeconds            10009.0
HalfSeconds              5006.0
Name: 4332, dtype: object
Adelaide
 Age                          44
M/F                           F
City                   Adelaide
State                       NaN
Country                     AUS
Half            0 days 01:47:36
40K             0 days 03:35:34
Pace                    0:08:44
TotalSeconds            12934.0
HalfSeconds              6456.0
Name: 15426, dtype: object
Adelaide, South Australia
 Age                                    62
M/F                                     M
City            Adelaide, South Australia
State                                 NaN
Country                               AUS
Half                      0 days 01:49:22
40K                       0 days 04:25:03
Pace                              0:11:15
TotalSeconds                      15903.0
HalfSeconds                        6562.0
Name: 19362, dtype: object
Adelphi
 Age                          32
M/F                           F
City                    Adelphi
State                        MD
Country                     USA
Half            0 days 01:40:40
40K             0 days 03:15:50
Pace                    0:07:54
TotalSeconds            11750.0
HalfSeconds              6040.0
Name: 10244, dtype: object
Adliswil
 Age                          34
M/F                           M
City                   Adliswil
State                       NaN
Country                     SUI
Half            0 days 01:24:56
40K             0 days 02:54:08
Pace                    0:07:04
TotalSeconds            10448.0
HalfSeconds              5096.0
Name: 1699, dtype: object
Adolfo Lopez Edo Mex
 Age                               50
M/F                                F
City            Adolfo Lopez Edo Mex
State                            NaN
Country                          MEX
Half                 0 days 01:43:59
40K                  0 days 03:30:14
Pace                         0:08:32
TotalSeconds                 12614.0
HalfSeconds                   6239.0
Name: 18673, dtype: object
Adrian
 Age                          36
M/F                           M
City                     Adrian
State                        MI
Country                     USA
Half            0 days 01:40:54
40K             0 days 03:26:56
Pace                    0:08:23
TotalSeconds            12416.0
HalfSeconds              6054.0
Name: 6219, dtype: object
Adstock
 Age                          54
M/F                           M
City                    Adstock
State                        QC
Country                     CAN
Half            0 days 01:49:15
40K             0 days 03:32:48
Pace                    0:08:36
TotalSeconds            12768.0
HalfSeconds              6555.0
Name: 14927, dtype: object
Aelvsjoe
 Age                          55
M/F                           M
City                   Aelvsjoe
State                       NaN
Country                     SWE
Half            0 days 01:43:44
40K             0 days 03:22:51
Pace                    0:08:13
TotalSeconds            12171.0
HalfSeconds              6224.0
Name: 12066, dtype: object
Afton
 Age                          22
M/F                           M
City                      Afton
State                        MN
Country                     USA
Half            0 days 01:25:23
40K             0 days 02:50:39
Pace                    0:06:52
TotalSeconds            10239.0
HalfSeconds              5123.0
Name: 1010, dtype: object
Agassiz
 Age                          54
M/F                           M
City                    Agassiz
State                        BC
Country                     CAN
Half            0 days 01:52:16
40K             0 days 03:54:28
Pace                    0:09:38
TotalSeconds            14068.0
HalfSeconds              6736.0
Name: 10343, dtype: object
Agawam
 Age                          45
M/F                           M
City                     Agawam
State                        MA
Country                     USA
Half            0 days 01:34:10
40K             0 days 03:07:54
Pace                    0:07:34
TotalSeconds            11274.0
HalfSeconds              5650.0
Name: 6193, dtype: object
Ageo
 Age                          64
M/F                           M
City                       Ageo
State                       NaN
Country                     JPN
Half            0 days 01:58:55
40K             0 days 04:12:10
Pace                    0:10:11
TotalSeconds            15130.0
HalfSeconds              7135.0
Name: 21558, dtype: object
Agoura Hills
 Age                          53
M/F                           F
City               Agoura Hills
State                        CA
Country                     USA
Half            0 days 01:56:35
40K             0 days 04:00:24
Pace                    0:09:53
TotalSeconds            14424.0
HalfSeconds              6995.0
Name: 24813, dtype: object
Aguanga
 Age                          40
M/F                           F
City                    Aguanga
State                        CA
Country                     USA
Half            0 days 01:52:46
40K             0 days 03:36:52
Pace                    0:08:44
TotalSeconds            13012.0
HalfSeconds              6766.0
Name: 18460, dtype: object
Aguascalientes
 Age                          42
M/F                           F
City             Aguascalientes
State                       NaN
Country                     MEX
Half            0 days 01:45:58
40K             0 days 03:29:37
Pace                    0:08:28
TotalSeconds            12577.0
HalfSeconds              6358.0
Name: 18619, dtype: object
Aguascalientes, Ags
 Age                              40
M/F                               M
City            Aguascalientes, Ags
State                           NaN
Country                         MEX
Half                0 days 01:55:01
40K                 0 days 03:47:12
Pace                        0:09:10
TotalSeconds                13632.0
HalfSeconds                  6901.0
Name: 31644, dtype: object
Ahmedabad
 Age                          42
M/F                           M
City                  Ahmedabad
State                       NaN
Country                     IND
Half            0 days 01:31:34
40K             0 days 03:02:43
Pace                    0:07:26
TotalSeconds            10963.0
HalfSeconds              5494.0
Name: 7469, dtype: object
Aibonito
 Age                          47
M/F                           M
City                   Aibonito
State                        PR
Country                     USA
Half            0 days 01:29:14
40K             0 days 03:11:46
Pace                    0:07:47
TotalSeconds            11506.0
HalfSeconds              5354.0
Name: 4182, dtype: object
Aichi
 Age                          55
M/F                           F
City                      Aichi
State                       NaN
Country                     JPN
Half            0 days 01:57:21
40K             0 days 04:13:08
Pace                    0:10:16
TotalSeconds            15188.0
HalfSeconds              7041.0
Name: 24679, dtype: object
Aiken
 Age                          25
M/F                           M
City                      Aiken
State                        SC
Country                     USA
Half            0 days 01:22:49
40K             0 days 02:44:14
Pace                    0:06:40
TotalSeconds             9854.0
HalfSeconds              4969.0
Name: 1980, dtype: object
Airdrie
 Age                          53
M/F                           M
City                    Airdrie
State                        AB
Country                     CAN
Half            0 days 01:36:37
40K             0 days 03:06:51
Pace                    0:07:33
TotalSeconds            11211.0
HalfSeconds              5797.0
Name: 11603, dtype: object
Aitkin
 Age                          47
M/F                           M
City                     Aitkin
State                        MN
Country                     USA
Half            0 days 01:36:38
40K             0 days 03:07:47
Pace                    0:07:37
TotalSeconds            11267.0
HalfSeconds              5798.0
Name: 7154, dtype: object
Ajax
 Age                          44
M/F                           M
City                       Ajax
State                        ON
Country                     CAN
Half            0 days 01:31:19
40K             0 days 03:02:35
Pace                    0:07:22
TotalSeconds            10955.0
HalfSeconds              5479.0
Name: 7590, dtype: object
Akron
 Age                          27
M/F                           M
City                      Akron
State                        OH
Country                     USA
Half            0 days 01:14:35
40K             0 days 02:27:44
Pace                    0:05:58
TotalSeconds             8864.0
HalfSeconds              4475.0
Name: 182, dtype: object
Alachua
 Age                          20
M/F                           F
City                    Alachua
State                        FL
Country                     USA
Half            0 days 01:45:44
40K             0 days 03:19:37
Pace                    0:08:02
TotalSeconds            11977.0
HalfSeconds              6344.0
Name: 15505, dtype: object
Alajuela, Atenas, Atenas
 Age                                   40
M/F                                    M
City            Alajuela, Atenas, Atenas
State                                NaN
Country                              CRC
Half                     0 days 01:34:08
40K                      0 days 03:06:01
Pace                             0:07:31
TotalSeconds                     11161.0
HalfSeconds                       5648.0
Name: 5751, dtype: object
Alameda
 Age                          46
M/F                           M
City                    Alameda
State                        CA
Country                     USA
Half            0 days 01:37:52
40K             0 days 03:09:18
Pace                    0:07:36
TotalSeconds            11358.0
HalfSeconds              5872.0
Name: 11337, dtype: object
Alamo
 Age                          36

Alleroed
 Age                          49
M/F                           F
City                   Alleroed
State                       NaN
Country                     DEN
Half            0 days 01:51:45
40K             0 days 03:56:36
Pace                    0:09:33
TotalSeconds            14196.0
HalfSeconds              6705.0
Name: 15391, dtype: object
Alliance
 Age                          26
M/F                           M
City                   Alliance
State                        OH
Country                     USA
Half            0 days 01:21:20
40K             0 days 02:40:25
Pace                    0:06:30
TotalSeconds             9625.0
HalfSeconds              4880.0
Name: 218, dtype: object
Allison Park
 Age                          44
M/F                           F
City               Allison Park
State                        PA
Country                     USA
Half            0 days 01:52:14
40K             0 days 03:47:24
Pace                    0:09:11
TotalSeconds            13644.0
HalfSeconds              6734.0
Name: 21417, dtype: object
Allston
 Age                          28
M/F                           M
City                    Allston
State                        MA
Country                     USA
Half            0 days 01:14:35
40K             0 days 02:23:57
Pace                    0:05:50
TotalSeconds             8637.0
HalfSeconds              4475.0
Name: 102, dtype: object
Alma
 Age                          48
M/F                           F
City                       Alma
State                        AR
Country                     USA
Half            0 days 01:50:13
40K             0 days 03:41:34
Pace                    0:08:58
TotalSeconds            13294.0
HalfSeconds              6613.0
Name: 22873, dtype: object
Aloha
 Age                          50
M/F                           F
City                      Aloha
State                        OR
Country                     USA
Half            0 days 01:53:20
40K             0 days 03:43:45
Pace                    0:09:03
TotalSeconds            13425.0
HalfSeconds              6800.0
Name: 20786, dtype: object
Alpena
 Age                          67
M/F                           M
City                     Alpena
State                        MI
Country                     USA
Half            0 days 02:02:35
40K             0 days 03:58:36
Pace                    0:09:41
TotalSeconds            14316.0
HalfSeconds              7355.0
Name: 23052, dtype: object
Alpharetta
 Age                          52
M/F                           M
City                 Alpharetta
State                        GA
Country                     USA
Half            0 days 01:42:38
40K             0 days 03:16:14
Pace                    0:07:55
TotalSeconds            11774.0
HalfSeconds              6158.0
Name: 14095, dtype: object
Alpine
 Age                          32
M/F                           F
City                     Alpine
State                        UT
Country                     USA
Half            0 days 01:38:26
40K             0 days 03:13:37
Pace                    0:07:49
TotalSeconds            11617.0
HalfSeconds              5906.0
Name: 8928, dtype: object
Alsip
 Age                          47
M/F                           F
City                      Alsip
State                        IL
Country                     USA
Half            0 days 01:56:29
40K             0 days 03:45:52
Pace                    0:09:06
TotalSeconds            13552.0
HalfSeconds              6989.0
Name: 21904, dtype: object
Alston
 Age                          30
M/F                           F
City                     Alston
State                        MA
Country                     USA
Half            0 days 02:03:03
40K             0 days 04:20:14
Pace                    0:10:29
TotalSeconds            15614.0
HalfSeconds              7383.0
Name: 31060, dtype: object
Alta
 Age                          55
M/F                           F
City                       Alta
State                        WY
Country                     USA
Half            0 days 01:49:25
40K             0 days 03:36:58
Pace                    0:08:45
TotalSeconds            13018.0
HalfSeconds              6565.0
Name: 23556, dtype: object
Altadena
 Age                          42
M/F                           M
City                   Altadena
State                        CA
Country                     USA
Half            0 days 01:28:46
40K             0 days 03:05:19
Pace                    0:07:30
TotalSeconds            11119.0
HalfSeconds              5326.0
Name: 4690, dtype: object
Altavilla Vicentina
 Age                              48
M/F                               M
City            Altavilla Vicentina
State                           NaN
Country                         ITA
Half                0 days 01:32:26
40K                 0 days 03:06:46
Pace                        0:07:31
TotalSeconds                11206.0
HalfSeconds                  5546.0
Name: 8669, dtype: object
Altavista
 Age                          46
M/F                           F
City                  Altavista
State                        VA
Country                     USA
Half            0 days 02:03:10
40K             0 days 04:09:09
Pace                    0:10:02
TotalSeconds            14949.0
HalfSeconds              7390.0
Name: 23533, dtype: object
Altdorf
 Age                          55
M/F                           M
City                    Altdorf
State                       NaN
Country                     SUI
Half            0 days 02:04:12
40K             0 days 04:09:55
Pace                    0:10:09
TotalSeconds            14995.0
HalfSeconds              7452.0
Name: 31528, dtype: object
Althengstett
 Age                          37
M/F                           M
City               Althengstett
State                       NaN
Country                     GER
Half            0 days 01:51:44
40K             0 days 03:47:51
Pace                    0:09:09
TotalSeconds            13671.0
HalfSeconds              6704.0
Name: 31036, dtype: object
Alton
 Age                          52
M/F                           F
City                      Alton
State                        ON
Country                     CAN
Half            0 days 01:46:47
40K             0 days 03:31:09
Pace                    0:08:30
TotalSeconds            12669.0
HalfSeconds              6407.0
Name: 13406, dtype: object
Altoona
 Age                          29
M/F                           F
City                    Altoona
State                        IA
Country                     USA
Half            0 days 01:36:17
40K             0 days 03:08:33
Pace                    0:07:38
TotalSeconds            11313.0
HalfSeconds              5777.0
Name: 10854, dtype: object
Alvin
 Age                          48
M/F                           F
City                      Alvin
State                        TX
Country                     USA
Half            0 days 01:40:22
40K             0 days 03:20:36
Pace                    0:08:06
TotalSeconds            12036.0
HalfSeconds              6022.0
Name: 13513, dtype: object
Alvsjo
 Age                          65
M/F                           M
City                     Alvsjo
State                       NaN
Country                     SWE
Half            0 days 02:24:46
40K             0 days 05:28:49
Pace                    0:13:27
TotalSeconds            19729.0
HalfSeconds              8686.0
Name: 25492, dtype: object
Amarillo
 Age                          26
M/F                           F
City                   Amarillo
State                        TX
Country                     USA
Half            0 days 01:41:01
40K             0 days 03:25:29
Pace                    0:08:17
TotalSeconds            12329.0
HalfSeconds              6061.0
Name: 16762, dtype: object
Ambler
 Age                          25
M/F                           M
City                     Ambler
State                        PA
Country                     USA
Half            0 days 01:25:59
40K             0 days 02:53:49
Pace                    0:07:04
TotalSeconds            10429.0
HalfSeconds              5159.0
Name: 1843, dtype: object
Ambo
 Age                          26
M/F                           M
City                       Ambo
State                       NaN
Country                     ETH
Half            0 days 01:06:46
40K             0 days 02:05:59
Pace                    0:05:06
TotalSeconds             7559.0
HalfSeconds              4006.0
Name: 1, dtype: object
Amelia Island
 Age                          66
M/F                           M
City              Amelia Island
State                        FL
Country                     USA
Half            0 days 01:47:32
40K             0 days 03:27:39
Pace                    0:08:21
TotalSeconds            12459.0
HalfSeconds              6452.0
Name: 21397, dtype: object
American Fork
 Age                          41
M/F                           F
City              American Fork
State                        UT
Country                     USA
Half            0 days 01:51:57
40K             0 days 03:40:13
Pace                    0:08:54
TotalSeconds            13213.0
HalfSeconds              6717.0
Name: 20412, dtype: object
Americus
 Age                          50
M/F                           M
City                   Americus
State                        GA
Country                     USA
Half            0 days 01:30:50
40K             0 days 02:54:20
Pace                    0:07:01
TotalSeconds            10460.0
HalfSeconds              5450.0
Name: 1471, dtype: object
Amersfoort
 Age                          41
M/F                           M
City                 Amersfoort
State                       NaN
Country                     NED
Half            0 days 01:24:03
40K             0 days 02:44:22
Pace                    0:06:38
TotalSeconds             9862.0
HalfSeconds              5043.0
Name: 1182, dtype: object
Ames
 Age                          27
M/F                           M
City                       Ames
State                        IA
Country                     USA
Half            0 days 01:25:39
40K             0 days 02:51:28
Pace                    0:06:59
TotalSeconds            10288.0
HalfSeconds              5139.0
Name: 1866, dtype: object
Amesbury
 Age                          39
M/F                           F
City                   Amesbury
State                        MA
Country                     USA
Half            0 days 01:33:45
40K             0 days 02:58:57
Pace                    0:07:11
TotalSeconds            10737.0
HalfSeconds              5625.0
Name: 6236, dtype: object
Amherst
 Age                          39
M/F                           M
City                    Amherst
State                        NY
Country                     USA
Half            0 days 01:21:27
40K             0 days 02:47:09
Pace                    0:06:45
TotalSeconds            10029.0
HalfSeconds              4887.0
Name: 358, dtype: object
Amherst Jct
 Age                          31
M/F                           F
City                Amherst Jct
State                        WI
Country                     USA
Half            0 days 02:08:00
40K             0 days 04:20:42
Pace                    0:10:25
TotalSeconds            15642.0
HalfSeconds              7680.0
Name: 16363, dtype: object
Amherstburg
 Age                          26
M/F                           F
City                Amherstburg
State                        ON
Country                     CAN
Half            0 days 01:36:05
40K             0 days 03:15:50
Pace                    0:07:53
TotalSeconds            11750.0
HalfSeconds              5765.0
Name: 8115, dtype: object
Amityville
 Age                          43
M/F                           M
City                 Amityville
State                        NY
Country                     USA
Half            0 days 01:19:57
40K             0 days 02:36:48
Pace                    0:06:19
TotalSeconds             9408.0
HalfSeconds              4797.0
Name: 589, dtype: object
Ammon
 Age                          39
M/F                           F
City                      Ammon
State                        ID
Country                     USA
Half            0 days 01:51:09
40K             0 days 03:45:18
Pace                    0:09:05
TotalSeconds            13518.0
HalfSeconds              6669.0
Name: 19578, dtype: object
Amos
 Age                          27
M/F                           M
City                       Amos
State                        QC
Country                     CAN
Half            0 days 01:21:11
40K             0 days 02:41:50
Pace                    0:06:34
TotalSeconds             9710.0
HalfSeconds              4871.0
Name: 1112, dtype: object
Amsterdam
 Age                          44
M/F                           M
City                  Amsterdam
State                       NaN
Country                     NED
Half            0 days 01:35:01
40K             0 days 03:09:27
Pace                    0:07:40
TotalSeconds            11367.0
HalfSeconds              5701.0
Name: 8766, dtype: object
Amston
 Age                          41
M/F                           M
City                     Amston
State                        CT
Country                     USA
Half            0 days 01:50:13
40K             0 days 03:22:04
Pace                    0:08:08
TotalSeconds            12124.0
HalfSeconds              6613.0
Name: 8311, dtype: object
Anacortes
 Age                          55
M/F                           M
City                  Anacortes
State                        WA
Country                     USA
Half            0 days 01:47:19
40K             0 days 03:30:57
Pace                    0:08:29
TotalSeconds            12657.0
HalfSeconds              6439.0
Name: 9252, dtype: object
Anaheim
 Age                          62
M/F                           F
City                    Anaheim
State                        CA
Country                     USA
Half            0 days 01:52:14
40K             0 days 03:31:00
Pace                    0:08:30
TotalSeconds            12660.0
HalfSeconds              6734.0
Name: 25147, dtype: object
Anaheim Hills
 Age                          27
M/F                           F
City              Anaheim Hills
State                        CA
Country                     USA
Half            0 days 01:32:36
40K             0 days 03:04:05
Pace                    0:07:26
TotalSeconds            11045.0
HalfSeconds              5556.0
Name: 4986, dtype: object
Anapolis - Goias
 Age                           45
M/F                            M
City            Anapolis - Goias
State                        NaN
Country                      BRA
Half             0 days 01:36:55
40K              0 days 03:17:40
Pace                     0:08:00
TotalSeconds             11860.0
HalfSeconds               5815.0
Name: 7558, dtype: object
Ancaster
 Age                          40
M/F                           M
City                   Ancaster
State                        ON
Country                     CAN
Half            0 days 01:41:40
40K             0 days 03:23:12
Pace                    0:08:15
TotalSeconds            12192.0
HalfSeconds              6100.0
Name: 8631, dtype: object
Anchorage
 Age                          23
M/F                           M
City                  Anchorage
State                        AK
Country                     USA
Half            0 days 01:16:57
40K             0 days 02:29:13
Pace                    0:06:01
TotalSeconds             8953.0
HalfSeconds              4617.0
Name: 210, dtype: object
Ancienne-Lorette
 Age                           58
M/F                            M
City            Ancienne-Lorette
State                         QC
Country                      CAN
Half             0 days 01:49:04
40K              0 days 03:30:37
Pace                     0:08:28
TotalSeconds             12637.0
HalfSeconds               6544.0
Name: 18805, dtype: object
Anderson
 Age                          51
M/F                           M
City                   Anderson
State                        IN
Country                     USA
Half            0 days 01:47:41
40K             0 days 03:22:30
Pace                    0:08:08
TotalSeconds            12150.0
HalfSeconds              6461.0
Name: 13512, dtype: object
Andover
 Age                          31
M/F                           M
City                    Andover
State                        MA
Country                     USA
Half            0 days 01:17:10
40K             0 days 02:30:17
Pace                    0:06:04
TotalSeconds             9017.0
HalfSeconds              4630.0
Name: 989, dtype: object
Angleton
 Age                          56
M/F                           F
City                   Angleton
State                        TX
Country                     USA
Half            0 days 01:55:04
40K             0 days 03:52:55
Pace                    0:09:27
TotalSeconds            13975.0
HalfSeconds              6904.0
Name: 25438, dtype: object
Angola
 Age                          38
M/F                           F
City                     Angola
State                        IN
Country                     USA
Half            0 days 01:43:51
40K             0 days 03:33:11
Pace                    0:08:37
TotalSeconds            12791.0
HalfSeconds              6231.0
Name: 14137, dtype: object
Anjou
 Age                          45
M/F                           M
City                      Anjou
State                        QC
Country                     CAN
Half            0 days 01:35:13
40K             0 days 03:10:29
Pace                    0:07:43
TotalSeconds            11429.0
HalfSeconds              5713.0
Name: 8287, dtype: object
Ankeny
 Age                          37
M/F                           M
City                     Ankeny
State                        IA
Country                     USA
Half            0 days 01:28:20
40K             0 days 02:52:32
Pace                    0:06:58
TotalSeconds            10352.0
HalfSeconds              5300.0
Name: 3258, dtype: object
Anmore
 Age                          40
M/F                           F
City                     Anmore
State                        BC
Country                     CAN
Half            0 days 01:49:24
40K             0 days 03:37:23
Pace                    0:08:45
TotalSeconds            13043.0
HalfSeconds              6564.0
Name: 21712, dtype: object
Ann Arbor
 Age                          24
M/F                           M
City                  Ann Arbor
State                        MI
Country                     USA
Half            0 days 01:11:26
40K             0 days 02:20:35
Pace                    0:05:42
TotalSeconds             8435.0
HalfSeconds              4286.0
Name: 31, dtype: object
Annandale
 Age                          53
M/F                           M
City                  Annandale
State                        NJ
Country                     USA
Half            0 days 01:32:21
40K             0 days 03:00:18
Pace                    0:07:16
TotalSeconds            10818.0
HalfSeconds              5541.0
Name: 3211, dtype: object
Annapolis
 Age                          20
M/F                           M
City                  Annapolis
State                        MD
Country                     USA
Half            0 days 01:29:16
40K             0 days 02:55:41
Pace                    0:07:06
TotalSeconds            10541.0
HalfSeconds              5356.0
Name: 3580, dtype: object
Annville
 Age                          47
M/F                           M
City                   Annville
State                        PA
Country                     USA
Half            0 days 01:30:29
40K             0 days 03:04:57
Pace                    0:07:29
TotalSeconds            11097.0
HalfSeconds              5429.0

Name: 21568, dtype: object
Arkadelphia
 Age                          66
M/F                           M
City                Arkadelphia
State                        AR
Country                     USA
Half            0 days 02:05:07
40K             0 days 04:09:22
Pace                    0:10:05
TotalSeconds            14962.0
HalfSeconds              7507.0
Name: 25555, dtype: object
Arleta
 Age                          26
M/F                           M
City                     Arleta
State                        CA
Country                     USA
Half            0 days 01:39:22
40K             0 days 03:26:05
Pace                    0:08:18
TotalSeconds            12365.0
HalfSeconds              5962.0
Name: 5325, dtype: object
Arlington
 Age                          42
M/F                           M
City                  Arlington
State                        VA
Country                     USA
Half            0 days 01:12:32
40K             0 days 02:22:53
Pace                    0:05:48
TotalSeconds             8573.0
HalfSeconds              4352.0
Name: 78, dtype: object
Arlington Heights
 Age                            37
M/F                             M
City            Arlington Heights
State                          IL
Country                       USA
Half              0 days 01:25:52
40K               0 days 02:53:52
Pace                      0:07:02
TotalSeconds              10432.0
HalfSeconds                5152.0
Name: 3382, dtype: object
Arlington Hts
 Age                          49
M/F                           M
City              Arlington Hts
State                        IL
Country                     USA
Half            0 days 01:39:57
40K             0 days 03:15:00
Pace                    0:07:53
TotalSeconds            11700.0
HalfSeconds              5997.0
Name: 8874, dtype: object
Armagh
 Age                          31
M/F                           F
City                     Armagh
State                       NaN
Country                     GBR
Half            0 days 01:45:45
40K             0 days 03:45:43
Pace                    0:09:06
TotalSeconds            13543.0
HalfSeconds              6345.0
Name: 10024, dtype: object
Armstrong
 Age                          32
M/F                           F
City                  Armstrong
State                        IA
Country                     USA
Half            0 days 01:47:49
40K             0 days 03:31:51
Pace                    0:08:32
TotalSeconds            12711.0
HalfSeconds              6469.0
Name: 17428, dtype: object
Arnhem
 Age                          49
M/F                           M
City                     Arnhem
State                       NaN
Country                     NED
Half            0 days 01:43:52
40K             0 days 03:17:54
Pace                    0:07:59
TotalSeconds            11874.0
HalfSeconds              6232.0
Name: 11269, dtype: object
Arnold
 Age                          55
M/F                           M
City                     Arnold
State                        MD
Country                     USA
Half            0 days 01:35:24
40K             0 days 03:05:33
Pace                    0:07:29
TotalSeconds            11133.0
HalfSeconds              5724.0
Name: 9462, dtype: object
Arsi
 Age                          31
M/F                           F
City                       Arsi
State                       NaN
Country                     ETH
Half            0 days 01:15:32
40K             0 days 02:21:56
Pace                    0:05:44
TotalSeconds             8516.0
HalfSeconds              4532.0
Name: F4, dtype: object
Arvada
 Age                          27
M/F                           M
City                     Arvada
State                        CO
Country                     USA
Half            0 days 01:24:19
40K             0 days 02:54:37
Pace                    0:07:05
TotalSeconds            10477.0
HalfSeconds              5059.0
Name: 1393, dtype: object
Arvika
 Age                          54
M/F                           M
City                     Arvika
State                       NaN
Country                     SWE
Half            0 days 01:49:51
40K             0 days 03:52:12
Pace                    0:09:22
TotalSeconds            13932.0
HalfSeconds              6591.0
Name: 16772, dtype: object
Asbury
 Age                          47
M/F                           M
City                     Asbury
State                        NJ
Country                     USA
Half            0 days 01:31:47
40K             0 days 03:16:17
Pace                    0:07:56
TotalSeconds            11777.0
HalfSeconds              5507.0
Name: 6578, dtype: object
Asbury Park
 Age                          33
M/F                           M
City                Asbury Park
State                        NJ
Country                     USA
Half            0 days 01:20:32
40K             0 days 02:44:10
Pace                    0:06:39
TotalSeconds             9850.0
HalfSeconds              4832.0
Name: 579, dtype: object
Asela
 Age                          28
M/F                           F
City                      Asela
State                       NaN
Country                     ETH
Half            0 days 01:15:32
40K             0 days 02:25:49
Pace                    0:05:54
TotalSeconds             8749.0
HalfSeconds              4532.0
Name: F15, dtype: object
Ashaway
 Age                          38
M/F                           M
City                    Ashaway
State                        RI
Country                     USA
Half            0 days 01:23:57
40K             0 days 02:39:02
Pace                    0:06:24
TotalSeconds             9542.0
HalfSeconds              5037.0
Name: 1028, dtype: object
Ashburn
 Age                          32
M/F                           M
City                    Ashburn
State                        VA
Country                     USA
Half            0 days 01:28:10
40K             0 days 02:50:56
Pace                    0:06:54
TotalSeconds            10256.0
HalfSeconds              5290.0
Name: 929, dtype: object
Ashburnham
 Age                          53
M/F                           M
City                 Ashburnham
State                        MA
Country                     USA
Half            0 days 02:13:33
40K             0 days 04:17:20
Pace                    0:10:20
TotalSeconds            15440.0
HalfSeconds              8013.0
Name: 26915, dtype: object
Ashby
 Age                          50
M/F                           F
City                      Ashby
State                        MA
Country                     USA
Half            0 days 02:35:20
40K             0 days 05:23:36
Pace                    0:12:59
TotalSeconds            19416.0
HalfSeconds              9320.0
Name: 28192, dtype: object
Asheville
 Age                          29
M/F                           M
City                  Asheville
State                        NC
Country                     USA
Half            0 days 01:21:55
40K             0 days 02:44:34
Pace                    0:06:38
TotalSeconds             9874.0
HalfSeconds              4915.0
Name: 1707, dtype: object
Ashland
 Age                          26
M/F                           F
City                    Ashland
State                        MA
Country                     USA
Half            0 days 01:20:10
40K             0 days 02:43:30
Pace                    0:06:42
TotalSeconds             9810.0
HalfSeconds              4810.0
Name: 1402, dtype: object
Ashtabula
 Age                          27
M/F                           M
City                  Ashtabula
State                        OH
Country                     USA
Half            0 days 01:30:39
40K             0 days 02:55:49
Pace                    0:07:10
TotalSeconds            10549.0
HalfSeconds              5439.0
Name: 3545, dtype: object
Askam In Furness
 Age                           44
M/F                            M
City            Askam In Furness
State                        NaN
Country                      GBR
Half             0 days 01:50:00
40K              0 days 03:52:47
Pace                     0:09:23
TotalSeconds             13967.0
HalfSeconds               6600.0
Name: 6124, dtype: object
Asnieres
 Age                          63
M/F                           M
City                   Asnieres
State                       NaN
Country                     FRA
Half            0 days 01:49:56
40K             0 days 04:12:14
Pace                    0:10:17
TotalSeconds            15134.0
HalfSeconds              6596.0
Name: 15178, dtype: object
Aspach Michelbach
 Age                            45
M/F                             M
City            Aspach Michelbach
State                         NaN
Country                       FRA
Half              0 days 01:29:04
40K               0 days 03:11:27
Pace                      0:07:47
TotalSeconds              11487.0
HalfSeconds                5344.0
Name: 31419, dtype: object
Aspen
 Age                          48
M/F                           M
City                      Aspen
State                        CO
Country                     USA
Half            0 days 01:33:30
40K             0 days 03:10:36
Pace                    0:07:46
TotalSeconds            11436.0
HalfSeconds              5610.0
Name: 8218, dtype: object
Asperg
 Age                          56
M/F                           M
City                     Asperg
State                       NaN
Country                     GER
Half            0 days 01:54:59
40K             0 days 03:36:59
Pace                    0:08:45
TotalSeconds            13019.0
HalfSeconds              6899.0
Name: 30920, dtype: object
Aspers
 Age                          73
M/F                           M
City                     Aspers
State                        PA
Country                     USA
Half            0 days 02:11:58
40K             0 days 04:39:38
Pace                    0:11:29
TotalSeconds            16778.0
HalfSeconds              7918.0
Name: 25804, dtype: object
Astoria
 Age                          35
M/F                           M
City                    Astoria
State                        NY
Country                     USA
Half            0 days 01:26:21
40K             0 days 02:49:21
Pace                    0:06:50
TotalSeconds            10161.0
HalfSeconds              5181.0
Name: 4692, dtype: object
Atascadero
 Age                          62
M/F                           M
City                 Atascadero
State                        CA
Country                     USA
Half            0 days 01:57:56
40K             0 days 04:11:18
Pace                    0:10:10
TotalSeconds            15078.0
HalfSeconds              7076.0
Name: 21819, dtype: object
Atascocita
 Age                          25
M/F                           F
City                 Atascocita
State                        TX
Country                     USA
Half            0 days 01:43:07
40K             0 days 03:37:20
Pace                    0:08:50
TotalSeconds            13040.0
HalfSeconds              6187.0
Name: 14709, dtype: object
Atchison
 Age                          35
M/F                           M
City                   Atchison
State                        KS
Country                     USA
Half            0 days 01:33:50
40K             0 days 03:18:43
Pace                    0:08:02
TotalSeconds            11923.0
HalfSeconds              5630.0
Name: 5070, dtype: object
Athens
 Age                          26
M/F                           M
City                     Athens
State                        GA
Country                     USA
Half            0 days 01:24:22
40K             0 days 02:41:16
Pace                    0:06:31
TotalSeconds             9676.0
HalfSeconds              5062.0
Name: 2254, dtype: object
Atherton
 Age                          23
M/F                           F
City                   Atherton
State                        CA
Country                     USA
Half            0 days 01:32:44
40K             0 days 03:07:14
Pace                    0:07:36
TotalSeconds            11234.0
HalfSeconds              5564.0
Name: 9376, dtype: object
Athlone
 Age                          39
M/F                           M
City                    Athlone
State                       NaN
Country                     IRL
Half            0 days 01:24:56
40K             0 days 02:45:45
Pace                    0:06:42
TotalSeconds             9945.0
HalfSeconds              5096.0
Name: 2216, dtype: object
Atizapan De Zaragoza
 Age                               40
M/F                                M
City            Atizapan De Zaragoza
State                            NaN
Country                          MEX
Half                 0 days 01:25:36
40K                  0 days 02:57:49
Pace                         0:07:09
TotalSeconds                 10669.0
HalfSeconds                   5136.0
Name: 1876, dtype: object
Atkinson
 Age                          35
M/F                           M
City                   Atkinson
State                        NH
Country                     USA
Half            0 days 01:31:07
40K             0 days 02:56:58
Pace                    0:07:10
TotalSeconds            10618.0
HalfSeconds              5467.0
Name: 5094, dtype: object
Atlacomulco, Edo. De Mexico
 Age                                      30
M/F                                       F
City            Atlacomulco, Edo. De Mexico
State                                   NaN
Country                                 MEX
Half                        0 days 01:42:09
40K                         0 days 03:30:05
Pace                                0:08:29
TotalSeconds                        12605.0
HalfSeconds                          6129.0
Name: 10571, dtype: object
Atlanta
 Age                          34
M/F                           M
City                    Atlanta
State                        GA
Country                     USA
Half            0 days 01:17:06
40K             0 days 02:32:23
Pace                    0:06:09
TotalSeconds             9143.0
HalfSeconds              4626.0
Name: 338, dtype: object
Atlantic Beach
 Age                          51
M/F                           M
City             Atlantic Beach
State                        FL
Country                     USA
Half            0 days 01:42:08
40K             0 days 03:25:05
Pace                    0:08:19
TotalSeconds            12305.0
HalfSeconds              6128.0
Name: 12309, dtype: object
Atlantic Highlands
 Age                             49
M/F                              F
City            Atlantic Highlands
State                           NJ
Country                        USA
Half               0 days 01:59:41
40K                0 days 03:59:28
Pace                       0:09:39
TotalSeconds               14368.0
HalfSeconds                 7181.0
Name: 22125, dtype: object
Atlantic Mine
 Age                          56
M/F                           M
City              Atlantic Mine
State                        MI
Country                     USA
Half            0 days 01:35:13
40K             0 days 03:06:19
Pace                    0:07:33
TotalSeconds            11179.0
HalfSeconds              5713.0
Name: 18953, dtype: object
Atmore
 Age                          24
M/F                           M
City                     Atmore
State                        AL
Country                     USA
Half            0 days 01:16:05
40K             0 days 02:23:37
Pace                    0:05:47
TotalSeconds             8617.0
HalfSeconds              4565.0
Name: 217, dtype: object
Atoka
 Age                          53
M/F                           F
City                      Atoka
State                        OK
Country                     USA
Half            0 days 01:58:14
40K             0 days 03:49:45
Pace                    0:09:16
TotalSeconds            13785.0
HalfSeconds              7094.0
Name: 24292, dtype: object
Attleboro
 Age                          29
M/F                           M
City                  Attleboro
State                        MA
Country                     USA
Half            0 days 01:29:21
40K             0 days 02:51:14
Pace                    0:06:54
TotalSeconds            10274.0
HalfSeconds              5361.0
Name: 3486, dtype: object
Auburn
 Age                          35
M/F                           M
City                     Auburn
State                        NY
Country                     USA
Half            0 days 01:14:34
40K             0 days 02:27:46
Pace                    0:05:59
TotalSeconds             8866.0
HalfSeconds              4474.0
Name: 154, dtype: object
Auburn Hills
 Age                          26
M/F                           F
City               Auburn Hills
State                        MI
Country                     USA
Half            0 days 01:37:21
40K             0 days 03:04:30
Pace                    0:07:25
TotalSeconds            11070.0
HalfSeconds              5841.0
Name: 10971, dtype: object
Auburndale
 Age                          55
M/F                           M
City                 Auburndale
State                        MA
Country                     USA
Half            0 days 01:32:52
40K             0 days 03:10:30
Pace                    0:07:44
TotalSeconds            11430.0
HalfSeconds              5572.0
Name: 5279, dtype: object
Auchenflower
 Age                          60
M/F                           F
City               Auchenflower
State                       NaN
Country                     AUS
Half            0 days 02:33:24
40K             0 days 05:12:44
Pace                    0:12:42
TotalSeconds            18764.0
HalfSeconds              9204.0
Name: 31596, dtype: object
Auckland
 Age                          25
M/F                           M
City                   Auckland
State                       NaN
Country                     NZL
Half            0 days 01:12:31
40K             0 days 02:24:55
Pace                    0:05:53
TotalSeconds             8695.0
HalfSeconds              4351.0
Name: 124, dtype: object
Audubon
 Age                          30
M/F                           F
City                    Audubon
State                        NJ
Country                     USA
Half            0 days 01:39:48
40K             0 days 03:17:29
Pace                    0:07:58
TotalSeconds            11849.0
HalfSeconds              5988.0
Name: 12591, dtype: object
Augres
 Age                          45
M/F                           F
City                     Augres
State                        MI
Country                     USA
Half            0 days 02:21:15
40K             0 days 04:52:13
Pace                    0:11:50
TotalSeconds            17533.0
HalfSeconds              8475.0
Name: 30732, dtype: object
Augusta
 Age                          28
M/F                           M
City                    Augusta
State                        GA
Country                     USA
Half            0 days 01:22:49
40K             0 days 02:53:06
Pace                    0:07:00
TotalSeconds            10386.0
HalfSeconds              4969.0
Name: 1246, dtype: object
Augustusburg
 Age                          44
M/F                           F
City               Augustusburg
State                       NaN
Country                     GER
Half            0 days 02:01:38
40K             0 days 04:03:14
Pace                    0:09:49
TotalSeconds            14594.0
HalfSeconds              7298.0
Name: 31792, dtype: object
Aulon
 Age                          52
M/F                           F
City                      Aulon
State                       NaN
Country                     FRA
Half            0 days 02:17:34
40K             0 days 04:51:10
Pace                    0:11:42
TotalSeconds            17470.0
HalfSeconds              8254.0
Name: 25070, dtype: object
Aurora
 Age                          43

Bad Homburg
 Age                          56
M/F                           F
City                Bad Homburg
State                       NaN
Country                     GER
Half            0 days 02:20:45
40K             0 days 04:37:46
Pace                    0:11:15
TotalSeconds            16666.0
HalfSeconds              8445.0
Name: 31032, dtype: object
Bad Lauterberg
 Age                          59
M/F                           M
City             Bad Lauterberg
State                       NaN
Country                     GER
Half            0 days 01:35:07
40K             0 days 03:14:47
Pace                    0:07:54
TotalSeconds            11687.0
HalfSeconds              5707.0
Name: 11180, dtype: object
Bad Soden
 Age                          44
M/F                           M
City                  Bad Soden
State                       NaN
Country                     GER
Half            0 days 02:20:27
40K             0 days 04:46:44
Pace                    0:11:32
TotalSeconds            17204.0
HalfSeconds              8427.0
Name: 30960, dtype: object
Bad Zwischenahn
 Age                          50
M/F                           M
City            Bad Zwischenahn
State                       NaN
Country                     GER
Half            0 days 01:59:49
40K             0 days 04:02:01
Pace                    0:09:47
TotalSeconds            14521.0
HalfSeconds              7189.0
Name: 31038, dtype: object
Badalona
 Age                          39
M/F                           M
City                   Badalona
State                       NaN
Country                     ESP
Half            0 days 01:26:24
40K             0 days 02:55:06
Pace                    0:07:08
TotalSeconds            10506.0
HalfSeconds              5184.0
Name: 1526, dtype: object
Bade Dist., Taoyuan City
 Age                                   53
M/F                                    M
City            Bade Dist., Taoyuan City
State                                NaN
Country                              TWN
Half                     0 days 01:36:37
40K                      0 days 03:21:33
Pace                             0:08:13
TotalSeconds                     12093.0
HalfSeconds                       5797.0
Name: 5874, dtype: object
Baden
 Age                          38
M/F                           M
City                      Baden
State                        ON
Country                     CAN
Half            0 days 01:26:58
40K             0 days 02:55:09
Pace                    0:07:06
TotalSeconds            10509.0
HalfSeconds              5218.0
Name: 1922, dtype: object
Badhoevedorp
 Age                          45
M/F                           M
City               Badhoevedorp
State                       NaN
Country                     NED
Half            0 days 01:32:00
40K             0 days 03:03:05
Pace                    0:07:25
TotalSeconds            10985.0
HalfSeconds              5520.0
Name: 5888, dtype: object
Baerums Verk
 Age                          52
M/F                           M
City               Baerums Verk
State                       NaN
Country                     NOR
Half            0 days 02:30:04
40K             0 days 04:57:32
Pace                    0:12:05
TotalSeconds            17852.0
HalfSeconds              9004.0
Name: 31434, dtype: object
Baetterkinden
 Age                          50
M/F                           M
City              Baetterkinden
State                       NaN
Country                     SUI
Half            0 days 01:35:48
40K             0 days 03:17:05
Pace                    0:07:59
TotalSeconds            11825.0
HalfSeconds              5748.0
Name: 8328, dtype: object
Baie-Comeau
 Age                          34
M/F                           F
City                Baie-Comeau
State                        QC
Country                     CAN
Half            0 days 01:45:04
40K             0 days 03:27:42
Pace                    0:08:23
TotalSeconds            12462.0
HalfSeconds              6304.0
Name: 11494, dtype: object
Baie-D'Urfe
 Age                          49
M/F                           M
City                Baie-D'Urfe
State                        QC
Country                     CAN
Half            0 days 01:43:38
40K             0 days 03:18:23
Pace                    0:07:59
TotalSeconds            11903.0
HalfSeconds              6218.0
Name: 12438, dtype: object
Bailey
 Age                          59
M/F                           M
City                     Bailey
State                        CO
Country                     USA
Half            0 days 01:36:09
40K             0 days 03:10:45
Pace                    0:07:43
TotalSeconds            11445.0
HalfSeconds              5769.0
Name: 5720, dtype: object
Baileys Harbor
 Age                          41
M/F                           F
City             Baileys Harbor
State                        WI
Country                     USA
Half            0 days 01:55:52
40K             0 days 03:46:45
Pace                    0:09:06
TotalSeconds            13605.0
HalfSeconds              6952.0
Name: 21821, dtype: object
Bainbridge
 Age                          30
M/F                           M
City                 Bainbridge
State                        OH
Country                     USA
Half            0 days 01:27:53
40K             0 days 02:50:26
Pace                    0:06:53
TotalSeconds            10226.0
HalfSeconds              5273.0
Name: 3697, dtype: object
Bainbridge Island
 Age                            45
M/F                             M
City            Bainbridge Island
State                          WA
Country                       USA
Half              0 days 01:28:36
40K               0 days 02:52:19
Pace                      0:06:58
TotalSeconds              10339.0
HalfSeconds                5316.0
Name: 3902, dtype: object
Baker City
 Age                          46
M/F                           M
City                 Baker City
State                        OR
Country                     USA
Half            0 days 01:25:46
40K             0 days 02:57:06
Pace                    0:07:12
TotalSeconds            10626.0
HalfSeconds              5146.0
Name: 1924, dtype: object
Bakersfield
 Age                          52
M/F                           M
City                Bakersfield
State                        CA
Country                     USA
Half            0 days 01:36:55
40K             0 days 03:12:24
Pace                    0:07:48
TotalSeconds            11544.0
HalfSeconds              5815.0
Name: 10819, dtype: object
Bala Cynwyd
 Age                          68
M/F                           M
City                Bala Cynwyd
State                        PA
Country                     USA
Half            0 days 01:32:43
40K             0 days 02:59:26
Pace                    0:07:15
TotalSeconds            10766.0
HalfSeconds              5563.0
Name: 5938, dtype: object
Baldwinsville
 Age                          48
M/F                           F
City              Baldwinsville
State                        NY
Country                     USA
Half            0 days 01:42:25
40K             0 days 03:21:27
Pace                    0:08:08
TotalSeconds            12087.0
HalfSeconds              6145.0
Name: 13201, dtype: object
Balfurya
 Age                          28
M/F                           M
City                   Balfurya
State                       NaN
Country                     ISR
Half            0 days 01:32:03
40K             0 days 03:08:25
Pace                    0:07:38
TotalSeconds            11305.0
HalfSeconds              5523.0
Name: 3018, dtype: object
Balgowlah Heights
 Age                            42
M/F                             F
City            Balgowlah Heights
State                         NaN
Country                       AUS
Half              0 days 01:58:01
40K               0 days 03:45:25
Pace                      0:09:02
TotalSeconds              13525.0
HalfSeconds                7081.0
Name: 20471, dtype: object
Ball Ground
 Age                          22
M/F                           M
City                Ball Ground
State                        GA
Country                     USA
Half            0 days 01:23:23
40K             0 days 02:48:27
Pace                    0:06:47
TotalSeconds            10107.0
HalfSeconds              5003.0
Name: 496, dtype: object
Ballina
 Age                          43
M/F                           F
City                    Ballina
State                       NaN
Country                     IRL
Half            0 days 02:15:32
40K             0 days 04:29:46
Pace                    0:10:50
TotalSeconds            16186.0
HalfSeconds              8132.0
Name: 19715, dtype: object
Balloch
 Age                          38
M/F                           M
City                    Balloch
State                       NaN
Country                     GBR
Half            0 days 01:32:01
40K             0 days 03:04:31
Pace                    0:07:27
TotalSeconds            11071.0
HalfSeconds              5521.0
Name: 28667, dtype: object
Ballston Lake
 Age                          49
M/F                           M
City              Ballston Lake
State                        NY
Country                     USA
Half            0 days 01:39:26
40K             0 days 03:13:18
Pace                    0:07:48
TotalSeconds            11598.0
HalfSeconds              5966.0
Name: 11356, dtype: object
Ballwin
 Age                          36
M/F                           M
City                    Ballwin
State                        MO
Country                     USA
Half            0 days 01:21:19
40K             0 days 02:38:55
Pace                    0:06:25
TotalSeconds             9535.0
HalfSeconds              4879.0
Name: 721, dtype: object
Balmain East
 Age                          51
M/F                           M
City               Balmain East
State                       NaN
Country                     AUS
Half            0 days 01:49:00
40K             0 days 03:35:27
Pace                    0:08:41
TotalSeconds            12927.0
HalfSeconds              6540.0
Name: 13902, dtype: object
Baltimore
 Age                          30
M/F                           M
City                  Baltimore
State                        MD
Country                     USA
Half            0 days 01:20:23
40K             0 days 02:37:02
Pace                    0:06:20
TotalSeconds             9422.0
HalfSeconds              4823.0
Name: 1430, dtype: object
Baltimre
 Age                          45
M/F                           M
City                   Baltimre
State                        MD
Country                     USA
Half            0 days 01:37:55
40K             0 days 03:23:00
Pace                    0:08:15
TotalSeconds            12180.0
HalfSeconds              5875.0
Name: 7153, dtype: object
Bandon
 Age                          41
M/F                           F
City                     Bandon
State                        OR
Country                     USA
Half            0 days 01:47:15
40K             0 days 03:29:27
Pace                    0:08:28
TotalSeconds            12567.0
HalfSeconds              6435.0
Name: 20951, dtype: object
Bangalore
 Age                          57
M/F                           M
City                  Bangalore
State                       NaN
Country                     IND
Half            0 days 01:39:42
40K             0 days 03:24:43
Pace                    0:08:18
TotalSeconds            12283.0
HalfSeconds              5982.0
Name: 17820, dtype: object
Bangor
 Age                          49
M/F                           M
City                     Bangor
State                        PA
Country                     USA
Half            0 days 01:42:43
40K             0 days 03:28:32
Pace                    0:08:27
TotalSeconds            12512.0
HalfSeconds              6163.0
Name: 9941, dtype: object
Banks
 Age                          63
M/F                           M
City                      Banks
State                        OR
Country                     USA
Half            0 days 02:02:44
40K             0 days 04:33:34
Pace                    0:11:06
TotalSeconds            16414.0
HalfSeconds              7364.0
Name: 21971, dtype: object
Bannockburn
 Age                          33
M/F                           M
City                Bannockburn
State                        IL
Country                     USA
Half            0 days 01:29:57
40K             0 days 02:54:24
Pace                    0:07:03
TotalSeconds            10464.0
HalfSeconds              5397.0
Name: 4412, dtype: object
Bantam
 Age                          52
M/F                           M
City                     Bantam
State                        CT
Country                     USA
Half            0 days 01:39:06
40K             0 days 03:37:11
Pace                    0:08:46
TotalSeconds            13031.0
HalfSeconds              5946.0
Name: 9555, dtype: object
Bar Harbor
 Age                          38
M/F                           F
City                 Bar Harbor
State                        ME
Country                     USA
Half            0 days 01:34:38
40K             0 days 03:07:06
Pace                    0:07:34
TotalSeconds            11226.0
HalfSeconds              5678.0
Name: 6362, dtype: object
Barbastro
 Age                          48
M/F                           M
City                  Barbastro
State                       NaN
Country                     ESP
Half            0 days 01:29:59
40K             0 days 02:55:36
Pace                    0:07:05
TotalSeconds            10536.0
HalfSeconds              5399.0
Name: 3353, dtype: object
Barcelona
 Age                          45
M/F                           M
City                  Barcelona
State                       NaN
Country                     ESP
Half            0 days 01:36:25
40K             0 days 03:16:28
Pace                    0:07:57
TotalSeconds            11788.0
HalfSeconds              5785.0
Name: 6814, dtype: object
Barcelonnette
 Age                          36
M/F                           M
City              Barcelonnette
State                       NaN
Country                     FRA
Half            0 days 01:21:29
40K             0 days 02:40:02
Pace                    0:06:29
TotalSeconds             9602.0
HalfSeconds              4889.0
Name: 1729, dtype: object
Barendrecht
 Age                          55
M/F                           M
City                Barendrecht
State                       NaN
Country                     NED
Half            0 days 01:49:38
40K             0 days 03:53:21
Pace                    0:09:27
TotalSeconds            14001.0
HalfSeconds              6578.0
Name: 14762, dtype: object
Bargersville
 Age                          55
M/F                           M
City               Bargersville
State                        IN
Country                     USA
Half            0 days 01:49:02
40K             0 days 03:28:32
Pace                    0:08:23
TotalSeconds            12512.0
HalfSeconds              6542.0
Name: 10783, dtype: object
Bari
 Age                          50
M/F                           M
City                       Bari
State                       NaN
Country                     ITA
Half            0 days 01:36:49
40K             0 days 03:16:32
Pace                    0:08:01
TotalSeconds            11792.0
HalfSeconds              5809.0
Name: 4639, dtype: object
Barleben
 Age                          51
M/F                           M
City                   Barleben
State                       NaN
Country                     GER
Half            0 days 02:14:29
40K             0 days 04:30:13
Pace                    0:10:54
TotalSeconds            16213.0
HalfSeconds              8069.0
Name: 31878, dtype: object
Barnegat
 Age                          39
M/F                           F
City                   Barnegat
State                        NJ
Country                     USA
Half            0 days 01:46:35
40K             0 days 03:32:17
Pace                    0:08:34
TotalSeconds            12737.0
HalfSeconds              6395.0
Name: 20319, dtype: object
Barnesville
 Age                          29
M/F                           M
City                Barnesville
State                        OH
Country                     USA
Half            0 days 01:24:01
40K             0 days 02:43:14
Pace                    0:06:35
TotalSeconds             9794.0
HalfSeconds              5041.0
Name: 1857, dtype: object
Barnhart
 Age                          50
M/F                           M
City                   Barnhart
State                        MO
Country                     USA
Half            0 days 01:44:43
40K             0 days 03:20:23
Pace                    0:08:04
TotalSeconds            12023.0
HalfSeconds              6283.0
Name: 9110, dtype: object
Barnstable
 Age                          56
M/F                           F
City                 Barnstable
State                        MA
Country                     USA
Half            0 days 02:02:01
40K             0 days 03:59:30
Pace                    0:09:38
TotalSeconds            14370.0
HalfSeconds              7321.0
Name: 25530, dtype: object
Barranquilla
 Age                          65
M/F                           M
City               Barranquilla
State                       NaN
Country                     COL
Half            0 days 01:56:35
40K             0 days 04:14:09
Pace                    0:10:19
TotalSeconds            15249.0
HalfSeconds              6995.0
Name: 25425, dtype: object
Barranquitas
 Age                          43
M/F                           M
City               Barranquitas
State                        PR
Country                     USA
Half            0 days 01:32:35
40K             0 days 03:00:02
Pace                    0:07:21
TotalSeconds            10802.0
HalfSeconds              5555.0
Name: 8228, dtype: object
Barre
 Age                          48
M/F                           M
City                      Barre
State                        MA
Country                     USA
Half            0 days 01:42:02
40K             0 days 03:23:52
Pace                    0:08:15
TotalSeconds            12232.0
HalfSeconds              6122.0
Name: 30645, dtype: object
Barreiro
 Age                          42
M/F                           M
City                   Barreiro
State                       NaN
Country                     POR
Half            0 days 01:29:15
40K             0 days 03:00:44
Pace                    0:07:17
TotalSeconds            10844.0
HalfSeconds              5355.0
Name: 2566, dtype: object
Barrie
 Age                          48
M/F                           M
City                     Barrie
State                        ON
Country                     CAN
Half            0 days 01:26:00
40K             0 days 03:01:13
Pace                    0:07:21
TotalSeconds            10873.0
HalfSeconds              5160.0
Name: 1561, dtype: object
Barriefield
 Age                          65
M/F                           M
City                Barriefield
State                        ON
Country                     CAN
Half            0 days 01:52:58
40K             0 days 03:41:19
Pace                    0:08:55
TotalSeconds            13279.0
HalfSeconds              6778.0
Name: 22261, dtype: object
Barriere
 Age                          50
M/F                           F
City                   Barriere
State                        BC
Country                     CAN
Half            0 days 02:00:48
40K             0 days 04:01:19
Pace                    0:09:45
TotalSeconds            14479.0
HalfSeconds              7248.0
Name: 24705, dtype: object
Barrington
 Age                          29
M/F                           M
City                 Barrington
State                        IL

Bay Shore
 Age                          27
M/F                           F
City                  Bay Shore
State                        NY
Country                     USA
Half            0 days 01:36:33
40K             0 days 03:05:42
Pace                    0:07:28
TotalSeconds            11142.0
HalfSeconds              5793.0
Name: 11974, dtype: object
Bay Village
 Age                          41
M/F                           M
City                Bay Village
State                        OH
Country                     USA
Half            0 days 01:26:12
40K             0 days 02:57:01
Pace                    0:07:15
TotalSeconds            10621.0
HalfSeconds              5172.0
Name: 2885, dtype: object
Bayport
 Age                          30
M/F                           M
City                    Bayport
State                        NY
Country                     USA
Half            0 days 01:32:30
40K             0 days 03:06:49
Pace                    0:07:36
TotalSeconds            11209.0
HalfSeconds              5550.0
Name: 2535, dtype: object
Bayreuth
 Age                          50
M/F                           M
City                   Bayreuth
State                       NaN
Country                     GER
Half            0 days 01:53:34
40K             0 days 03:46:05
Pace                    0:09:09
TotalSeconds            13565.0
HalfSeconds              6814.0
Name: 6263, dtype: object
Bayside
 Age                          35
M/F                           M
City                    Bayside
State                        WI
Country                     USA
Half            0 days 01:28:40
40K             0 days 02:56:40
Pace                    0:07:13
TotalSeconds            10600.0
HalfSeconds              5320.0
Name: 1853, dtype: object
Baytown
 Age                          53
M/F                           F
City                    Baytown
State                        TX
Country                     USA
Half            0 days 01:56:26
40K             0 days 03:43:30
Pace                    0:09:02
TotalSeconds            13410.0
HalfSeconds              6986.0
Name: 24159, dtype: object
Bayville
 Age                          41
M/F                           F
City                   Bayville
State                        NY
Country                     USA
Half            0 days 01:38:18
40K             0 days 03:20:16
Pace                    0:08:07
TotalSeconds            12016.0
HalfSeconds              5898.0
Name: 5050, dtype: object
Beach City
 Age                          45
M/F                           F
City                 Beach City
State                        TX
Country                     USA
Half            0 days 01:56:55
40K             0 days 03:49:14
Pace                    0:09:15
TotalSeconds            13754.0
HalfSeconds              7015.0
Name: 23275, dtype: object
Beach Lake
 Age                          42
M/F                           F
City                 Beach Lake
State                        PA
Country                     USA
Half            0 days 01:49:34
40K             0 days 03:34:27
Pace                    0:08:39
TotalSeconds            12867.0
HalfSeconds              6574.0
Name: 17602, dtype: object
Beachwood
 Age                          27
M/F                           F
City                  Beachwood
State                        OH
Country                     USA
Half            0 days 01:41:08
40K             0 days 03:11:59
Pace                    0:07:44
TotalSeconds            11519.0
HalfSeconds              6068.0
Name: 7270, dtype: object
Beacon
 Age                          41
M/F                           M
City                     Beacon
State                        NY
Country                     USA
Half            0 days 01:18:29
40K             0 days 02:37:39
Pace                    0:06:24
TotalSeconds             9459.0
HalfSeconds              4709.0
Name: 915, dtype: object
Beaconsfield
 Age                          57
M/F                           M
City               Beaconsfield
State                        QC
Country                     CAN
Half            0 days 01:35:23
40K             0 days 03:10:37
Pace                    0:07:44
TotalSeconds            11437.0
HalfSeconds              5723.0
Name: 7678, dtype: object
Beamsville
 Age                          30
M/F                           F
City                 Beamsville
State                        ON
Country                     CAN
Half            0 days 01:35:32
40K             0 days 03:04:46
Pace                    0:07:26
TotalSeconds            11086.0
HalfSeconds              5732.0
Name: 12971, dtype: object
Bear
 Age                          33
M/F                           M
City                       Bear
State                        DE
Country                     USA
Half            0 days 01:28:56
40K             0 days 02:49:36
Pace                    0:06:50
TotalSeconds            10176.0
HalfSeconds              5336.0
Name: 3869, dtype: object
Beaufort
 Age                          28
M/F                           F
City                   Beaufort
State                        SC
Country                     USA
Half            0 days 01:25:34
40K             0 days 02:48:41
Pace                    0:06:48
TotalSeconds            10121.0
HalfSeconds              5134.0
Name: 1496, dtype: object
Beauharnois
 Age                          58
M/F                           M
City                Beauharnois
State                        QC
Country                     CAN
Half            0 days 01:42:10
40K             0 days 03:24:27
Pace                    0:08:15
TotalSeconds            12267.0
HalfSeconds              6130.0
Name: 10294, dtype: object
Beaumont
 Age                          32
M/F                           F
City                   Beaumont
State                        TX
Country                     USA
Half            0 days 01:48:23
40K             0 days 03:33:57
Pace                    0:08:38
TotalSeconds            12837.0
HalfSeconds              6503.0
Name: 18287, dtype: object
Beaupre
 Age                          50
M/F                           M
City                    Beaupre
State                        QC
Country                     CAN
Half            0 days 01:34:04
40K             0 days 03:05:24
Pace                    0:07:32
TotalSeconds            11124.0
HalfSeconds              5644.0
Name: 8046, dtype: object
Beaux Arts
 Age                          51
M/F                           F
City                 Beaux Arts
State                        WA
Country                     USA
Half            0 days 01:54:32
40K             0 days 03:40:27
Pace                    0:08:53
TotalSeconds            13227.0
HalfSeconds              6872.0
Name: 24677, dtype: object
Beaver
 Age                          46
M/F                           F
City                     Beaver
State                        PA
Country                     USA
Half            0 days 01:45:45
40K             0 days 03:29:20
Pace                    0:08:28
TotalSeconds            12560.0
HalfSeconds              6345.0
Name: 17936, dtype: object
Beaver Bank
 Age                          59
M/F                           M
City                Beaver Bank
State                        NS
Country                     CAN
Half            0 days 01:49:16
40K             0 days 03:33:19
Pace                    0:08:38
TotalSeconds            12799.0
HalfSeconds              6556.0
Name: 18975, dtype: object
Beaver Dam
 Age                          59
M/F                           F
City                 Beaver Dam
State                        WI
Country                     USA
Half            0 days 02:01:35
40K             0 days 04:04:05
Pace                    0:09:53
TotalSeconds            14645.0
HalfSeconds              7295.0
Name: 21257, dtype: object
Beavercreek
 Age                          39
M/F                           M
City                Beavercreek
State                        OH
Country                     USA
Half            0 days 01:19:31
40K             0 days 02:43:04
Pace                    0:06:37
TotalSeconds             9784.0
HalfSeconds              4771.0
Name: 340, dtype: object
Beaverdam
 Age                          46
M/F                           M
City                  Beaverdam
State                        VA
Country                     USA
Half            0 days 01:47:51
40K             0 days 03:38:24
Pace                    0:08:48
TotalSeconds            13104.0
HalfSeconds              6471.0
Name: 11243, dtype: object
Beaverton
 Age                          47
M/F                           M
City                  Beaverton
State                        OR
Country                     USA
Half            0 days 01:30:28
40K             0 days 02:57:03
Pace                    0:07:09
TotalSeconds            10623.0
HalfSeconds              5428.0
Name: 8417, dtype: object
Becancour
 Age                          33
M/F                           M
City                  Becancour
State                        QC
Country                     CAN
Half            0 days 01:29:17
40K             0 days 02:57:35
Pace                    0:07:10
TotalSeconds            10655.0
HalfSeconds              5357.0
Name: 3822, dtype: object
Bedford
 Age                          32
M/F                           M
City                    Bedford
State                        MA
Country                     USA
Half            0 days 01:24:46
40K             0 days 02:41:47
Pace                    0:06:32
TotalSeconds             9707.0
HalfSeconds              5086.0
Name: 420, dtype: object
Bedford Corners
 Age                          44
M/F                           M
City            Bedford Corners
State                        NY
Country                     USA
Half            0 days 01:59:52
40K             0 days 03:47:20
Pace                    0:09:05
TotalSeconds            13640.0
HalfSeconds              7192.0
Name: 28946, dtype: object
Bedford Hills
 Age                          52
M/F                           F
City              Bedford Hills
State                        NY
Country                     USA
Half            0 days 02:21:56
40K             0 days 04:42:16
Pace                    0:11:25
TotalSeconds            16936.0
HalfSeconds              8516.0
Name: 27235, dtype: object
Bedminster
 Age                          58
M/F                           M
City                 Bedminster
State                        NJ
Country                     USA
Half            0 days 02:05:43
40K             0 days 03:57:20
Pace                    0:09:29
TotalSeconds            14240.0
HalfSeconds              7543.0
Name: 14933, dtype: object
Bee Cave
 Age                          39
M/F                           M
City                   Bee Cave
State                        TX
Country                     USA
Half            0 days 01:29:06
40K             0 days 03:00:02
Pace                    0:07:20
TotalSeconds            10802.0
HalfSeconds              5346.0
Name: 6931, dtype: object
Beechville
 Age                          38
M/F                           F
City                 Beechville
State                        NS
Country                     CAN
Half            0 days 01:38:55
40K             0 days 03:15:36
Pace                    0:07:55
TotalSeconds            11736.0
HalfSeconds              5935.0
Name: 10249, dtype: object
Beeton
 Age                          36
M/F                           M
City                     Beeton
State                        ON
Country                     CAN
Half            0 days 01:25:42
40K             0 days 02:46:26
Pace                    0:06:43
TotalSeconds             9986.0
HalfSeconds              5142.0
Name: 5848, dtype: object
Beijiing
 Age                          56
M/F                           M
City                   Beijiing
State                       NaN
Country                     CHN
Half            0 days 01:39:33
40K             0 days 03:35:37
Pace                    0:08:48
TotalSeconds            12937.0
HalfSeconds              5973.0
Name: 13408, dtype: object
Beijing
 Age                          50
M/F                           M
City                    Beijing
State                       NaN
Country                     CHN
Half            0 days 01:25:22
40K             0 days 02:47:18
Pace                    0:06:44
TotalSeconds            10038.0
HalfSeconds              5122.0
Name: 2166, dtype: object
Beijing,P.R.
 Age                          43
M/F                           M
City               Beijing,P.R.
State                       NaN
Country                     CHN
Half            0 days 01:29:53
40K             0 days 03:12:49
Pace                    0:07:49
TotalSeconds            11569.0
HalfSeconds              5393.0
Name: 4670, dtype: object
Bekoji
 Age                          28
M/F                           F
City                     Bekoji
State                       NaN
Country                     ETH
Half            0 days 01:15:48
40K             0 days 02:33:51
Pace                    0:06:13
TotalSeconds             9231.0
HalfSeconds              4548.0
Name: F2, dtype: object
Bel Air
 Age                          39
M/F                           M
City                    Bel Air
State                        MD
Country                     USA
Half            0 days 01:25:03
40K             0 days 02:47:04
Pace                    0:06:45
TotalSeconds            10024.0
HalfSeconds              5103.0
Name: 2000, dtype: object
Belchertown
 Age                          31
M/F                           F
City                Belchertown
State                        MA
Country                     USA
Half            0 days 01:51:36
40K             0 days 03:39:00
Pace                    0:08:49
TotalSeconds            13140.0
HalfSeconds              6696.0
Name: 17011, dtype: object
Belfast
 Age                          52
M/F                           M
City                    Belfast
State                       NaN
Country                     GBR
Half            0 days 01:44:12
40K             0 days 03:22:34
Pace                    0:08:09
TotalSeconds            12154.0
HalfSeconds              6252.0
Name: 13569, dtype: object
Belfast, N Ireland
 Age                             41
M/F                              F
City            Belfast, N Ireland
State                          NaN
Country                        GBR
Half               0 days 01:53:04
40K                0 days 03:39:01
Pace                       0:08:50
TotalSeconds               13141.0
HalfSeconds                 6784.0
Name: 31762, dtype: object
Belgrade Srbija
 Age                          49
M/F                           M
City            Belgrade Srbija
State                       NaN
Country                     SRB
Half            0 days 01:55:45
40K             0 days 03:53:32
Pace                    0:09:28
TotalSeconds            14012.0
HalfSeconds              6945.0
Name: 31767, dtype: object
Bell Gardens
 Age                          53
M/F                           M
City               Bell Gardens
State                        CA
Country                     USA
Half            0 days 01:21:12
40K             0 days 02:42:43
Pace                    0:06:35
TotalSeconds             9763.0
HalfSeconds              4872.0
Name: 836, dtype: object
Bella Vista
 Age                          51
M/F                           M
City                Bella Vista
State                       NaN
Country                     AUS
Half            0 days 01:40:45
40K             0 days 03:27:52
Pace                    0:08:24
TotalSeconds            12472.0
HalfSeconds              6045.0
Name: 10100, dtype: object
Bellaire
 Age                          40
M/F                           M
City                   Bellaire
State                        TX
Country                     USA
Half            0 days 01:32:56
40K             0 days 03:08:12
Pace                    0:07:36
TotalSeconds            11292.0
HalfSeconds              5576.0
Name: 6566, dtype: object
Belle Mead
 Age                          36
M/F                           F
City                 Belle Mead
State                        NJ
Country                     USA
Half            0 days 01:54:31
40K             0 days 03:52:07
Pace                    0:09:24
TotalSeconds            13927.0
HalfSeconds              6871.0
Name: 17584, dtype: object
Belle River
 Age                          40
M/F                           M
City                Belle River
State                        ON
Country                     CAN
Half            0 days 01:35:10
40K             0 days 03:25:42
Pace                    0:08:20
TotalSeconds            12342.0
HalfSeconds              5710.0
Name: 8505, dtype: object
Belleair
 Age                          47
M/F                           M
City                   Belleair
State                        FL
Country                     USA
Half            0 days 01:42:20
40K             0 days 03:24:40
Pace                    0:08:17
TotalSeconds            12280.0
HalfSeconds              6140.0
Name: 9439, dtype: object
Bellefonte
 Age                          29
M/F                           M
City                 Bellefonte
State                        PA
Country                     USA
Half            0 days 01:23:37
40K             0 days 02:47:33
Pace                    0:06:47
TotalSeconds            10053.0
HalfSeconds              5017.0
Name: 4394, dtype: object
Belleville
 Age                          42
M/F                           M
City                 Belleville
State                        ON
Country                     CAN
Half            0 days 01:29:47
40K             0 days 02:51:50
Pace                    0:06:57
TotalSeconds            10310.0
HalfSeconds              5387.0
Name: 8353, dtype: object
Bellevue
 Age                          36
M/F                           M
City                   Bellevue
State                        WA
Country                     USA
Half            0 days 01:31:27
40K             0 days 02:50:27
Pace                    0:06:50
TotalSeconds            10227.0
HalfSeconds              5487.0
Name: 2123, dtype: object
Bellingham
 Age                          45
M/F                           F
City                 Bellingham
State                        MA
Country                     USA
Half            0 days 01:39:42
40K             0 days 03:15:10
Pace                    0:07:53
TotalSeconds            11710.0
HalfSeconds              5982.0
Name: 13499, dtype: object
Bellport
 Age                          52
M/F                           F
City                   Bellport
State                        NY
Country                     USA
Half            0 days 01:42:16
40K             0 days 03:24:44
Pace                    0:08:15
TotalSeconds            12284.0
HalfSeconds              6136.0
Name: 17092, dtype: object
Belluno
 Age                          48
M/F                           M
City                    Belluno
State                       NaN
Country                     ITA
Half            0 days 01:10:45
40K             0 days 02:19:33
Pace                    0:05:38
TotalSeconds             8373.0
HalfSeconds              4245.0
Name: 75, dtype: object
Belmont
 Age                          24
M/F                           M
City                    Belmont
State                        NH
Country                     USA
Half            0 days 01:22:26
40K             0 days 02:43:28
Pace                    0:06:36
TotalSeconds             9808.0
HalfSeconds              4946.0
Name: 777, dtype: object
Belo Horizonte
 Age                          29
M/F                           M
City             Belo Horizonte
State                       NaN
Country                     BRA
Half            0 days 01:28:43
40K             0 days 02:50:58
Pace                    0:06:53
TotalSeconds            10258.0

Bensenville
 Age                          36
M/F                           M
City                Bensenville
State                        IL
Country                     USA
Half            0 days 01:24:26
40K             0 days 02:50:35
Pace                    0:06:53
TotalSeconds            10235.0
HalfSeconds              5066.0
Name: 1145, dtype: object
Bensonville
 Age                          39
M/F                           M
City                Bensonville
State                        IL
Country                     USA
Half            0 days 01:26:07
40K             0 days 02:51:12
Pace                    0:06:56
TotalSeconds            10272.0
HalfSeconds              5167.0
Name: 5658, dtype: object
Benton
 Age                          39
M/F                           M
City                     Benton
State                        KY
Country                     USA
Half            0 days 01:36:45
40K             0 days 03:12:09
Pace                    0:07:45
TotalSeconds            11529.0
HalfSeconds              5805.0
Name: 6320, dtype: object
Bentonville
 Age                          34
M/F                           M
City                Bentonville
State                        AR
Country                     USA
Half            0 days 01:24:02
40K             0 days 02:45:00
Pace                    0:06:41
TotalSeconds             9900.0
HalfSeconds              5042.0
Name: 2195, dtype: object
Berea
 Age                          34
M/F                           M
City                      Berea
State                        OH
Country                     USA
Half            0 days 01:22:26
40K             0 days 02:41:57
Pace                    0:06:32
TotalSeconds             9717.0
HalfSeconds              4946.0
Name: 577, dtype: object
Bergen Nh
 Age                          54
M/F                           M
City                  Bergen Nh
State                       NaN
Country                     NED
Half            0 days 01:46:51
40K             0 days 03:40:11
Pace                    0:08:55
TotalSeconds            13211.0
HalfSeconds              6411.0
Name: 14537, dtype: object
Bergenfield
 Age                          47
M/F                           M
City                Bergenfield
State                        NJ
Country                     USA
Half            0 days 01:35:28
40K             0 days 03:17:56
Pace                    0:08:01
TotalSeconds            11876.0
HalfSeconds              5728.0
Name: 9585, dtype: object
Bergschenhoek
 Age                          45
M/F                           M
City              Bergschenhoek
State                       NaN
Country                     NED
Half            0 days 01:38:02
40K             0 days 03:26:37
Pace                    0:08:20
TotalSeconds            12397.0
HalfSeconds              5882.0
Name: 8936, dtype: object
Berkel En Rodenrijs
 Age                              40
M/F                               M
City            Berkel En Rodenrijs
State                           NaN
Country                         NED
Half                0 days 01:36:38
40K                 0 days 03:10:18
Pace                        0:07:40
TotalSeconds                11418.0
HalfSeconds                  5798.0
Name: 7356, dtype: object
Berkeley
 Age                          28
M/F                           M
City                   Berkeley
State                        CA
Country                     USA
Half            0 days 01:22:34
40K             0 days 02:38:24
Pace                    0:06:24
TotalSeconds             9504.0
HalfSeconds              4954.0
Name: 1716, dtype: object
Berkley
 Age                          45
M/F                           M
City                    Berkley
State                        MI
Country                     USA
Half            0 days 01:49:32
40K             0 days 03:38:42
Pace                    0:08:51
TotalSeconds            13122.0
HalfSeconds              6572.0
Name: 12585, dtype: object
Berlin
 Age                          43
M/F                           M
City                     Berlin
State                       NaN
Country                     GER
Half            0 days 01:39:27
40K             0 days 03:08:37
Pace                    0:07:40
TotalSeconds            11317.0
HalfSeconds              5967.0
Name: 31523, dtype: object
Bermuda Run
 Age                          49
M/F                           M
City                Bermuda Run
State                        NC
Country                     USA
Half            0 days 01:50:46
40K             0 days 03:56:19
Pace                    0:09:33
TotalSeconds            14179.0
HalfSeconds              6646.0
Name: 11718, dtype: object
Bernal
 Age                          27
M/F                           M
City                     Bernal
State                       NaN
Country                     ARG
Half            0 days 01:30:54
40K             0 days 03:00:44
Pace                    0:07:19
TotalSeconds            10844.0
HalfSeconds              5454.0
Name: 4960, dtype: object
Bernardsville
 Age                          58
M/F                           M
City              Bernardsville
State                        NJ
Country                     USA
Half            0 days 01:24:36
40K             0 days 02:46:50
Pace                    0:06:45
TotalSeconds            10010.0
HalfSeconds              5076.0
Name: 1215, dtype: object
Bernin
 Age                          47
M/F                           M
City                     Bernin
State                       NaN
Country                     FRA
Half            0 days 01:32:51
40K             0 days 03:35:11
Pace                    0:08:41
TotalSeconds            12911.0
HalfSeconds              5571.0
Name: 3661, dtype: object
Bertrange
 Age                          59
M/F                           F
City                  Bertrange
State                       NaN
Country                     LUX
Half            0 days 02:02:18
40K             0 days 04:01:36
Pace                    0:09:45
TotalSeconds            14496.0
HalfSeconds              7338.0
Name: 31290, dtype: object
Berwick
 Age                          57
M/F                           M
City                    Berwick
State                        PA
Country                     USA
Half            0 days 01:52:01
40K             0 days 03:34:50
Pace                    0:08:39
TotalSeconds            12890.0
HalfSeconds              6721.0
Name: 17232, dtype: object
Berwyn
 Age                          46
M/F                           F
City                     Berwyn
State                        PA
Country                     USA
Half            0 days 01:36:45
40K             0 days 03:08:32
Pace                    0:07:36
TotalSeconds            11312.0
HalfSeconds              5805.0
Name: 6732, dtype: object
Bessemer
 Age                          41
M/F                           F
City                   Bessemer
State                        AL
Country                     USA
Half            0 days 01:51:49
40K             0 days 03:41:28
Pace                    0:08:58
TotalSeconds            13288.0
HalfSeconds              6709.0
Name: 21261, dtype: object
Bethel
 Age                          54
M/F                           M
City                     Bethel
State                        VT
Country                     USA
Half            0 days 01:37:17
40K             0 days 03:09:17
Pace                    0:07:38
TotalSeconds            11357.0
HalfSeconds              5837.0
Name: 12954, dtype: object
Bethel Park
 Age                          23
M/F                           M
City                Bethel Park
State                        PA
Country                     USA
Half            0 days 01:26:24
40K             0 days 02:51:39
Pace                    0:07:01
TotalSeconds            10299.0
HalfSeconds              5184.0
Name: 5086, dtype: object
Bethesda
 Age                          37
M/F                           M
City                   Bethesda
State                        MD
Country                     USA
Half            0 days 01:25:47
40K             0 days 02:44:03
Pace                    0:06:36
TotalSeconds             9843.0
HalfSeconds              5147.0
Name: 3777, dtype: object
Bethlehem
 Age                          41
M/F                           M
City                  Bethlehem
State                        PA
Country                     USA
Half            0 days 01:25:18
40K             0 days 02:46:51
Pace                    0:06:43
TotalSeconds            10011.0
HalfSeconds              5118.0
Name: 1413, dtype: object
Bettendorf
 Age                          36
M/F                           M
City                 Bettendorf
State                        IA
Country                     USA
Half            0 days 01:28:20
40K             0 days 02:51:36
Pace                    0:06:56
TotalSeconds            10296.0
HalfSeconds              5300.0
Name: 6052, dtype: object
Beverly
 Age                          32
M/F                           M
City                    Beverly
State                        MA
Country                     USA
Half            0 days 01:21:29
40K             0 days 02:37:54
Pace                    0:06:22
TotalSeconds             9474.0
HalfSeconds              4889.0
Name: 1670, dtype: object
Beverly Hills
 Age                          42
M/F                           F
City              Beverly Hills
State                        MI
Country                     USA
Half            0 days 01:47:28
40K             0 days 03:41:22
Pace                    0:08:55
TotalSeconds            13282.0
HalfSeconds              6448.0
Name: 16334, dtype: object
Bexley
 Age                          38
M/F                           M
City                     Bexley
State                        OH
Country                     USA
Half            0 days 01:33:54
40K             0 days 03:02:47
Pace                    0:07:23
TotalSeconds            10967.0
HalfSeconds              5634.0
Name: 4084, dtype: object
Bezons
 Age                          46
M/F                           F
City                     Bezons
State                       NaN
Country                     FRA
Half            0 days 01:57:36
40K             0 days 03:53:40
Pace                    0:09:25
TotalSeconds            14020.0
HalfSeconds              7056.0
Name: 23212, dtype: object
Biberach
 Age                          34
M/F                           M
City                   Biberach
State                       NaN
Country                     GER
Half            0 days 01:36:45
40K             0 days 03:06:18
Pace                    0:07:29
TotalSeconds            11178.0
HalfSeconds              5805.0
Name: 3677, dtype: object
Biddeford
 Age                          56
M/F                           M
City                  Biddeford
State                        ME
Country                     USA
Half            0 days 01:45:23
40K             0 days 03:18:23
Pace                    0:08:00
TotalSeconds            11903.0
HalfSeconds              6323.0
Name: 18517, dtype: object
Biddenham
 Age                          35
M/F                           M
City                  Biddenham
State                       NaN
Country                     GBR
Half            0 days 01:39:40
40K             0 days 03:12:08
Pace                    0:07:43
TotalSeconds            11528.0
HalfSeconds              5980.0
Name: 31680, dtype: object
Biedenkopf
 Age                          34
M/F                           M
City                 Biedenkopf
State                       NaN
Country                     GER
Half            0 days 01:46:12
40K             0 days 03:26:13
Pace                    0:08:20
TotalSeconds            12373.0
HalfSeconds              6372.0
Name: 31043, dtype: object
Bielsko-Biala
 Age                          41
M/F                           M
City              Bielsko-Biala
State                       NaN
Country                     GBR
Half            0 days 01:31:39
40K             0 days 03:11:53
Pace                    0:07:49
TotalSeconds            11513.0
HalfSeconds              5499.0
Name: 6079, dtype: object
Bierzglinek
 Age                          47
M/F                           M
City                Bierzglinek
State                       NaN
Country                     POL
Half            0 days 01:42:21
40K             0 days 03:26:00
Pace                    0:08:20
TotalSeconds            12360.0
HalfSeconds              6141.0
Name: 9095, dtype: object
Biesenthal
 Age                          55
M/F                           M
City                 Biesenthal
State                       NaN
Country                     GER
Half            0 days 01:53:10
40K             0 days 03:42:11
Pace                    0:08:59
TotalSeconds            13331.0
HalfSeconds              6790.0
Name: 16615, dtype: object
Big Bear City
 Age                          52
M/F                           M
City              Big Bear City
State                        CA
Country                     USA
Half            0 days 01:36:55
40K             0 days 03:09:39
Pace                    0:07:41
TotalSeconds            11379.0
HalfSeconds              5815.0
Name: 10574, dtype: object
Big Rapids
 Age                          24
M/F                           F
City                 Big Rapids
State                        MI
Country                     USA
Half            0 days 01:41:11
40K             0 days 03:22:29
Pace                    0:08:13
TotalSeconds            12149.0
HalfSeconds              6071.0
Name: 16449, dtype: object
Big Sky
 Age                          37
M/F                           F
City                    Big Sky
State                        MT
Country                     USA
Half            0 days 02:14:34
40K             0 days 04:22:28
Pace                    0:10:34
TotalSeconds            15748.0
HalfSeconds              8074.0
Name: 29503, dtype: object
Bilbao
 Age                          47
M/F                           M
City                     Bilbao
State                       NaN
Country                     ESP
Half            0 days 01:34:33
40K             0 days 03:09:55
Pace                    0:07:48
TotalSeconds            11395.0
HalfSeconds              5673.0
Name: 8842, dtype: object
Billerica
 Age                          39
M/F                           F
City                  Billerica
State                        MA
Country                     USA
Half            0 days 01:28:22
40K             0 days 03:24:22
Pace                    0:08:11
TotalSeconds            12262.0
HalfSeconds              5302.0
Name: 2654, dtype: object
Billingham
 Age                          32
M/F                           M
City                 Billingham
State                       NaN
Country                     GBR
Half            0 days 01:26:27
40K             0 days 02:48:41
Pace                    0:06:49
TotalSeconds            10121.0
HalfSeconds              5187.0
Name: 2069, dtype: object
Billings
 Age                          25
M/F                           M
City                   Billings
State                        MT
Country                     USA
Half            0 days 01:27:53
40K             0 days 03:06:06
Pace                    0:07:34
TotalSeconds            11166.0
HalfSeconds              5273.0
Name: 4526, dtype: object
Billywillinga
 Age                          58
M/F                           M
City              Billywillinga
State                       NaN
Country                     AUS
Half            0 days 02:13:19
40K             0 days 04:35:56
Pace                    0:11:14
TotalSeconds            16556.0
HalfSeconds              7999.0
Name: 31544, dtype: object
Biloxi
 Age                          24
M/F                           M
City                     Biloxi
State                        MS
Country                     USA
Half            0 days 01:38:04
40K             0 days 03:44:47
Pace                    0:09:17
TotalSeconds            13487.0
HalfSeconds              5884.0
Name: 4964, dtype: object
Bilthoven
 Age                          50
M/F                           M
City                  Bilthoven
State                       NaN
Country                     NED
Half            0 days 01:31:27
40K             0 days 03:03:16
Pace                    0:07:24
TotalSeconds            10996.0
HalfSeconds              5487.0
Name: 6547, dtype: object
Binghamton
 Age                          23
M/F                           M
City                 Binghamton
State                        NY
Country                     USA
Half            0 days 01:12:02
40K             0 days 02:19:59
Pace                    0:05:39
TotalSeconds             8399.0
HalfSeconds              4322.0
Name: 104, dtype: object
Binningen
 Age                          41
M/F                           M
City                  Binningen
State                       NaN
Country                     SUI
Half            0 days 01:44:30
40K             0 days 03:53:09
Pace                    0:09:22
TotalSeconds            13989.0
HalfSeconds              6270.0
Name: 30118, dtype: object
Biot
 Age                          35
M/F                           M
City                       Biot
State                       NaN
Country                     FRA
Half            0 days 01:22:59
40K             0 days 02:51:12
Pace                    0:06:52
TotalSeconds            10272.0
HalfSeconds              4979.0
Name: 831, dtype: object
Birdsboro
 Age                          29
M/F                           F
City                  Birdsboro
State                        PA
Country                     USA
Half            0 days 01:37:44
40K             0 days 03:09:10
Pace                    0:07:37
TotalSeconds            11350.0
HalfSeconds              5864.0
Name: 13438, dtype: object
Birmingham
 Age                          36
M/F                           M
City                 Birmingham
State                        AL
Country                     USA
Half            0 days 01:20:39
40K             0 days 02:35:32
Pace                    0:06:17
TotalSeconds             9332.0
HalfSeconds              4839.0
Name: 394, dtype: object
Bischeim
 Age                          32
M/F                           M
City                   Bischeim
State                       NaN
Country                     FRA
Half            0 days 01:29:27
40K             0 days 02:57:14
Pace                    0:07:10
TotalSeconds            10634.0
HalfSeconds              5367.0
Name: 31420, dtype: object
Bischofszell
 Age                          69
M/F                           M
City               Bischofszell
State                       NaN
Country                     SUI
Half            0 days 02:16:06
40K             0 days 04:38:14
Pace                    0:11:18
TotalSeconds            16694.0
HalfSeconds              8166.0
Name: 25048, dtype: object
Bishop'S Stortford
 Age                             50
M/F                              M
City            Bishop'S Stortford
State                          NaN
Country                        GBR
Half               0 days 01:39:29
40K                0 days 03:14:16
Pace                       0:07:50
TotalSeconds               11656.0
HalfSeconds                 5969.0
Name: 12396, dtype: object
Bismarck
 Age                          27
M/F                           M
City                   Bismarck
State                        ND
Country                     USA
Half            0 days 01:24:10
40K             0 days 02:48:05
Pace                    0:06:47
TotalSeconds            10085.0
HalfSeconds              5050.0
Name: 1975, dtype: object
Bissendorf
 Age                          51
M/F                           M
City                 Bissendorf
State                       NaN
Country                     GER
Half            0 days 01:59:54
40K             0 days 04:00:06

 Age                          39
M/F                           F
City                 Bloomsburg
State                        PA
Country                     USA
Half            0 days 01:47:09
40K             0 days 03:28:16
Pace                    0:08:23
TotalSeconds            12496.0
HalfSeconds              6429.0
Name: 15368, dtype: object
Bloomsbury
 Age                          27
M/F                           F
City                 Bloomsbury
State                        NJ
Country                     USA
Half            0 days 01:48:01
40K             0 days 03:50:28
Pace                    0:09:21
TotalSeconds            13828.0
HalfSeconds              6481.0
Name: 9898, dtype: object
Blowing Rock
 Age                          26
M/F                           F
City               Blowing Rock
State                        NC
Country                     USA
Half            0 days 01:17:01
40K             0 days 02:28:58
Pace                    0:06:01
TotalSeconds             8938.0
HalfSeconds              4621.0
Name: F17, dtype: object
Bludesch
 Age                          58
M/F                           M
City                   Bludesch
State                       NaN
Country                     AUT
Half            0 days 01:59:21
40K             0 days 04:11:48
Pace                    0:10:07
TotalSeconds            15108.0
HalfSeconds              7161.0
Name: 31132, dtype: object
Blue Bell
 Age                          46
M/F                           F
City                  Blue Bell
State                        PA
Country                     USA
Half            0 days 01:48:16
40K             0 days 03:28:54
Pace                    0:08:21
TotalSeconds            12534.0
HalfSeconds              6496.0
Name: 14060, dtype: object
Blue Springs
 Age                          52
M/F                           M
City               Blue Springs
State                        MO
Country                     USA
Half            0 days 01:43:38
40K             0 days 03:30:02
Pace                    0:08:29
TotalSeconds            12602.0
HalfSeconds              6218.0
Name: 13303, dtype: object
Bluffdale
 Age                          50
M/F                           F
City                  Bluffdale
State                        UT
Country                     USA
Half            0 days 02:05:34
40K             0 days 04:08:49
Pace                    0:10:03
TotalSeconds            14929.0
HalfSeconds              7534.0
Name: 23407, dtype: object
Bluffton
 Age                          34
M/F                           M
City                   Bluffton
State                        SC
Country                     USA
Half            0 days 01:23:05
40K             0 days 02:43:32
Pace                    0:06:38
TotalSeconds             9812.0
HalfSeconds              4985.0
Name: 1750, dtype: object
Blumenort
 Age                          27
M/F                           M
City                  Blumenort
State                        MB
Country                     CAN
Half            0 days 01:29:15
40K             0 days 02:49:33
Pace                    0:06:49
TotalSeconds            10173.0
HalfSeconds              5355.0
Name: 4562, dtype: object
Boa Vista
 Age                          41
M/F                           M
City                  Boa Vista
State                       NaN
Country                     BRA
Half            0 days 01:48:33
40K             0 days 03:38:02
Pace                    0:08:48
TotalSeconds            13082.0
HalfSeconds              6513.0
Name: 30272, dtype: object
Boalsburg
 Age                          35
M/F                           F
City                  Boalsburg
State                        PA
Country                     USA
Half            0 days 01:43:10
40K             0 days 03:24:07
Pace                    0:08:15
TotalSeconds            12247.0
HalfSeconds              6190.0
Name: 17096, dtype: object
Boardman
 Age                          55
M/F                           F
City                   Boardman
State                        OR
Country                     USA
Half            0 days 01:57:01
40K             0 days 03:44:42
Pace                    0:09:01
TotalSeconds            13482.0
HalfSeconds              7021.0
Name: 22525, dtype: object
Boca Raton
 Age                          28
M/F                           M
City                 Boca Raton
State                        FL
Country                     USA
Half            0 days 01:25:13
40K             0 days 02:57:51
Pace                    0:07:14
TotalSeconds            10671.0
HalfSeconds              5113.0
Name: 1696, dtype: object
Bodenheim
 Age                          46
M/F                           M
City                  Bodenheim
State                       NaN
Country                     GER
Half            0 days 01:30:02
40K             0 days 02:57:19
Pace                    0:07:11
TotalSeconds            10639.0
HalfSeconds              5402.0
Name: 7023, dtype: object
Bogart
 Age                          41
M/F                           M
City                     Bogart
State                        GA
Country                     USA
Half            0 days 01:47:42
40K             0 days 03:31:02
Pace                    0:08:29
TotalSeconds            12662.0
HalfSeconds              6462.0
Name: 8911, dtype: object
Bogota
 Age                          37
M/F                           M
City                     Bogota
State                       NaN
Country                     COL
Half            0 days 01:22:30
40K             0 days 02:38:55
Pace                    0:06:24
TotalSeconds             9535.0
HalfSeconds              4950.0
Name: 651, dtype: object
Bogota D. C.
 Age                          65
M/F                           F
City               Bogota D. C.
State                       NaN
Country                     COL
Half            0 days 02:00:35
40K             0 days 04:07:49
Pace                    0:09:59
TotalSeconds            14869.0
HalfSeconds              7235.0
Name: 25849, dtype: object
Bogota D.c.
 Age                          30
M/F                           M
City                Bogota D.c.
State                       NaN
Country                     COL
Half            0 days 01:29:21
40K             0 days 02:54:04
Pace                    0:07:02
TotalSeconds            10444.0
HalfSeconds              5361.0
Name: 5400, dtype: object
Bogota Dc
 Age                          43
M/F                           M
City                  Bogota Dc
State                       NaN
Country                     COL
Half            0 days 01:30:04
40K             0 days 02:57:02
Pace                    0:07:09
TotalSeconds            10622.0
HalfSeconds              5404.0
Name: 2422, dtype: object
Bogota Dc.
 Age                          28
M/F                           M
City                 Bogota Dc.
State                       NaN
Country                     COL
Half            0 days 01:21:05
40K             0 days 02:37:46
Pace                    0:06:24
TotalSeconds             9466.0
HalfSeconds              4865.0
Name: 2316, dtype: object
Bogota, D.c:
 Age                          50
M/F                           M
City               Bogota, D.c:
State                       NaN
Country                     COL
Half            0 days 01:44:21
40K             0 days 03:17:43
Pace                    0:08:00
TotalSeconds            11863.0
HalfSeconds              6261.0
Name: 13562, dtype: object
Bogote D.c.
 Age                          55
M/F                           M
City                Bogote D.c.
State                       NaN
Country                     COL
Half            0 days 01:55:28
40K             0 days 04:03:43
Pace                    0:09:53
TotalSeconds            14623.0
HalfSeconds              6928.0
Name: 10614, dtype: object
Bogotá
 Age                          50
M/F                           M
City                     Bogotá
State                       NaN
Country                     COL
Half            0 days 01:24:34
40K             0 days 02:47:54
Pace                    0:06:49
TotalSeconds            10074.0
HalfSeconds              5074.0
Name: 5823, dtype: object
Boiling Springs
 Age                          45
M/F                           M
City            Boiling Springs
State                        SC
Country                     USA
Half            0 days 01:33:49
40K             0 days 03:00:35
Pace                    0:07:18
TotalSeconds            10835.0
HalfSeconds              5629.0
Name: 6643, dtype: object
Bois Le Roi
 Age                          43
M/F                           M
City                Bois Le Roi
State                       NaN
Country                     FRA
Half            0 days 01:43:21
40K             0 days 03:28:46
Pace                    0:08:26
TotalSeconds            12526.0
HalfSeconds              6201.0
Name: 30194, dtype: object
Boisbriand
 Age                          50
M/F                           M
City                 Boisbriand
State                        QC
Country                     CAN
Half            0 days 01:50:00
40K             0 days 03:43:07
Pace                    0:08:59
TotalSeconds            13387.0
HalfSeconds              6600.0
Name: 13627, dtype: object
Boischatel
 Age                          41
M/F                           M
City                 Boischatel
State                        QC
Country                     CAN
Half            0 days 01:28:33
40K             0 days 02:50:22
Pace                    0:06:52
TotalSeconds            10222.0
HalfSeconds              5313.0
Name: 6651, dtype: object
Boise
 Age                          28
M/F                           M
City                      Boise
State                        ID
Country                     USA
Half            0 days 01:27:18
40K             0 days 02:47:12
Pace                    0:06:44
TotalSeconds            10032.0
HalfSeconds              5238.0
Name: 2454, dtype: object
Bolinas
 Age                          55
M/F                           M
City                    Bolinas
State                        CA
Country                     USA
Half            0 days 01:38:18
40K             0 days 03:10:38
Pace                    0:07:42
TotalSeconds            11438.0
HalfSeconds              5898.0
Name: 13537, dtype: object
Bolingbroke
 Age                          55
M/F                           M
City                Bolingbroke
State                        GA
Country                     USA
Half            0 days 01:49:37
40K             0 days 03:44:38
Pace                    0:09:07
TotalSeconds            13478.0
HalfSeconds              6577.0
Name: 20037, dtype: object
Bolingbrook
 Age                          34
M/F                           M
City                Bolingbrook
State                        IL
Country                     USA
Half            0 days 01:26:37
40K             0 days 02:49:01
Pace                    0:06:51
TotalSeconds            10141.0
HalfSeconds              5197.0
Name: 556, dtype: object
Bolivar
 Age                          60
M/F                           M
City                    Bolivar
State                        NY
Country                     USA
Half            0 days 01:43:44
40K             0 days 03:34:32
Pace                    0:08:44
TotalSeconds            12872.0
HalfSeconds              6224.0
Name: 13606, dtype: object
Bolton
 Age                          38
M/F                           F
City                     Bolton
State                        CT
Country                     USA
Half            0 days 01:43:23
40K             0 days 03:27:49
Pace                    0:08:23
TotalSeconds            12469.0
HalfSeconds              6203.0
Name: 14775, dtype: object
Bolzano
 Age                          53
M/F                           F
City                    Bolzano
State                       NaN
Country                     ITA
Half            0 days 02:18:14
40K             0 days 04:47:11
Pace                    0:11:36
TotalSeconds            17231.0
HalfSeconds              8294.0
Name: 31809, dtype: object
Bonaire
 Age                          51
M/F                           M
City                    Bonaire
State                        GA
Country                     USA
Half            0 days 01:41:07
40K             0 days 03:11:32
Pace                    0:07:43
TotalSeconds            11492.0
HalfSeconds              6067.0
Name: 15082, dtype: object
Bondi Beach, Nsw
 Age                           37
M/F                            M
City            Bondi Beach, Nsw
State                        NaN
Country                      AUS
Half             0 days 01:29:49
40K              0 days 02:58:00
Pace                     0:07:12
TotalSeconds             10680.0
HalfSeconds               5389.0
Name: 4035, dtype: object
Bonduel
 Age                          46
M/F                           F
City                    Bonduel
State                        WI
Country                     USA
Half            0 days 01:58:26
40K             0 days 03:54:59
Pace                    0:09:32
TotalSeconds            14099.0
HalfSeconds              7106.0
Name: 23364, dtype: object
Bondurant
 Age                          29
M/F                           F
City                  Bondurant
State                        IA
Country                     USA
Half            0 days 01:37:13
40K             0 days 03:05:00
Pace                    0:07:27
TotalSeconds            11100.0
HalfSeconds              5833.0
Name: 10590, dtype: object
Bonita Springs
 Age                          54
M/F                           M
City             Bonita Springs
State                        FL
Country                     USA
Half            0 days 01:47:50
40K             0 days 03:44:36
Pace                    0:09:07
TotalSeconds            13476.0
HalfSeconds              6470.0
Name: 12175, dtype: object
Bonner Springs
 Age                          49
M/F                           M
City             Bonner Springs
State                        KS
Country                     USA
Half            0 days 01:39:47
40K             0 days 03:25:25
Pace                    0:08:19
TotalSeconds            12325.0
HalfSeconds              5987.0
Name: 11469, dtype: object
Bonney Lake
 Age                          50
M/F                           F
City                Bonney Lake
State                        WA
Country                     USA
Half            0 days 01:52:59
40K             0 days 03:42:07
Pace                    0:08:57
TotalSeconds            13327.0
HalfSeconds              6779.0
Name: 20559, dtype: object
Bonogin
 Age                          46
M/F                           M
City                    Bonogin
State                       NaN
Country                     AUS
Half            0 days 01:39:06
40K             0 days 03:34:46
Pace                    0:08:57
TotalSeconds            12886.0
HalfSeconds              5946.0
Name: 10719, dtype: object
Bonshaw
 Age                          45
M/F                           M
City                    Bonshaw
State                        PE
Country                     CAN
Half            0 days 01:50:16
40K             0 days 03:49:48
Pace                    0:09:19
TotalSeconds            13788.0
HalfSeconds              6616.0
Name: 9813, dtype: object
Boone
 Age                          47
M/F                           F
City                      Boone
State                        NC
Country                     USA
Half            0 days 01:52:04
40K             0 days 03:42:21
Pace                    0:08:58
TotalSeconds            13341.0
HalfSeconds              6724.0
Name: 24044, dtype: object
Boonton
 Age                          54
M/F                           F
City                    Boonton
State                        NJ
Country                     USA
Half            0 days 01:41:06
40K             0 days 03:12:11
Pace                    0:07:44
TotalSeconds            11531.0
HalfSeconds              6066.0
Name: 15110, dtype: object
Boonville
 Age                          39
M/F                           F
City                  Boonville
State                        NY
Country                     USA
Half            0 days 01:39:06
40K             0 days 03:13:39
Pace                    0:07:47
TotalSeconds            11619.0
HalfSeconds              5946.0
Name: 11885, dtype: object
Boothbay
 Age                          33
M/F                           M
City                   Boothbay
State                        ME
Country                     USA
Half            0 days 01:33:45
40K             0 days 02:59:47
Pace                    0:07:17
TotalSeconds            10787.0
HalfSeconds              5625.0
Name: 1939, dtype: object
Boothbay Harbor
 Age                          51
M/F                           F
City            Boothbay Harbor
State                        ME
Country                     USA
Half            0 days 01:52:27
40K             0 days 03:42:58
Pace                    0:08:59
TotalSeconds            13378.0
HalfSeconds              6747.0
Name: 24636, dtype: object
Boscawen
 Age                          47
M/F                           M
City                   Boscawen
State                        NH
Country                     USA
Half            0 days 01:33:32
40K             0 days 03:07:31
Pace                    0:07:37
TotalSeconds            11251.0
HalfSeconds              5612.0
Name: 9380, dtype: object
Bossier City
 Age                          47
M/F                           F
City               Bossier City
State                        LA
Country                     USA
Half            0 days 01:48:48
40K             0 days 03:41:31
Pace                    0:09:03
TotalSeconds            13291.0
HalfSeconds              6528.0
Name: 17416, dtype: object
Boston
 Age                          35
M/F                           F
City                     Boston
State                        MA
Country                     USA
Half            0 days 04:47:17
40K             0 days 00:00:00
Pace                    0:24:30
TotalSeconds                0.0
HalfSeconds             17237.0
Name: 28487, dtype: object
Boston Heights
 Age                          48
M/F                           F
City             Boston Heights
State                        OH
Country                     USA
Half            0 days 02:00:24
40K             0 days 04:17:18
Pace                    0:10:18
TotalSeconds            15438.0
HalfSeconds              7224.0
Name: 18485, dtype: object
Bothell
 Age                          41
M/F                           F
City                    Bothell
State                        WA
Country                     USA
Half            0 days 01:52:51
40K             0 days 03:36:23
Pace                    0:08:42
TotalSeconds            12983.0
HalfSeconds              6771.0
Name: 16784, dtype: object
Boucherville
 Age                          46
M/F                           M
City               Boucherville
State                        QC
Country                     CAN
Half            0 days 01:39:05
40K             0 days 03:08:44
Pace                    0:07:35
TotalSeconds            11324.0
HalfSeconds              5945.0
Name: 10402, dtype: object
Boulder
 Age                          40
M/F                           M
City                    Boulder
State                        CO
Country                     USA
Half            0 days 01:10:15
40K             0 days 02:16:51
Pace                    0:05:32
TotalSeconds             8211.0
HalfSeconds              4215.0
Name: 79, dtype: object
Boulder City
 Age                          40
M/F                           F
City               Boulder City
State                        NV
Country                     USA
Half            0 days 01:49:38
40K             0 days 03:35:13
Pace                    0:08:42
TotalSeconds            12913.0

Bradford
 Age                          39
M/F                           M
City                   Bradford
State                        VT
Country                     USA
Half            0 days 01:25:42
40K             0 days 02:55:39
Pace                    0:07:07
TotalSeconds            10539.0
HalfSeconds              5142.0
Name: 1168, dtype: object
Bradley
 Age                          62
M/F                           M
City                    Bradley
State                        SD
Country                     USA
Half            0 days 01:51:36
40K             0 days 03:34:33
Pace                    0:08:40
TotalSeconds            12873.0
HalfSeconds              6696.0
Name: 21147, dtype: object
Braintree
 Age                          33
M/F                           M
City                  Braintree
State                        MA
Country                     USA
Half            0 days 01:30:03
40K             0 days 03:03:50
Pace                    0:07:27
TotalSeconds            11030.0
HalfSeconds              5403.0
Name: 2878, dtype: object
Brampton
 Age                          53
M/F                           M
City                   Brampton
State                        ON
Country                     CAN
Half            0 days 01:38:27
40K             0 days 03:09:23
Pace                    0:07:38
TotalSeconds            11363.0
HalfSeconds              5907.0
Name: 11578, dtype: object
Brandon
 Age                          33
M/F                           M
City                    Brandon
State                        FL
Country                     USA
Half            0 days 01:25:02
40K             0 days 02:56:06
Pace                    0:07:10
TotalSeconds            10566.0
HalfSeconds              5102.0
Name: 1639, dtype: object
Branford
 Age                          28
M/F                           F
City                   Branford
State                        CT
Country                     USA
Half            0 days 01:39:05
40K             0 days 03:10:42
Pace                    0:07:43
TotalSeconds            11442.0
HalfSeconds              5945.0
Name: 11762, dtype: object
Branson
 Age                          23
M/F                           M
City                    Branson
State                        MO
Country                     USA
Half            0 days 01:24:05
40K             0 days 02:42:16
Pace                    0:06:33
TotalSeconds             9736.0
HalfSeconds              5045.0
Name: 2444, dtype: object
Brantford
 Age                          38
M/F                           F
City                  Brantford
State                        ON
Country                     CAN
Half            0 days 01:51:29
40K             0 days 03:25:20
Pace                    0:08:13
TotalSeconds            12320.0
HalfSeconds              6689.0
Name: 11831, dtype: object
Brasd'Or
 Age                          43
M/F                           F
City                   Brasd'Or
State                        NS
Country                     CAN
Half            0 days 01:51:25
40K             0 days 03:44:41
Pace                    0:09:06
TotalSeconds            13481.0
HalfSeconds              6685.0
Name: 21473, dtype: object
Brasilia
 Age                          52
M/F                           M
City                   Brasilia
State                       NaN
Country                     BRA
Half            0 days 01:39:22
40K             0 days 03:18:18
Pace                    0:07:59
TotalSeconds            11898.0
HalfSeconds              5962.0
Name: 9604, dtype: object
Brasília
 Age                          55
M/F                           M
City                   Brasília
State                       NaN
Country                     BRA
Half            0 days 01:42:08
40K             0 days 03:43:04
Pace                    0:09:11
TotalSeconds            13384.0
HalfSeconds              6128.0
Name: 9091, dtype: object
Brasília, Distrito Federal
 Age                                     33
M/F                                      M
City            Brasília, Distrito Federal
State                                  NaN
Country                                BRA
Half                       0 days 01:31:15
40K                        0 days 03:13:54
Pace                               0:07:53
TotalSeconds                       11634.0
HalfSeconds                         5475.0
Name: 3341, dtype: object
Bratislava
 Age                          41
M/F                           M
City                 Bratislava
State                       NaN
Country                     SVK
Half            0 days 01:17:35
40K             0 days 02:31:17
Pace                    0:06:06
TotalSeconds             9077.0
HalfSeconds              4655.0
Name: 646, dtype: object
Brattleboro
 Age                          30
M/F                           F
City                Brattleboro
State                        VT
Country                     USA
Half            0 days 01:28:23
40K             0 days 03:03:38
Pace                    0:07:25
TotalSeconds            11018.0
HalfSeconds              5303.0
Name: 1659, dtype: object
Braunschweig
 Age                          39
M/F                           M
City               Braunschweig
State                       NaN
Country                     GER
Half            0 days 01:33:30
40K             0 days 03:12:14
Pace                    0:07:51
TotalSeconds            11534.0
HalfSeconds              5610.0
Name: 2271, dtype: object
Brea
 Age                          43
M/F                           F
City                       Brea
State                        CA
Country                     USA
Half            0 days 01:44:11
40K             0 days 03:26:11
Pace                    0:08:19
TotalSeconds            12371.0
HalfSeconds              6251.0
Name: 14645, dtype: object
Breckenridge
 Age                          56
M/F                           M
City               Breckenridge
State                        CO
Country                     USA
Half            0 days 01:40:35
40K             0 days 03:15:49
Pace                    0:07:53
TotalSeconds            11749.0
HalfSeconds              6035.0
Name: 7594, dtype: object
Brecksville
 Age                          22
M/F                           M
City                Brecksville
State                        OH
Country                     USA
Half            0 days 01:17:07
40K             0 days 02:33:53
Pace                    0:06:14
TotalSeconds             9233.0
HalfSeconds              4627.0
Name: 588, dtype: object
Breda
 Age                          50
M/F                           F
City                      Breda
State                       NaN
Country                     NED
Half            0 days 02:06:14
40K             0 days 04:12:50
Pace                    0:10:15
TotalSeconds            15170.0
HalfSeconds              7574.0
Name: 31267, dtype: object
Breganze
 Age                          37
M/F                           M
City                   Breganze
State                       NaN
Country                     ITA
Half            0 days 01:36:46
40K             0 days 03:20:54
Pace                    0:08:10
TotalSeconds            12054.0
HalfSeconds              5806.0
Name: 6512, dtype: object
Breinigsville
 Age                          35
M/F                           F
City              Breinigsville
State                        PA
Country                     USA
Half            0 days 02:27:08
40K             0 days 04:53:34
Pace                    0:11:47
TotalSeconds            17614.0
HalfSeconds              8828.0
Name: 26870, dtype: object
Breitenbrunn
 Age                          46
M/F                           M
City               Breitenbrunn
State                       NaN
Country                     AUT
Half            0 days 01:34:00
40K             0 days 03:02:42
Pace                    0:07:22
TotalSeconds            10962.0
HalfSeconds              5640.0
Name: 8068, dtype: object
Bremerhaven
 Age                          53
M/F                           M
City                Bremerhaven
State                       NaN
Country                     GER
Half            0 days 01:49:29
40K             0 days 03:43:47
Pace                    0:08:59
TotalSeconds            13427.0
HalfSeconds              6569.0
Name: 5892, dtype: object
Bremerton
 Age                          22
M/F                           M
City                  Bremerton
State                        WA
Country                     USA
Half            0 days 01:17:07
40K             0 days 02:31:35
Pace                    0:06:06
TotalSeconds             9095.0
HalfSeconds              4627.0
Name: 857, dtype: object
Brenham
 Age                          40
M/F                           F
City                    Brenham
State                        TX
Country                     USA
Half            0 days 01:54:00
40K             0 days 03:50:29
Pace                    0:09:16
TotalSeconds            13829.0
HalfSeconds              6840.0
Name: 16904, dtype: object
Brentwood
 Age                          44
M/F                           M
City                  Brentwood
State                       NaN
Country                     GBR
Half            0 days 01:33:34
40K             0 days 03:07:14
Pace                    0:07:36
TotalSeconds            11234.0
HalfSeconds              5614.0
Name: 6485, dtype: object
Brescia
 Age                          38
M/F                           M
City                    Brescia
State                       NaN
Country                     ITA
Half            0 days 02:00:39
40K             0 days 04:05:50
Pace                    0:09:52
TotalSeconds            14750.0
HalfSeconds              7239.0
Name: 31431, dtype: object
Brest
 Age                          47
M/F                           M
City                      Brest
State                       NaN
Country                     FRA
Half            0 days 01:29:09
40K             0 days 02:58:16
Pace                    0:07:14
TotalSeconds            10696.0
HalfSeconds              5349.0
Name: 5744, dtype: object
Brevard
 Age                          46
M/F                           M
City                    Brevard
State                        NC
Country                     USA
Half            0 days 01:36:36
40K             0 days 03:32:04
Pace                    0:08:41
TotalSeconds            12724.0
HalfSeconds              5796.0
Name: 6276, dtype: object
Brewster
 Age                          48
M/F                           M
City                   Brewster
State                        NY
Country                     USA
Half            0 days 01:43:15
40K             0 days 03:31:33
Pace                    0:08:34
TotalSeconds            12693.0
HalfSeconds              6195.0
Name: 11670, dtype: object
Briarwood
 Age                          45
M/F                           F
City                  Briarwood
State                        NY
Country                     USA
Half            0 days 01:52:22
40K             0 days 03:45:01
Pace                    0:09:05
TotalSeconds            13501.0
HalfSeconds              6742.0
Name: 24068, dtype: object
Brick
 Age                          41
M/F                           M
City                      Brick
State                        NJ
Country                     USA
Half            0 days 01:27:24
40K             0 days 02:47:19
Pace                    0:06:44
TotalSeconds            10039.0
HalfSeconds              5244.0
Name: 2004, dtype: object
Bridgeport
 Age                          30
M/F                           M
City                 Bridgeport
State                        CT
Country                     USA
Half            0 days 01:23:32
40K             0 days 02:56:46
Pace                    0:07:09
TotalSeconds            10606.0
HalfSeconds              5012.0
Name: 2461, dtype: object
Bridgewater
 Age                          39
M/F                           M
City                Bridgewater
State                        NJ
Country                     USA
Half            0 days 01:31:50
40K             0 days 03:04:31
Pace                    0:07:29
TotalSeconds            11071.0
HalfSeconds              5510.0
Name: 2277, dtype: object
Bridgewater Corners
 Age                              29
M/F                               F
City            Bridgewater Corners
State                            VT
Country                         USA
Half                0 days 01:51:49
40K                 0 days 03:49:22
Pace                        0:09:12
TotalSeconds                13762.0
HalfSeconds                  6709.0
Name: 10923, dtype: object
Brielle
 Age                          48
M/F                           F
City                    Brielle
State                        NJ
Country                     USA
Half            0 days 01:56:32
40K             0 days 03:51:48
Pace                    0:09:20
TotalSeconds            13908.0
HalfSeconds              6992.0
Name: 21866, dtype: object
Brigantine
 Age                          24
M/F                           F
City                 Brigantine
State                        NJ
Country                     USA
Half            0 days 01:44:19
40K             0 days 03:40:41
Pace                    0:09:00
TotalSeconds            13241.0
HalfSeconds              6259.0
Name: 16516, dtype: object
Brighton
 Age                          27
M/F                           M
City                   Brighton
State                        MA
Country                     USA
Half            0 days 01:13:49
40K             0 days 02:22:05
Pace                    0:05:45
TotalSeconds             8525.0
HalfSeconds              4429.0
Name: 152, dtype: object
Brigstock
 Age                          45
M/F                           M
City                  Brigstock
State                       NaN
Country                     GBR
Half            0 days 01:49:34
40K             0 days 03:33:04
Pace                    0:08:35
TotalSeconds            12784.0
HalfSeconds              6574.0
Name: 31897, dtype: object
Brimfield
 Age                          41
M/F                           F
City                  Brimfield
State                        MA
Country                     USA
Half            0 days 01:51:52
40K             0 days 03:40:52
Pace                    0:08:55
TotalSeconds            13252.0
HalfSeconds              6712.0
Name: 27390, dtype: object
Brisbane
 Age                          55
M/F                           M
City                   Brisbane
State                       NaN
Country                     AUS
Half            0 days 01:35:18
40K             0 days 03:09:08
Pace                    0:07:40
TotalSeconds            11348.0
HalfSeconds              5718.0
Name: 12577, dtype: object
Bristol
 Age                          34
M/F                           M
City                    Bristol
State                        RI
Country                     USA
Half            0 days 01:27:05
40K             0 days 02:56:28
Pace                    0:07:11
TotalSeconds            10588.0
HalfSeconds              5225.0
Name: 3452, dtype: object
Bristow
 Age                          46
M/F                           F
City                    Bristow
State                        VA
Country                     USA
Half            0 days 01:54:54
40K             0 days 03:44:47
Pace                    0:09:06
TotalSeconds            13487.0
HalfSeconds              6894.0
Name: 22593, dtype: object
Brno
 Age                          42
M/F                           M
City                       Brno
State                       NaN
Country                     CZE
Half            0 days 01:33:34
40K             0 days 03:00:47
Pace                    0:07:18
TotalSeconds            10847.0
HalfSeconds              5614.0
Name: 7385, dtype: object
Broadbeach Waters
 Age                            54
M/F                             F
City            Broadbeach Waters
State                         NaN
Country                       AUS
Half              0 days 02:34:16
40K               0 days 05:05:13
Pace                      0:12:22
TotalSeconds              18313.0
HalfSeconds                9256.0
Name: 31550, dtype: object
Broadview Heights
 Age                            42
M/F                             M
City            Broadview Heights
State                          OH
Country                       USA
Half              0 days 01:38:15
40K               0 days 03:14:25
Pace                      0:07:50
TotalSeconds              11665.0
HalfSeconds                5895.0
Name: 8307, dtype: object
Brockport
 Age                          24
M/F                           M
City                  Brockport
State                        NY
Country                     USA
Half            0 days 01:31:02
40K             0 days 03:04:36
Pace                    0:07:30
TotalSeconds            11076.0
HalfSeconds              5462.0
Name: 4926, dtype: object
Brockton
 Age                          34
M/F                           F
City                   Brockton
State                        MA
Country                     USA
Half            0 days 01:33:50
40K             0 days 03:05:21
Pace                    0:07:28
TotalSeconds            11121.0
HalfSeconds              5630.0
Name: 6905, dtype: object
Brockville
 Age                          49
M/F                           F
City                 Brockville
State                        ON
Country                     CAN
Half            0 days 01:48:57
40K             0 days 03:34:59
Pace                    0:08:42
TotalSeconds            12899.0
HalfSeconds              6537.0
Name: 24433, dtype: object
Brodheadsville
 Age                          36
M/F                           M
City             Brodheadsville
State                        PA
Country                     USA
Half            0 days 01:24:43
40K             0 days 02:45:21
Pace                    0:06:40
TotalSeconds             9921.0
HalfSeconds              5083.0
Name: 3103, dtype: object
Broken Arrow
 Age                          38
M/F                           F
City               Broken Arrow
State                        OK
Country                     USA
Half            0 days 01:50:11
40K             0 days 03:40:48
Pace                    0:08:53
TotalSeconds            13248.0
HalfSeconds              6611.0
Name: 13792, dtype: object
Bromma
 Age                          40
M/F                           M
City                     Bromma
State                       NaN
Country                     SWE
Half            0 days 01:26:45
40K             0 days 02:46:46
Pace                    0:06:43
TotalSeconds            10006.0
HalfSeconds              5205.0
Name: 3174, dtype: object
Bronx
 Age                          28
M/F                           M
City                      Bronx
State                        NY
Country                     USA
Half            0 days 01:17:04
40K             0 days 02:31:06
Pace                    0:06:09
TotalSeconds             9066.0
HalfSeconds              4624.0
Name: 583, dtype: object
Bronx,
 Age                          20
M/F                           F
City                     Bronx,
State                        NY
Country                     USA
Half            0 days 02:25:13
40K             0 days 05:02:51
Pace                    0:12:14
TotalSeconds            18171.0
HalfSeconds              8713.0
Name: 26814, dtype: object
Bronxville
 Age                          30
M/F                           M
City                 Bronxville
State                        NY
Country                     USA
Half            0 days 01:39:58
40K             0 days 03:23:58
Pace                    0:08:13
TotalSeconds            12238.0
HalfSeconds              5998.0
Name: 1527, dtype: object
Brook Park
 Age                          26
M/F                           M
City                 Brook Park
State                        OH

Broomfield
 Age                          32
M/F                           M
City                 Broomfield
State                        CO
Country                     USA
Half            0 days 01:22:30
40K             0 days 02:43:52
Pace                    0:06:40
TotalSeconds             9832.0
HalfSeconds              4950.0
Name: 3162, dtype: object
Brossard
 Age                          33
M/F                           M
City                   Brossard
State                        QC
Country                     CAN
Half            0 days 01:27:10
40K             0 days 02:47:30
Pace                    0:06:45
TotalSeconds            10050.0
HalfSeconds              5230.0
Name: 3009, dtype: object
Broussard
 Age                          53
M/F                           F
City                  Broussard
State                        LA
Country                     USA
Half            0 days 01:54:05
40K             0 days 03:52:44
Pace                    0:09:25
TotalSeconds            13964.0
HalfSeconds              6845.0
Name: 24912, dtype: object
Brownsburg
 Age                          44
M/F                           M
City                 Brownsburg
State                        IN
Country                     USA
Half            0 days 01:39:15
40K             0 days 03:16:49
Pace                    0:07:57
TotalSeconds            11809.0
HalfSeconds              5955.0
Name: 6429, dtype: object
Brownstown
 Age                          58
M/F                           M
City                 Brownstown
State                        MI
Country                     USA
Half            0 days 01:40:07
40K             0 days 03:19:11
Pace                    0:08:03
TotalSeconds            11951.0
HalfSeconds              6007.0
Name: 8821, dtype: object
Brownsville
 Age                          34
M/F                           M
City                Brownsville
State                        TX
Country                     USA
Half            0 days 01:28:48
40K             0 days 02:55:56
Pace                    0:07:08
TotalSeconds            10556.0
HalfSeconds              5328.0
Name: 5386, dtype: object
Brugge
 Age                          41
M/F                           F
City                     Brugge
State                       NaN
Country                     BEL
Half            0 days 01:40:22
40K             0 days 03:18:13
Pace                    0:08:01
TotalSeconds            11893.0
HalfSeconds              6022.0
Name: 9560, dtype: object
Brundee Nsw
 Age                          43
M/F                           M
City                Brundee Nsw
State                       NaN
Country                     AUS
Half            0 days 01:27:05
40K             0 days 02:49:56
Pace                    0:06:51
TotalSeconds            10196.0
HalfSeconds              5225.0
Name: 6799, dtype: object
Brunico
 Age                          48
M/F                           M
City                    Brunico
State                       NaN
Country                     ITA
Half            0 days 02:06:07
40K             0 days 04:14:22
Pace                    0:10:16
TotalSeconds            15262.0
HalfSeconds              7567.0
Name: 31828, dtype: object
Brunoy
 Age                          45
M/F                           M
City                     Brunoy
State                       NaN
Country                     FRA
Half            0 days 01:34:39
40K             0 days 03:08:40
Pace                    0:07:40
TotalSeconds            11320.0
HalfSeconds              5679.0
Name: 8654, dtype: object
Brunswick
 Age                          47
M/F                           M
City                  Brunswick
State                        ME
Country                     USA
Half            0 days 01:21:20
40K             0 days 02:38:58
Pace                    0:06:25
TotalSeconds             9538.0
HalfSeconds              4880.0
Name: 537, dtype: object
Brunswick East
 Age                          50
M/F                           F
City             Brunswick East
State                       NaN
Country                     AUS
Half            0 days 02:02:11
40K             0 days 03:57:41
Pace                    0:09:33
TotalSeconds            14261.0
HalfSeconds              7331.0
Name: 31543, dtype: object
Brush Prairie
 Age                          50
M/F                           M
City              Brush Prairie
State                        WA
Country                     USA
Half            0 days 01:44:43
40K             0 days 03:23:28
Pace                    0:08:11
TotalSeconds            12208.0
HalfSeconds              6283.0
Name: 14949, dtype: object
Brussels
 Age                          52
M/F                           M
City                   Brussels
State                       NaN
Country                     BEL
Half            0 days 01:40:59
40K             0 days 03:25:16
Pace                    0:08:19
TotalSeconds            12316.0
HalfSeconds              6059.0
Name: 12953, dtype: object
Bryan
 Age                          37
M/F                           F
City                      Bryan
State                        TX
Country                     USA
Half            0 days 01:46:55
40K             0 days 03:29:10
Pace                    0:08:25
TotalSeconds            12550.0
HalfSeconds              6415.0
Name: 16051, dtype: object
Bryceville
 Age                          46
M/F                           M
City                 Bryceville
State                        FL
Country                     USA
Half            0 days 01:26:39
40K             0 days 02:51:08
Pace                    0:06:55
TotalSeconds            10268.0
HalfSeconds              5199.0
Name: 1891, dtype: object
Bryn Mawr
 Age                          48
M/F                           F
City                  Bryn Mawr
State                        PA
Country                     USA
Half            0 days 01:37:07
40K             0 days 03:10:37
Pace                    0:07:42
TotalSeconds            11437.0
HalfSeconds              5827.0
Name: 9408, dtype: object
Bucharest
 Age                          43
M/F                           M
City                  Bucharest
State                       NaN
Country                     ROU
Half            0 days 01:32:12
40K             0 days 03:09:16
Pace                    0:07:41
TotalSeconds            11356.0
HalfSeconds              5532.0
Name: 7687, dtype: object
Buchkirchen
 Age                          52
M/F                           M
City                Buchkirchen
State                       NaN
Country                     AUT
Half            0 days 01:32:54
40K             0 days 03:07:45
Pace                    0:07:36
TotalSeconds            11265.0
HalfSeconds              5574.0
Name: 9815, dtype: object
Buckhurst Hill
 Age                          44
M/F                           M
City             Buckhurst Hill
State                       NaN
Country                     GBR
Half            0 days 01:25:00
40K             0 days 02:43:50
Pace                    0:06:38
TotalSeconds             9830.0
HalfSeconds              5100.0
Name: 1872, dtype: object
Buckingham
 Age                          45
M/F                           M
City                 Buckingham
State                        VA
Country                     USA
Half            0 days 01:29:44
40K             0 days 02:53:25
Pace                    0:07:03
TotalSeconds            10405.0
HalfSeconds              5384.0
Name: 5776, dtype: object
Buckley
 Age                          47
M/F                           M
City                    Buckley
State                        WA
Country                     USA
Half            0 days 01:40:57
40K             0 days 03:20:06
Pace                    0:08:07
TotalSeconds            12006.0
HalfSeconds              6057.0
Name: 10720, dtype: object
Bucksport
 Age                          50
M/F                           F
City                  Bucksport
State                        ME
Country                     USA
Half            0 days 01:55:32
40K             0 days 03:47:25
Pace                    0:09:10
TotalSeconds            13645.0
HalfSeconds              6932.0
Name: 21583, dtype: object
Buda
 Age                          30
M/F                           F
City                       Buda
State                        TX
Country                     USA
Half            0 days 01:35:05
40K             0 days 03:22:43
Pace                    0:08:12
TotalSeconds            12163.0
HalfSeconds              5705.0
Name: 6210, dtype: object
Budapest
 Age                          26
M/F                           M
City                   Budapest
State                       NaN
Country                     HUN
Half            0 days 01:28:10
40K             0 days 03:02:42
Pace                    0:07:25
TotalSeconds            10962.0
HalfSeconds              5290.0

Name: 4199, dtype: object
Buderim
 Age                          40
M/F                           F
City                    Buderim
State                       NaN
Country                     AUS
Half            0 days 01:43:52
40K             0 days 03:23:12
Pace                    0:08:12
TotalSeconds            12192.0
HalfSeconds              6232.0
Name: 16196, dtype: object
Buena Park
 Age                          45
M/F                           M
City                 Buena Park
State                        CA
Country                     USA
Half            0 days 01:59:04
40K             0 days 04:19:34
Pace                    0:10:30
TotalSeconds            15574.0
HalfSeconds              7144.0
Name: 10248, dtype: object
Buenos Aires
 Age                          38
M/F                           M
City               Buenos Aires
State                       NaN
Country                     ARG
Half            0 days 01:29:52
40K             0 days 02:50:52
Pace                    0:06:51
TotalSeconds            10252.0
HalfSeconds              5392.0
Name: 3655, dtype: object
Buffalo
 Age                          40
M/F                           M
City                    Buffalo
State                        NY
Country                     USA
Half            0 days 01:31:09
40K             0 days 02:55:48
Pace                    0:07:06
TotalSeconds            10548.0
HalfSeconds              5469.0
Name: 4428, dtype: object
Buffalo Grove
 Age                          37
M/F                           F
City              Buffalo Grove
State                        IL
Country                     USA
Half            0 days 01:41:09
40K             0 days 03:18:13
Pace                    0:08:00
TotalSeconds            11893.0
HalfSeconds              6069.0
Name: 16037, dtype: object
Buford
 Age                          52
M/F                           M
City                     Buford
State                        GA
Country                     USA
Half            0 days 01:43:20
40K             0 days 03:42:04
Pace                    0:08:59
TotalSeconds            13324.0
HalfSeconds              6200.0
Name: 12369, dtype: object
Bulimba
 Age                          53
M/F                           M
City                    Bulimba
State                       NaN
Country                     AUS
Half            0 days 01:36:25
40K             0 days 03:09:18
Pace                    0:07:42
TotalSeconds            11358.0
HalfSeconds              5785.0
Name: 10730, dtype: object
Bulli Nsw
 Age                          37
M/F                           F
City                  Bulli Nsw
State                       NaN
Country                     AUS
Half            0 days 01:41:26
40K             0 days 03:24:50
Pace                    0:08:17
TotalSeconds            12290.0
HalfSeconds              6086.0
Name: 14819, dtype: object
Bundaberg
 Age                          50
M/F                           M
City                  Bundaberg
State                       NaN
Country                     AUS
Half            0 days 01:44:20
40K             0 days 03:27:30
Pace                    0:08:22
TotalSeconds            12450.0
HalfSeconds              6260.0
Name: 13675, dtype: object
Bunnlevel
 Age                          40
M/F                           M
City                  Bunnlevel
State                        NC
Country                     USA
Half            0 days 01:34:09
40K             0 days 02:59:04
Pace                    0:07:13
TotalSeconds            10744.0
HalfSeconds              5649.0
Name: 8031, dtype: object
Burbank
 Age                          24
M/F                           M
City                    Burbank
State                        CA
Country                     USA
Half            0 days 01:26:41
40K             0 days 02:49:21
Pace                    0:06:49
TotalSeconds            10161.0
HalfSeconds              5201.0
Name: 4246, dtype: object
Burdett
 Age                          54
M/F                           F
City                    Burdett
State                        NY
Country                     USA
Half            0 days 02:01:21
40K             0 days 03:58:07
Pace                    0:09:39
TotalSeconds            14287.0
HalfSeconds              7281.0
Name: 24410, dtype: object
Burghill
 Age                          25
M/F                           M
City                   Burghill
State                        OH
Country                     USA
Half            0 days 01:33:22
40K             0 days 03:17:09
Pace                    0:08:02
TotalSeconds            11829.0
HalfSeconds              5602.0
Name: 4904, dtype: object
Burien
 Age                          63
M/F                           M
City                     Burien
State                        WA
Country                     USA
Half            0 days 01:54:01
40K             0 days 03:45:05
Pace                    0:09:07
TotalSeconds            13505.0
HalfSeconds              6841.0
Name: 23333, dtype: object
Burke
 Age                          37
M/F                           M
City                      Burke
State                        VA
Country                     USA
Half            0 days 01:23:17
40K             0 days 02:39:52
Pace                    0:06:27
TotalSeconds             9592.0
HalfSeconds              4997.0
Name: 1418, dtype: object
Burleson
 Age                          45
M/F                           F
City                   Burleson
State                        TX
Country                     USA
Half            0 days 01:50:50
40K             0 days 03:56:12
Pace                    0:09:30
TotalSeconds            14172.0
HalfSeconds              6650.0
Name: 21924, dtype: object
Burlingame
 Age                          32
M/F                           M
City                 Burlingame
State                        CA
Country                     USA
Half            0 days 01:21:58
40K             0 days 02:40:26
Pace                    0:06:28
TotalSeconds             9626.0
HalfSeconds              4918.0
Name: 543, dtype: object
Burlington
 Age                          48
M/F                           M
City                 Burlington
State                        VT
Country                     USA
Half            0 days 01:24:38
40K             0 days 02:47:07
Pace                    0:06:48
TotalSeconds            10027.0
HalfSeconds              5078.0
Name: 2146, dtype: object
Burnaby
 Age                          41
M/F                           M
City                    Burnaby
State                        BC
Country                     CAN
Half            0 days 01:30:56
40K             0 days 02:59:52
Pace                    0:07:17
TotalSeconds            10792.0
HalfSeconds              5456.0
Name: 6510, dtype: object
Burnham On Sea
 Age                          70
M/F                           F
City             Burnham On Sea
State                       NaN
Country                     GBR
Half            0 days 01:56:10
40K             0 days 03:47:54
Pace                    0:09:11
TotalSeconds            13674.0
HalfSeconds              6970.0
Name: 22191, dtype: object
Burns
 Age                          61
M/F                           F
City                      Burns
State                        TN
Country                     USA
Half            0 days 02:05:05
40K             0 days 04:06:49
Pace                    0:09:56
TotalSeconds            14809.0
HalfSeconds              7505.0
Name: 25785, dtype: object
Burnsville
 Age                          27
M/F                           M
City                 Burnsville
State                        MN
Country                     USA
Half            0 days 01:20:11
40K             0 days 02:39:12
Pace                    0:06:27
TotalSeconds             9552.0
HalfSeconds              4811.0
Name: 678, dtype: object
Burnt Hills
 Age                          26
M/F                           F
City                Burnt Hills
State                        NY
Country                     USA
Half            0 days 01:42:01
40K             0 days 03:19:16
Pace                    0:08:03
TotalSeconds            11956.0
HalfSeconds              6121.0
Name: 14656, dtype: object
Burnt River
 Age                          53
M/F                           M
City                Burnt River
State                        ON
Country                     CAN
Half            0 days 01:53:10
40K             0 days 05:03:59
Pace                    0:12:20
TotalSeconds            18239.0
HalfSeconds              6790.0
Name: 12174, dtype: object
Burr Ridge
 Age                          45
M/F                           F
City                 Burr Ridge
State                        IL
Country                     USA
Half            0 days 01:37:58
40K             0 days 03:14:08
Pace                    0:07:52
TotalSeconds            11648.0
HalfSeconds              5878.0
Name: 7477, dtype: object
Burridge
 Age                          37
M/F                           M
City                   Burridge
State                       NaN
Country                     GBR
Half            0 days 01:42:06
40K             0 days 03:29:26
Pace                    0:08:30
TotalSeconds            12566.0
HalfSeconds              6126.0
Name: 31697, dtype: object
Burton
 Age                          65
M/F                           M
City                     Burton
State                        OH
Country                     USA
Half            0 days 02:02:38
40K             0 days 04:02:45
Pace                    0:09:49
TotalSeconds            14565.0
HalfSeconds              7358.0
Name: 25334, dtype: object
Busan
 Age                          55
M/F                           M
City                      Busan
State                       NaN
Country                     KOR
Half            0 days 01:38:56
40K             0 days 03:43:58
Pace                    0:09:07
TotalSeconds            13438.0
HalfSeconds              5936.0
Name: 6296, dtype: object
Bussigny
 Age                          44
M/F                           M
City                   Bussigny
State                       NaN
Country                     SUI
Half            0 days 01:38:58
40K             0 days 03:22:03
Pace                    0:08:15
TotalSeconds            12123.0
HalfSeconds              5938.0
Name: 8889, dtype: object
Bussum
 Age                          46
M/F                           M
City                     Bussum
State                       NaN
Country                     NED
Half            0 days 01:50:58
40K             0 days 03:50:11
Pace                    0:09:28
TotalSeconds            13811.0
HalfSeconds              6658.0
Name: 31270, dtype: object
Bussy Saint Georges
 Age                              47
M/F                               M
City            Bussy Saint Georges
State                           NaN
Country                         FRA
Half                0 days 01:35:32
40K                 0 days 03:23:41
Pace                        0:08:22
TotalSeconds                12221.0
HalfSeconds                  5732.0
Name: 5041, dtype: object
Butler
 Age                          58
M/F                           M
City                     Butler
State                        PA
Country                     USA
Half            0 days 02:00:23
40K             0 days 04:03:02
Pace                    0:09:46
TotalSeconds            14582.0
HalfSeconds              7223.0
Name: 19687, dtype: object
Butte
 Age                          50
M/F                           M
City                      Butte
State                        MT
Country                     USA
Half            0 days 01:42:00
40K             0 days 03:27:27
Pace                    0:08:25
TotalSeconds            12447.0
HalfSeconds              6120.0
Name: 13232, dtype: object
Bydgoszcz
 Age                          40
M/F                           M
City                  Bydgoszcz
State                       NaN
Country                     POL
Half            0 days 01:27:21
40K             0 days 02:45:49
Pace                    0:06:40
TotalSeconds             9949.0
HalfSeconds              5241.0
Name: 417, dtype: object
Byfield
 Age                          50
M/F                           M
City                    Byfield
State                        MA
Country                     USA
Half            0 days 01:45:16
40K             0 days 03:40:08
Pace                    0:08:57
TotalSeconds            13208.0
HalfSeconds              6316.0
Name: 14717, dtype: object
Byron
 Age                          45
M/F                           M
City                      Byron
State                        IL
Country                     USA
Half            0 days 01:36:22
40K             0 days 03:09:14
Pace                    0:07:40
TotalSeconds            11354.0
HalfSeconds              5782.0
Name: 8676, dtype: object
Byron Center
 Age                          46
M/F                           F
City               Byron Center
State                        MI
Country                     USA
Half            0 days 01:41:50
40K             0 days 03:21:47
Pace                    0:08:08
TotalSeconds            12107.0
HalfSeconds              6110.0
Name: 20151, dtype: object
Bécancour
 Age                          40
M/F                           M
City                  Bécancour
State                        QC
Country                     CAN
Half            0 days 01:34:32
40K             0 days 03:08:20
Pace                    0:07:36
TotalSeconds            11300.0
HalfSeconds              5672.0
Name: 5608, dtype: object
Caba
 Age                          47
M/F                           M
City                       Caba
State                       NaN
Country                     ARG
Half            0 days 01:53:51
40K             0 days 04:14:40
Pace                    0:10:11
TotalSeconds            15280.0
HalfSeconds              6831.0
Name: 10926, dtype: object
Cabin John
 Age                          44
M/F                           M
City                 Cabin John
State                        MD
Country                     USA
Half            0 days 01:44:41
40K             0 days 03:26:18
Pace                    0:08:21
TotalSeconds            12378.0
HalfSeconds              6281.0
Name: 8410, dtype: object
Caen
 Age                          45
M/F                           M
City                       Caen
State                       NaN
Country                     FRA
Half            0 days 01:52:18
40K             0 days 05:06:52
Pace                    0:12:18
TotalSeconds            18412.0
HalfSeconds              6738.0
Name: 30072, dtype: object
Caguas
 Age                          43
M/F                           F
City                     Caguas
State                        PR
Country                     USA
Half            0 days 01:50:57
40K             0 days 04:01:55
Pace                    0:09:51
TotalSeconds            14515.0
HalfSeconds              6657.0
Name: 10845, dtype: object
Calabasas
 Age                          40
M/F                           M
City                  Calabasas
State                        CA
Country                     USA
Half            0 days 01:29:53
40K             0 days 03:35:21
Pace                    0:08:48
TotalSeconds            12921.0
HalfSeconds              5393.0
Name: 7461, dtype: object
Caldwell
 Age                          51
M/F                           M
City                   Caldwell
State                        NJ
Country                     USA
Half            0 days 01:43:28
40K             0 days 03:29:07
Pace                    0:08:33
TotalSeconds            12547.0
HalfSeconds              6208.0
Name: 13877, dtype: object
Caledon
 Age                          47
M/F                           F
City                    Caledon
State                        ON
Country                     CAN
Half            0 days 01:51:33
40K             0 days 03:39:56
Pace                    0:08:55
TotalSeconds            13196.0
HalfSeconds              6693.0
Name: 22846, dtype: object
Caledon East
 Age                          42
M/F                           F
City               Caledon East
State                        ON
Country                     CAN
Half            0 days 01:43:52
40K             0 days 03:22:07
Pace                    0:08:10
TotalSeconds            12127.0
HalfSeconds              6232.0
Name: 19593, dtype: object
Caledonia
 Age                          41
M/F                           M
City                  Caledonia
State                        WI
Country                     USA
Half            0 days 01:32:47
40K             0 days 03:09:58
Pace                    0:07:42
TotalSeconds            11398.0
HalfSeconds              5567.0
Name: 1898, dtype: object
Calexico
 Age                          46
M/F                           M
City                   Calexico
State                        CA
Country                     USA
Half            0 days 01:43:41
40K             0 days 03:30:08
Pace                    0:08:29
TotalSeconds            12608.0
HalfSeconds              6221.0
Name: 11926, dtype: object
Calgary
 Age                          32
M/F                           M
City                    Calgary
State                        AB
Country                     CAN
Half            0 days 01:27:54
40K             0 days 02:49:01
Pace                    0:06:49
TotalSeconds            10141.0
HalfSeconds              5274.0
Name: 5160, dtype: object
Califon
 Age                          53
M/F                           M
City                    Califon
State                        NJ
Country                     USA
Half            0 days 02:04:13
40K             0 days 03:45:40
Pace                    0:09:05
TotalSeconds            13540.0
HalfSeconds              7453.0
Name: 14852, dtype: object
California
 Age                          41
M/F                           F
City                 California
State                        MD
Country                     USA
Half            0 days 02:20:19
40K             0 days 04:42:12
Pace                    0:11:23
TotalSeconds            16932.0
HalfSeconds              8419.0
Name: 30349, dtype: object
Callaway
 Age                          42
M/F                           M
City                   Callaway
State                        MD
Country                     USA
Half            0 days 01:30:22
40K             0 days 02:57:33
Pace                    0:07:11
TotalSeconds            10653.0
HalfSeconds              5422.0
Name: 2428, dtype: object
Calmar
 Age                          46
M/F                           M
City                     Calmar
State                        IA
Country                     USA
Half            0 days 01:32:03
40K             0 days 02:51:49
Pace                    0:06:54
TotalSeconds            10309.0
HalfSeconds              5523.0
Name: 7084, dtype: object
Calumet
 Age                          70
M/F                           M
City                    Calumet
State                        MI
Country                     USA
Half            0 days 01:54:23
40K             0 days 03:51:22
Pace                    0:09:20
TotalSeconds            13882.0
HalfSeconds              6863.0
Name: 21204, dtype: object
Camanche
 Age                          48
M/F                           M
City                   Camanche
State                        IA
Country                     USA
Half            0 days 01:35:23
40K             0 days 03:29:01
Pace                    0:08:26
TotalSeconds            12541.0
HalfSeconds              5723.0
Name: 9781, dtype: object
Camarillo
 Age                          20
M/F                           F
City                  Camarillo
State                        CA
Country                     USA
Half            0 days 01:31:43
40K             0 days 02:58:46
Pace                    0:07:13
TotalSeconds            10726.0

Camberwell
 Age                          42
M/F                           M
City                 Camberwell
State                       NaN
Country                     AUS
Half            0 days 01:15:20
40K             0 days 02:29:48
Pace                    0:06:04
TotalSeconds             8988.0
HalfSeconds              4520.0
Name: 166, dtype: object
Camberwell, Victoria
 Age                               41
M/F                                M
City            Camberwell, Victoria
State                            NaN
Country                          AUS
Half                 0 days 01:30:50
40K                  0 days 03:02:12
Pace                         0:07:24
TotalSeconds                 10932.0
HalfSeconds                   5450.0
Name: 6010, dtype: object
Cambridge
 Age                          26
M/F                           M
City                  Cambridge
State                        MA
Country                     USA
Half            0 days 01:12:27
40K             0 days 02:19:56
Pace                    0:05:39
TotalSeconds             8396.0
HalfSeconds              4347.0
Name: 103, dtype: object
Cambridge Springs
 Age                            30
M/F                             F
City            Cambridge Springs
State                          PA
Country                       USA
Half              0 days 01:37:52
40K               0 days 03:27:01
Pace                      0:08:23
TotalSeconds              12421.0
HalfSeconds                5872.0
Name: 8278, dtype: object
Camden
 Age                          46
M/F                           M
City                     Camden
State                        DE
Country                     USA
Half            0 days 01:29:45
40K             0 days 02:54:13
Pace                    0:07:01
TotalSeconds            10453.0
HalfSeconds              5385.0
Name: 10394, dtype: object
Camdenton
 Age                          32
M/F                           F
City                  Camdenton
State                        MO
Country                     USA
Half            0 days 01:44:15
40K             0 days 03:25:21
Pace                    0:08:17
TotalSeconds            12321.0
HalfSeconds              6255.0
Name: 16328, dtype: object
Cameron
 Age                          53
M/F                           M
City                    Cameron
State                        AZ
Country                     USA
Half            0 days 01:38:03
40K             0 days 03:12:05
Pace                    0:07:45
TotalSeconds            11525.0
HalfSeconds              5883.0
Name: 11765, dtype: object
Cameron Park
 Age                          47
M/F                           F
City               Cameron Park
State                        CA
Country                     USA
Half            0 days 01:51:41
40K             0 days 03:37:02
Pace                    0:08:43
TotalSeconds            13022.0
HalfSeconds              6701.0
Name: 20457, dtype: object
Cammack Village
 Age                          58
M/F                           M
City            Cammack Village
State                        AR
Country                     USA
Half            0 days 01:39:37
40K             0 days 03:20:48
Pace                    0:08:09
TotalSeconds            12048.0
HalfSeconds              5977.0
Name: 14224, dtype: object
Camp Hill
 Age                          46
M/F                           M
City                  Camp Hill
State                        PA
Country                     USA
Half            0 days 01:27:23
40K             0 days 02:50:06
Pace                    0:07:07
TotalSeconds            10206.0
HalfSeconds              5243.0
Name: 6797, dtype: object
Camp Lejeune
 Age                          44
M/F                           M
City               Camp Lejeune
State                        NC
Country                     USA
Half            0 days 02:16:37
40K             0 days 04:06:21
Pace                    0:09:55
TotalSeconds            14781.0
HalfSeconds              8197.0
Name: 26199, dtype: object
Campbell
 Age                          52
M/F                           M
City                   Campbell
State                        CA
Country                     USA
Half            0 days 01:22:29
40K             0 days 02:47:57
Pace                    0:06:48
TotalSeconds            10077.0
HalfSeconds              4949.0
Name: 636, dtype: object
Campbell River
 Age                          61
M/F                           M
City             Campbell River
State                        BC
Country                     CAN
Half            0 days 01:33:10
40K             0 days 03:05:05
Pace                    0:07:29
TotalSeconds            11105.0
HalfSeconds              5590.0
Name: 7191, dtype: object
Campeche
 Age                          48
M/F                           M
City                   Campeche
State                       NaN
Country                     MEX
Half            0 days 02:10:01
40K             0 days 04:23:14
Pace                    0:10:38
TotalSeconds            15794.0
HalfSeconds              7801.0
Name: 31847, dtype: object
Campinas
 Age                          45
M/F                           F
City                   Campinas
State                       NaN
Country                     BRA
Half            0 days 01:54:48
40K             0 days 03:54:42
Pace                    0:09:30
TotalSeconds            14082.0
HalfSeconds              6888.0
Name: 21893, dtype: object
Campos Dos Goytacazes
 Age                                34
M/F                                 M
City            Campos Dos Goytacazes
State                             NaN
Country                           BRA
Half                  0 days 01:48:34
40K                   0 days 03:39:40
Pace                          0:08:54
TotalSeconds                  13180.0
HalfSeconds                    6514.0
Name: 30265, dtype: object
Camuy
 Age                          47
M/F                           M
City                      Camuy
State                        PR
Country                     USA
Half            0 days 01:29:55
40K             0 days 03:31:52
Pace                    0:08:41
TotalSeconds            12712.0
HalfSeconds              5395.0
Name: 11878, dtype: object
Canal Fulton
 Age                          62
M/F                           M
City               Canal Fulton
State                        OH
Country                     USA
Half            0 days 01:47:14
40K             0 days 03:47:04
Pace                    0:09:14
TotalSeconds            13624.0
HalfSeconds              6434.0
Name: 13207, dtype: object
Canal Winchester
 Age                           25
M/F                            M
City            Canal Winchester
State                         OH
Country                      USA
Half             0 days 01:31:28
40K              0 days 03:14:43
Pace                     0:07:54
TotalSeconds             11683.0
HalfSeconds               5488.0
Name: 3534, dtype: object
Canandaigua
 Age                          39
M/F                           F
City                Canandaigua
State                        NY
Country                     USA
Half            0 days 01:42:27
40K             0 days 03:19:52
Pace                    0:08:04
TotalSeconds            11992.0
HalfSeconds              6147.0
Name: 11883, dtype: object
Canberra
 Age                          43
M/F                           M
City                   Canberra
State                       NaN
Country                     AUS
Half            0 days 01:27:11
40K             0 days 03:19:40
Pace                    0:08:08
TotalSeconds            11980.0
HalfSeconds              5231.0
Name: 4184, dtype: object
Canberra Act
 Age                          48
M/F                           M
City               Canberra Act
State                       NaN
Country                     AUS
Half            0 days 01:44:00
40K             0 days 03:26:11
Pace                    0:08:20
TotalSeconds            12371.0
HalfSeconds              6240.0
Name: 10241, dtype: object
Canby
 Age                          39
M/F                           M
City                      Canby
State                        OR
Country                     USA
Half            0 days 01:29:50
40K             0 days 03:04:51
Pace                    0:07:31
TotalSeconds            11091.0
HalfSeconds              5390.0
Name: 4350, dtype: object
Cancun
 Age                          43
M/F                           M
City                     Cancun
State                       NaN
Country                     MEX
Half            0 days 01:28:13
40K             0 days 02:58:47
Pace                    0:07:20
TotalSeconds            10727.0
HalfSeconds              5293.0
Name: 3047, dtype: object
Cancun Benito Juarez Q.roo
 Age                                     48
M/F                                      F
City            Cancun Benito Juarez Q.roo
State                                  NaN
Country                                MEX
Half                       0 days 01:55:20
40K                        0 days 03:44:48
Pace                               0:09:04
TotalSeconds                       13488.0
HalfSeconds                         6920.0
Name: 23478, dtype: object
Candia
 Age                          42
M/F                           F
City                     Candia
State                        NH
Country                     USA
Half            0 days 01:48:33
40K             0 days 03:29:53
Pace                    0:08:27
TotalSeconds            12593.0
HalfSeconds              6513.0
Name: 20871, dtype: object
Candiac
 Age                          51
M/F                           M
City                    Candiac
State                        QC
Country                     CAN
Half            0 days 01:34:33
40K             0 days 03:01:45
Pace                    0:07:19
TotalSeconds            10905.0
HalfSeconds              5673.0

Name: 8304, dtype: object
Cane Ridge
 Age                          40
M/F                           M
City                 Cane Ridge
State                        TN
Country                     USA
Half            0 days 01:39:55
40K             0 days 03:47:44
Pace                    0:09:12
TotalSeconds            13664.0
HalfSeconds              5995.0
Name: 6185, dtype: object
Canfield
 Age                          21
M/F                           F
City                   Canfield
State                        OH
Country                     USA
Half            0 days 01:40:26
40K             0 days 03:06:51
Pace                    0:07:30
TotalSeconds            11211.0
HalfSeconds              6026.0
Name: 10436, dtype: object
Canonsburg
 Age                          50
M/F                           F
City                 Canonsburg
State                        PA
Country                     USA
Half            0 days 01:55:36
40K             0 days 03:46:18
Pace                    0:09:06
TotalSeconds            13578.0
HalfSeconds              6936.0
Name: 23352, dtype: object
Canovanas
 Age                          35
M/F                           F
City                  Canovanas
State                        PR
Country                     USA
Half            0 days 01:35:55
40K             0 days 03:04:39
Pace                    0:07:26
TotalSeconds            11079.0
HalfSeconds              5755.0
Name: 9975, dtype: object
Canterbury
 Age                          60
M/F                           M
City                 Canterbury
State                        NH
Country                     USA
Half            0 days 01:43:53
40K             0 days 03:30:56
Pace                    0:08:35
TotalSeconds            12656.0
HalfSeconds              6233.0
Name: 15530, dtype: object
Cantley
 Age                          37
M/F                           M
City                    Cantley
State                        QC
Country                     CAN
Half            0 days 01:28:50
40K             0 days 02:53:25
Pace                    0:07:00
TotalSeconds            10405.0
HalfSeconds              5330.0
Name: 4850, dtype: object
Canton
 Age                          22
M/F                           M
City                     Canton
State                        NY
Country                     USA
Half            0 days 01:19:54
40K             0 days 02:35:15
Pace                    0:06:15
TotalSeconds             9315.0
HalfSeconds              4794.0
Name: 1662, dtype: object
Canyon
 Age                          58
M/F                           M
City                     Canyon
State                        TX
Country                     USA
Half            0 days 01:43:54
40K             0 days 03:16:53
Pace                    0:07:56
TotalSeconds            11813.0
HalfSeconds              6234.0
Name: 10742, dtype: object
Canyon Country
 Age                          46
M/F                           M
City             Canyon Country
State                        CA
Country                     USA
Half            0 days 01:49:09
40K             0 days 03:35:27
Pace                    0:08:42
TotalSeconds            12927.0
HalfSeconds              6549.0
Name: 12353, dtype: object
Cap-Sante
 Age                          70
M/F                           M
City                  Cap-Sante
State                        QC
Country                     CAN
Half            0 days 01:43:58
40K             0 days 03:21:20
Pace                    0:08:07
TotalSeconds            12080.0
HalfSeconds              6238.0
Name: 10780, dtype: object
Cape Canaveral
 Age                          60
M/F                           M
City             Cape Canaveral
State                        FL
Country                     USA
Half            0 days 01:43:44
40K             0 days 03:20:37
Pace                    0:08:06
TotalSeconds            12037.0
HalfSeconds              6224.0
Name: 16189, dtype: object
Cape Carteret
 Age                          38
M/F                           M
City              Cape Carteret
State                        NC
Country                     USA
Half            0 days 01:32:04
40K             0 days 03:08:02
Pace                    0:07:38
TotalSeconds            11282.0
HalfSeconds              5524.0
Name: 4957, dtype: object
Cape Charles
 Age                          48
M/F                           F
City               Cape Charles
State                        VA
Country                     USA
Half            0 days 01:54:40
40K             0 days 03:43:22
Pace                    0:08:59
TotalSeconds            13402.0
HalfSeconds              6880.0
Name: 22407, dtype: object
Cape Coral
 Age                          35
M/F                           F
City                 Cape Coral
State                        FL
Country                     USA
Half            0 days 01:37:35
40K             0 days 03:08:48
Pace                    0:07:37
TotalSeconds            11328.0
HalfSeconds              5855.0
Name: 8978, dtype: object
Cape Elizabeth
 Age                          44
M/F                           M
City             Cape Elizabeth
State                        ME
Country                     USA
Half            0 days 01:34:28
40K             0 days 03:06:23
Pace                    0:07:33
TotalSeconds            11183.0
HalfSeconds              5668.0
Name: 8403, dtype: object
Cape Girardeau
 Age                          39
M/F                           M
City             Cape Girardeau
State                        MO
Country                     USA
Half            0 days 01:26:22
40K             0 days 02:56:24
Pace                    0:07:09
TotalSeconds            10584.0
HalfSeconds              5182.0
Name: 2446, dtype: object
Cape May
 Age                          46
M/F                           M
City                   Cape May
State                        NJ
Country                     USA
Half            0 days 01:32:08
40K             0 days 03:14:09
Pace                    0:07:52
TotalSeconds            11649.0
HalfSeconds              5528.0
Name: 5913, dtype: object
Cape Town
 Age                          53
M/F                           M
City                  Cape Town
State                       NaN
Country                     RSA
Half            0 days 01:38:46
40K             0 days 03:35:56
Pace                    0:08:47
TotalSeconds            12956.0
HalfSeconds              5926.0
Name: 8939, dtype: object
Capinghem
 Age                          45
M/F                           M
City                  Capinghem
State                       NaN
Country                     FRA
Half            0 days 01:52:01
40K             0 days 03:56:36
Pace                    0:09:36
TotalSeconds            14196.0
HalfSeconds              6721.0
Name: 2861, dtype: object
Capriolo
 Age                          57
M/F                           M
City                   Capriolo
State                       NaN
Country                     ITA
Half            0 days 01:44:51
40K             0 days 03:29:24
Pace                    0:08:32
TotalSeconds            12564.0
HalfSeconds              6291.0
Name: 17319, dtype: object
Caracas
 Age                          52
M/F                           M
City                    Caracas
State                       NaN
Country                     VEN
Half            0 days 01:32:31
40K             0 days 03:02:04
Pace                    0:07:21
TotalSeconds            10924.0
HalfSeconds              5551.0
Name: 2753, dtype: object
Carbondale
 Age                          33
M/F                           M
City                 Carbondale
State                        PA
Country                     USA
Half            0 days 01:26:14
40K             0 days 02:46:38
Pace                    0:06:42
TotalSeconds             9998.0
HalfSeconds              5174.0
Name: 1412, dtype: object
Cardiff
 Age                          33
M/F                           M
City                    Cardiff
State                        CA
Country                     USA
Half            0 days 01:31:13
40K             0 days 03:11:19
Pace                    0:07:46
TotalSeconds            11479.0
HalfSeconds              5473.0
Name: 4311, dtype: object
Cardiff By The Sea
 Age                             61
M/F                              M
City            Cardiff By The Sea
State                           CA
Country                        USA
Half               0 days 01:56:18
40K                0 days 04:03:58
Pace                       0:09:55
TotalSeconds               14638.0
HalfSeconds                 6978.0
Name: 21787, dtype: object
Carlabad
 Age                          39
M/F                           M
City                   Carlabad
State                        NM
Country                     USA
Half            0 days 02:18:52
40K             0 days 04:46:34
Pace                    0:11:35
TotalSeconds            17194.0
HalfSeconds              8332.0
Name: 26499, dtype: object
Carleton Place
 Age                          49
M/F                           M
City             Carleton Place
State                        ON
Country                     CAN
Half            0 days 01:40:21
40K             0 days 03:26:13
Pace                    0:08:23
TotalSeconds            12373.0
HalfSeconds              6021.0
Name: 10941, dtype: object
Carleton-Sur-Mer
 Age                           66
M/F                            M
City            Carleton-Sur-Mer
State                         QC
Country                      CAN
Half             0 days 02:01:40
40K              0 days 04:13:28
Pace                     0:10:20
TotalSeconds             15208.0
HalfSeconds               7300.0
Name: 25069, dtype: object
Carlinville
 Age                          57
M/F                           M
City                Carlinville
State                        IL
Country                     USA
Half            0 days 01:42:35
40K             0 days 03:23:49
Pace                    0:08:13
TotalSeconds            12229.0
HalfSeconds              6155.0
Name: 12925, dtype: object
Carlisle
 Age                          25
M/F                           F
City                   Carlisle
State                        PA
Country                     USA
Half            0 days 01:29:55
40K             0 days 03:05:25
Pace                    0:07:29
TotalSeconds            11125.0
HalfSeconds              5395.0
Name: 10296, dtype: object
Carlisle Barracks
 Age                            43
M/F                             F
City            Carlisle Barracks
State                          PA
Country                       USA
Half              0 days 01:47:07
40K               0 days 03:28:01
Pace                      0:08:24
TotalSeconds              12481.0
HalfSeconds                6427.0
Name: 20627, dtype: object
Carlsbad
 Age                          34
M/F                           M
City                   Carlsbad
State                        CA
Country                     USA
Half            0 days 01:23:46
40K             0 days 02:46:26
Pace                    0:06:45
TotalSeconds             9986.0
HalfSeconds              5026.0
Name: 2613, dtype: object
Carlton Vic
 Age                          45
M/F                           M
City                Carlton Vic
State                       NaN
Country                     AUS
Half            0 days 01:40:37
40K             0 days 03:18:44
Pace                    0:08:01
TotalSeconds            11924.0
HalfSeconds              6037.0
Name: 11877, dtype: object
Carmel
 Age                          25
M/F                           M
City                     Carmel
State                        IN
Country                     USA
Half            0 days 01:20:32
40K             0 days 02:49:24
Pace                    0:06:51
TotalSeconds            10164.0
HalfSeconds              4832.0
Name: 569, dtype: object
Carmel Valley
 Age                          41
M/F                           F
City              Carmel Valley
State                        CA
Country                     USA
Half            0 days 01:47:12
40K             0 days 03:38:43
Pace                    0:08:54
TotalSeconds            13123.0
HalfSeconds              6432.0
Name: 20389, dtype: object
Carmichael
 Age                          26
M/F                           M
City                 Carmichael
State                        CA
Country                     USA
Half            0 days 01:30:11
40K             0 days 02:51:37
Pace                    0:06:54
TotalSeconds            10297.0
HalfSeconds              5411.0
Name: 5251, dtype: object
Carnation
 Age                          52
M/F                           M
City                  Carnation
State                        WA
Country                     USA
Half            0 days 01:36:22
40K             0 days 03:15:16
Pace                    0:07:54
TotalSeconds            11716.0
HalfSeconds              5782.0
Name: 8641, dtype: object
Carnegie
 Age                          33
M/F                           M
City                   Carnegie
State                        PA
Country                     USA
Half            0 days 01:40:15
40K             0 days 03:21:12
Pace                    0:08:09
TotalSeconds            12072.0
HalfSeconds              6015.0
Name: 4446, dtype: object
Caro
 Age                          50
M/F                           F
City                       Caro
State                        MI
Country                     USA
Half            0 days 01:44:09
40K             0 days 03:18:49
Pace                    0:07:59
TotalSeconds            11929.0
HalfSeconds              6249.0
Name: 18239, dtype: object
Carol Stream
 Age                          39
M/F                           M
City               Carol Stream
State                        IL
Country                     USA
Half            0 days 01:26:08
40K             0 days 03:09:18
Pace                    0:07:47
TotalSeconds            11358.0
HalfSeconds              5168.0
Name: 5725, dtype: object
Carp
 Age                          55
M/F                           M
City                       Carp
State                        ON
Country                     CAN
Half            0 days 01:45:05
40K             0 days 03:31:21
Pace                    0:08:32
TotalSeconds            12681.0
HalfSeconds              6305.0
Name: 15237, dtype: object
Carpinteria
 Age                          51
M/F                           M
City                Carpinteria
State                        CA
Country                     USA
Half            0 days 01:30:01
40K             0 days 02:58:58
Pace                    0:07:12
TotalSeconds            10738.0
HalfSeconds              5401.0
Name: 1470, dtype: object
Carrboro
 Age                          26
M/F                           F
City                   Carrboro
State                        NC
Country                     USA
Half            0 days 01:35:56
40K             0 days 03:18:30
Pace                    0:08:04
TotalSeconds            11910.0
HalfSeconds              5756.0
Name: 11093, dtype: object
Carrollton
 Age                          43
M/F                           M
City                 Carrollton
State                        TX
Country                     USA
Half            0 days 01:31:34
40K             0 days 02:57:52
Pace                    0:07:11
TotalSeconds            10672.0
HalfSeconds              5494.0
Name: 4158, dtype: object
Carryng Place
 Age                          55
M/F                           F
City              Carryng Place
State                        ON
Country                     CAN
Half            0 days 01:50:49
40K             0 days 03:32:22
Pace                    0:08:32
TotalSeconds            12742.0
HalfSeconds              6649.0
Name: 23512, dtype: object
Carshalton Beeches
 Age                             41
M/F                              F
City            Carshalton Beeches
State                          NaN
Country                        GBR
Half               0 days 01:38:18
40K                0 days 03:11:53
Pace                       0:07:45
TotalSeconds               11513.0
HalfSeconds                 5898.0
Name: 10537, dtype: object
Carson
 Age                          38
M/F                           F
City                     Carson
State                        WA
Country                     USA
Half            0 days 01:51:07
40K             0 days 03:45:00
Pace                    0:09:05
TotalSeconds            13500.0
HalfSeconds              6667.0
Name: 19443, dtype: object
Carson City
 Age                          52
M/F                           F
City                Carson City
State                        NV
Country                     USA
Half            0 days 01:58:50
40K             0 days 03:53:43
Pace                    0:09:25
TotalSeconds            14023.0
HalfSeconds              7130.0
Name: 22788, dtype: object
Cartago
 Age                          24
M/F                           F
City                    Cartago
State                       NaN
Country                     CRC
Half            0 days 01:39:40
40K             0 days 03:16:22
Pace                    0:07:56
TotalSeconds            11782.0
HalfSeconds              5980.0
Name: 17331, dtype: object
Cartersville
 Age                          55
M/F                           M
City               Cartersville
State                        GA
Country                     USA
Half            0 days 02:01:24
40K             0 days 04:07:03
Pace                    0:09:58
TotalSeconds            14823.0
HalfSeconds              7284.0
Name: 19227, dtype: object
Carterville
 Age                          52
M/F                           F
City                Carterville
State                        IL
Country                     USA
Half            0 days 01:57:52
40K             0 days 03:50:14
Pace                    0:09:16
TotalSeconds            13814.0
HalfSeconds              7072.0
Name: 24855, dtype: object
Carver
 Age                          47
M/F                           F
City                     Carver
State                        MA
Country                     USA
Half            0 days 02:11:28
40K             0 days 04:40:06
Pace                    0:11:18
TotalSeconds            16806.0
HalfSeconds              7888.0
Name: 30804, dtype: object
Cary
 Age                          35
M/F                           M
City                       Cary
State                        NC
Country                     USA
Half            0 days 01:18:55
40K             0 days 02:35:35
Pace                    0:06:19
TotalSeconds             9335.0
HalfSeconds              4735.0
Name: 867, dtype: object
Casablanca
 Age                          57
M/F                           M
City                 Casablanca
State                       NaN
Country                     MAR
Half            0 days 02:10:55
40K             0 days 04:42:00
Pace                    0:11:22
TotalSeconds            16920.0
HalfSeconds              7855.0
Name: 30063, dtype: object
Casalzuigno-Va
 Age                          47
M/F                           M
City             Casalzuigno-Va
State                       NaN
Country                     ITA
Half            0 days 01:46:01
40K             0 days 04:54:02
Pace                    0:12:11
TotalSeconds            17642.0
HalfSeconds              6361.0
Name: 31612, dtype: object
Cascais
 Age                          71
M/F                           M
City                    Cascais
State                       NaN
Country                     POR
Half            0 days 02:17:23
40K             0 days 04:41:17
Pace                    0:11:19
TotalSeconds            16877.0
HalfSeconds              8243.0
Name: 25537, dtype: object
Caseyville
 Age                          37
M/F                           F
City                 Caseyville
State                        IL

 Age                          26
M/F                           F
City                  Cebu City
State                       NaN
Country                     PHI
Half            0 days 01:21:09
40K             0 days 02:39:12
Pace                    0:06:27
TotalSeconds             9552.0
HalfSeconds              4869.0
Name: F37, dtype: object
Cecil
 Age                          40
M/F                           F
City                      Cecil
State                        PA
Country                     USA
Half            0 days 01:46:21
40K             0 days 03:40:02
Pace                    0:08:54
TotalSeconds            13202.0
HalfSeconds              6381.0
Name: 15084, dtype: object
Cedar Crest
 Age                          57
M/F                           F
City                Cedar Crest
State                        NM
Country                     USA
Half            0 days 01:53:10
40K             0 days 03:48:53
Pace                    0:09:15
TotalSeconds            13733.0
HalfSeconds              6790.0
Name: 21657, dtype: object
Cedar Falls
 Age                          35
M/F                           M
City                Cedar Falls
State                        IA
Country                     USA
Half            0 days 01:40:25
40K             0 days 03:27:49
Pace                    0:08:26
TotalSeconds            12469.0
HalfSeconds              6025.0
Name: 6687, dtype: object
Cedar Hills
 Age                          51
M/F                           F
City                Cedar Hills
State                        UT
Country                     USA
Half            0 days 01:43:12
40K             0 days 03:16:10
Pace                    0:07:54
TotalSeconds            11770.0
HalfSeconds              6192.0
Name: 19039, dtype: object
Cedar Knolls
 Age                          29
M/F                           M
City               Cedar Knolls
State                        NJ
Country                     USA
Half            0 days 01:28:00
40K             0 days 02:53:21
Pace                    0:07:00
TotalSeconds            10401.0
HalfSeconds              5280.0
Name: 1332, dtype: object
Cedar Lake
 Age                          29
M/F                           F
City                 Cedar Lake
State                        IN
Country                     USA
Half            0 days 01:51:37
40K             0 days 04:00:56
Pace                    0:09:42
TotalSeconds            14456.0
HalfSeconds              6697.0
Name: 17100, dtype: object
Cedar Park
 Age                          37
M/F                           M
City                 Cedar Park
State                        TX
Country                     USA
Half            0 days 01:26:21
40K             0 days 02:48:52
Pace                    0:06:48
TotalSeconds            10132.0
HalfSeconds              5181.0
Name: 6432, dtype: object
Cedar Rapids
 Age                          30
M/F                           M
City               Cedar Rapids
State                        IA
Country                     USA
Half            0 days 01:22:59
40K             0 days 02:41:02
Pace                    0:06:29
TotalSeconds             9662.0
HalfSeconds              4979.0
Name: 1875, dtype: object
Cedarburg
 Age                          52
M/F                           F
City                  Cedarburg
State                        WI
Country                     USA
Half            0 days 01:50:49
40K             0 days 03:46:46
Pace                    0:09:13
TotalSeconds            13606.0
HalfSeconds              6649.0
Name: 21227, dtype: object
Celbridge
 Age                          39
M/F                           M
City                  Celbridge
State                       NaN
Country                     IRL
Half            0 days 01:31:01
40K             0 days 03:00:14
Pace                    0:07:16
TotalSeconds            10814.0
HalfSeconds              5461.0
Name: 3778, dtype: object
Celebration
 Age                          64
M/F                           M
City                Celebration
State                        FL
Country                     USA
Half            0 days 01:58:03
40K             0 days 03:57:06
Pace                    0:09:34
TotalSeconds            14226.0
HalfSeconds              7083.0
Name: 23433, dtype: object
Celina
 Age                          43
M/F                           M
City                     Celina
State                        TX
Country                     USA
Half            0 days 01:35:43
40K             0 days 03:03:33
Pace                    0:07:24
TotalSeconds            11013.0
HalfSeconds              5743.0
Name: 6740, dtype: object
Cellatica
 Age                          37
M/F                           M
City                  Cellatica
State                       NaN
Country                     ITA
Half            0 days 02:04:33
40K             0 days 04:18:53
Pace                    0:10:26
TotalSeconds            15533.0
HalfSeconds              7473.0
Name: 31458, dtype: object
Centennial
 Age                          34
M/F                           M
City                 Centennial
State                        CO
Country                     USA
Half            0 days 01:24:20
40K             0 days 02:40:02
Pace                    0:06:27
TotalSeconds             9602.0
HalfSeconds              5060.0
Name: 919, dtype: object
Center Ossipee
 Age                          44
M/F                           F
City             Center Ossipee
State                        NH
Country                     USA
Half            0 days 01:45:44
40K             0 days 03:29:54
Pace                    0:08:28
TotalSeconds            12594.0
HalfSeconds              6344.0
Name: 14792, dtype: object
Center Point
 Age                          29
M/F                           F
City               Center Point
State                        IA
Country                     USA
Half            0 days 01:40:32
40K             0 days 03:22:36
Pace                    0:08:13
TotalSeconds            12156.0
HalfSeconds              6032.0
Name: 12624, dtype: object
Centereach
 Age                          23
M/F                           F
City                 Centereach
State                        NY
Country                     USA
Half            0 days 01:48:51
40K             0 days 03:27:26
Pace                    0:08:19
TotalSeconds            12446.0
HalfSeconds              6531.0
Name: 13044, dtype: object
Centerport
 Age                          25
M/F                           M
City                 Centerport
State                        NY
Country                     USA
Half            0 days 01:44:26
40K             0 days 03:33:03
Pace                    0:08:40
TotalSeconds            12783.0
HalfSeconds              6266.0
Name: 27524, dtype: object
Centerville
 Age                          38
M/F                           M
City                Centerville
State                        UT
Country                     USA
Half            0 days 01:24:55
40K             0 days 02:46:22
Pace                    0:06:42
TotalSeconds             9982.0
HalfSeconds              5095.0
Name: 1150, dtype: object
Central Square
 Age                          36
M/F                           F
City             Central Square
State                        NY
Country                     USA
Half            0 days 01:41:40
40K             0 days 03:18:03
Pace                    0:08:00
TotalSeconds            11883.0
HalfSeconds              6100.0
Name: 13824, dtype: object
Centre Hall
 Age                          38
M/F                           M
City                Centre Hall
State                        PA
Country                     USA
Half            0 days 01:32:58
40K             0 days 03:26:35
Pace                    0:08:23
TotalSeconds            12395.0
HalfSeconds              5578.0
Name: 2843, dtype: object
Centreville
 Age                          32
M/F                           F
City                Centreville
State                        VA
Country                     USA
Half            0 days 01:46:37
40K             0 days 03:24:15
Pace                    0:08:13
TotalSeconds            12255.0
HalfSeconds              6397.0
Name: 16664, dtype: object
Centurion
 Age                          40
M/F                           M
City                  Centurion
State                       NaN
Country                     RSA
Half            0 days 01:32:20
40K             0 days 03:05:03
Pace                    0:07:30
TotalSeconds            11103.0
HalfSeconds              5540.0
Name: 2617, dtype: object
Cergy
 Age                          38
M/F                           F
City                      Cergy
State                       NaN
Country                     FRA
Half            0 days 01:39:52
40K             0 days 03:13:59
Pace                    0:07:52
TotalSeconds            11639.0
HalfSeconds              5992.0
Name: 17775, dtype: object
Cerritos
 Age                          31
M/F                           M
City                   Cerritos
State                        CA
Country                     USA
Half            0 days 01:33:21
40K             0 days 03:15:36
Pace                    0:07:55
TotalSeconds            11736.0
HalfSeconds              5601.0
Name: 4686, dtype: object
Cessnock
 Age                          57
M/F                           M
City                   Cessnock
State                       NaN
Country                     AUS
Half            0 days 01:42:43
40K             0 days 03:26:36
Pace                    0:08:22
TotalSeconds            12396.0
HalfSeconds              6163.0
Name: 18886, dtype: object
Chadds Ford
 Age                          35
M/F                           M
City                Chadds Ford
State                        PA
Country                     USA
Half            0 days 01:32:01
40K             0 days 03:06:16
Pace                    0:07:33
TotalSeconds            11176.0
HalfSeconds              5521.0
Name: 5918, dtype: object
Chagrin Falls
 Age                          36
M/F                           M
City              Chagrin Falls
State                        OH
Country                     USA
Half            0 days 01:31:04
40K             0 days 02:56:59
Pace                    0:07:10
TotalSeconds            10619.0
HalfSeconds              5464.0
Name: 4662, dtype: object
Chai Wan
 Age                          40
M/F                           F
City                   Chai Wan
State                       NaN
Country                     HKG
Half            0 days 01:48:08
40K             0 days 03:29:15
Pace                    0:08:23
TotalSeconds            12555.0
HalfSeconds              6488.0
Name: 14149, dtype: object
Chalfont
 Age                          45
M/F                           M
City                   Chalfont
State                        PA
Country                     USA
Half            0 days 01:33:15
40K             0 days 03:08:19
Pace                    0:07:40
TotalSeconds            11299.0
HalfSeconds              5595.0
Name: 6458, dtype: object
Chalfont St Peter
 Age                            47
M/F                             M
City            Chalfont St Peter
State                         NaN
Country                       GBR
Half              0 days 01:26:53
40K               0 days 02:54:46
Pace                      0:07:05
TotalSeconds              10486.0
HalfSeconds                5213.0
Name: 1058, dtype: object
Chambersburg
 Age                          47
M/F                           M
City               Chambersburg
State                        PA
Country                     USA
Half            0 days 01:31:02
40K             0 days 02:57:52
Pace                    0:07:13
TotalSeconds            10672.0
HalfSeconds              5462.0
Name: 5077, dtype: object
Chambly
 Age                          45
M/F                           M
City                    Chambly
State                        QC
Country                     CAN
Half            0 days 01:36:38
40K             0 days 03:12:45
Pace                    0:07:47
TotalSeconds            11565.0
HalfSeconds              5798.0
Name: 9155, dtype: object
Champaign
 Age                          36
M/F                           M
City                  Champaign
State                        IL
Country                     USA
Half            0 days 01:29:46
40K             0 days 03:12:28
Pace                    0:07:46
TotalSeconds            11548.0
HalfSeconds              5386.0
Name: 2781, dtype: object
Champlin
 Age                          37
M/F                           M
City                   Champlin
State                        MN
Country                     USA
Half            0 days 01:25:10
40K             0 days 02:46:46
Pace                    0:06:44
TotalSeconds            10006.0
HalfSeconds              5110.0
Name: 2365, dtype: object
Chandler
 Age                          35
M/F                           M
City                   Chandler
State                        AZ
Country                     USA
Half            0 days 01:18:42
40K             0 days 02:47:57
Pace                    0:06:49
TotalSeconds            10077.0
HalfSeconds              4722.0
Name: 279, dtype: object
Changhua
 Age                          61
M/F                           M
City                   Changhua
State                       NaN
Country                     TWN
Half            0 days 01:50:05
40K             0 days 03:43:34
Pace                    0:09:04
TotalSeconds            13414.0
HalfSeconds              6605.0
Name: 22050, dtype: object
Changhua County
 Age                          56
M/F                           M
City            Changhua County
State                       NaN
Country                     TWN
Half            0 days 01:35:22
40K             0 days 04:04:08
Pace                    0:10:03
TotalSeconds            14648.0
HalfSeconds              5722.0
Name: 5339, dtype: object
Chanhassen
 Age                          41
M/F                           M
City                 Chanhassen
State                        MN
Country                     USA
Half            0 days 01:25:38
40K             0 days 03:11:07
Pace                    0:07:52
TotalSeconds            11467.0
HalfSeconds              5138.0
Name: 1274, dtype: object
Chantilly
 Age                          30
M/F                           M
City                  Chantilly
State                        VA
Country                     USA
Half            0 days 01:23:48
40K             0 days 02:44:35
Pace                    0:06:38
TotalSeconds             9875.0
HalfSeconds              5028.0
Name: 2633, dtype: object
Chapel Hill
 Age                          29
M/F                           M
City                Chapel Hill
State                        NC
Country                     USA
Half            0 days 01:15:24
40K             0 days 02:32:13
Pace                    0:06:10
TotalSeconds             9133.0
HalfSeconds              4524.0
Name: 222, dtype: object
Chapin
 Age                          39
M/F                           F
City                     Chapin
State                        SC
Country                     USA
Half            0 days 01:47:17
40K             0 days 03:38:48
Pace                    0:08:52
TotalSeconds            13128.0
HalfSeconds              6437.0
Name: 20102, dtype: object
Chapmanville
 Age                          37
M/F                           F
City               Chapmanville
State                        WV
Country                     USA
Half            0 days 01:53:41
40K             0 days 03:51:12
Pace                    0:09:18
TotalSeconds            13872.0
HalfSeconds              6821.0
Name: 14918, dtype: object
Chappaqua
 Age                          23
M/F                           M
City                  Chappaqua
State                        NY
Country                     USA
Half            0 days 01:17:12
40K             0 days 02:37:40
Pace                    0:06:27
TotalSeconds             9460.0
HalfSeconds              4632.0
Name: 781, dtype: object
Charleston
 Age                          27
M/F                           M
City                 Charleston
State                        SC
Country                     USA
Half            0 days 01:29:58
40K             0 days 02:56:58
Pace                    0:07:10
TotalSeconds            10618.0
HalfSeconds              5398.0
Name: 4131, dtype: object
Charlestown
 Age                          30
M/F                           F
City                Charlestown
State                        MA
Country                     USA
Half            0 days 01:21:09
40K             0 days 02:41:40
Pace                    0:06:32
TotalSeconds             9700.0
HalfSeconds              4869.0
Name: F21, dtype: object
Charlotte
 Age                          42
M/F                           M
City                  Charlotte
State                        NC
Country                     USA
Half            0 days 01:21:19
40K             0 days 02:36:04
Pace                    0:06:17
TotalSeconds             9364.0
HalfSeconds              4879.0
Name: 1540, dtype: object
Charlottenlund
 Age                          48
M/F                           F
City             Charlottenlund
State                       NaN
Country                     DEN
Half            0 days 01:43:15
40K             0 days 03:26:28
Pace                    0:08:22
TotalSeconds            12388.0
HalfSeconds              6195.0
Name: 17819, dtype: object
Charlottesville
 Age                          22
M/F                           M
City            Charlottesville
State                        VA
Country                     USA
Half            0 days 01:14:23
40K             0 days 02:39:15
Pace                    0:06:31
TotalSeconds             9555.0
HalfSeconds              4463.0
Name: 269, dtype: object
Charlottetown
 Age                          33
M/F                           M
City              Charlottetown
State                        PE
Country                     CAN
Half            0 days 01:18:01
40K             0 days 02:31:24
Pace                    0:06:08
TotalSeconds             9084.0
HalfSeconds              4681.0
Name: 369, dtype: object
Charlton
 Age                          24
M/F                           F
City                   Charlton
State                        NY
Country                     USA
Half            0 days 01:27:42
40K             0 days 03:05:16
Pace                    0:07:31
TotalSeconds            11116.0
HalfSeconds              5262.0
Name: 2136, dtype: object
Chaska
 Age                          43
M/F                           F
City                     Chaska
State                        MN
Country                     USA
Half            0 days 01:38:05
40K             0 days 03:12:18
Pace                    0:07:46
TotalSeconds            11538.0
HalfSeconds              5885.0
Name: 9477, dtype: object
Chateau Richer
 Age                          60
M/F                           M
City             Chateau Richer
State                        QC
Country                     CAN
Half            0 days 01:55:12
40K             0 days 03:52:58
Pace                    0:09:26
TotalSeconds            13978.0
HalfSeconds              6912.0
Name: 22141, dtype: object
Chateauneuf Sur Charente
 Age                                   40
M/F                                    M
City            Chateauneuf Sur Charente
State                                NaN
Country                              FRA
Half                     0 days 01:37:50
40K                      0 days 03:18:46
Pace                             0:08:03
TotalSeconds                     11926.0
HalfSeconds                       5870.0
Name: 5163, dtype: object
Chatham
 Age                          22
M/F                           M
City                    Chatham
State                        NJ
Country                     USA

Name: 15512, dtype: object
Chester
 Age                          38
M/F                           M
City                    Chester
State                        NH
Country                     USA
Half            0 days 01:32:58
40K             0 days 03:08:24
Pace                    0:07:40
TotalSeconds            11304.0
HalfSeconds              5578.0
Name: 6025, dtype: object
Chester Springs
 Age                          40
M/F                           M
City            Chester Springs
State                        PA
Country                     USA
Half            0 days 01:33:48
40K             0 days 03:10:21
Pace                    0:07:45
TotalSeconds            11421.0
HalfSeconds              5628.0
Name: 8555, dtype: object
Chesterbrook
 Age                          34
M/F                           M
City               Chesterbrook
State                        PA
Country                     USA
Half            0 days 01:28:38
40K             0 days 03:16:05
Pace                    0:07:56
TotalSeconds            11765.0
HalfSeconds              5318.0
Name: 4301, dtype: object
Chesterfield
 Age                          32
M/F                           M
City               Chesterfield
State                        VA
Country                     USA
Half            0 days 01:29:39
40K             0 days 02:54:30
Pace                    0:07:03
TotalSeconds            10470.0
HalfSeconds              5379.0
Name: 1576, dtype: object
Chesterland
 Age                          22
M/F                           M
City                Chesterland
State                        OH
Country                     USA
Half            0 days 01:28:28
40K             0 days 03:06:21
Pace                    0:07:33
TotalSeconds            11181.0
HalfSeconds              5308.0
Name: 2725, dtype: object
Chesterton
 Age                          67
M/F                           M
City                 Chesterton
State                        IN
Country                     USA
Half            0 days 02:10:17
40K             0 days 04:36:26
Pace                    0:12:51
TotalSeconds            16586.0
HalfSeconds              7817.0
Name: 25676, dtype: object
Chestnut
 Age                          27
M/F                           F
City                   Chestnut
State                        IL
Country                     USA
Half            0 days 01:45:25
40K             0 days 03:29:42
Pace                    0:08:27
TotalSeconds            12582.0
HalfSeconds              6325.0
Name: 17199, dtype: object
Chestnut Hill
 Age                          22
M/F                           M
City              Chestnut Hill
State                        MA
Country                     USA
Half            0 days 01:20:16
40K             0 days 02:35:56
Pace                    0:06:45
TotalSeconds             9356.0
HalfSeconds              4816.0
Name: 847, dtype: object
Cheung Sha Wan
 Age                          46
M/F                           M
City             Cheung Sha Wan
State                       NaN
Country                     HKG
Half            0 days 01:35:59
40K             0 days 03:20:06
Pace                    0:08:12
TotalSeconds            12006.0
HalfSeconds              5759.0
Name: 10892, dtype: object
Chevilly Larue
 Age                          44
M/F                           F
City             Chevilly Larue
State                       NaN
Country                     FRA
Half            0 days 01:45:54
40K             0 days 03:26:07
Pace                    0:08:18
TotalSeconds            12367.0
HalfSeconds              6354.0
Name: 19919, dtype: object
Chevy Chase
 Age                          45
M/F                           M
City                Chevy Chase
State                        MD
Country                     USA
Half            0 days 01:28:20
40K             0 days 02:59:40
Pace                    0:07:19
TotalSeconds            10780.0
HalfSeconds              5300.0
Name: 3912, dtype: object
Cheyenne
 Age                          35
M/F                           M
City                   Cheyenne
State                        WY
Country                     USA
Half            0 days 01:31:36
40K             0 days 03:09:42
Pace                    0:07:46
TotalSeconds            11382.0
HalfSeconds              5496.0
Name: 6731, dtype: object
Chiaravalle - An
 Age                           50
M/F                            M
City            Chiaravalle - An
State                        NaN
Country                      ITA
Half             0 days 01:49:21
40K              0 days 03:30:44
Pace                     0:08:32
TotalSeconds             12644.0
HalfSeconds               6561.0
Name: 31626, dtype: object
Chiba
 Age                          47
M/F                           M
City                      Chiba
State                       NaN
Country                     JPN
Half            0 days 01:32:50
40K             0 days 03:03:59
Pace                    0:07:24
TotalSeconds            11039.0
HalfSeconds              5570.0
Name: 1796, dtype: object
Chicago
 Age                          26
M/F                           M
City                    Chicago
State                        IL
Country                     USA
Half            0 days 01:13:39
40K             0 days 02:25:41
Pace                    0:05:53
TotalSeconds             8741.0
HalfSeconds              4419.0
Name: 742, dtype: object
Chichester
 Age                          43
M/F                           M
City                 Chichester
State                        NY
Country                     USA
Half            0 days 01:29:52
40K             0 days 02:55:13
Pace                    0:07:03
TotalSeconds            10513.0
HalfSeconds              5392.0
Name: 5602, dtype: object
Chico
 Age                          42
M/F                           F
City                      Chico
State                        CA
Country                     USA
Half            0 days 01:34:15
40K             0 days 03:10:49
Pace                    0:07:46
TotalSeconds            11449.0
HalfSeconds              5655.0
Name: 9190, dtype: object
Chicopee
 Age                          34
M/F                           M
City                   Chicopee
State                        MA
Country                     USA
Half            0 days 01:49:15
40K             0 days 03:36:40
Pace                    0:08:46
TotalSeconds            13000.0
HalfSeconds              6555.0
Name: 9762, dtype: object
Chicoutimi
 Age                          31
M/F                           M
City                 Chicoutimi
State                        QC
Country                     CAN
Half            0 days 01:20:14
40K             0 days 02:44:31
Pace                    0:06:41
TotalSeconds             9871.0
HalfSeconds              4814.0
Name: 1434, dtype: object
Chihuahua
 Age                          36
M/F                           M
City                  Chihuahua
State                       NaN
Country                     MEX
Half            0 days 01:29:59
40K             0 days 03:00:24
Pace                    0:07:23
TotalSeconds            10824.0
HalfSeconds              5399.0
Name: 5794, dtype: object
Chillicothe
 Age                          35
M/F                           F
City                Chillicothe
State                        OH
Country                     USA
Half            0 days 01:45:16
40K             0 days 03:21:34
Pace                    0:08:06
TotalSeconds            12094.0
HalfSeconds              6316.0
Name: 19171, dtype: object
Chilton
 Age                          51
M/F                           F
City                    Chilton
State                        WI
Country                     USA
Half            0 days 02:05:07
40K             0 days 04:05:16
Pace                    0:09:53
TotalSeconds            14716.0
HalfSeconds              7507.0
Name: 23327, dtype: object
Chinnor
 Age                          55
M/F                           M
City                    Chinnor
State                       NaN
Country                     GBR
Half            0 days 01:52:01
40K             0 days 04:00:51
Pace                    0:09:44
TotalSeconds            14451.0
HalfSeconds              6721.0
Name: 13933, dtype: object
Chino
 Age                          28
M/F                           M
City                      Chino
State                        CA
Country                     USA
Half            0 days 01:35:37
40K             0 days 03:07:54
Pace                    0:07:33
TotalSeconds            11274.0
HalfSeconds              5737.0
Name: 3801, dtype: object
Chino Hills
 Age                          52
M/F                           F
City                Chino Hills
State                        CA
Country                     USA
Half            0 days 01:34:29
40K             0 days 03:10:13
Pace                    0:07:41
TotalSeconds            11413.0
HalfSeconds              5669.0
Name: 4226, dtype: object
Chippewa Falls
 Age                          51
M/F                           M
City             Chippewa Falls
State                        WI
Country                     USA
Half            0 days 01:49:46
40K             0 days 03:49:45
Pace                    0:09:17
TotalSeconds            13785.0
HalfSeconds              6586.0
Name: 13008, dtype: object
Chipstead
 Age                          40
M/F                           F
City                  Chipstead
State                       NaN
Country                     GBR
Half            0 days 02:01:13
40K             0 days 04:01:17
Pace                    0:09:42
TotalSeconds            14477.0
HalfSeconds              7273.0
Name: 20757, dtype: object
Chislehurst
 Age                          43
M/F                           M
City                Chislehurst
State                       NaN
Country                     GBR
Half            0 days 01:34:33
40K             0 days 03:06:05
Pace                    0:07:32
TotalSeconds            11165.0
HalfSeconds              5673.0
Name: 6519, dtype: object
Choctaw
 Age                          39
M/F                           M
City                    Choctaw
State                        OK
Country                     USA
Half            0 days 01:30:01
40K             0 days 02:57:04
Pace                    0:07:10
TotalSeconds            10624.0
HalfSeconds              5401.0
Name: 5164, dtype: object
Chongqing
 Age                          37
M/F                           M
City                  Chongqing
State                       NaN
Country                     CHN
Half            0 days 01:41:56
40K             0 days 03:15:45
Pace                    0:07:53
TotalSeconds            11745.0
HalfSeconds              6116.0
Name: 3955, dtype: object
Christchurch
 Age                          39
M/F                           M
City               Christchurch
State                       NaN
Country                     NZL
Half            0 days 01:28:02
40K             0 days 02:50:52
Pace                    0:06:54
TotalSeconds            10252.0
HalfSeconds              5282.0
Name: 5818, dtype: object
Christiansburg
 Age                          54
M/F                           F
City             Christiansburg
State                        VA
Country                     USA
Half            0 days 01:51:18
40K             0 days 03:29:52
Pace                    0:08:26
TotalSeconds            12592.0
HalfSeconds              6678.0
Name: 24113, dtype: object
Christiansted
 Age                          38
M/F                           M
City              Christiansted
State                        VI
Country                     USA
Half            0 days 02:03:19
40K             0 days 03:56:51
Pace                    0:09:31
TotalSeconds            14211.0
HalfSeconds              7399.0
Name: 27381, dtype: object
Chuckey
 Age                          45
M/F                           M
City                    Chuckey
State                        TN
Country                     USA
Half            0 days 01:35:17
40K             0 days 03:06:45
Pace                    0:07:33
TotalSeconds            11205.0
HalfSeconds              5717.0
Name: 8536, dtype: object
Chula Vista
 Age                          24
M/F                           M
City                Chula Vista
State                        CA
Country                     USA
Half            0 days 01:29:34
40K             0 days 03:10:15
Pace                    0:08:06
TotalSeconds            11415.0
HalfSeconds              5374.0
Name: 5290, dtype: object
Chunchula
 Age                          34
M/F                           F
City                  Chunchula
State                        AL
Country                     USA
Half            0 days 01:44:39
40K             0 days 03:28:48
Pace                    0:08:26
TotalSeconds            12528.0
HalfSeconds              6279.0
Name: 17894, dtype: object
Churchville
 Age                          34
M/F                           M
City                Churchville
State                        MD
Country                     USA
Half            0 days 01:41:15
40K             0 days 03:33:56
Pace                    0:08:43
TotalSeconds            12836.0
HalfSeconds              6075.0
Name: 27479, dtype: object
Churubusco
 Age                          26
M/F                           M
City                 Churubusco
State                        IN
Country                     USA
Half            0 days 01:33:32
40K             0 days 03:01:28
Pace                    0:07:19
TotalSeconds            10888.0
HalfSeconds              5612.0
Name: 5324, dtype: object
Cicero
 Age                          21
M/F                           F
City                     Cicero
State                        NY
Country                     USA
Half            0 days 01:41:19
40K             0 days 03:18:17
Pace                    0:08:01
TotalSeconds            11897.0
HalfSeconds              6079.0
Name: 13391, dtype: object
Cicinnati
 Age                          36
M/F                           F
City                  Cicinnati
State                        OH
Country                     USA
Half            0 days 01:39:50
40K             0 days 03:15:53
Pace                    0:07:55
TotalSeconds            11753.0
HalfSeconds              5990.0
Name: 9830, dtype: object
Cincinnati
 Age                          27
M/F                           M
City                 Cincinnati
State                        OH
Country                     USA
Half            0 days 01:18:46
40K             0 days 02:36:04
Pace                    0:06:18
TotalSeconds             9364.0
HalfSeconds              4726.0
Name: 667, dtype: object
Cingoli-Mc
 Age                          45
M/F                           M
City                 Cingoli-Mc
State                       NaN
Country                     ITA
Half            0 days 01:37:36
40K             0 days 03:12:22
Pace                    0:07:44
TotalSeconds            11542.0
HalfSeconds              5856.0
Name: 9994, dtype: object
Circle Pines
 Age                          27
M/F                           F
City               Circle Pines
State                        MN
Country                     USA
Half            0 days 01:45:43
40K             0 days 03:29:10
Pace                    0:08:31
TotalSeconds            12550.0
HalfSeconds              6343.0
Name: 14849, dtype: object
Citrus Heights
 Age                          37
M/F                           M
City             Citrus Heights
State                        CA
Country                     USA
Half            0 days 01:32:46
40K             0 days 03:06:47
Pace                    0:07:33
TotalSeconds            11207.0
HalfSeconds              5566.0
Name: 3313, dtype: object
City Beach
 Age                          44
M/F                           F
City                 City Beach
State                       NaN
Country                     AUS
Half            0 days 01:34:16
40K             0 days 03:12:16
Pace                    0:07:47
TotalSeconds            11536.0
HalfSeconds              5656.0
Name: 5549, dtype: object
Ciudad Autonoma De Buenos Aires
 Age                                          37
M/F                                           M
City            Ciudad Autonoma De Buenos Aires
State                                       NaN
Country                                     ARG
Half                            0 days 01:39:08
40K                             0 days 03:32:30
Pace                                    0:08:35
TotalSeconds                            12750.0
HalfSeconds                              5948.0
Name: 2795, dtype: object
Ciudad De Buenos Aires
 Age                                 38
M/F                                  M
City            Ciudad De Buenos Aires
State                              NaN
Country                            ARG
Half                   0 days 01:44:05
40K                    0 days 03:39:10
Pace                           0:08:51
TotalSeconds                   13150.0
HalfSeconds                     6245.0
Name: 6475, dtype: object
Ciudad De Guatemala
 Age                              64
M/F                               M
City            Ciudad De Guatemala
State                           NaN
Country                         GUA
Half                0 days 01:33:59
40K                 0 days 03:22:15
Pace                        0:08:17
TotalSeconds                12135.0
HalfSeconds                  5639.0
Name: 8633, dtype: object
Ciudad De Mexico
 Age                           32
M/F                            F
City            Ciudad De Mexico
State                        NaN
Country                      MEX
Half             0 days 01:35:37
40K              0 days 03:14:04
Pace                     0:07:51
TotalSeconds             11644.0
HalfSeconds               5737.0
Name: 16527, dtype: object
Ciudad De México
 Age                           45
M/F                            M
City            Ciudad De México
State                        NaN
Country                      MEX
Half             0 days 01:24:41
40K              0 days 02:51:46
Pace                     0:06:58
TotalSeconds             10306.0
HalfSeconds               5081.0
Name: 3635, dtype: object
Ciudad Guzman Jalisco
 Age                                22
M/F                                 M
City            Ciudad Guzman Jalisco
State                             NaN
Country                           MEX
Half                  0 days 01:23:38
40K                   0 days 03:01:13
Pace                          0:07:22
TotalSeconds                  10873.0
HalfSeconds                    5018.0
Name: 4071, dtype: object
Ciudad Victoria, Tamaulipas
 Age                                      61
M/F                                       M
City            Ciudad Victoria, Tamaulipas
State                                   NaN
Country                                 MEX
Half                        0 days 01:43:18
40K                         0 days 03:30:02
Pace                                0:08:29
TotalSeconds                        12602.0
HalfSeconds                          6198.0
Name: 20615, dtype: object
Ciudad de México
 Age                           33
M/F                            M
City            Ciudad de México
State                        NaN
Country                      MEX
Half             0 days 01:32:07
40K              0 days 02:53:01
Pace                     0:06:57
TotalSeconds             10381.0
HalfSeconds               5527.0
Name: 4070, dtype: object
Cividate Al Piano
 Age                            29
M/F                             F
City            Cividate Al Piano
State                         NaN
Country                       ITA
Half              0 days 02:04:33
40K               0 days 04:18:55
Pace                      0:10:26
TotalSeconds              15535.0
HalfSeconds                7473.0
Name: 31526, dtype: object
Clackamas

Clarks Summit
 Age                          25
M/F                           F
City              Clarks Summit
State                        PA
Country                     USA
Half            0 days 01:39:58
40K             0 days 03:12:37
Pace                    0:07:46
TotalSeconds            11557.0
HalfSeconds              5998.0
Name: 16303, dtype: object
Clarksboro
 Age                          69
M/F                           F
City                 Clarksboro
State                        NJ
Country                     USA
Half            0 days 02:05:17
40K             0 days 04:08:13
Pace                    0:10:00
TotalSeconds            14893.0
HalfSeconds              7517.0
Name: 15547, dtype: object
Clarksburg
 Age                          37
M/F                           F
City                 Clarksburg
State                        WV
Country                     USA
Half            0 days 01:46:03
40K             0 days 03:24:58
Pace                    0:08:16
TotalSeconds            12298.0
HalfSeconds              6363.0
Name: 17872, dtype: object
Clarkston
 Age                          25
M/F                           M
City                  Clarkston
State                        MI
Country                     USA
Half            0 days 01:21:15
40K             0 days 02:40:43
Pace                    0:06:30
TotalSeconds             9643.0
HalfSeconds              4875.0
Name: 650, dtype: object
Clarksville
 Age                          20
M/F                           F
City                Clarksville
State                        MD
Country                     USA
Half            0 days 01:35:49
40K             0 days 03:02:10
Pace                    0:07:20
TotalSeconds            10930.0
HalfSeconds              5749.0
Name: 11569, dtype: object
Clathymore, Perthshire
 Age                                 49
M/F                                  F
City            Clathymore, Perthshire
State                              NaN
Country                            GBR
Half                   0 days 01:54:45
40K                    0 days 03:47:56
Pace                           0:09:11
TotalSeconds                   13676.0
HalfSeconds                     6885.0
Name: 22398, dtype: object
Clawson
 Age                          56
M/F                           M
City                    Clawson
State                        MI
Country                     USA
Half            0 days 01:48:35
40K             0 days 03:30:14
Pace                    0:08:28
TotalSeconds            12614.0
HalfSeconds              6515.0
Name: 19135, dtype: object
Clay
 Age                          37
M/F                           F
City                       Clay
State                        NY
Country                     USA
Half            0 days 01:33:53
40K             0 days 03:04:29
Pace                    0:07:27
TotalSeconds            11069.0
HalfSeconds              5633.0
Name: 8974, dtype: object
Clayfield
 Age                          39
M/F                           M
City                  Clayfield
State                       NaN
Country                     AUS
Half            0 days 01:59:02
40K             0 days 03:46:18
Pace                    0:09:07
TotalSeconds            13578.0
HalfSeconds              7142.0
Name: 27288, dtype: object
Claymont
 Age                          31
M/F                           M
City                   Claymont
State                        DE
Country                     USA
Half            0 days 01:28:48
40K             0 days 02:57:47
Pace                    0:07:14
TotalSeconds            10667.0
HalfSeconds              5328.0
Name: 4822, dtype: object
Clayton
 Age                          26
M/F                           M
City                    Clayton
State                        MO
Country                     USA
Half            0 days 01:20:50
40K             0 days 02:35:34
Pace                    0:06:18
TotalSeconds             9334.0
HalfSeconds              4850.0
Name: 581, dtype: object
Clear Lake
 Age                          41
M/F                           F
City                 Clear Lake
State                        SD
Country                     USA
Half            0 days 01:55:33
40K             0 days 03:53:06
Pace                    0:09:21
TotalSeconds            13986.0
HalfSeconds              6933.0
Name: 21390, dtype: object
Clearfield
 Age                          31
M/F                           F
City                 Clearfield
State                        UT
Country                     USA
Half            0 days 01:43:28
40K             0 days 03:18:29
Pace                    0:07:58
TotalSeconds            11909.0
HalfSeconds              6208.0
Name: 14241, dtype: object
Clearwater
 Age                          35
M/F                           F
City                 Clearwater
State                        FL
Country                     USA
Half            0 days 01:39:28
40K             0 days 03:13:21
Pace                    0:07:48
TotalSeconds            11601.0
HalfSeconds              5968.0
Name: 16795, dtype: object
Cleethorpes
 Age                          52
M/F                           M
City                Cleethorpes
State                       NaN
Country                     GBR
Half            0 days 01:45:27
40K             0 days 03:28:07
Pace                    0:08:22
TotalSeconds            12487.0
HalfSeconds              6327.0
Name: 13916, dtype: object
Clemmons
 Age                          39
M/F                           F
City                   Clemmons
State                        NC
Country                     USA
Half            0 days 01:41:15
40K             0 days 03:16:21
Pace                    0:07:54
TotalSeconds            11781.0
HalfSeconds              6075.0
Name: 18277, dtype: object
Clemson
 Age                          58
M/F                           M
City                    Clemson
State                        SC
Country                     USA
Half            0 days 01:31:36
40K             0 days 02:55:04
Pace                    0:07:03
TotalSeconds            10504.0
HalfSeconds              5496.0
Name: 2155, dtype: object
Clermont
 Age                          46
M/F                           M
City                   Clermont
State                        FL
Country                     USA
Half            0 days 01:28:05
40K             0 days 03:09:15
Pace                    0:07:45
TotalSeconds            11355.0
HalfSeconds              5285.0
Name: 2494, dtype: object
Cleveland
 Age                          25
M/F                           M
City                  Cleveland
State                        TN
Country                     USA
Half            0 days 01:26:01
40K             0 days 02:43:38
Pace                    0:06:35
TotalSeconds             9818.0
HalfSeconds              5161.0
Name: 4275, dtype: object
Cleveland Heights
 Age                            28
M/F                             M
City            Cleveland Heights
State                          OH
Country                       USA
Half              0 days 01:20:57
40K               0 days 02:43:24
Pace                      0:06:36
TotalSeconds               9804.0
HalfSeconds                4857.0
Name: 1154, dtype: object
Cleves
 Age                          26
M/F                           M
City                     Cleves
State                        OH
Country                     USA
Half            0 days 01:32:01
40K             0 days 03:15:15
Pace                    0:07:59
TotalSeconds            11715.0
HalfSeconds              5521.0
Name: 4101, dtype: object
Cliffside Park
 Age                          20
M/F                           M
City             Cliffside Park
State                        NJ
Country                     USA
Half            0 days 01:34:58
40K             0 days 04:02:57
Pace                    0:09:40
TotalSeconds            14577.0
HalfSeconds              5698.0
Name: 4859, dtype: object
Clifton
 Age                          52
M/F                           M
City                    Clifton
State                        VA
Country                     USA
Half            0 days 01:38:52
40K             0 days 03:11:16
Pace                    0:07:43
TotalSeconds            11476.0
HalfSeconds              5932.0
Name: 10685, dtype: object
Clifton Park
 Age                          33
M/F                           M
City               Clifton Park
State                        NY
Country                     USA
Half            0 days 01:29:19
40K             0 days 03:02:51
Pace                    0:07:22
TotalSeconds            10971.0
HalfSeconds              5359.0
Name: 2783, dtype: object
Clinton
 Age                          26
M/F                           M
City                    Clinton
State                        MA
Country                     USA
Half            0 days 01:31:44
40K             0 days 03:15:35
Pace                    0:08:02
TotalSeconds            11735.0
HalfSeconds              5504.0
Name: 4540, dtype: object
Clinton Corners
 Age                          53
M/F                           M
City            Clinton Corners
State                        NY
Country                     USA
Half            0 days 01:42:09
40K             0 days 03:28:22
Pace                    0:08:26
TotalSeconds            12502.0
HalfSeconds              6129.0
Name: 8439, dtype: object
Clinton Township
 Age                           39
M/F                            M
City            Clinton Township
State                         MI
Country                      USA
Half             0 days 01:32:58
40K              0 days 03:11:45
Pace                     0:07:45
TotalSeconds             11505.0
HalfSeconds               5578.0
Name: 1254, dtype: object
Clive
 Age                          48
M/F                           M
City                      Clive
State                        IA
Country                     USA
Half            0 days 01:41:34
40K             0 days 03:21:36
Pace                    0:08:10
TotalSeconds            12096.0
HalfSeconds              6094.0
Name: 10567, dtype: object
Clonakilty
 Age                          52
M/F                           M
City                 Clonakilty
State                       NaN
Country                     IRL
Half            0 days 02:08:03
40K             0 days 04:22:11
Pace                    0:10:43
TotalSeconds            15731.0
HalfSeconds              7683.0
Name: 31751, dtype: object
Clondalkin
 Age                          34
M/F                           M
City                 Clondalkin
State                       NaN
Country                     IRL
Half            0 days 01:38:51
40K             0 days 03:30:37
Pace                    0:08:34
TotalSeconds            12637.0
HalfSeconds              5931.0
Name: 3988, dtype: object
Cloquet
 Age                          49
M/F                           M
City                    Cloquet
State                        MN
Country                     USA
Half            0 days 01:27:22
40K             0 days 02:57:37
Pace                    0:07:11
TotalSeconds            10657.0
HalfSeconds              5242.0
Name: 8203, dtype: object
Closter
 Age                          48
M/F                           M
City                    Closter
State                        NJ
Country                     USA
Half            0 days 01:33:01
40K             0 days 03:03:43
Pace                    0:07:26
TotalSeconds            11023.0
HalfSeconds              5581.0
Name: 6556, dtype: object
Cloudcroft
 Age                          43
M/F                           M
City                 Cloudcroft
State                        NM
Country                     USA
Half            0 days 01:22:18
40K             0 days 02:40:43
Pace                    0:06:30
TotalSeconds             9643.0
HalfSeconds              4938.0
Name: 4863, dtype: object
Clover
 Age                          48
M/F                           F
City                     Clover
State                        SC
Country                     USA
Half            0 days 01:54:42
40K             0 days 03:45:23
Pace                    0:09:05
TotalSeconds            13523.0
HalfSeconds              6882.0
Name: 22221, dtype: object
Clovis
 Age                          33
M/F                           F
City                     Clovis
State                        CA
Country                     USA
Half            0 days 01:42:25
40K             0 days 03:18:50
Pace                    0:08:00
TotalSeconds            11930.0
HalfSeconds              6145.0
Name: 16787, dtype: object
Clute
 Age                          45
M/F                           F
City                      Clute
State                        TX
Country                     USA
Half            0 days 02:09:54
40K             0 days 04:08:03
Pace                    0:09:58
TotalSeconds            14883.0
HalfSeconds              7794.0
Name: 22205, dtype: object
Clyde Hill
 Age                          42
M/F                           M
City                 Clyde Hill
State                        WA
Country                     USA
Half            0 days 01:37:29
40K             0 days 03:16:39
Pace                    0:07:56
TotalSeconds            11799.0
HalfSeconds              5849.0
Name: 5531, dtype: object
Clymer
 Age                          47
M/F                           M
City                     Clymer
State                        NY
Country                     USA
Half            0 days 01:40:17
40K             0 days 03:14:42
Pace                    0:07:53
TotalSeconds            11682.0
HalfSeconds              6017.0
Name: 12477, dtype: object
Co Cork
 Age                          35
M/F                           F
City                    Co Cork
State                       NaN
Country                     IRL
Half            0 days 01:59:24
40K             0 days 03:56:35
Pace                    0:09:33
TotalSeconds            14195.0
HalfSeconds              7164.0
Name: 19748, dtype: object
Co Down, N Ireland
 Age                             36
M/F                              M
City            Co Down, N Ireland
State                          NaN
Country                        GBR
Half               0 days 01:49:06
40K                0 days 03:43:32
Pace                       0:09:06
TotalSeconds               13412.0
HalfSeconds                 6546.0
Name: 31748, dtype: object
Co Dublin
 Age                          21
M/F                           M
City                  Co Dublin
State                       NaN
Country                     IRL
Half            0 days 01:28:34
40K             0 days 02:57:00
Pace                    0:07:10
TotalSeconds            10620.0
HalfSeconds              5314.0
Name: 5488, dtype: object
Co Galway
 Age                          46
M/F                           M
City                  Co Galway
State                       NaN
Country                     IRL
Half            0 days 01:38:01
40K             0 days 03:16:01
Pace                    0:07:55
TotalSeconds            11761.0
HalfSeconds              5881.0
Name: 10201, dtype: object
Co Kildare
 Age                          50
M/F                           M
City                 Co Kildare
State                       NaN
Country                     IRL
Half            0 days 01:58:18
40K             0 days 03:48:20
Pace                    0:09:14
TotalSeconds            13700.0
HalfSeconds              7098.0
Name: 31795, dtype: object
Co Limerick
 Age                          26
M/F                           F
City                Co Limerick
State                       NaN
Country                     IRL
Half            0 days 02:15:27
40K             0 days 04:34:35
Pace                    0:11:05
TotalSeconds            16475.0
HalfSeconds              8127.0
Name: 31726, dtype: object
Co Tyrone, N Ireland
 Age                               38
M/F                                F
City            Co Tyrone, N Ireland
State                            NaN
Country                          GBR
Half                 0 days 02:09:29
40K                  0 days 04:10:44
Pace                         0:10:05
TotalSeconds                 15044.0
HalfSeconds                   7769.0
Name: 31789, dtype: object
Co Wexford
 Age                          50
M/F                           M
City                 Co Wexford
State                       NaN
Country                     IRL
Half            0 days 02:04:13
40K             0 days 04:11:06
Pace                    0:10:08
TotalSeconds            15066.0
HalfSeconds              7453.0
Name: 29417, dtype: object
Co Wicklow
 Age                          26
M/F                           F
City                 Co Wicklow
State                       NaN
Country                     IRL
Half            0 days 02:07:43
40K             0 days 04:10:57
Pace                    0:10:08
TotalSeconds            15057.0
HalfSeconds              7663.0
Name: 27999, dtype: object
Coatesville
 Age                          37
M/F                           F
City                Coatesville
State                        PA
Country                     USA
Half            0 days 01:46:36
40K             0 days 03:26:59
Pace                    0:08:21
TotalSeconds            12419.0
HalfSeconds              6396.0
Name: 19657, dtype: object
Cobourg
 Age                          40
M/F                           M
City                    Cobourg
State                        ON
Country                     CAN
Half            0 days 01:31:40
40K             0 days 03:16:16
Pace                    0:08:01
TotalSeconds            11776.0
HalfSeconds              5500.0
Name: 7501, dtype: object
Cochrane
 Age                          46
M/F                           M
City                   Cochrane
State                        AB
Country                     CAN
Half            0 days 01:32:06
40K             0 days 03:07:20
Pace                    0:07:34
TotalSeconds            11240.0
HalfSeconds              5526.0
Name: 3058, dtype: object
Cockeysville
 Age                          37
M/F                           M
City               Cockeysville
State                        MD
Country                     USA
Half            0 days 01:36:05
40K             0 days 03:41:57
Pace                    0:09:26
TotalSeconds            13317.0
HalfSeconds              5765.0
Name: 6469, dtype: object
Cocoa
 Age                          51
M/F                           M
City                      Cocoa
State                        FL
Country                     USA
Half            0 days 01:41:39
40K             0 days 03:35:02
Pace                    0:08:45
TotalSeconds            12902.0
HalfSeconds              6099.0
Name: 12101, dtype: object
Coconut Creek
 Age                          38
M/F                           M
City              Coconut Creek
State                        FL
Country                     USA
Half            0 days 01:27:03
40K             0 days 02:59:08
Pace                    0:07:17
TotalSeconds            10748.0
HalfSeconds              5223.0
Name: 5662, dtype: object
Cody
 Age                          40
M/F                           M
City                       Cody
State                        WY
Country                     USA
Half            0 days 01:37:18
40K             0 days 03:34:45
Pace                    0:08:52
TotalSeconds            12885.0
HalfSeconds              5838.0
Name: 8717, dtype: object
Coeur D Alene
 Age                          40
M/F                           M
City              Coeur D Alene
State                        ID
Country                     USA
Half            0 days 01:31:46
40K             0 days 03:08:17
Pace                    0:07:42
TotalSeconds            11297.0
HalfSeconds              5506.0
Name: 8145, dtype: object
Coeur D'Alene
 Age                          24
M/F                           M
City              Coeur D'Alene

 Age                          42
M/F                           M
City                  Columbia,
State                        SC
Country                     USA
Half            0 days 01:35:07
40K             0 days 03:01:36
Pace                    0:07:18
TotalSeconds            10896.0
HalfSeconds              5707.0
Name: 7616, dtype: object
Columbus
 Age                          31
M/F                           M
City                   Columbus
State                        OH
Country                     USA
Half            0 days 01:23:51
40K             0 days 02:41:07
Pace                    0:06:29
TotalSeconds             9667.0
HalfSeconds              5031.0
Name: 2984, dtype: object
Comanche
 Age                          60
M/F                           F
City                   Comanche
State                        TX
Country                     USA
Half            0 days 02:15:52
40K             0 days 04:22:14
Pace                    0:10:33
TotalSeconds            15734.0
HalfSeconds              8152.0
Name: 25934, dtype: object
Combined Locks
 Age                          35
M/F                           F
City             Combined Locks
State                        WI
Country                     USA
Half            0 days 01:42:32
40K             0 days 03:25:05
Pace                    0:08:14
TotalSeconds            12305.0
HalfSeconds              6152.0
Name: 11674, dtype: object
Commack
 Age                          23
M/F                           M
City                    Commack
State                        NY
Country                     USA
Half            0 days 02:11:37
40K             0 days 04:17:24
Pace                    0:10:23
TotalSeconds            15444.0
HalfSeconds              7897.0
Name: 30034, dtype: object
Commerce
 Age                          53
M/F                           M
City                   Commerce
State                        MI
Country                     USA
Half            0 days 01:42:30
40K             0 days 04:03:58
Pace                    0:09:52
TotalSeconds            14638.0
HalfSeconds              6150.0
Name: 12808, dtype: object
Commerce City
 Age                          43
M/F                           F
City              Commerce City
State                        CO
Country                     USA
Half            0 days 01:54:10
40K             0 days 03:37:28
Pace                    0:08:45
TotalSeconds            13048.0
HalfSeconds              6850.0
Name: 20560, dtype: object
Commerce Township
 Age                            52
M/F                             F
City            Commerce Township
State                          MI
Country                       USA
Half              0 days 02:05:19
40K               0 days 04:10:19
Pace                      0:10:05
TotalSeconds              15019.0
HalfSeconds                7519.0
Name: 23465, dtype: object
Commerce Twp
 Age                          55
M/F                           M
City               Commerce Twp
State                        MI
Country                     USA
Half            0 days 01:49:48
40K             0 days 03:55:59
Pace                    0:09:35
TotalSeconds            14159.0
HalfSeconds              6588.0
Name: 17398, dtype: object
Commercial Point
 Age                           37
M/F                            F
City            Commercial Point
State                         OH
Country                      USA
Half             0 days 01:44:45
40K              0 days 03:16:19
Pace                     0:07:53
TotalSeconds             11779.0
HalfSeconds               6285.0
Name: 13342, dtype: object
Comstock Park
 Age                          52
M/F                           M
City              Comstock Park
State                        MI
Country                     USA
Half            0 days 01:31:45
40K             0 days 03:07:00
Pace                    0:07:36
TotalSeconds            11220.0
HalfSeconds              5505.0
Name: 6257, dtype: object
Conception Bay South
 Age                               35
M/F                                M
City            Conception Bay South
State                             NL
Country                          CAN
Half                 0 days 01:29:06
40K                  0 days 02:51:25
Pace                         0:06:55
TotalSeconds                 10285.0
HalfSeconds                   5346.0
Name: 5496, dtype: object
Concon
 Age                          37
M/F                           F
City                     Concon
State                       NaN
Country                     CHI
Half            0 days 01:47:10
40K             0 days 03:30:49
Pace                    0:08:31
TotalSeconds            12649.0
HalfSeconds              6430.0
Name: 18707, dtype: object
Concord
 Age                          44
M/F                           M
City                    Concord
State                        MA
Country                     USA
Half            0 days 01:15:33
40K             0 days 02:28:54
Pace                    0:06:02
TotalSeconds             8934.0
HalfSeconds              4533.0
Name: 468, dtype: object
Concord Township
 Age                           48
M/F                            M
City            Concord Township
State                         OH
Country                      USA
Half             0 days 01:38:02
40K              0 days 03:18:05
Pace                     0:08:00
TotalSeconds             11885.0
HalfSeconds               5882.0
Name: 6981, dtype: object
Concord Twp
 Age                          45
M/F                           F
City                Concord Twp
State                        OH
Country                     USA
Half            0 days 01:38:52
40K             0 days 03:17:08
Pace                    0:07:57
TotalSeconds            11828.0
HalfSeconds              5932.0
Name: 16183, dtype: object
Concorezzo
 Age                          40
M/F                           F
City                 Concorezzo
State                       NaN
Country                     ITA
Half            0 days 02:35:08
40K             0 days 05:45:24
Pace                    0:14:00
TotalSeconds            20724.0
HalfSeconds              9308.0
Name: 21161, dtype: object
Condon
 Age                          52
M/F                           F
City                     Condon
State                        OR
Country                     USA
Half            0 days 01:49:11
40K             0 days 03:36:43
Pace                    0:08:47
TotalSeconds            13003.0
HalfSeconds              6551.0
Name: 22242, dtype: object
Conegliano
 Age                          56
M/F                           M
City                 Conegliano
State                       NaN
Country                     ITA
Half            0 days 01:57:44
40K             0 days 03:46:43
Pace                    0:09:08
TotalSeconds            13603.0
HalfSeconds              7064.0
Name: 31813, dtype: object
Conestogo
 Age                          37
M/F                           M
City                  Conestogo
State                        ON
Country                     CAN
Half            0 days 01:47:23
40K             0 days 03:36:45
Pace                    0:08:46
TotalSeconds            13005.0
HalfSeconds              6443.0
Name: 29985, dtype: object
Congers
 Age                          42
M/F                           F
City                    Congers
State                        NY
Country                     USA
Half            0 days 02:03:17
40K             0 days 04:21:50
Pace                    0:10:37
TotalSeconds            15710.0
HalfSeconds              7397.0
Name: 29945, dtype: object
Congerville
 Age                          39
M/F                           F
City                Congerville
State                        IL
Country                     USA
Half            0 days 02:34:39
40K             0 days 05:18:07
Pace                    0:12:45
TotalSeconds            19087.0
HalfSeconds              9279.0
Name: 27391, dtype: object
Conneaut
 Age                          50
M/F                           F
City                   Conneaut
State                        OH
Country                     USA
Half            0 days 01:51:03
40K             0 days 03:41:07
Pace                    0:08:56
TotalSeconds            13267.0
HalfSeconds              6663.0
Name: 22937, dtype: object
Conquerall Bank
 Age                          54
M/F                           M
City            Conquerall Bank
State                        NS
Country                     CAN
Half            0 days 01:46:11
40K             0 days 03:25:08
Pace                    0:08:17
TotalSeconds            12308.0
HalfSeconds              6371.0
Name: 13641, dtype: object

Conroe
 Age                          42
M/F                           F
City                     Conroe
State                        TX
Country                     USA
Half            0 days 01:51:34
40K             0 days 03:47:31
Pace                    0:09:16
TotalSeconds            13651.0
HalfSeconds              6694.0
Name: 21189, dtype: object
Consecon
 Age                          38
M/F                           F
City                   Consecon
State                        ON
Country                     CAN
Half            0 days 01:50:49
40K             0 days 03:32:22
Pace                    0:08:32
TotalSeconds            12742.0
HalfSeconds              6649.0
Name: 18454, dtype: object
Conshohocken
 Age                          25
M/F                           M
City               Conshohocken
State                        PA
Country                     USA
Half            0 days 01:17:01
40K             0 days 02:40:18
Pace                    0:06:30
TotalSeconds             9618.0
HalfSeconds              4621.0
Name: 1441, dtype: object
Constantia
 Age                          60
M/F                           M
City                 Constantia
State                        NY
Country                     USA
Half            0 days 01:57:54
40K             0 days 03:55:22
Pace                    0:09:31
TotalSeconds            14122.0
HalfSeconds              7074.0
Name: 21781, dtype: object
Constantine
 Age                          55
M/F                           F
City                Constantine
State                        MI
Country                     USA
Half            0 days 01:53:48
40K             0 days 03:40:42
Pace                    0:08:54
TotalSeconds            13242.0
HalfSeconds              6828.0
Name: 20473, dtype: object
Contrecoeur
 Age                          47
M/F                           M
City                Contrecoeur
State                        QC
Country                     CAN
Half            0 days 01:36:18
40K             0 days 03:10:29
Pace                    0:07:41
TotalSeconds            11429.0
HalfSeconds              5778.0
Name: 10960, dtype: object
Conway
 Age                          41
M/F                           F
City                     Conway
State                        AR
Country                     USA
Half            0 days 01:46:21
40K             0 days 03:26:47
Pace                    0:08:23
TotalSeconds            12407.0
HalfSeconds              6381.0
Name: 20677, dtype: object
Cookeville
 Age                          42
M/F                           M
City                 Cookeville
State                        TN
Country                     USA
Half            0 days 01:28:36
40K             0 days 02:50:55
Pace                    0:06:55
TotalSeconds            10255.0
HalfSeconds              5316.0
Name: 2854, dtype: object
Cookshire-Eaton
 Age                          46
M/F                           M
City            Cookshire-Eaton
State                        QC
Country                     CAN
Half            0 days 01:25:40
40K             0 days 02:49:14
Pace                    0:06:49
TotalSeconds            10154.0
HalfSeconds              5140.0
Name: 1071, dtype: object
Coon Rapids
 Age                          42
M/F                           F
City                Coon Rapids
State                        MN
Country                     USA
Half            0 days 01:51:53
40K             0 days 03:44:44
Pace                    0:09:05
TotalSeconds            13484.0
HalfSeconds              6713.0
Name: 21253, dtype: object
Cooper City
 Age                          50
M/F                           M
City                Cooper City
State                        FL
Country                     USA
Half            0 days 01:47:41
40K             0 days 03:40:42
Pace                    0:09:02
TotalSeconds            13242.0
HalfSeconds              6461.0
Name: 15053, dtype: object
Coopersburg
 Age                          30
M/F                           F
City                Coopersburg
State                        PA
Country                     USA
Half            0 days 01:44:49
40K             0 days 03:30:22
Pace                    0:08:30
TotalSeconds            12622.0
HalfSeconds              6289.0
Name: 15099, dtype: object
Coopersville
 Age                          40
M/F                           M
City               Coopersville
State                        MI
Country                     USA
Half            0 days 01:32:47
40K             0 days 03:10:27
Pace                    0:07:43
TotalSeconds            11427.0
HalfSeconds              5567.0
Name: 5025, dtype: object
Coos Bay
 Age                          50
M/F                           F
City                   Coos Bay
State                        OR
Country                     USA
Half            0 days 01:54:16
40K             0 days 03:42:56
Pace                    0:08:59
TotalSeconds            13376.0
HalfSeconds              6856.0
Name: 21136, dtype: object
Copenhagen
 Age                          41
M/F                           M
City                 Copenhagen
State                       NaN
Country                     DEN
Half            0 days 01:32:07
40K             0 days 02:59:06
Pace                    0:07:12
TotalSeconds            10746.0
HalfSeconds              5527.0
Name: 4398, dtype: object
Copenhagen N
 Age                          34
M/F                           M
City               Copenhagen N
State                       NaN
Country                     DEN
Half            0 days 01:52:17
40K             0 days 03:50:07
Pace                    0:09:19
TotalSeconds            13807.0
HalfSeconds              6737.0
Name: 4610, dtype: object
Copenhagen S
 Age                          30
M/F                           M
City               Copenhagen S
State                       NaN
Country                     DEN
Half            0 days 01:29:00
40K             0 days 02:51:38
Pace                    0:06:55
TotalSeconds            10298.0
HalfSeconds              5340.0
Name: 497, dtype: object
Copenhagen Sv
 Age                          37
M/F                           M
City              Copenhagen Sv
State                       NaN
Country                     DEN
Half            0 days 01:27:39
40K             0 days 03:13:06
Pace                    0:07:51
TotalSeconds            11586.0
HalfSeconds              5259.0
Name: 4187, dtype: object
Copenhagen V.
 Age                          59
M/F                           F
City              Copenhagen V.
State                       NaN
Country                     DEN
Half            0 days 02:17:59
40K             0 days 04:28:19
Pace                    0:10:52
TotalSeconds            16099.0
HalfSeconds              8279.0
Name: 30302, dtype: object
Coppell
 Age                          25
M/F                           M
City                    Coppell
State                        TX
Country                     USA
Half            0 days 01:29:01
40K             0 days 02:48:06
Pace                    0:06:45
TotalSeconds            10086.0
HalfSeconds              5341.0
Name: 3429, dtype: object
Coquitlam
 Age                          48
M/F                           M
City                  Coquitlam
State                        BC
Country                     CAN
Half            0 days 01:40:01
40K             0 days 03:18:21
Pace                    0:08:00
TotalSeconds            11901.0
HalfSeconds              6001.0
Name: 8024, dtype: object
Coral Gables
 Age                          40
M/F                           M
City               Coral Gables
State                        FL
Country                     USA
Half            0 days 01:26:28
40K             0 days 02:51:12
Pace                    0:06:58
TotalSeconds            10272.0
HalfSeconds              5188.0
Name: 4104, dtype: object
Coralville
 Age                          42
M/F                           M
City                 Coralville
State                        IA
Country                     USA
Half            0 days 01:37:37
40K             0 days 03:11:36
Pace                    0:07:44
TotalSeconds            11496.0
HalfSeconds              5857.0
Name: 8093, dtype: object
Coram
 Age                          48
M/F                           F
City                      Coram
State                        NY
Country                     USA
Half            0 days 01:46:02
40K             0 days 03:26:37
Pace                    0:08:19
TotalSeconds            12397.0
HalfSeconds              6362.0
Name: 19751, dtype: object
Coraopolis
 Age                          37
M/F                           M
City                 Coraopolis
State                        PA
Country                     USA
Half            0 days 01:21:15
40K             0 days 02:39:13
Pace                    0:06:27
TotalSeconds             9553.0
HalfSeconds              4875.0
Name: 2176, dtype: object
Corbeil
 Age                          44
M/F                           F
City                    Corbeil
State                        ON
Country                     CAN
Half            0 days 01:46:21
40K             0 days 03:37:47
Pace                    0:08:49
TotalSeconds            13067.0
HalfSeconds              6381.0
Name: 19488, dtype: object
Cordoba
 Age                          20
M/F                           F
City                    Cordoba
State                       NaN
Country                     ARG
Half            0 days 01:37:49
40K             0 days 03:16:53
Pace                    0:08:00
TotalSeconds            11813.0
HalfSeconds              5869.0
Name: 10315, dtype: object
Corinth
 Age                          74
M/F                           M
City                    Corinth
State                        MS
Country                     USA
Half            0 days 02:24:06
40K             0 days 04:42:32
Pace                    0:11:22
TotalSeconds            16952.0
HalfSeconds              8646.0
Name: 25915, dtype: object
Cork
 Age                          48
M/F                           F
City                       Cork
State                       NaN
Country                     IRL
Half            0 days 01:36:12
40K             0 days 03:07:57
Pace                    0:07:35
TotalSeconds            11277.0
HalfSeconds              5772.0
Name: 7245, dtype: object
Corlett Gardens
 Age                          42
M/F                           F
City            Corlett Gardens
State                       NaN
Country                     RSA
Half            0 days 02:17:13
40K             0 days 04:25:55
Pace                    0:10:42
TotalSeconds            15955.0
HalfSeconds              8233.0

Name: 31622, dtype: object
Corminboeuf
 Age                          64
M/F                           M
City                Corminboeuf
State                       NaN
Country                     SUI
Half            0 days 02:10:21
40K             0 days 04:22:38
Pace                    0:10:37
TotalSeconds            15758.0
HalfSeconds              7821.0
Name: 21929, dtype: object
Cornelius
 Age                          35
M/F                           M
City                  Cornelius
State                        NC
Country                     USA
Half            0 days 01:30:55
40K             0 days 03:03:56
Pace                    0:07:29
TotalSeconds            11036.0
HalfSeconds              5455.0
Name: 3841, dtype: object
Corner Brook
 Age                          45
M/F                           M
City               Corner Brook
State                        NL
Country                     CAN
Half            0 days 01:34:03
40K             0 days 03:05:51
Pace                    0:07:29
TotalSeconds            11151.0
HalfSeconds              5643.0
Name: 9033, dtype: object
Corning
 Age                          63
M/F                           M
City                    Corning
State                        NY
Country                     USA
Half            0 days 01:59:19
40K             0 days 04:00:52
Pace                    0:09:46
TotalSeconds            14452.0
HalfSeconds              7159.0
Name: 21842, dtype: object
Cornwall
 Age                          47
M/F                           F
City                   Cornwall
State                        ON
Country                     CAN
Half            0 days 01:41:22
40K             0 days 03:22:10
Pace                    0:08:12
TotalSeconds            12130.0
HalfSeconds              6082.0
Name: 19840, dtype: object
Corona
 Age                          44
M/F                           M
City                     Corona
State                        CA
Country                     USA
Half            0 days 01:32:57
40K             0 days 03:11:53
Pace                    0:07:44
TotalSeconds            11513.0
HalfSeconds              5577.0
Name: 4143, dtype: object
Coronado
 Age                          41
M/F                           M
City                   Coronado
State                        CA
Country                     USA
Half            0 days 01:22:13
40K             0 days 02:37:45
Pace                    0:06:22
TotalSeconds             9465.0
HalfSeconds              4933.0
Name: 1644, dtype: object
Corpus Christi
 Age                          40
M/F                           M
City             Corpus Christi
State                        TX
Country                     USA
Half            0 days 01:29:46
40K             0 days 03:03:28
Pace                    0:07:28
TotalSeconds            11008.0
HalfSeconds              5386.0
Name: 3747, dtype: object
Corry
 Age                          67
M/F                           M
City                      Corry
State                        PA
Country                     USA
Half            0 days 02:06:34
40K             0 days 04:18:05
Pace                    0:10:22
TotalSeconds            15485.0
HalfSeconds              7594.0
Name: 25463, dtype: object
Corsico
 Age                          48
M/F                           M
City                    Corsico
State                       NaN
Country                     ITA
Half            0 days 01:52:37
40K             0 days 03:39:17
Pace                    0:08:53
TotalSeconds            13157.0
HalfSeconds              6757.0
Name: 31450, dtype: object
Corte Madera
 Age                          46
M/F                           M
City               Corte Madera
State                        CA
Country                     USA
Half            0 days 01:23:28
40K             0 days 02:45:01
Pace                    0:06:41
TotalSeconds             9901.0
HalfSeconds              5008.0
Name: 975, dtype: object
Cortland
 Age                          31
M/F                           F
City                   Cortland
State                        NY
Country                     USA
Half            0 days 01:27:20
40K             0 days 02:49:20
Pace                    0:06:51
TotalSeconds            10160.0
HalfSeconds              5240.0
Name: 2408, dtype: object
Cortlandt Manor
 Age                          59
M/F                           M
City            Cortlandt Manor
State                        NY
Country                     USA
Half            0 days 01:45:40
40K             0 days 03:29:41
Pace                    0:08:33
TotalSeconds            12581.0
HalfSeconds              6340.0
Name: 17899, dtype: object
Corvallis
 Age                          27
M/F                           M
City                  Corvallis
State                        OR
Country                     USA
Half            0 days 01:26:53
40K             0 days 02:50:11
Pace                    0:06:52
TotalSeconds            10211.0
HalfSeconds              5213.0
Name: 4291, dtype: object
Cos Cob
 Age                          42
M/F                           M
City                    Cos Cob
State                        CT
Country                     USA
Half            0 days 01:31:01
40K             0 days 02:59:14
Pace                    0:07:15
TotalSeconds            10754.0
HalfSeconds              5461.0
Name: 6800, dtype: object
Coshocton
 Age                          49
M/F                           M
City                  Coshocton
State                        OH
Country                     USA
Half            0 days 01:50:28
40K             0 days 03:51:36
Pace                    0:09:19
TotalSeconds            13896.0
HalfSeconds              6628.0
Name: 11089, dtype: object
Costa Mesa
 Age                          26
M/F                           F
City                 Costa Mesa
State                        CA
Country                     USA
Half            0 days 01:29:55
40K             0 days 02:56:31
Pace                    0:07:08
TotalSeconds            10591.0
HalfSeconds              5395.0
Name: 5635, dtype: object
Costa Rica
 Age                          35
M/F                           F
City                 Costa Rica
State                       NaN
Country                     CRC
Half            0 days 01:51:25
40K             0 days 03:37:37
Pace                    0:08:46
TotalSeconds            13057.0
HalfSeconds              6685.0
Name: 19555, dtype: object
Cotati
 Age                          46
M/F                           M
City                     Cotati
State                        CA
Country                     USA
Half            0 days 01:34:14
40K             0 days 03:05:53
Pace                    0:07:29
TotalSeconds            11153.0
HalfSeconds              5654.0
Name: 8399, dtype: object
Coteau-Du-Lac
 Age                          51
M/F                           M
City              Coteau-Du-Lac
State                        QC
Country                     CAN
Half            0 days 01:36:32
40K             0 days 03:05:39
Pace                    0:07:30
TotalSeconds            11139.0
HalfSeconds              5792.0
Name: 13861, dtype: object
Coto De Caza
 Age                          52
M/F                           F
City               Coto De Caza
State                        CA
Country                     USA
Half            0 days 01:56:32
40K             0 days 04:02:01
Pace                    0:09:49
TotalSeconds            14521.0
HalfSeconds              6992.0
Name: 23451, dtype: object
Cottage Grove
 Age                          37
M/F                           M
City              Cottage Grove
State                        WI
Country                     USA
Half            0 days 01:37:25
40K             0 days 03:13:04
Pace                    0:07:50
TotalSeconds            11584.0
HalfSeconds              5845.0
Name: 6461, dtype: object
Cottbus
 Age                          54
M/F                           F
City                    Cottbus
State                       NaN
Country                     GER
Half            0 days 02:06:58
40K             0 days 04:11:20
Pace                    0:10:07
TotalSeconds            15080.0
HalfSeconds              7618.0
Name: 30836, dtype: object
Cottonwood Heights
 Age                             22
M/F                              F
City            Cottonwood Heights
State                           UT
Country                        USA
Half               0 days 01:40:48
40K                0 days 03:18:33
Pace                       0:08:02
TotalSeconds               11913.0
HalfSeconds                 6048.0
Name: 17182, dtype: object
Coudersport
 Age                          45
M/F                           M
City                Coudersport
State                        PA
Country                     USA
Half            0 days 01:49:30
40K             0 days 03:51:09
Pace                    0:09:23
TotalSeconds            13869.0
HalfSeconds              6570.0
Name: 10697, dtype: object
Council Bluffs
 Age                          55
M/F                           M
City             Council Bluffs
State                        IA
Country                     USA
Half            0 days 02:32:15
40K             0 days 04:45:13
Pace                    0:11:26
TotalSeconds            17113.0
HalfSeconds              9135.0
Name: 26754, dtype: object
County Galway
 Age                          54
M/F                           M
City              County Galway
State                       NaN
Country                     IRL
Half            0 days 02:01:53
40K             0 days 04:30:39
Pace                    0:11:00
TotalSeconds            16239.0
HalfSeconds              7313.0
Name: 12727, dtype: object
County Meath
 Age                          36
M/F                           F
City               County Meath
State                       NaN
Country                     IRL
Half            0 days 01:45:41
40K             0 days 03:28:14
Pace                    0:08:24
TotalSeconds            12494.0
HalfSeconds              6341.0
Name: 16309, dtype: object
Courtenay
 Age                          62
M/F                           F
City                  Courtenay
State                        BC
Country                     CAN
Half            0 days 02:09:43
40K             0 days 04:22:15
Pace                    0:10:36
TotalSeconds            15735.0
HalfSeconds              7783.0
Name: 24562, dtype: object
Coventry
 Age                          23
M/F                           M
City                   Coventry
State                        RI
Country                     USA
Half            0 days 01:21:53
40K             0 days 02:46:03
Pace                    0:06:45
TotalSeconds             9963.0
HalfSeconds              4913.0
Name: 1863, dtype: object

Covina
 Age                          48
M/F                           M
City                     Covina
State                        CA
Country                     USA
Half            0 days 01:32:52
40K             0 days 03:09:21
Pace                    0:07:38
TotalSeconds            11361.0
HalfSeconds              5572.0
Name: 8042, dtype: object
Covington
 Age                          34
M/F                           M
City                  Covington
State                        WA
Country                     USA
Half            0 days 01:20:24
40K             0 days 02:37:35
Pace                    0:06:22
TotalSeconds             9455.0
HalfSeconds              4824.0
Name: 446, dtype: object
Cow Bay
 Age                          49
M/F                           M
City                    Cow Bay
State                        NS
Country                     CAN
Half            0 days 01:39:36
40K             0 days 03:27:56
Pace                    0:08:24
TotalSeconds            12476.0
HalfSeconds              5976.0
Name: 9695, dtype: object
Coyoacán, Df
 Age                          28
M/F                           M
City               Coyoacán, Df
State                       NaN
Country                     MEX
Half            0 days 01:27:07
40K             0 days 03:01:44
Pace                    0:07:17
TotalSeconds            10904.0
HalfSeconds              5227.0
Name: 2351, dtype: object
Craig
 Age                          60
M/F                           M
City                      Craig
State                        CO
Country                     USA
Half            0 days 01:52:54
40K             0 days 03:57:29
Pace                    0:09:39
TotalSeconds            14249.0
HalfSeconds              6774.0
Name: 13068, dtype: object
Cranberry Isles
 Age                          58
M/F                           M
City            Cranberry Isles
State                        ME
Country                     USA
Half            0 days 01:43:20
40K             0 days 03:24:48
Pace                    0:08:22
TotalSeconds            12288.0
HalfSeconds              6200.0
Name: 11539, dtype: object
Cranberry Township
 Age                             40
M/F                              M
City            Cranberry Township
State                           PA
Country                        USA
Half               0 days 01:26:30
40K                0 days 02:49:02
Pace                       0:06:51
TotalSeconds               10142.0
HalfSeconds                 5190.0
Name: 4359, dtype: object
Cranberry Twp
 Age                          43
M/F                           F
City              Cranberry Twp
State                        PA
Country                     USA
Half            0 days 01:53:03
40K             0 days 03:54:23
Pace                    0:09:28
TotalSeconds            14063.0
HalfSeconds              6783.0
Name: 19736, dtype: object
Cranford
 Age                          54
M/F                           M
City                   Cranford
State                        NJ
Country                     USA
Half            0 days 01:33:44
40K             0 days 03:03:45
Pace                    0:07:26
TotalSeconds            11025.0
HalfSeconds              5624.0
Name: 7429, dtype: object
Cranston
 Age                          44
M/F                           M
City                   Cranston
State                        RI
Country                     USA
Half            0 days 01:32:11
40K             0 days 03:01:39
Pace                    0:07:20
TotalSeconds            10899.0
HalfSeconds              5531.0
Name: 8516, dtype: object
Craughwell
 Age                          48
M/F                           F
City                 Craughwell
State                       NaN
Country                     IRL
Half            0 days 02:08:03
40K             0 days 04:22:11
Pace                    0:10:43
TotalSeconds            15731.0
HalfSeconds              7683.0
Name: 31742, dtype: object
Crawford
 Age                          39
M/F                           F
City                   Crawford
State                        TX
Country                     USA
Half            0 days 01:40:06
40K             0 days 03:29:25
Pace                    0:08:28
TotalSeconds            12565.0
HalfSeconds              6006.0
Name: 13635, dtype: object
Crawfordsville
 Age                          41
M/F                           M
City             Crawfordsville
State                        IN
Country                     USA
Half            0 days 01:32:45
40K             0 days 03:02:57
Pace                    0:07:24
TotalSeconds            10977.0
HalfSeconds              5565.0
Name: 8739, dtype: object
Crawley
 Age                          37
M/F                           M
City                    Crawley
State                       NaN
Country                     GBR
Half            0 days 01:37:05
40K             0 days 03:20:22
Pace                    0:08:04
TotalSeconds            12022.0
HalfSeconds              5825.0
Name: 5960, dtype: object
Cream Ridge
 Age                          36
M/F                           F
City                Cream Ridge
State                        NJ
Country                     USA
Half            0 days 01:46:29
40K             0 days 03:28:29
Pace                    0:08:26
TotalSeconds            12509.0
HalfSeconds              6389.0
Name: 18875, dtype: object
Creazzo
 Age                          43
M/F                           M
City                    Creazzo
State                       NaN
Country                     ITA
Half            0 days 01:25:59
40K             0 days 02:45:41
Pace                    0:06:41
TotalSeconds             9941.0
HalfSeconds              5159.0
Name: 2050, dtype: object
Creemore
 Age                          62
M/F                           F
City                   Creemore
State                        ON
Country                     CAN
Half            0 days 02:01:30
40K             0 days 04:04:34
Pace                    0:09:54
TotalSeconds            14674.0
HalfSeconds              7290.0
Name: 25689, dtype: object
Cremona
 Age                          51
M/F                           M
City                    Cremona
State                       NaN
Country                     ITA
Half            0 days 01:41:01
40K             0 days 03:20:09
Pace                    0:08:11
TotalSeconds            12009.0
HalfSeconds              6061.0
Name: 11676, dtype: object
Cremorne Nsw
 Age                          46
M/F                           M
City               Cremorne Nsw
State                       NaN
Country                     AUS
Half            0 days 02:15:04
40K             0 days 04:55:23
Pace                    0:11:57
TotalSeconds            17723.0
HalfSeconds              8104.0
Name: 31546, dtype: object
Crescent
 Age                          43
M/F                           M
City                   Crescent
State                        PA
Country                     USA
Half            0 days 01:34:15
40K             0 days 03:05:32
Pace                    0:07:32
TotalSeconds            11132.0
HalfSeconds              5655.0
Name: 8829, dtype: object
Crest Hill
 Age                          32
M/F                           M
City                 Crest Hill
State                        IL
Country                     USA
Half            0 days 01:32:06
40K             0 days 03:20:10
Pace                    0:08:05
TotalSeconds            12010.0
HalfSeconds              5526.0
Name: 3627, dtype: object
Crestwood
 Age                          38
M/F                           M
City                  Crestwood
State                        IL
Country                     USA
Half            0 days 01:29:10
40K             0 days 02:55:08
Pace                    0:07:06
TotalSeconds            10508.0
HalfSeconds              5350.0
Name: 2561, dtype: object
Crocker
 Age                          45
M/F                           F
City                    Crocker
State                        MO
Country                     USA
Half            0 days 02:28:25
40K             0 days 05:14:45
Pace                    0:12:52
TotalSeconds            18885.0
HalfSeconds              8905.0
Name: 20601, dtype: object
Crofton
 Age                          50
M/F                           M
City                    Crofton
State                        MD
Country                     USA
Half            0 days 01:43:06
40K             0 days 03:14:24
Pace                    0:07:49
TotalSeconds            11664.0
HalfSeconds              6186.0
Name: 14874, dtype: object
Cromwell
 Age                          54
M/F                           M
City                   Cromwell
State                        CT
Country                     USA
Half            0 days 01:43:44
40K             0 days 03:21:06
Pace                    0:08:09
TotalSeconds            12066.0
HalfSeconds              6224.0
Name: 14750, dtype: object
Cronulla
 Age                          51
M/F                           M
City                   Cronulla
State                       NaN
Country                     AUS
Half            0 days 01:45:55
40K             0 days 03:54:47
Pace                    0:09:30
TotalSeconds            14087.0
HalfSeconds              6355.0
Name: 14321, dtype: object
Cross Lanes
 Age                          65
M/F                           M
City                Cross Lanes
State                        WV
Country                     USA
Half            0 days 02:11:51
40K             0 days 04:46:14
Pace                    0:11:39
TotalSeconds            17174.0
HalfSeconds              7911.0
Name: 25429, dtype: object
Cross River
 Age                          57
M/F                           M
City                Cross River
State                        NY
Country                     USA
Half            0 days 01:43:39
40K             0 days 03:22:50
Pace                    0:08:13
TotalSeconds            12170.0
HalfSeconds              6219.0
Name: 14550, dtype: object
Croton On Hudson
 Age                           53
M/F                            M
City            Croton On Hudson
State                         NY
Country                      USA
Half             0 days 01:48:12
40K              0 days 03:36:22
Pace                     0:08:45
TotalSeconds             12982.0
HalfSeconds               6492.0
Name: 14335, dtype: object
Croton-On-Hudson
 Age                           47
M/F                            M
City            Croton-On-Hudson
State                         NY
Country                      USA
Half             0 days 01:40:58
40K              0 days 03:17:44
Pace                     0:08:00
TotalSeconds             11864.0
HalfSeconds               6058.0
Name: 11966, dtype: object
Crown City
 Age                          58
M/F                           M
City                 Crown City
State                        OH
Country                     USA
Half            0 days 01:40:19
40K             0 days 03:16:49
Pace                    0:07:57
TotalSeconds            11809.0
HalfSeconds              6019.0
Name: 10411, dtype: object
Crown Point
 Age                          33
M/F                           M
City                Crown Point
State                        IN
Country                     USA
Half            0 days 01:27:47
40K             0 days 03:12:57
Pace                    0:07:53
TotalSeconds            11577.0
HalfSeconds              5267.0
Name: 2788, dtype: object
Croydon
 Age                          32
M/F                           M
City                    Croydon
State                       NaN
Country                     GBR
Half            0 days 01:22:42
40K             0 days 02:50:03
Pace                    0:06:52
TotalSeconds            10203.0
HalfSeconds              4962.0
Name: 572, dtype: object
Crozet
 Age                          46
M/F                           M
City                     Crozet
State                        VA
Country                     USA
Half            0 days 01:37:50
40K             0 days 03:29:52
Pace                    0:08:32
TotalSeconds            12592.0
HalfSeconds              5870.0
Name: 9539, dtype: object
Crystal
 Age                          28
M/F                           M
City                    Crystal
State                        MN
Country                     USA
Half            0 days 01:29:02
40K             0 days 02:50:51
Pace                    0:06:54
TotalSeconds            10251.0
HalfSeconds              5342.0
Name: 1782, dtype: object
Crystal Beach
 Age                          37
M/F                           M
City              Crystal Beach
State                        FL
Country                     USA
Half            0 days 01:34:59
40K             0 days 03:13:30
Pace                    0:07:50
TotalSeconds            11610.0
HalfSeconds              5699.0
Name: 6398, dtype: object
Crystal Lake
 Age                          47
M/F                           M
City               Crystal Lake
State                        IL
Country                     USA
Half            0 days 01:30:17
40K             0 days 02:52:58
Pace                    0:06:59
TotalSeconds            10378.0
HalfSeconds              5417.0
Name: 6863, dtype: object
Cuautlancingo, Puebla
 Age                                37
M/F                                 M
City            Cuautlancingo, Puebla
State                             NaN
Country                           MEX
Half                  0 days 01:35:30
40K                   0 days 03:30:11
Pace                          0:08:29
TotalSeconds                  12611.0
HalfSeconds                    5730.0
Name: 5247, dtype: object
Cudgen
 Age                          35
M/F                           F
City                     Cudgen
State                       NaN
Country                     AUS
Half            0 days 02:05:49
40K             0 days 04:17:02
Pace                    0:10:29
TotalSeconds            15422.0
HalfSeconds              7549.0
Name: 31799, dtype: object
Cuernavaca Morelos
 Age                             33
M/F                              F
City            Cuernavaca Morelos
State                          NaN
Country                        MEX
Half               0 days 01:37:19
40K                0 days 03:21:12
Pace                       0:08:04
TotalSeconds               12072.0
HalfSeconds                 5839.0
Name: 9921, dtype: object
Culemborg
 Age                          55
M/F                           M
City                  Culemborg
State                       NaN
Country                     NED
Half            0 days 01:46:50
40K             0 days 03:36:45
Pace                    0:08:45
TotalSeconds            13005.0
HalfSeconds              6410.0
Name: 17008, dtype: object
Culiacan
 Age                          48
M/F                           M
City                   Culiacan
State                       NaN
Country                     MEX
Half            0 days 01:33:36
40K             0 days 03:13:21
Pace                    0:07:52
TotalSeconds            11601.0
HalfSeconds              5616.0
Name: 7406, dtype: object
Culiacan De Rosales
 Age                              40
M/F                               M
City            Culiacan De Rosales
State                           NaN
Country                         MEX
Half                0 days 01:31:53
40K                 0 days 02:57:54
Pace                        0:07:12
TotalSeconds                10674.0
HalfSeconds                  5513.0
Name: 7159, dtype: object
Cullman
 Age                          47
M/F                           F
City                    Cullman
State                        AL
Country                     USA
Half            0 days 02:09:09
40K             0 days 04:21:50
Pace                    0:10:36
TotalSeconds            15710.0
HalfSeconds              7749.0
Name: 24161, dtype: object
Culpeper
 Age                          36
M/F                           M
City                   Culpeper
State                        VA
Country                     USA
Half            0 days 01:29:21
40K             0 days 02:59:01
Pace                    0:07:15
TotalSeconds            10741.0
HalfSeconds              5361.0
Name: 2562, dtype: object
Culver City
 Age                          36
M/F                           M
City                Culver City
State                        CA
Country                     USA
Half            0 days 01:28:45
40K             0 days 03:05:50
Pace                    0:07:33
TotalSeconds            11150.0
HalfSeconds              5325.0
Name: 5378, dtype: object
Cumberland
 Age                          40
M/F                           F
City                 Cumberland
State                        ME
Country                     USA
Half            0 days 01:41:05
40K             0 days 03:12:55
Pace                    0:07:47
TotalSeconds            11575.0
HalfSeconds              6065.0
Name: 15124, dtype: object
Cumming
 Age                          40
M/F                           M
City                    Cumming
State                        GA
Country                     USA
Half            0 days 01:30:58
40K             0 days 02:55:33
Pace                    0:07:05
TotalSeconds            10533.0
HalfSeconds              5458.0
Name: 8327, dtype: object
Cummington
 Age                          38
M/F                           F
City                 Cummington
State                        MA
Country                     USA
Half            0 days 02:24:16
40K             0 days 04:45:10
Pace                    0:11:29
TotalSeconds            17110.0
HalfSeconds              8656.0
Name: 26605, dtype: object
Cuneo
 Age                          41
M/F                           M
City                      Cuneo
State                       NaN
Country                     ITA
Half            0 days 01:21:17
40K             0 days 02:44:43
Pace                    0:06:40
TotalSeconds             9883.0
HalfSeconds              4877.0
Name: 843, dtype: object
Cupar
 Age                          42
M/F                           M
City                      Cupar
State                       NaN
Country                     GBR
Half            0 days 01:24:52
40K             0 days 02:47:58
Pace                    0:06:48
TotalSeconds            10078.0
HalfSeconds              5092.0
Name: 1103, dtype: object
Cupertino
 Age                          46
M/F                           M
City                  Cupertino
State                        CA
Country                     USA
Half            0 days 01:24:26
40K             0 days 02:41:34
Pace                    0:06:30
TotalSeconds             9694.0
HalfSeconds              5066.0
Name: 1234, dtype: object
Curitiba
 Age                          38
M/F                           M
City                   Curitiba
State                       NaN
Country                     BRA
Half            0 days 01:28:12
40K             0 days 03:00:06
Pace                    0:07:28
TotalSeconds            10806.0
HalfSeconds              5292.0
Name: 6659, dtype: object
Cushing
 Age                          37
M/F                           F
City                    Cushing
State                        WI
Country                     USA
Half            0 days 01:33:07
40K             0 days 03:10:07
Pace                    0:07:39
TotalSeconds            11407.0
HalfSeconds              5587.0
Name: 2976, dtype: object
Cut Off
 Age                          53
M/F                           M
City                    Cut Off
State                        LA
Country                     USA
Half            0 days 01:44:34
40K             0 days 03:23:11
Pace                    0:08:14
TotalSeconds            12191.0
HalfSeconds              6274.0
Name: 14595, dtype: object
Cutchogue
 Age                          40
M/F                           F
City                  Cutchogue

Cutler Bay
 Age                          52
M/F                           M
City                 Cutler Bay
State                        FL
Country                     USA
Half            0 days 02:16:14
40K             0 days 04:45:43
Pace                    0:11:34
TotalSeconds            17143.0
HalfSeconds              8174.0
Name: 27297, dtype: object
Cuxhaven
 Age                          50
M/F                           M
City                   Cuxhaven
State                       NaN
Country                     GER
Half            0 days 01:41:28
40K             0 days 03:30:56
Pace                    0:08:33
TotalSeconds            12656.0
HalfSeconds              6088.0
Name: 7571, dtype: object
Cuyahoga Falls
 Age                          53
M/F                           M
City             Cuyahoga Falls
State                        OH
Country                     USA
Half            0 days 01:35:57
40K             0 days 03:17:39
Pace                    0:08:07
TotalSeconds            11859.0
HalfSeconds              5757.0
Name: 7346, dtype: object
Cypress
 Age                          48
M/F                           M
City                    Cypress
State                        TX
Country                     USA
Half            0 days 01:29:07
40K             0 days 02:58:27
Pace                    0:07:13
TotalSeconds            10707.0
HalfSeconds              5347.0
Name: 2406, dtype: object
Dacula
 Age                          29
M/F                           F
City                     Dacula
State                        GA
Country                     USA
Half            0 days 01:29:23
40K             0 days 02:53:56
Pace                    0:07:00
TotalSeconds            10436.0
HalfSeconds              5363.0
Name: 8336, dtype: object
Daeniken
 Age                          39
M/F                           M
City                   Daeniken
State                       NaN
Country                     SUI
Half            0 days 01:48:00
40K             0 days 03:41:08
Pace                    0:08:57
TotalSeconds            13268.0
HalfSeconds              6480.0
Name: 31590, dtype: object
Dahlenburg
 Age                          50
M/F                           M
City                 Dahlenburg
State                       NaN
Country                     GER
Half            0 days 02:06:56
40K             0 days 04:06:25
Pace                    0:09:56
TotalSeconds            14785.0
HalfSeconds              7616.0
Name: 31307, dtype: object
Dahlonega
 Age                          39
M/F                           M
City                  Dahlonega
State                        GA
Country                     USA
Half            0 days 01:41:06
40K             0 days 03:28:24
Pace                    0:08:28
TotalSeconds            12504.0
HalfSeconds              6066.0
Name: 14454, dtype: object
Daisy
 Age                          50
M/F                           F
City                      Daisy
State                        OK
Country                     USA
Half            0 days 01:58:14
40K             0 days 03:49:46
Pace                    0:09:16
TotalSeconds            13786.0
HalfSeconds              7094.0
Name: 25036, dtype: object
Dalheim
 Age                          53
M/F                           M
City                    Dalheim
State                       NaN
Country                     LUX
Half            0 days 01:41:45
40K             0 days 03:18:01
Pace                    0:07:59
TotalSeconds            11881.0
HalfSeconds              6105.0
Name: 11741, dtype: object
Dalkeith
 Age                          55
M/F                           M
City                   Dalkeith
State                       NaN
Country                     AUS
Half            0 days 01:45:41
40K             0 days 03:26:27
Pace                    0:08:20
TotalSeconds            12387.0
HalfSeconds              6341.0
Name: 17318, dtype: object
Dallas
 Age                          28
M/F                           M
City                     Dallas
State                        TX
Country                     USA
Half            0 days 01:07:57
40K             0 days 02:12:47
Pace                    0:05:25
TotalSeconds             7967.0
HalfSeconds              4077.0
Name: 43, dtype: object
Dallastown
 Age                          47
M/F                           M
City                 Dallastown
State                        PA
Country                     USA
Half            0 days 01:41:45
40K             0 days 03:28:16
Pace                    0:08:35
TotalSeconds            12496.0
HalfSeconds              6105.0
Name: 12184, dtype: object
Dalton
 Age                          29
M/F                           M
City                     Dalton
State                        PA
Country                     USA
Half            0 days 01:29:04
40K             0 days 02:53:28
Pace                    0:06:59
TotalSeconds            10408.0
HalfSeconds              5344.0
Name: 1647, dtype: object
Daly City
 Age                          28
M/F                           M
City                  Daly City
State                        CA
Country                     USA
Half            0 days 01:19:00
40K             0 days 02:40:39
Pace                    0:06:30
TotalSeconds             9639.0
HalfSeconds              4740.0
Name: 698, dtype: object
Damascus
 Age                          39
M/F                           F
City                   Damascus
State                        MD
Country                     USA
Half            0 days 01:44:23
40K             0 days 03:20:46
Pace                    0:08:05
TotalSeconds            12046.0
HalfSeconds              6263.0
Name: 12977, dtype: object
Damme
 Age                          58
M/F                           M
City                      Damme
State                       NaN
Country                     BEL
Half            0 days 01:55:43
40K             0 days 03:50:29
Pace                    0:09:19
TotalSeconds            13829.0
HalfSeconds              6943.0
Name: 31282, dtype: object
Dana Point
 Age                          45
M/F                           M
City                 Dana Point
State                        CA
Country                     USA
Half            0 days 01:40:36
40K             0 days 03:33:27
Pace                    0:08:39
TotalSeconds            12807.0
HalfSeconds              6036.0
Name: 9423, dtype: object
Danbury
 Age                          41
M/F                           M
City                    Danbury
State                        CT
Country                     USA
Half            0 days 01:29:57
40K             0 days 02:51:56
Pace                    0:06:55
TotalSeconds            10316.0
HalfSeconds              5397.0
Name: 5558, dtype: object
Danielson
 Age                          60
M/F                           M
City                  Danielson
State                        CT
Country                     USA
Half            0 days 01:42:37
40K             0 days 03:17:47
Pace                    0:07:58
TotalSeconds            11867.0
HalfSeconds              6157.0
Name: 13839, dtype: object
Dannemora
 Age                          33
M/F                           M
City                  Dannemora
State                        NY
Country                     USA
Half            0 days 01:30:29
40K             0 days 03:01:16
Pace                    0:07:19
TotalSeconds            10876.0
HalfSeconds              5429.0
Name: 3031, dtype: object
Dansville
 Age                          52
M/F                           F
City                  Dansville
State                        NY
Country                     USA
Half            0 days 01:49:56
40K             0 days 03:32:31
Pace                    0:08:34
TotalSeconds            12751.0
HalfSeconds              6596.0
Name: 21541, dtype: object
Danvers
 Age                          28
M/F                           F
City                    Danvers
State                        MA
Country                     USA
Half            0 days 01:36:56
40K             0 days 03:14:47
Pace                    0:07:53
TotalSeconds            11687.0
HalfSeconds              5816.0
Name: 14890, dtype: object
Danvile
 Age                          55
M/F                           F
City                    Danvile
State                        CA
Country                     USA
Half            0 days 01:58:32
40K             0 days 03:47:03
Pace                    0:09:10
TotalSeconds            13623.0
HalfSeconds              7112.0
Name: 25426, dtype: object
Danville
 Age                          29
M/F                           M
City                   Danville
State                        VA
Country                     USA
Half            0 days 01:12:34
40K             0 days 02:24:15
Pace                    0:05:52
TotalSeconds             8655.0
HalfSeconds              4354.0
Name: 153, dtype: object
Daours
 Age                          49
M/F                           M
City                     Daours
State                       NaN
Country                     FRA
Half            0 days 01:38:37
40K             0 days 03:20:12
Pace                    0:08:06
TotalSeconds            12012.0
HalfSeconds              5917.0
Name: 10425, dtype: object
Daqing
 Age                          28
M/F                           M
City                     Daqing
State                       NaN
Country                     CHN
Half            0 days 01:37:01
40K             0 days 03:21:47
Pace                    0:08:13
TotalSeconds            12107.0
HalfSeconds              5821.0
Name: 4812, dtype: object
Darien
 Age                          42
M/F                           M
City                     Darien
State                        CT
Country                     USA
Half            0 days 01:24:41
40K             0 days 02:47:42
Pace                    0:06:45
TotalSeconds            10062.0
HalfSeconds              5081.0
Name: 1137, dtype: object
Darlington
 Age                          54
M/F                           M
City                 Darlington
State                       NaN
Country                     GBR
Half            0 days 01:43:11
40K             0 days 03:31:15
Pace                    0:08:32
TotalSeconds            12675.0
HalfSeconds              6191.0
Name: 12269, dtype: object
Dartford
 Age                          44
M/F                           M
City                   Dartford
State                       NaN
Country                     GBR
Half            0 days 01:35:31
40K             0 days 03:10:16
Pace                    0:07:45
TotalSeconds            11416.0
HalfSeconds              5731.0

Name: 8903, dtype: object
Dartmouth
 Age                          47
M/F                           F
City                  Dartmouth
State                        NS
Country                     CAN
Half            0 days 01:25:15
40K             0 days 02:49:04
Pace                    0:06:51
TotalSeconds            10144.0
HalfSeconds              5115.0
Name: F112, dtype: object
Date
 Age                          51
M/F                           M
City                       Date
State                       NaN
Country                     JPN
Half            0 days 01:56:00
40K             0 days 03:57:24
Pace                    0:09:39
TotalSeconds            14244.0
HalfSeconds              6960.0
Name: 14282, dtype: object
Dauphin Island
 Age                          38
M/F                           F
City             Dauphin Island
State                        AL
Country                     USA
Half            0 days 01:39:15
40K             0 days 03:06:35
Pace                    0:07:29
TotalSeconds            11195.0
HalfSeconds              5955.0
Name: 12578, dtype: object
Davenport
 Age                          50
M/F                           M
City                  Davenport
State                        IA
Country                     USA
Half            0 days 01:23:59
40K             0 days 02:44:02
Pace                    0:06:39
TotalSeconds             9842.0
HalfSeconds              5039.0
Name: 1773, dtype: object
David City
 Age                          33
M/F                           M
City                 David City
State                        NE
Country                     USA
Half            0 days 01:37:36
40K             0 days 03:25:34
Pace                    0:08:18
TotalSeconds            12334.0
HalfSeconds              5856.0
Name: 2600, dtype: object
Davidson
 Age                          41
M/F                           F
City                   Davidson
State                        NC
Country                     USA
Half            0 days 01:47:20
40K             0 days 03:26:53
Pace                    0:08:23
TotalSeconds            12413.0
HalfSeconds              6440.0
Name: 20405, dtype: object
Davidsonville
 Age                          21
M/F                           F
City              Davidsonville
State                        MD
Country                     USA
Half            0 days 01:45:26
40K             0 days 03:22:38
Pace                    0:08:12
TotalSeconds            12158.0
HalfSeconds              6326.0
Name: 14573, dtype: object
Davie
 Age                          38
M/F                           M
City                      Davie
State                        FL
Country                     USA
Half            0 days 01:24:20
40K             0 days 02:51:18
Pace                    0:07:00
TotalSeconds            10278.0
HalfSeconds              5060.0
Name: 4097, dtype: object
Davis
 Age                          28
M/F                           M
City                      Davis
State                        CA
Country                     USA
Half            0 days 01:25:17
40K             0 days 02:42:52
Pace                    0:06:34
TotalSeconds             9772.0
HalfSeconds              5117.0
Name: 2632, dtype: object
Davison
 Age                          53
M/F                           M
City                    Davison
State                        MI
Country                     USA
Half            0 days 01:51:51
40K             0 days 03:29:42
Pace                    0:08:29
TotalSeconds            12582.0
HalfSeconds              6711.0
Name: 14412, dtype: object
Dawsonville
 Age                          46
M/F                           F
City                Dawsonville
State                        GA
Country                     USA
Half            0 days 02:06:06
40K             0 days 04:04:50
Pace                    0:09:51
TotalSeconds            14690.0
HalfSeconds              7566.0
Name: 29369, dtype: object
Dayton
 Age                          29
M/F                           M
City                     Dayton
State                        OH
Country                     USA
Half            0 days 01:31:57
40K             0 days 02:53:37
Pace                    0:07:00
TotalSeconds            10417.0
HalfSeconds              5517.0
Name: 3508, dtype: object
Daytona Beach
 Age                          49
M/F                           F
City              Daytona Beach
State                        FL
Country                     USA
Half            0 days 01:50:22
40K             0 days 03:45:10
Pace                    0:09:08
TotalSeconds            13510.0
HalfSeconds              6622.0
Name: 12976, dtype: object
Dayville
 Age                          38
M/F                           F
City                   Dayville
State                        CT
Country                     USA
Half            0 days 01:56:57
40K             0 days 03:48:20
Pace                    0:09:11
TotalSeconds            13700.0
HalfSeconds              7017.0
Name: 20483, dtype: object
Ddo
 Age                          51
M/F                           F
City                        Ddo
State                        QC
Country                     CAN
Half            0 days 01:57:27
40K             0 days 03:57:23
Pace                    0:09:35
TotalSeconds            14243.0
HalfSeconds              7047.0
Name: 23425, dtype: object
De Forest
 Age                          28
M/F                           M
City                  De Forest
State                        WI
Country                     USA
Half            0 days 01:30:29
40K             0 days 03:00:28
Pace                    0:07:26
TotalSeconds            10828.0
HalfSeconds              5429.0
Name: 4567, dtype: object
De Pere
 Age                          23
M/F                           M
City                    De Pere
State                        WI
Country                     USA
Half            0 days 01:19:29
40K             0 days 02:36:12
Pace                    0:06:21
TotalSeconds             9372.0
HalfSeconds              4769.0
Name: 544, dtype: object
De Soto
 Age                          36
M/F                           F
City                    De Soto
State                        MO
Country                     USA
Half            0 days 01:48:23
40K             0 days 03:33:56
Pace                    0:08:37
TotalSeconds            12836.0
HalfSeconds              6503.0
Name: 14477, dtype: object
Dearborn
 Age                          35
M/F                           F
City                   Dearborn
State                        MI
Country                     USA
Half            0 days 01:38:09
40K             0 days 03:14:56
Pace                    0:07:54
TotalSeconds            11696.0
HalfSeconds              5889.0
Name: 7327, dtype: object
Dearborn Heights
 Age                           36
M/F                            F
City            Dearborn Heights
State                         MI
Country                      USA
Half             0 days 01:43:03
40K              0 days 03:14:56
Pace                     0:07:50
TotalSeconds             11696.0
HalfSeconds               6183.0
Name: 16086, dtype: object
Debary
 Age                          54
M/F                           M
City                     Debary
State                        FL
Country                     USA
Half            0 days 01:46:13
40K             0 days 03:26:53
Pace                    0:08:24
TotalSeconds            12413.0
HalfSeconds              6373.0
Name: 13269, dtype: object
Debre Birhan
 Age                          25
M/F                           F
City               Debre Birhan
State                       NaN
Country                     ETH
Half            0 days 01:15:33
40K             0 days 02:34:31
Pace                    0:06:17
TotalSeconds             9271.0
HalfSeconds              4533.0
Name: F8, dtype: object
Decatur
 Age                          28
M/F                           M
City                    Decatur
State                        GA
Country                     USA
Half            0 days 01:25:33
40K             0 days 02:44:12
Pace                    0:06:38
TotalSeconds             9852.0
HalfSeconds              5133.0
Name: 1955, dtype: object
Deception Bay
 Age                          49
M/F                           M
City              Deception Bay
State                       NaN
Country                     AUS
Half            0 days 01:33:13
40K             0 days 03:06:26
Pace                    0:07:35
TotalSeconds            11186.0
HalfSeconds              5593.0
Name: 10355, dtype: object
Decorah
 Age                          54
M/F                           M
City                    Decorah
State                        IA
Country                     USA
Half            0 days 01:35:52
40K             0 days 03:08:35
Pace                    0:07:37
TotalSeconds            11315.0
HalfSeconds              5752.0
Name: 11341, dtype: object
Dedham
 Age                          44
M/F                           M
City                     Dedham
State                        MA
Country                     USA
Half            0 days 01:31:13
40K             0 days 02:58:39
Pace                    0:07:14
TotalSeconds            10719.0
HalfSeconds              5473.0
Name: 5632, dtype: object
Dee Why
 Age                          57
M/F                           M
City                    Dee Why
State                       NaN
Country                     AUS
Half            0 days 01:57:30
40K             0 days 03:50:59
Pace                    0:09:20
TotalSeconds            13859.0
HalfSeconds              7050.0
Name: 14432, dtype: object
Deep River
 Age                          37
M/F                           M
City                 Deep River
State                        ON
Country                     CAN
Half            0 days 01:33:18
40K             0 days 02:58:04
Pace                    0:07:10
TotalSeconds            10684.0
HalfSeconds              5598.0
Name: 4328, dtype: object
Deer Park
 Age                          47
M/F                           F
City                  Deer Park
State                        TX
Country                     USA
Half            0 days 01:53:26
40K             0 days 03:43:20
Pace                    0:09:00
TotalSeconds            13400.0
HalfSeconds              6806.0
Name: 22086, dtype: object
Deer River
 Age                          32
M/F                           F
City                 Deer River
State                        MN
Country                     USA
Half            0 days 01:51:54
40K             0 days 04:02:46
Pace                    0:09:47
TotalSeconds            14566.0
HalfSeconds              6714.0
Name: 16891, dtype: object
Deerfield
 Age                          44
M/F                           F
City                  Deerfield
State                        IL
Country                     USA
Half            0 days 01:44:45
40K             0 days 03:23:09
Pace                    0:08:11
TotalSeconds            12189.0
HalfSeconds              6285.0
Name: 16480, dtype: object
Deerfield Beach
 Age                          22
M/F                           F
City            Deerfield Beach
State                        FL
Country                     USA
Half            0 days 01:37:19
40K             0 days 03:09:41
Pace                    0:07:38
TotalSeconds            11381.0
HalfSeconds              5839.0
Name: 11141, dtype: object
Defiance
 Age                          35
M/F                           M
City                   Defiance
State                        OH
Country                     USA
Half            0 days 01:30:14
40K             0 days 02:56:08
Pace                    0:07:07
TotalSeconds            10568.0
HalfSeconds              5414.0
Name: 4627, dtype: object
Deford
 Age                          45
M/F                           F
City                     Deford
State                        MI
Country                     USA
Half            0 days 01:52:41
40K             0 days 03:40:28
Pace                    0:08:57
TotalSeconds            13228.0
HalfSeconds              6761.0
Name: 19697, dtype: object
Deforest
 Age                          49
M/F                           F
City                   Deforest
State                        WI
Country                     USA
Half            0 days 01:57:53
40K             0 days 03:51:41
Pace                    0:09:22
TotalSeconds            13901.0
HalfSeconds              7073.0
Name: 24403, dtype: object
Dekalb
 Age                          35
M/F                           M
City                     Dekalb
State                        IL
Country                     USA
Half            0 days 01:32:32
40K             0 days 03:06:30
Pace                    0:07:34
TotalSeconds            11190.0
HalfSeconds              5552.0
Name: 1946, dtype: object
Del Mar
 Age                          51
M/F                           M
City                    Del Mar
State                        CA
Country                     USA
Half            0 days 01:45:50
40K             0 days 03:46:37
Pace                    0:09:13
TotalSeconds            13597.0
HalfSeconds              6350.0
Name: 12876, dtype: object
Delafield
 Age                          61
M/F                           M
City                  Delafield
State                        WI
Country                     USA
Half            0 days 01:48:15
40K             0 days 03:37:29
Pace                    0:08:47
TotalSeconds            13049.0
HalfSeconds              6495.0
Name: 13570, dtype: object
Deland
 Age                          37
M/F                           F
City                     Deland
State                        FL
Country                     USA
Half            0 days 01:45:04
40K             0 days 03:26:17
Pace                    0:08:19
TotalSeconds            12377.0
HalfSeconds              6304.0
Name: 16239, dtype: object
Delavan
 Age                          32
M/F                           M
City                    Delavan
State                        WI
Country                     USA
Half            0 days 01:30:53
40K             0 days 03:00:33
Pace                    0:07:22
TotalSeconds            10833.0
HalfSeconds              5453.0
Name: 4674, dtype: object
Delaware
 Age                          46
M/F                           M
City                   Delaware
State                        OH
Country                     USA
Half            0 days 01:27:21
40K             0 days 02:48:51
Pace                    0:06:49
TotalSeconds            10131.0
HalfSeconds              5241.0
Name: 2664, dtype: object
Delegacion Miguel Hidalgo
 Age                                    45
M/F                                     M
City            Delegacion Miguel Hidalgo
State                                 NaN
Country                               MEX
Half                      0 days 01:34:11
40K                       0 days 03:11:12
Pace                              0:07:44
TotalSeconds                      11472.0
HalfSeconds                        5651.0
Name: 12217, dtype: object
Delegación Miguel Hidalgo
 Age                                    43
M/F                                     M
City            Delegación Miguel Hidalgo
State                                 NaN
Country                               MEX
Half                      0 days 01:31:15
40K                       0 days 03:11:14
Pace                              0:07:48
TotalSeconds                      11474.0
HalfSeconds                        5475.0
Name: 5840, dtype: object
Delgany, Co. Wicklow
 Age                               38
M/F                                M
City            Delgany, Co. Wicklow
State                            NaN
Country                          IRL
Half                 0 days 01:30:55
40K                  0 days 03:10:02
Pace                         0:07:41
TotalSeconds                 11402.0
HalfSeconds                   5455.0
Name: 1641, dtype: object
Dell Rapids
 Age                          44
M/F                           F
City                Dell Rapids
State                        SD
Country                     USA
Half            0 days 01:57:18
40K             0 days 03:57:16
Pace                    0:09:35
TotalSeconds            14236.0
HalfSeconds              7038.0
Name: 21376, dtype: object
Dellroy
 Age                          61
M/F                           M
City                    Dellroy
State                        OH
Country                     USA
Half            0 days 02:08:21
40K             0 days 04:25:15
Pace                    0:10:47
TotalSeconds            15915.0
HalfSeconds              7701.0
Name: 21040, dtype: object
Delmar
 Age                          47
M/F                           M
City                     Delmar
State                        NY
Country                     USA
Half            0 days 01:36:23
40K             0 days 03:09:06
Pace                    0:07:39
TotalSeconds            11346.0
HalfSeconds              5783.0
Name: 9358, dtype: object
Delmas
 Age                          64
M/F                           M
City                     Delmas
State                        SK
Country                     CAN
Half            0 days 01:52:29
40K             0 days 03:52:03
Pace                    0:09:26
TotalSeconds            13923.0
HalfSeconds              6749.0
Name: 22454, dtype: object
Delray Beach
 Age                          29
M/F                           M
City               Delray Beach
State                        FL
Country                     USA
Half            0 days 01:25:50
40K             0 days 02:50:20
Pace                    0:06:53
TotalSeconds            10220.0
HalfSeconds              5150.0
Name: 1833, dtype: object
Delta
 Age                          42
M/F                           F
City                      Delta
State                        BC
Country                     CAN
Half            0 days 01:42:40
40K             0 days 03:20:59
Pace                    0:08:09
TotalSeconds            12059.0
HalfSeconds              6160.0
Name: 19791, dtype: object
Deltona
 Age                          58
M/F                           F
City                    Deltona
State                        FL
Country                     USA
Half            0 days 02:08:40
40K             0 days 04:28:31
Pace                    0:10:51
TotalSeconds            16111.0
HalfSeconds              7720.0
Name: 25375, dtype: object
Demarest
 Age                          50
M/F                           M
City                   Demarest
State                        NJ
Country                     USA
Half            0 days 01:40:56
40K             0 days 03:17:37
Pace                    0:07:59
TotalSeconds            11857.0
HalfSeconds              6056.0

Name: 10147, dtype: object
Den Bosch
 Age                          49
M/F                           M
City                  Den Bosch
State                       NaN
Country                     NED
Half            0 days 01:52:08
40K             0 days 04:03:23
Pace                    0:09:49
TotalSeconds            14603.0
HalfSeconds              6728.0
Name: 31269, dtype: object
Den Haag
 Age                          40
M/F                           M
City                   Den Haag
State                       NaN
Country                     NED
Half            0 days 01:25:06
40K             0 days 02:44:32
Pace                    0:06:39
TotalSeconds             9872.0
HalfSeconds              5106.0
Name: 1890, dtype: object
Denderhoutem
 Age                          45
M/F                           M
City               Denderhoutem
State                       NaN
Country                     BEL
Half            0 days 01:38:22
40K             0 days 03:25:46
Pace                    0:08:19
TotalSeconds            12346.0
HalfSeconds              5902.0
Name: 11233, dtype: object
Dendermonde
 Age                          61
M/F                           M
City                Dendermonde
State                       NaN
Country                     BEL
Half            0 days 01:52:04
40K             0 days 03:54:01
Pace                    0:09:29
TotalSeconds            14041.0
HalfSeconds              6724.0
Name: 12911, dtype: object
Denham Springs
 Age                          45
M/F                           M
City             Denham Springs
State                        LA
Country                     USA
Half            0 days 01:43:18
40K             0 days 03:43:55
Pace                    0:09:03
TotalSeconds            13435.0
HalfSeconds              6198.0
Name: 12243, dtype: object
Denmark
 Age                          43
M/F                           F
City                    Denmark
State                        WI
Country                     USA
Half            0 days 01:51:38
40K             0 days 03:52:40
Pace                    0:09:23
TotalSeconds            13960.0
HalfSeconds              6698.0
Name: 21078, dtype: object
Dennisport
 Age                          65
M/F                           M
City                 Dennisport
State                        MA
Country                     USA
Half            0 days 01:52:18
40K             0 days 03:59:15
Pace                    0:09:43
TotalSeconds            14355.0
HalfSeconds              6738.0
Name: 19370, dtype: object
Denton
 Age                          34
M/F                           M
City                     Denton
State                        TX
Country                     USA
Half            0 days 01:33:48
40K             0 days 03:07:08
Pace                    0:07:38
TotalSeconds            11228.0
HalfSeconds              5628.0
Name: 5313, dtype: object
Denvens
 Age                          26
M/F                           F
City                    Denvens
State                        MA
Country                     USA
Half            0 days 01:57:11
40K             0 days 03:51:58
Pace                    0:09:21
TotalSeconds            13918.0
HalfSeconds              7031.0
Name: 29117, dtype: object
Denver
 Age                          28
M/F                           M
City                     Denver
State                        CO
Country                     USA
Half            0 days 01:18:40
40K             0 days 02:32:18
Pace                    0:06:09
TotalSeconds             9138.0
HalfSeconds              4720.0
Name: 498, dtype: object
Depew
 Age                          46
M/F                           F
City                      Depew
State                        NY
Country                     USA
Half            0 days 02:03:59
40K             0 days 04:05:23
Pace                    0:09:55
TotalSeconds            14723.0
HalfSeconds              7439.0
Name: 14464, dtype: object
Derby
 Age                          53
M/F                           M
City                      Derby
State                        NY
Country                     USA
Half            0 days 01:40:57
40K             0 days 03:14:10
Pace                    0:07:49
TotalSeconds            11650.0
HalfSeconds              6057.0
Name: 11016, dtype: object
Derbyshire
 Age                          49
M/F                           M
City                 Derbyshire
State                       NaN
Country                     GBR
Half            0 days 01:41:05
40K             0 days 03:27:11
Pace                    0:08:25
TotalSeconds            12431.0
HalfSeconds              6065.0
Name: 10011, dtype: object
Deridder
 Age                          27
M/F                           F
City                   Deridder
State                        LA
Country                     USA
Half            0 days 01:38:46
40K             0 days 03:16:54
Pace                    0:07:58
TotalSeconds            11814.0
HalfSeconds              5926.0
Name: 10789, dtype: object
Derry
 Age                          52
M/F                           F
City                      Derry
State                        NH
Country                     USA
Half            0 days 01:47:23
40K             0 days 03:31:09
Pace                    0:08:33
TotalSeconds            12669.0
HalfSeconds              6443.0
Name: 28302, dtype: object
Derwood
 Age                          35
M/F                           M
City                    Derwood
State                        MD
Country                     USA
Half            0 days 01:30:55
40K             0 days 03:16:27
Pace                    0:07:58
TotalSeconds            11787.0
HalfSeconds              5455.0
Name: 5843, dtype: object
Des Moines
 Age                          48
M/F                           M
City                 Des Moines
State                        IA
Country                     USA
Half            0 days 01:26:35
40K             0 days 02:49:40
Pace                    0:06:53
TotalSeconds            10180.0
HalfSeconds              5195.0
Name: 2775, dtype: object
Destin
 Age                          54
M/F                           M
City                     Destin
State                        FL
Country                     USA
Half            0 days 01:45:55
40K             0 days 03:30:25
Pace                    0:08:29
TotalSeconds            12625.0
HalfSeconds              6355.0
Name: 12934, dtype: object
Detroit
 Age                          30
M/F                           F
City                    Detroit
State                        MI
Country                     USA
Half            0 days 01:40:10
40K             0 days 03:10:59
Pace                    0:07:42
TotalSeconds            11459.0
HalfSeconds              6010.0
Name: 10136, dtype: object
Detroit Lakes
 Age                          54
M/F                           F
City              Detroit Lakes
State                        MN
Country                     USA
Half            0 days 01:54:42
40K             0 days 03:55:09
Pace                    0:09:35
TotalSeconds            14109.0
HalfSeconds              6882.0
Name: 22011, dtype: object
Devils Lake
 Age                          60
M/F                           M
City                Devils Lake
State                        ND
Country                     USA
Half            0 days 01:59:33
40K             0 days 04:15:27
Pace                    0:10:25
TotalSeconds            15327.0
HalfSeconds              7173.0
Name: 21889, dtype: object
Devon
 Age                          40
M/F                           M
City                      Devon
State                        PA
Country                     USA
Half            0 days 01:35:30
40K             0 days 03:05:40
Pace                    0:07:29
TotalSeconds            11140.0
HalfSeconds              5730.0
Name: 5456, dtype: object
Devonshire
 Age                          38
M/F                           M
City                 Devonshire
State                       NaN
Country                     BER
Half            0 days 01:59:05
40K             0 days 03:52:25
Pace                    0:09:26
TotalSeconds            13945.0
HalfSeconds              7145.0
Name: 29918, dtype: object
Dewitt
 Age                          42
M/F                           F
City                     Dewitt
State                        MI
Country                     USA
Half            0 days 01:49:22
40K             0 days 03:40:19
Pace                    0:08:55
TotalSeconds            13219.0
HalfSeconds              6562.0
Name: 20427, dtype: object
Dexter
 Age                          46
M/F                           M
City                     Dexter
State                        MI
Country                     USA
Half            0 days 01:29:40
40K             0 days 03:06:12
Pace                    0:07:33
TotalSeconds            11172.0
HalfSeconds              5380.0

Name: 1133, dtype: object
Df
 Age                          43
M/F                           F
City                         Df
State                       NaN
Country                     MEX
Half            0 days 01:39:08
40K             0 days 03:15:31
Pace                    0:07:55
TotalSeconds            11731.0
HalfSeconds              5948.0
Name: 10312, dtype: object
Diamond Bar
 Age                          66
M/F                           M
City                Diamond Bar
State                        CA
Country                     USA
Half            0 days 01:54:10
40K             0 days 03:36:43
Pace                    0:08:42
TotalSeconds            13003.0
HalfSeconds              6850.0
Name: 22274, dtype: object
Diamond Springs
 Age                          30
M/F                           M
City            Diamond Springs
State                        CA
Country                     USA
Half            0 days 01:33:29
40K             0 days 03:05:56
Pace                    0:07:32
TotalSeconds            11156.0
HalfSeconds              5609.0
Name: 4717, dtype: object
Diddillibah
 Age                          42
M/F                           M
City                Diddillibah
State                       NaN
Country                     AUS
Half            0 days 01:44:34
40K             0 days 03:25:28
Pace                    0:08:19
TotalSeconds            12328.0
HalfSeconds              6274.0
Name: 31551, dtype: object
Diego Martin
 Age                          51
M/F                           F
City               Diego Martin
State                       NaN
Country                     TRI
Half            0 days 01:50:19
40K             0 days 03:40:58
Pace                    0:08:59
TotalSeconds            13258.0
HalfSeconds              6619.0
Name: 22774, dtype: object
Dieppe
 Age                          48
M/F                           M
City                     Dieppe
State                        NB
Country                     CAN
Half            0 days 01:38:52
40K             0 days 03:20:01
Pace                    0:08:05
TotalSeconds            12001.0
HalfSeconds              5932.0
Name: 12324, dtype: object
Dighton
 Age                          39
M/F                           M
City                    Dighton
State                        MA
Country                     USA
Half            0 days 02:15:58
40K             0 days 04:36:41
Pace                    0:11:10
TotalSeconds            16601.0
HalfSeconds              8158.0
Name: 29897, dtype: object
Dillingen
 Age                          42
M/F                           M
City                  Dillingen
State                       NaN
Country                     GER
Half            0 days 01:29:58
40K             0 days 03:05:43
Pace                    0:07:32
TotalSeconds            11143.0
HalfSeconds              5398.0
Name: 2629, dtype: object
Dillon
 Age                          56
M/F                           F
City                     Dillon
State                        CO
Country                     USA
Half            0 days 02:10:52
40K             0 days 04:38:01
Pace                    0:11:14
TotalSeconds            16681.0
HalfSeconds              7852.0
Name: 25195, dtype: object
Dillsburg
 Age                          39
M/F                           F
City                  Dillsburg
State                        PA
Country                     USA
Half            0 days 01:36:02
40K             0 days 03:05:33
Pace                    0:07:28
TotalSeconds            11133.0
HalfSeconds              5762.0
Name: 12749, dtype: object
Distrito Federal
 Age                           43
M/F                            M
City            Distrito Federal
State                        NaN
Country                      MEX
Half             0 days 01:29:29
40K              0 days 03:07:37
Pace                     0:07:37
TotalSeconds             11257.0
HalfSeconds               5369.0
Name: 3189, dtype: object
Divinópolis
 Age                          40
M/F                           F
City                Divinópolis
State                       NaN
Country                     BRA
Half            0 days 01:48:19
40K             0 days 03:35:29
Pace                    0:08:42
TotalSeconds            12929.0
HalfSeconds              6499.0
Name: 18601, dtype: object
Dix Hills
 Age                          59
M/F                           F
City                  Dix Hills
State                        NY
Country                     USA
Half            0 days 01:50:37
40K             0 days 03:41:54
Pace                    0:08:57
TotalSeconds            13314.0
HalfSeconds              6637.0
Name: 19452, dtype: object
Dixon
 Age                          30
M/F                           M
City                      Dixon
State                        CA
Country                     USA
Half            0 days 01:30:08
40K             0 days 03:01:11
Pace                    0:07:20
TotalSeconds            10871.0
HalfSeconds              5408.0
Name: 5297, dtype: object
Dobbiaco
 Age                          45
M/F                           M
City                   Dobbiaco
State                       NaN
Country                     ITA
Half            0 days 01:50:30
40K             0 days 03:48:43
Pace                    0:09:16
TotalSeconds            13723.0
HalfSeconds              6630.0
Name: 31830, dtype: object
Dobbs Ferry
 Age                          52
M/F                           M
City                Dobbs Ferry
State                        NY
Country                     USA
Half            0 days 01:45:53
40K             0 days 03:43:44
Pace                    0:09:05
TotalSeconds            13424.0
HalfSeconds              6353.0
Name: 14564, dtype: object
Dodgeville
 Age                          51
M/F                           M
City                 Dodgeville
State                        WI
Country                     USA
Half            0 days 01:39:41
40K             0 days 03:10:36
Pace                    0:07:41
TotalSeconds            11436.0
HalfSeconds              5981.0
Name: 9469, dtype: object
Dollard-Des-Ormeaux
 Age                              50
M/F                               F
City            Dollard-Des-Ormeaux
State                            QC
Country                         CAN
Half                0 days 01:42:17
40K                 0 days 03:21:38
Pace                        0:08:08
TotalSeconds                12098.0
HalfSeconds                  6137.0
Name: 14474, dtype: object
Dolton
 Age                          59
M/F                           M
City                     Dolton
State                        IL
Country                     USA
Half            0 days 01:35:43
40K             0 days 03:20:36
Pace                    0:08:09
TotalSeconds            12036.0
HalfSeconds              5743.0
Name: 6671, dtype: object
Donaustauf
 Age                          47
M/F                           M
City                 Donaustauf
State                       NaN
Country                     GER
Half            0 days 01:34:22
40K             0 days 03:12:12
Pace                    0:07:47
TotalSeconds            11532.0
HalfSeconds              5662.0
Name: 9648, dtype: object
Doncaster
 Age                          33
M/F                           M
City                  Doncaster
State                       NaN
Country                     GBR
Half            0 days 02:14:12
40K             0 days 04:29:07
Pace                    0:10:53
TotalSeconds            16147.0
HalfSeconds              8052.0
Name: 26100, dtype: object
Doniphan
 Age                          34
M/F                           M
City                   Doniphan
State                        NE
Country                     USA
Half            0 days 01:31:12
40K             0 days 03:12:23
Pace                    0:07:52
TotalSeconds            11543.0
HalfSeconds              5472.0
Name: 5675, dtype: object
Donnacona
 Age                          36
M/F                           F
City                  Donnacona
State                        QC
Country                     CAN
Half            0 days 01:46:28
40K             0 days 03:36:43
Pace                    0:08:45
TotalSeconds            13003.0
HalfSeconds              6388.0
Name: 9689, dtype: object
Doral
 Age                          31
M/F                           F
City                      Doral
State                        FL
Country                     USA
Half            0 days 01:40:58
40K             0 days 03:11:00
Pace                    0:07:40
TotalSeconds            11460.0
HalfSeconds              6058.0
Name: 11920, dtype: object
Dorchester
 Age                          28
M/F                           M
City                 Dorchester
State                        MA
Country                     USA
Half            0 days 01:12:32
40K             0 days 02:35:32
Pace                    0:06:26
TotalSeconds             9332.0
HalfSeconds              4352.0
Name: 982, dtype: object
Dorchester Center
 Age                            29
M/F                             M
City            Dorchester Center
State                          MA
Country                       USA
Half              0 days 01:55:36
40K               0 days 04:15:01
Pace                      0:10:18
TotalSeconds              15301.0
HalfSeconds                6936.0
Name: 30068, dtype: object
Dorr
 Age                          44
M/F                           M
City                       Dorr
State                        MI
Country                     USA
Half            0 days 01:30:19
40K             0 days 02:54:21
Pace                    0:07:01
TotalSeconds            10461.0
HalfSeconds              5419.0
Name: 6340, dtype: object
Dorval
 Age                          52
M/F                           M
City                     Dorval
State                        QC
Country                     CAN
Half            0 days 01:32:49
40K             0 days 03:10:57
Pace                    0:07:44
TotalSeconds            11457.0
HalfSeconds              5569.0
Name: 6733, dtype: object
Doswell
 Age                          43
M/F                           M
City                    Doswell
State                        VA
Country                     USA
Half            0 days 01:38:48
40K             0 days 03:20:04
Pace                    0:08:06
TotalSeconds            12004.0
HalfSeconds              5928.0
Name: 7052, dtype: object
Dothan
 Age                          27
M/F                           M
City                     Dothan
State                        AL
Country                     USA
Half            0 days 01:22:27
40K             0 days 02:42:26
Pace                    0:06:33
TotalSeconds             9746.0
HalfSeconds              4947.0
Name: 1723, dtype: object
Douglas
 Age                          39
M/F                           F
City                    Douglas
State                        WY
Country                     USA
Half            0 days 01:52:33
40K             0 days 03:41:46
Pace                    0:08:56
TotalSeconds            13306.0
HalfSeconds              6753.0
Name: 19663, dtype: object
Douglas Cork
 Age                          36
M/F                           M
City               Douglas Cork
State                       NaN
Country                     IRL
Half            0 days 02:01:08
40K             0 days 04:03:47
Pace                    0:09:51
TotalSeconds            14627.0
HalfSeconds              7268.0
Name: 28633, dtype: object
Douglass
 Age                          60
M/F                           F
City                   Douglass
State                        KS
Country                     USA
Half            0 days 02:11:19
40K             0 days 04:28:59
Pace                    0:10:54
TotalSeconds            16139.0
HalfSeconds              7879.0
Name: 25457, dtype: object
Douglaston
 Age                          41
M/F                           F
City                 Douglaston
State                        NY
Country                     USA
Half            0 days 01:53:36
40K             0 days 03:45:00
Pace                    0:09:07
TotalSeconds            13500.0
HalfSeconds              6816.0
Name: 20769, dtype: object
Douglasville
 Age                          41
M/F                           F
City               Douglasville
State                        GA
Country                     USA
Half            0 days 01:55:57
40K             0 days 03:54:37
Pace                    0:09:30
TotalSeconds            14077.0
HalfSeconds              6957.0
Name: 20845, dtype: object
Douglaville
 Age                          32
M/F                           F
City                Douglaville
State                        GA
Country                     USA
Half            0 days 02:11:12
40K             0 days 04:26:20
Pace                    0:10:42
TotalSeconds            15980.0
HalfSeconds              7872.0
Name: 26951, dtype: object
Dover
 Age                          37
M/F                           M
City                      Dover
State                        DE
Country                     USA
Half            0 days 01:26:00
40K             0 days 02:50:14
Pace                    0:06:54
TotalSeconds            10214.0
HalfSeconds              5160.0
Name: 1557, dtype: object
Dover Foxcroft
 Age                          59
M/F                           M
City             Dover Foxcroft
State                        ME
Country                     USA
Half            0 days 01:47:27
40K             0 days 03:27:33
Pace                    0:08:23
TotalSeconds            12453.0
HalfSeconds              6447.0
Name: 20242, dtype: object
Dover-Foxcroft
 Age                          25
M/F                           M
City             Dover-Foxcroft
State                        ME
Country                     USA
Half            0 days 01:23:52
40K             0 days 02:42:59
Pace                    0:06:35
TotalSeconds             9779.0
HalfSeconds              5032.0
Name: 1083, dtype: object
Downers Grove
 Age                          41
M/F                           M
City              Downers Grove
State                        IL
Country                     USA
Half            0 days 01:25:40
40K             0 days 02:53:42
Pace                    0:07:05
TotalSeconds            10422.0
HalfSeconds              5140.0
Name: 1187, dtype: object
Downey
 Age                          42
M/F                           M
City                     Downey
State                        CA
Country                     USA
Half            0 days 01:16:16
40K             0 days 02:27:27
Pace                    0:05:58
TotalSeconds             8847.0
HalfSeconds              4576.0
Name: 229, dtype: object
Downingtown
 Age                          34
M/F                           M
City                Downingtown
State                        PA
Country                     USA
Half            0 days 01:24:42
40K             0 days 02:45:51
Pace                    0:06:43
TotalSeconds             9951.0
HalfSeconds              5082.0
Name: 2128, dtype: object
Doylestown
 Age                          33
M/F                           M
City                 Doylestown
State                        PA
Country                     USA
Half            0 days 01:24:51
40K             0 days 02:47:09
Pace                    0:06:45
TotalSeconds            10029.0
HalfSeconds              5091.0
Name: 3475, dtype: object
Dracut
 Age                          48
M/F                           M
City                     Dracut
State                        MA
Country                     USA
Half            0 days 01:33:08
40K             0 days 03:02:33
Pace                    0:07:23
TotalSeconds            10953.0
HalfSeconds              5588.0
Name: 12198, dtype: object
Draillant
 Age                          39
M/F                           M
City                  Draillant
State                       NaN
Country                     FRA
Half            0 days 01:33:40
40K             0 days 03:12:51
Pace                    0:07:48
TotalSeconds            11571.0
HalfSeconds              5620.0
Name: 7241, dtype: object
Draper

 Age                          32
M/F                           M
City                     Draper
State                        UT
Country                     USA
Half            0 days 01:21:27
40K             0 days 02:45:02
Pace                    0:06:40
TotalSeconds             9902.0
HalfSeconds              4887.0
Name: 587, dtype: object
Dresden
 Age                          36
M/F                           M
City                    Dresden
State                       NaN
Country                     GER
Half            0 days 01:27:35
40K             0 days 02:59:27
Pace                    0:07:18
TotalSeconds            10767.0
HalfSeconds              5255.0
Name: 31862, dtype: object
Drexel Hill
 Age                          52
M/F                           M
City                Drexel Hill
State                        PA
Country                     USA
Half            0 days 01:40:18
40K             0 days 03:09:11
Pace                    0:07:37
TotalSeconds            11351.0
HalfSeconds              6018.0
Name: 11861, dtype: object
Dripping Springs
 Age                           50
M/F                            F
City            Dripping Springs
State                         TX
Country                      USA
Half             0 days 02:16:12
40K              0 days 04:33:44
Pace                     0:10:59
TotalSeconds             16424.0
HalfSeconds               8172.0
Name: 22824, dtype: object
Drongen
 Age                          48
M/F                           M
City                    Drongen
State                       NaN
Country                     BEL
Half            0 days 01:22:31
40K             0 days 02:43:38
Pace                    0:06:38
TotalSeconds             9818.0
HalfSeconds              4951.0
Name: 2407, dtype: object
Drummondville
 Age                          41
M/F                           M
City              Drummondville
State                        QC
Country                     CAN
Half            0 days 01:27:08
40K             0 days 02:52:28
Pace                    0:06:57
TotalSeconds            10348.0
HalfSeconds              5228.0
Name: 2955, dtype: object
Drummoyne
 Age                          30
M/F                           M
City                  Drummoyne
State                       NaN
Country                     AUS
Half            0 days 01:30:56
40K             0 days 03:14:22
Pace                    0:07:52
TotalSeconds            11662.0
HalfSeconds              5456.0
Name: 4725, dtype: object
Dryden
 Age                          54
M/F                           F
City                     Dryden
State                        NY
Country                     USA
Half            0 days 01:47:12
40K             0 days 03:34:10
Pace                    0:08:42
TotalSeconds            12850.0
HalfSeconds              6432.0
Name: 24056, dtype: object
Dubai
 Age                          45
M/F                           M
City                      Dubai
State                       NaN
Country                     UAE
Half            0 days 01:29:59
40K             0 days 03:04:41
Pace                    0:07:32
TotalSeconds            11081.0
HalfSeconds              5399.0
Name: 3581, dtype: object
Dubai International Financial Centre
 Age                                               45
M/F                                                M
City            Dubai International Financial Centre
State                                            NaN
Country                                          UAE
Half                                 0 days 01:40:52
40K                                  0 days 03:36:54
Pace                                         0:08:54
TotalSeconds                                 13014.0
HalfSeconds                                   6052.0
Name: 9149, dtype: object
Dubai, PO Box
 Age                          46
M/F                           M
City              Dubai, PO Box
State                       NaN
Country                     UAE
Half            0 days 01:41:07
40K             0 days 03:34:25
Pace                    0:08:43
TotalSeconds            12865.0
HalfSeconds              6067.0
Name: 10516, dtype: object
Dubbo
 Age                          60
M/F                           M
City                      Dubbo
State                       NaN
Country                     AUS
Half            0 days 02:02:49
40K             0 days 04:28:12
Pace                    0:10:51
TotalSeconds            16092.0
HalfSeconds              7369.0
Name: 20036, dtype: object
Dublin
 Age                          46
M/F                           M
City                     Dublin
State                        OH
Country                     USA
Half            0 days 01:17:46
40K             0 days 02:32:04
Pace                    0:06:09
TotalSeconds             9124.0
HalfSeconds              4666.0
Name: 598, dtype: object
Dublin 24
 Age                          58
M/F                           M
City                  Dublin 24
State                       NaN
Country                     IRL
Half            0 days 01:44:52
40K             0 days 03:27:32
Pace                    0:08:24
TotalSeconds            12452.0
HalfSeconds              6292.0
Name: 31711, dtype: object
Dublin 3
 Age                          46
M/F                           M
City                   Dublin 3
State                       NaN
Country                     IRL
Half            0 days 01:31:33
40K             0 days 03:11:08
Pace                    0:07:47
TotalSeconds            11468.0
HalfSeconds              5493.0
Name: 4827, dtype: object
Dublin 4
 Age                          32
M/F                           F
City                   Dublin 4
State                       NaN
Country                     IRL
Half            0 days 02:08:29
40K             0 days 04:44:41
Pace                    0:11:26
TotalSeconds            17081.0
HalfSeconds              7709.0
Name: 31780, dtype: object
Dublin 6w
 Age                          42
M/F                           M
City                  Dublin 6w
State                       NaN
Country                     IRL
Half            0 days 01:56:03
40K             0 days 03:55:52
Pace                    0:09:35
TotalSeconds            14152.0
HalfSeconds              6963.0
Name: 31766, dtype: object
Dublin 8
 Age                          28
M/F                           F
City                   Dublin 8
State                       NaN
Country                     IRL
Half            0 days 01:39:29
40K             0 days 03:15:33
Pace                    0:07:53
TotalSeconds            11733.0
HalfSeconds              5969.0
Name: 19277, dtype: object
Dubnica Nad Vahom
 Age                            44
M/F                             M
City            Dubnica Nad Vahom
State                         NaN
Country                       SVK
Half              0 days 01:24:11
40K               0 days 02:45:32
Pace                      0:06:41
TotalSeconds               9932.0
HalfSeconds                5051.0
Name: 1260, dtype: object
Dubois
 Age                          67
M/F                           M
City                     Dubois
State                        WY
Country                     USA
Half            0 days 02:08:44
40K             0 days 04:23:01
Pace                    0:10:39
TotalSeconds            15781.0
HalfSeconds              7724.0
Name: 25361, dtype: object
Duboistown
 Age                          28
M/F                           M
City                 Duboistown
State                        PA
Country                     USA
Half            0 days 01:17:07
40K             0 days 02:36:22
Pace                    0:06:19
TotalSeconds             9382.0
HalfSeconds              4627.0
Name: 220, dtype: object
Dubuque
 Age                          35
M/F                           M
City                    Dubuque
State                        IA
Country                     USA
Half            0 days 01:28:36
40K             0 days 02:48:01
Pace                    0:06:46
TotalSeconds            10081.0
HalfSeconds              5316.0
Name: 3194, dtype: object
Dudley
 Age                          56
M/F                           F
City                     Dudley
State                        MA
Country                     USA
Half            0 days 02:03:37
40K             0 days 04:00:09
Pace                    0:09:40
TotalSeconds            14409.0
HalfSeconds              7417.0
Name: 25104, dtype: object
Duerbheim
 Age                          53
M/F                           M
City                  Duerbheim
State                       NaN
Country                     GER
Half            0 days 01:29:56
40K             0 days 03:00:08
Pace                    0:07:17
TotalSeconds            10808.0
HalfSeconds              5396.0
Name: 3672, dtype: object
Duesseldorf
 Age                          44
M/F                           M
City                Duesseldorf
State                       NaN
Country                     GER
Half            0 days 01:48:51
40K             0 days 03:31:09
Pace                    0:08:31
TotalSeconds            12669.0
HalfSeconds              6531.0
Name: 31128, dtype: object
Duisburg
 Age                          49
M/F                           M
City                   Duisburg
State                       NaN
Country                     GER
Half            0 days 01:52:14
40K             0 days 03:34:35
Pace                    0:08:38
TotalSeconds            12875.0
HalfSeconds              6734.0
Name: 31039, dtype: object
Dulles
 Age                          40
M/F                           F
City                     Dulles
State                        VA
Country                     USA
Half            0 days 02:02:08
40K             0 days 04:16:09
Pace                    0:10:24
TotalSeconds            15369.0
HalfSeconds              7328.0
Name: 20376, dtype: object
Duluth
 Age                          29
M/F                           M
City                     Duluth
State                        MN
Country                     USA
Half            0 days 01:22:56
40K             0 days 02:47:42
Pace                    0:06:46
TotalSeconds            10062.0
HalfSeconds              4976.0
Name: 1123, dtype: object

Dumfries
 Age                          46
M/F                           F
City                   Dumfries
State                        VA
Country                     USA
Half            0 days 01:54:09
40K             0 days 03:39:11
Pace                    0:08:48
TotalSeconds            13151.0
HalfSeconds              6849.0
Name: 23104, dtype: object
Dumont
 Age                          42
M/F                           M
City                     Dumont
State                        NJ
Country                     USA
Half            0 days 01:27:16
40K             0 days 02:50:04
Pace                    0:06:50
TotalSeconds            10204.0
HalfSeconds              5236.0
Name: 3773, dtype: object
Dunbar
 Age                          51
M/F                           M
City                     Dunbar
State                        PA
Country                     USA
Half            0 days 02:01:04
40K             0 days 04:06:58
Pace                    0:09:59
TotalSeconds            14818.0
HalfSeconds              7264.0
Name: 13867, dtype: object
Dunbarton
 Age                          49
M/F                           M
City                  Dunbarton
State                        NH
Country                     USA
Half            0 days 01:26:49
40K             0 days 02:54:11
Pace                    0:07:04
TotalSeconds            10451.0
HalfSeconds              5209.0
Name: 9641, dtype: object
Duncan
 Age                          38
M/F                           F
City                     Duncan
State                        BC
Country                     CAN
Half            0 days 02:04:45
40K             0 days 04:06:50
Pace                    0:09:55
TotalSeconds            14810.0
HalfSeconds              7485.0
Name: 17419, dtype: object
Dundas
 Age                          36
M/F                           M
City                     Dundas
State                        ON
Country                     CAN
Half            0 days 01:34:54
40K             0 days 03:11:12
Pace                    0:07:44
TotalSeconds            11472.0
HalfSeconds              5694.0
Name: 3109, dtype: object
Dunedin
 Age                          34
M/F                           F
City                    Dunedin
State                        FL
Country                     USA
Half            0 days 01:47:10
40K             0 days 03:36:53
Pace                    0:08:46
TotalSeconds            13013.0
HalfSeconds              6430.0
Name: 16572, dtype: object
Dunkirk
 Age                          45
M/F                           M
City                    Dunkirk
State                        MD
Country                     USA
Half            0 days 01:34:12
40K             0 days 03:49:45
Pace                    0:09:11
TotalSeconds            13785.0
HalfSeconds              5652.0
Name: 5942, dtype: object
Dunlap
 Age                          36
M/F                           F
City                     Dunlap
State                        IL
Country                     USA
Half            0 days 01:44:08
40K             0 days 03:27:34
Pace                    0:08:26
TotalSeconds            12454.0
HalfSeconds              6248.0
Name: 14371, dtype: object
Dunmore
 Age                          47
M/F                           F
City                    Dunmore
State                        PA
Country                     USA
Half            0 days 01:48:42
40K             0 days 03:35:36
Pace                    0:08:43
TotalSeconds            12936.0
HalfSeconds              6522.0
Name: 17654, dtype: object
Dunn
 Age                          45
M/F                           M
City                       Dunn
State                        NC
Country                     USA
Half            0 days 01:38:56
40K             0 days 03:39:45
Pace                    0:08:53
TotalSeconds            13185.0
HalfSeconds              5936.0
Name: 10102, dtype: object
Dunrobin
 Age                          60
M/F                           M
City                   Dunrobin
State                        ON
Country                     CAN
Half            0 days 01:47:13
40K             0 days 03:36:26
Pace                    0:08:47
TotalSeconds            12986.0
HalfSeconds              6433.0
Name: 23292, dtype: object
Dunstable
 Age                          46
M/F                           M
City                  Dunstable
State                        MA
Country                     USA
Half            0 days 01:37:37
40K             0 days 03:26:11
Pace                    0:08:20
TotalSeconds            12371.0
HalfSeconds              5857.0
Name: 6577, dtype: object
Dunwoody
 Age                          45
M/F                           M
City                   Dunwoody
State                        GA
Country                     USA
Half            0 days 01:28:57
40K             0 days 02:58:41
Pace                    0:07:17
TotalSeconds            10721.0
HalfSeconds              5337.0
Name: 1249, dtype: object
Dupont
 Age                          44
M/F                           M
City                     Dupont
State                        WA
Country                     USA
Half            0 days 01:34:45
40K             0 days 03:09:41
Pace                    0:07:39
TotalSeconds            11381.0
HalfSeconds              5685.0
Name: 8114, dtype: object
Durand
 Age                          49
M/F                           M
City                     Durand
State                        MI
Country                     USA
Half            0 days 01:35:59
40K             0 days 03:18:19
Pace                    0:08:05
TotalSeconds            11899.0
HalfSeconds              5759.0
Name: 9338, dtype: object
Durango
 Age                          42
M/F                           M
City                    Durango
State                        CO
Country                     USA
Half            0 days 01:25:17
40K             0 days 02:52:31
Pace                    0:06:59
TotalSeconds            10351.0
HalfSeconds              5117.0
Name: 1690, dtype: object
Durham
 Age                          34
M/F                           M
City                     Durham
State                        NC
Country                     USA
Half            0 days 01:18:14
40K             0 days 02:34:33
Pace                    0:06:15
TotalSeconds             9273.0
HalfSeconds              4694.0
Name: 555, dtype: object
Duvall
 Age                          47
M/F                           M
City                     Duvall
State                        WA
Country                     USA
Half            0 days 01:41:57
40K             0 days 03:26:57
Pace                    0:08:21
TotalSeconds            12417.0
HalfSeconds              6117.0
Name: 12523, dtype: object
Duxbury
 Age                          23
M/F                           M
City                    Duxbury
State                        MA
Country                     USA
Half            0 days 01:27:22
40K             0 days 03:07:43
Pace                    0:07:43
TotalSeconds            11263.0
HalfSeconds              5242.0
Name: 1851, dtype: object
Düren
 Age                          41
M/F                           M
City                      Düren
State                       NaN
Country                     GER
Half            0 days 01:42:15
40K             0 days 03:35:08
Pace                    0:08:53
TotalSeconds            12908.0
HalfSeconds              6135.0
Name: 7289, dtype: object
Eagan
 Age                          23
M/F                           M
City                      Eagan
State                        MN
Country                     USA
Half            0 days 01:24:04
40K             0 days 02:42:41
Pace                    0:06:34
TotalSeconds             9761.0
HalfSeconds              5044.0
Name: 2011, dtype: object
Eagar
 Age                          65
M/F                           F
City                      Eagar
State                        AZ
Country                     USA
Half            0 days 02:15:05
40K             0 days 04:33:44
Pace                    0:11:15
TotalSeconds            16424.0
HalfSeconds              8105.0
Name: 25879, dtype: object
Eagleville
 Age                          36
M/F                           M
City                 Eagleville
State                        PA
Country                     USA
Half            0 days 01:36:37
40K             0 days 03:11:49
Pace                    0:07:45
TotalSeconds            11509.0
HalfSeconds              5797.0
Name: 6555, dtype: object
Earlton
 Age                          55
M/F                           M
City                    Earlton
State                        NY
Country                     USA
Half            0 days 01:48:39
40K             0 days 03:57:05
Pace                    0:09:36
TotalSeconds            14225.0
HalfSeconds              6519.0
Name: 13750, dtype: object
Earlville
 Age                          55
M/F                           M
City                  Earlville
State                        IL
Country                     USA
Half            0 days 01:55:07
40K             0 days 03:54:41
Pace                    0:09:31
TotalSeconds            14081.0
HalfSeconds              6907.0
Name: 18120, dtype: object
Earlysville
 Age                          48
M/F                           F
City                Earlysville
State                        VA
Country                     USA
Half            0 days 01:51:48
40K             0 days 03:52:32
Pace                    0:09:24
TotalSeconds            13952.0
HalfSeconds              6708.0
Name: 21065, dtype: object
Easley
 Age                          57
M/F                           F
City                     Easley
State                        SC
Country                     USA
Half            0 days 02:11:05
40K             0 days 04:38:35
Pace                    0:11:13
TotalSeconds            16715.0
HalfSeconds              7865.0
Name: 25365, dtype: object
East Amherst
 Age                          53
M/F                           M
City               East Amherst
State                        NY
Country                     USA
Half            0 days 01:40:36
40K             0 days 03:15:32
Pace                    0:07:58
TotalSeconds            11732.0
HalfSeconds              6036.0
Name: 14855, dtype: object
East Andover
 Age                          47
M/F                           F
City               East Andover
State                        NH
Country                     USA
Half            0 days 01:42:49
40K             0 days 03:26:22
Pace                    0:08:18
TotalSeconds            12382.0
HalfSeconds              6169.0
Name: 14901, dtype: object
East Aurora
 Age                          26
M/F                           M
City                East Aurora
State                        NY
Country                     USA
Half            0 days 01:25:16
40K             0 days 02:50:16
Pace                    0:06:52
TotalSeconds            10216.0
HalfSeconds              5116.0
Name: 4245, dtype: object
East Boston
 Age                          30
M/F                           F
City                East Boston
State                        MA
Country                     USA
Half            0 days 01:41:16
40K             0 days 03:19:56
Pace                    0:08:05
TotalSeconds            11996.0
HalfSeconds              6076.0
Name: 12750, dtype: object
East Bridgewater
 Age                           37
M/F                            F
City            East Bridgewater
State                         MA
Country                      USA
Half             0 days 02:03:30
40K              0 days 03:56:19
Pace                     0:09:32
TotalSeconds             14179.0
HalfSeconds               7410.0
Name: 27170, dtype: object
East Brunswick
 Age                          28
M/F                           M
City             East Brunswick
State                        NJ
Country                     USA
Half            0 days 01:25:37
40K             0 days 02:46:09
Pace                    0:06:43
TotalSeconds             9969.0
HalfSeconds              5137.0
Name: 2962, dtype: object
East Canton
 Age                          36
M/F                           F
City                East Canton
State                        OH
Country                     USA
Half            0 days 01:47:47
40K             0 days 03:40:04
Pace                    0:08:56
TotalSeconds            13204.0
HalfSeconds              6467.0
Name: 19144, dtype: object
East Elmhurst
 Age                          29
M/F                           M
City              East Elmhurst
State                        NY
Country                     USA
Half            0 days 01:28:22
40K             0 days 02:50:51
Pace                    0:06:53
TotalSeconds            10251.0
HalfSeconds              5302.0
Name: 3401, dtype: object
East Falmouth
 Age                          46
M/F                           F
City              East Falmouth
State                        MA
Country                     USA
Half            0 days 02:16:38
40K             0 days 04:28:29
Pace                    0:10:50
TotalSeconds            16109.0
HalfSeconds              8198.0
Name: 27886, dtype: object
East Freetown
 Age                          44
M/F                           F
City              East Freetown
State                        MA
Country                     USA
Half            0 days 02:18:47
40K             0 days 04:40:30
Pace                    0:11:13
TotalSeconds            16830.0
HalfSeconds              8327.0
Name: 26860, dtype: object
East Grand Rapids
 Age                            44
M/F                             M
City            East Grand Rapids
State                          MI
Country                       USA
Half              0 days 01:48:21
40K               0 days 03:23:11
Pace                      0:08:10
TotalSeconds              12191.0
HalfSeconds                6501.0
Name: 8620, dtype: object
East Greenbush
 Age                          57
M/F                           M
City             East Greenbush
State                        NY
Country                     USA
Half            0 days 01:41:23
40K             0 days 03:17:49
Pace                    0:07:58
TotalSeconds            11869.0
HalfSeconds              6083.0
Name: 13042, dtype: object
East Greenwich
 Age                          33
M/F                           M
City             East Greenwich
State                        RI
Country                     USA
Half            0 days 01:17:32
40K             0 days 02:41:05
Pace                    0:06:31
TotalSeconds             9665.0
HalfSeconds              4652.0
Name: 990, dtype: object
East Haddam

 Age                          24
M/F                           F
City                East Haddam
State                        CT
Country                     USA
Half            0 days 01:38:44
40K             0 days 03:10:55
Pace                    0:07:40
TotalSeconds            11455.0
HalfSeconds              5924.0
Name: 13309, dtype: object
East Hampstead
 Age                          22
M/F                           M
City             East Hampstead
State                        NH
Country                     USA
Half            0 days 01:29:42
40K             0 days 02:52:12
Pace                    0:06:55
TotalSeconds            10332.0
HalfSeconds              5382.0
Name: 4257, dtype: object
East Hampton
 Age                          29
M/F                           F
City               East Hampton
State                        CT
Country                     USA
Half            0 days 01:43:25
40K             0 days 03:21:12
Pace                    0:08:07
TotalSeconds            12072.0
HalfSeconds              6205.0
Name: 10899, dtype: object
East Hardwick
 Age                          42
M/F                           F
City              East Hardwick
State                        VT
Country                     USA
Half            0 days 01:52:14
40K             0 days 03:32:06
Pace                    0:08:31
TotalSeconds            12726.0
HalfSeconds              6734.0
Name: 21207, dtype: object
East Hartford
 Age                          47
M/F                           F
City              East Hartford
State                        CT
Country                     USA
Half            0 days 01:58:09
40K             0 days 03:58:34
Pace                    0:09:44
TotalSeconds            14314.0
HalfSeconds              7089.0
Name: 23001, dtype: object
East Hills
 Age                          61
M/F                           M
City                 East Hills
State                        NY
Country                     USA
Half            0 days 01:50:25
40K             0 days 03:38:27
Pace                    0:08:50
TotalSeconds            13107.0
HalfSeconds              6625.0
Name: 22053, dtype: object
East Kingston
 Age                          39
M/F                           F
City              East Kingston
State                        NH
Country                     USA
Half            0 days 01:54:29
40K             0 days 03:40:21
Pace                    0:08:53
TotalSeconds            13221.0
HalfSeconds              6869.0
Name: 19849, dtype: object
East Lansing
 Age                          27
M/F                           M
City               East Lansing
State                        MI
Country                     USA
Half            0 days 01:14:17
40K             0 days 02:40:25
Pace                    0:06:30
TotalSeconds             9625.0
HalfSeconds              4457.0
Name: 140, dtype: object
East Liverpool
 Age                          27
M/F                           M
City             East Liverpool
State                        OH
Country                     USA
Half            0 days 01:21:05
40K             0 days 02:38:25
Pace                    0:06:24
TotalSeconds             9505.0
HalfSeconds              4865.0
Name: 801, dtype: object
East Longmeadow
 Age                          41
M/F                           F
City            East Longmeadow
State                        MA
Country                     USA
Half            0 days 01:41:51
40K             0 days 03:16:03
Pace                    0:07:53
TotalSeconds            11763.0
HalfSeconds              6111.0
Name: 14208, dtype: object
East Lyme
 Age                          36
M/F                           M
City                  East Lyme
State                        CT
Country                     USA
Half            0 days 01:29:14
40K             0 days 02:56:55
Pace                    0:07:09
TotalSeconds            10615.0
HalfSeconds              5354.0
Name: 4720, dtype: object
East Malvern
 Age                          64
M/F                           M
City               East Malvern
State                       NaN
Country                     AUS
Half            0 days 02:04:59
40K             0 days 04:04:29
Pace                    0:09:55
TotalSeconds            14669.0
HalfSeconds              7499.0
Name: 22968, dtype: object
East Malvern, Vic
 Age                            55
M/F                             F
City            East Malvern, Vic
State                         NaN
Country                       AUS
Half              0 days 02:04:56
40K               0 days 04:23:12
Pace                      0:10:42
TotalSeconds              15792.0
HalfSeconds                7496.0
Name: 24617, dtype: object
East Northport
 Age                          60
M/F                           F
City             East Northport
State                        NY
Country                     USA
Half            0 days 02:04:34
40K             0 days 04:02:32
Pace                    0:09:44
TotalSeconds            14552.0
HalfSeconds              7474.0
Name: 25699, dtype: object
East Orange
 Age                          28
M/F                           F
City                East Orange
State                        NJ
Country                     USA
Half            0 days 02:39:27
40K             0 days 05:29:27
Pace                    0:13:16
TotalSeconds            19767.0
HalfSeconds              9567.0
Name: 30220, dtype: object
East Palestine
 Age                          39
M/F                           M
City             East Palestine
State                        OH
Country                     USA
Half            0 days 01:29:35
40K             0 days 02:53:59
Pace                    0:07:00
TotalSeconds            10439.0
HalfSeconds              5375.0
Name: 3957, dtype: object
East Point
 Age                          60
M/F                           M
City                 East Point
State                        GA
Country                     USA
Half            0 days 02:37:30
40K             0 days 05:14:13
Pace                    0:12:42
TotalSeconds            18853.0
HalfSeconds              9450.0
Name: 29925, dtype: object
East Providence
 Age                          27
M/F                           M
City            East Providence
State                        RI
Country                     USA
Half            0 days 01:31:37
40K             0 days 03:06:16
Pace                    0:07:33
TotalSeconds            11176.0
HalfSeconds              5497.0
Name: 5203, dtype: object
East Ridge
 Age                          48
M/F                           M
City                 East Ridge
State                        TN
Country                     USA
Half            0 days 01:25:06
40K             0 days 02:44:25
Pace                    0:06:39
TotalSeconds             9865.0
HalfSeconds              5106.0
Name: 1559, dtype: object
East Rochester
 Age                          41
M/F                           M
City             East Rochester
State                        NY
Country                     USA
Half            0 days 01:33:57
40K             0 days 03:22:21
Pace                    0:08:11
TotalSeconds            12141.0
HalfSeconds              5637.0
Name: 7210, dtype: object
East Rutherford
 Age                          51
M/F                           M
City            East Rutherford
State                        NJ
Country                     USA
Half            0 days 01:37:48
40K             0 days 03:15:26
Pace                    0:07:55
TotalSeconds            11726.0
HalfSeconds              5868.0
Name: 10586, dtype: object
East Sandwich
 Age                          50
M/F                           F
City              East Sandwich
State                        MA
Country                     USA
Half            0 days 01:56:41
40K             0 days 03:46:07
Pace                    0:09:09
TotalSeconds            13567.0
HalfSeconds              7001.0
Name: 22396, dtype: object
East Sparta
 Age                          51
M/F                           F
City                East Sparta
State                        OH
Country                     USA
Half            0 days 01:58:44
40K             0 days 03:52:38
Pace                    0:09:23
TotalSeconds            13958.0
HalfSeconds              7124.0
Name: 24590, dtype: object
East Stroudsburg
 Age                           53
M/F                            M
City            East Stroudsburg
State                         PA
Country                      USA
Half             0 days 01:47:10
40K              0 days 03:37:38
Pace                     0:08:45
TotalSeconds             13058.0
HalfSeconds               6430.0
Name: 14068, dtype: object
East Syracuse
 Age                          27
M/F                           M
City              East Syracuse
State                        NY
Country                     USA
Half            0 days 01:14:39
40K             0 days 02:30:29
Pace                    0:06:05
TotalSeconds             9029.0
HalfSeconds              4479.0
Name: 429, dtype: object
East Taunton
 Age                          41
M/F                           F
City               East Taunton
State                        MA
Country                     USA
Half            0 days 01:50:23
40K             0 days 03:39:44
Pace                    0:08:51
TotalSeconds            13184.0
HalfSeconds              6623.0
Name: 28511, dtype: object
East Thetford
 Age                          50
M/F                           F
City              East Thetford
State                        VT
Country                     USA
Half            0 days 01:53:02
40K             0 days 03:37:18
Pace                    0:08:45
TotalSeconds            13038.0
HalfSeconds              6782.0
Name: 21636, dtype: object
East Troy
 Age                          62
M/F                           M
City                  East Troy
State                        WI
Country                     USA
Half            0 days 02:10:01
40K             0 days 04:10:58
Pace                    0:10:04
TotalSeconds            15058.0
HalfSeconds              7801.0
Name: 22590, dtype: object
East Walpole
 Age                          34
M/F                           M
City               East Walpole
State                        MA
Country                     USA
Half            0 days 01:53:33
40K             0 days 03:56:30
Pace                    0:09:37
TotalSeconds            14190.0
HalfSeconds              6813.0
Name: 27572, dtype: object
East Wenatchee
 Age                          61
M/F                           M
City             East Wenatchee
State                        WA
Country                     USA
Half            0 days 01:50:07
40K             0 days 03:35:45
Pace                    0:08:44
TotalSeconds            12945.0
HalfSeconds              6607.0
Name: 18951, dtype: object
East Williston
 Age                          51
M/F                           M
City             East Williston
State                        NY
Country                     USA
Half            0 days 01:49:31
40K             0 days 03:40:56
Pace                    0:08:53
TotalSeconds            13256.0
HalfSeconds              6571.0
Name: 14470, dtype: object
East Windsor
 Age                          47
M/F                           M
City               East Windsor
State                        NJ
Country                     USA
Half            0 days 01:38:19
40K             0 days 03:15:06
Pace                    0:07:53
TotalSeconds            11706.0
HalfSeconds              5899.0

Name: 6764, dtype: object
Eastaboga
 Age                          53
M/F                           F
City                  Eastaboga
State                        AL
Country                     USA
Half            0 days 02:12:52
40K             0 days 04:45:14
Pace                    0:11:31
TotalSeconds            17114.0
HalfSeconds              7972.0
Name: 24936, dtype: object
Eastchester
 Age                          43
M/F                           M
City                Eastchester
State                        NY
Country                     USA
Half            0 days 02:25:21
40K             0 days 05:06:08
Pace                    0:12:20
TotalSeconds            18368.0
HalfSeconds              8721.0
Name: 30952, dtype: object
Easthampton
 Age                          33
M/F                           F
City                Easthampton
State                        MA
Country                     USA
Half            0 days 01:37:12
40K             0 days 03:11:45
Pace                    0:07:48
TotalSeconds            11505.0
HalfSeconds              5832.0
Name: 10868, dtype: object
Easton
 Age                          44
M/F                           M
City                     Easton
State                        PA
Country                     USA
Half            0 days 01:25:18
40K             0 days 02:47:43
Pace                    0:06:47
TotalSeconds            10063.0
HalfSeconds              5118.0
Name: 1079, dtype: object
Eastvale
 Age                          41
M/F                           M
City                   Eastvale
State                        CA
Country                     USA
Half            0 days 01:31:51
40K             0 days 03:26:30
Pace                    0:08:20
TotalSeconds            12390.0
HalfSeconds              5511.0
Name: 3617, dtype: object
Eaton
 Age                          45
M/F                           M
City                      Eaton
State                        OH
Country                     USA
Half            0 days 01:26:12
40K             0 days 02:58:25
Pace                    0:07:14
TotalSeconds            10705.0
HalfSeconds              5172.0
Name: 2211, dtype: object
Eau Claire
 Age                          55
M/F                           M
City                 Eau Claire
State                        WI
Country                     USA
Half            0 days 01:41:11
40K             0 days 03:15:45
Pace                    0:07:53
TotalSeconds            11745.0
HalfSeconds              6071.0
Name: 9514, dtype: object
Ecatepec
 Age                          43
M/F                           M
City                   Ecatepec
State                       NaN
Country                     MEX
Half            0 days 02:00:05
40K             0 days 03:53:22
Pace                    0:09:22
TotalSeconds            14002.0
HalfSeconds              7205.0
Name: 7439, dtype: object
Echallens
 Age                          52
M/F                           F
City                  Echallens
State                       NaN
Country                     SUI
Half            0 days 02:16:50
40K             0 days 04:38:29
Pace                    0:11:13
TotalSeconds            16709.0
HalfSeconds              8210.0
Name: 31592, dtype: object
Echandens
 Age                          51
M/F                           M
City                  Echandens
State                       NaN
Country                     SUI
Half            0 days 01:37:52
40K             0 days 03:19:40
Pace                    0:08:07
TotalSeconds            11980.0
HalfSeconds              5872.0
Name: 6980, dtype: object
Ecublens
 Age                          52
M/F                           M
City                   Ecublens
State                       NaN
Country                     SUI
Half            0 days 01:24:51
40K             0 days 02:53:57
Pace                    0:07:05
TotalSeconds            10437.0
HalfSeconds              5091.0
Name: 2412, dtype: object
Eden
 Age                          22
M/F                           M
City                       Eden
State                        UT
Country                     USA
Half            0 days 01:28:04
40K             0 days 02:52:53
Pace                    0:07:02
TotalSeconds            10373.0
HalfSeconds              5284.0
Name: 3237, dtype: object
Eden Prairie
 Age                          22
M/F                           F
City               Eden Prairie
State                        MN
Country                     USA
Half            0 days 01:32:48
40K             0 days 02:54:19
Pace                    0:07:00
TotalSeconds            10459.0
HalfSeconds              5568.0
Name: 10265, dtype: object
Edgar
 Age                          39
M/F                           M
City                      Edgar
State                        NE
Country                     USA
Half            0 days 01:23:12
40K             0 days 02:45:19
Pace                    0:06:41
TotalSeconds             9919.0
HalfSeconds              4992.0
Name: 859, dtype: object
Edgewater
 Age                          30
M/F                           F
City                  Edgewater
State                        CO
Country                     USA
Half            0 days 01:41:26
40K             0 days 03:27:21
Pace                    0:08:26
TotalSeconds            12441.0
HalfSeconds              6086.0
Name: 16697, dtype: object
Edgewood
 Age                          61
M/F                           M
City                   Edgewood
State                        WA
Country                     USA
Half            0 days 01:53:11
40K             0 days 04:01:30
Pace                    0:09:46
TotalSeconds            14490.0
HalfSeconds              6791.0
Name: 20556, dtype: object
Edina
 Age                          49
M/F                           M
City                      Edina
State                        MN
Country                     USA
Half            0 days 01:33:54
40K             0 days 03:06:31
Pace                    0:07:34
TotalSeconds            11191.0
HalfSeconds              5634.0
Name: 6598, dtype: object
Edinburgh
 Age                          37
M/F                           M
City                  Edinburgh
State                       NaN
Country                     GBR
Half            0 days 01:27:23
40K             0 days 02:53:01
Pace                    0:07:00
TotalSeconds            10381.0
HalfSeconds              5243.0
Name: 3690, dtype: object
Edmond
 Age                          40
M/F                           M
City                     Edmond
State                        OK
Country                     USA
Half            0 days 01:25:36
40K             0 days 02:46:40
Pace                    0:06:43
TotalSeconds            10000.0
HalfSeconds              5136.0
Name: 268, dtype: object
Edmonds
 Age                          32
M/F                           M
City                    Edmonds
State                        WA
Country                     USA
Half            0 days 01:31:12
40K             0 days 02:54:58
Pace                    0:07:03
TotalSeconds            10498.0
HalfSeconds              5472.0
Name: 4163, dtype: object
Edmonton
 Age                          31
M/F                           M
City                   Edmonton
State                        AB
Country                     CAN
Half            0 days 01:23:30
40K             0 days 02:42:47
Pace                    0:06:34
TotalSeconds             9767.0
HalfSeconds              5010.0
Name: 1331, dtype: object
Edmundston
 Age                          56
M/F                           F
City                 Edmundston
State                        NB
Country                     CAN
Half            0 days 01:52:31
40K             0 days 03:46:28
Pace                    0:09:09
TotalSeconds            13588.0
HalfSeconds              6751.0
Name: 19354, dtype: object
Edwards
 Age                          32
M/F                           M
City                    Edwards
State                        CA
Country                     USA
Half            0 days 01:17:55
40K             0 days 02:34:12
Pace                    0:06:14
TotalSeconds             9252.0
HalfSeconds              4675.0
Name: 361, dtype: object
Edwardsville
 Age                          28
M/F                           F
City               Edwardsville
State                        IL
Country                     USA
Half            0 days 01:28:11
40K             0 days 02:46:36
Pace                    0:06:43
TotalSeconds             9996.0
HalfSeconds              5291.0
Name: 2685, dtype: object
Effort
 Age                          45
M/F                           M
City                     Effort
State                        PA
Country                     USA
Half            0 days 01:49:47
40K             0 days 03:53:26
Pace                    0:09:28
TotalSeconds            14006.0
HalfSeconds              6587.0
Name: 12465, dtype: object
Ega
 Age                          38
M/F                           M
City                        Ega
State                       NaN
Country                     DEN
Half            0 days 01:45:59
40K             0 days 03:37:20
Pace                    0:08:49
TotalSeconds            13040.0
HalfSeconds              6359.0
Name: 30477, dtype: object
Egg Bei Zuerich
 Age                          41
M/F                           M
City            Egg Bei Zuerich
State                       NaN
Country                     SUI
Half            0 days 01:37:29
40K             0 days 03:22:40
Pace                    0:08:11
TotalSeconds            12160.0
HalfSeconds              5849.0
Name: 5654, dtype: object
Egg Harbor Township
 Age                              53
M/F                               M
City            Egg Harbor Township
State                            NJ
Country                         USA
Half                0 days 01:39:41
40K                 0 days 03:31:40
Pace                        0:08:44
TotalSeconds                12700.0
HalfSeconds                  5981.0
Name: 9899, dtype: object
Egg Harbor Twp
 Age                          42
M/F                           F
City             Egg Harbor Twp
State                        NJ
Country                     USA
Half            0 days 02:22:36
40K             0 days 04:37:25
Pace                    0:11:07
TotalSeconds            16645.0
HalfSeconds              8556.0
Name: 32050, dtype: object
Eidsvoll
 Age                          41
M/F                           M
City                   Eidsvoll
State                       NaN
Country                     NOR
Half            0 days 01:37:54
40K             0 days 03:19:44
Pace                    0:08:06
TotalSeconds            11984.0
HalfSeconds              5874.0
Name: 7666, dtype: object
Eighty Four
 Age                          35
M/F                           F
City                Eighty Four
State                        PA
Country                     USA
Half            0 days 01:40:35
40K             0 days 03:16:50
Pace                    0:07:57
TotalSeconds            11810.0
HalfSeconds              6035.0
Name: 17437, dtype: object
Eisenstadt
 Age                          61
M/F                           M
City                 Eisenstadt
State                       NaN
Country                     AUT
Half            0 days 02:17:15
40K             0 days 04:29:34
Pace                    0:10:50
TotalSeconds            16174.0
HalfSeconds              8235.0
Name: 31127, dtype: object
El Cajon
 Age                          36
M/F                           M
City                   El Cajon
State                        CA
Country                     USA
Half            0 days 01:32:49
40K             0 days 03:05:15
Pace                    0:07:31
TotalSeconds            11115.0
HalfSeconds              5569.0
Name: 6294, dtype: object
El Centro
 Age                          41
M/F                           M
City                  El Centro
State                        CA
Country                     USA
Half            0 days 01:30:31
40K             0 days 03:06:21
Pace                    0:07:34
TotalSeconds            11181.0
HalfSeconds              5431.0
Name: 6612, dtype: object
El Cerrito
 Age                          39
M/F                           M
City                 El Cerrito
State                        CA
Country                     USA
Half            0 days 01:37:39
40K             0 days 03:24:37
Pace                    0:08:22
TotalSeconds            12277.0
HalfSeconds              5859.0
Name: 30443, dtype: object
El Dorado
 Age                          44
M/F                           M
City                  El Dorado
State                        KS
Country                     USA
Half            0 days 01:29:42
40K             0 days 02:55:19
Pace                    0:07:04
TotalSeconds            10519.0
HalfSeconds              5382.0
Name: 5084, dtype: object
El Dorado Hills
 Age                          47
M/F                           M
City            El Dorado Hills
State                        CA
Country                     USA
Half            0 days 01:36:34
40K             0 days 03:13:11
Pace                    0:07:49
TotalSeconds            11591.0
HalfSeconds              5794.0
Name: 11021, dtype: object
El Paso
 Age                          53
M/F                           M
City                    El Paso
State                        TX
Country                     USA
Half            0 days 01:34:21
40K             0 days 03:09:02
Pace                    0:07:39
TotalSeconds            11342.0
HalfSeconds              5661.0
Name: 5363, dtype: object
El Segundo
 Age                          33
M/F                           M
City                 El Segundo
State                        CA
Country                     USA
Half            0 days 01:33:23
40K             0 days 03:12:01
Pace                    0:07:47
TotalSeconds            11521.0
HalfSeconds              5603.0
Name: 4874, dtype: object
Elda (Alicante)
 Age                          41
M/F                           M
City            Elda (Alicante)
State                       NaN
Country                     ESP
Half            0 days 01:34:47
40K             0 days 03:14:50
Pace                    0:07:55
TotalSeconds            11690.0
HalfSeconds              5687.0
Name: 7309, dtype: object
Eldoret
 Age                          23
M/F                           M
City                    Eldoret
State                       NaN
Country                     KEN
Half            0 days 01:06:46
40K             0 days 02:08:11
Pace                    0:05:11
TotalSeconds             7691.0
HalfSeconds              4006.0
Name: 14, dtype: object
Eldridge
 Age                          36
M/F                           F
City                   Eldridge
State                        IA
Country                     USA
Half            0 days 01:56:39
40K             0 days 03:54:49
Pace                    0:09:26
TotalSeconds            14089.0
HalfSeconds              6999.0
Name: 18033, dtype: object
Eleva
 Age                          46
M/F                           M
City                      Eleva
State                        WI
Country                     USA
Half            0 days 01:40:30
40K             0 days 03:20:54
Pace                    0:08:04
TotalSeconds            12054.0
HalfSeconds              6030.0
Name: 10518, dtype: object
Elgin
 Age                          39
M/F                           M
City                      Elgin
State                        IL
Country                     USA
Half            0 days 01:30:36
40K             0 days 02:56:21
Pace                    0:07:07
TotalSeconds            10581.0
HalfSeconds              5436.0
Name: 5322, dtype: object
Eliot
 Age                          49
M/F                           M
City                      Eliot
State                        ME
Country                     USA
Half            0 days 01:38:37
40K             0 days 03:28:40
Pace                    0:08:26
TotalSeconds            12520.0
HalfSeconds              5917.0
Name: 9193, dtype: object
Elizabeth Township
 Age                             29
M/F                              F
City            Elizabeth Township
State                           PA
Country                        USA
Half               0 days 01:36:49
40K                0 days 03:05:12
Pace                       0:07:30
TotalSeconds               11112.0
HalfSeconds                 5809.0
Name: 12806, dtype: object
Elizabethton
 Age                          52
M/F                           M
City               Elizabethton
State                        TN
Country                     USA
Half            0 days 01:42:52
40K             0 days 03:17:48
Pace                    0:07:58
TotalSeconds            11868.0
HalfSeconds              6172.0
Name: 13181, dtype: object

Elizabethtown
 Age                          45
M/F                           M
City              Elizabethtown
State                        ON
Country                     CAN
Half            0 days 01:30:12
40K             0 days 02:56:17
Pace                    0:07:08
TotalSeconds            10577.0
HalfSeconds              5412.0
Name: 7071, dtype: object
Elk Grove
 Age                          47
M/F                           M
City                  Elk Grove
State                        CA
Country                     USA
Half            0 days 01:41:17
40K             0 days 03:13:43
Pace                    0:07:47
TotalSeconds            11623.0
HalfSeconds              6077.0
Name: 12505, dtype: object
Elk Grove Village
 Age                            41
M/F                             F
City            Elk Grove Village
State                          IL
Country                       USA
Half              0 days 01:46:42
40K               0 days 03:23:31
Pace                      0:08:12
TotalSeconds              12211.0
HalfSeconds                6402.0
Name: 13896, dtype: object
Elk Mound
 Age                          58
M/F                           M
City                  Elk Mound
State                        WI
Country                     USA
Half            0 days 01:49:34
40K             0 days 03:33:26
Pace                    0:08:38
TotalSeconds            12806.0
HalfSeconds              6574.0
Name: 19702, dtype: object
Elk Rapids
 Age                          67
M/F                           F
City                 Elk Rapids
State                        MI
Country                     USA
Half            0 days 02:29:13
40K             0 days 05:15:34
Pace                    0:12:46
TotalSeconds            18934.0
HalfSeconds              8953.0
Name: 25763, dtype: object
Elk River
 Age                          22
M/F                           F
City                  Elk River
State                        MN
Country                     USA
Half            0 days 01:49:32
40K             0 days 03:49:52
Pace                    0:09:21
TotalSeconds            13792.0
HalfSeconds              6572.0
Name: 15451, dtype: object
Elkhart
 Age                          30
M/F                           F
City                    Elkhart
State                        IN
Country                     USA
Half            0 days 01:43:55
40K             0 days 03:28:03
Pace                    0:08:24
TotalSeconds            12483.0
HalfSeconds              6235.0
Name: 7623, dtype: object
Elkhorn
 Age                          40
M/F                           F
City                    Elkhorn
State                        NE
Country                     USA
Half            0 days 01:39:36
40K             0 days 03:14:41
Pace                    0:07:51
TotalSeconds            11681.0
HalfSeconds              5976.0
Name: 10857, dtype: object
Elkin
 Age                          46
M/F                           M
City                      Elkin
State                        NC
Country                     USA
Half            0 days 01:40:10
40K             0 days 03:25:02
Pace                    0:08:19
TotalSeconds            12302.0
HalfSeconds              6010.0
Name: 12610, dtype: object
Elkins Park
 Age                          47
M/F                           M
City                Elkins Park
State                        PA
Country                     USA
Half            0 days 01:41:56
40K             0 days 03:29:29
Pace                    0:08:27
TotalSeconds            12569.0
HalfSeconds              6116.0
Name: 12209, dtype: object
Elkmont
 Age                          52
M/F                           F
City                    Elkmont
State                        AL
Country                     USA
Half            0 days 01:50:59
40K             0 days 03:40:41
Pace                    0:08:56
TotalSeconds            13241.0
HalfSeconds              6659.0
Name: 21183, dtype: object
Elkridge
 Age                          36
M/F                           F
City                   Elkridge
State                        MD
Country                     USA
Half            0 days 01:45:02
40K             0 days 03:24:09
Pace                    0:08:14
TotalSeconds            12249.0
HalfSeconds              6302.0
Name: 20206, dtype: object
Elkton
 Age                          35
M/F                           F
City                     Elkton
State                        FL
Country                     USA
Half            0 days 01:44:53
40K             0 days 03:30:22
Pace                    0:08:31
TotalSeconds            12622.0
HalfSeconds              6293.0
Name: 14691, dtype: object
Elkview
 Age                          44
M/F                           F
City                    Elkview
State                        WV
Country                     USA
Half            0 days 01:47:11
40K             0 days 03:24:57
Pace                    0:08:16
TotalSeconds            12297.0
HalfSeconds              6431.0
Name: 19436, dtype: object
Ellensburg
 Age                          42
M/F                           M
City                 Ellensburg
State                        WA
Country                     USA
Half            0 days 01:29:40
40K             0 days 02:52:19
Pace                    0:06:59
TotalSeconds            10339.0
HalfSeconds              5380.0
Name: 4092, dtype: object
Ellettsville
 Age                          51
M/F                           M
City               Ellettsville
State                        IN
Country                     USA
Half            0 days 01:44:21
40K             0 days 03:35:23
Pace                    0:08:43
TotalSeconds            12923.0
HalfSeconds              6261.0
Name: 11003, dtype: object
Ellicott City
 Age                          53
M/F                           M
City              Ellicott City
State                        MD
Country                     USA
Half            0 days 01:29:24
40K             0 days 02:54:18
Pace                    0:07:02
TotalSeconds            10458.0
HalfSeconds              5364.0
Name: 4181, dtype: object
Ellington
 Age                          35
M/F                           M
City                  Ellington
State                        CT
Country                     USA
Half            0 days 01:29:36
40K             0 days 02:49:20
Pace                    0:06:50
TotalSeconds            10160.0
HalfSeconds              5376.0
Name: 4195, dtype: object
Ellisville
 Age                          38
M/F                           F
City                 Ellisville
State                        MO
Country                     USA
Half            0 days 01:44:35
40K             0 days 03:29:53
Pace                    0:08:29
TotalSeconds            12593.0
HalfSeconds              6275.0
Name: 18446, dtype: object
Ellsworth
 Age                          28
M/F                           M
City                  Ellsworth
State                        ME
Country                     USA
Half            0 days 01:20:54
40K             0 days 02:49:47
Pace                    0:06:50
TotalSeconds            10187.0
HalfSeconds              4854.0
Name: 362, dtype: object
Elm Grove
 Age                          47
M/F                           F
City                  Elm Grove
State                        WI
Country                     USA
Half            0 days 01:51:55
40K             0 days 03:40:38
Pace                    0:08:58
TotalSeconds            13238.0
HalfSeconds              6715.0
Name: 21175, dtype: object
Elmhurst
 Age                          38
M/F                           F
City                   Elmhurst
State                        IL
Country                     USA
Half            0 days 01:45:47
40K             0 days 03:26:56
Pace                    0:08:22
TotalSeconds            12416.0
HalfSeconds              6347.0
Name: 19126, dtype: object
Elmira
 Age                          42
M/F                           F
City                     Elmira
State                        ON
Country                     CAN
Half            0 days 01:49:33
40K             0 days 03:28:38
Pace                    0:08:24
TotalSeconds            12518.0
HalfSeconds              6573.0
Name: 20487, dtype: object
Elmora
 Age                          60
M/F                           M
City                     Elmora
State                        PA
Country                     USA
Half            0 days 02:42:47
40K             0 days 05:40:15
Pace                    0:13:44
TotalSeconds            20415.0
HalfSeconds              9767.0
Name: 29493, dtype: object
Elon
 Age                          38
M/F                           M
City                       Elon
State                        NC
Country                     USA
Half            0 days 01:33:14
40K             0 days 02:57:12
Pace                    0:07:07
TotalSeconds            10632.0
HalfSeconds              5594.0
Name: 6960, dtype: object
Elsmere
 Age                          37
M/F                           F
City                    Elsmere
State                        KY
Country                     USA
Half            0 days 01:54:45
40K             0 days 04:16:15
Pace                    0:10:20
TotalSeconds            15375.0
HalfSeconds              6885.0
Name: 19112, dtype: object
Elverson
 Age                          49
M/F                           M
City                   Elverson
State                        PA
Country                     USA
Half            0 days 01:38:48
40K             0 days 03:09:35
Pace                    0:07:39
TotalSeconds            11375.0
HalfSeconds              5928.0
Name: 11403, dtype: object
Emeryville
 Age                          33
M/F                           F
City                 Emeryville
State                        CA
Country                     USA
Half            0 days 01:33:10
40K             0 days 03:05:56
Pace                    0:07:34
TotalSeconds            11156.0
HalfSeconds              5590.0
Name: 9768, dtype: object
Emmaus
 Age                          28
M/F                           M
City                     Emmaus
State                        PA
Country                     USA
Half            0 days 01:21:04
40K             0 days 02:40:55
Pace                    0:06:31
TotalSeconds             9655.0
HalfSeconds              4864.0
Name: 4048, dtype: object
Emmett
 Age                          34
M/F                           F
City                     Emmett
State                        ID
Country                     USA
Half            0 days 01:42:40
40K             0 days 03:22:42
Pace                    0:08:11
TotalSeconds            12162.0
HalfSeconds              6160.0
Name: 12010, dtype: object
Emporia
 Age                          26
M/F                           M
City                    Emporia
State                        KS
Country                     USA
Half            0 days 01:34:05
40K             0 days 03:25:40
Pace                    0:08:21
TotalSeconds            12340.0
HalfSeconds              5645.0
Name: 2626, dtype: object

Encinitas
 Age                          40
M/F                           F
City                  Encinitas
State                        CA
Country                     USA
Half            0 days 01:21:45
40K             0 days 02:39:11
Pace                    0:06:27
TotalSeconds             9551.0
HalfSeconds              4905.0
Name: F103, dtype: object
Encino
 Age                          46
M/F                           F
City                     Encino
State                        CA
Country                     USA
Half            0 days 01:50:04
40K             0 days 03:55:50
Pace                    0:09:36
TotalSeconds            14150.0
HalfSeconds              6604.0
Name: 20229, dtype: object
Endicott
 Age                          46
M/F                           M
City                   Endicott
State                        NY
Country                     USA
Half            0 days 01:28:29
40K             0 days 02:57:09
Pace                    0:07:10
TotalSeconds            10629.0
HalfSeconds              5309.0
Name: 1569, dtype: object
Endwell
 Age                          59
M/F                           M
City                    Endwell
State                        NY
Country                     USA
Half            0 days 01:57:38
40K             0 days 04:19:10
Pace                    0:10:28
TotalSeconds            15550.0
HalfSeconds              7058.0
Name: 16726, dtype: object
Enfield
 Age                          30
M/F                           F
City                    Enfield
State                        CT
Country                     USA
Half            0 days 01:43:28
40K             0 days 03:17:32
Pace                    0:07:56
TotalSeconds            11852.0
HalfSeconds              6208.0
Name: 14904, dtype: object
Englewood
 Age                          37
M/F                           M
City                  Englewood
State                        NJ
Country                     USA
Half            0 days 01:23:02
40K             0 days 02:43:02
Pace                    0:06:39
TotalSeconds             9782.0
HalfSeconds              4982.0
Name: 1657, dtype: object
Enterprise
 Age                          51
M/F                           M
City                 Enterprise
State                        AL
Country                     USA
Half            0 days 01:39:39
40K             0 days 03:21:04
Pace                    0:08:10
TotalSeconds            12064.0
HalfSeconds              5979.0
Name: 13552, dtype: object
Epalinges
 Age                          61
M/F                           M
City                  Epalinges
State                       NaN
Country                     SUI
Half            0 days 01:47:10
40K             0 days 03:43:35
Pace                    0:09:05
TotalSeconds            13415.0
HalfSeconds              6430.0
Name: 20547, dtype: object
Ephraim
 Age                          38
M/F                           F
City                    Ephraim
State                        UT
Country                     USA
Half            0 days 01:49:06
40K             0 days 03:33:19
Pace                    0:08:36
TotalSeconds            12799.0
HalfSeconds              6546.0
Name: 19598, dtype: object
Epping
 Age                          28
M/F                           F
City                     Epping
State                        NH
Country                     USA
Half            0 days 02:18:34
40K             0 days 04:40:17
Pace                    0:11:14
TotalSeconds            16817.0
HalfSeconds              8314.0
Name: 26279, dtype: object
Epworth
 Age                          34
M/F                           F
City                    Epworth
State                        IA
Country                     USA
Half            0 days 01:56:49
40K             0 days 03:42:30
Pace                    0:08:56
TotalSeconds            13350.0
HalfSeconds              7009.0
Name: 14500, dtype: object
Erfurt
 Age                          46
M/F                           M
City                     Erfurt
State                       NaN
Country                     GER
Half            0 days 01:35:23
40K             0 days 03:12:21
Pace                    0:07:44
TotalSeconds            11541.0
HalfSeconds              5723.0
Name: 8515, dtype: object
Erie
 Age                          37
M/F                           M
City                       Erie
State                        PA
Country                     USA
Half            0 days 01:29:05
40K             0 days 02:53:22
Pace                    0:07:01
TotalSeconds            10402.0
HalfSeconds              5345.0
Name: 1475, dtype: object
Erieville
 Age                          26
M/F                           F
City                  Erieville
State                        NY
Country                     USA
Half            0 days 01:46:39
40K             0 days 03:31:10
Pace                    0:08:31
TotalSeconds            12670.0
HalfSeconds              6399.0
Name: 13210, dtype: object
Erin
 Age                          49
M/F                           F
City                       Erin
State                        ON
Country                     CAN
Half            0 days 01:51:20
40K             0 days 03:46:37
Pace                    0:09:12
TotalSeconds            13597.0
HalfSeconds              6680.0
Name: 23016, dtype: object
Erlangen
 Age                          51
M/F                           F
City                   Erlangen
State                       NaN
Country                     GER
Half            0 days 01:59:03
40K             0 days 03:55:19
Pace                    0:09:31
TotalSeconds            14119.0
HalfSeconds              7143.0
Name: 25012, dtype: object
Erlanger
 Age                          39
M/F                           F
City                   Erlanger
State                        KY
Country                     USA
Half            0 days 01:45:26
40K             0 days 03:33:49
Pace                    0:08:38
TotalSeconds            12829.0
HalfSeconds              6326.0
Name: 14232, dtype: object
Escalon
 Age                          50
M/F                           M
City                    Escalon
State                        CA
Country                     USA
Half            0 days 01:41:34
40K             0 days 03:24:18
Pace                    0:08:16
TotalSeconds            12258.0
HalfSeconds              6094.0
Name: 12249, dtype: object
Escanaba
 Age                          40
M/F                           F
City                   Escanaba
State                        MI
Country                     USA
Half            0 days 01:59:10
40K             0 days 03:49:56
Pace                    0:09:17
TotalSeconds            13796.0
HalfSeconds              7150.0
Name: 21466, dtype: object
Escondido
 Age                          23
M/F                           F
City                  Escondido
State                        CA
Country                     USA
Half            0 days 01:40:11
40K             0 days 03:17:37
Pace                    0:07:59
TotalSeconds            11857.0
HalfSeconds              6011.0
Name: 8467, dtype: object
Esko
 Age                          60
M/F                           M
City                       Esko
State                        MN
Country                     USA
Half            0 days 01:25:23
40K             0 days 02:44:22
Pace                    0:06:38
TotalSeconds             9862.0
HalfSeconds              5123.0
Name: 1202, dtype: object
Espergaerde
 Age                          59
M/F                           M
City                Espergaerde
State                       NaN
Country                     DEN
Half            0 days 01:55:41
40K             0 days 04:13:51
Pace                    0:10:19
TotalSeconds            15231.0
HalfSeconds              6941.0
Name: 20063, dtype: object
Espergærde
 Age                          60
M/F                           M
City                 Espergærde
State                       NaN
Country                     DEN
Half            0 days 01:56:32
40K             0 days 04:06:40
Pace                    0:10:04
TotalSeconds            14800.0
HalfSeconds              6992.0
Name: 22285, dtype: object
Esplugues De Llobregat (bcn)
 Age                                       47
M/F                                        M
City            Esplugues De Llobregat (bcn)
State                                    NaN
Country                                  ESP
Half                         0 days 01:39:30
40K                          0 days 03:41:19
Pace                                 0:09:00
TotalSeconds                         13279.0
HalfSeconds                           5970.0
Name: 9782, dtype: object
Espoo
 Age                          30
M/F                           M
City                      Espoo
State                       NaN
Country                     FIN
Half            0 days 01:16:16
40K             0 days 02:32:08
Pace                    0:06:09
TotalSeconds             9128.0
HalfSeconds              4576.0
Name: 921, dtype: object
Esquerchin
 Age                          41
M/F                           M
City                 Esquerchin
State                       NaN
Country                     FRA
Half            0 days 01:30:52
40K             0 days 03:11:37
Pace                    0:07:48
TotalSeconds            11497.0
HalfSeconds              5452.0
Name: 8691, dtype: object
Essen
 Age                          44
M/F                           M
City                      Essen
State                       NaN
Country                     GER
Half            0 days 01:56:48
40K             0 days 03:45:45
Pace                    0:09:06
TotalSeconds            13545.0
HalfSeconds              7008.0
Name: 31131, dtype: object
Essendon
 Age                          54
M/F                           M
City                   Essendon
State                       NaN
Country                     AUS
Half            0 days 01:41:54
40K             0 days 03:45:40
Pace                    0:09:04
TotalSeconds            13540.0
HalfSeconds              6114.0
Name: 12233, dtype: object
Essex
 Age                          50
M/F                           M
City                      Essex
State                       NaN
Country                     GBR
Half            0 days 01:29:02
40K             0 days 02:55:34
Pace                    0:07:09
TotalSeconds            10534.0
HalfSeconds              5342.0
Name: 3633, dtype: object
Essex Drive
 Age                          48
M/F                           M
City                Essex Drive
State                       NaN
Country                     GBR
Half            0 days 01:42:05
40K             0 days 03:23:51
Pace                    0:08:16
TotalSeconds            12231.0
HalfSeconds              6125.0
Name: 10242, dtype: object
Essex Junction
 Age                          68
M/F                           M
City             Essex Junction
State                        VT
Country                     USA
Half            0 days 01:54:34
40K             0 days 03:42:36
Pace                    0:09:00
TotalSeconds            13356.0
HalfSeconds              6874.0
Name: 24501, dtype: object
Essex Uk
 Age                          36
M/F                           M
City                   Essex Uk
State                       NaN
Country                     GBR
Half            0 days 01:40:05
40K             0 days 03:30:42
Pace                    0:08:33
TotalSeconds            12642.0
HalfSeconds              6005.0
Name: 6553, dtype: object
Essexville
 Age                          48
M/F                           M
City                 Essexville
State                        MI
Country                     USA
Half            0 days 01:42:01
40K             0 days 03:21:03
Pace                    0:08:08
TotalSeconds            12063.0
HalfSeconds              6121.0
Name: 11172, dtype: object
Estado De Mexico
 Age                           55
M/F                            F
City            Estado De Mexico
State                        NaN
Country                      MEX
Half             0 days 01:50:44
40K              0 days 03:39:46
Pace                     0:08:53
TotalSeconds             13186.0
HalfSeconds               6644.0
Name: 21196, dtype: object
Estado De Mexico, Mexico
 Age                                   33
M/F                                    F
City            Estado De Mexico, Mexico
State                                NaN
Country                              MEX
Half                     0 days 01:33:31
40K                      0 days 03:00:45
Pace                             0:07:17
TotalSeconds                     10845.0
HalfSeconds                       5611.0
Name: 9006, dtype: object
Estero
 Age                          73
M/F                           M
City                     Estero
State                        FL
Country                     USA
Half            0 days 02:45:09
40K             0 days 05:57:48
Pace                    0:14:34
TotalSeconds            21468.0
HalfSeconds              9909.0
Name: 15559, dtype: object
Estes Park
 Age                          45
M/F                           F
City                 Estes Park
State                        CO
Country                     USA
Half            0 days 01:46:57
40K             0 days 03:28:14
Pace                    0:08:25
TotalSeconds            12494.0
HalfSeconds              6417.0
Name: 20704, dtype: object
Etna
 Age                          38
M/F                           M
City                       Etna
State                        NH
Country                     USA
Half            0 days 01:43:44
40K             0 days 03:28:53
Pace                    0:08:25
TotalSeconds            12533.0
HalfSeconds              6224.0
Name: 4243, dtype: object
Etobicoke
 Age                          33
M/F                           M
City                  Etobicoke
State                        ON
Country                     CAN
Half            0 days 01:26:23
40K             0 days 02:54:44
Pace                    0:07:04
TotalSeconds            10484.0
HalfSeconds              5183.0
Name: 2804, dtype: object
Etten-Leur
 Age                          58
M/F                           M
City                 Etten-Leur
State                       NaN
Country                     NED
Half            0 days 02:02:25
40K             0 days 04:02:56
Pace                    0:09:49
TotalSeconds            14576.0
HalfSeconds              7345.0
Name: 31275, dtype: object
Etters
 Age                          68
M/F                           M
City                     Etters
State                        PA
Country                     USA
Half            0 days 01:40:02
40K             0 days 03:12:56
Pace                    0:07:47
TotalSeconds            11576.0
HalfSeconds              6002.0
Name: 13013, dtype: object
Eugene
 Age                          70
M/F                           M
City                     Eugene
State                        OR
Country                     USA
Half            0 days 02:14:34
40K             0 days 00:00:00
Pace                    0:10:34
TotalSeconds                0.0
HalfSeconds              8074.0
Name: 25368, dtype: object
Euless
 Age                          40
M/F                           M
City                     Euless
State                        TX
Country                     USA
Half            0 days 01:26:46
40K             0 days 02:57:55
Pace                    0:07:14
TotalSeconds            10675.0
HalfSeconds              5206.0
Name: 4520, dtype: object
Eureka
 Age                          42
M/F                           F
City                     Eureka
State                        MO
Country                     USA
Half            0 days 01:48:15
40K             0 days 03:35:44
Pace                    0:08:43
TotalSeconds            12944.0
HalfSeconds              6495.0
Name: 18781, dtype: object
Eustis
 Age                          37
M/F                           M
City                     Eustis
State                        FL
Country                     USA
Half            0 days 01:39:31
40K             0 days 03:24:25
Pace                    0:08:21
TotalSeconds            12265.0
HalfSeconds              5971.0
Name: 2787, dtype: object
Evans
 Age                          47
M/F                           M
City                      Evans
State                        GA
Country                     USA
Half            0 days 01:35:09
40K             0 days 03:03:54
Pace                    0:07:26
TotalSeconds            11034.0
HalfSeconds              5709.0
Name: 10692, dtype: object
Evans City
 Age                          45
M/F                           M
City                 Evans City
State                        PA
Country                     USA
Half            0 days 01:38:18
40K             0 days 03:20:47
Pace                    0:08:08
TotalSeconds            12047.0
HalfSeconds              5898.0
Name: 10957, dtype: object
Evanston
 Age                          26
M/F                           M
City                   Evanston
State                        IL
Country                     USA
Half            0 days 01:18:29
40K             0 days 02:29:11
Pace                    0:06:03
TotalSeconds             8951.0
HalfSeconds              4709.0
Name: 278, dtype: object
Evansville

 Age                          33
M/F                           M
City                 Evansville
State                        IN
Country                     USA
Half            0 days 01:17:58
40K             0 days 02:34:57
Pace                    0:06:16
TotalSeconds             9297.0
HalfSeconds              4678.0
Name: 433, dtype: object
Evart
 Age                          31
M/F                           M
City                      Evart
State                        MI
Country                     USA
Half            0 days 01:36:20
40K             0 days 03:32:04
Pace                    0:08:29
TotalSeconds            12724.0
HalfSeconds              5780.0
Name: 3057, dtype: object
Evendale
 Age                          53
M/F                           F
City                   Evendale
State                        OH
Country                     USA
Half            0 days 01:51:39
40K             0 days 03:40:02
Pace                    0:08:51
TotalSeconds            13202.0
HalfSeconds              6699.0
Name: 21157, dtype: object
Everett
 Age                          25
M/F                           M
City                    Everett
State                        MA
Country                     USA
Half            0 days 01:24:09
40K             0 days 02:57:15
Pace                    0:07:11
TotalSeconds            10635.0
HalfSeconds              5049.0
Name: 3818, dtype: object
Evergreen
 Age                          38
M/F                           F
City                  Evergreen
State                        CO
Country                     USA
Half            0 days 01:33:51
40K             0 days 03:03:34
Pace                    0:07:25
TotalSeconds            11014.0
HalfSeconds              5631.0
Name: 9455, dtype: object
Evergreen Park
 Age                          29
M/F                           M
City             Evergreen Park
State                        IL
Country                     USA
Half            0 days 01:24:15
40K             0 days 02:53:29
Pace                    0:07:01
TotalSeconds            10409.0
HalfSeconds              5055.0
Name: 1746, dtype: object
Eversley Cross
 Age                          58
M/F                           F
City             Eversley Cross
State                       NaN
Country                     GBR
Half            0 days 02:03:49
40K             0 days 04:02:55
Pace                    0:09:46
TotalSeconds            14575.0
HalfSeconds              7429.0
Name: 25254, dtype: object
Everton Park
 Age                          49
M/F                           M
City               Everton Park
State                       NaN
Country                     AUS
Half            0 days 01:34:45
40K             0 days 03:02:57
Pace                    0:07:21
TotalSeconds            10977.0
HalfSeconds              5685.0
Name: 7201, dtype: object
Excelsior
 Age                          57
M/F                           M
City                  Excelsior
State                        MN
Country                     USA
Half            0 days 01:36:14
40K             0 days 03:19:50
Pace                    0:08:07
TotalSeconds            11990.0
HalfSeconds              5774.0
Name: 8290, dtype: object
Exeter
 Age                          46
M/F                           M
City                     Exeter
State                        NH
Country                     USA
Half            0 days 01:31:47
40K             0 days 03:19:08
Pace                    0:08:06
TotalSeconds            11948.0
HalfSeconds              5507.0
Name: 6831, dtype: object
Export
 Age                          23
M/F                           F
City                     Export
State                        PA
Country                     USA
Half            0 days 01:38:41
40K             0 days 03:10:22
Pace                    0:07:41
TotalSeconds            11422.0
HalfSeconds              5921.0
Name: 11247, dtype: object
Exton
 Age                          55
M/F                           M
City                      Exton
State                        PA
Country                     USA
Half            0 days 01:41:18
40K             0 days 03:22:14
Pace                    0:08:11
TotalSeconds            12134.0
HalfSeconds              6078.0
Name: 11397, dtype: object
FRENCH POLYNESIA
 Age                           42
M/F                            F
City            FRENCH POLYNESIA
State                        NaN
Country                      FRA
Half             0 days 02:00:07
40K              0 days 03:52:06
Pace                     0:09:25
TotalSeconds             13926.0
HalfSeconds               7207.0
Name: 29113, dtype: object
Fabius
 Age                          39
M/F                           M
City                     Fabius
State                        NY
Country                     USA
Half            0 days 01:34:10
40K             0 days 03:10:18
Pace                    0:07:43
TotalSeconds            11418.0
HalfSeconds              5650.0
Name: 6005, dtype: object
Fair Grove
 Age                          53
M/F                           F
City                 Fair Grove
State                        MO
Country                     USA
Half            0 days 01:45:29
40K             0 days 03:36:17
Pace                    0:08:44
TotalSeconds            12977.0
HalfSeconds              6329.0
Name: 22036, dtype: object
Fair Haven
 Age                          45
M/F                           F
City                 Fair Haven
State                        NJ
Country                     USA
Half            0 days 01:50:20
40K             0 days 03:29:44
Pace                    0:08:27
TotalSeconds            12584.0
HalfSeconds              6620.0
Name: 19616, dtype: object
Fair Lawn
 Age                          51
M/F                           M
City                  Fair Lawn
State                        NJ
Country                     USA
Half            0 days 01:33:58
40K             0 days 03:05:12
Pace                    0:07:29
TotalSeconds            11112.0
HalfSeconds              5638.0
Name: 6681, dtype: object
Fair Oaks
 Age                          51
M/F                           M
City                  Fair Oaks
State                        CA
Country                     USA
Half            0 days 01:33:11
40K             0 days 03:00:27
Pace                    0:07:17
TotalSeconds            10827.0
HalfSeconds              5591.0
Name: 3987, dtype: object
Fair Oaks Ranch
 Age                          50
M/F                           F
City            Fair Oaks Ranch
State                        TX
Country                     USA
Half            0 days 01:48:42
40K             0 days 03:35:06
Pace                    0:08:41
TotalSeconds            12906.0
HalfSeconds              6522.0
Name: 21562, dtype: object
Fairbanks
 Age                          59
M/F                           M
City                  Fairbanks
State                        AK
Country                     USA
Half            0 days 01:41:51
40K             0 days 03:19:21
Pace                    0:08:01
TotalSeconds            11961.0
HalfSeconds              6111.0
Name: 11584, dtype: object
Fairborn
 Age                          41
M/F                           M
City                   Fairborn
State                        OH
Country                     USA
Half            0 days 01:29:15
40K             0 days 02:50:18
Pace                    0:06:52
TotalSeconds            10218.0
HalfSeconds              5355.0
Name: 5915, dtype: object
Fairfax
 Age                          33
M/F                           M
City                    Fairfax
State                        VA
Country                     USA
Half            0 days 01:28:26
40K             0 days 02:51:59
Pace                    0:06:57
TotalSeconds            10319.0
HalfSeconds              5306.0
Name: 4547, dtype: object
Fairfax Station
 Age                          24
M/F                           M
City            Fairfax Station
State                        VA
Country                     USA
Half            0 days 01:29:33
40K             0 days 03:16:45
Pace                    0:08:03
TotalSeconds            11805.0
HalfSeconds              5373.0
Name: 4645, dtype: object
Fairfield
 Age                          43
M/F                           M
City                  Fairfield
State                       NaN
Country                     AUS
Half            0 days 01:20:09
40K             0 days 02:41:41
Pace                    0:06:34
TotalSeconds             9701.0
HalfSeconds              4809.0
Name: 683, dtype: object
Fairgrove
 Age                          49
M/F                           F
City                  Fairgrove
State                        MI
Country                     USA
Half            0 days 01:52:40
40K             0 days 03:36:40
Pace                    0:08:42
TotalSeconds            13000.0
HalfSeconds              6760.0
Name: 21970, dtype: object
Fairhaven
 Age                          41
M/F                           F
City                  Fairhaven
State                        MA
Country                     USA
Half            0 days 01:40:16
40K             0 days 03:21:32
Pace                    0:08:09
TotalSeconds            12092.0
HalfSeconds              6016.0
Name: 16351, dtype: object
Fairhope
 Age                          46
M/F                           F
City                   Fairhope
State                        AL
Country                     USA
Half            0 days 01:58:59
40K             0 days 04:02:02
Pace                    0:09:48
TotalSeconds            14522.0
HalfSeconds              7139.0
Name: 23221, dtype: object
Fairmont
 Age                          27
M/F                           M
City                   Fairmont
State                        WV
Country                     USA
Half            0 days 01:22:25
40K             0 days 02:37:36
Pace                    0:06:20
TotalSeconds             9456.0
HalfSeconds              4945.0

Name: 3406, dtype: object
Fairmount City
 Age                          28
M/F                           F
City             Fairmount City
State                        PA
Country                     USA
Half            0 days 01:47:00
40K             0 days 03:32:34
Pace                    0:08:35
TotalSeconds            12754.0
HalfSeconds              6420.0
Name: 13737, dtype: object
Fairport
 Age                          27
M/F                           M
City                   Fairport
State                        NY
Country                     USA
Half            0 days 01:30:29
40K             0 days 03:24:09
Pace                    0:08:17
TotalSeconds            12249.0
HalfSeconds              5429.0
Name: 2145, dtype: object
Fairview
 Age                          38
M/F                           F
City                   Fairview
State                        NC
Country                     USA
Half            0 days 01:28:04
40K             0 days 02:49:57
Pace                    0:06:52
TotalSeconds            10197.0
HalfSeconds              5284.0
Name: 5590, dtype: object
Fairview Park
 Age                          25
M/F                           F
City              Fairview Park
State                        OH
Country                     USA
Half            0 days 01:32:11
40K             0 days 03:02:30
Pace                    0:07:23
TotalSeconds            10950.0
HalfSeconds              5531.0
Name: 10110, dtype: object
Falkenberg
 Age                          51
M/F                           M
City                 Falkenberg
State                       NaN
Country                     SWE
Half            0 days 01:49:12
40K             0 days 03:58:44
Pace                    0:09:40
TotalSeconds            14324.0
HalfSeconds              6552.0
Name: 14603, dtype: object
Fall City
 Age                          46
M/F                           M
City                  Fall City
State                        WA
Country                     USA
Half            0 days 01:59:10
40K             0 days 03:46:41
Pace                    0:09:09
TotalSeconds            13601.0
HalfSeconds              7150.0
Name: 29804, dtype: object
Fall River
 Age                          45
M/F                           M
City                 Fall River
State                        MA
Country                     USA
Half            0 days 01:35:40
40K             0 days 03:15:13
Pace                    0:07:56
TotalSeconds            11713.0
HalfSeconds              5740.0
Name: 6343, dtype: object
Fallbrook
 Age                          20
M/F                           M
City                  Fallbrook
State                        CA
Country                     USA
Half            0 days 01:23:15
40K             0 days 03:12:03
Pace                    0:07:47
TotalSeconds            11523.0
HalfSeconds              4995.0
Name: 1950, dtype: object
Falls Church
 Age                          50
M/F                           M
City               Falls Church
State                        VA
Country                     USA
Half            0 days 01:42:52
40K             0 days 03:25:24
Pace                    0:08:18
TotalSeconds            12324.0
HalfSeconds              6172.0
Name: 12300, dtype: object
Falmouth
 Age                          44
M/F                           F
City                   Falmouth
State                        ME
Country                     USA
Half            0 days 01:23:55
40K             0 days 02:42:32
Pace                    0:06:35
TotalSeconds             9752.0
HalfSeconds              5035.0
Name: F102, dtype: object
Falsterbo
 Age                          49
M/F                           M
City                  Falsterbo
State                       NaN
Country                     SWE
Half            0 days 01:34:50
40K             0 days 03:23:07
Pace                    0:08:17
TotalSeconds            12187.0
HalfSeconds              5690.0
Name: 9753, dtype: object
Falun
 Age                          61
M/F                           M
City                      Falun
State                       NaN
Country                     SWE
Half            0 days 01:51:30
40K             0 days 03:41:24
Pace                    0:08:55
TotalSeconds            13284.0
HalfSeconds              6690.0
Name: 21815, dtype: object
Falzes
 Age                          41
M/F                           F
City                     Falzes
State                       NaN
Country                     ITA
Half            0 days 02:06:08
40K             0 days 04:14:25
Pace                    0:10:16
TotalSeconds            15265.0
HalfSeconds              7568.0
Name: 31829, dtype: object
Fancy Farm
 Age                          40
M/F                           M
City                 Fancy Farm
State                        KY
Country                     USA
Half            0 days 01:33:26
40K             0 days 03:15:02
Pace                    0:07:53
TotalSeconds            11702.0
HalfSeconds              5606.0
Name: 6264, dtype: object
Far Hills
 Age                          45
M/F                           M
City                  Far Hills
State                        NJ
Country                     USA
Half            0 days 01:28:44
40K             0 days 03:17:37
Pace                    0:08:11
TotalSeconds            11857.0
HalfSeconds              5324.0
Name: 4781, dtype: object
Fara Vicentino - Vicenza
 Age                                   44
M/F                                    M
City            Fara Vicentino - Vicenza
State                                NaN
Country                              ITA
Half                     0 days 01:25:23
40K                      0 days 02:50:28
Pace                             0:06:54
TotalSeconds                     10228.0
HalfSeconds                       5123.0
Name: 1618, dtype: object
Fareham
 Age                          55
M/F                           M
City                    Fareham
State                       NaN
Country                     GBR
Half            0 days 01:38:32
40K             0 days 03:15:26
Pace                    0:07:54
TotalSeconds            11726.0
HalfSeconds              5912.0
Name: 12079, dtype: object
Fargo
 Age                          32
M/F                           F
City                      Fargo
State                        ND
Country                     USA
Half            0 days 01:42:35
40K             0 days 03:19:59
Pace                    0:08:04
TotalSeconds            11999.0
HalfSeconds              6155.0
Name: 11922, dtype: object
Faringdon
 Age                          49
M/F                           F
City                  Faringdon
State                       NaN
Country                     GBR
Half            0 days 01:59:52
40K             0 days 04:05:30
Pace                    0:09:56
TotalSeconds            14730.0
HalfSeconds              7192.0
Name: 19741, dtype: object
Farmersville
 Age                          42
M/F                           M
City               Farmersville
State                        CA
Country                     USA
Half            0 days 01:34:59
40K             0 days 03:30:32
Pace                    0:08:39
TotalSeconds            12632.0
HalfSeconds              5699.0
Name: 8680, dtype: object
Farmingdale
 Age                          35
M/F                           M
City                Farmingdale
State                        NJ
Country                     USA
Half            0 days 01:23:50
40K             0 days 02:42:18
Pace                    0:06:32
TotalSeconds             9738.0
HalfSeconds              5030.0
Name: 1958, dtype: object
Farmington
 Age                          37
M/F                           M
City                 Farmington
State                        UT
Country                     USA
Half            0 days 01:20:43
40K             0 days 02:39:32
Pace                    0:06:28
TotalSeconds             9572.0
HalfSeconds              4843.0
Name: 1337, dtype: object
Farmington Hills
 Age                           41
M/F                            M
City            Farmington Hills
State                         MI
Country                      USA
Half             0 days 01:22:00
40K              0 days 02:53:40
Pace                     0:07:01
TotalSeconds             10420.0
HalfSeconds               4920.0
Name: 668, dtype: object
Farmingville
 Age                          49
M/F                           M
City               Farmingville
State                        NY
Country                     USA
Half            0 days 02:39:21
40K             0 days 05:19:25
Pace                    0:12:52
TotalSeconds            19165.0
HalfSeconds              9561.0
Name: 31926, dtype: object
Farnborough
 Age                          45
M/F                           M
City                Farnborough
State                       NaN
Country                     GBR
Half            0 days 01:24:55
40K             0 days 02:48:33
Pace                    0:06:49
TotalSeconds            10113.0
HalfSeconds              5095.0
Name: 2585, dtype: object
Fate
 Age                          41
M/F                           F
City                       Fate
State                        TX
Country                     USA
Half            0 days 01:45:42
40K             0 days 03:22:41
Pace                    0:08:17
TotalSeconds            12161.0
HalfSeconds              6342.0
Name: 13872, dtype: object
Fayetteville
 Age                          32
M/F                           M
City               Fayetteville
State                        NY
Country                     USA
Half            0 days 01:22:37
40K             0 days 02:46:31
Pace                    0:06:46
TotalSeconds             9991.0
HalfSeconds              4957.0
Name: 2790, dtype: object
Fayville
 Age                          24
M/F                           M
City                   Fayville
State                        MA
Country                     USA
Half            0 days 02:20:01
40K             0 days 04:35:52
Pace                    0:11:06
TotalSeconds            16552.0
HalfSeconds              8401.0
Name: 31402, dtype: object
Federal Way
 Age                          35
M/F                           F
City                Federal Way
State                        WA
Country                     USA
Half            0 days 01:42:14
40K             0 days 03:17:05
Pace                    0:07:57
TotalSeconds            11825.0
HalfSeconds              6134.0
Name: 15384, dtype: object
Feeding Hills
 Age                          56
M/F                           M
City              Feeding Hills
State                        MA
Country                     USA
Half            0 days 01:51:40
40K             0 days 03:46:38
Pace                    0:09:11
TotalSeconds            13598.0
HalfSeconds              6700.0
Name: 11476, dtype: object
Feltham
 Age                          52
M/F                           M
City                    Feltham
State                       NaN
Country                     GBR
Half            0 days 01:39:03
40K             0 days 03:24:51
Pace                    0:08:19
TotalSeconds            12291.0
HalfSeconds              5943.0
Name: 13788, dtype: object
Fengyuan Dist, Taichung City
 Age                                       40
M/F                                        M
City            Fengyuan Dist, Taichung City
State                                    NaN
Country                                  TWN
Half                         0 days 01:30:44
40K                          0 days 02:58:25
Pace                                 0:07:12
TotalSeconds                         10705.0
HalfSeconds                           5444.0
Name: 7539, dtype: object
Fenton
 Age                          51
M/F                           F
City                     Fenton
State                        MI
Country                     USA
Half            0 days 01:30:01
40K             0 days 02:57:28
Pace                    0:07:11
TotalSeconds            10648.0
HalfSeconds              5401.0
Name: 5989, dtype: object
Ferdinand
 Age                          48
M/F                           M
City                  Ferdinand
State                        IN
Country                     USA
Half            0 days 01:35:54
40K             0 days 03:17:12
Pace                    0:08:00
TotalSeconds            11832.0
HalfSeconds              5754.0
Name: 8591, dtype: object
Fergus Falls
 Age                          38
M/F                           F
City               Fergus Falls
State                        MN
Country                     USA
Half            0 days 01:58:34
40K             0 days 03:50:11
Pace                    0:09:15
TotalSeconds            13811.0
HalfSeconds              7114.0
Name: 20113, dtype: object
Fernandina Beach
 Age                           37
M/F                            F
City            Fernandina Beach
State                         FL
Country                      USA
Half             0 days 01:53:00
40K              0 days 03:42:36
Pace                     0:08:58
TotalSeconds             13356.0
HalfSeconds               6780.0
Name: 18823, dtype: object
Ferndale
 Age                          27
M/F                           F
City                   Ferndale
State                        MI
Country                     USA
Half            0 days 01:44:27
40K             0 days 03:30:51
Pace                    0:08:29
TotalSeconds            12651.0
HalfSeconds              6267.0
Name: 10322, dtype: object
Ferron
 Age                          40
M/F                           M
City                     Ferron
State                        UT
Country                     USA
Half            0 days 01:18:33
40K             0 days 02:32:37
Pace                    0:06:11
TotalSeconds             9157.0
HalfSeconds              4713.0
Name: 265, dtype: object
Ferryland
 Age                          57
M/F                           F
City                  Ferryland
State                        NL
Country                     CAN
Half            0 days 01:44:33
40K             0 days 03:39:36
Pace                    0:08:54
TotalSeconds            13176.0
HalfSeconds              6273.0
Name: 11323, dtype: object
Festus
 Age                          38
M/F                           F
City                     Festus
State                        MO
Country                     USA
Half            0 days 01:49:33
40K             0 days 03:44:16
Pace                    0:09:06
TotalSeconds            13456.0
HalfSeconds              6573.0
Name: 20884, dtype: object
Fiave' - Tn
 Age                          53
M/F                           M
City                Fiave' - Tn
State                       NaN
Country                     ITA
Half            0 days 01:39:07
40K             0 days 03:15:10
Pace                    0:07:53
TotalSeconds            11710.0
HalfSeconds              5947.0
Name: 10636, dtype: object
Fife
 Age                          34
M/F                           M
City                       Fife
State                       NaN
Country                     GBR
Half            0 days 01:22:51
40K             0 days 02:45:41
Pace                    0:06:42
TotalSeconds             9941.0
HalfSeconds              4971.0
Name: 635, dtype: object
Figtree
 Age                          51
M/F                           M
City                    Figtree
State                       NaN
Country                     AUS
Half            0 days 01:41:35
40K             0 days 03:48:49
Pace                    0:09:30
TotalSeconds            13729.0
HalfSeconds              6095.0
Name: 7298, dtype: object
Findlay
 Age                          35
M/F                           M
City                    Findlay
State                        OH
Country                     USA
Half            0 days 01:17:16
40K             0 days 02:35:34
Pace                    0:06:19
TotalSeconds             9334.0
HalfSeconds              4636.0
Name: 209, dtype: object
Findley Lake
 Age                          54
M/F                           M
City               Findley Lake
State                        NY
Country                     USA
Half            0 days 01:45:32
40K             0 days 03:27:07
Pace                    0:08:22
TotalSeconds            12427.0
HalfSeconds              6332.0

Name: 14437, dtype: object
Finksburg
 Age                          42
M/F                           F
City                  Finksburg
State                        MD
Country                     USA
Half            0 days 02:02:16
40K             0 days 04:12:10
Pace                    0:10:10
TotalSeconds            15130.0
HalfSeconds              7336.0
Name: 21080, dtype: object
Fircrest
 Age                          45
M/F                           M
City                   Fircrest
State                        WA
Country                     USA
Half            0 days 02:03:00
40K             0 days 04:20:24
Pace                    0:10:31
TotalSeconds            15624.0
HalfSeconds              7380.0
Name: 9323, dtype: object
Fishers
 Age                          45
M/F                           M
City                    Fishers
State                        IN
Country                     USA
Half            0 days 01:25:47
40K             0 days 02:40:46
Pace                    0:06:27
TotalSeconds             9646.0
HalfSeconds              5147.0
Name: 1316, dtype: object
Fishersville
 Age                          48
M/F                           M
City               Fishersville
State                        VA
Country                     USA
Half            0 days 01:30:58
40K             0 days 03:03:54
Pace                    0:07:25
TotalSeconds            11034.0
HalfSeconds              5458.0
Name: 2884, dtype: object
Fisherville
 Age                          47
M/F                           F
City                Fisherville
State                        KY
Country                     USA
Half            0 days 02:00:48
40K             0 days 04:08:30
Pace                    0:10:03
TotalSeconds            14910.0
HalfSeconds              7248.0
Name: 22715, dtype: object
Fitchburg
 Age                          35
M/F                           F
City                  Fitchburg
State                        WI
Country                     USA
Half            0 days 01:31:58
40K             0 days 02:54:02
Pace                    0:07:00
TotalSeconds            10442.0
HalfSeconds              5518.0
Name: 5554, dtype: object
Fitzwilliam
 Age                          64
M/F                           M
City                Fitzwilliam
State                        NH
Country                     USA
Half            0 days 01:44:53
40K             0 days 03:36:31
Pace                    0:08:50
TotalSeconds            12991.0
HalfSeconds              6293.0
Name: 24090, dtype: object
Fivemiletown
 Age                          47
M/F                           M
City               Fivemiletown
State                       NaN
Country                     GBR
Half            0 days 01:36:00
40K             0 days 03:07:46
Pace                    0:07:35
TotalSeconds            11266.0
HalfSeconds              5760.0
Name: 11116, dtype: object
Flagler Beach
 Age                          49
M/F                           M
City              Flagler Beach
State                        FL
Country                     USA
Half            0 days 01:43:22
40K             0 days 03:28:30
Pace                    0:08:24
TotalSeconds            12510.0
HalfSeconds              6202.0
Name: 5373, dtype: object
Flagstaff
 Age                          31
M/F                           M
City                  Flagstaff
State                        AZ
Country                     USA
Half            0 days 01:21:59
40K             0 days 02:43:51
Pace                    0:06:39
TotalSeconds             9831.0
HalfSeconds              4919.0
Name: 545, dtype: object
Flagstafff
 Age                          51
M/F                           F
City                 Flagstafff
State                        AZ
Country                     USA
Half            0 days 01:44:48
40K             0 days 03:27:11
Pace                    0:08:23
TotalSeconds            12431.0
HalfSeconds              6288.0
Name: 19300, dtype: object
Flanders
 Age                          52
M/F                           F
City                   Flanders
State                        NJ
Country                     USA
Half            0 days 01:37:44
40K             0 days 03:10:04
Pace                    0:07:40
TotalSeconds            11404.0
HalfSeconds              5864.0
Name: 11073, dtype: object
Fleckney
 Age                          43
M/F                           M
City                   Fleckney
State                       NaN
Country                     GBR
Half            0 days 01:36:06
40K             0 days 03:12:27
Pace                    0:07:48
TotalSeconds            11547.0
HalfSeconds              5766.0
Name: 6401, dtype: object
Fleetwood
 Age                          21
M/F                           F
City                  Fleetwood
State                        PA
Country                     USA
Half            0 days 01:36:44
40K             0 days 03:10:08
Pace                    0:07:38
TotalSeconds            11408.0
HalfSeconds              5804.0
Name: 9511, dtype: object
Fleming Island
 Age                          46
M/F                           M
City             Fleming Island
State                        FL
Country                     USA
Half            0 days 01:30:27
40K             0 days 03:01:22
Pace                    0:07:20
TotalSeconds            10882.0
HalfSeconds              5427.0
Name: 9043, dtype: object
Flemington
 Age                          44
M/F                           M
City                 Flemington
State                        NJ
Country                     USA
Half            0 days 01:27:36
40K             0 days 02:50:27
Pace                    0:06:52
TotalSeconds            10227.0
HalfSeconds              5256.0
Name: 2862, dtype: object
Fletcher
 Age                          31
M/F                           F
City                   Fletcher
State                        NC
Country                     USA
Half            0 days 01:41:34
40K             0 days 03:18:58
Pace                    0:08:02
TotalSeconds            11938.0
HalfSeconds              6094.0
Name: 17358, dtype: object
Flint
 Age                          49
M/F                           M
City                      Flint
State                        MI
Country                     USA
Half            0 days 01:44:31
40K             0 days 03:39:58
Pace                    0:08:55
TotalSeconds            13198.0
HalfSeconds              6271.0
Name: 10876, dtype: object
Florence
 Age                          45
M/F                           M
City                   Florence
State                        SC
Country                     USA
Half            0 days 01:28:42
40K             0 days 02:55:37
Pace                    0:07:07
TotalSeconds            10537.0
HalfSeconds              5322.0
Name: 2678, dtype: object
Floresville
 Age                          28
M/F                           F
City                Floresville
State                        TX
Country                     USA
Half            0 days 01:56:21
40K             0 days 03:46:34
Pace                    0:09:08
TotalSeconds            13594.0
HalfSeconds              6981.0
Name: 17808, dtype: object
Florham Park
 Age                          47
M/F                           M
City               Florham Park
State                        NJ
Country                     USA
Half            0 days 01:41:07
40K             0 days 03:28:24
Pace                    0:08:28
TotalSeconds            12504.0
HalfSeconds              6067.0
Name: 12363, dtype: object
Florissant
 Age                          30
M/F                           F
City                 Florissant
State                        MO
Country                     USA
Half            0 days 01:45:01
40K             0 days 03:30:08
Pace                    0:08:28
TotalSeconds            12608.0
HalfSeconds              6301.0
Name: 19121, dtype: object
Flourtown
 Age                          35
M/F                           M
City                  Flourtown
State                        PA
Country                     USA
Half            0 days 01:24:22
40K             0 days 02:49:31
Pace                    0:06:54
TotalSeconds            10171.0
HalfSeconds              5062.0
Name: 1243, dtype: object
Flower Mound
 Age                          42
M/F                           F
City               Flower Mound
State                        TX
Country                     USA
Half            0 days 01:30:12
40K             0 days 02:55:01
Pace                    0:07:03
TotalSeconds            10501.0
HalfSeconds              5412.0
Name: 3477, dtype: object
Flowery Branch
 Age                          61
M/F                           M
City             Flowery Branch
State                        GA
Country                     USA
Half            0 days 01:41:58
40K             0 days 03:24:31
Pace                    0:08:17
TotalSeconds            12271.0
HalfSeconds              6118.0
Name: 24353, dtype: object
Flowood
 Age                          59
M/F                           F
City                    Flowood
State                        MS
Country                     USA
Half            0 days 02:10:37
40K             0 days 04:34:53
Pace                    0:11:02
TotalSeconds            16493.0
HalfSeconds              7837.0
Name: 24937, dtype: object
Floyds Knobs
 Age                          58
M/F                           M
City               Floyds Knobs
State                        IN
Country                     USA
Half            0 days 01:37:00
40K             0 days 03:18:34
Pace                    0:08:01
TotalSeconds            11914.0
HalfSeconds              5820.0
Name: 7247, dtype: object
Flushing
 Age                          38
M/F                           M
City                   Flushing
State                        NY
Country                     USA
Half            0 days 01:31:22
40K             0 days 03:01:12
Pace                    0:07:17
TotalSeconds            10872.0
HalfSeconds              5482.0
Name: 2219, dtype: object
Fogelsville
 Age                          44
M/F                           F
City                Fogelsville
State                        PA
Country                     USA
Half            0 days 01:42:02
40K             0 days 03:26:05
Pace                    0:08:20
TotalSeconds            12365.0
HalfSeconds              6122.0
Name: 17458, dtype: object
Foligno - Pg
 Age                          39
M/F                           M
City               Foligno - Pg
State                       NaN
Country                     ITA
Half            0 days 01:19:43
40K             0 days 02:41:27
Pace                    0:06:32
TotalSeconds             9687.0
HalfSeconds              4783.0
Name: 705, dtype: object
Folsom
 Age                          42
M/F                           M
City                     Folsom
State                        CA
Country                     USA
Half            0 days 01:30:55
40K             0 days 02:57:18
Pace                    0:07:10
TotalSeconds            10638.0
HalfSeconds              5455.0
Name: 8466, dtype: object
Fond Du Lac
 Age                          62
M/F                           M
City                Fond Du Lac
State                        WI
Country                     USA
Half            0 days 01:39:47
40K             0 days 03:10:05
Pace                    0:07:40
TotalSeconds            11405.0
HalfSeconds              5987.0
Name: 10536, dtype: object
Fontana
 Age                          29
M/F                           F
City                    Fontana
State                        WI
Country                     USA
Half            0 days 01:43:00
40K             0 days 03:31:55
Pace                    0:08:35
TotalSeconds            12715.0
HalfSeconds              6180.0
Name: 11794, dtype: object
Fonthill
 Age                          62
M/F                           M
City                   Fonthill
State                        ON
Country                     CAN
Half            0 days 01:47:49
40K             0 days 03:28:41
Pace                    0:08:27
TotalSeconds            12521.0
HalfSeconds              6469.0
Name: 21121, dtype: object
Foothill Ranch
 Age                          55
M/F                           F
City             Foothill Ranch
State                        CA
Country                     USA
Half            0 days 01:58:34
40K             0 days 03:44:12
Pace                    0:09:03
TotalSeconds            13452.0
HalfSeconds              7114.0
Name: 25344, dtype: object
Footscray
 Age                          45
M/F                           F
City                  Footscray
State                       NaN
Country                     AUS
Half            0 days 01:45:45
40K             0 days 03:27:14
Pace                    0:08:23
TotalSeconds            12434.0
HalfSeconds              6345.0
Name: 20392, dtype: object
For Worth
 Age                          21
M/F                           F
City                  For Worth
State                        TX
Country                     USA
Half            0 days 01:40:40
40K             0 days 03:11:56
Pace                    0:07:44
TotalSeconds            11516.0
HalfSeconds              6040.0
Name: 12939, dtype: object
Forest
 Age                          34
M/F                           M
City                     Forest
State                        VA
Country                     USA
Half            0 days 01:31:44
40K             0 days 03:27:12
Pace                    0:08:24
TotalSeconds            12432.0
HalfSeconds              5504.0
Name: 4588, dtype: object
Forest City
 Age                          59
M/F                           M
City                Forest City
State                        IA
Country                     USA
Half            0 days 01:52:06
40K             0 days 03:42:34
Pace                    0:09:02
TotalSeconds            13354.0
HalfSeconds              6726.0
Name: 10237, dtype: object
Forest Grove
 Age                          35
M/F                           F
City               Forest Grove
State                        OR
Country                     USA
Half            0 days 01:38:17
40K             0 days 03:05:56
Pace                    0:07:28
TotalSeconds            11156.0
HalfSeconds              5897.0
Name: 9829, dtype: object
Forest Hills
 Age                          40
M/F                           M
City               Forest Hills
State                        NY
Country                     USA
Half            0 days 01:32:47
40K             0 days 03:54:22
Pace                    0:09:26
TotalSeconds            14062.0
HalfSeconds              5567.0
Name: 5283, dtype: object
Forest Lake
 Age                          30
M/F                           F
City                Forest Lake
State                        MN
Country                     USA
Half            0 days 01:37:18
40K             0 days 03:13:07
Pace                    0:07:49
TotalSeconds            11587.0
HalfSeconds              5838.0
Name: 9922, dtype: object
Forest Park
 Age                          25
M/F                           M
City                Forest Park
State                        IL
Country                     USA
Half            0 days 01:24:53
40K             0 days 03:03:05
Pace                    0:07:22
TotalSeconds            10985.0
HalfSeconds              5093.0
Name: 2707, dtype: object
Forestdale
 Age                          42
M/F                           F
City                 Forestdale
State                        MA
Country                     USA
Half            0 days 02:40:22
40K             0 days 05:30:12
Pace                    0:13:19
TotalSeconds            19812.0
HalfSeconds              9622.0
Name: 26781, dtype: object
Forestville
 Age                          67
M/F                           F
City                Forestville
State                        CA
Country                     USA
Half            0 days 02:19:12
40K             0 days 04:41:20
Pace                    0:11:21
TotalSeconds            16880.0
HalfSeconds              8352.0
Name: 26073, dtype: object
Forney
 Age                          31
M/F                           M
City                     Forney
State                        TX
Country                     USA
Half            0 days 01:22:27
40K             0 days 03:00:41
Pace                    0:07:24
TotalSeconds            10841.0
HalfSeconds              4947.0
Name: 3716, dtype: object
Forsyth
 Age                          51
M/F                           M
City                    Forsyth
State                        GA
Country                     USA
Half            0 days 01:42:29
40K             0 days 03:22:57
Pace                    0:08:16
TotalSeconds            12177.0
HalfSeconds              6149.0
Name: 12451, dtype: object
Fort Atkinson
 Age                          35
M/F                           F
City              Fort Atkinson
State                        WI
Country                     USA
Half            0 days 01:33:28
40K             0 days 03:02:10
Pace                    0:07:24
TotalSeconds            10930.0
HalfSeconds              5608.0
Name: 9028, dtype: object
Fort Belvoir
 Age                          32
M/F                           M
City               Fort Belvoir
State                        VA
Country                     USA
Half            0 days 01:24:53
40K             0 days 02:44:06
Pace                    0:06:38
TotalSeconds             9846.0
HalfSeconds              5093.0
Name: 4778, dtype: object
Fort Bragg
 Age                          23
M/F                           F
City                 Fort Bragg
State                        NC
Country                     USA
Half            0 days 02:18:58
40K             0 days 04:50:18
Pace                    0:11:38
TotalSeconds            17418.0
HalfSeconds              8338.0
Name: 26210, dtype: object
Fort Collins
 Age                          43
M/F                           M
City               Fort Collins
State                        CO
Country                     USA
Half            0 days 01:22:35
40K             0 days 02:39:41
Pace                    0:06:27
TotalSeconds             9581.0
HalfSeconds              4955.0
Name: 3863, dtype: object
Fort De France
 Age                          43
M/F                           F
City             Fort De France
State                       NaN
Country                     FRA
Half            0 days 02:43:05
40K             0 days 05:43:54
Pace                    0:13:49
TotalSeconds            20634.0
HalfSeconds              9785.0
Name: 30195, dtype: object
Fort Drum
 Age                          29
M/F                           F
City                  Fort Drum
State                        NY
Country                     USA
Half            0 days 01:43:47
40K             0 days 03:32:39
Pace                    0:08:34
TotalSeconds            12759.0
HalfSeconds              6227.0
Name: 15183, dtype: object
Fort Erie
 Age                          48
M/F                           F
City                  Fort Erie
State                        ON
Country                     CAN
Half            0 days 02:01:55
40K             0 days 03:52:51
Pace                    0:09:23
TotalSeconds            13971.0
HalfSeconds              7315.0
Name: 22253, dtype: object
Fort Gratiot
 Age                          55
M/F                           M
City               Fort Gratiot
State                        MI
Country                     USA
Half            0 days 01:42:25
40K             0 days 03:14:47
Pace                    0:07:52
TotalSeconds            11687.0
HalfSeconds              6145.0
Name: 15435, dtype: object
Fort Knox
 Age                          54
M/F                           M
City                  Fort Knox
State                        KY
Country                     USA
Half            0 days 02:21:55
40K             0 days 05:00:45

 Age                          37
M/F                           M
City             Fountain Hills
State                        AZ
Country                     USA
Half            0 days 01:27:20
40K             0 days 02:51:42
Pace                    0:06:56
TotalSeconds            10302.0
HalfSeconds              5240.0
Name: 3762, dtype: object
Fountain Valley
 Age                          36
M/F                           M
City            Fountain Valley
State                        CA
Country                     USA
Half            0 days 01:30:00
40K             0 days 03:00:08
Pace                    0:07:20
TotalSeconds            10808.0
HalfSeconds              5400.0
Name: 3259, dtype: object
Fowlerville
 Age                          45
M/F                           M
City                Fowlerville
State                        MI
Country                     USA
Half            0 days 01:29:51
40K             0 days 02:57:33
Pace                    0:07:11
TotalSeconds            10653.0
HalfSeconds              5391.0
Name: 8002, dtype: object
Fox Island
 Age                          45
M/F                           F
City                 Fox Island
State                        WA
Country                     USA
Half            0 days 01:55:20
40K             0 days 03:43:46
Pace                    0:09:01
TotalSeconds            13426.0
HalfSeconds              6920.0
Name: 23319, dtype: object
Fox Point
 Age                          59
M/F                           M
City                  Fox Point
State                        WI
Country                     USA
Half            0 days 01:45:08
40K             0 days 03:26:43
Pace                    0:08:23
TotalSeconds            12403.0
HalfSeconds              6308.0
Name: 14300, dtype: object
Fox River Grove
 Age                          41
M/F                           M
City            Fox River Grove
State                        IL
Country                     USA
Half            0 days 01:32:21
40K             0 days 03:01:04
Pace                    0:07:20
TotalSeconds            10864.0
HalfSeconds              5541.0
Name: 6260, dtype: object
Foxboro
 Age                          28
M/F                           M
City                    Foxboro
State                        MA
Country                     USA
Half            0 days 01:39:21
40K             0 days 03:18:30
Pace                    0:08:04
TotalSeconds            11910.0
HalfSeconds              5961.0
Name: 27552, dtype: object
Foxborough
 Age                          35
M/F                           F
City                 Foxborough
State                        MA
Country                     USA
Half            0 days 02:00:52
40K             0 days 04:04:23
Pace                    0:09:52
TotalSeconds            14663.0
HalfSeconds              7252.0
Name: 27336, dtype: object
Fpo
 Age                          41
M/F                           M
City                        Fpo
State                        AE
Country                     USA
Half            0 days 01:34:21
40K             0 days 03:04:07
Pace                    0:07:32
TotalSeconds            11047.0
HalfSeconds              5661.0
Name: 8681, dtype: object
Framigham
 Age                          24
M/F                           M
City                  Framigham
State                        MA
Country                     USA
Half            0 days 02:05:23
40K             0 days 03:59:11
Pace                    0:09:38
TotalSeconds            14351.0
HalfSeconds              7523.0
Name: 28215, dtype: object
Framingham
 Age                          38
M/F                           M
City                 Framingham
State                        MA
Country                     USA
Half            0 days 01:33:07
40K             0 days 03:02:23
Pace                    0:07:23
TotalSeconds            10943.0
HalfSeconds              5587.0
Name: 6827, dtype: object
Francestown
 Age                          63
M/F                           M
City                Francestown
State                        NH
Country                     USA
Half            0 days 01:44:05
40K             0 days 03:27:48
Pace                    0:08:25
TotalSeconds            12468.0
HalfSeconds              6245.0
Name: 10105, dtype: object
Franco Da Rocha
 Age                          45
M/F                           F
City            Franco Da Rocha
State                       NaN
Country                     BRA
Half            0 days 01:41:47
40K             0 days 03:19:03
Pace                    0:08:02
TotalSeconds            11943.0
HalfSeconds              6107.0
Name: 22949, dtype: object
Frankenmuth
 Age                          41
M/F                           M
City                Frankenmuth
State                        MI
Country                     USA
Half            0 days 01:33:15
40K             0 days 03:14:40
Pace                    0:08:03
TotalSeconds            11680.0
HalfSeconds              5595.0
Name: 8482, dtype: object
Frankenthal
 Age                          51
M/F                           M
City                Frankenthal
State                       NaN
Country                     GER
Half            0 days 01:48:03
40K             0 days 03:35:08
Pace                    0:08:41
TotalSeconds            12908.0
HalfSeconds              6483.0
Name: 8588, dtype: object
Frankford
 Age                          40
M/F                           M
City                  Frankford
State                        ON
Country                     CAN
Half            0 days 01:20:05
40K             0 days 02:36:04
Pace                    0:06:18
TotalSeconds             9364.0
HalfSeconds              4805.0
Name: 852, dtype: object
Frankfort
 Age                          35
M/F                           F
City                  Frankfort
State                        IL
Country                     USA
Half            0 days 01:42:03
40K             0 days 03:26:31
Pace                    0:08:21
TotalSeconds            12391.0
HalfSeconds              6123.0
Name: 12284, dtype: object
Frankfrod
 Age                          53
M/F                           F
City                  Frankfrod
State                        ON
Country                     CAN
Half            0 days 01:51:50
40K             0 days 03:42:33
Pace                    0:08:59
TotalSeconds            13353.0
HalfSeconds              6710.0
Name: 24976, dtype: object
Frankfurt
 Age                          42
M/F                           M
City                  Frankfurt
State                       NaN
Country                     GER
Half            0 days 01:39:28
40K             0 days 03:08:36
Pace                    0:07:35
TotalSeconds            11316.0
HalfSeconds              5968.0
Name: 7391, dtype: object
Frankfurt Am Main
 Age                            26
M/F                             M
City            Frankfurt Am Main
State                         NaN
Country                       GER
Half              0 days 01:20:09
40K               0 days 02:49:32
Pace                      0:06:51
TotalSeconds              10172.0
HalfSeconds                4809.0
Name: 474, dtype: object
Franklin
 Age                          40
M/F                           M
City                   Franklin
State                        MA
Country                     USA
Half            0 days 01:24:01
40K             0 days 02:46:43
Pace                    0:06:44
TotalSeconds            10003.0
HalfSeconds              5041.0
Name: 1593, dtype: object
Franksville
 Age                          66
M/F                           M
City                Franksville
State                        WI
Country                     USA
Half            0 days 01:40:22
40K             0 days 03:19:26
Pace                    0:08:02
TotalSeconds            11966.0
HalfSeconds              6022.0
Name: 11121, dtype: object
Fraser
 Age                          53
M/F                           M
City                     Fraser
State                        MI
Country                     USA
Half            0 days 01:43:35
40K             0 days 03:51:27
Pace                    0:09:30
TotalSeconds            13887.0
HalfSeconds              6215.0
Name: 15083, dtype: object
Fredensborg
 Age                          58
M/F                           M
City                Fredensborg
State                       NaN
Country                     DEN
Half            0 days 01:49:22
40K             0 days 03:50:12
Pace                    0:09:20
TotalSeconds            13812.0
HalfSeconds              6562.0
Name: 17692, dtype: object
Frederica
 Age                          48
M/F                           M
City                  Frederica
State                        DE
Country                     USA
Half            0 days 02:05:19
40K             0 days 04:40:37
Pace                    0:11:29
TotalSeconds            16837.0
HalfSeconds              7519.0
Name: 8292, dtype: object
Frederick
 Age                          32
M/F                           M
City                  Frederick
State                        MD
Country                     USA
Half            0 days 01:20:02
40K             0 days 02:37:59
Pace                    0:06:22
TotalSeconds             9479.0
HalfSeconds              4802.0

Name: 1046, dtype: object
Frederick,
 Age                          48
M/F                           F
City                 Frederick,
State                        MD
Country                     USA
Half            0 days 01:59:29
40K             0 days 03:59:13
Pace                    0:09:40
TotalSeconds            14353.0
HalfSeconds              7169.0
Name: 21982, dtype: object
Fredericksburg
 Age                          36
M/F                           F
City             Fredericksburg
State                        VA
Country                     USA
Half            0 days 01:33:44
40K             0 days 02:59:52
Pace                    0:07:15
TotalSeconds            10792.0
HalfSeconds              5624.0
Name: 7529, dtype: object
Fredericton
 Age                          35
M/F                           M
City                Fredericton
State                        NB
Country                     CAN
Half            0 days 01:22:37
40K             0 days 02:39:50
Pace                    0:06:30
TotalSeconds             9590.0
HalfSeconds              4957.0
Name: 1460, dtype: object
Frederiksberg C
 Age                          47
M/F                           M
City            Frederiksberg C
State                       NaN
Country                     DEN
Half            0 days 02:05:34
40K             0 days 04:39:03
Pace                    0:11:15
TotalSeconds            16743.0
HalfSeconds              7534.0
Name: 30402, dtype: object
Fredonia
 Age                          42
M/F                           F
City                   Fredonia
State                        NY
Country                     USA
Half            0 days 02:15:20
40K             0 days 04:34:30
Pace                    0:11:05
TotalSeconds            16470.0
HalfSeconds              8120.0
Name: 13540, dtype: object
Free Union
 Age                          49
M/F                           F
City                 Free Union
State                        VA
Country                     USA
Half            0 days 01:49:51
40K             0 days 03:36:02
Pace                    0:08:48
TotalSeconds            12962.0
HalfSeconds              6591.0
Name: 18484, dtype: object
Freeburg
 Age                          53
M/F                           M
City                   Freeburg
State                        PA
Country                     USA
Half            0 days 01:34:37
40K             0 days 03:08:17
Pace                    0:07:36
TotalSeconds            11297.0
HalfSeconds              5677.0
Name: 1915, dtype: object
Freedom
 Age                          24
M/F                           F
City                    Freedom
State                        NH
Country                     USA
Half            0 days 01:39:32
40K             0 days 03:14:30
Pace                    0:07:51
TotalSeconds            11670.0
HalfSeconds              5972.0
Name: 10213, dtype: object
Freehold
 Age                          56
M/F                           M
City                   Freehold
State                        NJ
Country                     USA
Half            0 days 01:41:51
40K             0 days 03:25:02
Pace                    0:08:21
TotalSeconds            12302.0
HalfSeconds              6111.0
Name: 14199, dtype: object
Freeland
 Age                          46
M/F                           F
City                   Freeland
State                        MD
Country                     USA
Half            0 days 01:47:05
40K             0 days 03:43:19
Pace                    0:09:09
TotalSeconds            13399.0
HalfSeconds              6425.0
Name: 18391, dtype: object
Freeman
 Age                          33
M/F                           F
City                    Freeman
State                        SD
Country                     USA
Half            0 days 01:33:37
40K             0 days 03:03:47
Pace                    0:07:25
TotalSeconds            11027.0
HalfSeconds              5617.0
Name: 7541, dtype: object
Freeport
 Age                          51
M/F                           M
City                   Freeport
State                        ME
Country                     USA
Half            0 days 01:36:58
40K             0 days 03:10:36
Pace                    0:07:43
TotalSeconds            11436.0
HalfSeconds              5818.0
Name: 13413, dtype: object
Freiburg
 Age                          47
M/F                           M
City                   Freiburg
State                       NaN
Country                     GER
Half            0 days 01:40:20
40K             0 days 03:32:07
Pace                    0:08:36
TotalSeconds            12727.0
HalfSeconds              6020.0
Name: 9474, dtype: object
Fremont
 Age                          30
M/F                           M
City                    Fremont
State                        CA
Country                     USA
Half            0 days 01:28:52
40K             0 days 02:51:55
Pace                    0:06:56
TotalSeconds            10315.0
HalfSeconds              5332.0
Name: 4011, dtype: object
Fresh Meadows
 Age                          38
M/F                           M
City              Fresh Meadows
State                        NY
Country                     USA
Half            0 days 01:28:51
40K             0 days 02:51:47
Pace                    0:06:57
TotalSeconds            10307.0
HalfSeconds              5331.0
Name: 5165, dtype: object
Fresno
 Age                          25
M/F                           M
City                     Fresno
State                        CA
Country                     USA
Half            0 days 01:23:15
40K             0 days 02:44:13
Pace                    0:06:38
TotalSeconds             9853.0
HalfSeconds              4995.0
Name: 2249, dtype: object
Fridley
 Age                          21
M/F                           M
City                    Fridley
State                        MN
Country                     USA
Half            0 days 01:28:41
40K             0 days 02:53:43
Pace                    0:07:01
TotalSeconds            10423.0
HalfSeconds              5321.0
Name: 3876, dtype: object
Friedrichsdorf
 Age                          53
M/F                           M
City             Friedrichsdorf
State                       NaN
Country                     GER
Half            0 days 01:55:54
40K             0 days 04:15:08
Pace                    0:10:37
TotalSeconds            15308.0
HalfSeconds              6954.0
Name: 31875, dtype: object
Friendsville
 Age                          49
M/F                           F
City               Friendsville
State                        TN
Country                     USA
Half            0 days 01:40:42
40K             0 days 03:18:05
Pace                    0:08:02
TotalSeconds            11885.0
HalfSeconds              6042.0
Name: 12303, dtype: object
Friendswood
 Age                          46
M/F                           F
City                Friendswood
State                        TX
Country                     USA
Half            0 days 01:54:23
40K             0 days 03:41:00
Pace                    0:08:56
TotalSeconds            13260.0
HalfSeconds              6863.0
Name: 21428, dtype: object
Friendwood
 Age                          54
M/F                           F
City                 Friendwood
State                        TX
Country                     USA
Half            0 days 01:58:42
40K             0 days 03:56:23
Pace                    0:09:32
TotalSeconds            14183.0
HalfSeconds              7122.0
Name: 25061, dtype: object
Frisco
 Age                          39
M/F                           M
City                     Frisco
State                        TX
Country                     USA
Half            0 days 01:29:16
40K             0 days 02:50:01
Pace                    0:06:50
TotalSeconds            10201.0
HalfSeconds              5356.0
Name: 5014, dtype: object
Frome, Somerset
 Age                          52
M/F                           F
City            Frome, Somerset
State                       NaN
Country                     GBR
Half            0 days 01:53:16
40K             0 days 03:38:10
Pace                    0:08:48
TotalSeconds            13090.0
HalfSeconds              6796.0
Name: 23058, dtype: object
Fruit Heights
 Age                          30
M/F                           F
City              Fruit Heights
State                        UT
Country                     USA
Half            0 days 01:29:53
40K             0 days 02:58:11
Pace                    0:07:12
TotalSeconds            10691.0
HalfSeconds              5393.0
Name: 2185, dtype: object
Fruitvale
 Age                          37
M/F                           F
City                  Fruitvale
State                        BC
Country                     CAN
Half            0 days 01:36:47
40K             0 days 03:12:57
Pace                    0:07:47
TotalSeconds            11577.0
HalfSeconds              5807.0
Name: 7020, dtype: object
Ft Lauderdale
 Age                          53
M/F                           F
City              Ft Lauderdale
State                        FL
Country                     USA
Half            0 days 02:07:48
40K             0 days 04:13:47
Pace                    0:10:15
TotalSeconds            15227.0
HalfSeconds              7668.0
Name: 27912, dtype: object
Ft Worth
 Age                          50
M/F                           F
City                   Ft Worth
State                        TX
Country                     USA
Half            0 days 01:43:11
40K             0 days 03:15:41
Pace                    0:07:53
TotalSeconds            11741.0
HalfSeconds              6191.0
Name: 18408, dtype: object
Ft. Mcmurray
 Age                          45
M/F                           M
City               Ft. Mcmurray
State                        AB
Country                     CAN
Half            0 days 01:40:21
40K             0 days 03:15:41
Pace                    0:07:53
TotalSeconds            11741.0
HalfSeconds              6021.0
Name: 5059, dtype: object
Ft. Myers
 Age                          69
M/F                           M
City                  Ft. Myers
State                        FL
Country                     USA
Half            0 days 02:04:12
40K             0 days 04:16:21
Pace                    0:10:22
TotalSeconds            15381.0
HalfSeconds              7452.0
Name: 25544, dtype: object
Ft. Worth
 Age                          51
M/F                           M
City                  Ft. Worth
State                        TX
Country                     USA
Half            0 days 01:42:24
40K             0 days 03:26:47
Pace                    0:08:22
TotalSeconds            12407.0
HalfSeconds              6144.0
Name: 11417, dtype: object
Fujimishi, Saitama
 Age                             65
M/F                              M
City            Fujimishi, Saitama
State                          NaN
Country                        JPN
Half               0 days 02:09:24
40K                0 days 05:01:40
Pace                       0:12:02
TotalSeconds               18100.0
HalfSeconds                 7764.0
Name: 25525, dtype: object
Fukuoka
 Age                          62
M/F                           F
City                    Fukuoka
State                       NaN
Country                     JPN
Half            0 days 01:35:57
40K             0 days 03:10:40
Pace                    0:07:43
TotalSeconds            11440.0
HalfSeconds              5757.0
Name: 7410, dtype: object
Fullerton
 Age                          26
M/F                           F
City                  Fullerton
State                        CA
Country                     USA
Half            0 days 01:43:46
40K             0 days 03:12:39
Pace                    0:07:44
TotalSeconds            11559.0
HalfSeconds              6226.0
Name: 13487, dtype: object
Fulton
 Age                          30
M/F                           M
City                     Fulton
State                        NY
Country                     USA
Half            0 days 01:31:02
40K             0 days 03:08:22
Pace                    0:07:35
TotalSeconds            11302.0
HalfSeconds              5462.0
Name: 3384, dtype: object
Fuquay Varina
 Age                          49
M/F                           F
City              Fuquay Varina
State                        NC
Country                     USA
Half            0 days 02:00:18
40K             0 days 04:01:07
Pace                    0:09:43
TotalSeconds            14467.0
HalfSeconds              7218.0
Name: 21805, dtype: object
Furlong
 Age                          60
M/F                           F
City                    Furlong
State                        PA
Country                     USA
Half            0 days 02:16:47
40K             0 days 04:34:45
Pace                    0:11:09
TotalSeconds            16485.0
HalfSeconds              8207.0
Name: 25975, dtype: object
Fuzhou
 Age                          48
M/F                           M
City                     Fuzhou
State                       NaN
Country                     CHN
Half            0 days 01:45:30
40K             0 days 03:34:24
Pace                    0:08:41
TotalSeconds            12864.0
HalfSeconds              6330.0
Name: 11161, dtype: object
GREENLAND
 Age                          35
M/F                           M
City                  GREENLAND
State                       NaN
Country                     DEN
Half            0 days 01:25:24
40K             0 days 02:47:08
Pace                    0:06:44
TotalSeconds            10028.0
HalfSeconds              5124.0
Name: 1935, dtype: object
Gadsden
 Age                          45
M/F                           F
City                    Gadsden
State                        AL
Country                     USA
Half            0 days 01:54:48
40K             0 days 03:39:50
Pace                    0:08:51
TotalSeconds            13190.0
HalfSeconds              6888.0
Name: 20980, dtype: object
Gaertringen
 Age                          51
M/F                           M
City                Gaertringen
State                       NaN
Country                     GER
Half            0 days 01:33:27
40K             0 days 02:59:46
Pace                    0:07:22
TotalSeconds            10786.0
HalfSeconds              5607.0
Name: 4727, dtype: object
Gahanna
 Age                          27
M/F                           M
City                    Gahanna
State                        OH
Country                     USA
Half            0 days 01:30:40
40K             0 days 02:55:44
Pace                    0:07:06
TotalSeconds            10544.0
HalfSeconds              5440.0
Name: 5121, dtype: object
Gainesville
 Age                          38
M/F                           M
City                Gainesville
State                        FL
Country                     USA
Half            0 days 01:23:50
40K             0 days 02:42:57
Pace                    0:06:37
TotalSeconds             9777.0
HalfSeconds              5030.0
Name: 1372, dtype: object
Gaithersburg
 Age                          39
M/F                           M
City               Gaithersburg
State                        MD
Country                     USA
Half            0 days 01:33:24
40K             0 days 03:04:00
Pace                    0:07:25
TotalSeconds            11040.0
HalfSeconds              5604.0
Name: 5897, dtype: object
Galena
 Age                          49
M/F                           F
City                     Galena
State                        OH
Country                     USA
Half            0 days 01:53:42
40K             0 days 03:41:13
Pace                    0:08:56
TotalSeconds            13273.0
HalfSeconds              6822.0
Name: 22770, dtype: object
Gales Ferry
 Age                          37
M/F                           F
City                Gales Ferry
State                        CT
Country                     USA
Half            0 days 01:54:46
40K             0 days 03:47:02
Pace                    0:09:11
TotalSeconds            13622.0
HalfSeconds              6886.0
Name: 20049, dtype: object
Galesburg
 Age                          46
M/F                           M
City                  Galesburg
State                        IL
Country                     USA
Half            0 days 02:15:48
40K             0 days 04:36:44
Pace                    0:11:13
TotalSeconds            16604.0
HalfSeconds              8148.0
Name: 30106, dtype: object
Galion
 Age                          48
M/F                           M
City                     Galion
State                        OH
Country                     USA
Half            0 days 01:45:30
40K             0 days 03:37:19
Pace                    0:08:48
TotalSeconds            13039.0
HalfSeconds              6330.0
Name: 12398, dtype: object
Gallipolis
 Age                          33
M/F                           F
City                 Gallipolis
State                        OH
Country                     USA
Half            0 days 01:43:53
40K             0 days 03:32:56
Pace                    0:08:36
TotalSeconds            12776.0
HalfSeconds              6233.0
Name: 13637, dtype: object
Galloway

 Age                          64
M/F                           M
City                   Galloway
State                        OH
Country                     USA
Half            0 days 02:06:35
40K             0 days 04:10:55
Pace                    0:10:08
TotalSeconds            15055.0
HalfSeconds              7595.0
Name: 15543, dtype: object
Gallupville
 Age                          23
M/F                           M
City                Gallupville
State                        NY
Country                     USA
Half            0 days 02:28:07
40K             0 days 05:07:37
Pace                    0:12:24
TotalSeconds            18457.0
HalfSeconds              8887.0
Name: 31400, dtype: object
Galveston
 Age                          35
M/F                           M
City                  Galveston
State                        TX
Country                     USA
Half            0 days 01:50:29
40K             0 days 03:33:47
Pace                    0:08:36
TotalSeconds            12827.0
HalfSeconds              6629.0
Name: 5868, dtype: object
Galway
 Age                          67
M/F                           M
City                     Galway
State                       NaN
Country                     IRL
Half            0 days 01:48:08
40K             0 days 03:28:37
Pace                    0:08:25
TotalSeconds            12517.0
HalfSeconds              6488.0
Name: 19356, dtype: object
Gander
 Age                          48
M/F                           F
City                     Gander
State                        NL
Country                     CAN
Half            0 days 01:56:53
40K             0 days 03:49:07
Pace                    0:09:14
TotalSeconds            13747.0
HalfSeconds              7013.0
Name: 22206, dtype: object
Gansevoort
 Age                          38
M/F                           M
City                 Gansevoort
State                        NY
Country                     USA
Half            0 days 01:29:14
40K             0 days 02:54:20
Pace                    0:07:04
TotalSeconds            10460.0
HalfSeconds              5354.0
Name: 5815, dtype: object
Gardabaer
 Age                          49
M/F                           M
City                  Gardabaer
State                       NaN
Country                     ISL
Half            0 days 01:43:20
40K             0 days 03:20:37
Pace                    0:08:04
TotalSeconds            12037.0
HalfSeconds              6200.0
Name: 9183, dtype: object
Garden
 Age                          22
M/F                           F
City                     Garden
State                        MI
Country                     USA
Half            0 days 01:44:06
40K             0 days 03:31:00
Pace                    0:08:32
TotalSeconds            12660.0
HalfSeconds              6246.0
Name: 15418, dtype: object
Garden City
 Age                          43
M/F                           M
City                Garden City
State                        NY
Country                     USA
Half            0 days 01:43:30
40K             0 days 03:25:08
Pace                    0:08:14
TotalSeconds            12308.0
HalfSeconds              6210.0
Name: 8269, dtype: object
Gardiner
 Age                          40
M/F                           M
City                   Gardiner
State                        ME
Country                     USA
Half            0 days 01:33:41
40K             0 days 03:22:43
Pace                    0:08:11
TotalSeconds            12163.0
HalfSeconds              5621.0
Name: 5273, dtype: object
Gardner
 Age                          43
M/F                           F
City                    Gardner
State                        MA
Country                     USA
Half            0 days 01:51:49
40K             0 days 03:36:24
Pace                    0:08:43
TotalSeconds            12984.0
HalfSeconds              6709.0
Name: 21141, dtype: object
Gardnerville
 Age                          40
M/F                           F
City               Gardnerville
State                        NV
Country                     USA
Half            0 days 01:50:18
40K             0 days 03:46:49
Pace                    0:09:10
TotalSeconds            13609.0
HalfSeconds              6618.0
Name: 20771, dtype: object
Garland
 Age                          29
M/F                           F
City                    Garland
State                        TX
Country                     USA
Half            0 days 01:43:45
40K             0 days 03:28:16
Pace                    0:08:26
TotalSeconds            12496.0
HalfSeconds              6225.0
Name: 17907, dtype: object
Garner
 Age                          33
M/F                           F
City                     Garner
State                        NC
Country                     USA
Half            0 days 02:04:07
40K             0 days 04:43:27
Pace                    0:11:23
TotalSeconds            17007.0
HalfSeconds              7447.0
Name: 29849, dtype: object
Garnerville
 Age                          49
M/F                           F
City                Garnerville
State                        NY
Country                     USA
Half            0 days 01:47:45
40K             0 days 03:44:56
Pace                    0:09:08
TotalSeconds            13496.0
HalfSeconds              6465.0
Name: 12963, dtype: object
Garnet Valley
 Age                          43
M/F                           F
City              Garnet Valley
State                        PA
Country                     USA
Half            0 days 01:46:39
40K             0 days 03:36:20
Pace                    0:08:44
TotalSeconds            12980.0
HalfSeconds              6399.0
Name: 21219, dtype: object
Garrison
 Age                          52
M/F                           M
City                   Garrison
State                        NY
Country                     USA
Half            0 days 01:50:02
40K             0 days 03:45:16
Pace                    0:09:06
TotalSeconds            13516.0
HalfSeconds              6602.0
Name: 14596, dtype: object
Garza Garcia Nuevo Leon
 Age                                  41
M/F                                   M
City            Garza Garcia Nuevo Leon
State                               NaN
Country                             MEX
Half                    0 days 02:03:32
40K                     0 days 04:35:09
Pace                            0:11:06
TotalSeconds                    16509.0
HalfSeconds                      7412.0
Name: 31840, dtype: object
Garza Garcia, N L
 Age                            43
M/F                             M
City            Garza Garcia, N L
State                         NaN
Country                       MEX
Half              0 days 01:53:19
40K               0 days 03:44:02
Pace                      0:09:03
TotalSeconds              13442.0
HalfSeconds                6799.0
Name: 28816, dtype: object
Gastonia
 Age                          56
M/F                           M
City                   Gastonia
State                        NC
Country                     USA
Half            0 days 01:36:17
40K             0 days 03:08:05
Pace                    0:07:35
TotalSeconds            11285.0
HalfSeconds              5777.0
Name: 11241, dtype: object
Gates Mills
 Age                          60
M/F                           M
City                Gates Mills
State                        OH
Country                     USA
Half            0 days 01:33:07
40K             0 days 03:06:07
Pace                    0:07:36
TotalSeconds            11167.0
HalfSeconds              5587.0
Name: 7101, dtype: object
Gatineau
 Age                          27
M/F                           M
City                   Gatineau
State                        QC
Country                     CAN
Half            0 days 01:21:52
40K             0 days 02:41:14
Pace                    0:06:31
TotalSeconds             9674.0
HalfSeconds              4912.0
Name: 912, dtype: object
Gavle
 Age                          56
M/F                           M
City                      Gavle
State                       NaN
Country                     SWE
Half            0 days 01:47:55
40K             0 days 03:29:07
Pace                    0:08:23
TotalSeconds            12547.0
HalfSeconds              6475.0
Name: 17107, dtype: object
Gaylord
 Age                          34
M/F                           M
City                    Gaylord
State                        MI
Country                     USA
Half            0 days 01:33:36
40K             0 days 03:06:32
Pace                    0:07:36
TotalSeconds            11192.0
HalfSeconds              5616.0
Name: 4238, dtype: object
Gechingen
 Age                          52
M/F                           M
City                  Gechingen
State                       NaN
Country                     GER
Half            0 days 01:34:11
40K             0 days 03:06:21
Pace                    0:07:32
TotalSeconds            11181.0
HalfSeconds              5651.0
Name: 6796, dtype: object

Geffen
 Age                          43
M/F                           M
City                     Geffen
State                       NaN
Country                     NED
Half            0 days 01:28:45
40K             0 days 02:56:53
Pace                    0:07:09
TotalSeconds            10613.0
HalfSeconds              5325.0
Name: 3392, dtype: object
Gelsenkirchen
 Age                          53
M/F                           M
City              Gelsenkirchen
State                       NaN
Country                     GER
Half            0 days 01:52:35
40K             0 days 03:51:25
Pace                    0:09:22
TotalSeconds            13885.0
HalfSeconds              6755.0
Name: 30712, dtype: object
Gembloux
 Age                          51
M/F                           M
City                   Gembloux
State                       NaN
Country                     BEL
Half            0 days 01:44:55
40K             0 days 03:41:57
Pace                    0:09:03
TotalSeconds            13317.0
HalfSeconds              6295.0
Name: 31279, dtype: object
Genas
 Age                          37
M/F                           M
City                      Genas
State                       NaN
Country                     FRA
Half            0 days 01:21:05
40K             0 days 02:34:46
Pace                    0:06:14
TotalSeconds             9286.0
HalfSeconds              4865.0
Name: 1101, dtype: object
Geneseo
 Age                          43
M/F                           M
City                    Geneseo
State                        NY
Country                     USA
Half            0 days 01:25:31
40K             0 days 02:46:07
Pace                    0:06:43
TotalSeconds             9967.0
HalfSeconds              5131.0
Name: 1171, dtype: object
Geneva
 Age                          33
M/F                           M
City                     Geneva
State                        IL
Country                     USA
Half            0 days 01:21:07
40K             0 days 02:43:06
Pace                    0:06:35
TotalSeconds             9786.0
HalfSeconds              4867.0
Name: 794, dtype: object
Genova
 Age                          45
M/F                           M
City                     Genova
State                       NaN
Country                     ITA
Half            0 days 01:34:37
40K             0 days 03:04:01
Pace                    0:07:26
TotalSeconds            11041.0
HalfSeconds              5677.0
Name: 31604, dtype: object
George
 Age                          45
M/F                           M
City                     George
State                       NaN
Country                     RSA
Half            0 days 01:22:55
40K             0 days 02:48:41
Pace                    0:06:51
TotalSeconds            10121.0
HalfSeconds              4975.0
Name: 2879, dtype: object
Georgetown
 Age                          51
M/F                           M
City                 Georgetown
State                        KY
Country                     USA
Half            0 days 01:37:54
40K             0 days 03:17:42
Pace                    0:07:55
TotalSeconds            11862.0
HalfSeconds              5874.0
Name: 7424, dtype: object
Geovresset
 Age                          53
M/F                           M
City                 Geovresset
State                       NaN
Country                     FRA
Half            0 days 01:46:35
40K             0 days 03:30:20
Pace                    0:08:28
TotalSeconds            12620.0
HalfSeconds              6395.0
Name: 14675, dtype: object
Gerena (Sevilla)
 Age                           56
M/F                            M
City            Gerena (Sevilla)
State                        NaN
Country                      ESP
Half             0 days 01:37:57
40K              0 days 03:14:07
Pace                     0:07:52
TotalSeconds             11647.0
HalfSeconds               5877.0
Name: 8460, dtype: object
Germantown
 Age                          23
M/F                           M
City                 Germantown
State                        MD
Country                     USA
Half            0 days 01:20:23
40K             0 days 02:48:10
Pace                    0:06:51
TotalSeconds            10090.0
HalfSeconds              4823.0
Name: 476, dtype: object
Germering
 Age                          60
M/F                           M
City                  Germering
State                       NaN
Country                     GER
Half            0 days 01:50:01
40K             0 days 03:39:04
Pace                    0:08:50
TotalSeconds            13144.0
HalfSeconds              6601.0
Name: 20281, dtype: object
Gerogetown
 Age                          46
M/F                           F
City                 Gerogetown
State                        MA
Country                     USA
Half            0 days 02:04:17
40K             0 days 04:02:33
Pace                    0:09:47
TotalSeconds            14553.0
HalfSeconds              7457.0
Name: 28129, dtype: object
Ghent
 Age                          31
M/F                           F
City                      Ghent
State                        NY
Country                     USA
Half            0 days 01:41:54
40K             0 days 03:13:50
Pace                    0:07:48
TotalSeconds            11630.0
HalfSeconds              6114.0
Name: 12037, dtype: object
Gibsonia
 Age                          50
M/F                           F
City                   Gibsonia
State                        PA
Country                     USA
Half            0 days 01:42:42
40K             0 days 03:15:53
Pace                    0:07:53
TotalSeconds            11753.0
HalfSeconds              6162.0
Name: 15229, dtype: object
Gibsonville
 Age                          37
M/F                           F
City                Gibsonville
State                        NC
Country                     USA
Half            0 days 01:43:38
40K             0 days 03:25:33
Pace                    0:08:17
TotalSeconds            12333.0
HalfSeconds              6218.0
Name: 18659, dtype: object
Gig Harbor
 Age                          56
M/F                           F
City                 Gig Harbor
State                        WA
Country                     USA
Half            0 days 02:02:16
40K             0 days 04:02:38
Pace                    0:09:48
TotalSeconds            14558.0
HalfSeconds              7336.0
Name: 25352, dtype: object
Gilbert
 Age                          44
M/F                           M
City                    Gilbert
State                        AZ
Country                     USA
Half            0 days 01:38:53
40K             0 days 03:13:19
Pace                    0:07:48
TotalSeconds            11599.0
HalfSeconds              5933.0
Name: 6864, dtype: object
Gilford
 Age                          54
M/F                           F
City                    Gilford
State                        NH
Country                     USA
Half            0 days 01:44:02
40K             0 days 03:16:10
Pace                    0:07:54
TotalSeconds            11770.0
HalfSeconds              6242.0
Name: 21553, dtype: object
Gilroy
 Age                          40
M/F                           F
City                     Gilroy
State                        CA
Country                     USA
Half            0 days 01:40:53
40K             0 days 03:12:32
Pace                    0:07:46
TotalSeconds            11552.0
HalfSeconds              6053.0
Name: 19743, dtype: object
Gingins
 Age                          43
M/F                           M
City                    Gingins
State                       NaN
Country                     SUI
Half            0 days 01:43:44
40K             0 days 03:32:13
Pace                    0:08:36
TotalSeconds            12733.0
HalfSeconds              6224.0
Name: 7667, dtype: object
Girona
 Age                          56
M/F                           F
City                     Girona
State                       NaN
Country                     ESP
Half            0 days 02:44:19
40K             0 days 05:29:21
Pace                    0:13:17
TotalSeconds            19761.0
HalfSeconds              9859.0
Name: 31676, dtype: object
Giugliano In Campania - Na
 Age                                     58
M/F                                      M
City            Giugliano In Campania - Na
State                                  NaN
Country                                ITA
Half                       0 days 01:39:38
40K                        0 days 03:16:01
Pace                               0:07:55
TotalSeconds                       11761.0
HalfSeconds                         5978.0
Name: 11325, dtype: object
Givatime
 Age                          47
M/F                           M
City                   Givatime
State                       NaN
Country                     ISR
Half            0 days 01:41:55
40K             0 days 03:27:48
Pace                    0:08:26
TotalSeconds            12468.0
HalfSeconds              6115.0
Name: 11441, dtype: object
Gjettum
 Age                          54
M/F                           M
City                    Gjettum
State                       NaN
Country                     NOR
Half            0 days 01:44:58
40K             0 days 03:37:27
Pace                    0:08:48
TotalSeconds            13047.0
HalfSeconds              6298.0
Name: 14601, dtype: object
Gladbeck
 Age                          53
M/F                           M
City                   Gladbeck
State                       NaN
Country                     GER
Half            0 days 02:09:49
40K             0 days 04:43:05
Pace                    0:11:26
TotalSeconds            16985.0
HalfSeconds              7789.0
Name: 31867, dtype: object
Gladstone
 Age                          42
M/F                           F
City                  Gladstone
State                        OR
Country                     USA
Half            0 days 01:54:38
40K             0 days 03:52:44
Pace                    0:09:23
TotalSeconds            13964.0
HalfSeconds              6878.0
Name: 21171, dtype: object
Gladwin
 Age                          63
M/F                           M
City                    Gladwin
State                        MI
Country                     USA
Half            0 days 02:04:44
40K             0 days 04:06:05
Pace                    0:09:56
TotalSeconds            14765.0
HalfSeconds              7484.0
Name: 24213, dtype: object
Gladwyne
 Age                          47
M/F                           F
City                   Gladwyne
State                        PA
Country                     USA
Half            0 days 01:37:49
40K             0 days 03:25:05
Pace                    0:08:23
TotalSeconds            12305.0
HalfSeconds              5869.0
Name: 11572, dtype: object
Glasgow
 Age                          46
M/F                           M
City                    Glasgow
State                       NaN
Country                     GBR
Half            0 days 01:23:41
40K             0 days 02:46:19
Pace                    0:06:44
TotalSeconds             9979.0
HalfSeconds              5021.0
Name: 2120, dtype: object
Glastonbury
 Age                          46
M/F                           M
City                Glastonbury
State                        CT
Country                     USA
Half            0 days 01:30:40
40K             0 days 03:01:26
Pace                    0:07:22
TotalSeconds            10886.0
HalfSeconds              5440.0
Name: 4050, dtype: object
Glen
 Age                          31
M/F                           F
City                       Glen
State                        NH
Country                     USA
Half            0 days 02:05:01
40K             0 days 04:05:11
Pace                    0:09:52
TotalSeconds            14711.0
HalfSeconds              7501.0
Name: 27388, dtype: object
Glen Allen
 Age                          42
M/F                           M
City                 Glen Allen
State                        VA
Country                     USA
Half            0 days 01:26:16
40K             0 days 02:47:19
Pace                    0:06:45
TotalSeconds            10039.0
HalfSeconds              5176.0
Name: 3539, dtype: object
Glen Burnie
 Age                          50
M/F                           M
City                Glen Burnie
State                        MD
Country                     USA
Half            0 days 01:44:37
40K             0 days 03:28:48
Pace                    0:08:27
TotalSeconds            12528.0
HalfSeconds              6277.0
Name: 13256, dtype: object
Glen Carbon
 Age                          42
M/F                           M
City                Glen Carbon
State                        IL
Country                     USA
Half            0 days 01:37:41
40K             0 days 03:18:23
Pace                    0:08:03
TotalSeconds            11903.0
HalfSeconds              5861.0
Name: 7672, dtype: object
Glen Ellyn
 Age                          44
M/F                           M
City                 Glen Ellyn
State                        IL
Country                     USA
Half            0 days 01:29:23
40K             0 days 03:03:42
Pace                    0:07:27
TotalSeconds            11022.0
HalfSeconds              5363.0
Name: 4483, dtype: object
Glen Head
 Age                          39
M/F                           M
City                  Glen Head
State                        NY
Country                     USA
Half            0 days 01:32:27
40K             0 days 02:58:59
Pace                    0:07:12
TotalSeconds            10739.0
HalfSeconds              5547.0
Name: 6678, dtype: object
Glen Mills
 Age                          53
M/F                           M
City                 Glen Mills
State                        PA
Country                     USA
Half            0 days 01:34:37
40K             0 days 03:20:48
Pace                    0:08:09
TotalSeconds            12048.0
HalfSeconds              5677.0
Name: 6188, dtype: object
Glen Ridge
 Age                          40
M/F                           M
City                 Glen Ridge
State                        NJ
Country                     USA
Half            0 days 01:37:48
40K             0 days 03:11:05
Pace                    0:07:42
TotalSeconds            11465.0
HalfSeconds              5868.0
Name: 5978, dtype: object
Glen Rock
 Age                          40
M/F                           M
City                  Glen Rock
State                        PA
Country                     USA
Half            0 days 01:25:39
40K             0 days 02:44:41
Pace                    0:06:39
TotalSeconds             9881.0
HalfSeconds              5139.0
Name: 1816, dtype: object
Glen Williams
 Age                          49
M/F                           M
City              Glen Williams
State                        ON
Country                     CAN
Half            0 days 01:43:56
40K             0 days 03:21:14
Pace                    0:08:05
TotalSeconds            12074.0
HalfSeconds              6236.0
Name: 11443, dtype: object
Glencoe
 Age                          52
M/F                           M
City                    Glencoe
State                        IL
Country                     USA
Half            0 days 01:40:20
40K             0 days 03:35:28
Pace                    0:08:43
TotalSeconds            12928.0
HalfSeconds              6020.0
Name: 7532, dtype: object
Glendale
 Age                          33
M/F                           M
City                   Glendale
State                        NY
Country                     USA
Half            0 days 01:24:13
40K             0 days 02:44:00
Pace                    0:06:36
TotalSeconds             9840.0
HalfSeconds              5053.0
Name: 557, dtype: object
Glenelg
 Age                          38
M/F                           M
City                    Glenelg
State                        MD
Country                     USA
Half            0 days 01:26:40
40K             0 days 02:48:38
Pace                    0:06:48
TotalSeconds            10118.0
HalfSeconds              5200.0
Name: 4525, dtype: object
Glenmont
 Age                          34
M/F                           M
City                   Glenmont
State                        NY
Country                     USA
Half            0 days 01:22:31
40K             0 days 02:43:56
Pace                    0:06:38
TotalSeconds             9836.0
HalfSeconds              4951.0
Name: 1531, dtype: object
Glenmoore
 Age                          23
M/F                           F
City                  Glenmoore
State                        PA
Country                     USA
Half            0 days 01:47:18
40K             0 days 03:28:40
Pace                    0:08:25
TotalSeconds            12520.0
HalfSeconds              6438.0
Name: 11432, dtype: object
Glenn Dale
 Age                          36
M/F                           M
City                 Glenn Dale
State                        MD
Country                     USA
Half            0 days 01:22:12
40K             0 days 02:42:44
Pace                    0:06:35
TotalSeconds             9764.0
HalfSeconds              4932.0

Name: 522, dtype: object
Glenshaw
 Age                          47
M/F                           M
City                   Glenshaw
State                        PA
Country                     USA
Half            0 days 01:27:03
40K             0 days 02:51:47
Pace                    0:06:55
TotalSeconds            10307.0
HalfSeconds              5223.0
Name: 4404, dtype: object
Glenside
 Age                          40
M/F                           M
City                   Glenside
State                        PA
Country                     USA
Half            0 days 01:25:20
40K             0 days 02:48:17
Pace                    0:06:47
TotalSeconds            10097.0
HalfSeconds              5120.0
Name: 1258, dtype: object
Glenview
 Age                          23
M/F                           M
City                   Glenview
State                        IL
Country                     USA
Half            0 days 01:24:10
40K             0 days 02:53:42
Pace                    0:07:03
TotalSeconds            10422.0
HalfSeconds              5050.0
Name: 1906, dtype: object
Glenville
 Age                          24
M/F                           M
City                  Glenville
State                        NY
Country                     USA
Half            0 days 01:18:44
40K             0 days 02:40:24
Pace                    0:06:28
TotalSeconds             9624.0
HalfSeconds              4724.0
Name: 290, dtype: object
Glenwood
 Age                          62
M/F                           F
City                   Glenwood
State                        MD
Country                     USA
Half            0 days 01:59:16
40K             0 days 03:57:13
Pace                    0:09:41
TotalSeconds            14233.0
HalfSeconds              7156.0
Name: 25668, dtype: object
Gloucester
 Age                          43
M/F                           M
City                 Gloucester
State                        MA
Country                     USA
Half            0 days 01:25:09
40K             0 days 02:49:33
Pace                    0:06:52
TotalSeconds            10173.0
HalfSeconds              5109.0
Name: 1295, dtype: object
Glover
 Age                          32
M/F                           F
City                     Glover
State                        VT
Country                     USA
Half            0 days 01:28:13
40K             0 days 02:47:22
Pace                    0:06:44
TotalSeconds            10042.0
HalfSeconds              5293.0
Name: 1106, dtype: object
Gloversville
 Age                          43
M/F                           F
City               Gloversville
State                        NY
Country                     USA
Half            0 days 01:41:53
40K             0 days 03:27:55
Pace                    0:08:23
TotalSeconds            12475.0
HalfSeconds              6113.0
Name: 14667, dtype: object
Goderich
 Age                          60
M/F                           M
City                   Goderich
State                        ON
Country                     CAN
Half            0 days 01:26:49
40K             0 days 02:47:51
Pace                    0:06:46
TotalSeconds            10071.0
HalfSeconds              5209.0
Name: 2507, dtype: object
Goettingen
 Age                          32
M/F                           F
City                 Goettingen
State                       NaN
Country                     GER
Half            0 days 01:54:31
40K             0 days 03:44:12
Pace                    0:09:02
TotalSeconds            13452.0
HalfSeconds              6871.0
Name: 31778, dtype: object
Goffstown
 Age                          42
M/F                           F
City                  Goffstown
State                        NH
Country                     USA
Half            0 days 01:37:25
40K             0 days 03:07:52
Pace                    0:07:34
TotalSeconds            11272.0
HalfSeconds              5845.0
Name: 8302, dtype: object
Goiania
 Age                          53
M/F                           M
City                    Goiania
State                       NaN
Country                     BRA
Half            0 days 01:33:15
40K             0 days 03:06:28
Pace                    0:07:32
TotalSeconds            11188.0
HalfSeconds              5595.0
Name: 7146, dtype: object
Goiania - Go
 Age                          47
M/F                           M
City               Goiania - Go
State                       NaN
Country                     BRA
Half            0 days 01:34:44
40K             0 days 03:05:37
Pace                    0:07:31
TotalSeconds            11137.0
HalfSeconds              5684.0
Name: 9610, dtype: object
Gold Beach
 Age                          32
M/F                           F
City                 Gold Beach
State                        OR
Country                     USA
Half            0 days 01:44:56
40K             0 days 03:23:40
Pace                    0:08:14
TotalSeconds            12220.0
HalfSeconds              6296.0
Name: 17460, dtype: object
Gold Hill
 Age                          36
M/F                           F
City                  Gold Hill
State                        OR
Country                     USA
Half            0 days 01:48:01
40K             0 days 03:37:06
Pace                    0:08:47
TotalSeconds            13026.0
HalfSeconds              6481.0
Name: 16365, dtype: object
Golden
 Age                          50
M/F                           M
City                     Golden
State                        CO
Country                     USA
Half            0 days 01:17:17
40K             0 days 02:31:20
Pace                    0:06:06
TotalSeconds             9080.0
HalfSeconds              4637.0
Name: 291, dtype: object
Golden Beach
 Age                          24
M/F                           F
City               Golden Beach
State                        FL
Country                     USA
Half            0 days 01:31:21
40K             0 days 03:15:04
Pace                    0:07:57
TotalSeconds            11704.0
HalfSeconds              5481.0
Name: 6311, dtype: object
Golden Valley
 Age                          31
M/F                           F
City              Golden Valley
State                        MN
Country                     USA
Half            0 days 01:46:27
40K             0 days 03:38:48
Pace                    0:08:50
TotalSeconds            13128.0
HalfSeconds              6387.0
Name: 17144, dtype: object
Goldendale
 Age                          36
M/F                           F
City                 Goldendale
State                        WA
Country                     USA
Half            0 days 01:39:09
40K             0 days 03:18:52
Pace                    0:08:04
TotalSeconds            11932.0
HalfSeconds              5949.0
Name: 10514, dtype: object
Goldsboro
 Age                          59
M/F                           M
City                  Goldsboro
State                        NC
Country                     USA
Half            0 days 01:40:45
40K             0 days 03:15:34
Pace                    0:07:54
TotalSeconds            11734.0
HalfSeconds              6045.0
Name: 14261, dtype: object
Goleta
 Age                          33
M/F                           M
City                     Goleta
State                        CA
Country                     USA
Half            0 days 01:11:44
40K             0 days 02:23:54
Pace                    0:05:50
TotalSeconds             8634.0
HalfSeconds              4304.0
Name: 41, dtype: object
Golf
 Age                          48
M/F                           F
City                       Golf
State                        IL
Country                     USA
Half            0 days 01:53:22
40K             0 days 03:40:27
Pace                    0:08:54
TotalSeconds            13227.0
HalfSeconds              6802.0
Name: 21661, dtype: object
Gond Pontouvre
 Age                          63
M/F                           F
City             Gond Pontouvre
State                       NaN
Country                     FRA
Half            0 days 01:53:59
40K             0 days 03:46:14
Pace                    0:09:08
TotalSeconds            13574.0
HalfSeconds              6839.0
Name: 22431, dtype: object
Gonnet
 Age                          53
M/F                           M
City                     Gonnet
State                       NaN
Country                     ARG
Half            0 days 01:43:42
40K             0 days 03:19:13
Pace                    0:08:00
TotalSeconds            11953.0
HalfSeconds              6222.0
Name: 6751, dtype: object
Gonzales
 Age                          20
M/F                           M
City                   Gonzales
State                        LA
Country                     USA
Half            0 days 01:28:55
40K             0 days 03:08:09
Pace                    0:07:39
TotalSeconds            11289.0
HalfSeconds              5335.0
Name: 2509, dtype: object

Goodrich
 Age                          47
M/F                           M
City                   Goodrich
State                        MI
Country                     USA
Half            0 days 01:34:33
40K             0 days 03:11:41
Pace                    0:07:46
TotalSeconds            11501.0
HalfSeconds              5673.0
Name: 7013, dtype: object
Goodyear
 Age                          44
M/F                           M
City                   Goodyear
State                        AZ
Country                     USA
Half            0 days 01:28:35
40K             0 days 02:53:57
Pace                    0:07:03
TotalSeconds            10437.0
HalfSeconds              5315.0
Name: 5600, dtype: object
Goodyer
 Age                          51
M/F                           M
City                    Goodyer
State                        AZ
Country                     USA
Half            0 days 02:02:03
40K             0 days 04:26:51
Pace                    0:10:50
TotalSeconds            16011.0
HalfSeconds              7323.0
Name: 9598, dtype: object
Goreville
 Age                          41
M/F                           M
City                  Goreville
State                        IL
Country                     USA
Half            0 days 01:34:20
40K             0 days 03:16:31
Pace                    0:08:04
TotalSeconds            11791.0
HalfSeconds              5660.0
Name: 8700, dtype: object
Gorham
 Age                          28
M/F                           M
City                     Gorham
State                        ME
Country                     USA
Half            0 days 01:17:02
40K             0 days 02:35:46
Pace                    0:06:19
TotalSeconds             9346.0
HalfSeconds              4622.0
Name: 331, dtype: object
Gorinchem
 Age                          49
M/F                           F
City                  Gorinchem
State                       NaN
Country                     NED
Half            0 days 01:39:54
40K             0 days 03:11:29
Pace                    0:07:42
TotalSeconds            11489.0
HalfSeconds              5994.0
Name: 10935, dtype: object
Goshen
 Age                          43
M/F                           M
City                     Goshen
State                        NY
Country                     USA
Half            0 days 01:24:53
40K             0 days 02:51:06
Pace                    0:06:57
TotalSeconds            10266.0
HalfSeconds              5093.0
Name: 2083, dtype: object
Goteborg
 Age                          44
M/F                           M
City                   Goteborg
State                       NaN
Country                     SWE
Half            0 days 01:54:53
40K             0 days 03:47:04
Pace                    0:09:06
TotalSeconds            13624.0
HalfSeconds              6893.0
Name: 29156, dtype: object
Gotha
 Age                          46
M/F                           M
City                      Gotha
State                        FL
Country                     USA
Half            0 days 01:45:25
40K             0 days 03:39:07
Pace                    0:08:52
TotalSeconds            13147.0
HalfSeconds              6325.0
Name: 11186, dtype: object
Gothenburg
 Age                          36
M/F                           M
City                 Gothenburg
State                       NaN
Country                     SWE
Half            0 days 01:51:22
40K             0 days 04:04:15
Pace                    0:09:54
TotalSeconds            14655.0
HalfSeconds              6682.0
Name: 6521, dtype: object
Gottingen
 Age                          36
M/F                           F
City                  Gottingen
State                       NaN
Country                     GER
Half            0 days 01:49:31
40K             0 days 03:38:48
Pace                    0:08:51
TotalSeconds            13128.0
HalfSeconds              6571.0
Name: 12603, dtype: object
Goulds
 Age                          52
M/F                           M
City                     Goulds
State                        NL
Country                     CAN
Half            0 days 01:39:16
40K             0 days 03:19:24
Pace                    0:08:03
TotalSeconds            11964.0
HalfSeconds              5956.0
Name: 12149, dtype: object
Grabo
 Age                          55
M/F                           M
City                      Grabo
State                       NaN
Country                     SWE
Half            0 days 01:54:39
40K             0 days 04:01:39
Pace                    0:09:52
TotalSeconds            14499.0
HalfSeconds              6879.0
Name: 20200, dtype: object
Grafton
 Age                          41
M/F                           M
City                    Grafton
State                        WI
Country                     USA
Half            0 days 01:30:35
40K             0 days 02:56:54
Pace                    0:07:11
TotalSeconds            10614.0
HalfSeconds              5435.0
Name: 4557, dtype: object
Graham
 Age                          56
M/F                           M
City                     Graham
State                        WA
Country                     USA
Half            0 days 01:49:51
40K             0 days 03:39:57
Pace                    0:08:53
TotalSeconds            13197.0
HalfSeconds              6591.0
Name: 17779, dtype: object
Granada
 Age                          40
M/F                           F
City                    Granada
State                        MN
Country                     USA
Half            0 days 01:46:00
40K             0 days 03:26:34
Pace                    0:08:19
TotalSeconds            12394.0
HalfSeconds              6360.0
Name: 14270, dtype: object
Granada Hills
 Age                          53
M/F                           M
City              Granada Hills
State                        CA
Country                     USA
Half            0 days 01:31:19
40K             0 days 03:02:10
Pace                    0:07:21
TotalSeconds            10930.0
HalfSeconds              5479.0
Name: 5620, dtype: object
Granbury
 Age                          55
M/F                           M
City                   Granbury
State                        TX
Country                     USA
Half            0 days 01:48:27
40K             0 days 03:33:51
Pace                    0:08:40
TotalSeconds            12831.0
HalfSeconds              6507.0
Name: 13951, dtype: object
Granby
 Age                          41
M/F                           F
City                     Granby
State                        QC
Country                     CAN
Half            0 days 01:37:21
40K             0 days 03:08:48
Pace                    0:07:37
TotalSeconds            11328.0
HalfSeconds              5841.0
Name: 12548, dtype: object
Grand Blanc
 Age                          20
M/F                           M
City                Grand Blanc
State                        MI
Country                     USA
Half            0 days 01:12:34
40K             0 days 02:30:55
Pace                    0:06:09
TotalSeconds             9055.0
HalfSeconds              4354.0
Name: 251, dtype: object
Grand Cayman
 Age                          48
M/F                           M
City               Grand Cayman
State                       NaN
Country                     CAY
Half            0 days 02:06:06
40K             0 days 04:20:58
Pace                    0:10:29
TotalSeconds            15658.0
HalfSeconds              7566.0
Name: 30731, dtype: object
Grand Forks
 Age                          32
M/F                           M
City                Grand Forks
State                        ND
Country                     USA
Half            0 days 01:29:18
40K             0 days 02:59:24
Pace                    0:07:16
TotalSeconds            10764.0
HalfSeconds              5358.0
Name: 5372, dtype: object
Grand Haven
 Age                          26
M/F                           M
City                Grand Haven
State                        MI
Country                     USA
Half            0 days 01:20:33
40K             0 days 02:44:47
Pace                    0:06:41
TotalSeconds             9887.0
HalfSeconds              4833.0
Name: 344, dtype: object
Grand Junction
 Age                          57
M/F                           M
City             Grand Junction
State                        CO
Country                     USA
Half            0 days 01:45:25
40K             0 days 03:25:42
Pace                    0:08:18
TotalSeconds            12342.0
HalfSeconds              6325.0
Name: 9234, dtype: object
Grand Ledge
 Age                          51
M/F                           M
City                Grand Ledge
State                        MI
Country                     USA
Half            0 days 02:06:46
40K             0 days 04:06:17
Pace                    0:09:53
TotalSeconds            14777.0
HalfSeconds              7606.0
Name: 25767, dtype: object
Grand Prairie
 Age                          45
M/F                           M
City              Grand Prairie
State                        TX
Country                     USA
Half            0 days 01:24:13
40K             0 days 02:46:56
Pace                    0:06:45
TotalSeconds            10016.0
HalfSeconds              5053.0
Name: 2465, dtype: object
Grand Rapids
 Age                          41
M/F                           M
City               Grand Rapids
State                        MI
Country                     USA
Half            0 days 01:20:01
40K             0 days 02:33:35
Pace                    0:06:12
TotalSeconds             9215.0
HalfSeconds              4801.0
Name: 283, dtype: object
Grand River
 Age                          51
M/F                           F
City                Grand River
State                        NS
Country                     CAN
Half            0 days 01:53:10
40K             0 days 03:42:12
Pace                    0:08:58
TotalSeconds            13332.0
HalfSeconds              6790.0
Name: 24259, dtype: object
Grande Prairie
 Age                          47
M/F                           F
City             Grande Prairie
State                        AB
Country                     CAN
Half            0 days 01:53:46
40K             0 days 03:50:37
Pace                    0:09:18
TotalSeconds            13837.0
HalfSeconds              6826.0
Name: 22564, dtype: object
Grande-Digue
 Age                          31
M/F                           F
City               Grande-Digue
State                        NB
Country                     CAN
Half            0 days 01:47:19
40K             0 days 03:39:22
Pace                    0:08:50
TotalSeconds            13162.0
HalfSeconds              6439.0
Name: 15029, dtype: object
Grandview
 Age                          37
M/F                           M
City                  Grandview
State                        MO
Country                     USA
Half            0 days 01:27:53
40K             0 days 02:58:22
Pace                    0:07:17
TotalSeconds            10702.0
HalfSeconds              5273.0
Name: 4360, dtype: object
Grandview Heights
 Age                            34
M/F                             F
City            Grandview Heights
State                          OH
Country                       USA
Half              0 days 01:50:55
40K               0 days 03:36:17
Pace                      0:08:42
TotalSeconds              12977.0
HalfSeconds                6655.0
Name: 16790, dtype: object
Grandville
 Age                          48
M/F                           M
City                 Grandville
State                        MI
Country                     USA
Half            0 days 01:26:50
40K             0 days 02:47:15
Pace                    0:06:45
TotalSeconds            10035.0
HalfSeconds              5210.0
Name: 1084, dtype: object
Granger
 Age                          30
M/F                           F
City                    Granger
State                        IN
Country                     USA
Half            0 days 01:49:03
40K             0 days 03:34:24
Pace                    0:08:39
TotalSeconds            12864.0
HalfSeconds              6543.0
Name: 17190, dtype: object
Granite Bay
 Age                          43
M/F                           F
City                Granite Bay
State                        CA
Country                     USA
Half            0 days 01:52:31
40K             0 days 03:49:59
Pace                    0:09:16
TotalSeconds            13799.0
HalfSeconds              6751.0
Name: 17486, dtype: object
Grant
 Age                          62
M/F                           F
City                      Grant
State                        MI
Country                     USA
Half            0 days 02:07:32
40K             0 days 04:11:48
Pace                    0:10:07
TotalSeconds            15108.0
HalfSeconds              7652.0
Name: 25833, dtype: object
Grantham
 Age                          54
M/F                           M
City                   Grantham
State                        NH
Country                     USA
Half            0 days 01:41:28
40K             0 days 03:26:22
Pace                    0:08:20
TotalSeconds            12382.0
HalfSeconds              6088.0
Name: 6787, dtype: object
Grants Pass
 Age                          26
M/F                           F
City                Grants Pass
State                        OR
Country                     USA
Half            0 days 01:40:43
40K             0 days 03:11:59
Pace                    0:07:44
TotalSeconds            11519.0
HalfSeconds              6043.0
Name: 14289, dtype: object
Grantsville
 Age                          46
M/F                           M
City                Grantsville
State                        UT
Country                     USA
Half            0 days 01:41:10
40K             0 days 03:24:10
Pace                    0:08:15
TotalSeconds            12250.0
HalfSeconds              6070.0
Name: 12407, dtype: object
Granville
 Age                          35
M/F                           M
City                  Granville
State                        NY
Country                     USA
Half            0 days 01:34:27
40K             0 days 03:34:33
Pace                    0:08:44
TotalSeconds            12873.0
HalfSeconds              5667.0
Name: 2814, dtype: object
Grapevine
 Age                          31
M/F                           F
City                  Grapevine
State                        TX
Country                     USA
Half            0 days 01:34:13
40K             0 days 03:21:11
Pace                    0:08:11
TotalSeconds            12071.0
HalfSeconds              5653.0
Name: 8976, dtype: object
Grass Lake
 Age                          28
M/F                           F
City                 Grass Lake
State                        MI
Country                     USA
Half            0 days 01:40:05
40K             0 days 03:16:12
Pace                    0:07:55
TotalSeconds            11772.0
HalfSeconds              6005.0
Name: 11425, dtype: object
Gray
 Age                          36
M/F                           M
City                       Gray
State                        LA
Country                     USA
Half            0 days 01:24:42
40K             0 days 02:45:15
Pace                    0:06:41
TotalSeconds             9915.0
HalfSeconds              5082.0
Name: 3849, dtype: object
Grayslake
 Age                          35
M/F                           M
City                  Grayslake
State                        IL
Country                     USA
Half            0 days 01:24:51
40K             0 days 02:48:41
Pace                    0:06:49
TotalSeconds            10121.0
HalfSeconds              5091.0
Name: 1594, dtype: object
Graz
 Age                          34
M/F                           M
City                       Graz
State                       NaN
Country                     AUT
Half            0 days 01:29:25
40K             0 days 03:02:08
Pace                    0:07:21
TotalSeconds            10928.0
HalfSeconds              5365.0
Name: 3087, dtype: object
Great Falls
 Age                          45
M/F                           M
City                Great Falls
State                        VA
Country                     USA
Half            0 days 01:40:22
40K             0 days 03:25:38
Pace                    0:08:24
TotalSeconds            12338.0
HalfSeconds              6022.0
Name: 10171, dtype: object
Great Mills
 Age                          35
M/F                           M
City                Great Mills
State                        MD
Country                     USA
Half            0 days 01:47:08
40K             0 days 03:41:35
Pace                    0:08:57
TotalSeconds            13295.0
HalfSeconds              6428.0
Name: 5946, dtype: object
Great Neck
 Age                          55
M/F                           M
City                 Great Neck
State                        NY
Country                     USA
Half            0 days 01:40:39
40K             0 days 03:14:10
Pace                    0:07:50
TotalSeconds            11650.0
HalfSeconds              6039.0
Name: 19238, dtype: object
Great River
 Age                          56
M/F                           M
City                Great River
State                        NY
Country                     USA
Half            0 days 01:51:02
40K             0 days 03:41:14
Pace                    0:08:58
TotalSeconds            13274.0
HalfSeconds              6662.0
Name: 18276, dtype: object
Greely
 Age                          54
M/F                           M
City                     Greely
State                        ON
Country                     CAN
Half            0 days 01:29:53
40K             0 days 02:53:31
Pace                    0:07:00
TotalSeconds            10411.0
HalfSeconds              5393.0
Name: 3660, dtype: object
Green Bay
 Age                          41
M/F                           M
City                  Green Bay
State                        WI
Country                     USA
Half            0 days 01:21:05
40K             0 days 02:54:37
Pace                    0:07:03
TotalSeconds            10477.0
HalfSeconds              4865.0
Name: 788, dtype: object
Green Cove Springs
 Age                             59
M/F                              F
City            Green Cove Springs
State                           FL
Country                        USA
Half               0 days 02:04:15
40K                0 days 04:15:07
Pace                       0:10:20
TotalSeconds               15307.0
HalfSeconds                 7455.0

Name: 25383, dtype: object
Green Harbor
 Age                          56
M/F                           M
City               Green Harbor
State                        MA
Country                     USA
Half            0 days 02:42:03
40K             0 days 05:10:11
Pace                    0:12:28
TotalSeconds            18611.0
HalfSeconds              9723.0
Name: 27501, dtype: object
Green Lane
 Age                          38
M/F                           M
City                 Green Lane
State                        PA
Country                     USA
Half            0 days 01:26:32
40K             0 days 02:49:20
Pace                    0:06:50
TotalSeconds            10160.0
HalfSeconds              5192.0
Name: 2706, dtype: object
Greencastle
 Age                          49
M/F                           M
City                Greencastle
State                        PA
Country                     USA
Half            0 days 01:41:10
40K             0 days 03:24:29
Pace                    0:08:18
TotalSeconds            12269.0
HalfSeconds              6070.0
Name: 11529, dtype: object
Greene
 Age                          28
M/F                           M
City                     Greene
State                        NY
Country                     USA
Half            0 days 01:30:32
40K             0 days 02:57:14
Pace                    0:07:09
TotalSeconds            10634.0
HalfSeconds              5432.0
Name: 2658, dtype: object
Greeneville
 Age                          50
M/F                           M
City                Greeneville
State                        TN
Country                     USA
Half            0 days 01:35:17
40K             0 days 02:58:27
Pace                    0:07:11
TotalSeconds            10707.0
HalfSeconds              5717.0
Name: 3329, dtype: object
Greenfield
 Age                          53
M/F                           M
City                 Greenfield
State                        MN
Country                     USA
Half            0 days 01:20:31
40K             0 days 02:49:31
Pace                    0:07:01
TotalSeconds            10171.0
HalfSeconds              4831.0
Name: 477, dtype: object
Greenfield Park
 Age                          56
M/F                           M
City            Greenfield Park
State                        QC
Country                     CAN
Half            0 days 01:35:32
40K             0 days 03:04:22
Pace                    0:07:27
TotalSeconds            11062.0
HalfSeconds              5732.0
Name: 10060, dtype: object
Greenfield Township
 Age                              44
M/F                               M
City            Greenfield Township
State                            PA
Country                         USA
Half                0 days 01:37:52
40K                 0 days 03:08:15
Pace                        0:07:37
TotalSeconds                11295.0
HalfSeconds                  5872.0
Name: 7116, dtype: object
Greenfieldpark
 Age                          61
M/F                           M
City             Greenfieldpark
State                        QC
Country                     CAN
Half            0 days 01:58:33
40K             0 days 03:53:46
Pace                    0:09:26
TotalSeconds            14026.0
HalfSeconds              7113.0
Name: 23128, dtype: object
Greenland
 Age                          55
M/F                           M
City                  Greenland
State                        NH
Country                     USA
Half            0 days 01:49:45
40K             0 days 03:29:04
Pace                    0:08:24
TotalSeconds            12544.0
HalfSeconds              6585.0
Name: 17500, dtype: object
Greenlawn
 Age                          28
M/F                           F
City                  Greenlawn
State                        NY
Country                     USA
Half            0 days 01:50:03
40K             0 days 04:07:45
Pace                    0:09:59
TotalSeconds            14865.0
HalfSeconds              6603.0
Name: 17851, dtype: object
Greensboro
 Age                          33
M/F                           M
City                 Greensboro
State                        NC
Country                     USA
Half            0 days 01:21:46
40K             0 days 02:38:19
Pace                    0:06:24
TotalSeconds             9499.0
HalfSeconds              4906.0
Name: 1017, dtype: object
Greensburg
 Age                          24
M/F                           F
City                 Greensburg
State                        PA
Country                     USA
Half            0 days 01:53:55
40K             0 days 04:02:42
Pace                    0:09:53
TotalSeconds            14562.0
HalfSeconds              6835.0
Name: 17530, dtype: object
Greenup
 Age                          49
M/F                           F
City                    Greenup
State                        KY
Country                     USA
Half            0 days 01:59:32
40K             0 days 03:52:36
Pace                    0:09:24
TotalSeconds            13956.0
HalfSeconds              7172.0
Name: 23112, dtype: object
Greenville
 Age                          27
M/F                           M
City                 Greenville
State                        SC
Country                     USA
Half            0 days 01:26:50
40K             0 days 02:47:26
Pace                    0:06:46
TotalSeconds            10046.0
HalfSeconds              5210.0
Name: 2231, dtype: object
Greenwich
 Age                          40
M/F                           M
City                  Greenwich
State                        CT
Country                     USA
Half            0 days 01:35:08
40K             0 days 03:02:59
Pace                    0:07:24
TotalSeconds            10979.0
HalfSeconds              5708.0
Name: 5509, dtype: object
Greenwood
 Age                          50
M/F                           M
City                  Greenwood
State                        IN
Country                     USA
Half            0 days 01:36:20
40K             0 days 03:14:04
Pace                    0:07:51
TotalSeconds            11644.0
HalfSeconds              5780.0
Name: 5968, dtype: object
Greenwood Village
 Age                            46
M/F                             M
City            Greenwood Village
State                          CO
Country                       USA
Half              0 days 01:29:22
40K               0 days 03:10:23
Pace                      0:07:44
TotalSeconds              11423.0
HalfSeconds                5362.0
Name: 3501, dtype: object
Greer
 Age                          60
M/F                           M
City                      Greer
State                        SC
Country                     USA
Half            0 days 01:29:51
40K             0 days 02:55:43
Pace                    0:07:06
TotalSeconds            10543.0
HalfSeconds              5391.0
Name: 4493, dtype: object
Gregory
 Age                          28
M/F                           F
City                    Gregory
State                        MI
Country                     USA
Half            0 days 02:07:26
40K             0 days 04:21:15
Pace                    0:10:33
TotalSeconds            15675.0
HalfSeconds              7646.0
Name: 18205, dtype: object
Grenville Sur La Rouge
 Age                                 52
M/F                                  F
City            Grenville Sur La Rouge
State                               QC
Country                            CAN
Half                   0 days 01:59:31
40K                    0 days 03:55:39
Pace                           0:09:29
TotalSeconds                   14139.0
HalfSeconds                     7171.0
Name: 22209, dtype: object
Gresham
 Age                          49
M/F                           F
City                    Gresham
State                        OR
Country                     USA
Half            0 days 01:44:35
40K             0 days 03:25:40
Pace                    0:08:19
TotalSeconds            12340.0
HalfSeconds              6275.0
Name: 17982, dtype: object
Griffin
 Age                          52
M/F                           F
City                    Griffin
State                        GA
Country                     USA
Half            0 days 01:56:03
40K             0 days 03:46:49
Pace                    0:09:09
TotalSeconds            13609.0
HalfSeconds              6963.0
Name: 24272, dtype: object

Grimsby
 Age                          37
M/F                           M
City                    Grimsby
State                        ON
Country                     CAN
Half            0 days 01:57:45
40K             0 days 03:52:56
Pace                    0:09:31
TotalSeconds            13976.0
HalfSeconds              7065.0
Name: 30371, dtype: object
Grimsby, N.e. Lincs
 Age                              56
M/F                               M
City            Grimsby, N.e. Lincs
State                           NaN
Country                         GBR
Half                0 days 01:49:32
40K                 0 days 03:39:56
Pace                        0:08:53
TotalSeconds                13196.0
HalfSeconds                  6572.0
Name: 11939, dtype: object
Grinnell
 Age                          24
M/F                           F
City                   Grinnell
State                        IA
Country                     USA
Half            0 days 01:32:24
40K             0 days 03:00:13
Pace                    0:07:17
TotalSeconds            10813.0
HalfSeconds              5544.0
Name: 13773, dtype: object
Griswold
 Age                          38
M/F                           M
City                   Griswold
State                        CT
Country                     USA
Half            0 days 02:02:27
40K             0 days 04:12:28
Pace                    0:10:13
TotalSeconds            15148.0
HalfSeconds              7347.0
Name: 30771, dtype: object
Groningen
 Age                          47
M/F                           M
City                  Groningen
State                       NaN
Country                     NED
Half            0 days 01:53:09
40K             0 days 04:10:48
Pace                    0:10:04
TotalSeconds            15048.0
HalfSeconds              6789.0
Name: 10886, dtype: object
Grose Pte
 Age                          40
M/F                           M
City                  Grose Pte
State                        MI
Country                     USA
Half            0 days 01:48:58
40K             0 days 03:32:39
Pace                    0:08:37
TotalSeconds            12759.0
HalfSeconds              6538.0
Name: 29207, dtype: object
Grosse Ile
 Age                          49
M/F                           M
City                 Grosse Ile
State                        MI
Country                     USA
Half            0 days 01:29:34
40K             0 days 02:57:34
Pace                    0:07:14
TotalSeconds            10654.0
HalfSeconds              5374.0
Name: 5332, dtype: object
Grosse Point
 Age                          23
M/F                           F
City               Grosse Point
State                        MI
Country                     USA
Half            0 days 02:23:54
40K             0 days 05:02:23
Pace                    0:12:12
TotalSeconds            18143.0
HalfSeconds              8634.0
Name: 28380, dtype: object
Grosse Pointe Farms
 Age                              45
M/F                               F
City            Grosse Pointe Farms
State                            MI
Country                         USA
Half                0 days 01:49:07
40K                 0 days 03:33:20
Pace                        0:08:36
TotalSeconds                12800.0
HalfSeconds                  6547.0
Name: 20301, dtype: object
Grosse Pointe Park
 Age                             46
M/F                              F
City            Grosse Pointe Park
State                           MI
Country                        USA
Half               0 days 01:51:57
40K                0 days 03:40:40
Pace                       0:08:54
TotalSeconds               13240.0
HalfSeconds                 6717.0
Name: 21279, dtype: object
Grosse Pointe Shores
 Age                               37
M/F                                F
City            Grosse Pointe Shores
State                             MI
Country                          USA
Half                 0 days 01:54:53
40K                  0 days 04:34:44
Pace                         0:11:11
TotalSeconds                 16484.0
HalfSeconds                   6893.0
Name: 18742, dtype: object
Grosse Pointe Woods
 Age                              31
M/F                               F
City            Grosse Pointe Woods
State                            MI
Country                         USA
Half                0 days 01:29:30
40K                 0 days 02:54:01
Pace                        0:07:01
TotalSeconds                10441.0
HalfSeconds                  5370.0
Name: 4570, dtype: object
Groton
 Age                          23
M/F                           M
City                     Groton
State                        CT
Country                     USA
Half            0 days 01:21:35
40K             0 days 03:06:34
Pace                    0:07:36
TotalSeconds            11194.0
HalfSeconds              4895.0
Name: 846, dtype: object
Grove City
 Age                          21
M/F                           M
City                 Grove City
State                        PA
Country                     USA
Half            0 days 01:27:38
40K             0 days 02:51:49
Pace                    0:07:00
TotalSeconds            10309.0
HalfSeconds              5258.0
Name: 2601, dtype: object
Grovedale
 Age                          51
M/F                           F
City                  Grovedale
State                        AB
Country                     CAN
Half            0 days 01:52:27
40K             0 days 03:44:21
Pace                    0:09:03
TotalSeconds            13461.0
HalfSeconds              6747.0
Name: 24405, dtype: object
Groveland
 Age                          30
M/F                           F
City                  Groveland
State                        FL
Country                     USA
Half            0 days 01:41:57
40K             0 days 03:16:57
Pace                    0:08:00
TotalSeconds            11817.0
HalfSeconds              6117.0
Name: 14407, dtype: object
Groves
 Age                          61
M/F                           M
City                     Groves
State                        TX
Country                     USA
Half            0 days 02:03:36
40K             0 days 04:16:35
Pace                    0:10:20
TotalSeconds            15395.0
HalfSeconds              7416.0
Name: 21163, dtype: object
Guadalajara
 Age                          33
M/F                           M
City                Guadalajara
State                       NaN
Country                     MEX
Half            0 days 01:22:23
40K             0 days 02:41:52
Pace                    0:06:33
TotalSeconds             9712.0
HalfSeconds              4943.0
Name: 1510, dtype: object
Guadalajara, Jalisco
 Age                               42
M/F                                M
City            Guadalajara, Jalisco
State                            NaN
Country                          MEX
Half                 0 days 01:34:29
40K                  0 days 03:08:27
Pace                         0:07:39
TotalSeconds                 11307.0
HalfSeconds                   5669.0
Name: 6963, dtype: object
Guadalupe
 Age                          52
M/F                           M
City                  Guadalupe
State                       NaN
Country                     MEX
Half            0 days 01:40:05
40K             0 days 03:29:05
Pace                    0:08:28
TotalSeconds            12545.0
HalfSeconds              6005.0
Name: 13423, dtype: object
Guadalupe, Zacatecas
 Age                               57
M/F                                M
City            Guadalupe, Zacatecas
State                            NaN
Country                          MEX
Half                 0 days 01:38:59
40K                  0 days 03:12:55
Pace                         0:07:48
TotalSeconds                 11575.0
HalfSeconds                   5939.0
Name: 10059, dtype: object
Guang Dong
 Age                          52
M/F                           M
City                 Guang Dong
State                       NaN
Country                     CHN
Half            0 days 01:58:08
40K             0 days 03:54:19
Pace                    0:09:26
TotalSeconds            14059.0
HalfSeconds              7088.0
Name: 23384, dtype: object
Guangzhou
 Age                          57
M/F                           M
City                  Guangzhou
State                       NaN
Country                     CHN
Half            0 days 01:46:00
40K             0 days 03:27:16
Pace                    0:08:20
TotalSeconds            12436.0
HalfSeconds              6360.0
Name: 18325, dtype: object
Guangzhou, Pr China
 Age                              45
M/F                               M
City            Guangzhou, Pr China
State                           NaN
Country                         CHN
Half                0 days 01:53:16
40K                 0 days 04:05:25
Pace                        0:09:58
TotalSeconds                14725.0
HalfSeconds                  6796.0
Name: 11880, dtype: object
Guatemala
 Age                          31
M/F                           M
City                  Guatemala
State                       NaN
Country                     GUA
Half            0 days 01:23:22
40K             0 days 02:38:40
Pace                    0:06:23
TotalSeconds             9520.0
HalfSeconds              5002.0
Name: 1044, dtype: object
Guatemala City
 Age                          32
M/F                           M
City             Guatemala City
State                       NaN
Country                     GUA
Half            0 days 01:22:11
40K             0 days 02:57:46
Pace                    0:07:18
TotalSeconds            10666.0
HalfSeconds              4931.0
Name: 1279, dtype: object
Guayanbo
 Age                          49
M/F                           F
City                   Guayanbo
State                        PR
Country                     USA
Half            0 days 02:12:24
40K             0 days 04:23:44
Pace                    0:10:37
TotalSeconds            15824.0
HalfSeconds              7944.0
Name: 26667, dtype: object
Guaynabo
 Age                          41
M/F                           M
City                   Guaynabo
State                        PR
Country                     USA
Half            0 days 01:45:09
40K             0 days 03:28:42
Pace                    0:08:24
TotalSeconds            12522.0
HalfSeconds              6309.0
Name: 27006, dtype: object
Guelph
 Age                          34
M/F                           M
City                     Guelph
State                        ON
Country                     CAN
Half            0 days 01:16:12
40K             0 days 02:25:57
Pace                    0:05:52
TotalSeconds             8757.0
HalfSeconds              4572.0
Name: 228, dtype: object
Guemligen
 Age                          53
M/F                           M
City                  Guemligen
State                       NaN
Country                     SUI
Half            0 days 01:39:34
40K             0 days 03:23:12
Pace                    0:08:16
TotalSeconds            12192.0
HalfSeconds              5974.0
Name: 16286, dtype: object
Guernsey
 Age                          54
M/F                           F
City                   Guernsey
State                       NaN
Country                     GBR
Half            0 days 01:45:33
40K             0 days 03:29:42
Pace                    0:08:30
TotalSeconds            12582.0
HalfSeconds              6333.0
Name: 14116, dtype: object
Guetersloh
 Age                          44
M/F                           M
City                 Guetersloh
State                       NaN
Country                     GER
Half            0 days 01:49:37
40K             0 days 03:44:14
Pace                    0:09:08
TotalSeconds            13454.0
HalfSeconds              6577.0
Name: 30923, dtype: object
Guilderland
 Age                          40
M/F                           M
City                Guilderland
State                        NY
Country                     USA
Half            0 days 01:21:38
40K             0 days 02:40:42
Pace                    0:06:30
TotalSeconds             9642.0
HalfSeconds              4898.0
Name: 657, dtype: object
Guildford
 Age                          45
M/F                           M
City                  Guildford
State                       NaN
Country                     GBR
Half            0 days 01:38:11
40K             0 days 03:16:29
Pace                    0:07:57
TotalSeconds            11789.0
HalfSeconds              5891.0
Name: 10727, dtype: object
Guilford
 Age                          39
M/F                           M
City                   Guilford
State                        CT
Country                     USA
Half            0 days 01:30:56
40K             0 days 02:59:44
Pace                    0:07:16
TotalSeconds            10784.0
HalfSeconds              5456.0
Name: 4763, dtype: object
Gulf Shores
 Age                          33
M/F                           F
City                Gulf Shores
State                        AL
Country                     USA
Half            0 days 01:45:46
40K             0 days 03:29:58
Pace                    0:08:29
TotalSeconds            12598.0
HalfSeconds              6346.0
Name: 14532, dtype: object
Gulfport
 Age                          38
M/F                           F
City                   Gulfport
State                        FL
Country                     USA
Half            0 days 01:52:04
40K             0 days 03:42:13
Pace                    0:09:00
TotalSeconds            13333.0
HalfSeconds              6724.0
Name: 20354, dtype: object
Gumma
 Age                          59
M/F                           M
City                      Gumma
State                       NaN
Country                     JPN
Half            0 days 02:15:41
40K             0 days 05:03:02
Pace                    0:12:15
TotalSeconds            18182.0
HalfSeconds              8141.0
Name: 31670, dtype: object
Gunnison
 Age                          53
M/F                           M
City                   Gunnison
State                        CO
Country                     USA
Half            0 days 01:40:47
40K             0 days 03:21:16
Pace                    0:08:10
TotalSeconds            12076.0
HalfSeconds              6047.0
Name: 13681, dtype: object
Gunsan-Si
 Age                          58
M/F                           M
City                  Gunsan-Si
State                       NaN
Country                     KOR
Half            0 days 01:57:24
40K             0 days 03:46:13
Pace                    0:09:04
TotalSeconds            13573.0
HalfSeconds              7044.0
Name: 11958, dtype: object
Guntersville
 Age                          37
M/F                           F
City               Guntersville
State                        AL
Country                     USA
Half            0 days 01:47:39
40K             0 days 03:24:01
Pace                    0:08:10
TotalSeconds            12241.0
HalfSeconds              6459.0
Name: 20182, dtype: object
Guntramsdorf
 Age                          39
M/F                           M
City               Guntramsdorf
State                       NaN
Country                     AUT
Half            0 days 01:35:37
40K             0 days 03:08:09
Pace                    0:07:36
TotalSeconds            11289.0
HalfSeconds              5737.0
Name: 31763, dtype: object
Gurgaon
 Age                          36
M/F                           F
City                    Gurgaon
State                       NaN
Country                     IND
Half            0 days 01:42:08
40K             0 days 03:22:47
Pace                    0:08:11
TotalSeconds            12167.0
HalfSeconds              6128.0
Name: 17855, dtype: object
Gurnee
 Age                          21
M/F                           M
City                     Gurnee
State                        IL
Country                     USA
Half            0 days 01:25:29
40K             0 days 03:00:57
Pace                    0:07:19
TotalSeconds            10857.0
HalfSeconds              5129.0
Name: 2697, dtype: object
Guthrie
 Age                          49
M/F                           M
City                    Guthrie
State                        OK
Country                     USA
Half            0 days 01:44:30
40K             0 days 03:52:53
Pace                    0:09:35
TotalSeconds            13973.0
HalfSeconds              6270.0
Name: 11581, dtype: object
Guys Mills
 Age                          34
M/F                           M
City                 Guys Mills
State                        PA
Country                     USA
Half            0 days 01:38:45
40K             0 days 03:16:52
Pace                    0:08:03
TotalSeconds            11812.0
HalfSeconds              5925.0
Name: 3579, dtype: object

Gwinn
 Age                          51
M/F                           F
City                      Gwinn
State                        MI
Country                     USA
Half            0 days 01:56:56
40K             0 days 03:50:46
Pace                    0:09:22
TotalSeconds            13846.0
HalfSeconds              7016.0
Name: 24615, dtype: object
Gwynedd
 Age                          33
M/F                           M
City                    Gwynedd
State                       NaN
Country                     GBR
Half            0 days 01:17:05
40K             0 days 02:32:28
Pace                    0:06:13
TotalSeconds             9148.0
HalfSeconds              4625.0
Name: 270, dtype: object
Göteborg
 Age                          52
M/F                           F
City                   Göteborg
State                       NaN
Country                     SWE
Half            0 days 01:39:28
40K             0 days 03:11:35
Pace                    0:07:42
TotalSeconds            11495.0
HalfSeconds              5968.0
Name: 9508, dtype: object
Haarlem
 Age                          39
M/F                           M
City                    Haarlem
State                       NaN
Country                     NED
Half            0 days 01:30:59
40K             0 days 03:07:27
Pace                    0:07:37
TotalSeconds            11247.0
HalfSeconds              5459.0
Name: 6192, dtype: object
Haarlev
 Age                          62
M/F                           M
City                    Haarlev
State                       NaN
Country                     DEN
Half            0 days 01:44:55
40K             0 days 03:27:32
Pace                    0:08:25
TotalSeconds            12452.0
HalfSeconds              6295.0
Name: 17376, dtype: object
Haberfield
 Age                          41
M/F                           M
City                 Haberfield
State                       NaN
Country                     AUS
Half            0 days 01:34:38
40K             0 days 04:29:23
Pace                    0:11:02
TotalSeconds            16163.0
HalfSeconds              5678.0
Name: 7378, dtype: object
Hachioji, Tokyo
 Age                          65
M/F                           M
City            Hachioji, Tokyo
State                       NaN
Country                     JPN
Half            0 days 01:53:51
40K             0 days 03:44:21
Pace                    0:09:05
TotalSeconds            13461.0
HalfSeconds              6831.0
Name: 25719, dtype: object
Hacienda Heights
 Age                           36
M/F                            F
City            Hacienda Heights
State                         CA
Country                      USA
Half             0 days 01:39:46
40K              0 days 03:09:30
Pace                     0:07:37
TotalSeconds             11370.0
HalfSeconds               5986.0
Name: 8185, dtype: object
Hackensack
 Age                          36
M/F                           F
City                 Hackensack
State                        NJ
Country                     USA
Half            0 days 01:33:05
40K             0 days 02:58:37
Pace                    0:07:12
TotalSeconds            10717.0
HalfSeconds              5585.0
Name: 11074, dtype: object
Hackettstown
 Age                          50
M/F                           M
City               Hackettstown
State                        NJ
Country                     USA
Half            0 days 01:33:01
40K             0 days 03:08:13
Pace                    0:07:38
TotalSeconds            11293.0
HalfSeconds              5581.0
Name: 7603, dtype: object
Haddon Township
 Age                          42
M/F                           F
City            Haddon Township
State                        NJ
Country                     USA
Half            0 days 01:41:06
40K             0 days 03:11:54
Pace                    0:07:43
TotalSeconds            11514.0
HalfSeconds              6066.0
Name: 15354, dtype: object
Haddonfield
 Age                          37
M/F                           F
City                Haddonfield
State                        NJ
Country                     USA
Half            0 days 01:37:46
40K             0 days 03:13:09
Pace                    0:07:48
TotalSeconds            11589.0
HalfSeconds              5866.0
Name: 10222, dtype: object
Hadley
 Age                          58
M/F                           M
City                     Hadley
State                        MA
Country                     USA
Half            0 days 01:43:01
40K             0 days 03:23:42
Pace                    0:08:14
TotalSeconds            12222.0
HalfSeconds              6181.0
Name: 13015, dtype: object
Hadsten
 Age                          54
M/F                           M
City                    Hadsten
State                       NaN
Country                     DEN
Half            0 days 01:35:20
40K             0 days 03:08:53
Pace                    0:07:39
TotalSeconds            11333.0
HalfSeconds              5720.0
Name: 9790, dtype: object
Hafnarfjordur
 Age                          54
M/F                           F
City              Hafnarfjordur
State                       NaN
Country                     ISL
Half            0 days 01:51:51
40K             0 days 03:36:42
Pace                    0:08:44
TotalSeconds            13002.0
HalfSeconds              6711.0
Name: 21679, dtype: object
Hagersten
 Age                          29
M/F                           M
City                  Hagersten
State                       NaN
Country                     SWE
Half            0 days 01:32:19
40K             0 days 03:16:26
Pace                    0:08:00
TotalSeconds            11786.0
HalfSeconds              5539.0
Name: 3819, dtype: object
Hagerstown
 Age                          44
M/F                           M
City                 Hagerstown
State                        MD
Country                     USA
Half            0 days 01:33:21
40K             0 days 03:06:49
Pace                    0:07:33
TotalSeconds            11209.0
HalfSeconds              5601.0
Name: 6655, dtype: object
Hainesport
 Age                          44
M/F                           M
City                 Hainesport
State                        NJ
Country                     USA
Half            0 days 02:14:51
40K             0 days 04:53:17
Pace                    0:11:54
TotalSeconds            17597.0
HalfSeconds              8091.0
Name: 28507, dtype: object
Hainesville
 Age                          26
M/F                           F
City                Hainesville
State                        IL
Country                     USA
Half            0 days 01:50:41
40K             0 days 03:38:54
Pace                    0:08:48
TotalSeconds            13134.0
HalfSeconds              6641.0
Name: 16979, dtype: object
Haining
 Age                          50
M/F                           M
City                    Haining
State                       NaN
Country                     CHN
Half            0 days 01:55:05
40K             0 days 03:53:54
Pace                    0:09:30
TotalSeconds            14034.0
HalfSeconds              6905.0
Name: 14308, dtype: object
Hales Corners
 Age                          29
M/F                           M
City              Hales Corners
State                        WI
Country                     USA
Half            0 days 01:26:28
40K             0 days 02:42:46
Pace                    0:06:32
TotalSeconds             9766.0
HalfSeconds              5188.0
Name: 1651, dtype: object
Halethorpe
 Age                          27
M/F                           M
City                 Halethorpe
State                        MD
Country                     USA
Half            0 days 01:26:23
40K             0 days 02:54:15
Pace                    0:07:05
TotalSeconds            10455.0
HalfSeconds              5183.0
Name: 2308, dtype: object
Haleyville
 Age                          35
M/F                           F
City                 Haleyville
State                        AL
Country                     USA
Half            0 days 01:45:10
40K             0 days 03:37:06
Pace                    0:08:45
TotalSeconds            13026.0
HalfSeconds              6310.0
Name: 10427, dtype: object
Halfmoon
 Age                          31
M/F                           F
City                   Halfmoon
State                        NY
Country                     USA
Half            0 days 01:43:45
40K             0 days 03:23:41
Pace                    0:08:14
TotalSeconds            12221.0
HalfSeconds              6225.0
Name: 16626, dtype: object

Halifax
 Age                          47
M/F                           M
City                    Halifax
State                        NS
Country                     CAN
Half            0 days 01:24:37
40K             0 days 02:45:00
Pace                    0:06:41
TotalSeconds             9900.0
HalfSeconds              5077.0
Name: 1213, dtype: object
Halle
 Age                          46
M/F                           F
City                      Halle
State                       NaN
Country                     GER
Half            0 days 01:44:35
40K             0 days 03:21:12
Pace                    0:08:06
TotalSeconds            12072.0
HalfSeconds              6275.0
Name: 16117, dtype: object
Hallowell
 Age                          38
M/F                           M
City                  Hallowell
State                        ME
Country                     USA
Half            0 days 01:30:33
40K             0 days 03:00:08
Pace                    0:07:17
TotalSeconds            10808.0
HalfSeconds              5433.0
Name: 6393, dtype: object
Halmstad
 Age                          40
M/F                           M
City                   Halmstad
State                       NaN
Country                     SWE
Half            0 days 01:27:18
40K             0 days 02:50:55
Pace                    0:06:52
TotalSeconds            10255.0
HalfSeconds              5238.0
Name: 8160, dtype: object
Halstenbek
 Age                          75
M/F                           M
City                 Halstenbek
State                       NaN
Country                     GER
Half            0 days 01:55:18
40K             0 days 04:12:13
Pace                    0:10:21
TotalSeconds            15133.0
HalfSeconds              6918.0
Name: 25601, dtype: object
Ham Lake
 Age                          35
M/F                           F
City                   Ham Lake
State                        MN
Country                     USA
Half            0 days 01:39:16
40K             0 days 03:16:44
Pace                    0:07:57
TotalSeconds            11804.0
HalfSeconds              5956.0
Name: 17290, dtype: object
Hamburg
 Age                          49
M/F                           M
City                    Hamburg
State                       NaN
Country                     GER
Half            0 days 01:24:13
40K             0 days 02:46:51
Pace                    0:06:44
TotalSeconds            10011.0
HalfSeconds              5053.0
Name: 931, dtype: object
Hamden
 Age                          31
M/F                           M
City                     Hamden
State                        CT
Country                     USA
Half            0 days 01:25:20
40K             0 days 02:45:05
Pace                    0:06:39
TotalSeconds             9905.0
HalfSeconds              5120.0
Name: 1544, dtype: object
Hamilton
 Age                          28
M/F                           M
City                   Hamilton
State                        ON
Country                     CAN
Half            0 days 01:19:56
40K             0 days 02:46:55
Pace                    0:06:46
TotalSeconds            10015.0
HalfSeconds              4796.0
Name: 970, dtype: object
Hamilton Parish
 Age                          40
M/F                           M
City            Hamilton Parish
State                       NaN
Country                     BER
Half            0 days 01:28:39
40K             0 days 02:48:30
Pace                    0:06:46
TotalSeconds            10110.0
HalfSeconds              5319.0
Name: 5546, dtype: object
Hammerteich
 Age                          60
M/F                           M
City                Hammerteich
State                       NaN
Country                     AUT
Half            0 days 02:11:51
40K             0 days 04:23:15
Pace                    0:10:38
TotalSeconds            15795.0
HalfSeconds              7911.0
Name: 31734, dtype: object
Hamminkeln
 Age                          52
M/F                           M
City                 Hamminkeln
State                       NaN
Country                     GER
Half            0 days 01:37:25
40K             0 days 03:09:20
Pace                    0:07:37
TotalSeconds            11360.0
HalfSeconds              5845.0
Name: 9147, dtype: object
Hammond
 Age                          24
M/F                           F
City                    Hammond
State                        WI
Country                     USA
Half            0 days 01:42:21
40K             0 days 03:22:31
Pace                    0:08:09
TotalSeconds            12151.0
HalfSeconds              6141.0
Name: 16534, dtype: object
Hammonds Plains
 Age                          31
M/F                           F
City            Hammonds Plains
State                        NS
Country                     CAN
Half            0 days 01:40:24
40K             0 days 03:13:31
Pace                    0:07:48
TotalSeconds            11611.0
HalfSeconds              6024.0
Name: 14013, dtype: object
Hammonton
 Age                          41
M/F                           F
City                  Hammonton
State                        NJ
Country                     USA
Half            0 days 01:49:57
40K             0 days 03:33:45
Pace                    0:08:37
TotalSeconds            12825.0
HalfSeconds              6597.0
Name: 21112, dtype: object
Hampden
 Age                          44
M/F                           F
City                    Hampden
State                        ME
Country                     USA
Half            0 days 01:52:50
40K             0 days 04:01:17
Pace                    0:09:48
TotalSeconds            14477.0
HalfSeconds              6770.0
Name: 21304, dtype: object
Hampshire
 Age                          55
M/F                           M
City                  Hampshire
State                       NaN
Country                     GBR
Half            0 days 02:15:26
40K             0 days 04:26:57
Pace                    0:10:49
TotalSeconds            16017.0
HalfSeconds              8126.0
Name: 31485, dtype: object
Hampstead
 Age                          46
M/F                           M
City                  Hampstead
State                        NC
Country                     USA
Half            0 days 01:28:15
40K             0 days 03:17:48
Pace                    0:07:59
TotalSeconds            11868.0
HalfSeconds              5295.0
Name: 4559, dtype: object
Hampton
 Age                          56
M/F                           M
City                    Hampton
State                        NB
Country                     CAN
Half            0 days 01:39:22
40K             0 days 03:12:03
Pace                    0:07:44
TotalSeconds            11523.0
HalfSeconds              5962.0
Name: 10887, dtype: object
Hampton Cove
 Age                          50
M/F                           M
City               Hampton Cove
State                        AL
Country                     USA
Half            0 days 01:31:07
40K             0 days 03:02:40
Pace                    0:07:26
TotalSeconds            10960.0
HalfSeconds              5467.0
Name: 7441, dtype: object
Hampton Falls
 Age                          26
M/F                           M
City              Hampton Falls
State                        NH
Country                     USA
Half            0 days 01:37:55
40K             0 days 03:07:30
Pace                    0:07:34
TotalSeconds            11250.0
HalfSeconds              5875.0
Name: 30425, dtype: object
Hamptonville
 Age                          43
M/F                           M
City               Hamptonville
State                        NC
Country                     USA
Half            0 days 01:29:42
40K             0 days 02:49:24
Pace                    0:06:49
TotalSeconds            10164.0
HalfSeconds              5382.0
Name: 7662, dtype: object
Hangzhou
 Age                          44
M/F                           F
City                   Hangzhou
State                       NaN
Country                     CHN
Half            0 days 01:36:48
40K             0 days 03:12:13
Pace                    0:07:46
TotalSeconds            11533.0
HalfSeconds              5808.0
Name: 10115, dtype: object
Hangzhou, Zhejiang
 Age                             40
M/F                              M
City            Hangzhou, Zhejiang
State                          NaN
Country                        CHN
Half               0 days 02:22:18
40K                0 days 05:02:50
Pace                       0:12:13
TotalSeconds               18170.0
HalfSeconds                 8538.0
Name: 28304, dtype: object
Hanover
 Age                          27
M/F                           M
City                    Hanover
State                        NH
Country                     USA
Half            0 days 01:17:47
40K             0 days 02:29:25
Pace                    0:06:01
TotalSeconds             8965.0
HalfSeconds              4667.0
Name: 422, dtype: object
Hanover Park
 Age                          43
M/F                           M
City               Hanover Park
State                        IL
Country                     USA
Half            0 days 01:27:58
40K             0 days 03:14:53
Pace                    0:07:54
TotalSeconds            11693.0
HalfSeconds              5278.0
Name: 1692, dtype: object
Hanscom Afb
 Age                          32
M/F                           M
City                Hanscom Afb
State                        MA
Country                     USA
Half            0 days 01:22:30
40K             0 days 02:41:29
Pace                    0:06:33
TotalSeconds             9689.0
HalfSeconds              4950.0
Name: 2118, dtype: object
Hanscom Air Force Base
 Age                                 29
M/F                                  M
City            Hanscom Air Force Base
State                               MA
Country                            USA
Half                   0 days 01:26:14
40K                    0 days 03:11:21
Pace                           0:07:49
TotalSeconds                   11481.0
HalfSeconds                     5174.0
Name: 4839, dtype: object
Hanson
 Age                          24
M/F                           F
City                     Hanson
State                        MA
Country                     USA
Half            0 days 01:46:05
40K             0 days 03:52:01
Pace                    0:09:23
TotalSeconds            13921.0
HalfSeconds              6365.0
Name: 15269, dtype: object
Hanwell
 Age                          43
M/F                           M
City                    Hanwell
State                        NB
Country                     CAN
Half            0 days 01:35:35
40K             0 days 03:07:33
Pace                    0:07:35
TotalSeconds            11253.0
HalfSeconds              5735.0
Name: 7498, dtype: object
Happy Valley
 Age                          24
M/F                           F
City               Happy Valley
State                        OR
Country                     USA
Half            0 days 01:40:37
40K             0 days 03:18:03
Pace                    0:07:59
TotalSeconds            11883.0
HalfSeconds              6037.0
Name: 9079, dtype: object
Harare
 Age                          33
M/F                           M
City                     Harare
State                       NaN
Country                     ZIM
Half            0 days 01:06:47
40K             0 days 02:11:48
Pace                    0:05:26
TotalSeconds             7908.0
HalfSeconds              4007.0
Name: 16, dtype: object
Harbor Springs
 Age                          33
M/F                           M
City             Harbor Springs
State                        MI
Country                     USA
Half            0 days 01:29:10
40K             0 days 02:54:36
Pace                    0:07:04
TotalSeconds            10476.0
HalfSeconds              5350.0
Name: 4953, dtype: object
Hardin
 Age                          28
M/F                           M
City                     Hardin
State                        MT
Country                     USA
Half            0 days 01:23:47
40K             0 days 02:42:13
Pace                    0:06:37
TotalSeconds             9733.0
HalfSeconds              5027.0
Name: 1700, dtype: object
Hardwick
 Age                          56
M/F                           M
City                   Hardwick
State                        NJ
Country                     USA
Half            0 days 01:30:40
40K             0 days 03:08:53
Pace                    0:07:41
TotalSeconds            11333.0
HalfSeconds              5440.0
Name: 4882, dtype: object
Harleysville
 Age                          32
M/F                           F
City               Harleysville
State                        PA
Country                     USA
Half            0 days 01:46:32
40K             0 days 03:33:21
Pace                    0:08:40
TotalSeconds            12801.0
HalfSeconds              6392.0
Name: 17075, dtype: object
Harlingen
 Age                          34
M/F                           M
City                  Harlingen
State                        TX
Country                     USA
Half            0 days 01:26:43
40K             0 days 02:56:54
Pace                    0:07:14
TotalSeconds            10614.0
HalfSeconds              5203.0
Name: 2589, dtype: object
Harpenden
 Age                          34
M/F                           M
City                  Harpenden
State                       NaN
Country                     GBR
Half            0 days 01:27:13
40K             0 days 02:47:31
Pace                    0:06:45
TotalSeconds            10051.0
HalfSeconds              5233.0
Name: 1880, dtype: object
Harpswell
 Age                          60
M/F                           M
City                  Harpswell
State                        ME
Country                     USA
Half            0 days 01:54:58
40K             0 days 03:40:41
Pace                    0:08:52
TotalSeconds            13241.0
HalfSeconds              6898.0
Name: 16386, dtype: object
Harrington Park
 Age                          53
M/F                           F
City            Harrington Park
State                        NJ
Country                     USA
Half            0 days 01:51:46
40K             0 days 03:37:12
Pace                    0:08:45
TotalSeconds            13032.0
HalfSeconds              6706.0
Name: 22227, dtype: object
Harrington Park, Nsw
 Age                               57
M/F                                M
City            Harrington Park, Nsw
State                            NaN
Country                          AUS
Half                 0 days 01:43:54
40K                  0 days 03:26:27
Pace                         0:08:24
TotalSeconds                 12387.0
HalfSeconds                   6234.0
Name: 15198, dtype: object
Harrisburg
 Age                          30
M/F                           F
City                 Harrisburg
State                        PA
Country                     USA
Half            0 days 01:38:58
40K             0 days 03:12:05
Pace                    0:07:46
TotalSeconds            11525.0
HalfSeconds              5938.0
Name: 11498, dtype: object
Harrison
 Age                          36
M/F                           M
City                   Harrison
State                        NJ
Country                     USA
Half            0 days 01:31:55
40K             0 days 03:00:32
Pace                    0:07:18
TotalSeconds            10832.0
HalfSeconds              5515.0
Name: 5064, dtype: object
Harrisonburg
 Age                          20
M/F                           F
City               Harrisonburg
State                        VA
Country                     USA
Half            0 days 01:44:52
40K             0 days 03:25:29
Pace                    0:08:19
TotalSeconds            12329.0
HalfSeconds              6292.0
Name: 16663, dtype: object
Harrisonville
 Age                          40
M/F                           M
City              Harrisonville
State                        MO
Country                     USA
Half            0 days 01:44:14
40K             0 days 03:23:51
Pace                    0:08:12
TotalSeconds            12231.0
HalfSeconds              6254.0
Name: 8906, dtype: object
Harrisville
 Age                          26
M/F                           F
City                Harrisville
State                        RI
Country                     USA
Half            0 days 02:13:16
40K             0 days 04:08:50
Pace                    0:09:57
TotalSeconds            14930.0
HalfSeconds              7996.0
Name: 28273, dtype: object
Harrogate
 Age                          24
M/F                           F
City                  Harrogate
State                        TN
Country                     USA
Half            0 days 01:41:01
40K             0 days 03:19:59
Pace                    0:08:05
TotalSeconds            11999.0
HalfSeconds              6061.0
Name: 14850, dtype: object
Harrowsmith
 Age                          39
M/F                           F
City                Harrowsmith
State                        ON
Country                     CAN
Half            0 days 01:47:00
40K             0 days 03:30:13
Pace                    0:08:28
TotalSeconds            12613.0
HalfSeconds              6420.0
Name: 20215, dtype: object

Harsum
 Age                          41
M/F                           M
City                     Harsum
State                       NaN
Country                     GER
Half            0 days 01:48:32
40K             0 days 03:49:18
Pace                    0:09:19
TotalSeconds            13758.0
HalfSeconds              6512.0
Name: 31776, dtype: object
Hartford
 Age                          26
M/F                           M
City                   Hartford
State                        CT
Country                     USA
Half            0 days 02:02:42
40K             0 days 04:15:17
Pace                    0:10:18
TotalSeconds            15317.0
HalfSeconds              7362.0
Name: 27627, dtype: object
Hartland
 Age                          45
M/F                           M
City                   Hartland
State                        MI
Country                     USA
Half            0 days 01:34:57
40K             0 days 03:16:09
Pace                    0:07:57
TotalSeconds            11769.0
HalfSeconds              5697.0
Name: 6557, dtype: object
Hartsdale
 Age                          31
M/F                           F
City                  Hartsdale
State                        NY
Country                     USA
Half            0 days 01:34:22
40K             0 days 03:05:27
Pace                    0:07:31
TotalSeconds            11127.0
HalfSeconds              5662.0
Name: 7645, dtype: object
Hartsville
 Age                          46
M/F                           F
City                 Hartsville
State                        SC
Country                     USA
Half            0 days 01:51:38
40K             0 days 03:31:59
Pace                    0:08:32
TotalSeconds            12719.0
HalfSeconds              6698.0
Name: 21158, dtype: object
Harvard
 Age                          50
M/F                           M
City                    Harvard
State                        MA
Country                     USA
Half            0 days 01:27:58
40K             0 days 02:49:44
Pace                    0:06:50
TotalSeconds            10184.0
HalfSeconds              5278.0
Name: 4447, dtype: object
Harvest
 Age                          32
M/F                           M
City                    Harvest
State                        AL
Country                     USA
Half            0 days 01:31:13
40K             0 days 03:07:15
Pace                    0:07:36
TotalSeconds            11235.0
HalfSeconds              5473.0
Name: 4532, dtype: object
Harwich
 Age                          59
M/F                           M
City                    Harwich
State                        MA
Country                     USA
Half            0 days 01:42:53
40K             0 days 03:24:30
Pace                    0:08:17
TotalSeconds            12270.0
HalfSeconds              6173.0
Name: 16777, dtype: object
Harwich Port
 Age                          58
M/F                           M
City               Harwich Port
State                        MA
Country                     USA
Half            0 days 01:51:47
40K             0 days 03:41:08
Pace                    0:08:55
TotalSeconds            13268.0
HalfSeconds              6707.0
Name: 18652, dtype: object
Harwinton
 Age                          48
M/F                           M
City                  Harwinton
State                        CT
Country                     USA
Half            0 days 01:36:52
40K             0 days 03:06:50
Pace                    0:07:33
TotalSeconds            11210.0
HalfSeconds              5812.0
Name: 10625, dtype: object
Harwood
 Age                          55
M/F                           F
City                    Harwood
State                        MD
Country                     USA
Half            0 days 01:55:56
40K             0 days 03:55:04
Pace                    0:09:34
TotalSeconds            14104.0
HalfSeconds              6956.0
Name: 24450, dtype: object
Hasbrouck Heights
 Age                            44
M/F                             M
City            Hasbrouck Heights
State                          NJ
Country                       USA
Half              0 days 01:26:24
40K               0 days 02:59:40
Pace                      0:07:17
TotalSeconds              10780.0
HalfSeconds                5184.0
Name: 3503, dtype: object
Haslemere
 Age                          23
M/F                           M
City                  Haslemere
State                       NaN
Country                     GBR
Half            0 days 01:28:38
40K             0 days 03:10:19
Pace                    0:07:40
TotalSeconds            11419.0
HalfSeconds              5318.0
Name: 1043, dtype: object
Haslett
 Age                          24
M/F                           M
City                    Haslett
State                        MI
Country                     USA
Half            0 days 01:22:58
40K             0 days 02:49:37
Pace                    0:06:50
TotalSeconds            10177.0
HalfSeconds              4978.0
Name: 1061, dtype: object
Haslev
 Age                          48
M/F                           M
City                     Haslev
State                       NaN
Country                     DEN
Half            0 days 01:46:23
40K             0 days 03:43:41
Pace                    0:09:05
TotalSeconds            13421.0
HalfSeconds              6383.0
Name: 12476, dtype: object
Hastings
 Age                          32
M/F                           M
City                   Hastings
State                        NE
Country                     USA
Half            0 days 01:29:20
40K             0 days 02:56:52
Pace                    0:07:09
TotalSeconds            10612.0
HalfSeconds              5360.0
Name: 4265, dtype: object
Hastings On Hudon
 Age                            36
M/F                             F
City            Hastings On Hudon
State                          NY
Country                       USA
Half              0 days 01:55:19
40K               0 days 03:42:39
Pace                      0:08:58
TotalSeconds              13359.0
HalfSeconds                6919.0
Name: 14953, dtype: object
Hastings On Hudson
 Age                             47
M/F                              F
City            Hastings On Hudson
State                           NY
Country                        USA
Half               0 days 01:52:16
40K                0 days 03:39:30
Pace                       0:08:51
TotalSeconds               13170.0
HalfSeconds                 6736.0
Name: 22927, dtype: object
Hastings-On-Hudson
 Age                             57
M/F                              F
City            Hastings-On-Hudson
State                           NY
Country                        USA
Half               0 days 02:02:26
40K                0 days 03:57:18
Pace                       0:09:34
TotalSeconds               14238.0
HalfSeconds                 7346.0
Name: 25607, dtype: object
Hatchet Lake
 Age                          49
M/F                           M
City               Hatchet Lake
State                        NS
Country                     CAN
Half            0 days 01:33:05
40K             0 days 03:01:07
Pace                    0:07:20
TotalSeconds            10867.0
HalfSeconds              5585.0
Name: 11492, dtype: object
Hattiesburg
 Age                          28
M/F                           M
City                Hattiesburg
State                        MS
Country                     USA
Half            0 days 01:28:09
40K             0 days 02:55:57
Pace                    0:07:06
TotalSeconds            10557.0
HalfSeconds              5289.0
Name: 2312, dtype: object
Hattingen
 Age                          25
M/F                           F
City                  Hattingen
State                       NaN
Country                     GER
Half            0 days 02:12:29
40K             0 days 04:14:59
Pace                    0:10:14
TotalSeconds            15299.0
HalfSeconds              7949.0
Name: 30691, dtype: object
Haubstadt
 Age                          40
M/F                           F
City                  Haubstadt
State                        IN
Country                     USA
Half            0 days 01:51:34
40K             0 days 03:33:00
Pace                    0:08:34
TotalSeconds            12780.0
HalfSeconds              6694.0
Name: 19060, dtype: object
Haughton
 Age                          50
M/F                           F
City                   Haughton
State                        LA
Country                     USA
Half            0 days 01:54:35
40K             0 days 03:55:00
Pace                    0:09:32
TotalSeconds            14100.0
HalfSeconds              6875.0
Name: 24782, dtype: object
Hausmannstaetten
 Age                           59
M/F                            M
City            Hausmannstaetten
State                        NaN
Country                      AUT
Half             0 days 02:08:55
40K              0 days 04:32:41
Pace                     0:11:07
TotalSeconds             16361.0
HalfSeconds               7735.0
Name: 31030, dtype: object
Havelock
 Age                          64
M/F                           F
City                   Havelock
State                       NaN
Country                     NZL
Half            0 days 02:15:09
40K             0 days 04:37:45
Pace                    0:11:23
TotalSeconds            16665.0
HalfSeconds              8109.0
Name: 31850, dtype: object

Haverhill
 Age                          28
M/F                           M
City                  Haverhill
State                        MA
Country                     USA
Half            0 days 01:21:50
40K             0 days 02:41:03
Pace                    0:06:29
TotalSeconds             9663.0
HalfSeconds              4910.0
Name: 255, dtype: object
Havertown
 Age                          48
M/F                           F
City                  Havertown
State                        PA
Country                     USA
Half            0 days 01:45:55
40K             0 days 03:26:34
Pace                    0:08:20
TotalSeconds            12394.0
HalfSeconds              6355.0
Name: 15304, dtype: object
Havre De Grace
 Age                          38
M/F                           M
City             Havre De Grace
State                        MD
Country                     USA
Half            0 days 01:15:35
40K             0 days 02:28:55
Pace                    0:06:01
TotalSeconds             8935.0
HalfSeconds              4535.0
Name: 171, dtype: object
Hawaiian Gardens
 Age                           63
M/F                            M
City            Hawaiian Gardens
State                         CA
Country                      USA
Half             0 days 01:55:49
40K              0 days 04:04:58
Pace                     0:09:55
TotalSeconds             14698.0
HalfSeconds               6949.0
Name: 22638, dtype: object
Hawker
 Age                          32
M/F                           F
City                     Hawker
State                       NaN
Country                     AUS
Half            0 days 01:47:19
40K             0 days 03:23:18
Pace                    0:08:08
TotalSeconds            12198.0
HalfSeconds              6439.0
Name: 12606, dtype: object
Hawley
 Age                          58
M/F                           M
City                     Hawley
State                        PA
Country                     USA
Half            0 days 02:01:13
40K             0 days 04:05:49
Pace                    0:09:54
TotalSeconds            14749.0
HalfSeconds              7273.0
Name: 17195, dtype: object
Haworth
 Age                          46
M/F                           F
City                    Haworth
State                        NJ
Country                     USA
Half            0 days 01:42:39
40K             0 days 03:23:24
Pace                    0:08:11
TotalSeconds            12204.0
HalfSeconds              6159.0
Name: 12859, dtype: object
Hawthorn
 Age                          42
M/F                           F
City                   Hawthorn
State                       NaN
Country                     AUS
Half            0 days 01:40:02
40K             0 days 03:15:32
Pace                    0:07:53
TotalSeconds            11732.0
HalfSeconds              6002.0
Name: 19594, dtype: object
Hawthorn Woods
 Age                          30
M/F                           F
City             Hawthorn Woods
State                        IL
Country                     USA
Half            0 days 01:31:50
40K             0 days 03:01:04
Pace                    0:07:18
TotalSeconds            10864.0
HalfSeconds              5510.0
Name: 7031, dtype: object
Hawthorne
 Age                          27
M/F                           F
City                  Hawthorne
State                        NJ
Country                     USA
Half            0 days 01:33:51
40K             0 days 03:02:26
Pace                    0:07:23
TotalSeconds            10946.0
HalfSeconds              5631.0
Name: 9635, dtype: object
Hayden
 Age                          51
M/F                           F
City                     Hayden
State                        ID
Country                     USA
Half            0 days 02:31:27
40K             0 days 05:11:48
Pace                    0:12:49
TotalSeconds            18708.0
HalfSeconds              9087.0
Name: 29861, dtype: object
Haymarket
 Age                          36
M/F                           M
City                  Haymarket
State                        VA
Country                     USA
Half            0 days 01:23:44
40K             0 days 03:00:58
Pace                    0:07:21
TotalSeconds            10858.0
HalfSeconds              5024.0
Name: 2495, dtype: object
Hayward
 Age                          36
M/F                           M
City                    Hayward
State                        WI
Country                     USA
Half            0 days 01:31:02
40K             0 days 03:21:40
Pace                    0:08:11
TotalSeconds            12100.0
HalfSeconds              5462.0
Name: 2366, dtype: object
Haywards Bay
 Age                          38
M/F                           M
City               Haywards Bay
State                       NaN
Country                     AUS
Half            0 days 01:45:31
40K             0 days 03:34:34
Pace                    0:08:39
TotalSeconds            12874.0
HalfSeconds              6331.0
Name: 31595, dtype: object
Haywards Heath
 Age                          35
M/F                           M
City             Haywards Heath
State                       NaN
Country                     GBR
Half            0 days 01:25:16
40K             0 days 02:51:06
Pace                    0:06:55
TotalSeconds            10266.0
HalfSeconds              5116.0
Name: 1720, dtype: object
Hazlet
 Age                          24
M/F                           M
City                     Hazlet
State                        NJ
Country                     USA
Half            0 days 01:31:01
40K             0 days 03:17:51
Pace                    0:08:04
TotalSeconds            11871.0
HalfSeconds              5461.0
Name: 5148, dtype: object
Headingley
 Age                          48
M/F                           M
City                 Headingley
State                        MB
Country                     CAN
Half            0 days 00:00:00
40K             0 days 03:03:57
Pace                    0:07:26
TotalSeconds            11037.0
HalfSeconds                 0.0
Name: 8003, dtype: object
Healdsburg
 Age                          51
M/F                           M
City                 Healdsburg
State                        CA
Country                     USA
Half            0 days 01:38:48
40K             0 days 03:11:59
Pace                    0:07:45
TotalSeconds            11519.0
HalfSeconds              5928.0
Name: 11017, dtype: object
Heath
 Age                          49
M/F                           M
City                      Heath
State                        TX
Country                     USA
Half            0 days 02:08:00
40K             0 days 04:12:01
Pace                    0:10:13
TotalSeconds            15121.0
HalfSeconds              7680.0
Name: 11827, dtype: object
Heathrow
 Age                          29
M/F                           M
City                   Heathrow
State                        FL
Country                     USA
Half            0 days 02:32:42
40K             0 days 05:15:51
Pace                    0:12:47
TotalSeconds            18951.0
HalfSeconds              9162.0
Name: 27345, dtype: object
Hebbs Cross
 Age                          56
M/F                           M
City                Hebbs Cross
State                        NS
Country                     CAN
Half            0 days 01:37:55
40K             0 days 03:14:48
Pace                    0:07:53
TotalSeconds            11688.0
HalfSeconds              5875.0
Name: 8846, dtype: object
Hebron
 Age                          50
M/F                           M
City                     Hebron
State                        IN
Country                     USA
Half            0 days 01:20:11
40K             0 days 02:40:58
Pace                    0:06:31
TotalSeconds             9658.0
HalfSeconds              4811.0
Name: 499, dtype: object
Hedehusene
 Age                          45
M/F                           M
City                 Hedehusene
State                       NaN
Country                     DEN
Half            0 days 01:45:34
40K             0 days 03:27:40
Pace                    0:08:23
TotalSeconds            12460.0
HalfSeconds              6334.0
Name: 12251, dtype: object
Heemstede
 Age                          48
M/F                           M
City                  Heemstede
State                       NaN
Country                     NED
Half            0 days 01:26:12
40K             0 days 02:56:08
Pace                    0:07:08
TotalSeconds            10568.0
HalfSeconds              5172.0
Name: 2666, dtype: object
Heiligenberg
 Age                          62
M/F                           M
City               Heiligenberg
State                       NaN
Country                     FRA
Half            0 days 02:09:18
40K             0 days 04:31:42
Pace                    0:11:01
TotalSeconds            16302.0
HalfSeconds              7758.0
Name: 31576, dtype: object
Heilongjian
 Age                          25
M/F                           F
City                Heilongjian
State                       NaN
Country                     CHN
Half            0 days 01:23:51
40K             0 days 02:50:29
Pace                    0:06:54
TotalSeconds            10229.0
HalfSeconds              5031.0
Name: F16, dtype: object
Helena
 Age                          32
M/F                           M
City                     Helena
State                        MT
Country                     USA
Half            0 days 01:23:53
40K             0 days 02:50:10
Pace                    0:06:53
TotalSeconds            10210.0
HalfSeconds              5033.0
Name: 1730, dtype: object
Helesmes
 Age                          36
M/F                           M
City                   Helesmes
State                       NaN
Country                     FRA
Half            0 days 01:25:09
40K             0 days 02:49:42
Pace                    0:06:52
TotalSeconds            10182.0
HalfSeconds              5109.0
Name: 2874, dtype: object
Hellertown
 Age                          55
M/F                           M
City                 Hellertown
State                        PA
Country                     USA
Half            0 days 01:56:16
40K             0 days 03:48:57
Pace                    0:09:15
TotalSeconds            13737.0
HalfSeconds              6976.0
Name: 26981, dtype: object
Hellerup
 Age                          49
M/F                           M
City                   Hellerup
State                       NaN
Country                     DEN
Half            0 days 01:41:48
40K             0 days 03:35:34
Pace                    0:08:44
TotalSeconds            12934.0
HalfSeconds              6108.0
Name: 7624, dtype: object
Helotes
 Age                          54
M/F                           M
City                    Helotes
State                        TX
Country                     USA
Half            0 days 01:37:22
40K             0 days 03:11:28
Pace                    0:07:50
TotalSeconds            11488.0
HalfSeconds              5842.0
Name: 11088, dtype: object
Helsingborg
 Age                          56
M/F                           M
City                Helsingborg
State                       NaN
Country                     SWE
Half            0 days 01:37:06
40K             0 days 03:07:58
Pace                    0:07:36
TotalSeconds            11278.0
HalfSeconds              5826.0
Name: 8596, dtype: object
Helsinki
 Age                          55
M/F                           M
City                   Helsinki
State                       NaN
Country                     FIN
Half            0 days 01:56:36
40K             0 days 00:00:00
Pace                    0:09:06
TotalSeconds                0.0
HalfSeconds              6996.0
Name: 18758, dtype: object
Hem
 Age                          40
M/F                           M
City                        Hem
State                       NaN
Country                     FRA
Half            0 days 01:28:26
40K             0 days 02:52:25
Pace                    0:07:00
TotalSeconds            10345.0
HalfSeconds              5306.0
Name: 3108, dtype: object
Hempstead
 Age                          46
M/F                           F
City                  Hempstead
State                        TX
Country                     USA
Half            0 days 01:54:52
40K             0 days 03:52:27
Pace                    0:09:23
TotalSeconds            13947.0
HalfSeconds              6892.0
Name: 13414, dtype: object
Henderson
 Age                          45
M/F                           M
City                  Henderson
State                        NV
Country                     USA
Half            0 days 01:29:26
40K             0 days 02:57:14
Pace                    0:07:12
TotalSeconds            10634.0
HalfSeconds              5366.0
Name: 7045, dtype: object
Hendersonville
 Age                          46
M/F                           M
City             Hendersonville
State                        TN
Country                     USA
Half            0 days 01:40:34
40K             0 days 03:19:23
Pace                    0:08:06
TotalSeconds            11963.0
HalfSeconds              6034.0
Name: 12333, dtype: object
Hendricks
 Age                          37
M/F                           M
City                  Hendricks
State                        MN
Country                     USA
Half            0 days 01:30:23
40K             0 days 02:52:31
Pace                    0:06:59
TotalSeconds            10351.0
HalfSeconds              5423.0
Name: 3119, dtype: object
Henley Beach South
 Age                             44
M/F                              F
City            Henley Beach South
State                          NaN
Country                        AUS
Half               0 days 01:38:10
40K                0 days 03:07:56
Pace                       0:07:35
TotalSeconds               11276.0
HalfSeconds                 5890.0
Name: 12796, dtype: object
Henley-On-Thames
 Age                           47
M/F                            M
City            Henley-On-Thames
State                        NaN
Country                      GBR
Half             0 days 01:34:26
40K              0 days 03:08:10
Pace                     0:07:37
TotalSeconds             11290.0
HalfSeconds               5666.0
Name: 8910, dtype: object
Henlow
 Age                          49
M/F                           F
City                     Henlow
State                       NaN
Country                     GBR
Half            0 days 01:56:36
40K             0 days 03:43:50
Pace                    0:09:01
TotalSeconds            13430.0
HalfSeconds              6996.0
Name: 31686, dtype: object
Henniker
 Age                          27
M/F                           F
City                   Henniker
State                        NH
Country                     USA
Half            0 days 01:39:54
40K             0 days 03:14:29
Pace                    0:07:51
TotalSeconds            11669.0
HalfSeconds              5994.0
Name: 13846, dtype: object
Henrico
 Age                          32
M/F                           M
City                    Henrico
State                        VA
Country                     USA
Half            0 days 01:32:36
40K             0 days 03:07:49
Pace                    0:07:42
TotalSeconds            11269.0
HalfSeconds              5556.0
Name: 4703, dtype: object
Herborn
 Age                          48
M/F                           M
City                    Herborn
State                       NaN
Country                     GER
Half            0 days 02:08:15
40K             0 days 04:31:17
Pace                    0:10:57
TotalSeconds            16277.0
HalfSeconds              7695.0
Name: 31750, dtype: object
Herculaneum
 Age                          31
M/F                           F
City                Herculaneum
State                        MO
Country                     USA
Half            0 days 02:07:50
40K             0 days 04:23:17
Pace                    0:10:36
TotalSeconds            15797.0
HalfSeconds              7670.0
Name: 17814, dtype: object
Hercules
 Age                          64
M/F                           M
City                   Hercules
State                        CA
Country                     USA
Half            0 days 01:56:23
40K             0 days 03:45:32
Pace                    0:09:05
TotalSeconds            13532.0
HalfSeconds              6983.0
Name: 21497, dtype: object
Heredia
 Age                          36
M/F                           F
City                    Heredia
State                       NaN
Country                     CRC
Half            0 days 01:30:09
40K             0 days 02:56:01
Pace                    0:07:07
TotalSeconds            10561.0
HalfSeconds              5409.0
Name: 9235, dtype: object
Herlev
 Age                          49
M/F                           M
City                     Herlev
State                       NaN
Country                     DEN
Half            0 days 02:01:58
40K             0 days 04:14:03
Pace                    0:10:17
TotalSeconds            15243.0
HalfSeconds              7318.0
Name: 30600, dtype: object
Hermannsburg
 Age                          27
M/F                           M
City               Hermannsburg
State                       NaN
Country                     GER
Half            0 days 01:33:44
40K             0 days 03:09:02
Pace                    0:07:39
TotalSeconds            11342.0
HalfSeconds              5624.0
Name: 2464, dtype: object
Hermantown
 Age                          35
M/F                           F
City                 Hermantown
State                        MN
Country                     USA
Half            0 days 01:46:04
40K             0 days 03:34:53
Pace                    0:08:40
TotalSeconds            12893.0
HalfSeconds              6364.0
Name: 15150, dtype: object
Hermitage
 Age                          42
M/F                           M
City                  Hermitage
State                        TN
Country                     USA
Half            0 days 01:30:51
40K             0 days 03:07:35
Pace                    0:07:38
TotalSeconds            11255.0
HalfSeconds              5451.0
Name: 4348, dtype: object
Hermonville
 Age                          40
M/F                           M
City                Hermonville
State                       NaN
Country                     FRA
Half            0 days 01:36:57
40K             0 days 03:18:40
Pace                    0:08:02
TotalSeconds            11920.0
HalfSeconds              5817.0
Name: 5516, dtype: object
Hermosa Beach
 Age                          32
M/F                           M
City              Hermosa Beach
State                        CA
Country                     USA
Half            0 days 01:24:18
40K             0 days 02:40:28
Pace                    0:06:30
TotalSeconds             9628.0
HalfSeconds              5058.0
Name: 5074, dtype: object
Hermosillo
 Age                          47
M/F                           M
City                 Hermosillo
State                       NaN
Country                     MEX
Half            0 days 01:39:31
40K             0 days 03:16:16
Pace                    0:08:06
TotalSeconds            11776.0
HalfSeconds              5971.0
Name: 11465, dtype: object
Hermosillo, Sonora
 Age                             43
M/F                              M
City            Hermosillo, Sonora
State                          NaN
Country                        MEX
Half               0 days 01:37:51
40K                0 days 03:10:24
Pace                       0:07:42
TotalSeconds               11424.0
HalfSeconds                 5871.0
Name: 7489, dtype: object
Herndon
 Age                          53
M/F                           M
City                    Herndon
State                        VA
Country                     USA
Half            0 days 01:41:12
40K             0 days 03:14:27

Herts
 Age                          50
M/F                           F
City                      Herts
State                       NaN
Country                     GBR
Half            0 days 01:41:22
40K             0 days 03:21:00
Pace                    0:08:08
TotalSeconds            12060.0
HalfSeconds              6082.0
Name: 14046, dtype: object
Herzogenaurach
 Age                          39
M/F                           M
City             Herzogenaurach
State                       NaN
Country                     GER
Half            0 days 01:44:51
40K             0 days 03:32:56
Pace                    0:08:37
TotalSeconds            12776.0
HalfSeconds              6291.0
Name: 29416, dtype: object
Heyworth
 Age                          43
M/F                           M
City                   Heyworth
State                        IL
Country                     USA
Half            0 days 01:37:05
40K             0 days 03:11:02
Pace                    0:07:43
TotalSeconds            11462.0
HalfSeconds              5825.0
Name: 8490, dtype: object
Hibbing
 Age                          33
M/F                           F
City                    Hibbing
State                        MN
Country                     USA
Half            0 days 01:45:52
40K             0 days 03:30:14
Pace                    0:08:30
TotalSeconds            12614.0
HalfSeconds              6352.0
Name: 17374, dtype: object
Hickory
 Age                          25
M/F                           F
City                    Hickory
State                        NC
Country                     USA
Half            0 days 01:51:01
40K             0 days 03:36:22
Pace                    0:08:44
TotalSeconds            12982.0
HalfSeconds              6661.0
Name: 18273, dtype: object
Hickory Creek
 Age                          30
M/F                           F
City              Hickory Creek
State                        TX
Country                     USA
Half            0 days 01:43:58
40K             0 days 03:23:17
Pace                    0:08:11
TotalSeconds            12197.0
HalfSeconds              6238.0
Name: 16722, dtype: object
Hidalgo
 Age                          40
M/F                           F
City                    Hidalgo
State                        TX
Country                     USA
Half            0 days 01:47:29
40K             0 days 03:29:44
Pace                    0:08:31
TotalSeconds            12584.0
HalfSeconds              6449.0
Name: 19095, dtype: object
Higganum
 Age                          52
M/F                           M
City                   Higganum
State                        CT
Country                     USA
Half            0 days 01:28:56
40K             0 days 03:02:12
Pace                    0:07:22
TotalSeconds            10932.0
HalfSeconds              5336.0
Name: 2810, dtype: object
High Point
 Age                          30
M/F                           M
City                 High Point
State                        NC
Country                     USA
Half            0 days 01:25:16
40K             0 days 02:44:17
Pace                    0:06:38
TotalSeconds             9857.0
HalfSeconds              5116.0
Name: 2833, dtype: object
High Springs
 Age                          62
M/F                           F
City               High Springs
State                        FL
Country                     USA
Half            0 days 01:53:49
40K             0 days 03:44:48
Pace                    0:09:05
TotalSeconds            13488.0
HalfSeconds              6829.0
Name: 24588, dtype: object
High Wycombe
 Age                          57
M/F                           M
City               High Wycombe
State                       NaN
Country                     GBR
Half            0 days 01:51:12
40K             0 days 03:45:15
Pace                    0:09:07
TotalSeconds            13515.0
HalfSeconds              6672.0
Name: 19083, dtype: object
Highland
 Age                          33
M/F                           M
City                   Highland
State                        UT
Country                     USA
Half            0 days 01:31:04
40K             0 days 03:19:12
Pace                    0:08:06
TotalSeconds            11952.0
HalfSeconds              5464.0
Name: 4848, dtype: object
Highland Park
 Age                          38
M/F                           M
City              Highland Park
State                        IL
Country                     USA
Half            0 days 01:26:01
40K             0 days 02:54:38
Pace                    0:07:04
TotalSeconds            10478.0
HalfSeconds              5161.0
Name: 2022, dtype: object
Highlands
 Age                          26
M/F                           F
City                  Highlands
State                        TX
Country                     USA
Half            0 days 01:45:07
40K             0 days 03:24:10
Pace                    0:08:16
TotalSeconds            12250.0
HalfSeconds              6307.0
Name: 7656, dtype: object
Highlands Ranch
 Age                          38
M/F                           M
City            Highlands Ranch
State                        CO
Country                     USA
Half            0 days 01:27:39
40K             0 days 02:48:30
Pace                    0:06:47
TotalSeconds            10110.0
HalfSeconds              5259.0
Name: 5020, dtype: object
Hillegom
 Age                          64
M/F                           M
City                   Hillegom
State                       NaN
Country                     NED
Half            0 days 02:03:53
40K             0 days 04:45:50
Pace                    0:11:31
TotalSeconds            17150.0
HalfSeconds              7433.0
Name: 31276, dtype: object
Hilliard
 Age                          35
M/F                           M
City                   Hilliard
State                        OH
Country                     USA
Half            0 days 01:25:38
40K             0 days 02:46:12
Pace                    0:06:42
TotalSeconds             9972.0
HalfSeconds              5138.0
Name: 1193, dtype: object
Hillsboro
 Age                          38
M/F                           M
City                  Hillsboro
State                        OR
Country                     USA
Half            0 days 01:28:22
40K             0 days 02:54:44
Pace                    0:07:05
TotalSeconds            10484.0
HalfSeconds              5302.0
Name: 5718, dtype: object
Hillsborough
 Age                          33
M/F                           M
City               Hillsborough
State                        NJ
Country                     USA
Half            0 days 01:30:25
40K             0 days 02:53:19
Pace                    0:06:59
TotalSeconds            10399.0
HalfSeconds              5425.0
Name: 5159, dtype: object
Hillsdale
 Age                          30
M/F                           M
City                  Hillsdale
State                        MI
Country                     USA
Half            0 days 01:29:00
40K             0 days 02:47:44
Pace                    0:06:45
TotalSeconds            10064.0
HalfSeconds              5340.0
Name: 738, dtype: object
Hilmar
 Age                          40
M/F                           F
City                     Hilmar
State                        CA
Country                     USA
Half            0 days 01:35:12
40K             0 days 03:03:53
Pace                    0:07:25
TotalSeconds            11033.0
HalfSeconds              5712.0
Name: 5625, dtype: object
Hilo
 Age                          45
M/F                           F
City                       Hilo
State                        HI
Country                     USA
Half            0 days 01:47:52
40K             0 days 03:30:33
Pace                    0:08:30
TotalSeconds            12633.0
HalfSeconds              6472.0
Name: 21170, dtype: object
Hilton
 Age                          26
M/F                           F
City                     Hilton
State                        NY
Country                     USA
Half            0 days 01:43:05
40K             0 days 03:19:22
Pace                    0:08:04
TotalSeconds            11962.0
HalfSeconds              6185.0
Name: 12917, dtype: object
Hilton Head
 Age                          53
M/F                           M
City                Hilton Head
State                        SC
Country                     USA
Half            0 days 01:39:22
40K             0 days 03:17:20
Pace                    0:07:58
TotalSeconds            11840.0
HalfSeconds              5962.0
Name: 16547, dtype: object
Hilton Head Island
 Age                             70
M/F                              M
City            Hilton Head Island
State                           SC
Country                        USA
Half               0 days 02:16:14
40K                0 days 04:41:54
Pace                       0:11:25
TotalSeconds               16914.0
HalfSeconds                 8174.0
Name: 15527, dtype: object
Himeji-Shi
 Age                          57
M/F                           M
City                 Himeji-Shi
State                       NaN
Country                     JPN
Half            0 days 02:16:29
40K             0 days 05:32:38
Pace                    0:13:31
TotalSeconds            19958.0
HalfSeconds              8189.0
Name: 7145, dtype: object
Hinckley
 Age                          53
M/F                           M
City                   Hinckley
State                        OH
Country                     USA
Half            0 days 01:42:56
40K             0 days 03:13:28
Pace                    0:07:47
TotalSeconds            11608.0
HalfSeconds              6176.0
Name: 14604, dtype: object
Hinesburg
 Age                          52
M/F                           M
City                  Hinesburg
State                        VT
Country                     USA
Half            0 days 01:48:18
40K             0 days 03:53:44
Pace                    0:09:32
TotalSeconds            14024.0
HalfSeconds              6498.0
Name: 15074, dtype: object
Hingham
 Age                          45
M/F                           M
City                    Hingham
State                        MA
Country                     USA
Half            0 days 01:37:52
40K             0 days 03:08:55
Pace                    0:07:39
TotalSeconds            11335.0
HalfSeconds              5872.0
Name: 10912, dtype: object
Hino-Shi, Tokyo
 Age                          47
M/F                           M
City            Hino-Shi, Tokyo
State                       NaN
Country                     JPN
Half            0 days 01:23:10
40K             0 days 02:45:40
Pace                    0:06:43
TotalSeconds             9940.0
HalfSeconds              4990.0
Name: 1247, dtype: object
Hinsdale
 Age                          55
M/F                           M
City                   Hinsdale
State                        IL
Country                     USA
Half            0 days 01:47:47
40K             0 days 03:25:23
Pace                    0:08:16
TotalSeconds            12323.0
HalfSeconds              6467.0
Name: 19705, dtype: object
Hirakata
 Age                          68
M/F                           M
City                   Hirakata
State                       NaN
Country                     JPN
Half            0 days 01:50:57
40K             0 days 03:54:51
Pace                    0:09:42
TotalSeconds            14091.0
HalfSeconds              6657.0
Name: 18489, dtype: object
Hiroshima
 Age                          65
M/F                           M
City                  Hiroshima
State                       NaN
Country                     JPN
Half            0 days 01:47:38
40K             0 days 03:34:50
Pace                    0:08:47
TotalSeconds            12890.0
HalfSeconds              6458.0
Name: 22711, dtype: object
Hitchcock
 Age                          57
M/F                           F
City                  Hitchcock
State                        TX
Country                     USA
Half            0 days 01:58:17
40K             0 days 03:57:32
Pace                    0:09:35
TotalSeconds            14252.0
HalfSeconds              7097.0
Name: 24497, dtype: object
Hitchin
 Age                          45
M/F                           F
City                    Hitchin
State                       NaN
Country                     GBR
Half            0 days 01:55:04
40K             0 days 03:52:08
Pace                    0:09:22
TotalSeconds            13928.0
HalfSeconds              6904.0
Name: 21973, dtype: object
Ho Ho Kus
 Age                          41
M/F                           M
City                  Ho Ho Kus
State                        NJ
Country                     USA
Half            0 days 01:49:38
40K             0 days 03:25:45
Pace                    0:08:14
TotalSeconds            12345.0
HalfSeconds              6578.0
Name: 4735, dtype: object
Ho-Ho-Kus
 Age                          22
M/F                           F
City                  Ho-Ho-Kus
State                        NJ
Country                     USA
Half            0 days 02:20:32
40K             0 days 05:03:27
Pace                    0:12:17
TotalSeconds            18207.0
HalfSeconds              8432.0
Name: 26283, dtype: object
Hobart
 Age                          41
M/F                           F
City                     Hobart
State                        IN
Country                     USA
Half            0 days 01:51:52
40K             0 days 03:36:43
Pace                    0:08:44
TotalSeconds            13003.0
HalfSeconds              6712.0
Name: 16831, dtype: object
Hobe Sound
 Age                          66
M/F                           F
City                 Hobe Sound
State                        FL
Country                     USA
Half            0 days 02:30:41
40K             0 days 05:00:35
Pace                    0:12:07
TotalSeconds            18035.0
HalfSeconds              9041.0
Name: 26068, dtype: object
Hobken
 Age                          26
M/F                           M
City                     Hobken
State                        NJ
Country                     USA
Half            0 days 01:55:04
40K             0 days 03:48:41
Pace                    0:09:12
TotalSeconds            13721.0
HalfSeconds              6904.0
Name: 29265, dtype: object
Hoboken
 Age                          33
M/F                           M
City                    Hoboken
State                        NJ
Country                     USA
Half            0 days 01:18:27
40K             0 days 02:30:18
Pace                    0:06:03
TotalSeconds             9018.0
HalfSeconds              4707.0
Name: 485, dtype: object
Hockessin
 Age                          43
M/F                           M
City                  Hockessin
State                        DE
Country                     USA
Half            0 days 01:29:45
40K             0 days 03:08:44
Pace                    0:07:39
TotalSeconds            11324.0
HalfSeconds              5385.0
Name: 5349, dtype: object
Hod Hasharon
 Age                          38
M/F                           M
City               Hod Hasharon
State                       NaN
Country                     ISR
Half            0 days 01:35:59
40K             0 days 03:21:27
Pace                    0:08:11
TotalSeconds            12087.0
HalfSeconds              5759.0
Name: 6447, dtype: object
Hoersholm
 Age                          38
M/F                           M
City                  Hoersholm
State                       NaN
Country                     DEN
Half            0 days 01:38:15
40K             0 days 03:24:59
Pace                    0:08:20
TotalSeconds            12299.0
HalfSeconds              5895.0
Name: 5494, dtype: object
Hoffman Estates
 Age                          49
M/F                           M
City            Hoffman Estates
State                        IL
Country                     USA
Half            0 days 01:31:44
40K             0 days 02:56:18
Pace                    0:07:08
TotalSeconds            10578.0
HalfSeconds              5504.0
Name: 4157, dtype: object
Hofheim
 Age                          56
M/F                           M
City                    Hofheim
State                       NaN
Country                     GER
Half            0 days 02:20:44
40K             0 days 04:36:31
Pace                    0:11:15
TotalSeconds            16591.0
HalfSeconds              8444.0
Name: 31029, dtype: object
Hofheim Am Taunus
 Age                            51
M/F                             M
City            Hofheim Am Taunus
State                         NaN
Country                       GER
Half              0 days 02:20:45
40K               0 days 04:36:31
Pace                      0:11:15
TotalSeconds              16591.0
HalfSeconds                8445.0
Name: 30838, dtype: object
Hohenbrunn
 Age                          46
M/F                           F
City                 Hohenbrunn
State                       NaN
Country                     GER
Half            0 days 01:51:15
40K             0 days 03:33:46
Pace                    0:08:38
TotalSeconds            12826.0
HalfSeconds              6675.0
Name: 21808, dtype: object
Holbrook
 Age                          51
M/F                           F
City                   Holbrook
State                        MA
Country                     USA
Half            0 days 01:52:16
40K             0 days 03:42:34
Pace                    0:09:00
TotalSeconds            13354.0
HalfSeconds              6736.0
Name: 27835, dtype: object
Holden
 Age                          26
M/F                           M
City                     Holden
State                        MA
Country                     USA
Half            0 days 01:19:06
40K             0 days 02:40:06
Pace                    0:06:31
TotalSeconds             9606.0
HalfSeconds              4746.0
Name: 351, dtype: object
Holderness
 Age                          44
M/F                           F
City                 Holderness
State                        NH
Country                     USA
Half            0 days 01:43:08
40K             0 days 03:52:22
Pace                    0:09:25
TotalSeconds            13942.0
HalfSeconds              6188.0
Name: 18613, dtype: object
Holladay
 Age                          41
M/F                           F
City                   Holladay
State                        UT
Country                     USA
Half            0 days 01:44:02
40K             0 days 03:27:10
Pace                    0:08:22
TotalSeconds            12430.0
HalfSeconds              6242.0
Name: 14400, dtype: object
Holland
 Age                          39
M/F                           M
City                    Holland
State                        NY
Country                     USA
Half            0 days 01:21:23
40K             0 days 02:38:06
Pace                    0:06:23
TotalSeconds             9486.0
HalfSeconds              4883.0
Name: 540, dtype: object
Holland Park West
 Age                            52
M/F                             M
City            Holland Park West
State                         NaN
Country                       AUS
Half              0 days 01:29:33
40K               0 days 02:55:46
Pace                      0:07:08
TotalSeconds              10546.0
HalfSeconds                5373.0
Name: 8050, dtype: object
Hollidaysburg
 Age                          39
M/F                           M
City              Hollidaysburg
State                        PA
Country                     USA
Half            0 days 01:29:17
40K             0 days 02:51:42
Pace                    0:06:54
TotalSeconds            10302.0
HalfSeconds              5357.0
Name: 2343, dtype: object
Hollis
 Age                          40
M/F                           F
City                     Hollis
State                        NH
Country                     USA
Half            0 days 01:38:59
40K             0 days 03:18:52

Honolulu
 Age                          33
M/F                           M
City                   Honolulu
State                        HI
Country                     USA
Half            0 days 01:30:16
40K             0 days 02:51:27
Pace                    0:06:53
TotalSeconds            10287.0
HalfSeconds              5416.0
Name: 4808, dtype: object
Hood River
 Age                          36
M/F                           F
City                 Hood River
State                        OR
Country                     USA
Half            0 days 01:46:36
40K             0 days 03:24:07
Pace                    0:08:14
TotalSeconds            12247.0
HalfSeconds              6396.0
Name: 19391, dtype: object
Hooksett
 Age                          48
M/F                           F
City                   Hooksett
State                        NH
Country                     USA
Half            0 days 01:36:21
40K             0 days 03:22:15
Pace                    0:08:20
TotalSeconds            12135.0
HalfSeconds              5781.0
Name: 12903, dtype: object
Hooper
 Age                          35
M/F                           F
City                     Hooper
State                        UT
Country                     USA
Half            0 days 01:46:33
40K             0 days 03:25:34
Pace                    0:08:16
TotalSeconds            12334.0
HalfSeconds              6393.0
Name: 18518, dtype: object
Hoover
 Age                          44
M/F                           M
City                     Hoover
State                        AL
Country                     USA
Half            0 days 01:36:29
40K             0 days 03:08:12
Pace                    0:07:34
TotalSeconds            11292.0
HalfSeconds              5789.0
Name: 1790, dtype: object
Hope
 Age                          55
M/F                           M
City                       Hope
State                        ID
Country                     USA
Half            0 days 01:43:15
40K             0 days 03:20:57
Pace                    0:08:07
TotalSeconds            12057.0
HalfSeconds              6195.0
Name: 15490, dtype: object
Hope Mills
 Age                          65
M/F                           M
City                 Hope Mills
State                        NC
Country                     USA
Half            0 days 02:00:08
40K             0 days 04:34:41
Pace                    0:11:11
TotalSeconds            16481.0
HalfSeconds              7208.0
Name: 24789, dtype: object
Hopedale
 Age                          34
M/F                           F
City                   Hopedale
State                        MA
Country                     USA
Half            0 days 02:09:51
40K             0 days 04:10:37
Pace                    0:10:05
TotalSeconds            15037.0
HalfSeconds              7791.0
Name: 28987, dtype: object
Hopewell
 Age                          55
M/F                           M
City                   Hopewell
State                        NJ
Country                     USA
Half            0 days 01:51:41
40K             0 days 03:32:08
Pace                    0:08:31
TotalSeconds            12728.0
HalfSeconds              6701.0
Name: 27522, dtype: object
Hopewell Junction
 Age                            60
M/F                             M
City            Hopewell Junction
State                          NY
Country                       USA
Half              0 days 01:53:05
40K               0 days 04:00:24
Pace                      0:09:42
TotalSeconds              14424.0
HalfSeconds                6785.0
Name: 10688, dtype: object
Hopkins
 Age                          40
M/F                           M
City                    Hopkins
State                        MN
Country                     USA
Half            0 days 01:29:21
40K             0 days 02:54:33
Pace                    0:07:03
TotalSeconds            10473.0
HalfSeconds              5361.0
Name: 3688, dtype: object
Hopkinton
 Age                          33
M/F                           M
City                  Hopkinton
State                        MA
Country                     USA
Half            0 days 01:21:23
40K             0 days 02:54:18
Pace                    0:07:03
TotalSeconds            10458.0
HalfSeconds              4883.0
Name: 987, dtype: object
Hoquiam
 Age                          41
M/F                           F
City                    Hoquiam
State                        WA
Country                     USA
Half            0 days 02:17:42
40K             0 days 04:52:01
Pace                    0:11:37
TotalSeconds            17521.0
HalfSeconds              8262.0
Name: 18574, dtype: object
Horning
 Age                          38
M/F                           M
City                    Horning
State                       NaN
Country                     DEN
Half            0 days 01:54:47
40K             0 days 04:00:45
Pace                    0:09:45
TotalSeconds            14445.0
HalfSeconds              6887.0
Name: 30296, dtype: object
Horsham
 Age                          36
M/F                           M
City                    Horsham
State                        PA
Country                     USA
Half            0 days 01:23:55
40K             0 days 02:41:32
Pace                    0:06:31
TotalSeconds             9692.0
HalfSeconds              5035.0
Name: 2078, dtype: object
Hortonville
 Age                          50
M/F                           M
City                Hortonville
State                        WI
Country                     USA
Half            0 days 01:48:44
40K             0 days 03:30:52
Pace                    0:08:32
TotalSeconds            12652.0
HalfSeconds              6524.0
Name: 13721, dtype: object
Hoschton
 Age                          60
M/F                           M
City                   Hoschton
State                        GA
Country                     USA
Half            0 days 01:52:18
40K             0 days 03:42:15
Pace                    0:09:03
TotalSeconds            13335.0
HalfSeconds              6738.0
Name: 19727, dtype: object
Hot Springs
 Age                          36
M/F                           M
City                Hot Springs
State                        AR
Country                     USA
Half            0 days 01:34:16
40K             0 days 03:07:15
Pace                    0:07:34
TotalSeconds            11235.0
HalfSeconds              5656.0
Name: 6477, dtype: object
Houghton Le Spring
 Age                             61
M/F                              F
City            Houghton Le Spring
State                          NaN
Country                        GBR
Half               0 days 01:55:44
40K                0 days 03:55:38
Pace                       0:09:33
TotalSeconds               14138.0
HalfSeconds                 6944.0
Name: 25132, dtype: object
Housatonic
 Age                          27
M/F                           M
City                 Housatonic
State                        MA
Country                     USA
Half            0 days 01:26:23
40K             0 days 03:14:16
Pace                    0:07:50
TotalSeconds            11656.0
HalfSeconds              5183.0
Name: 1353, dtype: object
Houston
 Age                          31
M/F                           M
City                    Houston
State                        TX
Country                     USA
Half            0 days 01:18:14
40K             0 days 02:33:00
Pace                    0:06:10
TotalSeconds             9180.0
HalfSeconds              4694.0
Name: 1097, dtype: object
Hovas
 Age                          59
M/F                           F
City                      Hovas
State                       NaN
Country                     SWE
Half            0 days 02:13:37
40K             0 days 04:29:18
Pace                    0:10:53
TotalSeconds            16158.0
HalfSeconds              8017.0
Name: 31497, dtype: object
Howell
 Age                          43
M/F                           F
City                     Howell
State                        MI
Country                     USA
Half            0 days 01:45:53
40K             0 days 03:28:37
Pace                    0:08:25
TotalSeconds            12517.0
HalfSeconds              6353.0
Name: 17447, dtype: object
Huacho
 Age                          47
M/F                           M
City                     Huacho
State                       NaN
Country                     PER
Half            0 days 01:32:15
40K             0 days 03:14:14
Pace                    0:08:06
TotalSeconds            11654.0
HalfSeconds              5535.0
Name: 12165, dtype: object
Hubbardston
 Age                          67
M/F                           M
City                Hubbardston
State                        MA
Country                     USA
Half            0 days 01:48:32
40K             0 days 03:38:11
Pace                    0:08:50
TotalSeconds            13091.0
HalfSeconds              6512.0
Name: 19064, dtype: object
Hubley
 Age                          53
M/F                           M
City                     Hubley
State                        NS
Country                     CAN
Half            0 days 01:26:17
40K             0 days 02:50:52
Pace                    0:06:53
TotalSeconds            10252.0
HalfSeconds              5177.0
Name: 1474, dtype: object
Hudson
 Age                          33
M/F                           M
City                     Hudson
State                        NH
Country                     USA
Half            0 days 01:26:25
40K             0 days 02:56:15
Pace                    0:07:07
TotalSeconds            10575.0
HalfSeconds              5185.0
Name: 3358, dtype: object
Hudsonville
 Age                          51
M/F                           M
City                Hudsonville
State                        MI
Country                     USA
Half            0 days 01:31:46
40K             0 days 03:04:25
Pace                    0:07:31
TotalSeconds            11065.0
HalfSeconds              5506.0
Name: 8604, dtype: object
Huixquilucan
 Age                          55
M/F                           M
City               Huixquilucan
State                       NaN
Country                     MEX
Half            0 days 01:42:07
40K             0 days 03:22:10
Pace                    0:08:10
TotalSeconds            12130.0
HalfSeconds              6127.0
Name: 16359, dtype: object
Huixquilucan, Edo De México
 Age                                      50
M/F                                       F
City            Huixquilucan, Edo De México
State                                   NaN
Country                                 MEX
Half                        0 days 01:48:45
40K                         0 days 03:32:10
Pace                                0:08:34
TotalSeconds                        12730.0
HalfSeconds                          6525.0
Name: 24203, dtype: object
Huixquilucan, Estado De Mexico
 Age                                         51
M/F                                          M
City            Huixquilucan, Estado De Mexico
State                                      NaN
Country                                    MEX
Half                           0 days 01:38:54
40K                            0 days 03:17:42
Pace                                   0:08:02
TotalSeconds                           11862.0
HalfSeconds                             5934.0
Name: 11848, dtype: object
Hull
 Age                          25
M/F                           M
City                       Hull
State                        MA
Country                     USA
Half            0 days 01:12:57
40K             0 days 02:23:40
Pace                    0:05:48
TotalSeconds             8620.0
HalfSeconds              4377.0
Name: 271, dtype: object
Hummelstown
 Age                          59
M/F                           M
City                Hummelstown
State                        PA
Country                     USA
Half            0 days 01:45:58
40K             0 days 03:29:12
Pace                    0:08:27
TotalSeconds            12552.0
HalfSeconds              6358.0
Name: 14654, dtype: object
Hundvag
 Age                          61
M/F                           M
City                    Hundvag
State                       NaN
Country                     NOR
Half            0 days 02:15:17
40K             0 days 05:00:37
Pace                    0:12:20
TotalSeconds            18037.0
HalfSeconds              8117.0
Name: 24262, dtype: object
Hunt
 Age                          67
M/F                           M
City                       Hunt
State                        NY
Country                     USA
Half            0 days 01:49:44
40K             0 days 03:45:56
Pace                    0:09:20
TotalSeconds            13556.0
HalfSeconds              6584.0
Name: 20553, dtype: object
Hunt Valley
 Age                          50
M/F                           F
City                Hunt Valley
State                        MD
Country                     USA
Half            0 days 01:52:13
40K             0 days 03:37:20
Pace                    0:08:45
TotalSeconds            13040.0
HalfSeconds              6733.0
Name: 17749, dtype: object
Huntersville
 Age                          40
M/F                           M
City               Huntersville
State                        NC
Country                     USA
Half            0 days 01:30:36
40K             0 days 02:55:03
Pace                    0:07:02
TotalSeconds            10503.0
HalfSeconds              5436.0
Name: 3306, dtype: object
Huntingdon
 Age                          49
M/F                           M
City                 Huntingdon
State                       NaN
Country                     GBR
Half            0 days 01:38:07
40K             0 days 03:14:27
Pace                    0:07:55
TotalSeconds            11667.0
HalfSeconds              5887.0
Name: 9513, dtype: object
Huntingdon Valley
 Age                            48
M/F                             M
City            Huntingdon Valley
State                          PA
Country                       USA
Half              0 days 01:34:11
40K               0 days 03:18:16
Pace                      0:08:01
TotalSeconds              11896.0
HalfSeconds                5651.0
Name: 7028, dtype: object
Huntington
 Age                          45
M/F                           M
City                 Huntington
State                        IN
Country                     USA
Half            0 days 01:32:42
40K             0 days 03:04:41
Pace                    0:07:28
TotalSeconds            11081.0
HalfSeconds              5562.0
Name: 7426, dtype: object
Huntington Beach
 Age                           50
M/F                            M
City            Huntington Beach
State                         CA
Country                      USA
Half             0 days 01:42:07
40K              0 days 03:14:23
Pace                     0:07:49
TotalSeconds             11663.0
HalfSeconds               6127.0
Name: 14461, dtype: object
Huntington Park
 Age                          50
M/F                           M
City            Huntington Park
State                        CA
Country                     USA
Half            0 days 01:28:17
40K             0 days 03:00:22
Pace                    0:07:20
TotalSeconds            10822.0
HalfSeconds              5297.0
Name: 4171, dtype: object
Huntington Station
 Age                             33
M/F                              M
City            Huntington Station
State                           NY
Country                        USA
Half               0 days 01:37:08
40K                0 days 03:31:00
Pace                       0:08:36
TotalSeconds               12660.0
HalfSeconds                 5828.0
Name: 2496, dtype: object
Huntington Woods
 Age                           49
M/F                            F
City            Huntington Woods
State                         MI
Country                      USA
Half             0 days 01:46:16
40K              0 days 03:31:14
Pace                     0:08:33
TotalSeconds             12674.0
HalfSeconds               6376.0
Name: 20488, dtype: object
Huntingtown
 Age                          54
M/F                           M
City                Huntingtown
State                        MD
Country                     USA
Half            0 days 01:50:21
40K             0 days 04:00:55
Pace                    0:09:49
TotalSeconds            14455.0
HalfSeconds              6621.0
Name: 13620, dtype: object
Huntley
 Age                          31
M/F                           M
City                    Huntley
State                        IL
Country                     USA
Half            0 days 01:30:03
40K             0 days 03:17:32
Pace                    0:08:02
TotalSeconds            11852.0
HalfSeconds              5403.0
Name: 2674, dtype: object
Huntsville
 Age                          29
M/F                           M
City                 Huntsville
State                        AL
Country                     USA
Half            0 days 01:23:22
40K             0 days 02:41:29
Pace                    0:06:33
TotalSeconds             9689.0
HalfSeconds              5002.0
Name: 2262, dtype: object
Hunzenschwil
 Age                          41
M/F                           M
City               Hunzenschwil
State                       NaN
Country                     SUI
Half            0 days 02:02:44
40K             0 days 03:47:28
Pace                    0:09:08
TotalSeconds            13648.0
HalfSeconds              7364.0
Name: 31375, dtype: object
Hurricane
 Age                          39
M/F                           M
City                  Hurricane
State                        UT
Country                     USA
Half            0 days 01:31:10
40K             0 days 02:57:47
Pace                    0:07:14
TotalSeconds            10667.0
HalfSeconds              5470.0
Name: 6045, dtype: object
Hurst
 Age                          32
M/F                           F
City                      Hurst
State                        TX
Country                     USA
Half            0 days 01:37:48
40K             0 days 03:10:04
Pace                    0:07:40
TotalSeconds            11404.0
HalfSeconds              5868.0
Name: 10770, dtype: object
Hutchinson
 Age                          55
M/F                           M
City                 Hutchinson
State                        MN
Country                     USA
Half            0 days 01:41:42
40K             0 days 03:27:39
Pace                    0:08:24
TotalSeconds            12459.0
HalfSeconds              6102.0
Name: 12280, dtype: object
Hyattsville
 Age                          29
M/F                           F
City                Hyattsville
State                        MD
Country                     USA
Half            0 days 01:34:17
40K             0 days 03:01:20
Pace                    0:07:17
TotalSeconds            10880.0
HalfSeconds              5657.0
Name: 11035, dtype: object
Hyde Park
 Age                          31
M/F                           M
City                  Hyde Park
State                        MA
Country                     USA
Half            0 days 01:41:28
40K             0 days 03:17:24
Pace                    0:07:58
TotalSeconds            11844.0
HalfSeconds              6088.0
Name: 22316, dtype: object
Hyougo Nishinomiya
 Age                             50
M/F                              M
City            Hyougo Nishinomiya
State                          NaN
Country                        JPN
Half               0 days 01:54:44
40K                0 days 04:35:44
Pace                       0:11:07
TotalSeconds               16544.0
HalfSeconds                 6884.0
Name: 6414, dtype: object
Hyrum
 Age                          59
M/F                           M
City                      Hyrum
State                        UT
Country                     USA

 Age                          23
M/F                           F
City                    Indiana
State                        PA
Country                     USA
Half            0 days 01:38:42
40K             0 days 03:11:17
Pace                    0:07:43
TotalSeconds            11477.0
HalfSeconds              5922.0
Name: 13859, dtype: object
Indianapolis
 Age                          25
M/F                           M
City               Indianapolis
State                        IN
Country                     USA
Half            0 days 01:18:59
40K             0 days 02:33:24
Pace                    0:06:12
TotalSeconds             9204.0
HalfSeconds              4739.0
Name: 1041, dtype: object
Indianola
 Age                          46
M/F                           M
City                  Indianola
State                        IA
Country                     USA
Half            0 days 01:33:08
40K             0 days 03:08:25
Pace                    0:07:37
TotalSeconds            11305.0
HalfSeconds              5588.0
Name: 6015, dtype: object
Indio
 Age                          33
M/F                           F
City                      Indio
State                        CA
Country                     USA
Half            0 days 01:42:16
40K             0 days 03:18:00
Pace                    0:07:58
TotalSeconds            11880.0
HalfSeconds              6136.0
Name: 17061, dtype: object
Industry
 Age                          31
M/F                           F
City                   Industry
State                        ME
Country                     USA
Half            0 days 01:44:08
40K             0 days 03:30:01
Pace                    0:08:29
TotalSeconds            12601.0
HalfSeconds              6248.0
Name: 17038, dtype: object
Ingersoll
 Age                          41
M/F                           F
City                  Ingersoll
State                        ON
Country                     CAN
Half            0 days 01:45:00
40K             0 days 03:24:30
Pace                    0:08:15
TotalSeconds            12270.0
HalfSeconds              6300.0
Name: 19625, dtype: object
Inglewood
 Age                          46
M/F                           M
City                  Inglewood
State                        CA
Country                     USA
Half            0 days 01:24:14
40K             0 days 02:46:43
Pace                    0:06:44
TotalSeconds            10003.0
HalfSeconds              5054.0
Name: 898, dtype: object
Ingolstadt
 Age                          45
M/F                           M
City                 Ingolstadt
State                       NaN
Country                     GER
Half            0 days 01:56:58
40K             0 days 03:45:14
Pace                    0:09:05
TotalSeconds            13514.0
HalfSeconds              7018.0
Name: 31206, dtype: object
Innisfil
 Age                          47
M/F                           F
City                   Innisfil
State                        ON
Country                     CAN
Half            0 days 01:54:05
40K             0 days 03:52:04
Pace                    0:09:24
TotalSeconds            13924.0
HalfSeconds              6845.0
Name: 22308, dtype: object
Inver Grove Heights
 Age                              54
M/F                               M
City            Inver Grove Heights
State                            MN
Country                         USA
Half                0 days 01:30:09
40K                 0 days 02:59:52
Pace                        0:07:16
TotalSeconds                10792.0
HalfSeconds                  5409.0
Name: 4495, dtype: object
Invercargill
 Age                          29
M/F                           F
City               Invercargill
State                       NaN
Country                     NZL
Half            0 days 01:40:28
40K             0 days 03:16:46
Pace                    0:07:57
TotalSeconds            11806.0
HalfSeconds              6028.0
Name: 16611, dtype: object
Ionia
 Age                          67
M/F                           M
City                      Ionia
State                        MI
Country                     USA
Half            0 days 01:57:05
40K             0 days 03:59:52
Pace                    0:09:56
TotalSeconds            14392.0
HalfSeconds              7025.0
Name: 18102, dtype: object
Iowa City
 Age                          28
M/F                           M
City                  Iowa City
State                        IA
Country                     USA
Half            0 days 01:23:25
40K             0 days 02:53:24
Pace                    0:07:05
TotalSeconds            10404.0
HalfSeconds              5005.0
Name: 1398, dtype: object
Ipswich
 Age                          41
M/F                           M
City                    Ipswich
State                        MA
Country                     USA
Half            0 days 01:31:07
40K             0 days 02:56:17
Pace                    0:07:09
TotalSeconds            10577.0
HalfSeconds              5467.0
Name: 4339, dtype: object
Ira Twp.
 Age                          42
M/F                           M
City                   Ira Twp.
State                        MI
Country                     USA
Half            0 days 01:34:24
40K             0 days 03:06:29
Pace                    0:07:32
TotalSeconds            11189.0
HalfSeconds              5664.0
Name: 7258, dtype: object
Irapuato
 Age                          47
M/F                           M
City                   Irapuato
State                       NaN
Country                     MEX
Half            0 days 01:28:49
40K             0 days 02:59:10
Pace                    0:07:17
TotalSeconds            10750.0
HalfSeconds              5329.0
Name: 4621, dtype: object
Irbid
 Age                          42
M/F                           M
City                      Irbid
State                       NaN
Country                     JOR
Half            0 days 01:29:27
40K             0 days 03:32:09
Pace                    0:08:37
TotalSeconds            12729.0
HalfSeconds              5367.0
Name: 3180, dtype: object
Irmo
 Age                          41
M/F                           M
City                       Irmo
State                        SC
Country                     USA
Half            0 days 01:35:50
40K             0 days 03:18:16
Pace                    0:08:04
TotalSeconds            11896.0
HalfSeconds              5750.0
Name: 8838, dtype: object
Iron Mountain
 Age                          37
M/F                           F
City              Iron Mountain
State                        MI
Country                     USA
Half            0 days 01:56:04
40K             0 days 04:02:58
Pace                    0:09:50
TotalSeconds            14578.0
HalfSeconds              6964.0
Name: 19467, dtype: object
Irondale
 Age                          32
M/F                           M
City                   Irondale
State                        AL
Country                     USA
Half            0 days 01:24:53
40K             0 days 02:43:25
Pace                    0:06:37
TotalSeconds             9805.0
HalfSeconds              5093.0
Name: 2542, dtype: object
Ironwood
 Age                          58
M/F                           M
City                   Ironwood
State                        MI
Country                     USA
Half            0 days 01:47:50
40K             0 days 03:33:49
Pace                    0:08:37
TotalSeconds            12829.0
HalfSeconds              6470.0
Name: 10497, dtype: object
Irvine
 Age                          31
M/F                           M
City                     Irvine
State                        CA
Country                     USA
Half            0 days 01:24:59
40K             0 days 02:44:51
Pace                    0:06:41
TotalSeconds             9891.0
HalfSeconds              5099.0
Name: 2751, dtype: object
Irving
 Age                          41
M/F                           M
City                     Irving
State                        TX
Country                     USA
Half            0 days 01:28:12
40K             0 days 02:53:01
Pace                    0:07:00
TotalSeconds            10381.0
HalfSeconds              5292.0
Name: 4372, dtype: object
Irvington
 Age                          45
M/F                           M
City                  Irvington
State                        NY
Country                     USA
Half            0 days 01:27:50
40K             0 days 02:51:06
Pace                    0:06:54
TotalSeconds            10266.0
HalfSeconds              5270.0
Name: 1591, dtype: object

Ise-City
 Age                          50
M/F                           M
City                   Ise-City
State                       NaN
Country                     JPN
Half            0 days 01:41:16
40K             0 days 03:39:43
Pace                    0:08:52
TotalSeconds            13183.0
HalfSeconds              6076.0
Name: 13706, dtype: object
Ishikawa
 Age                          39
M/F                           M
City                   Ishikawa
State                       NaN
Country                     JPN
Half            0 days 01:52:56
40K             0 days 03:43:16
Pace                    0:09:02
TotalSeconds            13396.0
HalfSeconds              6776.0
Name: 31666, dtype: object
Island Park
 Age                          52
M/F                           M
City                Island Park
State                        NY
Country                     USA
Half            0 days 01:35:38
40K             0 days 03:10:07
Pace                    0:07:41
TotalSeconds            11407.0
HalfSeconds              5738.0
Name: 14195, dtype: object
Isle
 Age                          29
M/F                           F
City                       Isle
State                        MN
Country                     USA
Half            0 days 01:32:58
40K             0 days 03:08:17
Pace                    0:07:39
TotalSeconds            11297.0
HalfSeconds              5578.0
Name: 8045, dtype: object
Isle Of Harris
 Age                          47
M/F                           M
City             Isle Of Harris
State                       NaN
Country                     GBR
Half            0 days 01:33:13
40K             0 days 03:14:07
Pace                    0:07:51
TotalSeconds            11647.0
HalfSeconds              5593.0
Name: 4563, dtype: object
Isleworth
 Age                          42
M/F                           F
City                  Isleworth
State                       NaN
Country                     GBR
Half            0 days 01:47:39
40K             0 days 00:00:00
Pace                    0:08:43
TotalSeconds                0.0
HalfSeconds              6459.0
Name: 14380, dtype: object
Islip
 Age                          45
M/F                           M
City                      Islip
State                        NY
Country                     USA
Half            0 days 01:36:31
40K             0 days 03:24:18
Pace                    0:08:15
TotalSeconds            12258.0
HalfSeconds              5791.0
Name: 8724, dtype: object
Isola Vicentina
 Age                          49
M/F                           M
City            Isola Vicentina
State                       NaN
Country                     ITA
Half            0 days 01:28:13
40K             0 days 02:56:05
Pace                    0:07:08
TotalSeconds            10565.0
HalfSeconds              5293.0
Name: 1523, dtype: object
Issaquah
 Age                          38
M/F                           M
City                   Issaquah
State                        WA
Country                     USA
Half            0 days 01:30:15
40K             0 days 02:55:07
Pace                    0:07:05
TotalSeconds            10507.0
HalfSeconds              5415.0
Name: 6060, dtype: object
Issy Les Moulineaux
 Age                              48
M/F                               M
City            Issy Les Moulineaux
State                           NaN
Country                         FRA
Half                0 days 01:48:31
40K                 0 days 03:27:26
Pace                        0:08:20
TotalSeconds                12446.0
HalfSeconds                  6511.0
Name: 5225, dtype: object
Itasca
 Age                          29
M/F                           F
City                     Itasca
State                        IL
Country                     USA
Half            0 days 01:48:23
40K             0 days 03:48:21
Pace                    0:09:14
TotalSeconds            13701.0
HalfSeconds              6503.0
Name: 16855, dtype: object
Iten
 Age                          27
M/F                           F
City                       Iten
State                       NaN
Country                     KEN
Half            0 days 01:15:32
40K             0 days 02:22:19
Pace                    0:05:46
TotalSeconds             8539.0
HalfSeconds              4532.0
Name: F11, dtype: object
Ithaca
 Age                          41
M/F                           F
City                     Ithaca
State                        NY
Country                     USA
Half            0 days 01:33:25
40K             0 days 02:56:22
Pace                    0:07:09
TotalSeconds            10582.0
HalfSeconds              5605.0
Name: 2225, dtype: object
Ivins
 Age                          36
M/F                           F
City                      Ivins
State                        UT
Country                     USA
Half            0 days 01:51:03
40K             0 days 03:51:29
Pace                    0:09:21
TotalSeconds            13889.0
HalfSeconds              6663.0
Name: 20369, dtype: object
Ivrea
 Age                          58
M/F                           F
City                      Ivrea
State                       NaN
Country                     ITA
Half            0 days 02:02:26
40K             0 days 03:58:17
Pace                    0:09:37
TotalSeconds            14297.0
HalfSeconds              7346.0
Name: 31827, dtype: object
Ivyland
 Age                          42
M/F                           F
City                    Ivyland
State                        PA
Country                     USA
Half            0 days 01:53:25
40K             0 days 03:46:05
Pace                    0:09:09
TotalSeconds            13565.0
HalfSeconds              6805.0
Name: 21586, dtype: object
Iyo-Gun
 Age                          34
M/F                           F
City                    Iyo-Gun
State                       NaN
Country                     JPN
Half            0 days 01:45:16
40K             0 days 03:26:12
Pace                    0:08:20
TotalSeconds            12372.0
HalfSeconds              6316.0
Name: 11756, dtype: object
Iztapalapa C P Mexico
 Age                                39
M/F                                 F
City            Iztapalapa C P Mexico
State                             NaN
Country                           MEX
Half                  0 days 01:39:56
40K                   0 days 03:23:39
Pace                          0:08:14
TotalSeconds                  12219.0
HalfSeconds                    5996.0
Name: 18456, dtype: object
Jacksboro
 Age                          34
M/F                           F
City                  Jacksboro
State                        TX
Country                     USA
Half            0 days 01:44:45
40K             0 days 03:30:18
Pace                    0:08:30
TotalSeconds            12618.0
HalfSeconds              6285.0
Name: 12394, dtype: object
Jackson
 Age                          21
M/F                           M
City                    Jackson
State                        MO
Country                     USA
Half            0 days 01:25:47
40K             0 days 02:59:09
Pace                    0:07:16
TotalSeconds            10749.0
HalfSeconds              5147.0
Name: 3866, dtype: object
Jackson Center
 Age                          31
M/F                           M
City             Jackson Center
State                        PA
Country                     USA
Half            0 days 01:24:06
40K             0 days 02:49:02
Pace                    0:06:50
TotalSeconds            10142.0
HalfSeconds              5046.0
Name: 470, dtype: object
Jackson Heights
 Age                          28
M/F                           F
City            Jackson Heights
State                        NY
Country                     USA
Half            0 days 01:37:07
40K             0 days 03:12:51
Pace                    0:07:47
TotalSeconds            11571.0
HalfSeconds              5827.0
Name: 10953, dtype: object
Jacksonville
 Age                          34
M/F                           F
City               Jacksonville
State                        FL
Country                     USA
Half            0 days 01:28:29
40K             0 days 02:49:27
Pace                    0:06:49
TotalSeconds            10167.0
HalfSeconds              5309.0
Name: 6470, dtype: object
Jacksonville Beach
 Age                             67
M/F                              M
City            Jacksonville Beach
State                           FL
Country                        USA
Half               0 days 01:59:34
40K                0 days 04:10:26
Pace                       0:10:07
TotalSeconds               15026.0
HalfSeconds                 7174.0
Name: 25096, dtype: object
Jakarta
 Age                          40
M/F                           M
City                    Jakarta
State                       NaN
Country                     INA
Half            0 days 01:35:03
40K             0 days 03:27:00
Pace                    0:08:22
TotalSeconds            12420.0
HalfSeconds              5703.0
Name: 8406, dtype: object
Jamaica
 Age                          44
M/F                           M
City                    Jamaica
State                        NY
Country                     USA
Half            0 days 01:26:16
40K             0 days 02:49:16
Pace                    0:06:51
TotalSeconds            10156.0
HalfSeconds              5176.0
Name: 2456, dtype: object
Jamaica Pain
 Age                          45
M/F                           M
City               Jamaica Pain
State                        MA
Country                     USA
Half            0 days 01:41:30
40K             0 days 03:29:06
Pace                    0:08:31
TotalSeconds            12546.0
HalfSeconds              6090.0
Name: 9571, dtype: object
Jamaica Plain
 Age                          29
M/F                           M
City              Jamaica Plain
State                        MA
Country                     USA
Half            0 days 01:20:19
40K             0 days 02:35:06
Pace                    0:06:15
TotalSeconds             9306.0
HalfSeconds              4819.0
Name: 1522, dtype: object
Jamesburg
 Age                          38
M/F                           F
City                  Jamesburg
State                        NJ
Country                     USA
Half            0 days 01:54:54
40K             0 days 03:49:06
Pace                    0:09:14
TotalSeconds            13746.0
HalfSeconds              6894.0
Name: 18569, dtype: object
Jamestown
 Age                          62
M/F                           M
City                  Jamestown
State                        RI
Country                     USA
Half            0 days 01:47:03
40K             0 days 03:30:00
Pace                    0:08:28
TotalSeconds            12600.0
HalfSeconds              6423.0
Name: 22126, dtype: object
Jamesville
 Age                          34
M/F                           F
City                 Jamesville
State                        NY
Country                     USA
Half            0 days 01:39:14
40K             0 days 03:18:34
Pace                    0:08:03
TotalSeconds            11914.0
HalfSeconds              5954.0
Name: 17341, dtype: object
Jamison
 Age                          50
M/F                           M
City                    Jamison
State                        PA
Country                     USA
Half            0 days 01:43:09
40K             0 days 03:36:56
Pace                    0:08:46
TotalSeconds            13016.0
HalfSeconds              6189.0
Name: 11184, dtype: object
Janesville
 Age                          42
M/F                           M
City                 Janesville
State                        CA
Country                     USA
Half            0 days 01:31:50
40K             0 days 03:08:31
Pace                    0:07:37
TotalSeconds            11311.0
HalfSeconds              5510.0
Name: 7635, dtype: object
Jardim Do Mar, Sao Bernardo Do Campo, Sp
 Age                                                   46
M/F                                                    F
City            Jardim Do Mar, Sao Bernardo Do Campo, Sp
State                                                NaN
Country                                              BRA
Half                                     0 days 01:49:48
40K                                      0 days 03:32:58
Pace                                             0:08:35
TotalSeconds                                     12778.0
HalfSeconds                                       6588.0
Name: 19440, dtype: object
Jardinopolis
 Age                          35
M/F                           M
City               Jardinopolis
State                       NaN
Country                     BRA
Half            0 days 01:45:23
40K             0 days 04:00:11
Pace                    0:10:07
TotalSeconds            14411.0
HalfSeconds              6323.0
Name: 676, dtype: object
Jarfalla
 Age                          53
M/F                           F
City                   Jarfalla
State                       NaN
Country                     SWE
Half            0 days 01:54:43
40K             0 days 03:47:03
Pace                    0:09:07
TotalSeconds            13623.0
HalfSeconds              6883.0
Name: 19936, dtype: object
Jasper
 Age                          45
M/F                           M
City                     Jasper
State                        IN
Country                     USA
Half            0 days 01:32:53
40K             0 days 03:34:13
Pace                    0:08:43
TotalSeconds            12853.0
HalfSeconds              5573.0
Name: 8935, dtype: object
Jbmdl
 Age                          27
M/F                           F
City                      Jbmdl
State                        NJ
Country                     USA
Half            0 days 01:41:36
40K             0 days 03:10:08
Pace                    0:07:37
TotalSeconds            11408.0
HalfSeconds              6096.0
Name: 13125, dtype: object
Jefferson
 Age                          24
M/F                           M
City                  Jefferson
State                        SD
Country                     USA
Half            0 days 01:20:27
40K             0 days 02:36:35
Pace                    0:06:20
TotalSeconds             9395.0
HalfSeconds              4827.0
Name: 559, dtype: object
Jefferson City
 Age                          29
M/F                           F
City             Jefferson City
State                        MO
Country                     USA
Half            0 days 01:36:59
40K             0 days 03:17:49
Pace                    0:08:02
TotalSeconds            11869.0
HalfSeconds              5819.0
Name: 18244, dtype: object
Jenison
 Age                          45
M/F                           M
City                    Jenison
State                        MI
Country                     USA
Half            0 days 01:50:39
40K             0 days 03:41:47
Pace                    0:08:57
TotalSeconds            13307.0
HalfSeconds              6639.0
Name: 12556, dtype: object
Jenkintown
 Age                          30
M/F                           F
City                 Jenkintown
State                        PA
Country                     USA
Half            0 days 01:54:13
40K             0 days 04:12:30
Pace                    0:10:11
TotalSeconds            15150.0
HalfSeconds              6853.0
Name: 18215, dtype: object
Jeonju City
 Age                          58
M/F                           M
City                Jeonju City
State                       NaN
Country                     KOR
Half            0 days 02:04:47
40K             0 days 04:24:54
Pace                    0:10:45
TotalSeconds            15894.0
HalfSeconds              7487.0
Name: 20288, dtype: object
Jericho
 Age                          49
M/F                           F
City                    Jericho
State                        VT
Country                     USA
Half            0 days 01:49:56
40K             0 days 03:37:13
Pace                    0:08:45
TotalSeconds            13033.0
HalfSeconds              6596.0
Name: 18327, dtype: object
Jermyn
 Age                          79
M/F                           M
City                     Jermyn
State                        PA
Country                     USA
Half            0 days 01:59:31
40K             0 days 03:52:17
Pace                    0:09:21
TotalSeconds            13937.0
HalfSeconds              7171.0
Name: 21932, dtype: object
Jerrabomberra
 Age                          46
M/F                           M
City              Jerrabomberra
State                       NaN
Country                     AUS
Half            0 days 01:27:11
40K             0 days 03:12:26
Pace                    0:07:51
TotalSeconds            11546.0
HalfSeconds              5231.0
Name: 12086, dtype: object
Jersey City
 Age                          30
M/F                           F
City                Jersey City
State                        NJ
Country                     USA
Half            0 days 01:34:23
40K             0 days 03:00:23
Pace                    0:07:16
TotalSeconds            10823.0
HalfSeconds              5663.0
Name: 8666, dtype: object
Jesenice-Osnice
 Age                          63
M/F                           M
City            Jesenice-Osnice
State                       NaN
Country                     CZE
Half            0 days 01:58:32
40K             0 days 04:02:10
Pace                    0:09:50
TotalSeconds            14530.0
HalfSeconds              7112.0
Name: 23250, dtype: object
Jessup
 Age                          49
M/F                           F
City                     Jessup
State                        PA
Country                     USA
Half            0 days 02:08:00
40K             0 days 04:44:37
Pace                    0:11:36
TotalSeconds            17077.0
HalfSeconds              7680.0
Name: 24242, dtype: object
Jesup
 Age                          47
M/F                           F
City                      Jesup
State                        GA
Country                     USA
Half            0 days 02:01:24
40K             0 days 04:23:20
Pace                    0:10:37
TotalSeconds            15800.0
HalfSeconds              7284.0
Name: 24439, dtype: object
Jewett City
 Age                          45
M/F                           F
City                Jewett City
State                        CT
Country                     USA
Half            0 days 02:47:59
40K             0 days 05:37:17
Pace                    0:13:36
TotalSeconds            20237.0
HalfSeconds             10079.0
Name: 30649, dtype: object
Jiangsu P.R. China
 Age                             46
M/F                              M
City            Jiangsu P.R. China
State                          NaN
Country                        CHN
Half               0 days 01:35:22
40K                0 days 03:23:51
Pace                       0:08:16
TotalSeconds               12231.0
HalfSeconds                 5722.0
Name: 11527, dtype: object
Jiangxi Province Of China

 Age                                    49
M/F                                     M
City            Jiangxi Province Of China
State                                 NaN
Country                               CHN
Half                      0 days 01:50:41
40K                       0 days 03:48:35
Pace                              0:09:16
TotalSeconds                      13715.0
HalfSeconds                        6641.0
Name: 11902, dtype: object
Joao Pessoa
 Age                          37
M/F                           M
City                Joao Pessoa
State                       NaN
Country                     BRA
Half            0 days 01:25:08
40K             0 days 02:46:06
Pace                    0:06:42
TotalSeconds             9966.0
HalfSeconds              5108.0
Name: 2648, dtype: object
Johanessburg
 Age                          63
M/F                           M
City               Johanessburg
State                       NaN
Country                     RSA
Half            0 days 01:36:49
40K             0 days 03:06:30
Pace                    0:07:31
TotalSeconds            11190.0
HalfSeconds              5809.0
Name: 10040, dtype: object
Johannesburg
 Age                          35
M/F                           M
City               Johannesburg
State                       NaN
Country                     RSA
Half            0 days 01:29:19
40K             0 days 02:55:03
Pace                    0:07:03
TotalSeconds            10503.0
HalfSeconds              5359.0
Name: 3838, dtype: object
Johns Creek
 Age                          52
M/F                           M
City                Johns Creek
State                        GA
Country                     USA
Half            0 days 01:43:44
40K             0 days 03:30:34
Pace                    0:08:33
TotalSeconds            12634.0
HalfSeconds              6224.0
Name: 14204, dtype: object
Johns Island
 Age                          35
M/F                           F
City               Johns Island
State                        SC
Country                     USA
Half            0 days 01:45:47
40K             0 days 03:29:19
Pace                    0:08:25
TotalSeconds            12559.0
HalfSeconds              6347.0
Name: 18455, dtype: object
Johnson City
 Age                          27
M/F                           M
City               Johnson City
State                        TN
Country                     USA
Half            0 days 01:16:16
40K             0 days 02:31:40
Pace                    0:06:10
TotalSeconds             9100.0
HalfSeconds              4576.0
Name: 197, dtype: object
Johnson Creek
 Age                          29
M/F                           F
City              Johnson Creek
State                        WI
Country                     USA
Half            0 days 01:34:47
40K             0 days 03:05:49
Pace                    0:07:29
TotalSeconds            11149.0
HalfSeconds              5687.0
Name: 7337, dtype: object
Johnsonville
 Age                          52
M/F                           M
City               Johnsonville
State                        NY
Country                     USA
Half            0 days 01:35:21
40K             0 days 03:19:28
Pace                    0:08:09
TotalSeconds            11968.0
HalfSeconds              5721.0
Name: 8728, dtype: object
Johnston
 Age                          49
M/F                           M
City                   Johnston
State                        RI
Country                     USA
Half            0 days 01:21:55
40K             0 days 02:43:46
Pace                    0:06:37
TotalSeconds             9826.0
HalfSeconds              4915.0
Name: 730, dtype: object
Johnstown
 Age                          51
M/F                           F
City                  Johnstown
State                        OH
Country                     USA
Half            0 days 01:57:08
40K             0 days 03:47:56
Pace                    0:09:11
TotalSeconds            13676.0
HalfSeconds              7028.0
Name: 23505, dtype: object
Joinville, SC - BRAZIL cep 89204-060
 Age                                               46
M/F                                                F
City            Joinville, SC - BRAZIL cep 89204-060
State                                            NaN
Country                                          BRA
Half                                 0 days 01:49:54
40K                                  0 days 03:36:21
Pace                                         0:08:45
TotalSeconds                                 12981.0
HalfSeconds                                   6594.0
Name: 20598, dtype: object
Joinville-Le-Pont
 Age                            29
M/F                             M
City            Joinville-Le-Pont
State                         NaN
Country                       FRA
Half              0 days 01:33:22
40K               0 days 03:06:03
Pace                      0:07:29
TotalSeconds              11163.0
HalfSeconds                5602.0
Name: 5202, dtype: object
Jolicure
 Age                          39
M/F                           F
City                   Jolicure
State                        NB
Country                     CAN
Half            0 days 01:35:47
40K             0 days 03:06:16
Pace                    0:07:32
TotalSeconds            11176.0
HalfSeconds              5747.0
Name: 8394, dtype: object
Jonesboro
 Age                          32
M/F                           F
City                  Jonesboro
State                        AR
Country                     USA
Half            0 days 01:49:53
40K             0 days 03:43:03
Pace                    0:09:04
TotalSeconds            13383.0
HalfSeconds              6593.0
Name: 14671, dtype: object
Jonesborough
 Age                          41
M/F                           M
City               Jonesborough
State                        TN
Country                     USA
Half            0 days 01:25:33
40K             0 days 02:55:35
Pace                    0:07:04
TotalSeconds            10535.0
HalfSeconds              5133.0
Name: 1014, dtype: object
Jonestown
 Age                          36
M/F                           F
City                  Jonestown
State                        PA
Country                     USA
Half            0 days 01:26:49
40K             0 days 02:49:47
Pace                    0:06:51
TotalSeconds            10187.0
HalfSeconds              5209.0
Name: 2485, dtype: object
Jonesville
 Age                          45
M/F                           M
City                 Jonesville
State                        VA
Country                     USA
Half            0 days 02:08:43
40K             0 days 04:28:42
Pace                    0:10:59
TotalSeconds            16122.0
HalfSeconds              7723.0
Name: 10810, dtype: object
Jonkoping
 Age                          42
M/F                           M
City                  Jonkoping
State                       NaN
Country                     SWE
Half            0 days 01:52:03
40K             0 days 03:45:34
Pace                    0:09:09
TotalSeconds            13534.0
HalfSeconds              6723.0
Name: 31503, dtype: object
Jonquiere
 Age                          45
M/F                           M
City                  Jonquiere
State                        QC
Country                     CAN
Half            0 days 01:21:23
40K             0 days 02:57:24
Pace                    0:07:16
TotalSeconds            10644.0
HalfSeconds              4883.0
Name: 1262, dtype: object
Joplin
 Age                          35
M/F                           M
City                     Joplin
State                        MO
Country                     USA
Half            0 days 01:27:25
40K             0 days 02:46:57
Pace                    0:06:43
TotalSeconds            10017.0
HalfSeconds              5245.0
Name: 1285, dtype: object
Joppa
 Age                          43
M/F                           F
City                      Joppa
State                        MD
Country                     USA
Half            0 days 01:51:13
40K             0 days 03:31:51
Pace                    0:08:30
TotalSeconds            12711.0
HalfSeconds              6673.0

Name: 20707, dtype: object
Joshua
 Age                          51
M/F                           F
City                     Joshua
State                        TX
Country                     USA
Half            0 days 01:57:09
40K             0 days 03:45:36
Pace                    0:09:06
TotalSeconds            13536.0
HalfSeconds              7029.0
Name: 24929, dtype: object
Jouy En Josas
 Age                          39
M/F                           F
City              Jouy En Josas
State                       NaN
Country                     FRA
Half            0 days 01:44:09
40K             0 days 03:22:35
Pace                    0:08:09
TotalSeconds            12155.0
HalfSeconds              6249.0
Name: 14311, dtype: object
Juiz De Fora
 Age                          46
M/F                           M
City               Juiz De Fora
State                       NaN
Country                     BRA
Half            0 days 01:55:35
40K             0 days 04:04:27
Pace                    0:10:06
TotalSeconds            14667.0
HalfSeconds              6935.0
Name: 1144, dtype: object
Jukskei Park
 Age                          37
M/F                           F
City               Jukskei Park
State                       NaN
Country                     RSA
Half            0 days 02:22:48
40K             0 days 04:26:13
Pace                    0:10:42
TotalSeconds            15973.0
HalfSeconds              8568.0
Name: 31625, dtype: object
Jundiai
 Age                          41
M/F                           M
City                    Jundiai
State                       NaN
Country                     BRA
Half            0 days 01:23:50
40K             0 days 02:53:13
Pace                    0:07:01
TotalSeconds            10393.0
HalfSeconds              5030.0
Name: 1489, dtype: object
Juneau
 Age                          42
M/F                           M
City                     Juneau
State                        AK
Country                     USA
Half            0 days 01:28:38
40K             0 days 03:05:47
Pace                    0:07:31
TotalSeconds            11147.0
HalfSeconds              5318.0
Name: 2532, dtype: object
Jupiter
 Age                          48
M/F                           M
City                    Jupiter
State                        FL
Country                     USA
Half            0 days 01:24:34
40K             0 days 02:49:07
Pace                    0:06:54
TotalSeconds            10147.0
HalfSeconds              5074.0
Name: 4133, dtype: object
Jurmala
 Age                          39
M/F                           F
City                    Jurmala
State                       NaN
Country                     LAT
Half            0 days 01:15:59
40K             0 days 02:24:35
Pace                    0:05:49
TotalSeconds             8675.0
HalfSeconds              4559.0
Name: F9, dtype: object
Justin
 Age                          52
M/F                           F
City                     Justin
State                        TX
Country                     USA
Half            0 days 03:11:00
40K             0 days 06:36:56
Pace                    0:15:59
TotalSeconds            23816.0
HalfSeconds             11460.0
Name: 26144, dtype: object
Kagoshima
 Age                          59
M/F                           M
City                  Kagoshima
State                       NaN
Country                     JPN
Half            0 days 01:46:08
40K             0 days 03:22:02
Pace                    0:08:10
TotalSeconds            12122.0
HalfSeconds              6368.0
Name: 19102, dtype: object
Kailua
 Age                          39
M/F                           M
City                     Kailua
State                        HI
Country                     USA
Half            0 days 01:32:35
40K             0 days 03:03:59
Pace                    0:07:27
TotalSeconds            11039.0
HalfSeconds              5555.0
Name: 6700, dtype: object
Kailua Kona
 Age                          40
M/F                           M
City                Kailua Kona
State                        HI
Country                     USA
Half            0 days 01:32:48
40K             0 days 03:05:18
Pace                    0:07:31
TotalSeconds            11118.0
HalfSeconds              5568.0
Name: 7278, dtype: object
Kailua-Kona
 Age                          57
M/F                           F
City                Kailua-Kona
State                        HI
Country                     USA
Half            0 days 01:56:41
40K             0 days 03:56:13
Pace                    0:09:34
TotalSeconds            14173.0
HalfSeconds              7001.0
Name: 24123, dtype: object
Kakamigahara, Gifu
 Age                             56
M/F                              M
City            Kakamigahara, Gifu
State                          NaN
Country                        JPN
Half               0 days 01:45:06
40K                0 days 03:29:17
Pace                       0:08:29
TotalSeconds               12557.0
HalfSeconds                 6306.0
Name: 18504, dtype: object
Kalama
 Age                          37
M/F                           F
City                     Kalama
State                        WA
Country                     USA
Half            0 days 01:56:55
40K             0 days 03:54:44
Pace                    0:09:28
TotalSeconds            14084.0
HalfSeconds              7015.0
Name: 20275, dtype: object
Kalamazoo
 Age                          23
M/F                           M
City                  Kalamazoo
State                        MI
Country                     USA
Half            0 days 01:14:21
40K             0 days 02:35:03
Pace                    0:06:17
TotalSeconds             9303.0
HalfSeconds              4461.0
Name: 137, dtype: object
Kalispell
 Age                          26
M/F                           F
City                  Kalispell
State                        MT
Country                     USA
Half            0 days 01:32:32
40K             0 days 03:03:18
Pace                    0:07:23
TotalSeconds            10998.0
HalfSeconds              5552.0
Name: 7161, dtype: object
Kamas
 Age                          37
M/F                           F
City                      Kamas
State                        UT
Country                     USA
Half            0 days 01:56:43
40K             0 days 04:03:23
Pace                    0:09:50
TotalSeconds            14603.0
HalfSeconds              7003.0
Name: 9947, dtype: object
Kamloops
 Age                          37
M/F                           M
City                   Kamloops
State                        BC
Country                     CAN
Half            0 days 01:34:29
40K             0 days 03:11:40
Pace                    0:07:47
TotalSeconds            11500.0
HalfSeconds              5669.0
Name: 6359, dtype: object
Kanagawa
 Age                          41
M/F                           F
City                   Kanagawa
State                       NaN
Country                     JPN
Half            0 days 01:35:02
40K             0 days 03:07:47
Pace                    0:07:35
TotalSeconds            11267.0
HalfSeconds              5702.0
Name: 8962, dtype: object
Kanagawa-Ken Pref.
 Age                             56
M/F                              M
City            Kanagawa-Ken Pref.
State                          NaN
Country                        JPN
Half               0 days 01:29:56
40K                0 days 03:00:38
Pace                       0:07:18
TotalSeconds               10838.0
HalfSeconds                 5396.0
Name: 2045, dtype: object
Kanata
 Age                          53
M/F                           M
City                     Kanata
State                        ON
Country                     CAN
Half            0 days 01:31:17
40K             0 days 03:06:06
Pace                    0:07:37
TotalSeconds            11166.0
HalfSeconds              5477.0
Name: 4620, dtype: object
Kandiyohi
 Age                          51
M/F                           M
City                  Kandiyohi
State                        MN
Country                     USA
Half            0 days 01:41:21
40K             0 days 03:40:56
Pace                    0:08:57
TotalSeconds            13256.0
HalfSeconds              6081.0
Name: 12961, dtype: object
Kaneohe
 Age                          51
M/F                           M
City                    Kaneohe
State                        HI
Country                     USA
Half            0 days 01:46:03
40K             0 days 03:16:30
Pace                    0:07:53
TotalSeconds            11790.0
HalfSeconds              6363.0
Name: 13948, dtype: object
Kangasala As
 Age                          49
M/F                           M
City               Kangasala As
State                       NaN
Country                     FIN
Half            0 days 01:46:22
40K             0 days 03:33:43
Pace                    0:08:38
TotalSeconds            12823.0
HalfSeconds              6382.0
Name: 9031, dtype: object
Kankakee
 Age                          66
M/F                           M
City                   Kankakee
State                        IL
Country                     USA
Half            0 days 01:56:38
40K             0 days 03:48:18
Pace                    0:09:11
TotalSeconds            13698.0
HalfSeconds              6998.0
Name: 24875, dtype: object
Kansas City
 Age                          29
M/F                           M
City                Kansas City
State                        MO
Country                     USA
Half            0 days 01:22:00
40K             0 days 02:47:16
Pace                    0:06:50
TotalSeconds            10036.0
HalfSeconds              4920.0
Name: 879, dtype: object
Kaohsiung
 Age                          24
M/F                           M
City                  Kaohsiung
State                       NaN
Country                     TWN
Half            0 days 01:23:36
40K             0 days 02:41:12
Pace                    0:06:32
TotalSeconds             9672.0
HalfSeconds              5016.0
Name: 2245, dtype: object
Kapchorwa
 Age                          29
M/F                           M
City                  Kapchorwa
State                       NaN
Country                     UGA
Half            0 days 01:06:45
40K             0 days 02:14:33
Pace                    0:05:32
TotalSeconds             8073.0
HalfSeconds              4005.0
Name: 15, dtype: object
Kappel
 Age                          41
M/F                           F
City                     Kappel
State                       NaN
Country                     SUI
Half            0 days 01:53:52
40K             0 days 03:40:47
Pace                    0:08:55
TotalSeconds            13247.0
HalfSeconds              6832.0
Name: 21015, dtype: object
Karachi
 Age                          47
M/F                           M
City                    Karachi
State                       NaN
Country                     PAK
Half            0 days 02:47:04
40K             0 days 05:30:31
Pace                    0:13:16
TotalSeconds            19831.0
HalfSeconds             10024.0
Name: 31808, dtype: object
Karrinyup
 Age                          45
M/F                           M
City                  Karrinyup
State                       NaN
Country                     AUS
Half            0 days 01:36:42
40K             0 days 03:11:20
Pace                    0:07:45
TotalSeconds            11480.0
HalfSeconds              5802.0
Name: 10496, dtype: object
Kars
 Age                          61
M/F                           M
City                       Kars
State                        ON
Country                     CAN
Half            0 days 01:53:27
40K             0 days 03:44:34
Pace                    0:09:04
TotalSeconds            13474.0
HalfSeconds              6807.0
Name: 23510, dtype: object
Karup
 Age                          42
M/F                           M
City                      Karup
State                       NaN
Country                     DEN
Half            0 days 01:27:08
40K             0 days 02:55:06
Pace                    0:07:05
TotalSeconds            10506.0
HalfSeconds              5228.0
Name: 1766, dtype: object
Kashiwa-Shi
 Age                          51
M/F                           F
City                Kashiwa-Shi
State                       NaN
Country                     JPN
Half            0 days 02:27:21
40K             0 days 04:57:33
Pace                    0:12:01
TotalSeconds            17853.0
HalfSeconds              8841.0
Name: 24908, dtype: object
Kasson
 Age                          21
M/F                           F
City                     Kasson
State                        MN
Country                     USA
Half            0 days 01:46:31
40K             0 days 03:31:37
Pace                    0:08:32
TotalSeconds            12697.0
HalfSeconds              6391.0
Name: 13389, dtype: object
Kathleen
 Age                          46
M/F                           M
City                   Kathleen
State                        GA
Country                     USA
Half            0 days 01:36:49
40K             0 days 03:25:31
Pace                    0:08:22
TotalSeconds            12331.0
HalfSeconds              5809.0
Name: 10706, dtype: object
Katonah
 Age                          55
M/F                           M
City                    Katonah
State                        NY
Country                     USA
Half            0 days 01:38:32
40K             0 days 03:13:23
Pace                    0:07:49
TotalSeconds            11603.0
HalfSeconds              5912.0
Name: 12818, dtype: object
Katy
 Age                          36
M/F                           M
City                       Katy
State                        TX
Country                     USA
Half            0 days 01:23:30
40K             0 days 02:40:34
Pace                    0:06:29
TotalSeconds             9634.0
HalfSeconds              5010.0
Name: 1235, dtype: object
Kaukauna
 Age                          37
M/F                           F
City                   Kaukauna
State                        WI
Country                     USA
Half            0 days 01:56:33
40K             0 days 04:17:59
Pace                    0:10:28
TotalSeconds            15479.0
HalfSeconds              6993.0
Name: 19351, dtype: object
Kaunas
 Age                          35
M/F                           M
City                     Kaunas
State                       NaN
Country                     LTU
Half            0 days 01:28:24
40K             0 days 02:54:55
Pace                    0:07:03
TotalSeconds            10495.0
HalfSeconds              5304.0
Name: 5100, dtype: object
Kauniainen
 Age                          43
M/F                           F
City                 Kauniainen
State                       NaN
Country                     FIN
Half            0 days 01:43:51
40K             0 days 03:41:06
Pace                    0:08:54
TotalSeconds            13266.0
HalfSeconds              6231.0
Name: 16747, dtype: object
Kawaguchi
 Age                          62
M/F                           M
City                  Kawaguchi
State                       NaN
Country                     JPN
Half            0 days 01:40:01
40K             0 days 03:21:29
Pace                    0:08:11
TotalSeconds            12089.0
HalfSeconds              6001.0
Name: 13708, dtype: object
Kawasaki
 Age                          34
M/F                           M
City                   Kawasaki
State                       NaN
Country                     JPN
Half            0 days 01:28:06
40K             0 days 02:57:43
Pace                    0:07:14
TotalSeconds            10663.0
HalfSeconds              5286.0
Name: 2797, dtype: object
Kawkawlin
 Age                          57
M/F                           F
City                  Kawkawlin
State                        MI
Country                     USA
Half            0 days 02:00:20
40K             0 days 04:25:36
Pace                    0:10:43
TotalSeconds            15936.0
HalfSeconds              7220.0
Name: 20159, dtype: object
Kaysville
 Age                          25
M/F                           M
City                  Kaysville
State                        UT
Country                     USA
Half            0 days 01:23:22
40K             0 days 02:41:36
Pace                    0:06:32
TotalSeconds             9696.0
HalfSeconds              5002.0
Name: 1667, dtype: object
Kearney
 Age                          26
M/F                           M
City                    Kearney
State                        NE
Country                     USA
Half            0 days 01:08:42
40K             0 days 02:19:14
Pace                    0:05:40
TotalSeconds             8354.0
HalfSeconds              4122.0
Name: 976, dtype: object
Kearny
 Age                          30
M/F                           M
City                     Kearny
State                        NJ
Country                     USA
Half            0 days 01:26:31
40K             0 days 02:51:02
Pace                    0:06:56
TotalSeconds            10262.0
HalfSeconds              5191.0
Name: 5276, dtype: object
Keedysville
 Age                          23
M/F                           F
City                Keedysville
State                        MD
Country                     USA
Half            0 days 01:49:47
40K             0 days 03:45:33
Pace                    0:09:10
TotalSeconds            13533.0
HalfSeconds              6587.0
Name: 14480, dtype: object
Keelung City
 Age                          53
M/F                           M
City               Keelung City
State                       NaN
Country                     TWN
Half            0 days 01:34:38
40K             0 days 03:40:50
Pace                    0:09:04
TotalSeconds            13250.0
HalfSeconds              5678.0
Name: 12453, dtype: object
Keene
 Age                          34
M/F                           M
City                      Keene
State                        NY
Country                     USA
Half            0 days 01:26:40
40K             0 days 02:48:29
Pace                    0:06:49
TotalSeconds            10109.0
HalfSeconds              5200.0
Name: 2373, dtype: object
Keeseville
 Age                          27
M/F                           M
City                 Keeseville
State                        NY
Country                     USA
Half            0 days 01:25:56
40K             0 days 02:52:26
Pace                    0:07:00
TotalSeconds            10346.0
HalfSeconds              5156.0
Name: 5214, dtype: object
Keiyo
 Age                          23
M/F                           F
City                      Keiyo
State                       NaN
Country                     KEN
Half            0 days 01:15:32
40K             0 days 02:23:57
Pace                    0:05:51
TotalSeconds             8637.0
HalfSeconds              4532.0
Name: F10, dtype: object

Keller
 Age                          50
M/F                           M
City                     Keller
State                        TX
Country                     USA
Half            0 days 01:35:58
40K             0 days 03:04:32
Pace                    0:07:26
TotalSeconds            11072.0
HalfSeconds              5758.0
Name: 9535, dtype: object
Kelowna
 Age                          48
M/F                           M
City                    Kelowna
State                        BC
Country                     CAN
Half            0 days 01:41:40
40K             0 days 03:25:32
Pace                    0:08:19
TotalSeconds            12332.0
HalfSeconds              6100.0
Name: 12555, dtype: object
Kelseyville
 Age                          70
M/F                           M
City                Kelseyville
State                        CA
Country                     USA
Half            0 days 02:09:14
40K             0 days 04:14:54
Pace                    0:10:15
TotalSeconds            15294.0
HalfSeconds              7754.0
Name: 25963, dtype: object
Kemptville
 Age                          46
M/F                           F
City                 Kemptville
State                        ON
Country                     CAN
Half            0 days 02:00:34
40K             0 days 04:03:35
Pace                    0:09:51
TotalSeconds            14615.0
HalfSeconds              7234.0
Name: 22762, dtype: object
Kenai
 Age                          56
M/F                           M
City                      Kenai
State                        AK
Country                     USA
Half            0 days 01:31:57
40K             0 days 03:14:13
Pace                    0:07:52
TotalSeconds            11653.0
HalfSeconds              5517.0
Name: 4896, dtype: object
Kendall
 Age                          53
M/F                           M
City                    Kendall
State                        NY
Country                     USA
Half            0 days 02:07:30
40K             0 days 04:46:23
Pace                    0:11:27
TotalSeconds            17183.0
HalfSeconds              7650.0
Name: 14907, dtype: object
Kenduskeag
 Age                          53
M/F                           M
City                 Kenduskeag
State                        ME
Country                     USA
Half            0 days 02:00:58
40K             0 days 04:07:41
Pace                    0:10:02
TotalSeconds            14861.0
HalfSeconds              7258.0
Name: 26018, dtype: object
Kenmore
 Age                          40
M/F                           M
City                    Kenmore
State                        WA
Country                     USA
Half            0 days 01:29:06
40K             0 days 03:03:51
Pace                    0:07:33
TotalSeconds            11031.0
HalfSeconds              5346.0
Name: 4640, dtype: object
Kennard
 Age                          55
M/F                           M
City                    Kennard
State                        TX
Country                     USA
Half            0 days 01:43:34
40K             0 days 03:26:55
Pace                    0:08:23
TotalSeconds            12415.0
HalfSeconds              6214.0
Name: 15341, dtype: object
Kennebunk
 Age                          37
M/F                           M
City                  Kennebunk
State                        ME
Country                     USA
Half            0 days 01:27:40
40K             0 days 02:51:07
Pace                    0:06:53
TotalSeconds            10267.0
HalfSeconds              5260.0
Name: 4107, dtype: object
Kennebunkport
 Age                          58
M/F                           F
City              Kennebunkport
State                        ME
Country                     USA
Half            0 days 02:40:48
40K             0 days 05:35:13
Pace                    0:13:29
TotalSeconds            20113.0
HalfSeconds              9648.0
Name: 26946, dtype: object
Kenner
 Age                          43
M/F                           M
City                     Kenner
State                        LA
Country                     USA
Half            0 days 02:41:02
40K             0 days 05:34:36
Pace                    0:13:33
TotalSeconds            20076.0
HalfSeconds              9662.0
Name: 32030, dtype: object
Kennesaw
 Age                          46
M/F                           M
City                   Kennesaw
State                        GA
Country                     USA
Half            0 days 01:25:57
40K             0 days 03:01:48
Pace                    0:07:21
TotalSeconds            10908.0
HalfSeconds              5157.0
Name: 6748, dtype: object
Kennett Square
 Age                          48
M/F                           M
City             Kennett Square
State                        PA
Country                     USA
Half            0 days 01:33:22
40K             0 days 03:03:42
Pace                    0:07:26
TotalSeconds            11022.0
HalfSeconds              5602.0
Name: 10677, dtype: object
Kenosha
 Age                          42
M/F                           F
City                    Kenosha
State                        WI
Country                     USA
Half            0 days 01:50:26
40K             0 days 03:34:59
Pace                    0:08:41
TotalSeconds            12899.0
HalfSeconds              6626.0
Name: 20322, dtype: object
Kenova
 Age                          42
M/F                           M
City                     Kenova
State                        WV
Country                     USA
Half            0 days 02:43:31
40K             0 days 05:29:28
Pace                    0:13:16
TotalSeconds            19768.0
HalfSeconds              9811.0
Name: 29496, dtype: object
Kensington
 Age                          32
M/F                           M
City                 Kensington
State                        NH
Country                     USA
Half            0 days 01:27:46
40K             0 days 02:57:22
Pace                    0:07:11
TotalSeconds            10642.0
HalfSeconds              5266.0
Name: 3254, dtype: object
Kent
 Age                          30
M/F                           F
City                       Kent
State                        WA
Country                     USA
Half            0 days 01:41:08
40K             0 days 03:15:57
Pace                    0:07:54
TotalSeconds            11757.0
HalfSeconds              6068.0
Name: 14478, dtype: object
Kent City
 Age                          52
M/F                           M
City                  Kent City
State                        MI
Country                     USA
Half            0 days 01:44:21
40K             0 days 03:54:46
Pace                    0:09:40
TotalSeconds            14086.0
HalfSeconds              6261.0
Name: 11766, dtype: object
Kentfield
 Age                          53
M/F                           M
City                  Kentfield
State                        CA
Country                     USA
Half            0 days 01:50:12
40K             0 days 03:32:19
Pace                    0:08:30
TotalSeconds            12739.0
HalfSeconds              6612.0
Name: 7689, dtype: object
Kents Hill
 Age                          54
M/F                           F
City                 Kents Hill
State                        ME
Country                     USA
Half            0 days 01:48:55
40K             0 days 03:40:53
Pace                    0:08:56
TotalSeconds            13253.0
HalfSeconds              6535.0
Name: 24878, dtype: object
Kentwood
 Age                          45
M/F                           M
City                   Kentwood
State                        MI
Country                     USA
Half            0 days 01:32:51
40K             0 days 03:07:15
Pace                    0:07:36
TotalSeconds            11235.0
HalfSeconds              5571.0
Name: 7559, dtype: object
Kerrville
 Age                          49
M/F                           M
City                  Kerrville
State                        TX
Country                     USA
Half            0 days 01:36:46
40K             0 days 03:10:08
Pace                    0:07:42
TotalSeconds            11408.0
HalfSeconds              5806.0
Name: 5526, dtype: object
Keswick
 Age                          21
M/F                           M
City                    Keswick
State                        VA
Country                     USA
Half            0 days 01:25:19
40K             0 days 02:50:13
Pace                    0:06:52
TotalSeconds            10213.0
HalfSeconds              5119.0
Name: 1400, dtype: object
Ketchum
 Age                          44
M/F                           F
City                    Ketchum
State                        ID
Country                     USA
Half            0 days 01:51:13
40K             0 days 03:39:10
Pace                    0:08:50
TotalSeconds            13150.0
HalfSeconds              6673.0
Name: 18684, dtype: object
Kettering
 Age                          28
M/F                           M
City                  Kettering
State                        OH
Country                     USA
Half            0 days 01:30:50
40K             0 days 02:54:25
Pace                    0:07:02
TotalSeconds            10465.0
HalfSeconds              5450.0
Name: 3605, dtype: object
Kewanee
 Age                          48
M/F                           M
City                    Kewanee
State                        IL
Country                     USA
Half            0 days 01:22:14
40K             0 days 02:42:21
Pace                    0:06:35
TotalSeconds             9741.0
HalfSeconds              4934.0
Name: 1183, dtype: object
Key Biscayne
 Age                          52
M/F                           M
City               Key Biscayne
State                        FL
Country                     USA
Half            0 days 02:01:49
40K             0 days 04:23:01
Pace                    0:10:40
TotalSeconds            15781.0
HalfSeconds              7309.0
Name: 29672, dtype: object
Kidman Park
 Age                          59
M/F                           M
City                Kidman Park
State                       NaN
Country                     AUS
Half            0 days 01:36:12
40K             0 days 03:12:43
Pace                    0:07:47
TotalSeconds            11563.0
HalfSeconds              5772.0
Name: 9594, dtype: object
Kiel
 Age                          24
M/F                           M
City                       Kiel
State                       NaN
Country                     GER
Half            0 days 01:29:33
40K             0 days 03:00:45
Pace                    0:07:17
TotalSeconds            10845.0
HalfSeconds              5373.0
Name: 4411, dtype: object
Kiev, Ukraine
 Age                          53
M/F                           M
City              Kiev, Ukraine
State                       NaN
Country                     UKR
Half            0 days 01:36:47
40K             0 days 03:15:37
Pace                    0:07:53
TotalSeconds            11737.0
HalfSeconds              5807.0
Name: 10262, dtype: object
Kihei
 Age                          36
M/F                           F
City                      Kihei
State                        HI
Country                     USA
Half            0 days 01:36:54
40K             0 days 03:12:33
Pace                    0:07:47
TotalSeconds            11553.0
HalfSeconds              5814.0
Name: 5891, dtype: object
Kilbride
 Age                          56
M/F                           M
City                   Kilbride
State                        ON
Country                     CAN
Half            0 days 01:47:39
40K             0 days 03:27:23
Pace                    0:08:23
TotalSeconds            12443.0
HalfSeconds              6459.0
Name: 19264, dtype: object
Kildeer
 Age                          45
M/F                           M
City                    Kildeer
State                        IL
Country                     USA
Half            0 days 01:41:48
40K             0 days 03:24:37
Pace                    0:08:20
TotalSeconds            12277.0
HalfSeconds              6108.0
Name: 27259, dtype: object
Kill Devil Hills
 Age                           36
M/F                            F
City            Kill Devil Hills
State                         NC
Country                      USA
Half             0 days 01:44:06
40K              0 days 03:27:54
Pace                     0:08:24
TotalSeconds             12474.0
HalfSeconds               6246.0
Name: 14824, dtype: object
Killeen
 Age                          25
M/F                           M
City                    Killeen
State                        TX
Country                     USA
Half            0 days 01:27:47
40K             0 days 02:56:16
Pace                    0:07:24
TotalSeconds            10576.0
HalfSeconds              5267.0
Name: 5166, dtype: object
Killen
 Age                          60
M/F                           M
City                     Killen
State                        AL
Country                     USA
Half            0 days 01:57:05
40K             0 days 04:14:20
Pace                    0:10:14
TotalSeconds            15260.0
HalfSeconds              7025.0
Name: 24307, dtype: object
Killingworth
 Age                          47
M/F                           F
City               Killingworth
State                        CT
Country                     USA
Half            0 days 02:14:18
40K             0 days 04:42:00
Pace                    0:11:19
TotalSeconds            16920.0
HalfSeconds              8058.0
Name: 29663, dtype: object
Kilsyth
 Age                          32
M/F                           F
City                    Kilsyth
State                       NaN
Country                     AUS
Half            0 days 01:57:39
40K             0 days 03:48:59
Pace                    0:09:15
TotalSeconds            13739.0
HalfSeconds              7059.0
Name: 31600, dtype: object
Kimberly
 Age                          53
M/F                           M
City                   Kimberly
State                        WI
Country                     USA
Half            0 days 01:47:45
40K             0 days 03:35:26
Pace                    0:08:44
TotalSeconds            12926.0
HalfSeconds              6465.0
Name: 14344, dtype: object
Kindred
 Age                          29
M/F                           M
City                    Kindred
State                        ND
Country                     USA
Half            0 days 01:32:54
40K             0 days 03:03:35
Pace                    0:07:24
TotalSeconds            11015.0
HalfSeconds              5574.0
Name: 3602, dtype: object
King City
 Age                          37
M/F                           F
City                  King City
State                        ON
Country                     CAN
Half            0 days 01:43:07
40K             0 days 03:21:59
Pace                    0:08:08
TotalSeconds            12119.0
HalfSeconds              6187.0
Name: 14032, dtype: object
King George
 Age                          36
M/F                           M
City                King George
State                        VA
Country                     USA
Half            0 days 01:30:50
40K             0 days 02:51:47
Pace                    0:06:53
TotalSeconds            10307.0
HalfSeconds              5450.0
Name: 6325, dtype: object
King Of Prussia
 Age                          41
M/F                           F
City            King Of Prussia
State                        PA
Country                     USA
Half            0 days 01:48:54
40K             0 days 03:33:11
Pace                    0:08:36
TotalSeconds            12791.0
HalfSeconds              6534.0
Name: 21178, dtype: object
Kings Lynn
 Age                          41
M/F                           M
City                 Kings Lynn
State                       NaN
Country                     GBR
Half            0 days 01:47:07
40K             0 days 03:49:37
Pace                    0:09:16
TotalSeconds            13777.0
HalfSeconds              6427.0
Name: 6146, dtype: object
Kings Mountain
 Age                          30
M/F                           F
City             Kings Mountain
State                        NC
Country                     USA
Half            0 days 01:40:00
40K             0 days 03:14:19
Pace                    0:07:50
TotalSeconds            11659.0
HalfSeconds              6000.0
Name: 13022, dtype: object
Kingsburg
 Age                          46
M/F                           M
City                  Kingsburg
State                        CA
Country                     USA
Half            0 days 01:41:36
40K             0 days 03:30:45
Pace                    0:08:33
TotalSeconds            12645.0
HalfSeconds              6096.0
Name: 11706, dtype: object
Kingsford
 Age                          51
M/F                           M
City                  Kingsford
State                        MI
Country                     USA
Half            0 days 01:36:22
40K             0 days 03:08:27
Pace                    0:07:36
TotalSeconds            11307.0
HalfSeconds              5782.0
Name: 6468, dtype: object
Kingsley
 Age                          42
M/F                           F
City                   Kingsley
State                        MI
Country                     USA
Half            0 days 01:59:12
40K             0 days 04:36:15
Pace                    0:11:16
TotalSeconds            16575.0
HalfSeconds              7152.0
Name: 21077, dtype: object
Kingsport
 Age                          41
M/F                           M
City                  Kingsport
State                        TN
Country                     USA
Half            0 days 01:38:29
40K             0 days 03:12:13
Pace                    0:07:45
TotalSeconds            11533.0
HalfSeconds              5909.0
Name: 8476, dtype: object
Kingston
 Age                          28
M/F                           F
City                   Kingston
State                        MA
Country                     USA
Half            0 days 01:29:02
40K             0 days 02:54:17
Pace                    0:07:02
TotalSeconds            10457.0
HalfSeconds              5342.0
Name: 5455, dtype: object
Kingston 5
 Age                          45
M/F                           M
City                 Kingston 5
State                       NaN
Country                     JAM
Half            0 days 01:37:37
40K             0 days 03:08:03
Pace                    0:07:35
TotalSeconds            11283.0
HalfSeconds              5857.0
Name: 11128, dtype: object
Kingston Springs
 Age                           25
M/F                            F
City            Kingston Springs
State                         TN
Country                      USA
Half             0 days 01:46:50
40K              0 days 03:40:05
Pace                     0:08:56
TotalSeconds             13205.0
HalfSeconds               6410.0
Name: 9495, dtype: object
Kingston Upon Hull
 Age                             43
M/F                              M
City            Kingston Upon Hull
State                          NaN
Country                        GBR
Half               0 days 01:21:51
40K                0 days 02:43:09
Pace                       0:06:38
TotalSeconds                9789.0
HalfSeconds                 4911.0
Name: 725, dtype: object
Kingsville
 Age                          23
M/F                           F
City                 Kingsville
State                        OH
Country                     USA
Half            0 days 01:30:20
40K             0 days 03:06:39
Pace                    0:07:37
TotalSeconds            11199.0
HalfSeconds              5420.0
Name: 3422, dtype: object
Kingwood
 Age                          32
M/F                           M
City                   Kingwood
State                        TX
Country                     USA
Half            0 days 01:23:54
40K             0 days 02:41:58
Pace                    0:06:32

Name: 21687, dtype: object
Knoxville
 Age                          35
M/F                           M
City                  Knoxville
State                        TN
Country                     USA
Half            0 days 01:25:30
40K             0 days 02:46:28
Pace                    0:06:43
TotalSeconds             9988.0
HalfSeconds              5130.0
Name: 3263, dtype: object
Kobenhavn N
 Age                          45
M/F                           M
City                Kobenhavn N
State                       NaN
Country                     DEN
Half            0 days 01:35:15
40K             0 days 03:29:57
Pace                    0:08:29
TotalSeconds            12597.0
HalfSeconds              5715.0
Name: 5845, dtype: object
Koenigsbronn
 Age                          59
M/F                           M
City               Koenigsbronn
State                       NaN
Country                     GER
Half            0 days 01:55:16
40K             0 days 03:45:28
Pace                    0:09:05
TotalSeconds            13528.0
HalfSeconds              6916.0
Name: 19776, dtype: object
Kohler
 Age                          67
M/F                           M
City                     Kohler
State                        WI
Country                     USA
Half            0 days 02:05:32
40K             0 days 04:07:58
Pace                    0:09:59
TotalSeconds            14878.0
HalfSeconds              7532.0
Name: 22811, dtype: object
Koka-City, Shiga
 Age                           60
M/F                            M
City            Koka-City, Shiga
State                        NaN
Country                      JPN
Half             0 days 01:54:21
40K              0 days 03:49:50
Pace                     0:09:19
TotalSeconds             13790.0
HalfSeconds               6861.0
Name: 23561, dtype: object
Kokomo
 Age                          43
M/F                           F
City                     Kokomo
State                        IN
Country                     USA
Half            0 days 01:49:06
40K             0 days 03:35:23
Pace                    0:08:45
TotalSeconds            12923.0
HalfSeconds              6546.0
Name: 21665, dtype: object
Komenda
 Age                          48
M/F                           F
City                    Komenda
State                       NaN
Country                     SLO
Half            0 days 02:04:03
40K             0 days 04:13:14
Pace                    0:10:12
TotalSeconds            15194.0
HalfSeconds              7443.0
Name: 24042, dtype: object
Komoka
 Age                          47
M/F                           F
City                     Komoka
State                        ON
Country                     CAN
Half            0 days 02:03:02
40K             0 days 04:03:56
Pace                    0:09:49
TotalSeconds            14636.0
HalfSeconds              7382.0
Name: 22662, dtype: object
Kongens Lyngby
 Age                          28
M/F                           M
City             Kongens Lyngby
State                       NaN
Country                     DEN
Half            0 days 01:29:38
40K             0 days 03:09:37
Pace                    0:07:45
TotalSeconds            11377.0
HalfSeconds              5378.0
Name: 4088, dtype: object
Kopavogur
 Age                          42
M/F                           M
City                  Kopavogur
State                       NaN
Country                     ISL
Half            0 days 01:30:55
40K             0 days 02:57:57
Pace                    0:07:12
TotalSeconds            10677.0
HalfSeconds              5455.0
Name: 5777, dtype: object
Kosice
 Age                          38
M/F                           M
City                     Kosice
State                       NaN
Country                     SVK
Half            0 days 01:30:49
40K             0 days 02:57:22
Pace                    0:07:10
TotalSeconds            10642.0
HalfSeconds              5449.0
Name: 4649, dtype: object
Kowloon
 Age                          48
M/F                           M
City                    Kowloon
State                       NaN
Country                     HKG
Half            0 days 01:32:09
40K             0 days 03:01:18
Pace                    0:07:19
TotalSeconds            10878.0
HalfSeconds              5529.0
Name: 10341, dtype: object
Kraainem
 Age                          37
M/F                           M
City                   Kraainem
State                       NaN
Country                     BEL
Half            0 days 01:37:36
40K             0 days 03:34:51
Pace                    0:08:46
TotalSeconds            12891.0
HalfSeconds              5856.0
Name: 6341, dtype: object
Krakow
 Age                          47
M/F                           F
City                     Krakow
State                        WI
Country                     USA
Half            0 days 02:01:42
40K             0 days 03:57:44
Pace                    0:09:34
TotalSeconds            14264.0
HalfSeconds              7302.0
Name: 23504, dtype: object
Kranj
 Age                          52
M/F                           F
City                      Kranj
State                       NaN
Country                     SLO
Half            0 days 02:01:53
40K             0 days 04:05:54
Pace                    0:09:54
TotalSeconds            14754.0
HalfSeconds              7313.0
Name: 29382, dtype: object
Kremmling
 Age                          28
M/F                           M
City                  Kremmling
State                        CO
Country                     USA
Half            0 days 01:34:18
40K             0 days 03:12:33
Pace                    0:07:51
TotalSeconds            11553.0
HalfSeconds              5658.0
Name: 2080, dtype: object
Kreuzlingen
 Age                          41
M/F                           M
City                Kreuzlingen
State                       NaN
Country                     SUI
Half            0 days 01:54:36
40K             0 days 03:53:32
Pace                    0:09:34
TotalSeconds            14012.0
HalfSeconds              6876.0
Name: 31538, dtype: object
Kriens
 Age                          35
M/F                           M
City                     Kriens
State                       NaN
Country                     SUI
Half            0 days 01:54:57
40K             0 days 03:50:26
Pace                    0:09:18
TotalSeconds            13826.0
HalfSeconds              6897.0
Name: 31530, dtype: object
Kristianssta
 Age                          56
M/F                           M
City               Kristianssta
State                       NaN
Country                     SWE
Half            0 days 01:45:06
40K             0 days 03:33:30
Pace                    0:08:42
TotalSeconds            12810.0
HalfSeconds              6306.0
Name: 19830, dtype: object
Kronberg
 Age                          53
M/F                           M
City                   Kronberg
State                       NaN
Country                     GER
Half            0 days 01:57:45
40K             0 days 03:57:54
Pace                    0:09:37
TotalSeconds            14274.0
HalfSeconds              7065.0
Name: 11126, dtype: object
Kronenwetter
 Age                          28
M/F                           F
City               Kronenwetter
State                        WI
Country                     USA
Half            0 days 01:44:50
40K             0 days 03:33:37
Pace                    0:08:38
TotalSeconds            12817.0
HalfSeconds              6290.0
Name: 13980, dtype: object
Kruibeke
 Age                          48
M/F                           M
City                   Kruibeke
State                       NaN
Country                     BEL
Half            0 days 01:28:07
40K             0 days 02:56:08
Pace                    0:07:09
TotalSeconds            10568.0
HalfSeconds              5287.0
Name: 6323, dtype: object
Kstovo
 Age                          48
M/F                           M
City                     Kstovo
State                       NaN
Country                     RUS
Half            0 days 01:29:33
40K             0 days 03:03:29
Pace                    0:07:24
TotalSeconds            11009.0
HalfSeconds              5373.0
Name: 4289, dtype: object
Kullavik
 Age                          68
M/F                           M
City                   Kullavik
State                       NaN
Country                     SWE
Half            0 days 02:03:43
40K             0 days 04:07:32
Pace                    0:10:00
TotalSeconds            14852.0
HalfSeconds              7423.0
Name: 25187, dtype: object
Kutztown
 Age                          50
M/F                           M
City                   Kutztown
State                        PA
Country                     USA
Half            0 days 01:43:32
40K             0 days 03:16:43
Pace                    0:07:56
TotalSeconds            11803.0
HalfSeconds              6212.0
Name: 14249, dtype: object
Kvanum
 Age                          33
M/F                           F
City                     Kvanum
State                       NaN
Country                     SWE
Half            0 days 01:58:21
40K             0 days 03:54:44
Pace                    0:09:30
TotalSeconds            14084.0
HalfSeconds              7101.0
Name: 31504, dtype: object
Kwun Tong, Kowloon
 Age                             35
M/F                              M
City            Kwun Tong, Kowloon
State                          NaN
Country                        HKG
Half               0 days 01:49:46
40K                0 days 03:37:27
Pace                       0:08:47
TotalSeconds               13047.0
HalfSeconds                 6586.0
Name: 2463, dtype: object
Kyiv
 Age                          29
M/F                           M
City                       Kyiv
State                       NaN
Country                     UKR
Half            0 days 01:30:11
40K             0 days 03:00:36
Pace                    0:07:17
TotalSeconds            10836.0
HalfSeconds              5411.0
Name: 4016, dtype: object
Kyoto
 Age                          51
M/F                           M
City                      Kyoto
State                       NaN
Country                     JPN
Half            0 days 01:41:18
40K             0 days 03:20:08
Pace                    0:08:06
TotalSeconds            12008.0
HalfSeconds              6078.0
Name: 14614, dtype: object
København S
 Age                          58
M/F                           M
City                København S
State                       NaN
Country                     DEN
Half            0 days 01:52:02
40K             0 days 03:32:28
Pace                    0:08:33
TotalSeconds            12748.0
HalfSeconds              6722.0
Name: 20128, dtype: object
L Assomption
 Age                          42
M/F                           M
City               L Assomption
State                        QC
Country                     CAN
Half            0 days 01:38:02
40K             0 days 03:22:23
Pace                    0:08:11
TotalSeconds            12143.0
HalfSeconds              5882.0
Name: 5668, dtype: object
L'Ancienne-Lorette
 Age                             42
M/F                              F
City            L'Ancienne-Lorette
State                           QC
Country                        CAN
Half               0 days 01:51:11
40K                0 days 03:30:47
Pace                       0:08:29
TotalSeconds               12647.0
HalfSeconds                 6671.0
Name: 21552, dtype: object
L'Assomption
 Age                          61
M/F                           M
City               L'Assomption
State                        QC
Country                     CAN
Half            0 days 01:53:11
40K             0 days 03:49:34
Pace                    0:09:17
TotalSeconds            13774.0
HalfSeconds              6791.0
Name: 21481, dtype: object
La Canada Flintridge
 Age                               45
M/F                                F
City            La Canada Flintridge
State                             CA
Country                          USA
Half                 0 days 01:52:18
40K                  0 days 03:41:54
Pace                         0:08:55
TotalSeconds                 13314.0
HalfSeconds                   6738.0
Name: 22510, dtype: object
La Crescenta
 Age                          51
M/F                           M
City               La Crescenta
State                        CA
Country                     USA
Half            0 days 01:41:26
40K             0 days 03:21:44
Pace                    0:08:10
TotalSeconds            12104.0
HalfSeconds              6086.0
Name: 7234, dtype: object
La Crosse
 Age                          29
M/F                           M
City                  La Crosse
State                        WI
Country                     USA
Half            0 days 01:31:28
40K             0 days 02:55:46
Pace                    0:07:05
TotalSeconds            10546.0
HalfSeconds              5488.0
Name: 5189, dtype: object
La Farlede
 Age                          43
M/F                           F
City                 La Farlede
State                       NaN
Country                     FRA
Half            0 days 02:00:08
40K             0 days 03:52:08
Pace                    0:09:25
TotalSeconds            13928.0
HalfSeconds              7208.0
Name: 20651, dtype: object
La Grange
 Age                          52
M/F                           M
City                  La Grange
State                        IL
Country                     USA
Half            0 days 01:33:45
40K             0 days 03:13:49
Pace                    0:07:49
TotalSeconds            11629.0
HalfSeconds              5625.0
Name: 6877, dtype: object
La Grange Park
 Age                          51
M/F                           M
City             La Grange Park
State                        IL
Country                     USA
Half            0 days 01:40:52
40K             0 days 03:14:08
Pace                    0:07:51
TotalSeconds            11648.0
HalfSeconds              6052.0
Name: 11619, dtype: object
La Habra
 Age                          39
M/F                           M
City                   La Habra
State                        CA
Country                     USA
Half            0 days 01:33:29
40K             0 days 03:16:30
Pace                    0:07:56
TotalSeconds            11790.0
HalfSeconds              5609.0
Name: 6537, dtype: object
La Habra Heights
 Age                           44
M/F                            F
City            La Habra Heights
State                         CA
Country                      USA
Half             0 days 01:55:41
40K              0 days 03:51:55
Pace                     0:09:21
TotalSeconds             13915.0
HalfSeconds               6941.0
Name: 20130, dtype: object
La Harpe
 Age                          24
M/F                           M
City                   La Harpe
State                        IL
Country                     USA
Half            0 days 01:34:29
40K             0 days 03:51:22
Pace                    0:09:20
TotalSeconds            13882.0
HalfSeconds              5669.0
Name: 3324, dtype: object
La Jolla
 Age                          48
M/F                           M
City                   La Jolla
State                        CA
Country                     USA
Half            0 days 01:31:41
40K             0 days 03:03:18
Pace                    0:07:26
TotalSeconds            10998.0
HalfSeconds              5501.0
Name: 3758, dtype: object
La Junta
 Age                          63
M/F                           M
City                   La Junta
State                        CO
Country                     USA
Half            0 days 01:49:51
40K             0 days 03:31:29
Pace                    0:08:32
TotalSeconds            12689.0
HalfSeconds              6591.0
Name: 21036, dtype: object
La Lucila, Buenos Aires
 Age                                  38
M/F                                   F
City            La Lucila, Buenos Aires
State                               NaN
Country                             ARG
Half                    0 days 01:39:29
40K                     0 days 03:13:14
Pace                            0:07:48
TotalSeconds                    11594.0
HalfSeconds                      5969.0
Name: 14010, dtype: object
La Malbaie
 Age                          49
M/F                           F
City                 La Malbaie
State                        QC
Country                     CAN
Half            0 days 01:45:44
40K             0 days 03:34:43
Pace                    0:08:45
TotalSeconds            12883.0
HalfSeconds              6344.0
Name: 14938, dtype: object
La Massana
 Age                          47
M/F                           M
City                 La Massana
State                       NaN
Country                     AND
Half            0 days 01:34:44
40K             0 days 03:08:26
Pace                    0:07:37
TotalSeconds            11306.0
HalfSeconds              5684.0
Name: 10145, dtype: object
La Mesa
 Age                          40
M/F                           M
City                    La Mesa
State                        CA
Country                     USA
Half            0 days 01:31:00
40K             0 days 03:03:41
Pace                    0:07:29
TotalSeconds            11021.0
HalfSeconds              5460.0
Name: 6715, dtype: object
La Porte
 Age                          61
M/F                           F
City                   La Porte
State                        TX
Country                     USA
Half            0 days 02:13:13
40K             0 days 04:28:32
Pace                    0:10:50
TotalSeconds            16112.0
HalfSeconds              7993.0
Name: 25932, dtype: object
La Prairie
 Age                          47
M/F                           M
City                 La Prairie
State                        QC
Country                     CAN
Half            0 days 01:40:04
40K             0 days 03:24:18
Pace                    0:08:21
TotalSeconds            12258.0
HalfSeconds              6004.0
Name: 11132, dtype: object
La Selva Beach
 Age                          35
M/F                           F
City             La Selva Beach
State                        CA
Country                     USA
Half            0 days 01:40:41
40K             0 days 03:15:50
Pace                    0:07:53
TotalSeconds            11750.0
HalfSeconds              6041.0
Name: 14742, dtype: object
La Verne
 Age                          46
M/F                           F
City                   La Verne
State                        CA
Country                     USA
Half            0 days 02:10:11
40K             0 days 04:22:57
Pace                    0:10:33
TotalSeconds            15777.0
HalfSeconds              7811.0
Name: 24186, dtype: object
La Vernia
 Age                          49
M/F                           M
City                  La Vernia
State                        TX
Country                     USA
Half            0 days 01:43:50
40K             0 days 03:29:12
Pace                    0:08:31
TotalSeconds            12552.0
HalfSeconds              6230.0
Name: 12272, dtype: object
Lac St-Joseph
 Age                          63
M/F                           F
City              Lac St-Joseph
State                        QC
Country                     CAN
Half            0 days 01:55:40
40K             0 days 03:54:20
Pace                    0:09:26
TotalSeconds            14060.0
HalfSeconds              6940.0
Name: 16876, dtype: object
Lac-Beauport
 Age                          41
M/F                           M
City               Lac-Beauport
State                        QC
Country                     CAN
Half            0 days 01:33:41
40K             0 days 03:10:37
Pace                    0:07:45
TotalSeconds            11437.0
HalfSeconds              5621.0
Name: 7310, dtype: object
Lacey
 Age                          42

Lake City
 Age                          43
M/F                           F
City                  Lake City
State                        FL
Country                     USA
Half            0 days 01:53:42
40K             0 days 03:50:14
Pace                    0:09:16
TotalSeconds            13814.0
HalfSeconds              6822.0
Name: 20648, dtype: object
Lake Elmo
 Age                          37
M/F                           M
City                  Lake Elmo
State                        MN
Country                     USA
Half            0 days 01:16:41
40K             0 days 02:26:14
Pace                    0:05:54
TotalSeconds             8774.0
HalfSeconds              4601.0
Name: 28, dtype: object
Lake Forest
 Age                          42
M/F                           M
City                Lake Forest
State                        IL
Country                     USA
Half            0 days 01:28:54
40K             0 days 02:54:46
Pace                    0:07:06
TotalSeconds            10486.0
HalfSeconds              5334.0
Name: 2137, dtype: object
Lake Forest Park
 Age                           51
M/F                            M
City            Lake Forest Park
State                         WA
Country                      USA
Half             0 days 01:50:34
40K              0 days 03:38:07
Pace                     0:08:48
TotalSeconds             13087.0
HalfSeconds               6634.0
Name: 13199, dtype: object
Lake Geneva
 Age                          37
M/F                           M
City                Lake Geneva
State                        WI
Country                     USA
Half            0 days 01:29:11
40K             0 days 02:59:16
Pace                    0:07:15
TotalSeconds            10756.0
HalfSeconds              5351.0
Name: 5930, dtype: object
Lake Grove
 Age                          40
M/F                           F
City                 Lake Grove
State                        NY
Country                     USA
Half            0 days 01:49:32
40K             0 days 03:32:34
Pace                    0:08:34
TotalSeconds            12754.0
HalfSeconds              6572.0
Name: 18774, dtype: object
Lake Havasu City
 Age                           57
M/F                            F
City            Lake Havasu City
State                         AZ
Country                      USA
Half             0 days 02:00:16
40K              0 days 03:50:50
Pace                     0:09:17
TotalSeconds             13850.0
HalfSeconds               7216.0
Name: 24799, dtype: object
Lake In The Hills
 Age                            40
M/F                             F
City            Lake In The Hills
State                          IL
Country                       USA
Half              0 days 01:51:40
40K               0 days 03:38:16
Pace                      0:08:47
TotalSeconds              13096.0
HalfSeconds                6700.0
Name: 21490, dtype: object
Lake Jackson
 Age                          56
M/F                           M
City               Lake Jackson
State                        TX
Country                     USA
Half            0 days 01:31:37
40K             0 days 03:03:36
Pace                    0:07:27
TotalSeconds            11016.0
HalfSeconds              5497.0
Name: 2318, dtype: object
Lake Jaclson
 Age                          54
M/F                           F
City               Lake Jaclson
State                        TX
Country                     USA
Half            0 days 02:09:53
40K             0 days 04:08:03
Pace                    0:09:58
TotalSeconds            14883.0
HalfSeconds              7793.0
Name: 22712, dtype: object
Lake Katrine
 Age                          53
M/F                           F
City               Lake Katrine
State                        NY
Country                     USA
Half            0 days 01:38:30
40K             0 days 03:12:21
Pace                    0:07:45
TotalSeconds            11541.0
HalfSeconds              5910.0
Name: 10033, dtype: object
Lake Mary
 Age                          39
M/F                           M
City                  Lake Mary
State                        FL
Country                     USA
Half            0 days 01:31:48
40K             0 days 03:05:50
Pace                    0:07:33
TotalSeconds            11150.0
HalfSeconds              5508.0
Name: 5101, dtype: object
Lake Orion
 Age                          50
M/F                           M
City                 Lake Orion
State                        MI
Country                     USA
Half            0 days 01:49:16
40K             0 days 03:50:18
Pace                    0:09:22
TotalSeconds            13818.0
HalfSeconds              6556.0
Name: 11750, dtype: object
Lake Oswego
 Age                          41
M/F                           M
City                Lake Oswego
State                        OR
Country                     USA
Half            0 days 01:19:52
40K             0 days 02:43:10
Pace                    0:06:34
TotalSeconds             9790.0
HalfSeconds              4792.0
Name: 619, dtype: object
Lake Placid
 Age                          51
M/F                           M
City                Lake Placid
State                        NY
Country                     USA
Half            0 days 01:41:44
40K             0 days 03:18:44
Pace                    0:08:01
TotalSeconds            11924.0
HalfSeconds              6104.0
Name: 11964, dtype: object
Lake Quivira
 Age                          49
M/F                           M
City               Lake Quivira
State                        KS
Country                     USA
Half            0 days 01:43:51
40K             0 days 03:20:21
Pace                    0:08:05
TotalSeconds            12021.0
HalfSeconds              6231.0
Name: 10240, dtype: object
Lake Ronkonkoma
 Age                          36
M/F                           F
City            Lake Ronkonkoma
State                        NY
Country                     USA
Half            0 days 01:49:05
40K             0 days 03:32:17
Pace                    0:08:33
TotalSeconds            12737.0
HalfSeconds              6545.0
Name: 12098, dtype: object
Lake Saint Louis
 Age                           43
M/F                            F
City            Lake Saint Louis
State                         MO
Country                      USA
Half             0 days 01:51:25
40K              0 days 03:34:40
Pace                     0:08:40
TotalSeconds             12880.0
HalfSeconds               6685.0
Name: 20909, dtype: object
Lake St Louis
 Age                          56
M/F                           M
City              Lake St Louis
State                        MO
Country                     USA
Half            0 days 01:47:46
40K             0 days 04:43:37
Pace                    0:11:18
TotalSeconds            17017.0
HalfSeconds              6466.0
Name: 19982, dtype: object
Lake Stevens
 Age                          66
M/F                           M
City               Lake Stevens
State                        WA
Country                     USA
Half            0 days 01:55:33
40K             0 days 03:44:40
Pace                    0:09:01
TotalSeconds            13480.0
HalfSeconds              6933.0
Name: 22070, dtype: object
Lake Tapps
 Age                          41
M/F                           F
City                 Lake Tapps
State                        WA
Country                     USA
Half            0 days 01:54:22
40K             0 days 03:39:42
Pace                    0:08:52
TotalSeconds            13182.0
HalfSeconds              6862.0
Name: 19253, dtype: object
Lake Worth
 Age                          44
M/F                           F
City                 Lake Worth
State                        FL
Country                     USA
Half            0 days 01:50:29
40K             0 days 03:34:07
Pace                    0:08:41
TotalSeconds            12847.0
HalfSeconds              6629.0
Name: 20976, dtype: object
Lakefield
 Age                          53
M/F                           F
City                  Lakefield
State                        ON
Country                     CAN
Half            0 days 02:02:41
40K             0 days 03:44:24
Pace                    0:09:00
TotalSeconds            13464.0
HalfSeconds              7361.0
Name: 22058, dtype: object
Lakeland
 Age                          28
M/F                           M
City                   Lakeland
State                        FL
Country                     USA
Half            0 days 01:29:31
40K             0 days 03:09:05
Pace                    0:07:38
TotalSeconds            11345.0
HalfSeconds              5371.0
Name: 2937, dtype: object
Lakemoor
 Age                          54
M/F                           M
City                   Lakemoor
State                        IL
Country                     USA
Half            0 days 01:32:19
40K             0 days 03:01:42
Pace                    0:07:22
TotalSeconds            10902.0
HalfSeconds              5539.0
Name: 5222, dtype: object
Lakeport
 Age                          25
M/F                           M
City                   Lakeport
State                        MI
Country                     USA
Half            0 days 01:21:04
40K             0 days 02:41:26
Pace                    0:06:32
TotalSeconds             9686.0
HalfSeconds              4864.0
Name: 1686, dtype: object
Lakesde
 Age                          52
M/F                           F
City                    Lakesde
State                        CA
Country                     USA
Half            0 days 01:42:38
40K             0 days 03:27:57
Pace                    0:08:23
TotalSeconds            12477.0
HalfSeconds              6158.0
Name: 18377, dtype: object
Lakeside
 Age                          45
M/F                           F
City                   Lakeside
State                        AZ
Country                     USA
Half            0 days 01:57:29
40K             0 days 03:48:05
Pace                    0:09:09
TotalSeconds            13685.0
HalfSeconds              7049.0
Name: 22672, dtype: object
Laketown
 Age                          37
M/F                           F
City                   Laketown
State                        UT
Country                     USA
Half            0 days 01:53:46
40K             0 days 03:36:22
Pace                    0:08:44
TotalSeconds            12982.0
HalfSeconds              6826.0
Name: 19504, dtype: object
Lakeville
 Age                          51
M/F                           M
City                  Lakeville
State                        MN
Country                     USA
Half            0 days 01:35:56
40K             0 days 03:03:07
Pace                    0:07:23
TotalSeconds            10987.0
HalfSeconds              5756.0
Name: 9583, dtype: object
Lakeway
 Age                          43
M/F                           M
City                    Lakeway
State                        TX
Country                     USA
Half            0 days 01:33:10
40K             0 days 03:12:55
Pace                    0:07:52
TotalSeconds            11575.0
HalfSeconds              5590.0
Name: 7029, dtype: object
Lakewood
 Age                          31
M/F                           M
City                   Lakewood
State                        OH
Country                     USA
Half            0 days 01:21:22
40K             0 days 02:43:09
Pace                    0:06:36
TotalSeconds             9789.0
HalfSeconds              4882.0
Name: 684, dtype: object
Lakewood Ranch
 Age                          24
M/F                           M
City             Lakewood Ranch
State                        FL
Country                     USA
Half            0 days 01:19:32
40K             0 days 02:48:37
Pace                    0:06:51
TotalSeconds            10117.0
HalfSeconds              4772.0
Name: 203, dtype: object
Lakwood
 Age                          32
M/F                           M
City                    Lakwood
State                        CO
Country                     USA
Half            0 days 02:05:44
40K             0 days 04:21:33
Pace                    0:10:34
TotalSeconds            15693.0
HalfSeconds              7544.0
Name: 29588, dtype: object
Lam Tin
 Age                          52
M/F                           F
City                    Lam Tin
State                       NaN
Country                     HKG
Half            0 days 01:58:28
40K             0 days 03:50:46
Pace                    0:09:19
TotalSeconds            13846.0
HalfSeconds              7108.0
Name: 24545, dtype: object
Lambertville
 Age                          23
M/F                           M
City               Lambertville
State                        NJ
Country                     USA
Half            0 days 01:20:50
40K             0 days 02:33:59
Pace                    0:06:13
TotalSeconds             9239.0
HalfSeconds              4850.0
Name: 727, dtype: object
Lancashire, England
 Age                              34
M/F                               M
City            Lancashire, England
State                           NaN
Country                         GBR
Half                0 days 01:25:55
40K                 0 days 02:47:47
Pace                        0:06:47
TotalSeconds                10067.0
HalfSeconds                  5155.0
Name: 3351, dtype: object
Lancaster
 Age                          33
M/F                           M
City                  Lancaster
State                        PA
Country                     USA
Half            0 days 01:22:33
40K             0 days 02:45:43
Pace                    0:06:44
TotalSeconds             9943.0
HalfSeconds              4953.0
Name: 505, dtype: object
Lanciano - Chieti
 Age                            54
M/F                             M
City            Lanciano - Chieti
State                         NaN
Country                       ITA
Half              0 days 01:46:13
40K               0 days 03:27:51
Pace                      0:08:21
TotalSeconds              12471.0
HalfSeconds                6373.0
Name: 8099, dtype: object
Land O Lakes
 Age                          38
M/F                           M
City               Land O Lakes
State                        FL
Country                     USA
Half            0 days 01:28:36
40K             0 days 02:49:53
Pace                    0:06:50
TotalSeconds            10193.0
HalfSeconds              5316.0
Name: 4451, dtype: object
Landenberg
 Age                          41
M/F                           F
City                 Landenberg
State                        PA
Country                     USA
Half            0 days 01:42:36
40K             0 days 03:19:15
Pace                    0:08:03
TotalSeconds            11955.0
HalfSeconds              6156.0
Name: 18782, dtype: object
Lander
 Age                          38
M/F                           M
City                     Lander
State                        WY
Country                     USA
Half            0 days 01:56:11
40K             0 days 03:39:06
Pace                    0:08:52
TotalSeconds            13146.0
HalfSeconds              6971.0
Name: 28713, dtype: object
Landsale
 Age                          57
M/F                           F
City                   Landsale
State                        PA
Country                     USA
Half            0 days 01:55:34
40K             0 days 03:46:19
Pace                    0:09:07
TotalSeconds            13579.0
HalfSeconds              6934.0
Name: 25199, dtype: object
Lane Cove
 Age                          31
M/F                           F
City                  Lane Cove
State                       NaN
Country                     AUS
Half            0 days 01:25:58
40K             0 days 02:52:35
Pace                    0:06:58
TotalSeconds            10355.0
HalfSeconds              5158.0
Name: 2325, dtype: object
Lanesborough
 Age                          21
M/F                           M
City               Lanesborough
State                        MA
Country                     USA
Half            0 days 01:26:38
40K             0 days 02:48:50
Pace                    0:06:50
TotalSeconds            10130.0
HalfSeconds              5198.0
Name: 3049, dtype: object
Langdon Hills
 Age                          42
M/F                           M
City              Langdon Hills
State                       NaN
Country                     GBR
Half            0 days 01:33:43
40K             0 days 03:08:33
Pace                    0:07:44
TotalSeconds            11313.0
HalfSeconds              5623.0
Name: 7263, dtype: object
Langford
 Age                          47
M/F                           F
City                   Langford
State                        SD
Country                     USA
Half            0 days 01:51:14
40K             0 days 03:37:19
Pace                    0:08:46
TotalSeconds            13039.0
HalfSeconds              6674.0
Name: 21110, dtype: object
Langhorne
 Age                          28
M/F                           M
City                  Langhorne
State                        PA
Country                     USA
Half            0 days 01:14:46
40K             0 days 02:28:56
Pace                    0:06:03
TotalSeconds             8936.0
HalfSeconds              4486.0
Name: 199, dtype: object
Langley
 Age                          47
M/F                           M
City                    Langley
State                        BC
Country                     CAN
Half            0 days 01:39:58
40K             0 days 03:19:37
Pace                    0:08:03
TotalSeconds            11977.0
HalfSeconds              5998.0
Name: 10919, dtype: object
Lansdale
 Age                          46
M/F                           M
City                   Lansdale
State                        PA
Country                     USA
Half            0 days 01:26:00
40K             0 days 02:49:33
Pace                    0:06:51
TotalSeconds            10173.0
HalfSeconds              5160.0
Name: 1116, dtype: object
Lansdowne
 Age                          46
M/F                           M
City                  Lansdowne
State                        VA
Country                     USA
Half            0 days 01:35:11
40K             0 days 03:04:25
Pace                    0:07:29
TotalSeconds            11065.0
HalfSeconds              5711.0
Name: 11372, dtype: object
Lansing
 Age                          62
M/F                           M
City                    Lansing
State                        IL
Country                     USA
Half            0 days 01:47:07
40K             0 days 03:28:24
Pace                    0:08:25
TotalSeconds            12504.0
HalfSeconds              6427.0
Name: 22701, dtype: object
Lantau
 Age                          46
M/F                           M
City                     Lantau
State                       NaN
Country                     HKG
Half            0 days 01:35:07
40K             0 days 03:11:09
Pace                    0:07:42
TotalSeconds            11469.0
HalfSeconds              5707.0
Name: 10761, dtype: object
Lapeer
 Age                          70
M/F                           M
City                     Lapeer
State                        MI
Country                     USA
Half            0 days 02:02:09
40K             0 days 04:12:38
Pace                    0:10:12
TotalSeconds            15158.0
HalfSeconds              7329.0
Name: 25834, dtype: object
Laporte
 Age                          53
M/F                           F
City                    Laporte
State                        TX
Country                     USA
Half            0 days 01:42:00
40K             0 days 03:36:49
Pace                    0:08:48
TotalSeconds            13009.0
HalfSeconds              6120.0
Name: 16745, dtype: object
Laramie
 Age                          37
M/F                           M
City                    Laramie
State                        WY

Le Mans
 Age                          67
M/F                           M
City                    Le Mans
State                       NaN
Country                     FRA
Half            0 days 01:38:58
40K             0 days 03:11:57
Pace                    0:07:45
TotalSeconds            11517.0
HalfSeconds              5938.0
Name: 9573, dtype: object
Le Pellerin
 Age                          74
M/F                           M
City                Le Pellerin
State                       NaN
Country                     FRA
Half            0 days 02:16:56
40K             0 days 04:42:06
Pace                    0:11:22
TotalSeconds            16926.0
HalfSeconds              8216.0
Name: 30069, dtype: object
Le Perray En Yvelines
 Age                                46
M/F                                 M
City            Le Perray En Yvelines
State                             NaN
Country                           FRA
Half                  0 days 01:40:58
40K                   0 days 03:19:39
Pace                          0:08:04
TotalSeconds                  11979.0
HalfSeconds                    6058.0
Name: 12746, dtype: object
Le Roy
 Age                          38
M/F                           M
City                     Le Roy
State                        IL
Country                     USA
Half            0 days 01:39:31
40K             0 days 03:35:04
Pace                    0:08:41
TotalSeconds            12904.0
HalfSeconds              5971.0
Name: 6140, dtype: object
League City
 Age                          37
M/F                           M
City                League City
State                        TX
Country                     USA
Half            0 days 01:30:06
40K             0 days 03:16:13
Pace                    0:08:02
TotalSeconds            11773.0
HalfSeconds              5406.0
Name: 4147, dtype: object
Leamington
 Age                          35
M/F                           F
City                 Leamington
State                        ON
Country                     CAN
Half            0 days 01:43:51
40K             0 days 03:28:48
Pace                    0:08:25
TotalSeconds            12528.0
HalfSeconds              6231.0
Name: 9254, dtype: object
Leamington Spa
 Age                          27
M/F                           M
City             Leamington Spa
State                       NaN
Country                     GBR
Half            0 days 01:27:59
40K             0 days 02:59:27
Pace                    0:07:15
TotalSeconds            10767.0
HalfSeconds              5279.0
Name: 4678, dtype: object
Leander
 Age                          36
M/F                           F
City                    Leander
State                        TX
Country                     USA
Half            0 days 01:40:46
40K             0 days 03:46:30
Pace                    0:09:09
TotalSeconds            13590.0
HalfSeconds              6046.0
Name: 14150, dtype: object
Leavenworth
 Age                          52
M/F                           M
City                Leavenworth
State                        WA
Country                     USA
Half            0 days 01:38:40
40K             0 days 03:09:11
Pace                    0:07:38
TotalSeconds            11351.0
HalfSeconds              5920.0
Name: 11963, dtype: object
Leawood
 Age                          47
M/F                           M
City                    Leawood
State                        KS
Country                     USA
Half            0 days 01:31:32
40K             0 days 03:07:23
Pace                    0:07:37
TotalSeconds            11243.0
HalfSeconds              5492.0
Name: 8470, dtype: object
Lebanon
 Age                          46
M/F                           M
City                    Lebanon
State                        NH
Country                     USA
Half            0 days 01:22:11
40K             0 days 02:40:39
Pace                    0:06:29
TotalSeconds             9639.0
HalfSeconds              4931.0
Name: 969, dtype: object
Lecce
 Age                          44
M/F                           M
City                      Lecce
State                       NaN
Country                     ITA
Half            0 days 01:25:04
40K             0 days 02:47:01
Pace                    0:06:44
TotalSeconds            10021.0
HalfSeconds              5104.0
Name: 3652, dtype: object
Lecco - Lc
 Age                          41
M/F                           M
City                 Lecco - Lc
State                       NaN
Country                     ITA
Half            0 days 01:35:25
40K             0 days 03:24:03
Pace                    0:08:21
TotalSeconds            12243.0
HalfSeconds              5725.0
Name: 5778, dtype: object
Ledyard
 Age                          49
M/F                           F
City                    Ledyard
State                        CT
Country                     USA
Half            0 days 01:49:44
40K             0 days 03:42:36
Pace                    0:09:00
TotalSeconds            13356.0
HalfSeconds              6584.0
Name: 20485, dtype: object
Lee
 Age                          55
M/F                           M
City                        Lee
State                        MA
Country                     USA
Half            0 days 01:35:07
40K             0 days 03:04:33
Pace                    0:07:26
TotalSeconds            11073.0
HalfSeconds              5707.0
Name: 6273, dtype: object
Leeds
 Age                          42
M/F                           M
City                      Leeds
State                       NaN
Country                     GBR
Half            0 days 01:31:14
40K             0 days 03:01:00
Pace                    0:07:20
TotalSeconds            10860.0
HalfSeconds              5474.0
Name: 6693, dtype: object
Leefdaal
 Age                          56
M/F                           M
City                   Leefdaal
State                       NaN
Country                     BEL
Half            0 days 01:56:08
40K             0 days 03:57:48
Pace                    0:09:39
TotalSeconds            14268.0
HalfSeconds              6968.0
Name: 31289, dtype: object
Lees Summit
 Age                          44
M/F                           M
City                Lees Summit
State                        MO
Country                     USA
Half            0 days 01:33:22
40K             0 days 03:04:12
Pace                    0:07:27
TotalSeconds            11052.0
HalfSeconds              5602.0
Name: 8420, dtype: object
Leesburg
 Age                          37
M/F                           F
City                   Leesburg
State                        VA
Country                     USA
Half            0 days 01:42:12
40K             0 days 03:20:15
Pace                    0:08:06
TotalSeconds            12015.0
HalfSeconds              6132.0
Name: 13043, dtype: object
Leetsdale
 Age                          37
M/F                           M
City                  Leetsdale
State                        PA
Country                     USA
Half            0 days 01:31:43
40K             0 days 03:16:29
Pace                    0:07:59
TotalSeconds            11789.0
HalfSeconds              5503.0
Name: 5309, dtype: object
Legazpi
 Age                          38
M/F                           M
City                    Legazpi
State                       NaN
Country                     ESP
Half            0 days 01:21:51
40K             0 days 02:44:37
Pace                    0:06:40
TotalSeconds             9877.0
HalfSeconds              4911.0
Name: 1892, dtype: object
Lehi
 Age                          38
M/F                           M
City                       Lehi
State                        UT
Country                     USA
Half            0 days 01:36:57
40K             0 days 03:22:27
Pace                    0:08:08
TotalSeconds            12147.0
HalfSeconds              5817.0
Name: 3142, dtype: object
Lehighton
 Age                          39
M/F                           M
City                  Lehighton
State                        PA
Country                     USA
Half            0 days 01:31:47
40K             0 days 02:59:05
Pace                    0:07:15
TotalSeconds            10745.0
HalfSeconds              5507.0
Name: 3010, dtype: object
Leicester
 Age                          32
M/F                           M
City                  Leicester
State                        MA
Country                     USA
Half            0 days 01:57:43
40K             0 days 04:07:58
Pace                    0:10:05
TotalSeconds            14878.0
HalfSeconds              7063.0
Name: 30113, dtype: object
Leicestershire
 Age                          38
M/F                           M
City             Leicestershire
State                       NaN
Country                     GBR
Half            0 days 02:02:35
40K             0 days 04:24:17
Pace                    0:10:38
TotalSeconds            15857.0
HalfSeconds              7355.0
Name: 31484, dtype: object
Leichhardt
 Age                          43
M/F                           M
City                 Leichhardt
State                       NaN
Country                     AUS
Half            0 days 01:14:37
40K             0 days 02:31:13
Pace                    0:06:06
TotalSeconds             9073.0
HalfSeconds              4477.0
Name: 83, dtype: object
Leiden
 Age                          39
M/F                           M
City                     Leiden
State                       NaN
Country                     NED
Half            0 days 01:36:10
40K             0 days 03:58:05
Pace                    0:09:48
TotalSeconds            14285.0
HalfSeconds              5770.0
Name: 3144, dtype: object
Leighton
 Age                          40
M/F                           M
City                   Leighton
State                        AL
Country                     USA
Half            0 days 01:40:37
40K             0 days 03:31:29
Pace                    0:08:36
TotalSeconds            12689.0
HalfSeconds              6037.0
Name: 6871, dtype: object
Leighton Buzzard
 Age                           34
M/F                            M
City            Leighton Buzzard
State                        NaN
Country                      GBR
Half             0 days 01:17:21
40K              0 days 02:36:20
Pace                     0:06:20
TotalSeconds              9380.0
HalfSeconds               4641.0
Name: 207, dtype: object
Leland
 Age                          35
M/F                           F
City                     Leland
State                        NC
Country                     USA
Half            0 days 01:35:17
40K             0 days 03:14:03
Pace                    0:07:49
TotalSeconds            11643.0
HalfSeconds              5717.0
Name: 10708, dtype: object
Lemon Grove
 Age                          36
M/F                           M
City                Lemon Grove
State                        CA
Country                     USA
Half            0 days 01:26:37
40K             0 days 02:47:13
Pace                    0:06:45
TotalSeconds            10033.0
HalfSeconds              5197.0
Name: 3166, dtype: object
Lemont
 Age                          48
M/F                           F
City                     Lemont
State                        IL
Country                     USA
Half            0 days 01:58:12
40K             0 days 04:00:13
Pace                    0:09:42
TotalSeconds            14413.0
HalfSeconds              7092.0
Name: 21919, dtype: object
Lemoyne
 Age                          51
M/F                           M
City                    Lemoyne
State                        QC
Country                     CAN
Half            0 days 01:42:10
40K             0 days 03:18:08
Pace                    0:08:01
TotalSeconds            11888.0
HalfSeconds              6130.0
Name: 15013, dtype: object
Lena
 Age                          31
M/F                           M
City                       Lena
State                        IL
Country                     USA
Half            0 days 01:37:39
40K             0 days 03:13:59
Pace                    0:07:48
TotalSeconds            11639.0
HalfSeconds              5859.0
Name: 3895, dtype: object
Lenexa
 Age                          55
M/F                           M
City                     Lenexa
State                        KS
Country                     USA
Half            0 days 01:31:39
40K             0 days 03:03:13
Pace                    0:07:25
TotalSeconds            10993.0
HalfSeconds              5499.0
Name: 6837, dtype: object
Leola
 Age                          53
M/F                           F
City                      Leola
State                        PA
Country                     USA
Half            0 days 01:52:27
40K             0 days 03:46:31
Pace                    0:09:08
TotalSeconds            13591.0
HalfSeconds              6747.0
Name: 23116, dtype: object
Leominster
 Age                          41
M/F                           M
City                 Leominster
State                        MA
Country                     USA
Half            0 days 02:05:22
40K             0 days 04:09:39
Pace                    0:10:10
TotalSeconds            14979.0
HalfSeconds              7522.0
Name: 28029, dtype: object
Leon
 Age                          43
M/F                           M
City                       Leon
State                       NaN
Country                     ESP
Half            0 days 01:29:28
40K             0 days 02:55:26
Pace                    0:07:08
TotalSeconds            10526.0
HalfSeconds              5368.0
Name: 3689, dtype: object
Leon Guanajuato
 Age                          38
M/F                           M
City            Leon Guanajuato
State                       NaN
Country                     MEX
Half            0 days 01:43:45
40K             0 days 03:38:56
Pace                    0:08:54
TotalSeconds            13136.0
HalfSeconds              6225.0
Name: 6902, dtype: object
Leon, Guanajuato
 Age                           55
M/F                            M
City            Leon, Guanajuato
State                        NaN
Country                      MEX
Half             0 days 01:44:22
40K              0 days 03:32:47
Pace                     0:08:40
TotalSeconds             12767.0
HalfSeconds               6262.0
Name: 10765, dtype: object
Leonard
 Age                          55
M/F                           M
City                    Leonard
State                        MI
Country                     USA
Half            0 days 01:46:26
40K             0 days 04:32:30
Pace                    0:11:11
TotalSeconds            16350.0
HalfSeconds              6386.0
Name: 16714, dtype: object
Leonardtown
 Age                          29
M/F                           M
City                Leonardtown
State                        MD
Country                     USA
Half            0 days 01:30:51
40K             0 days 03:11:30
Pace                    0:07:47
TotalSeconds            11490.0
HalfSeconds              5451.0
Name: 5401, dtype: object
Leonia
 Age                          61
M/F                           M
City                     Leonia
State                        NJ
Country                     USA
Half            0 days 01:52:31
40K             0 days 03:50:28
Pace                    0:09:21
TotalSeconds            13828.0
HalfSeconds              6751.0
Name: 22078, dtype: object
Lesueur
 Age                          51
M/F                           M
City                    Lesueur
State                        MN
Country                     USA
Half            0 days 01:51:40
40K             0 days 03:38:57
Pace                    0:08:49
TotalSeconds            13137.0
HalfSeconds              6700.0
Name: 11019, dtype: object
Letchworth
 Age                          45
M/F                           M
City                 Letchworth
State                       NaN
Country                     GBR
Half            0 days 01:32:30
40K             0 days 03:04:15
Pace                    0:07:27
TotalSeconds            11055.0
HalfSeconds              5550.0
Name: 7230, dtype: object
Letham
 Age                          40
M/F                           M
City                     Letham
State                       NaN
Country                     GBR
Half            0 days 01:28:11
40K             0 days 03:26:58
Pace                    0:08:22
TotalSeconds            12418.0
HalfSeconds              5291.0
Name: 3482, dtype: object
Lethbridge
 Age                          49
M/F                           M
City                 Lethbridge
State                        AB
Country                     CAN
Half            0 days 01:34:25
40K             0 days 03:14:21
Pace                    0:07:51
TotalSeconds            11661.0
HalfSeconds              5665.0
Name: 8073, dtype: object
Levis
 Age                          26
M/F                           M
City                      Levis
State                        QC
Country                     CAN
Half            0 days 01:19:02
40K             0 days 02:37:46
Pace                    0:06:24
TotalSeconds             9466.0
HalfSeconds              4742.0
Name: 1543, dtype: object
Levittown
 Age                          47
M/F                           M
City                  Levittown
State                        NY
Country                     USA
Half            0 days 01:40:19
40K             0 days 03:18:01
Pace                    0:07:58
TotalSeconds            11881.0
HalfSeconds              6019.0
Name: 10575, dtype: object
Lewis Center
 Age                          30
M/F                           M
City               Lewis Center
State                        OH
Country                     USA
Half            0 days 01:29:22
40K             0 days 02:52:03
Pace                    0:06:57
TotalSeconds            10323.0
HalfSeconds              5362.0
Name: 4978, dtype: object
Lewisburg
 Age                          25
M/F                           F
City                  Lewisburg
State                        PA
Country                     USA
Half            0 days 01:31:54
40K             0 days 03:05:02
Pace                    0:07:27
TotalSeconds            11102.0
HalfSeconds              5514.0
Name: 9800, dtype: object
Lewiston
 Age                          19
M/F                           M
City                   Lewiston
State                        ME
Country                     USA
Half            0 days 01:39:38
40K             0 days 03:18:57
Pace                    0:08:01
TotalSeconds            11937.0
HalfSeconds              5978.0
Name: 27836, dtype: object
Lewisville
 Age                          35
M/F                           M
City                 Lewisville
State                        TX
Country                     USA
Half            0 days 01:22:46
40K             0 days 03:10:06
Pace                    0:07:45
TotalSeconds            11406.0
HalfSeconds              4966.0
Name: 696, dtype: object
Lexington
 Age                          21
M/F                           M
City                  Lexington
State                        MA
Country                     USA
Half            0 days 01:19:58
40K             0 days 02:35:03
Pace                    0:06:16
TotalSeconds             9303.0
HalfSeconds              4798.0
Name: 453, dtype: object
Leymen
 Age                          35
M/F                           F
City                     Leymen
State                       NaN
Country                     FRA
Half            0 days 01:51:18
40K             0 days 03:41:26
Pace                    0:08:57
TotalSeconds            13286.0
HalfSeconds              6678.0
Name: 19392, dtype: object
León
 Age                          45
M/F                           F
City                       León
State                       NaN
Country                     MEX
Half            0 days 01:55:35
40K             0 days 03:46:45
Pace                    0:09:09

Linwood
 Age                          24
M/F                           M
City                    Linwood
State                        NJ
Country                     USA
Half            0 days 01:26:55
40K             0 days 03:16:08
Pace                    0:07:59
TotalSeconds            11768.0
HalfSeconds              5215.0
Name: 2071, dtype: object
Linz
 Age                          44
M/F                           F
City                       Linz
State                       NaN
Country                     AUT
Half            0 days 01:46:50
40K             0 days 03:29:44
Pace                    0:08:28
TotalSeconds            12584.0
HalfSeconds              6410.0
Name: 11407, dtype: object
Liperi
 Age                          72
M/F                           M
City                     Liperi
State                       NaN
Country                     FIN
Half            0 days 02:03:00
40K             0 days 04:03:37
Pace                    0:09:50
TotalSeconds            14617.0
HalfSeconds              7380.0
Name: 25384, dtype: object
Lisboa
 Age                          41
M/F                           M
City                     Lisboa
State                       NaN
Country                     POR
Half            0 days 01:30:39
40K             0 days 02:54:47
Pace                    0:07:03
TotalSeconds            10487.0
HalfSeconds              5439.0
Name: 5107, dtype: object
Lisbon
 Age                          62
M/F                           M
City                     Lisbon
State                       NaN
Country                     POR
Half            0 days 01:57:09
40K             0 days 03:50:02
Pace                    0:09:16
TotalSeconds            13802.0
HalfSeconds              7029.0
Name: 23459, dtype: object
Lisburn
 Age                          35
M/F                           F
City                    Lisburn
State                       NaN
Country                     GBR
Half            0 days 01:45:52
40K             0 days 03:29:32
Pace                    0:08:28
TotalSeconds            12572.0
HalfSeconds              6352.0
Name: 17603, dtype: object
Lisle
 Age                          60
M/F                           M
City                      Lisle
State                        IL
Country                     USA
Half            0 days 01:21:00
40K             0 days 02:37:07
Pace                    0:06:20
TotalSeconds             9427.0
HalfSeconds              4860.0
Name: 806, dtype: object
Listowel
 Age                          60
M/F                           M
City                   Listowel
State                        ON
Country                     CAN
Half            0 days 01:40:31
40K             0 days 03:23:10
Pace                    0:08:12
TotalSeconds            12190.0
HalfSeconds              6031.0
Name: 16248, dtype: object
Litcfield
 Age                          48
M/F                           F
City                  Litcfield
State                        NH
Country                     USA
Half            0 days 02:48:49
40K             0 days 05:31:53
Pace                    0:13:21
TotalSeconds            19913.0
HalfSeconds             10129.0
Name: 26873, dtype: object
Litchfield
 Age                          42
M/F                           M
City                 Litchfield
State                        NH
Country                     USA
Half            0 days 01:46:02
40K             0 days 03:23:23
Pace                    0:08:12
TotalSeconds            12203.0
HalfSeconds              6362.0
Name: 31352, dtype: object
Litchfield Park
 Age                          40
M/F                           M
City            Litchfield Park
State                        AZ
Country                     USA
Half            0 days 01:32:46
40K             0 days 03:07:16
Pace                    0:07:34
TotalSeconds            11236.0
HalfSeconds              5566.0
Name: 2869, dtype: object
Liteshoa
 Age                          29
M/F                           F
City                   Liteshoa
State                       NaN
Country                     ETH
Half            0 days 01:15:32
40K             0 days 02:21:49
Pace                    0:05:42
TotalSeconds             8509.0
HalfSeconds              4532.0
Name: F6, dtype: object
Lithia
 Age                          40
M/F                           F
City                     Lithia
State                        FL
Country                     USA
Half            0 days 01:36:57
40K             0 days 03:16:45
Pace                    0:07:58
TotalSeconds            11805.0
HalfSeconds              5817.0
Name: 6169, dtype: object
Lititz
 Age                          54
M/F                           M
City                     Lititz
State                        PA
Country                     USA
Half            0 days 01:35:10
40K             0 days 03:03:50
Pace                    0:07:29
TotalSeconds            11030.0
HalfSeconds              5710.0
Name: 10911, dtype: object
Little Britain
 Age                          41
M/F                           F
City             Little Britain
State                        ON
Country                     CAN
Half            0 days 01:38:33
40K             0 days 03:05:58
Pace                    0:07:29
TotalSeconds            11158.0
HalfSeconds              5913.0
Name: 13880, dtype: object
Little Egg Harbor
 Age                            41
M/F                             M
City            Little Egg Harbor
State                          NJ
Country                       USA
Half              0 days 01:34:43
40K               0 days 03:02:29
Pace                      0:07:20
TotalSeconds              10949.0
HalfSeconds                5683.0
Name: 7483, dtype: object
Little Falls
 Age                          53
M/F                           F
City               Little Falls
State                        MN
Country                     USA
Half            0 days 01:33:13
40K             0 days 03:04:10
Pace                    0:07:27
TotalSeconds            11050.0
HalfSeconds              5593.0
Name: 6088, dtype: object
Little Ferry
 Age                          58
M/F                           M
City               Little Ferry
State                        NJ
Country                     USA
Half            0 days 01:49:10
40K             0 days 03:26:44
Pace                    0:08:19
TotalSeconds            12404.0
HalfSeconds              6550.0
Name: 18697, dtype: object
Little Rock
 Age                          43
M/F                           M
City                Little Rock
State                        AR
Country                     USA
Half            0 days 01:21:35
40K             0 days 02:40:22
Pace                    0:06:31
TotalSeconds             9622.0
HalfSeconds              4895.0
Name: 673, dtype: object
Little Silver
 Age                          53
M/F                           M
City              Little Silver
State                        NJ
Country                     USA
Half            0 days 01:40:18
40K             0 days 03:10:03
Pace                    0:07:39
TotalSeconds            11403.0
HalfSeconds              6018.0
Name: 12170, dtype: object
Littleton
 Age                          45
M/F                           M
City                  Littleton
State                        CO
Country                     USA
Half            0 days 01:17:16
40K             0 days 02:45:08
Pace                    0:06:45
TotalSeconds             9908.0
HalfSeconds              4636.0
Name: 824, dtype: object
Livermore
 Age                          55
M/F                           F
City                  Livermore
State                        CA
Country                     USA
Half            0 days 02:04:52
40K             0 days 04:05:40
Pace                    0:09:55
TotalSeconds            14740.0
HalfSeconds              7492.0
Name: 25446, dtype: object
Liverpool
 Age                          21
M/F                           M
City                  Liverpool
State                        NY
Country                     USA
Half            0 days 01:27:12
40K             0 days 02:54:09
Pace                    0:07:02
TotalSeconds            10449.0
HalfSeconds              5232.0
Name: 1578, dtype: object
Livingston
 Age                          32
M/F                           F
City                 Livingston
State                        TX
Country                     USA
Half            0 days 01:35:27
40K             0 days 03:01:15
Pace                    0:07:18
TotalSeconds            10875.0
HalfSeconds              5727.0
Name: 8508, dtype: object
Livonia
 Age                          51
M/F                           M
City                    Livonia
State                        MI
Country                     USA
Half            0 days 01:42:36
40K             0 days 03:20:45
Pace                    0:08:06
TotalSeconds            12045.0
HalfSeconds              6156.0
Name: 13196, dtype: object
Ljubljana
 Age                          50
M/F                           M
City                  Ljubljana
State                       NaN
Country                     SLO
Half            0 days 01:26:39
40K             0 days 02:57:56
Pace                    0:07:12
TotalSeconds            10676.0
HalfSeconds              5199.0
Name: 2256, dtype: object
Ljusdal
 Age                          48
M/F                           M
City                    Ljusdal
State                       NaN
Country                     SWE
Half            0 days 02:02:48
40K             0 days 03:58:06
Pace                    0:09:36
TotalSeconds            14286.0
HalfSeconds              7368.0
Name: 31811, dtype: object
Lobethal
 Age                          65
M/F                           M
City                   Lobethal
State                       NaN
Country                     AUS
Half            0 days 01:48:23
40K             0 days 03:44:31
Pace                    0:09:07
TotalSeconds            13471.0
HalfSeconds              6503.0
Name: 14366, dtype: object
Lockhart
 Age                          58
M/F                           F
City                   Lockhart
State                        TX
Country                     USA
Half            0 days 02:04:12
40K             0 days 03:58:47
Pace                    0:09:38
TotalSeconds            14327.0
HalfSeconds              7452.0
Name: 25519, dtype: object
Lockport
 Age                          28
M/F                           M
City                   Lockport
State                        NY
Country                     USA
Half            0 days 01:25:55
40K             0 days 02:50:39
Pace                    0:06:53
TotalSeconds            10239.0
HalfSeconds              5155.0
Name: 1972, dtype: object
Locust
 Age                          46
M/F                           F
City                     Locust
State                        NJ
Country                     USA
Half            0 days 01:44:37
40K             0 days 03:18:51
Pace                    0:08:01
TotalSeconds            11931.0
HalfSeconds              6277.0
Name: 18458, dtype: object
Locust Grove
 Age                          31
M/F                           M
City               Locust Grove
State                        VA
Country                     USA
Half            0 days 01:20:49
40K             0 days 02:40:26
Pace                    0:06:29
TotalSeconds             9626.0
HalfSeconds              4849.0
Name: 1462, dtype: object
Loda
 Age                          60
M/F                           M
City                       Loda
State                        IL
Country                     USA
Half            0 days 01:53:09
40K             0 days 03:57:57
Pace                    0:09:35
TotalSeconds            14277.0
HalfSeconds              6789.0
Name: 20767, dtype: object
Lodi
 Age                          56
M/F                           M
City                       Lodi
State                        NJ
Country                     USA
Half            0 days 01:36:25
40K             0 days 03:11:20
Pace                    0:07:45
TotalSeconds            11480.0
HalfSeconds              5785.0
Name: 10161, dtype: object
Logan
 Age                          23
M/F                           M
City                      Logan
State                        UT
Country                     USA
Half            0 days 01:24:42
40K             0 days 02:43:54
Pace                    0:06:36
TotalSeconds             9834.0
HalfSeconds              5082.0
Name: 2484, dtype: object
Logandale
 Age                          38
M/F                           F
City                  Logandale
State                        NV
Country                     USA
Half            0 days 01:49:13
40K             0 days 03:40:34
Pace                    0:08:57
TotalSeconds            13234.0
HalfSeconds              6553.0
Name: 17070, dtype: object
Loganville
 Age                          51
M/F                           F
City                 Loganville
State                        GA
Country                     USA
Half            0 days 02:06:47
40K             0 days 04:07:48
Pace                    0:09:58
TotalSeconds            14868.0
HalfSeconds              7607.0
Name: 24150, dtype: object
Logy Bay
 Age                          57
M/F                           F
City                   Logy Bay
State                        NL
Country                     CAN
Half            0 days 02:12:27
40K             0 days 04:13:59
Pace                    0:10:13
TotalSeconds            15239.0
HalfSeconds              7947.0
Name: 25467, dtype: object
Lokeren
 Age                          29
M/F                           M
City                    Lokeren
State                       NaN
Country                     BEL
Half            0 days 01:21:37
40K             0 days 02:38:37
Pace                    0:06:24
TotalSeconds             9517.0
HalfSeconds              4897.0
Name: 1611, dtype: object
Lolo
 Age                          30
M/F                           M
City                       Lolo
State                        MT
Country                     USA
Half            0 days 01:23:36
40K             0 days 02:44:03
Pace                    0:06:38
TotalSeconds             9843.0
HalfSeconds              5016.0
Name: 812, dtype: object
Loma Linda
 Age                          29
M/F                           M
City                 Loma Linda
State                        CA
Country                     USA
Half            0 days 01:24:54
40K             0 days 02:46:57
Pace                    0:06:44
TotalSeconds            10017.0
HalfSeconds              5094.0
Name: 1067, dtype: object
Lombard
 Age                          61
M/F                           M
City                    Lombard
State                        IL
Country                     USA
Half            0 days 01:57:04
40K             0 days 03:48:02
Pace                    0:09:16
TotalSeconds            13682.0
HalfSeconds              7024.0
Name: 21630, dtype: object
Lompoc
 Age                          46
M/F                           M
City                     Lompoc
State                        CA
Country                     USA
Half            0 days 01:36:35
40K             0 days 03:09:01
Pace                    0:07:35
TotalSeconds            11341.0
HalfSeconds              5795.0
Name: 9517, dtype: object
London
 Age                          26
M/F                           M
City                     London
State                       NaN
Country                     GBR
Half            0 days 01:16:41
40K             0 days 02:33:28
Pace                    0:06:12
TotalSeconds             9208.0
HalfSeconds              4601.0
Name: 372, dtype: object
London, Great-Britain
 Age                                41
M/F                                 M
City            London, Great-Britain
State                             NaN
Country                           GBR
Half                  0 days 01:41:17
40K                   0 days 03:37:30
Pace                          0:08:48
TotalSeconds                  13050.0
HalfSeconds                    6077.0
Name: 6639, dtype: object
Londonderry
 Age                          51
M/F                           M
City                Londonderry
State                        NH
Country                     USA
Half            0 days 01:33:22
40K             0 days 03:03:31
Pace                    0:07:27
TotalSeconds            11011.0
HalfSeconds              5602.0
Name: 7233, dtype: object
Lone Oak
 Age                          50
M/F                           M
City                   Lone Oak
State                        TX
Country                     USA
Half            0 days 01:48:27
40K             0 days 03:48:31
Pace                    0:09:14
TotalSeconds            13711.0
HalfSeconds              6507.0
Name: 14045, dtype: object
Lone Tree
 Age                          45
M/F                           F
City                  Lone Tree
State                        CO
Country                     USA
Half            0 days 01:50:29
40K             0 days 03:54:18
Pace                    0:09:28
TotalSeconds            14058.0
HalfSeconds              6629.0
Name: 20902, dtype: object
Long Beach
 Age                          40
M/F                           M
City                 Long Beach
State                        CA
Country                     USA
Half            0 days 01:27:12
40K             0 days 02:51:58
Pace                    0:06:59
TotalSeconds            10318.0
HalfSeconds              5232.0
Name: 6708, dtype: object
Long Branch
 Age                          55
M/F                           M
City                Long Branch
State                        NJ
Country                     USA
Half            0 days 01:44:53
40K             0 days 03:21:03
Pace                    0:08:05
TotalSeconds            12063.0
HalfSeconds              6293.0
Name: 10181, dtype: object
Long Grove
 Age                          51
M/F                           F
City                 Long Grove
State                        IL
Country                     USA
Half            0 days 01:55:47
40K             0 days 03:42:17
Pace                    0:08:56
TotalSeconds            13337.0
HalfSeconds              6947.0
Name: 21162, dtype: object
Long Island City
 Age                           30
M/F                            M
City            Long Island City
State                         NY
Country                      USA
Half             0 days 01:15:43
40K              0 days 02:38:20
Pace                     0:06:27
TotalSeconds              9500.0
HalfSeconds               4543.0
Name: 495, dtype: object
Long Lake
 Age                          48
M/F                           F
City                  Long Lake
State                        MN
Country                     USA
Half            0 days 02:00:44
40K             0 days 04:00:29
Pace                    0:09:41
TotalSeconds            14429.0
HalfSeconds              7244.0
Name: 23351, dtype: object
Long Point
 Age                          48
M/F                           M
City                 Long Point
State                        NS
Country                     CAN
Half            0 days 01:38:09
40K             0 days 03:13:03
Pace                    0:07:50
TotalSeconds            11583.0
HalfSeconds              5889.0
Name: 9747, dtype: object
Long Valley
 Age                          57
M/F                           M
City                Long Valley
State                        NJ
Country                     USA
Half            0 days 01:47:56
40K             0 days 03:38:37
Pace                    0:08:51
TotalSeconds            13117.0
HalfSeconds              6476.0
Name: 16589, dtype: object
Longeville Les Metz
 Age                              46
M/F                               M
City            Longeville Les Metz
State                           NaN
Country                         FRA
Half                0 days 01:31:58

Lowellville
 Age                          38
M/F                           M
City                Lowellville
State                        OH
Country                     USA
Half            0 days 01:31:39
40K             0 days 02:57:15
Pace                    0:07:11
TotalSeconds            10635.0
HalfSeconds              5499.0
Name: 6669, dtype: object
Lower Burrell
 Age                          58
M/F                           M
City              Lower Burrell
State                        PA
Country                     USA
Half            0 days 01:53:18
40K             0 days 04:00:36
Pace                    0:09:44
TotalSeconds            14436.0
HalfSeconds              6798.0
Name: 19635, dtype: object
Lower Hutt
 Age                          35
M/F                           M
City                 Lower Hutt
State                       NaN
Country                     NZL
Half            0 days 01:39:27
40K             0 days 03:14:53
Pace                    0:07:51
TotalSeconds            11693.0
HalfSeconds              5967.0
Name: 5228, dtype: object
Lower Mitcham
 Age                          61
M/F                           M
City              Lower Mitcham
State                       NaN
Country                     AUS
Half            0 days 01:49:23
40K             0 days 03:52:08
Pace                    0:09:24
TotalSeconds            13928.0
HalfSeconds              6563.0
Name: 17682, dtype: object
Lower Sackville
 Age                          50
M/F                           F
City            Lower Sackville
State                        NS
Country                     CAN
Half            0 days 01:54:43
40K             0 days 03:46:17
Pace                    0:09:08
TotalSeconds            13577.0
HalfSeconds              6883.0
Name: 24524, dtype: object
Loxahatchee
 Age                          45
M/F                           F
City                Loxahatchee
State                        FL
Country                     USA
Half            0 days 01:52:44
40K             0 days 03:42:54
Pace                    0:09:01
TotalSeconds            13374.0
HalfSeconds              6764.0
Name: 21873, dtype: object
Loxley
 Age                          33
M/F                           F
City                     Loxley
State                        AL
Country                     USA
Half            0 days 01:44:38
40K             0 days 03:34:07
Pace                    0:08:38
TotalSeconds            12847.0
HalfSeconds              6278.0
Name: 16597, dtype: object
Lubbock
 Age                          36
M/F                           M
City                    Lubbock
State                        TX
Country                     USA
Half            0 days 01:31:54
40K             0 days 03:04:21
Pace                    0:07:27
TotalSeconds            11061.0
HalfSeconds              5514.0
Name: 2785, dtype: object
Lucca
 Age                          40
M/F                           M
City                      Lucca
State                       NaN
Country                     ITA
Half            0 days 01:28:55
40K             0 days 02:55:11
Pace                    0:07:04
TotalSeconds            10511.0
HalfSeconds              5335.0
Name: 2512, dtype: object
Lucerne
 Age                          49
M/F                           M
City                    Lucerne
State                       NaN
Country                     SUI
Half            0 days 01:34:31
40K             0 days 03:04:19
Pace                    0:07:26
TotalSeconds            11059.0
HalfSeconds              5671.0
Name: 8069, dtype: object
Ludington
 Age                          24
M/F                           M
City                  Ludington
State                        MI
Country                     USA
Half            0 days 01:22:38
40K             0 days 02:59:15
Pace                    0:07:25
TotalSeconds            10755.0
HalfSeconds              4958.0
Name: 1299, dtype: object
Ludlow
 Age                          64
M/F                           M
City                     Ludlow
State                        MA
Country                     USA
Half            0 days 01:56:59
40K             0 days 03:51:14
Pace                    0:09:18
TotalSeconds            13874.0
HalfSeconds              7019.0
Name: 28354, dtype: object
Ludvika
 Age                          47
M/F                           M
City                    Ludvika
State                       NaN
Country                     SWE
Half            0 days 01:39:42
40K             0 days 03:16:50
Pace                    0:07:55
TotalSeconds            11810.0
HalfSeconds              5982.0
Name: 5556, dtype: object
Luebbecke
 Age                          40
M/F                           M
City                  Luebbecke
State                       NaN
Country                     GER
Half            0 days 01:40:27
40K             0 days 03:23:36
Pace                    0:08:17
TotalSeconds            12216.0
HalfSeconds              6027.0
Name: 5731, dtype: object
Lugano
 Age                          44
M/F                           M
City                     Lugano
State                       NaN
Country                     SUI
Half            0 days 01:41:20
40K             0 days 03:20:23
Pace                    0:08:03
TotalSeconds            12023.0
HalfSeconds              6080.0
Name: 31365, dtype: object
Lugoff
 Age                          38
M/F                           F
City                     Lugoff
State                        SC
Country                     USA
Half            0 days 01:35:06
40K             0 days 03:03:16
Pace                    0:07:23
TotalSeconds            10996.0
HalfSeconds              5706.0
Name: 10258, dtype: object
Lulea
 Age                          44
M/F                           M
City                      Lulea
State                       NaN
Country                     SWE
Half            0 days 01:50:16
40K             0 days 03:29:21
Pace                    0:08:27
TotalSeconds            12561.0
HalfSeconds              6616.0
Name: 31472, dtype: object
Lumsden
 Age                          62
M/F                           M
City                    Lumsden
State                        SK
Country                     CAN
Half            0 days 01:50:15
40K             0 days 03:30:34
Pace                    0:08:28
TotalSeconds            12634.0
HalfSeconds              6615.0
Name: 18505, dtype: object
Lund
 Age                          56
M/F                           M
City                       Lund
State                       NaN
Country                     SWE
Half            0 days 01:52:10
40K             0 days 03:55:59
Pace                    0:09:39
TotalSeconds            14159.0
HalfSeconds              6730.0
Name: 19531, dtype: object
Lunenburg
 Age                          35
M/F                           M
City                  Lunenburg
State                        MA
Country                     USA
Half            0 days 01:29:55
40K             0 days 03:18:03
Pace                    0:08:09
TotalSeconds            11883.0
HalfSeconds              5395.0
Name: 5469, dtype: object
Lunion
 Age                          69
M/F                           M
City                     Lunion
State                       NaN
Country                     FRA
Half            0 days 02:09:00
40K             0 days 04:12:14
Pace                    0:10:09
TotalSeconds            15134.0
HalfSeconds              7740.0
Name: 30033, dtype: object
Luray
 Age                          49
M/F                           F
City                      Luray
State                        VA
Country                     USA
Half            0 days 01:47:02
40K             0 days 03:30:01
Pace                    0:08:29
TotalSeconds            12601.0
HalfSeconds              6422.0
Name: 20420, dtype: object
Lusby
 Age                          57
M/F                           M
City                      Lusby
State                        MD
Country                     USA
Half            0 days 01:37:33
40K             0 days 03:08:02
Pace                    0:07:35
TotalSeconds            11282.0
HalfSeconds              5853.0
Name: 13349, dtype: object
Lutherville
 Age                          24
M/F                           F
City                Lutherville
State                        MD
Country                     USA
Half            0 days 01:41:21
40K             0 days 03:31:06
Pace                    0:08:30
TotalSeconds            12666.0
HalfSeconds              6081.0
Name: 15309, dtype: object
Lutz
 Age                          40
M/F                           F
City                       Lutz
State                        FL
Country                     USA
Half            0 days 01:36:50
40K             0 days 03:06:14
Pace                    0:07:30
TotalSeconds            11174.0
HalfSeconds              5810.0
Name: 10280, dtype: object
Luverne
 Age                          60
M/F                           M
City                    Luverne
State                        ND
Country                     USA
Half            0 days 01:54:25
40K             0 days 03:56:12
Pace                    0:09:37
TotalSeconds            14172.0
HalfSeconds              6865.0
Name: 22111, dtype: object
Luxembourg
 Age                          31
M/F                           M
City                 Luxembourg
State                       NaN
Country                     LUX
Half            0 days 01:46:44
40K             0 days 03:39:22
Pace                    0:08:53
TotalSeconds            13162.0
HalfSeconds              6404.0
Name: 3578, dtype: object
Luxemburg
 Age                          46
M/F                           F
City                  Luxemburg
State                        WI
Country                     USA
Half            0 days 01:47:41
40K             0 days 03:44:54
Pace                    0:09:08
TotalSeconds            13494.0
HalfSeconds              6461.0
Name: 18584, dtype: object
Lyme
 Age                          50
M/F                           M
City                       Lyme
State                        NH
Country                     USA
Half            0 days 01:33:48
40K             0 days 03:29:04
Pace                    0:08:33
TotalSeconds            12544.0
HalfSeconds              5628.0
Name: 9390, dtype: object
Lynbrook
 Age                          31
M/F                           M
City                   Lynbrook
State                        NY
Country                     USA
Half            0 days 01:28:34
40K             0 days 02:58:56
Pace                    0:07:15
TotalSeconds            10736.0
HalfSeconds              5314.0
Name: 3333, dtype: object
Lynchburg
 Age                          25
M/F                           M
City                  Lynchburg
State                        VA
Country                     USA
Half            0 days 01:13:02
40K             0 days 02:28:24
Pace                    0:06:03
TotalSeconds             8904.0
HalfSeconds              4382.0
Name: 2522, dtype: object
Lynden
 Age                          43
M/F                           F
City                     Lynden
State                        ON
Country                     CAN
Half            0 days 02:14:37
40K             0 days 04:18:05
Pace                    0:10:20
TotalSeconds            15485.0
HalfSeconds              8077.0
Name: 21719, dtype: object
Lyndhurst
 Age                          30
M/F                           M
City                  Lyndhurst
State                        NJ
Country                     USA
Half            0 days 01:32:59
40K             0 days 03:28:43
Pace                    0:08:31
TotalSeconds            12523.0
HalfSeconds              5579.0
Name: 3124, dtype: object
Lynn
 Age                          41
M/F                           M
City                       Lynn
State                        MA
Country                     USA
Half            0 days 01:28:12
40K             0 days 02:54:35
Pace                    0:07:05
TotalSeconds            10475.0
HalfSeconds              5292.0
Name: 1797, dtype: object
Lynnfield
 Age                          38
M/F                           M
City                  Lynnfield
State                        MA
Country                     USA
Half            0 days 01:23:45
40K             0 days 02:40:19
Pace                    0:06:27
TotalSeconds             9619.0
HalfSeconds              5025.0
Name: 2401, dtype: object
Lynnwood
 Age                          31
M/F                           M
City                   Lynnwood
State                        WA
Country                     USA
Half            0 days 01:26:18
40K             0 days 02:55:53
Pace                    0:07:09
TotalSeconds            10553.0
HalfSeconds              5178.0
Name: 3905, dtype: object
Lynwood
 Age                          31
M/F                           M
City                    Lynwood
State                        CA
Country                     USA
Half            0 days 01:24:01
40K             0 days 02:47:51
Pace                    0:06:46
TotalSeconds            10071.0
HalfSeconds              5041.0
Name: 666, dtype: object
Lyon
 Age                          31
M/F                           M
City                       Lyon
State                       NaN
Country                     FRA
Half            0 days 01:42:32
40K             0 days 03:08:51
Pace                    0:07:34
TotalSeconds            11331.0
HalfSeconds              6152.0
Name: 31581, dtype: object
Lyons
 Age                          32
M/F                           F
City                      Lyons
State                        CO
Country                     USA
Half            0 days 01:35:47
40K             0 days 03:03:57
Pace                    0:07:25
TotalSeconds            11037.0
HalfSeconds              5747.0
Name: 8600, dtype: object
Lévis
 Age                          50
M/F                           M
City                      Lévis
State                        QC
Country                     CAN
Half            0 days 01:39:47
40K             0 days 03:17:17
Pace                    0:07:59
TotalSeconds            11837.0
HalfSeconds              5987.0
Name: 14396, dtype: object
López Mateos
 Age                          36
M/F                           M
City               López Mateos
State                       NaN
Country                     MEX
Half            0 days 01:29:53
40K             0 days 02:58:31
Pace                    0:07:14
TotalSeconds            10711.0
HalfSeconds              5393.0
Name: 3922, dtype: object
Maardu
 Age                          33
M/F                           M
City                     Maardu
State                       NaN
Country                     EST
Half            0 days 01:24:03
40K             0 days 02:49:24
Pace                    0:06:53
TotalSeconds            10164.0
HalfSeconds              5043.0
Name: 2882, dtype: object
Mableton
 Age                          55
M/F                           M
City                   Mableton
State                        GA
Country                     USA
Half            0 days 01:42:45
40K             0 days 03:39:24
Pace                    0:08:53
TotalSeconds            13164.0
HalfSeconds              6165.0
Name: 12704, dtype: object
Macau
 Age                          46
M/F                           M
City                      Macau
State                       NaN
Country                     CHN
Half            0 days 01:23:24
40K             0 days 02:50:56
Pace                    0:06:54
TotalSeconds            10256.0
HalfSeconds              5004.0
Name: 3227, dtype: object
Macedon
 Age                          45
M/F                           F
City                    Macedon
State                        NY
Country                     USA
Half            0 days 01:41:12
40K             0 days 03:16:57
Pace                    0:07:57
TotalSeconds            11817.0
HalfSeconds              6072.0
Name: 17844, dtype: object
Macedonia
 Age                          38
M/F                           M
City                  Macedonia
State                        OH
Country                     USA
Half            0 days 01:31:53
40K             0 days 02:57:39
Pace                    0:07:09
TotalSeconds            10659.0
HalfSeconds              5513.0
Name: 6938, dtype: object
Maceio
 Age                          38
M/F                           M
City                     Maceio
State                       NaN
Country                     BRA
Half            0 days 01:29:49
40K             0 days 03:03:51
Pace                    0:07:33
TotalSeconds            11031.0
HalfSeconds              5389.0
Name: 5213, dtype: object
Macerata
 Age                          51
M/F                           M
City                   Macerata
State                       NaN
Country                     ITA
Half            0 days 02:23:01
40K             0 days 04:50:35
Pace                    0:11:43
TotalSeconds            17435.0
HalfSeconds              8581.0
Name: 31817, dtype: object
Machesney Park
 Age                          53
M/F                           M
City             Machesney Park
State                        IL
Country                     USA
Half            0 days 01:46:46
40K             0 days 04:30:56
Pace                    0:10:50
TotalSeconds            16256.0
HalfSeconds              6406.0
Name: 12111, dtype: object
Machiasport
 Age                          62
M/F                           F
City                Machiasport
State                        ME
Country                     USA
Half            0 days 02:03:18
40K             0 days 04:17:58
Pace                    0:10:23
TotalSeconds            15478.0
HalfSeconds              7398.0
Name: 25733, dtype: object
Macomb
 Age                          55
M/F                           M
City                     Macomb
State                        MI
Country                     USA
Half            0 days 01:39:21
40K             0 days 03:10:35
Pace                    0:07:42
TotalSeconds            11435.0
HalfSeconds              5961.0
Name: 13436, dtype: object
Macomb Township
 Age                          45
M/F                           M
City            Macomb Township
State                        MI
Country                     USA
Half            0 days 01:47:38
40K             0 days 03:40:14
Pace                    0:08:53
TotalSeconds            13214.0
HalfSeconds              6458.0
Name: 10823, dtype: object
Macon
 Age                          33
M/F                           M
City                      Macon
State                        GA
Country                     USA
Half            0 days 01:25:59
40K             0 days 02:44:00
Pace                    0:06:37
TotalSeconds             9840.0
HalfSeconds              5159.0
Name: 2352, dtype: object
Macungie
 Age                          30
M/F                           M
City                   Macungie
State                        PA
Country                     USA
Half            0 days 01:26:26
40K             0 days 02:49:58
Pace                    0:06:53
TotalSeconds            10198.0
HalfSeconds              5186.0
Name: 2802, dtype: object
Madbury
 Age                          44
M/F                           F
City                    Madbury
State                        NH
Country                     USA
Half            0 days 01:50:29
40K             0 days 03:37:51
Pace                    0:08:48
TotalSeconds            13071.0
HalfSeconds              6629.0
Name: 22127, dtype: object
Madeira
 Age                          24
M/F                           M
City                    Madeira
State                        OH
Country                     USA
Half            0 days 01:15:03
40K             0 days 02:44:46
Pace                    0:06:44
TotalSeconds             9886.0
HalfSeconds              4503.0
Name: 576, dtype: object
Madero, Tamaulipas

Maida Vale
 Age                          64
M/F                           M
City                 Maida Vale
State                       NaN
Country                     AUS
Half            0 days 02:09:38
40K             0 days 04:48:32
Pace                    0:11:36
TotalSeconds            17312.0
HalfSeconds              7778.0
Name: 31542, dtype: object
Maidenhead
 Age                          59
M/F                           F
City                 Maidenhead
State                       NaN
Country                     GBR
Half            0 days 01:45:00
40K             0 days 03:22:10
Pace                    0:08:09
TotalSeconds            12130.0
HalfSeconds              6300.0
Name: 15331, dtype: object
Maineville
 Age                          41
M/F                           F
City                 Maineville
State                        OH
Country                     USA
Half            0 days 01:51:16
40K             0 days 03:39:10
Pace                    0:08:51
TotalSeconds            13150.0
HalfSeconds              6676.0
Name: 20974, dtype: object
Maitland
 Age                          41
M/F                           F
City                   Maitland
State                        FL
Country                     USA
Half            0 days 01:57:48
40K             0 days 03:40:05
Pace                    0:08:51
TotalSeconds            13205.0
HalfSeconds              7068.0
Name: 16479, dtype: object
Makati
 Age                          29
M/F                           F
City                     Makati
State                       NaN
Country                     PHI
Half            0 days 01:53:49
40K             0 days 03:37:58
Pace                    0:08:47
TotalSeconds            13078.0
HalfSeconds              6829.0
Name: 17298, dtype: object
Malaga
 Age                          54
M/F                           M
City                     Malaga
State                       NaN
Country                     ESP
Half            0 days 02:07:29
40K             0 days 04:12:59
Pace                    0:10:10
TotalSeconds            15179.0
HalfSeconds              7649.0
Name: 30958, dtype: object
Malaybalay City
 Age                          34
M/F                           M
City            Malaybalay City
State                       NaN
Country                     PHI
Half            0 days 01:24:09
40K             0 days 02:43:20
Pace                    0:06:35
TotalSeconds             9800.0
HalfSeconds              5049.0
Name: 2577, dtype: object
Malden
 Age                          46
M/F                           M
City                     Malden
State                        MA
Country                     USA
Half            0 days 01:32:58
40K             0 days 03:25:22
Pace                    0:08:26
TotalSeconds            12322.0
HalfSeconds              5578.0
Name: 4062, dtype: object
Malibu
 Age                          21
M/F                           F
City                     Malibu
State                        CA
Country                     USA
Half            0 days 01:43:06
40K             0 days 03:20:26
Pace                    0:08:04
TotalSeconds            12026.0
HalfSeconds              6186.0
Name: 13409, dtype: object
Malling
 Age                          38
M/F                           M
City                    Malling
State                       NaN
Country                     DEN
Half            0 days 01:29:06
40K             0 days 02:55:48
Pace                    0:07:09
TotalSeconds            10548.0
HalfSeconds              5346.0
Name: 5466, dtype: object
Malnate (va)
 Age                          57
M/F                           F
City               Malnate (va)
State                       NaN
Country                     ITA
Half            0 days 01:53:15
40K             0 days 03:49:28
Pace                    0:09:16
TotalSeconds            13768.0
HalfSeconds              6795.0
Name: 23078, dtype: object
Malta
 Age                          28
M/F                           M
City                      Malta
State                        NY
Country                     USA
Half            0 days 01:13:15
40K             0 days 02:21:26
Pace                    0:05:43
TotalSeconds             8486.0
HalfSeconds              4395.0
Name: 121, dtype: object
Malvern
 Age                          61
M/F                           M
City                    Malvern
State                        PA
Country                     USA
Half            0 days 01:35:17
40K             0 days 03:03:24
Pace                    0:07:23
TotalSeconds            11004.0
HalfSeconds              5717.0
Name: 9083, dtype: object
Mamaroneck
 Age                          48
M/F                           M
City                 Mamaroneck
State                        NY
Country                     USA
Half            0 days 01:31:16
40K             0 days 02:59:19
Pace                    0:07:14
TotalSeconds            10759.0
HalfSeconds              5476.0
Name: 8860, dtype: object
Mammoth Lakes
 Age                          40
M/F                           M
City              Mammoth Lakes
State                        CA
Country                     USA
Half            0 days 01:35:39
40K             0 days 03:04:25
Pace                    0:07:27
TotalSeconds            11065.0
HalfSeconds              5739.0
Name: 8720, dtype: object
Manahawkin
 Age                          36
M/F                           F
City                 Manahawkin
State                        NJ
Country                     USA
Half            0 days 01:46:34
40K             0 days 03:25:44
Pace                    0:08:19
TotalSeconds            12344.0
HalfSeconds              6394.0
Name: 17430, dtype: object
Manakin Sabot
 Age                          54
M/F                           M
City              Manakin Sabot
State                        VA
Country                     USA
Half            0 days 01:51:09
40K             0 days 03:59:10
Pace                    0:09:40
TotalSeconds            14350.0
HalfSeconds              6669.0
Name: 13619, dtype: object
Manalapan
 Age                          59
M/F                           M
City                  Manalapan
State                        NJ
Country                     USA
Half            0 days 01:46:28
40K             0 days 03:31:39
Pace                    0:08:33
TotalSeconds            12699.0
HalfSeconds              6388.0
Name: 18336, dtype: object
Manassas
 Age                          55
M/F                           M
City                   Manassas
State                        VA
Country                     USA
Half            0 days 01:43:47
40K             0 days 03:25:58
Pace                    0:08:19
TotalSeconds            12358.0
HalfSeconds              6227.0
Name: 14439, dtype: object
Manassas Park
 Age                          43
M/F                           M
City              Manassas Park
State                        VA
Country                     USA
Half            0 days 01:29:22
40K             0 days 02:48:41
Pace                    0:06:47
TotalSeconds            10121.0
HalfSeconds              5362.0
Name: 6133, dtype: object
Manaus
 Age                          51
M/F                           F
City                     Manaus
State                       NaN
Country                     BRA
Half            0 days 02:09:20
40K             0 days 04:18:06
Pace                    0:10:26
TotalSeconds            15486.0
HalfSeconds              7760.0
Name: 30252, dtype: object
Manchester
 Age                          32
M/F                           M
City                 Manchester
State                        NH
Country                     USA
Half            0 days 01:23:55
40K             0 days 02:42:43
Pace                    0:06:33
TotalSeconds             9763.0
HalfSeconds              5035.0
Name: 1347, dtype: object
Manchester By The Sea
 Age                                44
M/F                                 F
City            Manchester By The Sea
State                              MA
Country                           USA
Half                  0 days 00:00:00
40K                   0 days 04:06:16
Pace                          0:09:56
TotalSeconds                  14776.0
HalfSeconds                       0.0
Name: 21703, dtype: object
Manchester Center
 Age                            47
M/F                             M
City            Manchester Center
State                          VT
Country                       USA
Half              0 days 01:41:06
40K               0 days 03:19:29
Pace                      0:08:04
TotalSeconds              11969.0
HalfSeconds                6066.0
Name: 10359, dtype: object
Mandan
 Age                          53
M/F                           M
City                     Mandan
State                        ND
Country                     USA
Half            0 days 01:36:57
40K             0 days 03:17:43
Pace                    0:08:04
TotalSeconds            11863.0
HalfSeconds              5817.0
Name: 8713, dtype: object
Mandeville
 Age                          46
M/F                           M
City                 Mandeville
State                        LA
Country                     USA
Half            0 days 01:33:03
40K             0 days 03:00:05
Pace                    0:07:16
TotalSeconds            10805.0
HalfSeconds              5583.0
Name: 7367, dtype: object
Manhasset
 Age                          35
M/F                           F
City                  Manhasset
State                        NY
Country                     USA
Half            0 days 01:37:24
40K             0 days 03:05:56
Pace                    0:07:28
TotalSeconds            11156.0
HalfSeconds              5844.0
Name: 6164, dtype: object
Manhattan
 Age                          27
M/F                           M
City                  Manhattan
State                        KS
Country                     USA
Half            0 days 01:27:38
40K             0 days 02:47:17
Pace                    0:06:46
TotalSeconds            10037.0
HalfSeconds              5258.0
Name: 4030, dtype: object
Manhattan Beach
 Age                          41
M/F                           M
City            Manhattan Beach
State                        CA
Country                     USA
Half            0 days 01:28:49
40K             0 days 02:53:16
Pace                    0:07:00
TotalSeconds            10396.0
HalfSeconds              5329.0
Name: 8628, dtype: object
Manheim
 Age                          60
M/F                           M
City                    Manheim
State                        PA
Country                     USA
Half            0 days 01:43:22
40K             0 days 03:29:26
Pace                    0:08:27
TotalSeconds            12566.0
HalfSeconds              6202.0
Name: 15038, dtype: object
Manila
 Age                          45
M/F                           F
City                     Manila
State                       NaN
Country                     PHI
Half            0 days 01:49:42
40K             0 days 03:35:53
Pace                    0:08:41
TotalSeconds            12953.0
HalfSeconds              6582.0
Name: 23206, dtype: object
Manistee
 Age                          39
M/F                           F
City                   Manistee
State                        MI
Country                     USA
Half            0 days 01:49:02
40K             0 days 03:31:37
Pace                    0:08:33
TotalSeconds            12697.0
HalfSeconds              6542.0
Name: 18662, dtype: object
Manistique
 Age                          49
M/F                           F
City                 Manistique
State                        MI
Country                     USA
Half            0 days 01:57:01
40K             0 days 03:49:47
Pace                    0:09:18
TotalSeconds            13787.0
HalfSeconds              7021.0
Name: 24083, dtype: object
Manitou Springs
 Age                          61
M/F                           M
City            Manitou Springs
State                        CO
Country                     USA
Half            0 days 01:54:04
40K             0 days 03:52:10
Pace                    0:09:23
TotalSeconds            13930.0
HalfSeconds              6844.0
Name: 9860, dtype: object
Manitowoc
 Age                          36
M/F                           M
City                  Manitowoc
State                        WI
Country                     USA
Half            0 days 01:53:43
40K             0 days 03:46:13
Pace                    0:09:07
TotalSeconds            13573.0
HalfSeconds              6823.0
Name: 26263, dtype: object
Manizales
 Age                          62
M/F                           M
City                  Manizales
State                       NaN
Country                     COL
Half            0 days 01:45:30
40K             0 days 03:29:43
Pace                    0:08:27
TotalSeconds            12583.0
HalfSeconds              6330.0
Name: 20869, dtype: object
Mankato
 Age                          34
M/F                           M
City                    Mankato
State                        MN
Country                     USA
Half            0 days 01:25:47
40K             0 days 02:46:23
Pace                    0:06:44
TotalSeconds             9983.0
HalfSeconds              5147.0
Name: 2791, dtype: object
Manlius
 Age                          65
M/F                           M
City                    Manlius
State                        NY
Country                     USA
Half            0 days 01:46:56
40K             0 days 03:29:34
Pace                    0:08:29
TotalSeconds            12574.0
HalfSeconds              6416.0
Name: 14230, dtype: object
Mannheim
 Age                          51
M/F                           M
City                   Mannheim
State                       NaN
Country                     GER
Half            0 days 01:58:53
40K             0 days 04:01:19
Pace                    0:09:45
TotalSeconds            14479.0
HalfSeconds              7133.0
Name: 12821, dtype: object
Manorville
 Age                          44
M/F                           M
City                 Manorville
State                        NY
Country                     USA
Half            0 days 01:31:35
40K             0 days 03:00:12
Pace                    0:07:17
TotalSeconds            10812.0
HalfSeconds              5495.0
Name: 5471, dtype: object
Manotick
 Age                          49
M/F                           F
City                   Manotick
State                        ON
Country                     CAN
Half            0 days 01:46:51
40K             0 days 03:25:25
Pace                    0:08:19
TotalSeconds            12325.0
HalfSeconds              6411.0
Name: 21860, dtype: object
Mansfield
 Age                          24
M/F                           M
City                  Mansfield
State                        MA
Country                     USA
Half            0 days 01:16:05
40K             0 days 02:31:46
Pace                    0:06:12
TotalSeconds             9106.0
HalfSeconds              4565.0
Name: 332, dtype: object
Mansfield Center
 Age                           38
M/F                            F
City            Mansfield Center
State                         CT
Country                      USA
Half             0 days 01:38:19
40K              0 days 03:07:45
Pace                     0:07:33
TotalSeconds             11265.0
HalfSeconds               5899.0
Name: 11068, dtype: object
Mansfield Ctr
 Age                          40
M/F                           F
City              Mansfield Ctr
State                        CT
Country                     USA
Half            0 days 01:34:18
40K             0 days 03:00:14
Pace                    0:07:16
TotalSeconds            10814.0
HalfSeconds              5658.0
Name: 8453, dtype: object
Manteca
 Age                          46
M/F                           M
City                    Manteca
State                        CA
Country                     USA
Half            0 days 01:41:17
40K             0 days 03:25:56
Pace                    0:08:23
TotalSeconds            12356.0
HalfSeconds              6077.0
Name: 12218, dtype: object
Manteo
 Age                          42
M/F                           F
City                     Manteo
State                        NC
Country                     USA
Half            0 days 01:49:34
40K             0 days 03:30:03
Pace                    0:08:28
TotalSeconds            12603.0
HalfSeconds              6574.0
Name: 21579, dtype: object
Manvel
 Age                          46
M/F                           M
City                     Manvel
State                        TX
Country                     USA
Half            0 days 01:43:08
40K             0 days 03:36:26
Pace                    0:08:45
TotalSeconds            12986.0
HalfSeconds              6188.0
Name: 11556, dtype: object
Manville
 Age                          29
M/F                           F
City                   Manville
State                        RI
Country                     USA
Half            0 days 02:33:58
40K             0 days 05:34:37
Pace                    0:13:27
TotalSeconds            20077.0
HalfSeconds              9238.0
Name: 27719, dtype: object
Manzano
 Age                          48
M/F                           F
City                    Manzano
State                       NaN
Country                     ITA
Half            0 days 01:52:24
40K             0 days 03:41:55
Pace                    0:08:57
TotalSeconds            13315.0
HalfSeconds              6744.0
Name: 23136, dtype: object
Maple
 Age                          51
M/F                           M
City                      Maple
State                        ON
Country                     CAN
Half            0 days 01:32:13
40K             0 days 03:09:47
Pace                    0:07:42
TotalSeconds            11387.0
HalfSeconds              5533.0
Name: 7333, dtype: object
Maple Grove
 Age                          24
M/F                           F
City                Maple Grove
State                        MN
Country                     USA
Half            0 days 01:30:23
40K             0 days 02:52:09
Pace                    0:06:55
TotalSeconds            10329.0
HalfSeconds              5423.0
Name: 4479, dtype: object
Maple Park
 Age                          51
M/F                           F
City                 Maple Park
State                        IL
Country                     USA
Half            0 days 02:03:58
40K             0 days 04:30:46
Pace                    0:10:55
TotalSeconds            16246.0
HalfSeconds              7438.0
Name: 22889, dtype: object
Maple Ridge
 Age                          51
M/F                           M
City                Maple Ridge
State                        BC
Country                     CAN
Half            0 days 01:36:14
40K             0 days 03:11:16
Pace                    0:07:44
TotalSeconds            11476.0
HalfSeconds              5774.0
Name: 5270, dtype: object
Maple Valley
 Age                          39
M/F                           M
City               Maple Valley
State                        WA
Country                     USA
Half            0 days 01:34:45
40K             0 days 03:05:29
Pace                    0:07:28
TotalSeconds            11129.0
HalfSeconds              5685.0
Name: 2597, dtype: object
Mapleton
 Age                          45
M/F                           M
City                   Mapleton
State                        UT
Country                     USA
Half            0 days 01:41:07
40K             0 days 03:18:04
Pace                    0:08:00
TotalSeconds            11884.0
HalfSeconds              6067.0
Name: 5855, dtype: object
Maplewood
 Age                          34
M/F                           M
City                  Maplewood
State                        NJ
Country                     USA
Half            0 days 01:27:16

Markham
 Age                          38
M/F                           M
City                    Markham
State                        ON
Country                     CAN
Half            0 days 01:32:56
40K             0 days 03:01:24
Pace                    0:07:20
TotalSeconds            10884.0
HalfSeconds              5576.0
Name: 6817, dtype: object
Marlboro
 Age                          31
M/F                           M
City                   Marlboro
State                        MA
Country                     USA
Half            0 days 02:08:57
40K             0 days 04:27:18
Pace                    0:10:50
TotalSeconds            16038.0
HalfSeconds              7737.0
Name: 29128, dtype: object
Marlborough
 Age                          46
M/F                           M
City                Marlborough
State                        MA
Country                     USA
Half            0 days 01:24:32
40K             0 days 02:43:41
Pace                    0:06:36
TotalSeconds             9821.0
HalfSeconds              5072.0
Name: 1731, dtype: object
Marlow
 Age                          48
M/F                           F
City                     Marlow
State                       NaN
Country                     GBR
Half            0 days 01:54:10
40K             0 days 03:37:32
Pace                    0:08:44
TotalSeconds            13052.0
HalfSeconds              6850.0
Name: 22063, dtype: object
Marlton
 Age                          42
M/F                           M
City                    Marlton
State                        NJ
Country                     USA
Half            0 days 01:35:23
40K             0 days 03:09:05
Pace                    0:07:39
TotalSeconds            11345.0
HalfSeconds              5723.0
Name: 8869, dtype: object
Marmora
 Age                          24
M/F                           F
City                    Marmora
State                        NJ
Country                     USA
Half            0 days 01:45:01
40K             0 days 03:27:00
Pace                    0:08:20
TotalSeconds            12420.0
HalfSeconds              6301.0
Name: 8722, dtype: object
Marne
 Age                          30
M/F                           F
City                      Marne
State                        MI
Country                     USA
Half            0 days 01:45:07
40K             0 days 03:32:18
Pace                    0:08:34
TotalSeconds            12738.0
HalfSeconds              6307.0
Name: 13608, dtype: object
Marquette
 Age                          47
M/F                           M
City                  Marquette
State                        MI
Country                     USA
Half            0 days 01:33:48
40K             0 days 03:02:54
Pace                    0:07:24
TotalSeconds            10974.0
HalfSeconds              5628.0
Name: 6497, dtype: object
Marriottsville
 Age                          37
M/F                           M
City             Marriottsville
State                        MD
Country                     USA
Half            0 days 01:34:04
40K             0 days 03:08:59
Pace                    0:07:39
TotalSeconds            11339.0
HalfSeconds              5644.0
Name: 6160, dtype: object
Mars
 Age                          47
M/F                           M
City                       Mars
State                        PA
Country                     USA
Half            0 days 01:44:50
40K             0 days 03:48:32
Pace                    0:09:12
TotalSeconds            13712.0
HalfSeconds              6290.0
Name: 9397, dtype: object
Marshall
 Age                          23
M/F                           F
City                   Marshall
State                        MO
Country                     USA
Half            0 days 01:45:38
40K             0 days 03:11:20
Pace                    0:07:39
TotalSeconds            11480.0
HalfSeconds              6338.0
Name: 11724, dtype: object
Marshalltown
 Age                          47
M/F                           M
City               Marshalltown
State                        IA
Country                     USA
Half            0 days 01:39:07
40K             0 days 03:11:46
Pace                    0:07:48
TotalSeconds            11506.0
HalfSeconds              5947.0
Name: 10132, dtype: object
Marshfield
 Age                          48
M/F                           M
City                 Marshfield
State                        MA
Country                     USA
Half            0 days 01:30:04
40K             0 days 02:56:17
Pace                    0:07:05
TotalSeconds            10577.0
HalfSeconds              5404.0
Name: 4481, dtype: object
Marshfield Hills
 Age                           43
M/F                            M
City            Marshfield Hills
State                         MA
Country                      USA
Half             0 days 01:45:16
40K              0 days 03:21:30
Pace                     0:08:06
TotalSeconds             12090.0
HalfSeconds               6316.0
Name: 9367, dtype: object
Marstons Mills
 Age                          35
M/F                           M
City             Marstons Mills
State                        MA
Country                     USA
Half            0 days 01:20:23
40K             0 days 02:34:53
Pace                    0:06:14
TotalSeconds             9293.0
HalfSeconds              4823.0
Name: 937, dtype: object
Martinez
 Age                          44
M/F                           F
City                   Martinez
State                        CA
Country                     USA
Half            0 days 01:48:01
40K             0 days 03:32:10
Pace                    0:08:33
TotalSeconds            12730.0
HalfSeconds              6481.0
Name: 13193, dtype: object
Martinsburg
 Age                          33
M/F                           M
City                Martinsburg
State                        WV
Country                     USA
Half            0 days 01:28:21
40K             0 days 02:54:23
Pace                    0:07:05
TotalSeconds            10463.0
HalfSeconds              5301.0
Name: 5354, dtype: object
Martinsville
 Age                          39
M/F                           M
City               Martinsville
State                        VA
Country                     USA
Half            0 days 01:29:38
40K             0 days 03:05:48
Pace                    0:07:33
TotalSeconds            11148.0
HalfSeconds              5378.0
Name: 4202, dtype: object
Marvin
 Age                          60
M/F                           M
City                     Marvin
State                        NC
Country                     USA
Half            0 days 01:39:26
40K             0 days 03:11:48
Pace                    0:07:46
TotalSeconds            11508.0
HalfSeconds              5966.0
Name: 11078, dtype: object
Maryland Heights
 Age                           24
M/F                            F
City            Maryland Heights
State                         MO
Country                      USA
Half             0 days 01:39:17
40K              0 days 03:21:37
Pace                     0:08:07
TotalSeconds             12097.0
HalfSeconds               5957.0
Name: 14640, dtype: object
Marysville
 Age                          46
M/F                           M
City                 Marysville
State                        MI
Country                     USA
Half            0 days 01:38:13
40K             0 days 03:17:34
Pace                    0:08:03
TotalSeconds            11854.0
HalfSeconds              5893.0
Name: 7527, dtype: object
Maryville
 Age                          40
M/F                           M
City                  Maryville
State                        TN
Country                     USA
Half            0 days 01:31:46
40K             0 days 03:09:22
Pace                    0:07:46
TotalSeconds            11362.0
HalfSeconds              5506.0
Name: 6857, dtype: object
Mashpee
 Age                          28
M/F                           M
City                    Mashpee
State                        MA
Country                     USA
Half            0 days 01:56:55
40K             0 days 03:55:41
Pace                    0:09:34
TotalSeconds            14141.0
HalfSeconds              7015.0

Name: 31360, dtype: object
Mason
 Age                          47
M/F                           M
City                      Mason
State                        OH
Country                     USA
Half            0 days 01:32:09
40K             0 days 02:57:08
Pace                    0:07:09
TotalSeconds            10628.0
HalfSeconds              5529.0
Name: 9034, dtype: object
Mason City
 Age                          59
M/F                           M
City                 Mason City
State                        IA
Country                     USA
Half            0 days 01:46:29
40K             0 days 03:34:16
Pace                    0:08:40
TotalSeconds            12856.0
HalfSeconds              6389.0
Name: 20225, dtype: object
Maspeth
 Age                          43
M/F                           M
City                    Maspeth
State                        NY
Country                     USA
Half            0 days 01:29:52
40K             0 days 02:54:43
Pace                    0:07:01
TotalSeconds            10483.0
HalfSeconds              5392.0
Name: 3582, dtype: object
Massapequa
 Age                          30
M/F                           F
City                 Massapequa
State                        NY
Country                     USA
Half            0 days 02:15:25
40K             0 days 04:54:17
Pace                    0:11:51
TotalSeconds            17657.0
HalfSeconds              8125.0
Name: 20000, dtype: object
Massapequa Park
 Age                          38
M/F                           F
City            Massapequa Park
State                        NY
Country                     USA
Half            0 days 01:50:11
40K             0 days 03:50:38
Pace                    0:09:21
TotalSeconds            13838.0
HalfSeconds              6611.0
Name: 18236, dtype: object
Massillon
 Age                          55
M/F                           M
City                  Massillon
State                        OH
Country                     USA
Half            0 days 01:32:05
40K             0 days 02:59:13
Pace                    0:07:14
TotalSeconds            10753.0
HalfSeconds              5525.0
Name: 7213, dtype: object
Matagami
 Age                          57
M/F                           M
City                   Matagami
State                        QC
Country                     CAN
Half            0 days 02:00:44
40K             0 days 03:59:37
Pace                    0:09:33
TotalSeconds            14377.0
HalfSeconds              7244.0
Name: 18626, dtype: object
Matamoros, Tamps
 Age                           49
M/F                            M
City            Matamoros, Tamps
State                        NaN
Country                      MEX
Half             0 days 01:59:26
40K              0 days 04:30:27
Pace                     0:10:57
TotalSeconds             16227.0
HalfSeconds               7166.0
Name: 31661, dtype: object
Mather
 Age                          27
M/F                           F
City                     Mather
State                        CA
Country                     USA
Half            0 days 01:44:10
40K             0 days 03:28:11
Pace                    0:08:26
TotalSeconds            12491.0
HalfSeconds              6250.0
Name: 17804, dtype: object
Matsudo , Chiba-Pref.
 Age                                65
M/F                                 M
City            Matsudo , Chiba-Pref.
State                             NaN
Country                           JPN
Half                  0 days 01:58:41
40K                   0 days 04:08:56
Pace                          0:10:06
TotalSeconds                  14936.0
HalfSeconds                    7121.0
Name: 24449, dtype: object
Mattapoisett
 Age                          52
M/F                           F
City               Mattapoisett
State                        MA
Country                     USA
Half            0 days 01:53:51
40K             0 days 03:58:49
Pace                    0:09:37
TotalSeconds            14329.0
HalfSeconds              6831.0
Name: 19964, dtype: object
Mattawan
 Age                          48
M/F                           F
City                   Mattawan
State                        MI
Country                     USA
Half            0 days 01:57:46
40K             0 days 04:08:58
Pace                    0:10:06
TotalSeconds            14938.0
HalfSeconds              7066.0
Name: 24438, dtype: object
Matthews
 Age                          50
M/F                           M
City                   Matthews
State                        NC
Country                     USA
Half            0 days 01:33:17
40K             0 days 03:04:52
Pace                    0:07:30
TotalSeconds            11092.0
HalfSeconds              5597.0
Name: 9421, dtype: object
Mattoon
 Age                          52
M/F                           M
City                    Mattoon
State                        IL
Country                     USA
Half            0 days 01:41:03
40K             0 days 03:26:41
Pace                    0:08:24
TotalSeconds            12401.0
HalfSeconds              6063.0
Name: 13786, dtype: object
Mauldin
 Age                          34
M/F                           M
City                    Mauldin
State                        SC
Country                     USA
Half            0 days 01:33:46
40K             0 days 03:03:27
Pace                    0:07:26
TotalSeconds            11007.0
HalfSeconds              5626.0
Name: 3587, dtype: object
Maumee
 Age                          48
M/F                           M
City                     Maumee
State                        OH
Country                     USA
Half            0 days 01:33:03
40K             0 days 03:29:27
Pace                    0:08:29
TotalSeconds            12567.0
HalfSeconds              5583.0
Name: 4442, dtype: object
Mautern
 Age                          47
M/F                           M
City                    Mautern
State                       NaN
Country                     AUT
Half            0 days 01:52:07
40K             0 days 03:44:35
Pace                    0:09:12
TotalSeconds            13475.0
HalfSeconds              6727.0
Name: 31764, dtype: object
Mavcice
 Age                          45
M/F                           M
City                    Mavcice
State                       NaN
Country                     SLO
Half            0 days 01:32:18
40K             0 days 03:08:03
Pace                    0:07:37
TotalSeconds            11283.0
HalfSeconds              5538.0
Name: 7002, dtype: object
Mawson
 Age                          33
M/F                           F
City                     Mawson
State                       NaN
Country                     AUS
Half            0 days 01:44:32
40K             0 days 03:18:32
Pace                    0:07:59
TotalSeconds            11912.0
HalfSeconds              6272.0
Name: 3994, dtype: object
Mayfield
 Age                          28
M/F                           M
City                   Mayfield
State                        PA
Country                     USA
Half            0 days 01:27:52
40K             0 days 03:14:08
Pace                    0:07:55
TotalSeconds            11648.0
HalfSeconds              5272.0
Name: 2263, dtype: object
Mayfield Heights
 Age                           46
M/F                            F
City            Mayfield Heights
State                         OH
Country                      USA
Half             0 days 01:41:39
40K              0 days 03:18:00
Pace                     0:07:58
TotalSeconds             11880.0
HalfSeconds               6099.0
Name: 13950, dtype: object
Maynard
 Age                          31
M/F                           F
City                    Maynard
State                        MA
Country                     USA
Half            0 days 01:40:18
40K             0 days 03:10:55
Pace                    0:07:42
TotalSeconds            11455.0
HalfSeconds              6018.0
Name: 11733, dtype: object
Maynooth
 Age                          41
M/F                           M
City                   Maynooth
State                       NaN
Country                     IRL
Half            0 days 01:26:36
40K             0 days 02:50:52
Pace                    0:06:53
TotalSeconds            10252.0
HalfSeconds              5196.0
Name: 2395, dtype: object
Maywood
 Age                          21
M/F                           M
City                    Maywood
State                        NJ
Country                     USA
Half            0 days 01:56:52
40K             0 days 03:55:32
Pace                    0:09:26
TotalSeconds            14132.0
HalfSeconds              7012.0
Name: 25370, dtype: object
Mcallen
 Age                          53
M/F                           M
City                    Mcallen
State                        TX
Country                     USA
Half            0 days 01:27:14
40K             0 days 02:52:15
Pace                    0:06:55
TotalSeconds            10335.0
HalfSeconds              5234.0
Name: 2985, dtype: object
Mccammon
 Age                          43
M/F                           F
City                   Mccammon
State                        ID
Country                     USA
Half            0 days 01:40:09
40K             0 days 03:18:20
Pace                    0:08:02
TotalSeconds            11900.0
HalfSeconds              6009.0
Name: 16016, dtype: object
Mccook
 Age                          48
M/F                           M
City                     Mccook
State                        NE
Country                     USA
Half            0 days 01:34:17
40K             0 days 03:03:10
Pace                    0:07:24
TotalSeconds            10990.0
HalfSeconds              5657.0
Name: 11135, dtype: object
Mcdonough
 Age                          44
M/F                           M
City                  Mcdonough
State                        GA
Country                     USA
Half            0 days 01:37:00
40K             0 days 03:06:41
Pace                    0:07:33
TotalSeconds            11201.0
HalfSeconds              5820.0
Name: 2891, dtype: object
Mcfarland
 Age                          31
M/F                           F
City                  Mcfarland
State                        WI
Country                     USA
Half            0 days 01:27:26
40K             0 days 02:54:57
Pace                    0:07:05
TotalSeconds            10497.0
HalfSeconds              5246.0
Name: 3076, dtype: object
Mcgregor
 Age                          49
M/F                           F
City                   Mcgregor
State                        TX
Country                     USA
Half            0 days 01:42:43
40K             0 days 03:25:28
Pace                    0:08:20
TotalSeconds            12328.0
HalfSeconds              6163.0
Name: 21762, dtype: object
Mchenry
 Age                          49
M/F                           M
City                    Mchenry
State                        IL
Country                     USA
Half            0 days 01:27:11
40K             0 days 02:48:26
Pace                    0:06:47
TotalSeconds            10106.0
HalfSeconds              5231.0
Name: 1885, dtype: object
Mckenzie
 Age                          36
M/F                           F
City                   Mckenzie
State                        TN
Country                     USA
Half            0 days 01:39:26
40K             0 days 03:07:32
Pace                    0:07:31
TotalSeconds            11252.0
HalfSeconds              5966.0
Name: 14198, dtype: object
Mckinleyville
 Age                          56
M/F                           M
City              Mckinleyville
State                        CA
Country                     USA
Half            0 days 01:46:35
40K             0 days 03:35:52
Pace                    0:08:47
TotalSeconds            12952.0
HalfSeconds              6395.0
Name: 18556, dtype: object
Mckinney
 Age                          48
M/F                           M
City                   Mckinney
State                        TX
Country                     USA
Half            0 days 01:27:36
40K             0 days 02:52:30
Pace                    0:06:57
TotalSeconds            10350.0
HalfSeconds              5256.0
Name: 2220, dtype: object
Mclaren Vale
 Age                          38
M/F                           F
City               Mclaren Vale
State                       NaN
Country                     AUS
Half            0 days 01:49:01
40K             0 days 03:34:28
Pace                    0:08:39
TotalSeconds            12868.0
HalfSeconds              6541.0
Name: 18315, dtype: object
Mclean
 Age                          24
M/F                           M
City                     Mclean
State                        VA
Country                     USA
Half            0 days 01:24:06
40K             0 days 02:43:36
Pace                    0:06:35
TotalSeconds             9816.0
HalfSeconds              5046.0
Name: 2073, dtype: object
Mcminnville
 Age                          37
M/F                           F
City                Mcminnville
State                        TN
Country                     USA
Half            0 days 01:38:21
40K             0 days 03:11:59
Pace                    0:07:45
TotalSeconds            11519.0
HalfSeconds              5901.0
Name: 11472, dtype: object
Mcmurray
 Age                          38
M/F                           F
City                   Mcmurray
State                        PA
Country                     USA
Half            0 days 01:37:58
40K             0 days 03:12:40
Pace                    0:07:48
TotalSeconds            11560.0
HalfSeconds              5878.0
Name: 12867, dtype: object
Mead
 Age                          41
M/F                           F
City                       Mead
State                        WA
Country                     USA
Half            0 days 01:55:34
40K             0 days 03:43:12
Pace                    0:08:59
TotalSeconds            13392.0
HalfSeconds              6934.0
Name: 20441, dtype: object
Meadow Springs
 Age                          57
M/F                           M
City             Meadow Springs
State                       NaN
Country                     AUS
Half            0 days 01:38:48
40K             0 days 03:35:28
Pace                    0:08:49
TotalSeconds            12928.0
HalfSeconds              5928.0
Name: 8712, dtype: object
Meadville
 Age                          43
M/F                           F
City                  Meadville
State                        PA
Country                     USA
Half            0 days 01:51:09
40K             0 days 03:29:55
Pace                    0:08:26
TotalSeconds            12595.0
HalfSeconds              6669.0
Name: 21067, dtype: object
Meaford
 Age                          50
M/F                           M
City                    Meaford
State                        ON
Country                     CAN
Half            0 days 01:39:23
40K             0 days 03:20:10
Pace                    0:08:12
TotalSeconds            12010.0
HalfSeconds              5963.0
Name: 6326, dtype: object
Mebane
 Age                          55
M/F                           M
City                     Mebane
State                        NC
Country                     USA
Half            0 days 01:45:44
40K             0 days 03:23:26
Pace                    0:08:12
TotalSeconds            12206.0
HalfSeconds              6344.0
Name: 20216, dtype: object
Mechanicsburg
 Age                          48
M/F                           M
City              Mechanicsburg
State                        PA
Country                     USA
Half            0 days 01:36:50
40K             0 days 03:04:45
Pace                    0:07:25
TotalSeconds            11085.0
HalfSeconds              5810.0
Name: 7588, dtype: object
Mechanicsville
 Age                          36
M/F                           F
City             Mechanicsville
State                        VA
Country                     USA
Half            0 days 01:38:57
40K             0 days 03:09:47
Pace                    0:07:38
TotalSeconds            11387.0
HalfSeconds              5937.0
Name: 9783, dtype: object
Mechelen

 Age                          44
M/F                           M
City                   Mechelen
State                       NaN
Country                     BEL
Half            0 days 01:34:55
40K             0 days 03:14:24
Pace                    0:07:52
TotalSeconds            11664.0
HalfSeconds              5695.0
Name: 6481, dtype: object
Medellin
 Age                          40
M/F                           M
City                   Medellin
State                       NaN
Country                     COL
Half            0 days 01:29:40
40K             0 days 03:09:40
Pace                    0:07:44
TotalSeconds            11380.0
HalfSeconds              5380.0
Name: 6216, dtype: object
Medellín
 Age                          47
M/F                           F
City                   Medellín
State                       NaN
Country                     COL
Half            0 days 01:37:19
40K             0 days 03:20:01
Pace                    0:08:05
TotalSeconds            12001.0
HalfSeconds              5839.0
Name: 16702, dtype: object
Medfield
 Age                          30
M/F                           M
City                   Medfield
State                        MA
Country                     USA
Half            0 days 01:24:45
40K             0 days 02:57:05
Pace                    0:07:13
TotalSeconds            10625.0
HalfSeconds              5085.0
Name: 740, dtype: object
Medford
 Age                          32
M/F                           M
City                    Medford
State                        MA
Country                     USA
Half            0 days 01:22:57
40K             0 days 02:40:16
Pace                    0:06:28
TotalSeconds             9616.0
HalfSeconds              4977.0
Name: 1206, dtype: object
Medford Lakes
 Age                          31
M/F                           F
City              Medford Lakes
State                        NJ
Country                     USA
Half            0 days 01:41:13
40K             0 days 03:25:55
Pace                    0:08:20
TotalSeconds            12355.0
HalfSeconds              6073.0
Name: 16769, dtype: object
Media
 Age                          36
M/F                           F
City                      Media
State                        PA
Country                     USA
Half            0 days 01:35:03
40K             0 days 03:07:31
Pace                    0:07:34
TotalSeconds            11251.0
HalfSeconds              5703.0
Name: 3919, dtype: object
Medifeld
 Age                          22
M/F                           F
City                   Medifeld
State                        MA
Country                     USA
Half            0 days 02:03:47
40K             0 days 04:20:31
Pace                    0:10:31
TotalSeconds            15631.0
HalfSeconds              7427.0
Name: 27165, dtype: object
Medina
 Age                          26
M/F                           F
City                     Medina
State                        MN
Country                     USA
Half            0 days 01:45:42
40K             0 days 03:29:05
Pace                    0:08:26
TotalSeconds            12545.0
HalfSeconds              6342.0
Name: 14422, dtype: object
Medinah
 Age                          50
M/F                           M
City                    Medinah
State                        IL
Country                     USA
Half            0 days 01:44:37
40K             0 days 03:28:50
Pace                    0:08:25
TotalSeconds            12530.0
HalfSeconds              6277.0
Name: 13488, dtype: object
Medway
 Age                          51
M/F                           M
City                     Medway
State                        MA
Country                     USA
Half            0 days 01:30:53
40K             0 days 03:01:12
Pace                    0:07:21
TotalSeconds            10872.0
HalfSeconds              5453.0
Name: 3996, dtype: object
Melbourn
 Age                          50
M/F                           M
City                   Melbourn
State                       NaN
Country                     GBR
Half            0 days 02:39:43
40K             0 days 05:23:34
Pace                    0:13:00
TotalSeconds            19414.0
HalfSeconds              9583.0
Name: 27287, dtype: object
Melbourne
 Age                          26
M/F                           M
City                  Melbourne
State                        FL
Country                     USA
Half            0 days 01:19:16
40K             0 days 02:33:35
Pace                    0:06:13
TotalSeconds             9215.0
HalfSeconds              4756.0
Name: 493, dtype: object
Mellen
 Age                          42
M/F                           F
City                     Mellen
State                        WI
Country                     USA
Half            0 days 01:45:56
40K             0 days 03:30:53
Pace                    0:08:29
TotalSeconds            12653.0
HalfSeconds              6356.0
Name: 16684, dtype: object
Melrose
 Age                          37
M/F                           M
City                    Melrose
State                        MA
Country                     USA
Half            0 days 01:21:12
40K             0 days 02:34:47
Pace                    0:06:14
TotalSeconds             9287.0
HalfSeconds              4872.0
Name: 978, dtype: object
Melville
 Age                          54
M/F                           M
City                   Melville
State                        NY
Country                     USA
Half            0 days 01:43:46
40K             0 days 03:35:08
Pace                    0:08:41
TotalSeconds            12908.0
HalfSeconds              6226.0
Name: 13469, dtype: object
Memphis
 Age                          33
M/F                           M
City                    Memphis
State                        TN
Country                     USA
Half            0 days 01:19:58
40K             0 days 02:47:32
Pace                    0:06:47
TotalSeconds            10052.0
HalfSeconds              4798.0
Name: 294, dtype: object
Menan
 Age                          56
M/F                           M
City                      Menan
State                        ID
Country                     USA
Half            0 days 01:47:50
40K             0 days 03:40:06
Pace                    0:08:56
TotalSeconds            13206.0
HalfSeconds              6470.0
Name: 16606, dtype: object
Menands
 Age                          42
M/F                           M
City                    Menands
State                        NY
Country                     USA
Half            0 days 01:37:43
40K             0 days 03:29:21
Pace                    0:08:30
TotalSeconds            12561.0
HalfSeconds              5863.0
Name: 8260, dtype: object
Menasha
 Age                          28
M/F                           F
City                    Menasha
State                        WI
Country                     USA
Half            0 days 01:40:15
40K             0 days 03:21:02
Pace                    0:08:08
TotalSeconds            12062.0
HalfSeconds              6015.0
Name: 11875, dtype: object
Mendham
 Age                          58
M/F                           M
City                    Mendham
State                        NJ
Country                     USA
Half            0 days 01:39:34
40K             0 days 03:15:41
Pace                    0:07:54
TotalSeconds            11741.0
HalfSeconds              5974.0
Name: 12065, dtype: object
Mendota Heights
 Age                          47
M/F                           F
City            Mendota Heights
State                        MN
Country                     USA
Half            0 days 01:52:52
40K             0 days 03:56:36
Pace                    0:09:38
TotalSeconds            14196.0
HalfSeconds              6772.0
Name: 21936, dtype: object
Menifee
 Age                          40
M/F                           F
City                    Menifee
State                        CA
Country                     USA
Half            0 days 02:02:51
40K             0 days 03:54:19
Pace                    0:09:25
TotalSeconds            14059.0
HalfSeconds              7371.0
Name: 21721, dtype: object
Menlo Park
 Age                          24
M/F                           M
City                 Menlo Park
State                        CA
Country                     USA
Half            0 days 01:13:54
40K             0 days 02:26:01
Pace                    0:05:55
TotalSeconds             8761.0
HalfSeconds              4434.0
Name: 225, dtype: object
Menomonee Falls
 Age                          39
M/F                           M
City            Menomonee Falls
State                        WI
Country                     USA
Half            0 days 01:32:22
40K             0 days 03:04:52
Pace                    0:07:28
TotalSeconds            11092.0
HalfSeconds              5542.0
Name: 3195, dtype: object
Mentor
 Age                          40
M/F                           M
City                     Mentor
State                        OH
Country                     USA
Half            0 days 01:26:45
40K             0 days 02:55:05
Pace                    0:07:06
TotalSeconds            10505.0
HalfSeconds              5205.0
Name: 1298, dtype: object
Meota
 Age                          54
M/F                           M
City                      Meota
State                        SK
Country                     CAN
Half            0 days 01:41:01
40K             0 days 03:14:56
Pace                    0:07:52
TotalSeconds            11696.0
HalfSeconds              6061.0
Name: 10417, dtype: object
Meppershall
 Age                          45
M/F                           M
City                Meppershall
State                       NaN
Country                     GBR
Half            0 days 01:50:25
40K             0 days 03:48:38
Pace                    0:09:19
TotalSeconds            13718.0
HalfSeconds              6625.0
Name: 9669, dtype: object
Mequon
 Age                          45
M/F                           M
City                     Mequon
State                        WI
Country                     USA
Half            0 days 01:34:04
40K             0 days 03:00:08
Pace                    0:07:15
TotalSeconds            10808.0
HalfSeconds              5644.0
Name: 7414, dtype: object
Merced
 Age                          44
M/F                           M
City                     Merced
State                        CA
Country                     USA
Half            0 days 01:36:45
40K             0 days 03:38:18
Pace                    0:08:52
TotalSeconds            13098.0
HalfSeconds              5805.0
Name: 8376, dtype: object
Mercer
 Age                          39
M/F                           M
City                     Mercer
State                        PA
Country                     USA
Half            0 days 01:38:43
40K             0 days 03:17:51
Pace                    0:07:58
TotalSeconds            11871.0
HalfSeconds              5923.0
Name: 6073, dtype: object
Mercer Island
 Age                          47
M/F                           M
City              Mercer Island
State                        WA
Country                     USA
Half            0 days 01:26:48
40K             0 days 03:04:32
Pace                    0:07:36
TotalSeconds            11072.0
HalfSeconds              5208.0
Name: 2888, dtype: object
Merceuil
 Age                          41
M/F                           M
City                   Merceuil
State                       NaN
Country                     FRA
Half            0 days 01:34:43
40K             0 days 03:13:09
Pace                    0:07:51
TotalSeconds            11589.0
HalfSeconds              5683.0
Name: 4338, dtype: object
Mercier
 Age                          42
M/F                           M
City                    Mercier
State                        QC
Country                     CAN
Half            0 days 01:35:39
40K             0 days 03:18:08
Pace                    0:08:01
TotalSeconds            11888.0
HalfSeconds              5739.0
Name: 8541, dtype: object
Meriden
 Age                          44
M/F                           F
City                    Meriden
State                        CT
Country                     USA
Half            0 days 01:42:40
40K             0 days 03:26:33
Pace                    0:08:21
TotalSeconds            12393.0
HalfSeconds              6160.0
Name: 15192, dtype: object
Meridian
 Age                          34
M/F                           M
City                   Meridian
State                        MS
Country                     USA
Half            0 days 01:30:49
40K             0 days 02:57:58
Pace                    0:07:13
TotalSeconds            10678.0
HalfSeconds              5449.0
Name: 3098, dtype: object
Merion Station
 Age                          47
M/F                           M
City             Merion Station
State                        PA
Country                     USA
Half            0 days 01:40:59
40K             0 days 03:15:41
Pace                    0:07:54
TotalSeconds            11741.0
HalfSeconds              6059.0
Name: 12332, dtype: object
Merkel
 Age                          26
M/F                           F
City                     Merkel
State                        TX
Country                     USA
Half            0 days 01:47:04
40K             0 days 03:35:48
Pace                    0:08:41
TotalSeconds            12948.0
HalfSeconds              6424.0
Name: 17858, dtype: object
Merliot
 Age                          61
M/F                           M
City                    Merliot
State                       NaN
Country                     ESA
Half            0 days 01:48:04
40K             0 days 04:00:38
Pace                    0:09:43
TotalSeconds            14438.0
HalfSeconds              6484.0
Name: 19182, dtype: object
Merrick
 Age                          53
M/F                           M
City                    Merrick
State                        NY
Country                     USA
Half            0 days 01:37:19
40K             0 days 03:24:17
Pace                    0:08:16
TotalSeconds            12257.0
HalfSeconds              5839.0
Name: 9841, dtype: object
Merrimac
 Age                          41
M/F                           M
City                   Merrimac
State                        MA
Country                     USA
Half            0 days 01:33:44
40K             0 days 02:58:57
Pace                    0:07:11
TotalSeconds            10737.0
HalfSeconds              5624.0
Name: 6431, dtype: object
Merrimack
 Age                          28
M/F                           M
City                  Merrimack
State                        NH
Country                     USA
Half            0 days 01:31:24
40K             0 days 02:49:47
Pace                    0:06:50
TotalSeconds            10187.0
HalfSeconds              5484.0
Name: 27219, dtype: object
Merritt Island
 Age                          46
M/F                           F
City             Merritt Island
State                        FL
Country                     USA
Half            0 days 01:40:51
40K             0 days 03:16:21
Pace                    0:07:55
TotalSeconds            11781.0
HalfSeconds              6051.0
Name: 13014, dtype: object
Mesa
 Age                          35
M/F                           M
City                       Mesa
State                        AZ
Country                     USA
Half            0 days 01:19:13
40K             0 days 02:36:14
Pace                    0:06:19
TotalSeconds             9374.0
HalfSeconds              4753.0
Name: 380, dtype: object
Mesquite
 Age                          52
M/F                           F
City                   Mesquite
State                        NV
Country                     USA
Half            0 days 01:56:17
40K             0 days 03:49:02
Pace                    0:09:16
TotalSeconds            13742.0
HalfSeconds              6977.0
Name: 18177, dtype: object
Metabetchouan
 Age                          56
M/F                           M
City              Metabetchouan
State                        QC
Country                     CAN
Half            0 days 01:42:26
40K             0 days 03:16:30
Pace                    0:07:54
TotalSeconds            11790.0
HalfSeconds              6146.0
Name: 10218, dtype: object
Metairie
 Age                          32
M/F                           M
City                   Metairie
State                        LA
Country                     USA
Half            0 days 01:27:55
40K             0 days 03:24:54
Pace                    0:08:24
TotalSeconds            12294.0
HalfSeconds              5275.0
Name: 2773, dtype: object
Metamora
 Age                          27
M/F                           F
City                   Metamora
State                        IL
Country                     USA
Half            0 days 01:45:23
40K             0 days 03:29:43
Pace                    0:08:26
TotalSeconds            12583.0
HalfSeconds              6323.0
Name: 13795, dtype: object
Metepec
 Age                          40
M/F                           F
City                    Metepec
State                       NaN
Country                     MEX
Half            0 days 01:46:57
40K             0 days 03:22:30
Pace                    0:08:08
TotalSeconds            12150.0
HalfSeconds              6417.0
Name: 20205, dtype: object
Metepec, Edo De Mex
 Age                              42
M/F                               M
City            Metepec, Edo De Mex
State                           NaN
Country                         MEX
Half                0 days 01:50:59
40K                 0 days 03:39:37
Pace                        0:08:52
TotalSeconds                13177.0
HalfSeconds                  6659.0
Name: 30825, dtype: object
Metepec, Edo. De Mexico
 Age                                  53
M/F                                   M
City            Metepec, Edo. De Mexico
State                               NaN
Country                             MEX
Half                    0 days 01:43:37
40K                     0 days 03:14:09
Pace                            0:07:46
TotalSeconds                    11649.0
HalfSeconds                      6217.0
Name: 13053, dtype: object
Metepec, Edo. Mex
 Age                            56
M/F                             M
City            Metepec, Edo. Mex
State                         NaN
Country                       MEX
Half              0 days 01:53:10
40K               0 days 03:56:16
Pace                      0:09:35
TotalSeconds              14176.0
HalfSeconds                6790.0
Name: 16262, dtype: object
Metepec, Estado De Mexico
 Age                                    41
M/F                                     M
City            Metepec, Estado De Mexico
State                                 NaN
Country                               MEX
Half                      0 days 01:39:52
40K                       0 days 03:17:05
Pace                              0:07:56
TotalSeconds                      11825.0
HalfSeconds                        5992.0
Name: 6833, dtype: object
Metepec, Estado De México
 Age                                    36
M/F                                     M
City            Metepec, Estado De México
State                                 NaN
Country                               MEX
Half                      0 days 01:33:24
40K                       0 days 03:02:24
Pace                              0:07:21
TotalSeconds                      10944.0
HalfSeconds                        5604.0
Name: 6466, dtype: object
Methuen
 Age                          32
M/F                           M
City                    Methuen
State                        MA
Country                     USA
Half            0 days 01:29:05
40K             0 days 03:03:00
Pace                    0:07:24
TotalSeconds            10980.0
HalfSeconds              5345.0

Miami Beach
 Age                          37
M/F                           M
City                Miami Beach
State                        FL
Country                     USA
Half            0 days 01:13:58
40K             0 days 02:32:35
Pace                    0:06:11
TotalSeconds             9155.0
HalfSeconds              4438.0
Name: 189, dtype: object
Miami Shores
 Age                          45
M/F                           F
City               Miami Shores
State                        FL
Country                     USA
Half            0 days 01:40:55
40K             0 days 03:18:31
Pace                    0:08:00
TotalSeconds            11911.0
HalfSeconds              6055.0
Name: 9333, dtype: object
Michie
 Age                          63
M/F                           M
City                     Michie
State                        TN
Country                     USA
Half            0 days 02:01:13
40K             0 days 04:32:47
Pace                    0:11:01
TotalSeconds            16367.0
HalfSeconds              7273.0
Name: 22766, dtype: object
Middle Sackville
 Age                           32
M/F                            F
City            Middle Sackville
State                         NS
Country                      CAN
Half             0 days 02:23:39
40K              0 days 04:43:16
Pace                     0:11:25
TotalSeconds             16996.0
HalfSeconds               8619.0
Name: 29801, dtype: object
Middleboro
 Age                          39
M/F                           M
City                 Middleboro
State                        MA
Country                     USA
Half            0 days 01:38:26
40K             0 days 03:32:04
Pace                    0:08:51
TotalSeconds            12724.0
HalfSeconds              5906.0
Name: 7160, dtype: object
Middleburg
 Age                          54
M/F                           M
City                 Middleburg
State                        PA
Country                     USA
Half            0 days 02:08:45
40K             0 days 04:34:11
Pace                    0:11:01
TotalSeconds            16451.0
HalfSeconds              7725.0
Name: 13518, dtype: object
Middlebury
 Age                          36
M/F                           M
City                 Middlebury
State                        CT
Country                     USA
Half            0 days 01:21:45
40K             0 days 02:35:42
Pace                    0:06:16
TotalSeconds             9342.0
HalfSeconds              4905.0
Name: 2987, dtype: object
Middlefield
 Age                          29
M/F                           M
City                Middlefield
State                        CT
Country                     USA
Half            0 days 01:25:31
40K             0 days 02:45:06
Pace                    0:06:39
TotalSeconds             9906.0
HalfSeconds              5131.0
Name: 2119, dtype: object
Middleport
 Age                          25
M/F                           F
City                 Middleport
State                        NY
Country                     USA
Half            0 days 01:42:02
40K             0 days 03:26:17
Pace                    0:08:21
TotalSeconds            12377.0
HalfSeconds              6122.0
Name: 16218, dtype: object
Middlesex
 Age                          49
M/F                           M
City                  Middlesex
State                       NaN
Country                     GBR
Half            0 days 01:45:21
40K             0 days 03:34:25
Pace                    0:08:39
TotalSeconds            12865.0
HalfSeconds              6321.0
Name: 31494, dtype: object
Middleton
 Age                          38
M/F                           M
City                  Middleton
State                        NH
Country                     USA
Half            0 days 01:22:36
40K             0 days 02:44:59
Pace                    0:06:40
TotalSeconds             9899.0
HalfSeconds              4956.0
Name: 2060, dtype: object
Middletown
 Age                          27
M/F                           M
City                 Middletown
State                        CT
Country                     USA
Half            0 days 01:16:25
40K             0 days 02:32:44
Pace                    0:06:14
TotalSeconds             9164.0
HalfSeconds              4585.0
Name: 315, dtype: object
Midhurst
 Age                          40
M/F                           F
City                   Midhurst
State                        ON
Country                     CAN
Half            0 days 01:49:30
40K             0 days 03:30:44
Pace                    0:08:29
TotalSeconds            12644.0
HalfSeconds              6570.0
Name: 16278, dtype: object
Midland
 Age                          30
M/F                           M
City                    Midland
State                        MI
Country                     USA
Half            0 days 01:17:20
40K             0 days 02:30:52
Pace                    0:06:06
TotalSeconds             9052.0
HalfSeconds              4640.0
Name: 647, dtype: object
Midland Park
 Age                          54
M/F                           M
City               Midland Park
State                        NJ
Country                     USA
Half            0 days 01:32:45
40K             0 days 03:00:48
Pace                    0:07:19
TotalSeconds            10848.0
HalfSeconds              5565.0
Name: 6883, dtype: object
Midlothian
 Age                          24
M/F                           F
City                 Midlothian
State                        VA
Country                     USA
Half            0 days 01:30:18
40K             0 days 02:51:42
Pace                    0:06:56
TotalSeconds            10302.0
HalfSeconds              5418.0
Name: 5859, dtype: object
Midvale
 Age                          30
M/F                           M
City                    Midvale
State                        UT
Country                     USA
Half            0 days 01:33:03
40K             0 days 03:19:21
Pace                    0:08:06
TotalSeconds            11961.0
HalfSeconds              5583.0
Name: 1815, dtype: object
Midway
 Age                          60
M/F                           M
City                     Midway
State                        UT
Country                     USA
Half            0 days 01:51:28
40K             0 days 03:46:52
Pace                    0:09:12
TotalSeconds            13612.0
HalfSeconds              6688.0
Name: 12574, dtype: object
Midway City
 Age                          29
M/F                           F
City                Midway City
State                        CA
Country                     USA
Half            0 days 01:40:24
40K             0 days 03:12:08
Pace                    0:07:43
TotalSeconds            11528.0
HalfSeconds              6024.0
Name: 15272, dtype: object
Miguel Hidalgo
 Age                          35
M/F                           M
City             Miguel Hidalgo
State                       NaN
Country                     MEX
Half            0 days 01:36:18
40K             0 days 03:38:36
Pace                    0:08:59
TotalSeconds            13116.0
HalfSeconds              5778.0
Name: 5721, dtype: object
Miguel Hidalgo, Distrito Federal
 Age                                           36
M/F                                            M
City            Miguel Hidalgo, Distrito Federal
State                                        NaN
Country                                      MEX
Half                             0 days 01:39:44
40K                              0 days 03:40:23
Pace                                     0:08:53
TotalSeconds                             13223.0
HalfSeconds                               5984.0
Name: 6955, dtype: object
Milan
 Age                          35
M/F                           M
City                      Milan
State                       NaN
Country                     ITA
Half            0 days 01:30:26
40K             0 days 02:59:15
Pace                    0:07:14
TotalSeconds            10755.0
HalfSeconds              5426.0
Name: 4106, dtype: object
Milano
 Age                          41
M/F                           M
City                     Milano
State                       NaN
Country                     ITA
Half            0 days 01:25:55
40K             0 days 02:56:43
Pace                    0:07:12
TotalSeconds            10603.0
HalfSeconds              5155.0
Name: 6872, dtype: object
Mildmay
 Age                          55
M/F                           M
City                    Mildmay
State                        ON
Country                     CAN
Half            0 days 01:46:12
40K             0 days 03:35:14
Pace                    0:08:43
TotalSeconds            12914.0
HalfSeconds              6372.0
Name: 10952, dtype: object
Mildord
 Age                          35
M/F                           M
City                    Mildord
State                        MA
Country                     USA
Half            0 days 01:45:51
40K             0 days 03:45:11
Pace                    0:09:12
TotalSeconds            13511.0
HalfSeconds              6351.0
Name: 28041, dtype: object
Milford
 Age                          37
M/F                           M
City                    Milford
State                        MA
Country                     USA
Half            0 days 01:31:00
40K             0 days 02:58:12
Pace                    0:07:12
TotalSeconds            10692.0
HalfSeconds              5460.0
Name: 6152, dtype: object
Mililani
 Age                          56
M/F                           M
City                   Mililani
State                        HI
Country                     USA
Half            0 days 01:28:50
40K             0 days 02:48:47
Pace                    0:06:48
TotalSeconds            10127.0
HalfSeconds              5330.0
Name: 1926, dtype: object
Mill Creek
 Age                          65
M/F                           M
City                 Mill Creek
State                        WA
Country                     USA
Half            0 days 01:40:21
40K             0 days 03:23:20
Pace                    0:08:14
TotalSeconds            12200.0
HalfSeconds              6021.0

Name: 13695, dtype: object
Mill Valley
 Age                          38
M/F                           M
City                Mill Valley
State                        CA
Country                     USA
Half            0 days 01:12:34
40K             0 days 02:20:27
Pace                    0:05:40
TotalSeconds             8427.0
HalfSeconds              4354.0
Name: 119, dtype: object
Millbrae
 Age                          40
M/F                           F
City                   Millbrae
State                        CA
Country                     USA
Half            0 days 01:56:54
40K             0 days 04:05:48
Pace                    0:10:01
TotalSeconds            14748.0
HalfSeconds              7014.0
Name: 21412, dtype: object
Millbrook
 Age                          60
M/F                           M
City                  Millbrook
State                        NY
Country                     USA
Half            0 days 01:48:21
40K             0 days 03:32:11
Pace                    0:08:35
TotalSeconds            12731.0
HalfSeconds              6501.0
Name: 17271, dtype: object
Millburn
 Age                          47
M/F                           M
City                   Millburn
State                        NJ
Country                     USA
Half            0 days 01:28:24
40K             0 days 02:57:44
Pace                    0:07:11
TotalSeconds            10664.0
HalfSeconds              5304.0
Name: 2126, dtype: object
Millbury
 Age                          37
M/F                           M
City                   Millbury
State                        MA
Country                     USA
Half            0 days 01:28:30
40K             0 days 02:47:49
Pace                    0:06:46
TotalSeconds            10069.0
HalfSeconds              5310.0
Name: 2270, dtype: object
Milledgeville
 Age                          38
M/F                           M
City              Milledgeville
State                        GA
Country                     USA
Half            0 days 01:28:39
40K             0 days 03:12:25
Pace                    0:07:52
TotalSeconds            11545.0
HalfSeconds              5319.0
Name: 1887, dtype: object
Millersburg
 Age                          52
M/F                           F
City                Millersburg
State                        PA
Country                     USA
Half            0 days 01:54:14
40K             0 days 03:45:08
Pace                    0:09:05
TotalSeconds            13508.0
HalfSeconds              6854.0
Name: 22297, dtype: object
Millerstown
 Age                          42
M/F                           F
City                Millerstown
State                        PA
Country                     USA
Half            0 days 02:21:17
40K             0 days 04:49:18
Pace                    0:11:40
TotalSeconds            17358.0
HalfSeconds              8477.0
Name: 29890, dtype: object
Millersville
 Age                          40
M/F                           F
City               Millersville
State                        PA
Country                     USA
Half            0 days 01:47:21
40K             0 days 03:36:45
Pace                    0:08:48
TotalSeconds            13005.0
HalfSeconds              6441.0
Name: 19675, dtype: object
Millington
 Age                          46
M/F                           M
City                 Millington
State                        NJ
Country                     USA
Half            0 days 01:37:56
40K             0 days 03:18:20
Pace                    0:08:02
TotalSeconds            11900.0
HalfSeconds              5876.0
Name: 8493, dtype: object
Millis
 Age                          42
M/F                           M
City                     Millis
State                        MA
Country                     USA
Half            0 days 01:33:53
40K             0 days 03:11:50
Pace                    0:07:47
TotalSeconds            11510.0
HalfSeconds              5633.0
Name: 28064, dtype: object
Milltown
 Age                          55
M/F                           F
City                   Milltown
State                        MT
Country                     USA
Half            0 days 01:53:28
40K             0 days 03:53:58
Pace                    0:09:28
TotalSeconds            14038.0
HalfSeconds              6808.0
Name: 22087, dtype: object
Millville
 Age                          50
M/F                           M
City                  Millville
State                        MA
Country                     USA
Half            0 days 01:37:10
40K             0 days 03:41:16
Pace                    0:09:08
TotalSeconds            13276.0
HalfSeconds              5830.0
Name: 9029, dtype: object
Milpitas
 Age                          32
M/F                           M
City                   Milpitas
State                        CA
Country                     USA
Half            0 days 01:21:48
40K             0 days 02:42:17
Pace                    0:06:34
TotalSeconds             9737.0
HalfSeconds              4908.0
Name: 1032, dtype: object
Milton
 Age                          38
M/F                           M
City                     Milton
State                        MA
Country                     USA
Half            0 days 01:23:55
40K             0 days 02:44:07
Pace                    0:06:38
TotalSeconds             9847.0
HalfSeconds              5035.0
Name: 1553, dtype: object
Milton Highlands
 Age                           70
M/F                            F
City            Milton Highlands
State                         NS
Country                      CAN
Half             0 days 02:31:14
40K              0 days 05:09:38
Pace                     0:12:27
TotalSeconds             18578.0
HalfSeconds               9074.0
Name: 26113, dtype: object
Milton Keynes
 Age                          51
M/F                           M
City              Milton Keynes
State                       NaN
Country                     GBR
Half            0 days 01:37:00
40K             0 days 03:10:37
Pace                    0:07:42
TotalSeconds            11437.0
HalfSeconds              5820.0
Name: 8865, dtype: object
Milwaukee
 Age                          29
M/F                           M
City                  Milwaukee
State                        WI
Country                     USA
Half            0 days 01:18:08
40K             0 days 02:30:24
Pace                    0:06:03
TotalSeconds             9024.0
HalfSeconds              4688.0
Name: 160, dtype: object
Milwaukie
 Age                          31
M/F                           F
City                  Milwaukie
State                        OR
Country                     USA
Half            0 days 02:01:39
40K             0 days 04:35:39
Pace                    0:11:09
TotalSeconds            16539.0
HalfSeconds              7299.0
Name: 14389, dtype: object
Minato-Ku, Tokyo
 Age                           54
M/F                            F
City            Minato-Ku, Tokyo
State                        NaN
Country                      JPN
Half             0 days 01:40:43
40K              0 days 03:25:18
Pace                     0:08:17
TotalSeconds             12318.0
HalfSeconds               6043.0
Name: 16332, dtype: object
Minden
 Age                          29
M/F                           F
City                     Minden
State                        IA
Country                     USA
Half            0 days 01:37:24
40K             0 days 03:11:03
Pace                    0:07:42
TotalSeconds            11463.0
HalfSeconds              5844.0
Name: 12799, dtype: object
Mindoro
 Age                          55
M/F                           M
City                    Mindoro
State                        WI
Country                     USA
Half            0 days 01:49:28
40K             0 days 03:45:36
Pace                    0:09:08
TotalSeconds            13536.0
HalfSeconds              6568.0
Name: 14221, dtype: object
Mineola
 Age                          60
M/F                           M
City                    Mineola
State                        NY
Country                     USA
Half            0 days 01:46:44
40K             0 days 03:32:05
Pace                    0:08:36
TotalSeconds            12725.0
HalfSeconds              6404.0
Name: 18661, dtype: object
Minitonas
 Age                          47
M/F                           M
City                  Minitonas
State                        MB
Country                     CAN
Half            0 days 02:13:20
40K             0 days 04:58:51
Pace                    0:12:09
TotalSeconds            17931.0
HalfSeconds              8000.0
Name: 12529, dtype: object
Minneapolis
 Age                          32
M/F                           M
City                Minneapolis
State                        MN
Country                     USA
Half            0 days 01:15:52
40K             0 days 02:29:54
Pace                    0:06:02
TotalSeconds             8994.0
HalfSeconds              4552.0
Name: 105, dtype: object
Minneola
 Age                          36
M/F                           M
City                   Minneola
State                        FL
Country                     USA
Half            0 days 01:33:29
40K             0 days 03:18:59
Pace                    0:08:04
TotalSeconds            11939.0
HalfSeconds              5609.0
Name: 6884, dtype: object
Minnetonka
 Age                          48
M/F                           M
City                 Minnetonka
State                        MN
Country                     USA
Half            0 days 01:39:29
40K             0 days 03:08:08
Pace                    0:07:35
TotalSeconds            11288.0
HalfSeconds              5969.0
Name: 9627, dtype: object
Minoa
 Age                          35
M/F                           M
City                      Minoa
State                        NY
Country                     USA
Half            0 days 01:32:32
40K             0 days 03:06:30
Pace                    0:07:34
TotalSeconds            11190.0
HalfSeconds              5552.0
Name: 717, dtype: object
Minocqua
 Age                          44
M/F                           M
City                   Minocqua
State                        WI
Country                     USA
Half            0 days 01:42:50
40K             0 days 03:20:01
Pace                    0:08:03
TotalSeconds            12001.0
HalfSeconds              6170.0
Name: 8558, dtype: object
Minot
 Age                          32
M/F                           F
City                      Minot
State                        ND
Country                     USA
Half            0 days 01:28:54
40K             0 days 02:53:45
Pace                    0:07:01
TotalSeconds            10425.0
HalfSeconds              5334.0
Name: 8618, dtype: object
Mint Hill
 Age                          42
M/F                           F
City                  Mint Hill
State                        NC
Country                     USA
Half            0 days 01:51:39
40K             0 days 03:57:05
Pace                    0:09:31
TotalSeconds            14225.0
HalfSeconds              6699.0
Name: 19462, dtype: object
Mira
 Age                          42
M/F                           M
City                       Mira
State                       NaN
Country                     ITA
Half            0 days 01:34:18
40K             0 days 03:08:50
Pace                    0:07:38
TotalSeconds            11330.0
HalfSeconds              5658.0
Name: 5627, dtype: object
Mira Loma
 Age                          36
M/F                           F
City                  Mira Loma
State                        CA
Country                     USA
Half            0 days 01:51:33
40K             0 days 03:54:39
Pace                    0:09:30
TotalSeconds            14079.0
HalfSeconds              6693.0
Name: 19513, dtype: object
Mirabel
 Age                          37
M/F                           F
City                    Mirabel
State                        QC
Country                     CAN
Half            0 days 01:50:16
40K             0 days 03:31:18
Pace                    0:08:30
TotalSeconds            12678.0
HalfSeconds              6616.0
Name: 18885, dtype: object
Miramar Beach
 Age                          39
M/F                           M
City              Miramar Beach
State                        FL
Country                     USA
Half            0 days 01:51:43
40K             0 days 03:40:02
Pace                    0:08:52
TotalSeconds            13202.0
HalfSeconds              6703.0
Name: 27442, dtype: object
Miramichi
 Age                          49
M/F                           F
City                  Miramichi
State                        NB
Country                     CAN
Half            0 days 01:28:59
40K             0 days 02:50:09
Pace                    0:06:51
TotalSeconds            10209.0
HalfSeconds              5339.0
Name: 2375, dtype: object
Miremont
 Age                          51
M/F                           M
City                   Miremont
State                       NaN
Country                     FRA
Half            0 days 01:32:16
40K             0 days 02:58:43
Pace                    0:07:12
TotalSeconds            10723.0
HalfSeconds              5536.0
Name: 5113, dtype: object
Mishawaka
 Age                          40
M/F                           M
City                  Mishawaka
State                        IN
Country                     USA
Half            0 days 01:32:33
40K             0 days 03:03:48
Pace                    0:07:26
TotalSeconds            11028.0
HalfSeconds              5553.0
Name: 3720, dtype: object
Mission
 Age                          29
M/F                           M
City                    Mission
State                        KS
Country                     USA
Half            0 days 01:30:51
40K             0 days 02:52:10
Pace                    0:06:55
TotalSeconds            10330.0
HalfSeconds              5451.0
Name: 4039, dtype: object
Mission Hills
 Age                          52
M/F                           M
City              Mission Hills
State                        KS
Country                     USA
Half            0 days 01:37:11
40K             0 days 03:12:53
Pace                    0:07:51
TotalSeconds            11573.0
HalfSeconds              5831.0
Name: 9724, dtype: object
Mission Viejo
 Age                          31
M/F                           M
City              Mission Viejo
State                        CA
Country                     USA
Half            0 days 01:23:58
40K             0 days 02:43:23
Pace                    0:06:37
TotalSeconds             9803.0
HalfSeconds              5038.0
Name: 1883, dtype: object
Mississauga
 Age                          43
M/F                           M
City                Mississauga
State                        ON
Country                     CAN
Half            0 days 01:20:48
40K             0 days 02:38:01
Pace                    0:06:23
TotalSeconds             9481.0
HalfSeconds              4848.0
Name: 488, dtype: object
Missoula
 Age                          50
M/F                           F
City                   Missoula
State                        MT
Country                     USA
Half            0 days 01:46:41
40K             0 days 03:25:39
Pace                    0:08:18
TotalSeconds            12339.0
HalfSeconds              6401.0
Name: 20620, dtype: object
Missouri City
 Age                          59
M/F                           M
City              Missouri City
State                        TX
Country                     USA
Half            0 days 01:49:30
40K             0 days 03:36:54
Pace                    0:08:47
TotalSeconds            13014.0
HalfSeconds              6570.0
Name: 15507, dtype: object
Mitcham, Victoria
 Age                            35
M/F                             F
City            Mitcham, Victoria
State                         NaN
Country                       AUS
Half              0 days 01:52:16
40K               0 days 03:47:26
Pace                      0:09:12
TotalSeconds              13646.0
HalfSeconds                6736.0
Name: 18407, dtype: object
Mitchell
 Age                          30
M/F                           M
City                   Mitchell
State                        SD
Country                     USA
Half            0 days 01:16:56
40K             0 days 02:49:45
Pace                    0:06:52
TotalSeconds            10185.0
HalfSeconds              4616.0
Name: 202, dtype: object
Moberly
 Age                          45
M/F                           F
City                    Moberly
State                        MO
Country                     USA
Half            0 days 01:40:50
40K             0 days 03:20:49
Pace                    0:08:09
TotalSeconds            12049.0
HalfSeconds              6050.0
Name: 12675, dtype: object
Mobile
 Age                          30
M/F                           M
City                     Mobile
State                        AL
Country                     USA
Half            0 days 01:13:42
40K             0 days 02:26:24
Pace                    0:05:54
TotalSeconds             8784.0
HalfSeconds              4422.0
Name: 142, dtype: object
Modena
 Age                          50
M/F                           M
City                     Modena
State                       NaN
Country                     ITA
Half            0 days 01:26:15
40K             0 days 02:50:41
Pace                    0:06:56
TotalSeconds            10241.0
HalfSeconds              5175.0
Name: 2493, dtype: object
Modesto
 Age                          40
M/F                           M
City                    Modesto
State                        CA
Country                     USA
Half            0 days 01:33:47
40K             0 days 03:12:37
Pace                    0:07:51
TotalSeconds            11557.0
HalfSeconds              5627.0
Name: 7520, dtype: object
Modiin
 Age                          39
M/F                           M
City                     Modiin
State                       NaN
Country                     ISR
Half            0 days 01:31:56
40K             0 days 03:00:45
Pace                    0:07:16
TotalSeconds            10845.0
HalfSeconds              5516.0
Name: 1633, dtype: object
Mogadore
 Age                          42
M/F                           F
City                   Mogadore
State                        OH
Country                     USA
Half            0 days 02:00:25
40K             0 days 04:17:18
Pace                    0:10:18
TotalSeconds            15438.0
HalfSeconds              7225.0
Name: 19872, dtype: object
Mogi Das Cruzes

 Age                          32
M/F                           F
City            Mogi Das Cruzes
State                       NaN
Country                     BRA
Half            0 days 01:35:48
40K             0 days 03:02:02
Pace                    0:07:19
TotalSeconds            10922.0
HalfSeconds              5748.0
Name: 9268, dtype: object
Mogi Das Cruzes, Sp
 Age                              68
M/F                               M
City            Mogi Das Cruzes, Sp
State                           NaN
Country                         BRA
Half                0 days 02:13:07
40K                 0 days 04:24:48
Pace                        0:10:40
TotalSeconds                15888.0
HalfSeconds                  7987.0
Name: 25149, dtype: object
Mohawk
 Age                          55
M/F                           M
City                     Mohawk
State                        NY
Country                     USA
Half            0 days 01:40:56
40K             0 days 03:21:13
Pace                    0:08:07
TotalSeconds            12073.0
HalfSeconds              6056.0
Name: 11091, dtype: object
Mohnton
 Age                          46
M/F                           M
City                    Mohnton
State                        PA
Country                     USA
Half            0 days 01:34:20
40K             0 days 03:14:08
Pace                    0:07:53
TotalSeconds            11648.0
HalfSeconds              5660.0
Name: 10131, dtype: object
Mokena
 Age                          50
M/F                           F
City                     Mokena
State                        IL
Country                     USA
Half            0 days 01:49:28
40K             0 days 03:39:51
Pace                    0:08:52
TotalSeconds            13191.0
HalfSeconds              6568.0
Name: 24464, dtype: object
Moline
 Age                          27
M/F                           F
City                     Moline
State                        IL
Country                     USA
Half            0 days 01:46:55
40K             0 days 03:52:39
Pace                    0:09:28
TotalSeconds            13959.0
HalfSeconds              6415.0
Name: 14213, dtype: object
Moline, Il
 Age                          24
M/F                           F
City                 Moline, Il
State                        IL
Country                     USA
Half            0 days 01:39:52
40K             0 days 03:16:45
Pace                    0:07:57
TotalSeconds            11805.0
HalfSeconds              5992.0
Name: 11130, dtype: object
Molndal
 Age                          43
M/F                           M
City                    Molndal
State                       NaN
Country                     SWE
Half            0 days 01:27:13
40K             0 days 03:09:39
Pace                    0:07:40
TotalSeconds            11379.0
HalfSeconds              5233.0
Name: 4115, dtype: object
Momence
 Age                          35
M/F                           F
City                    Momence
State                        IL
Country                     USA
Half            0 days 02:09:11
40K             0 days 04:13:14
Pace                    0:10:12
TotalSeconds            15194.0
HalfSeconds              7751.0
Name: 20406, dtype: object
Mona
 Age                          37
M/F                           F
City                       Mona
State                        UT
Country                     USA
Half            0 days 01:54:28
40K             0 days 03:44:11
Pace                    0:09:05
TotalSeconds            13451.0
HalfSeconds              6868.0
Name: 16824, dtype: object
Monclova
 Age                          41
M/F                           M
City                   Monclova
State                       NaN
Country                     MEX
Half            0 days 01:28:13
40K             0 days 03:03:23
Pace                    0:07:26
TotalSeconds            11003.0
HalfSeconds              5293.0
Name: 1743, dtype: object
Moncton
 Age                          43
M/F                           M
City                    Moncton
State                        NB
Country                     CAN
Half            0 days 01:23:03
40K             0 days 02:40:03
Pace                    0:06:28
TotalSeconds             9603.0
HalfSeconds              4983.0
Name: 2967, dtype: object
Monkton
 Age                          27
M/F                           F
City                    Monkton
State                        MD
Country                     USA
Half            0 days 01:42:34
40K             0 days 03:26:57
Pace                    0:08:24
TotalSeconds            12417.0
HalfSeconds              6154.0
Name: 10253, dtype: object
Monmouth
 Age                          27
M/F                           F
City                   Monmouth
State                        IL
Country                     USA
Half            0 days 01:39:32
40K             0 days 03:09:42
Pace                    0:07:37
TotalSeconds            11382.0
HalfSeconds              5972.0
Name: 13316, dtype: object
Monmouth Jct
 Age                          62
M/F                           M
City               Monmouth Jct
State                        NJ
Country                     USA
Half            0 days 01:53:58
40K             0 days 03:42:02
Pace                    0:08:58
TotalSeconds            13322.0
HalfSeconds              6838.0
Name: 24201, dtype: object
Monmouth Junction
 Age                            45
M/F                             M
City            Monmouth Junction
State                          NJ
Country                       USA
Half              0 days 01:51:13
40K               0 days 03:48:45
Pace                      0:09:13
TotalSeconds              13725.0
HalfSeconds                6673.0
Name: 10712, dtype: object
Mono
 Age                          63
M/F                           M
City                       Mono
State                        ON
Country                     CAN
Half            0 days 01:47:34
40K             0 days 03:34:14
Pace                    0:08:41
TotalSeconds            12854.0
HalfSeconds              6454.0
Name: 19108, dtype: object
Monroe
 Age                          45
M/F                           M
City                     Monroe
State                        NC
Country                     USA
Half            0 days 01:27:38
40K             0 days 02:47:08
Pace                    0:06:43
TotalSeconds            10028.0
HalfSeconds              5258.0
Name: 3163, dtype: object
Monroe Center
 Age                          53
M/F                           M
City              Monroe Center
State                        IL
Country                     USA
Half            0 days 01:34:07
40K             0 days 03:07:21
Pace                    0:07:35
TotalSeconds            11241.0
HalfSeconds              5647.0
Name: 12125, dtype: object
Monroe Falls
 Age                          26
M/F                           F
City               Monroe Falls
State                        OH
Country                     USA
Half            0 days 01:49:18
40K             0 days 03:38:30
Pace                    0:08:50
TotalSeconds            13110.0
HalfSeconds              6558.0
Name: 12824, dtype: object
Monroe Township
 Age                          25
M/F                           M
City            Monroe Township
State                        NJ
Country                     USA
Half            0 days 01:28:19
40K             0 days 02:50:04
Pace                    0:06:53
TotalSeconds            10204.0
HalfSeconds              5299.0
Name: 3683, dtype: object
Monroeville
 Age                          53
M/F                           F
City                Monroeville
State                        PA
Country                     USA
Half            0 days 02:00:48
40K             0 days 03:59:38
Pace                    0:09:47
TotalSeconds            14378.0
HalfSeconds              7248.0
Name: 23248, dtype: object
Monrovia
 Age                          43
M/F                           F
City                   Monrovia
State                        CA
Country                     USA
Half            0 days 01:40:45
40K             0 days 03:17:36
Pace                    0:07:58
TotalSeconds            11856.0
HalfSeconds              6045.0
Name: 14292, dtype: object
Monson
 Age                          50
M/F                           F
City                     Monson
State                        MA
Country                     USA
Half            0 days 01:43:46
40K             0 days 03:20:01
Pace                    0:08:03
TotalSeconds            12001.0
HalfSeconds              6226.0

Name: 18108, dtype: object
Mont Belvieu
 Age                          38
M/F                           F
City               Mont Belvieu
State                        TX
Country                     USA
Half            0 days 01:42:00
40K             0 days 03:17:30
Pace                    0:07:59
TotalSeconds            11850.0
HalfSeconds              6120.0
Name: 16231, dtype: object
Mont St-Gregoire
 Age                           51
M/F                            M
City            Mont St-Gregoire
State                         QC
Country                      CAN
Half             0 days 01:44:42
40K              0 days 03:23:19
Pace                     0:08:13
TotalSeconds             12199.0
HalfSeconds               6282.0
Name: 10828, dtype: object
Mont St-Hilaire
 Age                          35
M/F                           F
City            Mont St-Hilaire
State                        QC
Country                     CAN
Half            0 days 01:43:11
40K             0 days 03:30:10
Pace                    0:08:31
TotalSeconds            12610.0
HalfSeconds              6191.0
Name: 19809, dtype: object
Mont Vernon
 Age                          44
M/F                           F
City                Mont Vernon
State                        NH
Country                     USA
Half            0 days 01:41:27
40K             0 days 03:14:02
Pace                    0:07:49
TotalSeconds            11642.0
HalfSeconds              6087.0
Name: 11799, dtype: object
Mont-Joli
 Age                          48
M/F                           M
City                  Mont-Joli
State                        QC
Country                     CAN
Half            0 days 01:43:21
40K             0 days 03:22:53
Pace                    0:08:14
TotalSeconds            12173.0
HalfSeconds              6201.0
Name: 11280, dtype: object
Mont-Laurier
 Age                          51
M/F                           F
City               Mont-Laurier
State                        QC
Country                     CAN
Half            0 days 02:00:38
40K             0 days 03:56:35
Pace                    0:09:31
TotalSeconds            14195.0
HalfSeconds              7238.0
Name: 24924, dtype: object
Mont-Royal
 Age                          41
M/F                           F
City                 Mont-Royal
State                        QC
Country                     CAN
Half            0 days 01:38:55
40K             0 days 03:09:16
Pace                    0:07:38
TotalSeconds            11356.0
HalfSeconds              5935.0
Name: 11216, dtype: object
Mont-Saint-Hilaire
 Age                             36
M/F                              M
City            Mont-Saint-Hilaire
State                           QC
Country                        CAN
Half               0 days 01:28:32
40K                0 days 02:50:07
Pace                       0:06:51
TotalSeconds               10207.0
HalfSeconds                 5312.0
Name: 4564, dtype: object
Montague
 Age                          43
M/F                           F
City                   Montague
State                        PE
Country                     CAN
Half            0 days 01:47:00
40K             0 days 03:24:22
Pace                    0:08:12
TotalSeconds            12262.0
HalfSeconds              6420.0
Name: 17005, dtype: object
Montclair
 Age                          34
M/F                           M
City                  Montclair
State                        NJ
Country                     USA
Half            0 days 01:19:57
40K             0 days 02:45:24
Pace                    0:06:56
TotalSeconds             9924.0
HalfSeconds              4797.0
Name: 554, dtype: object
Montebello
 Age                          26
M/F                           M
City                 Montebello
State                        CA
Country                     USA
Half            0 days 01:21:35
40K             0 days 02:41:14
Pace                    0:06:31
TotalSeconds             9674.0
HalfSeconds              4895.0
Name: 1328, dtype: object
Monterey
 Age                          49
M/F                           M
City                   Monterey
State                        CA
Country                     USA
Half            0 days 01:34:02
40K             0 days 03:03:15
Pace                    0:07:25
TotalSeconds            10995.0
HalfSeconds              5642.0
Name: 6406, dtype: object
Monterey Park
 Age                          45
M/F                           M
City              Monterey Park
State                        CA
Country                     USA
Half            0 days 01:36:13
40K             0 days 03:07:21
Pace                    0:07:33
TotalSeconds            11241.0
HalfSeconds              5773.0
Name: 11404, dtype: object
Monterrey
 Age                          52
M/F                           M
City                  Monterrey
State                       NaN
Country                     MEX
Half            0 days 01:21:19
40K             0 days 02:36:58
Pace                    0:06:20
TotalSeconds             9418.0
HalfSeconds              4879.0
Name: 693, dtype: object
Monterrey, N.l.
 Age                          47
M/F                           M
City            Monterrey, N.l.
State                       NaN
Country                     MEX
Half            0 days 01:31:11
40K             0 days 03:03:31
Pace                    0:07:26
TotalSeconds            11011.0
HalfSeconds              5471.0
Name: 10949, dtype: object
Monterrey, Nl
 Age                          47
M/F                           F
City              Monterrey, Nl
State                       NaN
Country                     MEX
Half            0 days 01:50:31
40K             0 days 03:34:26
Pace                    0:08:39
TotalSeconds            12866.0
HalfSeconds              6631.0
Name: 21518, dtype: object
Monterrey, Nuevo Leon
 Age                                51
M/F                                 M
City            Monterrey, Nuevo Leon
State                             NaN
Country                           MEX
Half                  0 days 02:00:43
40K                   0 days 04:14:37
Pace                          0:10:19
TotalSeconds                  15277.0
HalfSeconds                    7243.0
Name: 13449, dtype: object
Montevideo
 Age                          39
M/F                           M
City                 Montevideo
State                       NaN
Country                     URU
Half            0 days 01:23:54
40K             0 days 02:42:44
Pace                    0:06:35
TotalSeconds             9764.0
HalfSeconds              5034.0
Name: 2694, dtype: object
Montgomery
 Age                          43
M/F                           M
City                 Montgomery
State                        TX
Country                     USA
Half            0 days 01:22:23
40K             0 days 02:41:33
Pace                    0:06:34
TotalSeconds             9693.0
HalfSeconds              4943.0
Name: 2266, dtype: object
Montgomery Village
 Age                             24
M/F                              F
City            Montgomery Village
State                           MD
Country                        USA
Half               0 days 01:30:40
40K                0 days 02:50:10
Pace                       0:06:50
TotalSeconds               10210.0
HalfSeconds                 5440.0
Name: 5383, dtype: object
Monticello
 Age                          43
M/F                           M
City                 Monticello
State                        IL
Country                     USA
Half            0 days 01:37:25
40K             0 days 03:14:40
Pace                    0:07:52
TotalSeconds            11680.0
HalfSeconds              5845.0
Name: 6357, dtype: object
Montmagny
 Age                          48
M/F                           M
City                  Montmagny
State                        QC
Country                     CAN
Half            0 days 01:37:12
40K             0 days 03:06:39
Pace                    0:07:31
TotalSeconds            11199.0
HalfSeconds              5832.0
Name: 9805, dtype: object
Montpelier
 Age                          36
M/F                           F
City                 Montpelier
State                        VT
Country                     USA
Half            0 days 01:35:51
40K             0 days 03:05:24
Pace                    0:07:28
TotalSeconds            11124.0
HalfSeconds              5751.0
Name: 7082, dtype: object
Montpellier
 Age                          55
M/F                           M
City                Montpellier
State                       NaN
Country                     FRA
Half            0 days 01:43:13
40K             0 days 03:20:13
Pace                    0:08:05
TotalSeconds            12013.0
HalfSeconds              6193.0
Name: 14360, dtype: object
Montreal
 Age                          32
M/F                           M
City                   Montreal
State                        QC
Country                     CAN
Half            0 days 01:14:53
40K             0 days 02:34:31
Pace                    0:06:17
TotalSeconds             9271.0
HalfSeconds              4493.0
Name: 148, dtype: object
Montreal West
 Age                          51
M/F                           F
City              Montreal West
State                        QC
Country                     CAN
Half            0 days 02:02:53
40K             0 days 04:20:52
Pace                    0:10:33
TotalSeconds            15652.0
HalfSeconds              7373.0
Name: 21398, dtype: object
Montreal-Est
 Age                          55
M/F                           M
City               Montreal-Est
State                        QC
Country                     CAN
Half            0 days 01:47:00
40K             0 days 03:29:07
Pace                    0:08:25
TotalSeconds            12547.0
HalfSeconds              6420.0
Name: 13190, dtype: object
Montrose
 Age                          36
M/F                           M
City                   Montrose
State                        NY
Country                     USA
Half            0 days 01:29:41
40K             0 days 02:52:34
Pace                    0:06:59
TotalSeconds            10354.0
HalfSeconds              5381.0
Name: 3498, dtype: object
Montréal
 Age                          36
M/F                           M
City                   Montréal
State                        QC
Country                     CAN
Half            0 days 01:28:06
40K             0 days 02:52:02
Pace                    0:06:57
TotalSeconds            10322.0
HalfSeconds              5286.0
Name: 4136, dtype: object
Montville
 Age                          29
M/F                           F
City                  Montville
State                        NJ
Country                     USA
Half            0 days 01:48:54
40K             0 days 03:42:21
Pace                    0:08:57
TotalSeconds            13341.0
HalfSeconds              6534.0
Name: 17023, dtype: object
Monument
 Age                          46
M/F                           M
City                   Monument
State                        CO
Country                     USA
Half            0 days 01:27:00
40K             0 days 02:52:32
Pace                    0:07:00
TotalSeconds            10352.0
HalfSeconds              5220.0
Name: 715, dtype: object
Monza
 Age                          41
M/F                           M
City                      Monza
State                       NaN
Country                     ITA
Half            0 days 02:00:02
40K             0 days 04:53:01
Pace                    0:12:02
TotalSeconds            17581.0
HalfSeconds              7202.0
Name: 31449, dtype: object
Moon Township
 Age                          37
M/F                           M
City              Moon Township
State                        PA
Country                     USA
Half            0 days 01:27:09
40K             0 days 02:56:29
Pace                    0:07:11
TotalSeconds            10589.0
HalfSeconds              5229.0
Name: 4419, dtype: object
Moore
 Age                          32
M/F                           M
City                      Moore
State                        OK
Country                     USA
Half            0 days 01:24:03
40K             0 days 02:51:55
Pace                    0:07:00
TotalSeconds            10315.0
HalfSeconds              5043.0
Name: 2047, dtype: object
Moorestown
 Age                          58
M/F                           M
City                 Moorestown
State                        NJ
Country                     USA
Half            0 days 01:27:32
40K             0 days 02:49:43
Pace                    0:06:52
TotalSeconds            10183.0
HalfSeconds              5252.0
Name: 2841, dtype: object
Mooresville
 Age                          45
M/F                           M
City                Mooresville
State                        NC
Country                     USA
Half            0 days 01:38:11
40K             0 days 03:29:48
Pace                    0:08:26
TotalSeconds            12588.0
HalfSeconds              5891.0
Name: 6887, dtype: object
Moorhead
 Age                          26
M/F                           M
City                   Moorhead
State                        MN
Country                     USA
Half            0 days 01:14:17
40K             0 days 02:28:14
Pace                    0:06:00
TotalSeconds             8894.0
HalfSeconds              4457.0
Name: 133, dtype: object
Moorpark
 Age                          40
M/F                           M
City                   Moorpark
State                        CA
Country                     USA
Half            0 days 01:33:11
40K             0 days 03:02:43
Pace                    0:07:26
TotalSeconds            10963.0
HalfSeconds              5591.0
Name: 8241, dtype: object
Moose Jaw
 Age                          58
M/F                           F
City                  Moose Jaw
State                        SK
Country                     CAN
Half            0 days 02:03:41
40K             0 days 04:00:05
Pace                    0:09:41
TotalSeconds            14405.0
HalfSeconds              7421.0
Name: 25285, dtype: object
Moose Pass
 Age                          57
M/F                           M
City                 Moose Pass
State                        AK
Country                     USA
Half            0 days 01:42:38
40K             0 days 03:28:15
Pace                    0:08:34
TotalSeconds            12495.0
HalfSeconds              6158.0
Name: 15483, dtype: object
Morbio Inferiore
 Age                           51
M/F                            M
City            Morbio Inferiore
State                        NaN
Country                      SUI
Half             0 days 01:39:01
40K              0 days 00:00:00
Pace                     0:11:27
TotalSeconds                 0.0
HalfSeconds               5941.0
Name: 11696, dtype: object
Moreland Hills
 Age                          42
M/F                           M
City             Moreland Hills
State                        OH
Country                     USA
Half            0 days 01:36:36
40K             0 days 03:15:37
Pace                    0:07:58
TotalSeconds            11737.0
HalfSeconds              5796.0
Name: 8719, dtype: object
Morelia
 Age                          45
M/F                           F
City                    Morelia
State                       NaN
Country                     MEX
Half            0 days 01:47:17
40K             0 days 03:29:55
Pace                    0:08:31
TotalSeconds            12595.0
HalfSeconds              6437.0
Name: 22241, dtype: object
Morelia, Michoacan
 Age                             66
M/F                              M
City            Morelia, Michoacan
State                          NaN
Country                        MEX
Half               0 days 01:59:07
40K                0 days 03:47:35
Pace                       0:09:09
TotalSeconds               13655.0
HalfSeconds                 7147.0
Name: 23045, dtype: object
Moreno Valley
 Age                          55
M/F                           M
City              Moreno Valley
State                        CA
Country                     USA
Half            0 days 01:46:47
40K             0 days 03:32:54
Pace                    0:08:39
TotalSeconds            12774.0
HalfSeconds              6407.0
Name: 16296, dtype: object
Moretown
 Age                          40
M/F                           F
City                   Moretown
State                        VT
Country                     USA
Half            0 days 01:36:01
40K             0 days 03:10:01
Pace                    0:07:43
TotalSeconds            11401.0
HalfSeconds              5761.0
Name: 10287, dtype: object
Morgan Hill
 Age                          40
M/F                           M
City                Morgan Hill
State                        CA
Country                     USA
Half            0 days 01:34:52
40K             0 days 03:10:36
Pace                    0:07:44
TotalSeconds            11436.0
HalfSeconds              5692.0
Name: 6071, dtype: object
Morgantown
 Age                          26
M/F                           F
City                 Morgantown
State                        WV
Country                     USA
Half            0 days 01:31:16
40K             0 days 03:01:15
Pace                    0:07:18
TotalSeconds            10875.0
HalfSeconds              5476.0
Name: 1953, dtype: object
Morganville
 Age                          56
M/F                           F
City                Morganville
State                        NJ
Country                     USA
Half            0 days 02:05:42
40K             0 days 04:02:31
Pace                    0:09:46
TotalSeconds            14551.0
HalfSeconds              7542.0
Name: 25459, dtype: object
Morges
 Age                          24
M/F                           M
City                     Morges
State                       NaN
Country                     SUI
Half            0 days 01:28:27
40K             0 days 03:40:36
Pace                    0:09:06
TotalSeconds            13236.0
HalfSeconds              5307.0
Name: 31594, dtype: object
Morin Heights
 Age                          40
M/F                           F
City              Morin Heights
State                        QC
Country                     CAN
Half            0 days 02:15:38
40K             0 days 04:26:55
Pace                    0:10:44
TotalSeconds            16015.0
HalfSeconds              8138.0
Name: 28504, dtype: object
Morin-Heights
 Age                          39
M/F                           M
City              Morin-Heights
State                        QC
Country                     CAN
Half            0 days 01:32:31
40K             0 days 02:59:09
Pace                    0:07:14
TotalSeconds            10749.0
HalfSeconds              5551.0
Name: 5878, dtype: object
Mornington
 Age                          40
M/F                           F
City                 Mornington
State                       NaN
Country                     AUS
Half            0 days 01:46:24
40K             0 days 03:27:43
Pace                    0:08:23
TotalSeconds            12463.0
HalfSeconds              6384.0
Name: 16555, dtype: object
Moroleon
 Age                          49
M/F                           M
City                   Moroleon
State                       NaN
Country                     MEX
Half            0 days 01:39:55
40K             0 days 03:58:25
Pace                    0:09:44
TotalSeconds            14305.0
HalfSeconds              5995.0
Name: 9121, dtype: object
Morpeth
 Age                          54
M/F                           M
City                    Morpeth
State                       NaN
Country                     GBR
Half            0 days 01:40:14
40K             0 days 03:16:39
Pace                    0:07:57
TotalSeconds            11799.0
HalfSeconds              6014.0
Name: 14823, dtype: object
Morris
 Age                          45

 Age                          63
M/F                           M
City                   Morrison
State                        CO
Country                     USA
Half            0 days 01:55:44
40K             0 days 03:48:00
Pace                    0:09:14
TotalSeconds            13680.0
HalfSeconds              6944.0
Name: 21695, dtype: object
Morristown
 Age                          52
M/F                           M
City                 Morristown
State                        NJ
Country                     USA
Half            0 days 01:30:28
40K             0 days 02:58:03
Pace                    0:07:12
TotalSeconds            10683.0
HalfSeconds              5428.0
Name: 3316, dtype: object
Morrisville
 Age                          37
M/F                           M
City                Morrisville
State                        PA
Country                     USA
Half            0 days 01:32:18
40K             0 days 03:02:29
Pace                    0:07:24
TotalSeconds            10949.0
HalfSeconds              5538.0
Name: 6403, dtype: object
Morro Bay
 Age                          53
M/F                           M
City                  Morro Bay
State                        CA
Country                     USA
Half            0 days 01:43:48
40K             0 days 03:21:31
Pace                    0:08:15
TotalSeconds            12091.0
HalfSeconds              6228.0
Name: 13796, dtype: object
Morrow
 Age                          36
M/F                           F
City                     Morrow
State                        OH
Country                     USA
Half            0 days 01:33:46
40K             0 days 03:05:26
Pace                    0:07:30
TotalSeconds            11126.0
HalfSeconds              5626.0
Name: 8167, dtype: object
Morteros
 Age                          47
M/F                           M
City                   Morteros
State                       NaN
Country                     ARG
Half            0 days 01:39:09
40K             0 days 03:12:54
Pace                    0:07:46
TotalSeconds            11574.0
HalfSeconds              5949.0
Name: 10801, dtype: object
Mortimer West End
 Age                            43
M/F                             M
City            Mortimer West End
State                         NaN
Country                       GBR
Half              0 days 01:41:48
40K               0 days 04:15:34
Pace                      0:10:26
TotalSeconds              15334.0
HalfSeconds                6108.0
Name: 8077, dtype: object
Moscow
 Age                          35
M/F                           M
City                     Moscow
State                       NaN
Country                     RUS
Half            0 days 01:21:57
40K             0 days 02:41:27
Pace                    0:06:33
TotalSeconds             9687.0
HalfSeconds              4917.0
Name: 992, dtype: object
Moscow, Zelenograd
 Age                             33
M/F                              M
City            Moscow, Zelenograd
State                          NaN
Country                        RUS
Half               0 days 01:19:52
40K                0 days 02:40:54
Pace                       0:06:31
TotalSeconds                9654.0
HalfSeconds                 4792.0
Name: 654, dtype: object
Moseley
 Age                          48
M/F                           M
City                    Moseley
State                        VA
Country                     USA
Half            0 days 01:48:23
40K             0 days 03:45:21
Pace                    0:09:08
TotalSeconds            13521.0
HalfSeconds              6503.0
Name: 9244, dtype: object
Mosinee
 Age                          23
M/F                           M
City                    Mosinee
State                        WI
Country                     USA
Half            0 days 01:20:08
40K             0 days 02:45:01
Pace                    0:06:42
TotalSeconds             9901.0
HalfSeconds              4808.0
Name: 1111, dtype: object
Mosman
 Age                          39
M/F                           F
City                     Mosman
State                       NaN
Country                     AUS
Half            0 days 01:47:54
40K             0 days 03:41:23
Pace                    0:08:55
TotalSeconds            13283.0
HalfSeconds              6474.0
Name: 12108, dtype: object
Motherwell
 Age                          41
M/F                           M
City                 Motherwell
State                       NaN
Country                     GBR
Half            0 days 01:26:17
40K             0 days 02:56:40
Pace                    0:07:12
TotalSeconds            10600.0
HalfSeconds              5177.0
Name: 1369, dtype: object
Mottville
 Age                          35
M/F                           F
City                  Mottville
State                        MI
Country                     USA
Half            0 days 02:04:16
40K             0 days 04:03:05
Pace                    0:09:46
TotalSeconds            14585.0
HalfSeconds              7456.0
Name: 19597, dtype: object
Moulineaux
 Age                          47
M/F                           M
City                 Moulineaux
State                       NaN
Country                     FRA
Half            0 days 01:40:16
40K             0 days 03:36:20
Pace                    0:08:42
TotalSeconds            12980.0
HalfSeconds              6016.0
Name: 1186, dtype: object
Mount Airy
 Age                          46
M/F                           M
City                 Mount Airy
State                        NC
Country                     USA
Half            0 days 01:35:42
40K             0 days 03:06:51
Pace                    0:07:31
TotalSeconds            11211.0
HalfSeconds              5742.0
Name: 9883, dtype: object
Mount Arlington
 Age                          41
M/F                           F
City            Mount Arlington
State                        NJ
Country                     USA
Half            0 days 01:51:00
40K             0 days 03:35:15
Pace                    0:08:42
TotalSeconds            12915.0
HalfSeconds              6660.0
Name: 18762, dtype: object
Mount Carmel
 Age                          41
M/F                           M
City               Mount Carmel
State                        IL
Country                     USA
Half            0 days 01:29:52
40K             0 days 03:00:49
Pace                    0:07:24
TotalSeconds            10849.0
HalfSeconds              5392.0
Name: 4929, dtype: object
Mount Hawthorn
 Age                          37
M/F                           F
City             Mount Hawthorn
State                       NaN
Country                     AUS
Half            0 days 01:41:58
40K             0 days 03:23:30
Pace                    0:08:16
TotalSeconds            12210.0
HalfSeconds              6118.0
Name: 15076, dtype: object
Mount Holly Springs
 Age                              31
M/F                               F
City            Mount Holly Springs
State                            PA
Country                         USA
Half                0 days 01:38:59
40K                 0 days 03:34:34
Pace                        0:08:42
TotalSeconds                12874.0
HalfSeconds                  5939.0
Name: 5197, dtype: object
Mount Horeb
 Age                          37
M/F                           F
City                Mount Horeb
State                        WI
Country                     USA
Half            0 days 01:45:58
40K             0 days 03:24:15
Pace                    0:08:15
TotalSeconds            12255.0
HalfSeconds              6358.0
Name: 17139, dtype: object
Mount Joy
 Age                          39
M/F                           F
City                  Mount Joy
State                        PA
Country                     USA
Half            0 days 01:52:24
40K             0 days 03:39:33
Pace                    0:08:50
TotalSeconds            13173.0
HalfSeconds              6744.0
Name: 15009, dtype: object
Mount Juliet
 Age                          36
M/F                           F
City               Mount Juliet
State                        TN
Country                     USA
Half            0 days 01:54:54
40K             0 days 03:50:54
Pace                    0:09:19
TotalSeconds            13854.0
HalfSeconds              6894.0
Name: 18918, dtype: object
Mount Kisco
 Age                          43
M/F                           M
City                Mount Kisco
State                        NY
Country                     USA
Half            0 days 01:31:01
40K             0 days 02:51:37
Pace                    0:06:54
TotalSeconds            10297.0
HalfSeconds              5461.0
Name: 4815, dtype: object
Mount Laurel
 Age                          51
M/F                           F
City               Mount Laurel
State                        NJ
Country                     USA
Half            0 days 02:15:39
40K             0 days 04:37:44
Pace                    0:11:13
TotalSeconds            16664.0
HalfSeconds              8139.0
Name: 24719, dtype: object
Mount Lofty
 Age                          40
M/F                           M
City                Mount Lofty
State                       NaN
Country                     AUS
Half            0 days 01:30:42
40K             0 days 03:00:44
Pace                    0:07:20
TotalSeconds            10844.0
HalfSeconds              5442.0
Name: 5877, dtype: object
Mount Pearl
 Age                          50
M/F                           M
City                Mount Pearl
State                        NL
Country                     CAN
Half            0 days 01:35:48
40K             0 days 03:06:38
Pace                    0:07:33
TotalSeconds            11198.0
HalfSeconds              5748.0
Name: 10099, dtype: object
Mount Pleasant
 Age                          28
M/F                           F
City             Mount Pleasant
State                        SC
Country                     USA
Half            0 days 01:41:27
40K             0 days 03:13:53
Pace                    0:07:49
TotalSeconds            11633.0
HalfSeconds              6087.0
Name: 13045, dtype: object
Mount Royal
 Age                          49
M/F                           M
City                Mount Royal
State                        QC
Country                     CAN
Half            0 days 01:32:37
40K             0 days 02:57:29
Pace                    0:07:09
TotalSeconds            10649.0
HalfSeconds              5557.0
Name: 6647, dtype: object
Mount Sinai
 Age                          51
M/F                           F
City                Mount Sinai
State                        NY
Country                     USA
Half            0 days 01:45:49
40K             0 days 03:30:01
Pace                    0:08:29
TotalSeconds            12601.0
HalfSeconds              6349.0
Name: 21984, dtype: object
Mount Sterling
 Age                          57
M/F                           F
City             Mount Sterling
State                        KY
Country                     USA
Half            0 days 01:53:08
40K             0 days 03:50:42
Pace                    0:09:25
TotalSeconds            13842.0
HalfSeconds              6788.0
Name: 22791, dtype: object
Mount Uniacke
 Age                          50
M/F                           M
City              Mount Uniacke
State                        NS
Country                     CAN
Half            0 days 01:44:28
40K             0 days 03:33:30
Pace                    0:08:37
TotalSeconds            12810.0
HalfSeconds              6268.0
Name: 12807, dtype: object
Mount Vernon
 Age                          35
M/F                           M
City               Mount Vernon
State                        NY
Country                     USA
Half            0 days 01:17:46
40K             0 days 02:38:26
Pace                    0:06:26
TotalSeconds             9506.0
HalfSeconds              4666.0
Name: 281, dtype: object
Mount Zion
 Age                          58
M/F                           M
City                 Mount Zion
State                        IL
Country                     USA
Half            0 days 01:46:55
40K             0 days 03:28:03
Pace                    0:08:22
TotalSeconds            12483.0
HalfSeconds              6415.0
Name: 19556, dtype: object
Mountain Brook
 Age                          68
M/F                           M
City             Mountain Brook
State                        AL
Country                     USA
Half            0 days 02:00:41
40K             0 days 04:01:35
Pace                    0:09:44
TotalSeconds            14495.0
HalfSeconds              7241.0
Name: 25502, dtype: object
Mountain Home
 Age                          37
M/F                           F
City              Mountain Home
State                        AR
Country                     USA
Half            0 days 01:50:26
40K             0 days 03:39:02
Pace                    0:08:51
TotalSeconds            13142.0
HalfSeconds              6626.0
Name: 19546, dtype: object
Mountain House
 Age                          37
M/F                           F
City             Mountain House
State                        CA
Country                     USA
Half            0 days 01:41:55
40K             0 days 03:14:21
Pace                    0:07:49
TotalSeconds            11661.0
HalfSeconds              6115.0
Name: 13385, dtype: object
Mountain Lake
 Age                          61
M/F                           M
City              Mountain Lake
State                        MN
Country                     USA
Half            0 days 02:00:17
40K             0 days 04:00:49
Pace                    0:09:44
TotalSeconds            14449.0
HalfSeconds              7217.0
Name: 23343, dtype: object
Mountain Lakes
 Age                          41
M/F                           F
City             Mountain Lakes
State                        NJ
Country                     USA
Half            0 days 01:46:44
40K             0 days 03:25:04
Pace                    0:08:16
TotalSeconds            12304.0
HalfSeconds              6404.0
Name: 17683, dtype: object
Mountain Top
 Age                          57
M/F                           M
City               Mountain Top
State                        PA
Country                     USA
Half            0 days 01:38:38
40K             0 days 03:16:47
Pace                    0:07:58
TotalSeconds            11807.0
HalfSeconds              5918.0
Name: 9261, dtype: object
Mountain View
 Age                          45
M/F                           M
City              Mountain View
State                        CA
Country                     USA
Half            0 days 01:28:20
40K             0 days 02:57:54
Pace                    0:07:11
TotalSeconds            10674.0
HalfSeconds              5300.0
Name: 1051, dtype: object
Mountainhome
 Age                          62
M/F                           F
City               Mountainhome
State                        PA
Country                     USA
Half            0 days 02:19:34
40K             0 days 04:56:23
Pace                    0:11:59
TotalSeconds            17783.0
HalfSeconds              8374.0
Name: 25883, dtype: object
Mountville
 Age                          47
M/F                           M
City                 Mountville
State                        PA
Country                     USA
Half            0 days 01:26:05
40K             0 days 02:51:04
Pace                    0:06:54
TotalSeconds            10264.0
HalfSeconds              5165.0
Name: 3043, dtype: object
Mouth Of Wilson
 Age                          25
M/F                           M
City            Mouth Of Wilson
State                        VA
Country                     USA
Half            0 days 02:14:46
40K             0 days 04:17:37
Pace                    0:10:20
TotalSeconds            15457.0
HalfSeconds              8086.0
Name: 30750, dtype: object
Moyers
 Age                          59
M/F                           M
City                     Moyers
State                        OK
Country                     USA
Half            0 days 01:39:17
40K             0 days 03:19:02
Pace                    0:08:04
TotalSeconds            11942.0
HalfSeconds              5957.0
Name: 16532, dtype: object
Mpls
 Age                          35
M/F                           F
City                       Mpls
State                        MN
Country                     USA
Half            0 days 01:45:49
40K             0 days 03:26:34
Pace                    0:08:19
TotalSeconds            12394.0
HalfSeconds              6349.0
Name: 14881, dtype: object
Mt Baldy
 Age                          57
M/F                           M
City                   Mt Baldy
State                        CA
Country                     USA
Half            0 days 01:41:50
40K             0 days 03:32:29
Pace                    0:08:38
TotalSeconds            12749.0
HalfSeconds              6110.0
Name: 11067, dtype: object
Mt Pleasant
 Age                          43
M/F                           M
City                Mt Pleasant
State                        SC
Country                     USA
Half            0 days 01:37:10
40K             0 days 03:12:49
Pace                    0:07:48
TotalSeconds            11569.0
HalfSeconds              5830.0
Name: 5657, dtype: object
Mt St Hilaire
 Age                          59
M/F                           M
City              Mt St Hilaire
State                        QC
Country                     CAN
Half            0 days 01:51:14
40K             0 days 03:50:30
Pace                    0:09:18
TotalSeconds            13830.0
HalfSeconds              6674.0
Name: 28876, dtype: object
Mt. Holly Springs
 Age                            32
M/F                             M
City            Mt. Holly Springs
State                          PA
Country                       USA
Half              0 days 01:13:46
40K               0 days 02:40:10
Pace                      0:06:31
TotalSeconds               9610.0
HalfSeconds                4426.0
Name: 37, dtype: object
Mt. Pleasant
 Age                          24
M/F                           M
City               Mt. Pleasant
State                        MI
Country                     USA
Half            0 days 01:26:22
40K             0 days 03:24:19
Pace                    0:08:28
TotalSeconds            12259.0
HalfSeconds              5182.0
Name: 3676, dtype: object
Mt. Tabor
 Age                          61
M/F                           M
City                  Mt. Tabor
State                        NJ
Country                     USA
Half            0 days 01:55:16
40K             0 days 03:44:30
Pace                    0:09:05
TotalSeconds            13470.0
HalfSeconds              6916.0
Name: 24393, dtype: object
Mt.pearl
 Age                          46
M/F                           M
City                   Mt.pearl
State                        NL
Country                     CAN
Half            0 days 01:37:12
40K             0 days 03:21:32
Pace                    0:08:11
TotalSeconds            12092.0
HalfSeconds              5832.0
Name: 11857, dtype: object
Mtn. Grove
 Age                          46
M/F                           F
City                 Mtn. Grove
State                        MO
Country                     USA
Half            0 days 01:59:45
40K             0 days 03:51:47
Pace                    0:09:21
TotalSeconds            13907.0
HalfSeconds              7185.0
Name: 23525, dtype: object
Muenchen
 Age                          40
M/F                           M
City                   Muenchen
State                       NaN
Country                     GER
Half            0 days 01:30:16
40K             0 days 03:06:58
Pace                    0:07:35
TotalSeconds            11218.0
HalfSeconds              5416.0
Name: 5598, dtype: object
Mukilteo
 Age                          52
M/F                           F
City                   Mukilteo

N Weymouth
 Age                          58
M/F                           F
City                 N Weymouth
State                        MA
Country                     USA
Half            0 days 02:02:20
40K             0 days 04:06:23
Pace                    0:09:55
TotalSeconds            14783.0
HalfSeconds              7340.0
Name: 25484, dtype: object
N. Augusta
 Age                          53
M/F                           F
City                 N. Augusta
State                        SC
Country                     USA
Half            0 days 01:44:24
40K             0 days 03:22:28
Pace                    0:08:10
TotalSeconds            12148.0
HalfSeconds              6264.0
Name: 19864, dtype: object
N. Billerica
 Age                          31
M/F                           F
City               N. Billerica
State                        MA
Country                     USA
Half            0 days 01:59:40
40K             0 days 04:12:20
Pace                    0:10:12
TotalSeconds            15140.0
HalfSeconds              7180.0
Name: 27425, dtype: object
NSW
 Age                          55
M/F                           F
City                        NSW
State                       NaN
Country                     AUS
Half            0 days 01:52:35
40K             0 days 03:37:26
Pace                    0:08:46
TotalSeconds            13046.0
HalfSeconds              6755.0
Name: 25371, dtype: object
Naas, Co. Kildare
 Age                            34
M/F                             M
City            Naas, Co. Kildare
State                         NaN
Country                       IRL
Half              0 days 01:22:49
40K               0 days 04:26:14
Pace                      0:10:43
TotalSeconds              15974.0
HalfSeconds                4969.0
Name: 1575, dtype: object
Nacogdoches
 Age                          57
M/F                           M
City                Nacogdoches
State                        TX
Country                     USA
Half            0 days 01:38:52
40K             0 days 03:21:22
Pace                    0:08:09
TotalSeconds            12082.0
HalfSeconds              5932.0
Name: 11754, dtype: object
Nagakute-Si, Aichi-Ken
 Age                                 55
M/F                                  M
City            Nagakute-Si, Aichi-Ken
State                              NaN
Country                            JPN
Half                   0 days 01:31:38
40K                    0 days 03:01:42
Pace                           0:07:19
TotalSeconds                   10902.0
HalfSeconds                     5498.0
Name: 4368, dtype: object
Nagano
 Age                          51
M/F                           M
City                     Nagano
State                       NaN
Country                     JPN
Half            0 days 01:44:33
40K             0 days 03:37:28
Pace                    0:08:47
TotalSeconds            13048.0
HalfSeconds              6273.0
Name: 13302, dtype: object
Nagasaki City, Nagasaki
 Age                                  52
M/F                                   M
City            Nagasaki City, Nagasaki
State                               NaN
Country                             JPN
Half                    0 days 02:38:44
40K                     0 days 05:18:32
Pace                            0:12:53
TotalSeconds                    19112.0
HalfSeconds                      9524.0
Name: 31706, dtype: object
Nagoya
 Age                          62
M/F                           M
City                     Nagoya
State                       NaN
Country                     JPN
Half            0 days 01:50:19
40K             0 days 03:33:17
Pace                    0:08:37
TotalSeconds            12797.0
HalfSeconds              6619.0
Name: 21669, dtype: object
Nagoya-City, Aichi-Prefecture
 Age                                        42
M/F                                         F
City            Nagoya-City, Aichi-Prefecture
State                                     NaN
Country                                   JPN
Half                          0 days 01:49:52
40K                           0 days 03:43:29
Pace                                  0:09:02
TotalSeconds                          13409.0
HalfSeconds                            6592.0
Name: 15366, dtype: object
Nahant
 Age                          23
M/F                           F
City                     Nahant
State                        MA
Country                     USA
Half            0 days 01:54:03
40K             0 days 03:40:59
Pace                    0:08:55
TotalSeconds            13259.0
HalfSeconds              6843.0
Name: 26373, dtype: object
Nairn
 Age                          48
M/F                           M
City                      Nairn
State                       NaN
Country                     GBR
Half            0 days 01:41:38
40K             0 days 03:22:47
Pace                    0:08:12
TotalSeconds            12167.0
HalfSeconds              6098.0
Name: 11613, dtype: object
Nakanoku Tokyo
 Age                          48
M/F                           F
City             Nakanoku Tokyo
State                       NaN
Country                     JPN
Half            0 days 01:46:58
40K             0 days 03:26:14
Pace                    0:08:19
TotalSeconds            12374.0
HalfSeconds              6418.0
Name: 16707, dtype: object
Nakusp
 Age                          53
M/F                           F
City                     Nakusp
State                        BC
Country                     CAN
Half            0 days 01:55:32
40K             0 days 03:54:53
Pace                    0:09:31
TotalSeconds            14093.0
HalfSeconds              6932.0
Name: 24627, dtype: object
Nampa
 Age                          60
M/F                           M
City                      Nampa
State                        ID
Country                     USA
Half            0 days 01:51:01
40K             0 days 03:38:50
Pace                    0:08:51
TotalSeconds            13130.0
HalfSeconds              6661.0
Name: 20935, dtype: object
Nanaimo
 Age                          43
M/F                           M
City                    Nanaimo
State                        BC
Country                     CAN
Half            0 days 01:34:40
40K             0 days 03:18:42
Pace                    0:08:03
TotalSeconds            11922.0
HalfSeconds              5680.0
Name: 8852, dtype: object
Nanchang Jx
 Age                          34
M/F                           M
City                Nanchang Jx
State                       NaN
Country                     CHN
Half            0 days 02:23:01
40K             0 days 04:55:41
Pace                    0:11:58
TotalSeconds            17741.0
HalfSeconds              8581.0
Name: 29614, dtype: object
Nancy
 Age                          61
M/F                           M
City                      Nancy
State                       NaN
Country                     FRA
Half            0 days 02:00:07
40K             0 days 04:00:43
Pace                    0:09:46
TotalSeconds            14443.0
HalfSeconds              7207.0
Name: 31575, dtype: object
Nantucket
 Age                          47
M/F                           M
City                  Nantucket
State                        MA
Country                     USA
Half            0 days 01:51:46
40K             0 days 03:36:24
Pace                    0:08:43
TotalSeconds            12984.0
HalfSeconds              6706.0
Name: 29054, dtype: object
Nanuet
 Age                          45
M/F                           F
City                     Nanuet
State                        NY
Country                     USA
Half            0 days 01:41:27
40K             0 days 03:14:34
Pace                    0:07:52
TotalSeconds            11674.0
HalfSeconds              6087.0
Name: 11444, dtype: object
Napa
 Age                          31
M/F                           F
City                       Napa
State                        CA
Country                     USA
Half            0 days 01:47:27
40K             0 days 03:25:01
Pace                    0:08:14
TotalSeconds            12301.0
HalfSeconds              6447.0
Name: 14353, dtype: object
Naperville
 Age                          23
M/F                           M
City                 Naperville
State                        IL
Country                     USA
Half            0 days 01:17:46
40K             0 days 02:32:17
Pace                    0:06:10
TotalSeconds             9137.0
HalfSeconds              4666.0
Name: 817, dtype: object
Naples
 Age                          33
M/F                           M
City                     Naples
State                        FL
Country                     USA
Half            0 days 01:25:05
40K             0 days 02:45:06
Pace                    0:06:40
TotalSeconds             9906.0
HalfSeconds              5105.0
Name: 1794, dtype: object
Nara City
 Age                          75
M/F                           M
City                  Nara City
State                       NaN
Country                     JPN
Half            0 days 01:59:55
40K             0 days 04:52:41
Pace                    0:12:02
TotalSeconds            17561.0
HalfSeconds              7195.0
Name: 25044, dtype: object
Narberth
 Age                          24
M/F                           M
City                   Narberth
State                        PA
Country                     USA
Half            0 days 01:12:27
40K             0 days 02:31:54
Pace                    0:06:23
TotalSeconds             9114.0
HalfSeconds              4347.0
Name: 164, dtype: object
Naremburn
 Age                          55
M/F                           M
City                  Naremburn
State                       NaN
Country                     AUS
Half            0 days 02:13:16
40K             0 days 04:36:42
Pace                    0:11:11
TotalSeconds            16602.0
HalfSeconds              7996.0
Name: 31553, dtype: object
Narragansett
 Age                          53
M/F                           M
City               Narragansett
State                        RI
Country                     USA
Half            0 days 01:39:50
40K             0 days 03:20:19
Pace                    0:08:07
TotalSeconds            12019.0
HalfSeconds              5990.0
Name: 12583, dtype: object
Narvon
 Age                          40
M/F                           F
City                     Narvon
State                        PA
Country                     USA
Half            0 days 01:31:59
40K             0 days 02:59:46
Pace                    0:07:16
TotalSeconds            10786.0
HalfSeconds              5519.0
Name: 4705, dtype: object
Nashua
 Age                          25
M/F                           M
City                     Nashua
State                        NH
Country                     USA
Half            0 days 01:18:11
40K             0 days 02:33:55
Pace                    0:06:14
TotalSeconds             9235.0
HalfSeconds              4691.0
Name: 1164, dtype: object
Nashville
 Age                          21
M/F                           M
City                  Nashville
State                        TN
Country                     USA
Half            0 days 01:22:10
40K             0 days 02:39:49
Pace                    0:06:31
TotalSeconds             9589.0
HalfSeconds              4930.0
Name: 1109, dtype: object
Nassau
 Age                          49
M/F                           F
City                     Nassau
State                        NY
Country                     USA
Half            0 days 01:48:08
40K             0 days 03:39:36
Pace                    0:08:52
TotalSeconds            13176.0
HalfSeconds              6488.0
Name: 18435, dtype: object
Nassau Bay
 Age                          61
M/F                           M
City                 Nassau Bay
State                        TX
Country                     USA
Half            0 days 01:49:43
40K             0 days 03:59:25
Pace                    0:09:41
TotalSeconds            14365.0
HalfSeconds              6583.0
Name: 19733, dtype: object
Natick
 Age                          38
M/F                           M
City                     Natick
State                        MA
Country                     USA
Half            0 days 01:23:09
40K             0 days 02:41:25
Pace                    0:06:31
TotalSeconds             9685.0
HalfSeconds              4989.0
Name: 2354, dtype: object
National City
 Age                          50
M/F                           M
City              National City
State                        CA
Country                     USA
Half            0 days 01:41:02
40K             0 days 03:18:08
Pace                    0:08:03
TotalSeconds            11888.0
HalfSeconds              6062.0
Name: 13360, dtype: object
National Park
 Age                          52
M/F                           M
City              National Park
State                        NJ
Country                     USA
Half            0 days 01:39:35
40K             0 days 03:10:46
Pace                    0:07:42
TotalSeconds            11446.0
HalfSeconds              5975.0
Name: 11588, dtype: object
Naucalpan
 Age                          24
M/F                           M
City                  Naucalpan
State                       NaN
Country                     MEX
Half            0 days 01:27:50
40K             0 days 02:51:24
Pace                    0:06:56
TotalSeconds            10284.0
HalfSeconds              5270.0
Name: 4667, dtype: object
Naucalpan Edo Mex
 Age                            36
M/F                             M
City            Naucalpan Edo Mex
State                         NaN
Country                       MEX
Half              0 days 01:35:42
40K               0 days 03:22:42
Pace                      0:08:13
TotalSeconds              12162.0
HalfSeconds                5742.0
Name: 567, dtype: object
Naucalpan Estado De Mex
 Age                                  35
M/F                                   F
City            Naucalpan Estado De Mex
State                               NaN
Country                             MEX
Half                    0 days 01:43:07
40K                     0 days 03:29:28
Pace                            0:08:31
TotalSeconds                    12568.0
HalfSeconds                      6187.0
Name: 12392, dtype: object
Naucalpan, Edo De Mex
 Age                                48
M/F                                 M
City            Naucalpan, Edo De Mex
State                             NaN
Country                           MEX
Half                  0 days 02:02:01
40K                   0 days 04:13:21
Pace                          0:10:13
TotalSeconds                  15201.0
HalfSeconds                    7321.0
Name: 31663, dtype: object
Naucalpan, Edo. Mex.
 Age                               38
M/F                                F
City            Naucalpan, Edo. Mex.
State                            NaN
Country                          MEX
Half                 0 days 01:44:29
40K                  0 days 03:35:52
Pace                         0:08:43
TotalSeconds                 12952.0
HalfSeconds                   6269.0
Name: 18138, dtype: object
Naucalpan, Estado De México
 Age                                      52
M/F                                       M
City            Naucalpan, Estado De México
State                                   NaN
Country                                 MEX
Half                        0 days 01:32:43
40K                         0 days 03:10:14
Pace                                0:07:43
TotalSeconds                        11414.0
HalfSeconds                          5563.0
Name: 6914, dtype: object
Naugatuck
 Age                          30
M/F                           F
City                  Naugatuck
State                        CT
Country                     USA
Half            0 days 01:45:00
40K             0 days 03:35:13
Pace                    0:08:40
TotalSeconds            12913.0
HalfSeconds              6300.0
Name: 8624, dtype: object
Navan
 Age                          45
M/F                           M
City                      Navan
State                       NaN
Country                     IRL
Half            0 days 01:49:45
40K             0 days 03:47:19
Pace                    0:09:11
TotalSeconds            13639.0
HalfSeconds              6585.0
Name: 8758, dtype: object
Navarre
 Age                          46
M/F                           F
City                    Navarre
State                        FL
Country                     USA
Half            0 days 01:47:21
40K             0 days 03:33:16
Pace                    0:08:36
TotalSeconds            12796.0
HalfSeconds              6441.0
Name: 19486, dtype: object
Nazareth
 Age                          24
M/F                           F
City                   Nazareth
State                        PA
Country                     USA
Half            0 days 01:32:33
40K             0 days 03:06:27
Pace                    0:07:34
TotalSeconds            11187.0
HalfSeconds              5553.0
Name: 10732, dtype: object
Nd-Du-Mont-Carmel
 Age                            46
M/F                             M
City            Nd-Du-Mont-Carmel
State                          QC
Country                       CAN
Half              0 days 01:36:40
40K               0 days 03:17:48
Pace                      0:08:03
TotalSeconds              11868.0
HalfSeconds                5800.0
Name: 6843, dtype: object
Ne7 7an
 Age                          57
M/F                           M
City                    Ne7 7an
State                       NaN
Country                     GBR
Half            0 days 02:13:00
40K             0 days 04:23:45
Pace                    0:10:41
TotalSeconds            15825.0
HalfSeconds              7980.0
Name: 17940, dtype: object
Nea Ionia
 Age                          54
M/F                           M
City                  Nea Ionia
State                       NaN
Country                     GRE
Half            0 days 02:11:06
40K             0 days 04:23:14
Pace                    0:10:41
TotalSeconds            15794.0
HalfSeconds              7866.0
Name: 23421, dtype: object
Nedervetil
 Age                          61
M/F                           M
City                 Nedervetil
State                       NaN
Country                     FIN
Half            0 days 02:00:17
40K             0 days 04:05:48
Pace                    0:09:58
TotalSeconds            14748.0
HalfSeconds              7217.0
Name: 22057, dtype: object
Nedrow
 Age                          30
M/F                           M
City                     Nedrow
State                        NY
Country                     USA
Half            0 days 01:47:37
40K             0 days 03:45:54
Pace                    0:09:02
TotalSeconds            13554.0
HalfSeconds              6457.0
Name: 9990, dtype: object
Needham
 Age                          18
M/F                           M
City                    Needham
State                        MA
Country                     USA
Half            0 days 01:22:35
40K             0 days 02:38:30
Pace                    0:06:23
TotalSeconds             9510.0
HalfSeconds              4955.0
Name: 2115, dtype: object
Needham Heights
 Age                          57
M/F                           M
City            Needham Heights
State                        MA
Country                     USA
Half            0 days 02:09:57
40K             0 days 04:45:07
Pace                    0:11:25
TotalSeconds            17107.0
HalfSeconds              7797.0
Name: 26588, dtype: object
Neenah
 Age                          31
M/F                           F
City                     Neenah
State                        WI
Country                     USA
Half            0 days 01:42:23
40K             0 days 03:17:29
Pace                    0:07:58
TotalSeconds            11849.0

New Haven
 Age                          25
M/F                           F
City                  New Haven
State                        CT
Country                     USA
Half            0 days 01:31:09
40K             0 days 02:52:11
Pace                    0:06:56
TotalSeconds            10331.0
HalfSeconds              5469.0
Name: 3997, dtype: object
New Hope
 Age                          50
M/F                           M
City                   New Hope
State                        PA
Country                     USA
Half            0 days 01:44:17
40K             0 days 03:23:54
Pace                    0:08:14
TotalSeconds            12234.0
HalfSeconds              6257.0
Name: 13112, dtype: object
New Hudson
 Age                          32
M/F                           F
City                 New Hudson
State                        MI
Country                     USA
Half            0 days 01:38:43
40K             0 days 03:16:05
Pace                    0:07:56
TotalSeconds            11765.0
HalfSeconds              5923.0
Name: 11921, dtype: object
New Ipswich
 Age                          42
M/F                           M
City                New Ipswich
State                        NH
Country                     USA
Half            0 days 01:31:23
40K             0 days 02:58:07
Pace                    0:07:10
TotalSeconds            10687.0
HalfSeconds              5483.0
Name: 5760, dtype: object
New Lenox
 Age                          53
M/F                           M
City                  New Lenox
State                        IL
Country                     USA
Half            0 days 01:40:59
40K             0 days 03:17:08
Pace                    0:07:58
TotalSeconds            11828.0
HalfSeconds              6059.0
Name: 15035, dtype: object
New London
 Age                          30
M/F                           M
City                 New London
State                        CT
Country                     USA
Half            0 days 01:32:03
40K             0 days 03:04:08
Pace                    0:07:26
TotalSeconds            11048.0
HalfSeconds              5523.0
Name: 1784, dtype: object
New Market
 Age                          36
M/F                           M
City                 New Market
State                        VA
Country                     USA
Half            0 days 01:27:27
40K             0 days 03:12:24
Pace                    0:07:48
TotalSeconds            11544.0
HalfSeconds              5247.0
Name: 4363, dtype: object
New Maryland
 Age                          48
M/F                           M
City               New Maryland
State                        NB
Country                     CAN
Half            0 days 01:46:05
40K             0 days 03:23:21
Pace                    0:08:12
TotalSeconds            12201.0
HalfSeconds              6365.0
Name: 11222, dtype: object
New Milford
 Age                          22
M/F                           F
City                New Milford
State                        CT
Country                     USA
Half            0 days 01:40:22
40K             0 days 03:17:24
Pace                    0:08:00
TotalSeconds            11844.0
HalfSeconds              6022.0
Name: 12973, dtype: object
New Milton
 Age                          38
M/F                           F
City                 New Milton
State                       NaN
Country                     GBR
Half            0 days 02:15:25
40K             0 days 04:23:27
Pace                    0:10:36
TotalSeconds            15807.0
HalfSeconds              8125.0
Name: 31486, dtype: object
New Minas
 Age                          65
M/F                           M
City                  New Minas
State                        NS
Country                     CAN
Half            0 days 01:45:39
40K             0 days 03:24:22
Pace                    0:08:15
TotalSeconds            12262.0
HalfSeconds              6339.0
Name: 13363, dtype: object
New Orleans
 Age                          41
M/F                           M
City                New Orleans
State                        LA
Country                     USA
Half            0 days 01:28:48
40K             0 days 02:52:26
Pace                    0:06:57
TotalSeconds            10346.0
HalfSeconds              5328.0
Name: 3679, dtype: object
New Palestine
 Age                          44
M/F                           M
City              New Palestine
State                        IN
Country                     USA
Half            0 days 01:25:10
40K             0 days 02:50:42
Pace                    0:06:54
TotalSeconds            10242.0
HalfSeconds              5110.0
Name: 1472, dtype: object
New Paltz
 Age                          30
M/F                           M
City                  New Paltz
State                        NY
Country                     USA
Half            0 days 01:08:48
40K             0 days 02:16:22
Pace                    0:05:32
TotalSeconds             8182.0
HalfSeconds              4128.0
Name: 27, dtype: object
New Paris
 Age                          48
M/F                           M
City                  New Paris
State                        OH
Country                     USA
Half            0 days 01:52:55
40K             0 days 03:40:10
Pace                    0:08:52
TotalSeconds            13210.0
HalfSeconds              6775.0
Name: 12172, dtype: object
New Philadelphia
 Age                           46
M/F                            M
City            New Philadelphia
State                         OH
Country                      USA
Half             0 days 01:26:12
40K              0 days 03:02:48
Pace                     0:07:23
TotalSeconds             10968.0
HalfSeconds               5172.0
Name: 1869, dtype: object
New Port Richey
 Age                          36
M/F                           F
City            New Port Richey
State                        FL
Country                     USA
Half            0 days 01:29:38
40K             0 days 02:55:35
Pace                    0:07:05
TotalSeconds            10535.0
HalfSeconds              5378.0
Name: 3596, dtype: object
New Providence
 Age                          35
M/F                           M
City             New Providence
State                        NJ
Country                     USA
Half            0 days 01:35:14
40K             0 days 03:17:42
Pace                    0:08:00
TotalSeconds            11862.0
HalfSeconds              5714.0
Name: 4843, dtype: object
New Richmond
 Age                          25
M/F                           M
City               New Richmond
State                        WI
Country                     USA
Half            0 days 01:37:46
40K             0 days 03:08:31
Pace                    0:07:35
TotalSeconds            11311.0
HalfSeconds              5866.0
Name: 1671, dtype: object
New Ringgold
 Age                          47
M/F                           F
City               New Ringgold
State                        PA
Country                     USA
Half            0 days 01:48:52
40K             0 days 03:34:12
Pace                    0:08:40
TotalSeconds            12852.0
HalfSeconds              6532.0
Name: 21837, dtype: object
New River
 Age                          64
M/F                           M
City                  New River
State                        AZ
Country                     USA
Half            0 days 01:52:18
40K             0 days 03:55:18
Pace                    0:09:31
TotalSeconds            14118.0
HalfSeconds              6738.0
Name: 24035, dtype: object
New Roads
 Age                          46
M/F                           M
City                  New Roads
State                        LA
Country                     USA
Half            0 days 02:12:27
40K             0 days 04:37:51
Pace                    0:11:18
TotalSeconds            16671.0
HalfSeconds              7947.0
Name: 31958, dtype: object
New Rochelle
 Age                          55
M/F                           F
City               New Rochelle
State                        NY
Country                     USA
Half            0 days 02:03:37
40K             0 days 04:08:59
Pace                    0:10:04
TotalSeconds            14939.0
HalfSeconds              7417.0
Name: 24960, dtype: object
New Ross
 Age                          61
M/F                           F
City                   New Ross
State                        NS
Country                     CAN
Half            0 days 02:08:19
40K             0 days 04:15:20
Pace                    0:10:19
TotalSeconds            15320.0
HalfSeconds              7699.0
Name: 25800, dtype: object
New Smyrna Beach
 Age                           24
M/F                            M
City            New Smyrna Beach
State                         FL
Country                      USA
Half             0 days 01:26:17
40K              0 days 03:03:35
Pace                     0:07:27
TotalSeconds             11015.0
HalfSeconds               5177.0
Name: 2816, dtype: object
New South Wales
 Age                          39
M/F                           M
City            New South Wales
State                       NaN
Country                     AUS
Half            0 days 02:01:09
40K             0 days 04:12:58
Pace                    0:10:17
TotalSeconds            15178.0
HalfSeconds              7269.0
Name: 31803, dtype: object
New South Whales
 Age                           36
M/F                            M
City            New South Whales
State                        NaN
Country                      AUS
Half             0 days 02:11:34
40K              0 days 05:03:11
Pace                     0:12:27
TotalSeconds             18191.0
HalfSeconds               7894.0
Name: 31804, dtype: object
New Taipei City
 Age                          39
M/F                           M
City            New Taipei City
State                       NaN
Country                     TWN
Half            0 days 01:25:15
40K             0 days 02:44:10
Pace                    0:06:37
TotalSeconds             9850.0
HalfSeconds              5115.0
Name: 3129, dtype: object
New Tecumseth
 Age                          39
M/F                           F
City              New Tecumseth
State                        ON
Country                     CAN
Half            0 days 01:44:18
40K             0 days 03:19:24
Pace                    0:08:01
TotalSeconds            11964.0
HalfSeconds              6258.0
Name: 14638, dtype: object
New Territories
 Age                          36
M/F                           M
City            New Territories
State                       NaN
Country                     HKG
Half            0 days 01:33:10
40K             0 days 03:03:45
Pace                    0:07:24
TotalSeconds            11025.0
HalfSeconds              5590.0
Name: 5700, dtype: object
New Westminster
 Age                          50
M/F                           M
City            New Westminster
State                        BC
Country                     CAN
Half            0 days 01:43:08
40K             0 days 03:20:42
Pace                    0:08:06
TotalSeconds            12042.0
HalfSeconds              6188.0
Name: 13650, dtype: object
New Windsor
 Age                          36
M/F                           F
City                New Windsor
State                        NY
Country                     USA
Half            0 days 01:52:18
40K             0 days 03:39:40
Pace                    0:08:57
TotalSeconds            13180.0
HalfSeconds              6738.0
Name: 18286, dtype: object
New York
 Age                          36
M/F                           M
City                   New York
State                        NY
Country                     USA
Half            0 days 01:18:00
40K             0 days 02:32:02
Pace                    0:06:08
TotalSeconds             9122.0
HalfSeconds              4680.0
Name: 530, dtype: object
New York City
 Age                          46
M/F                           M
City              New York City
State                        NY
Country                     USA
Half            0 days 01:24:16
40K             0 days 02:42:03
Pace                    0:06:34
TotalSeconds             9723.0
HalfSeconds              5056.0
Name: 4945, dtype: object
Newark
 Age                          37
M/F                           M
City                     Newark
State                        DE
Country                     USA
Half            0 days 01:21:02
40K             0 days 02:37:42
Pace                    0:06:21
TotalSeconds             9462.0
HalfSeconds              4862.0
Name: 726, dtype: object
Newberg
 Age                          52
M/F                           F
City                    Newberg
State                        OR
Country                     USA
Half            0 days 01:57:19
40K             0 days 04:02:51
Pace                    0:09:51
TotalSeconds            14571.0
HalfSeconds              7039.0
Name: 22192, dtype: object
Newburgh
 Age                          47
M/F                           M
City                   Newburgh
State                        IN
Country                     USA
Half            0 days 01:35:41
40K             0 days 03:22:16
Pace                    0:08:15
TotalSeconds            12136.0
HalfSeconds              5741.0
Name: 8147, dtype: object
Newburgh Heights
 Age                           34
M/F                            M
City            Newburgh Heights
State                         OH
Country                      USA
Half             0 days 01:30:58
40K              0 days 03:06:27
Pace                     0:07:32
TotalSeconds             11187.0
HalfSeconds               5458.0
Name: 4680, dtype: object
Newbury
 Age                          47
M/F                           M
City                    Newbury
State                       NaN
Country                     GBR
Half            0 days 01:36:52
40K             0 days 03:15:54
Pace                    0:07:53
TotalSeconds            11754.0
HalfSeconds              5812.0
Name: 5207, dtype: object
Newbury Park
 Age                          40
M/F                           M
City               Newbury Park
State                        CA
Country                     USA
Half            0 days 01:29:09
40K             0 days 03:05:26
Pace                    0:07:39
TotalSeconds            11126.0
HalfSeconds              5349.0
Name: 3553, dtype: object
Newburyport
 Age                          49
M/F                           M
City                Newburyport
State                        MA
Country                     USA
Half            0 days 01:30:43
40K             0 days 02:57:16
Pace                    0:07:09
TotalSeconds            10636.0
HalfSeconds              5443.0
Name: 5678, dtype: object
Newcastle
 Age                          61
M/F                           M
City                  Newcastle
State                        WA
Country                     USA
Half            0 days 01:57:26
40K             0 days 03:55:40
Pace                    0:09:34
TotalSeconds            14140.0
HalfSeconds              7046.0
Name: 18738, dtype: object
Newcastle Upon Tyne
 Age                              55
M/F                               M
City            Newcastle Upon Tyne
State                           NaN
Country                         GBR
Half                0 days 01:39:19
40K                 0 days 03:31:50
Pace                        0:08:37
TotalSeconds                12710.0
HalfSeconds                  5959.0
Name: 16087, dtype: object
Newfields
 Age                          44
M/F                           M
City                  Newfields
State                        NH
Country                     USA
Half            0 days 02:06:55
40K             0 days 04:38:08
Pace                    0:11:15
TotalSeconds            16688.0
HalfSeconds              7615.0
Name: 30010, dtype: object
Newhall
 Age                          31
M/F                           M
City                    Newhall
State                        CA
Country                     USA
Half            0 days 01:37:10
40K             0 days 03:35:11
Pace                    0:08:44
TotalSeconds            12911.0
HalfSeconds              5830.0
Name: 4300, dtype: object
Newington
 Age                          26
M/F                           M
City                  Newington
State                        CT
Country                     USA
Half            0 days 01:21:47
40K             0 days 02:48:02
Pace                    0:06:47
TotalSeconds            10082.0
HalfSeconds              4907.0
Name: 586, dtype: object
Newmarket
 Age                          24
M/F                           M
City                  Newmarket
State                        NH
Country                     USA
Half            0 days 01:11:58
40K             0 days 02:24:03
Pace                    0:05:50
TotalSeconds             8643.0
HalfSeconds              4318.0
Name: 114, dtype: object
Newnan
 Age                          39
M/F                           M
City                     Newnan
State                        GA
Country                     USA
Half            0 days 01:27:25
40K             0 days 02:50:06
Pace                    0:06:51
TotalSeconds            10206.0
HalfSeconds              5245.0
Name: 1492, dtype: object
Newport
 Age                          33
M/F                           M
City                    Newport
State                        RI
Country                     USA
Half            0 days 01:34:56
40K             0 days 03:04:37
Pace                    0:07:28
TotalSeconds            11077.0
HalfSeconds              5696.0
Name: 26201, dtype: object
Newport Beach
 Age                          41
M/F                           F
City              Newport Beach
State                        CA
Country                     USA
Half            0 days 01:28:21
40K             0 days 03:05:12
Pace                    0:07:35
TotalSeconds            11112.0
HalfSeconds              5301.0
Name: 3023, dtype: object
Newport News
 Age                          32
M/F                           M
City               Newport News
State                        VA
Country                     USA
Half            0 days 01:25:27
40K             0 days 02:48:51
Pace                    0:06:51
TotalSeconds            10131.0
HalfSeconds              5127.0
Name: 2925, dtype: object
Newry
 Age                          35
M/F                           M
City                      Newry
State                       NaN
Country                     GBR
Half            0 days 01:18:34
40K             0 days 02:35:46
Pace                    0:06:19
TotalSeconds             9346.0
HalfSeconds              4714.0
Name: 368, dtype: object
Newton
 Age                          24
M/F                           M
City                     Newton
State                        MA
Country                     USA
Half            0 days 01:13:51
40K             0 days 02:23:50
Pace                    0:05:48
TotalSeconds             8630.0
HalfSeconds              4431.0
Name: 820, dtype: object
Newton Center
 Age                          45
M/F                           M
City              Newton Center
State                        MA
Country                     USA
Half            0 days 01:34:10
40K             0 days 03:13:38
Pace                    0:07:50
TotalSeconds            11618.0
HalfSeconds              5650.0
Name: 6726, dtype: object
Newton Centre
 Age                          61
M/F                           M
City              Newton Centre
State                        MA
Country                     USA
Half            0 days 02:43:52
40K             0 days 05:31:04
Pace                    0:13:25
TotalSeconds            19864.0
HalfSeconds              9832.0
Name: 26467, dtype: object
Newton Highlands
 Age                           49
M/F                            M
City            Newton Highlands
State                         MA

Name: 5080, dtype: object
Normal
 Age                          38
M/F                           F
City                     Normal
State                        IL
Country                     USA
Half            0 days 01:51:53
40K             0 days 03:36:41
Pace                    0:08:44
TotalSeconds            13001.0
HalfSeconds              6713.0
Name: 20368, dtype: object
Norman
 Age                          48
M/F                           M
City                     Norman
State                        OK
Country                     USA
Half            0 days 01:23:04
40K             0 days 02:39:22
Pace                    0:06:25
TotalSeconds             9562.0
HalfSeconds              4984.0
Name: 539, dtype: object
Norrtalje
 Age                          55
M/F                           F
City                  Norrtalje
State                       NaN
Country                     SWE
Half            0 days 02:00:57
40K             0 days 03:56:26
Pace                    0:09:30
TotalSeconds            14186.0
HalfSeconds              7257.0
Name: 24805, dtype: object
Norrtelje
 Age                          66
M/F                           M
City                  Norrtelje
State                       NaN
Country                     SWE
Half            0 days 01:54:57
40K             0 days 03:51:06
Pace                    0:09:20
TotalSeconds            13866.0
HalfSeconds              6897.0
Name: 22858, dtype: object
Nortborough
 Age                          50
M/F                           M
City                Nortborough
State                        MA
Country                     USA
Half            0 days 01:33:05
40K             0 days 03:12:36
Pace                    0:07:50
TotalSeconds            11556.0
HalfSeconds              5585.0
Name: 9017, dtype: object
North Adams
 Age                          37
M/F                           F
City                North Adams
State                        MA
Country                     USA
Half            0 days 02:02:07
40K             0 days 04:16:34
Pace                    0:10:23
TotalSeconds            15394.0
HalfSeconds              7327.0
Name: 30076, dtype: object
North Andover
 Age                          37
M/F                           M
City              North Andover
State                        MA
Country                     USA
Half            0 days 01:19:36
40K             0 days 02:35:01
Pace                    0:06:16
TotalSeconds             9301.0
HalfSeconds              4776.0
Name: 979, dtype: object
North Attleboro
 Age                          47
M/F                           M
City            North Attleboro
State                        MA
Country                     USA
Half            0 days 01:35:23
40K             0 days 03:06:39
Pace                    0:07:33
TotalSeconds            11199.0
HalfSeconds              5723.0
Name: 8457, dtype: object
North Augusta
 Age                          24
M/F                           F
City              North Augusta
State                        SC
Country                     USA
Half            0 days 01:37:56
40K             0 days 03:09:34
Pace                    0:07:37
TotalSeconds            11374.0
HalfSeconds              5876.0
Name: 11832, dtype: object
North Aurora
 Age                          29
M/F                           F
City               North Aurora
State                        IL
Country                     USA
Half            0 days 01:34:41
40K             0 days 03:05:43
Pace                    0:07:30
TotalSeconds            11143.0
HalfSeconds              5681.0
Name: 5706, dtype: object
North Babylon
 Age                          51
M/F                           M
City              North Babylon
State                        NY
Country                     USA
Half            0 days 01:35:07
40K             0 days 03:18:03
Pace                    0:08:00
TotalSeconds            11883.0
HalfSeconds              5707.0
Name: 5774, dtype: object
North Bay
 Age                          31
M/F                           M
City                  North Bay
State                        ON
Country                     CAN
Half            0 days 01:32:18
40K             0 days 03:01:52
Pace                    0:07:21
TotalSeconds            10912.0
HalfSeconds              5538.0
Name: 3842, dtype: object
North Bay Village
 Age                            40
M/F                             M
City            North Bay Village
State                          FL
Country                       USA
Half              0 days 01:32:50
40K               0 days 03:01:42
Pace                      0:07:21
TotalSeconds              10902.0
HalfSeconds                5570.0
Name: 5748, dtype: object
North Bend
 Age                          53
M/F                           M
City                 North Bend
State                        WA
Country                     USA
Half            0 days 01:31:59
40K             0 days 02:59:28
Pace                    0:07:14
TotalSeconds            10768.0
HalfSeconds              5519.0
Name: 2842, dtype: object
North Bennington
 Age                           37
M/F                            F
City            North Bennington
State                         VT
Country                      USA
Half             0 days 02:02:07
40K              0 days 04:09:27
Pace                     0:10:04
TotalSeconds             14967.0
HalfSeconds               7327.0
Name: 30001, dtype: object
North Bergen
 Age                          47
M/F                           M
City               North Bergen
State                        NJ
Country                     USA
Half            0 days 01:37:52
40K             0 days 03:38:54
Pace                    0:08:58
TotalSeconds            13134.0
HalfSeconds              5872.0
Name: 12352, dtype: object
North Berwick
 Age                          29
M/F                           F
City              North Berwick
State                        ME
Country                     USA
Half            0 days 02:32:09
40K             0 days 04:49:58
Pace                    0:11:35
TotalSeconds            17398.0
HalfSeconds              9129.0
Name: 31109, dtype: object
North Brunswick
 Age                          34
M/F                           M
City            North Brunswick
State                        NJ
Country                     USA
Half            0 days 01:18:47
40K             0 days 02:33:08
Pace                    0:06:12
TotalSeconds             9188.0
HalfSeconds              4727.0
Name: 1649, dtype: object
North Caldwell
 Age                          41
M/F                           M
City             North Caldwell
State                        NJ
Country                     USA
Half            0 days 01:34:33
40K             0 days 03:10:54
Pace                    0:07:46
TotalSeconds            11454.0
HalfSeconds              5673.0
Name: 8345, dtype: object
North Canton
 Age                          31
M/F                           M
City               North Canton
State                        OH
Country                     USA
Half            0 days 01:22:21
40K             0 days 02:39:44
Pace                    0:06:27
TotalSeconds             9584.0
HalfSeconds              4941.0
Name: 1864, dtype: object
North Charleston
 Age                           26
M/F                            F
City            North Charleston
State                         SC
Country                      USA
Half             0 days 01:34:10
40K              0 days 03:03:33
Pace                     0:07:25
TotalSeconds             11013.0
HalfSeconds               5650.0
Name: 10163, dtype: object
North Chelmsford
 Age                           34
M/F                            M
City            North Chelmsford
State                         MA
Country                      USA
Half             0 days 01:58:13
40K              0 days 04:11:33
Pace                     0:10:18
TotalSeconds             15093.0
HalfSeconds               7093.0
Name: 30436, dtype: object
North Chesterfield
 Age                             42
M/F                              F
City            North Chesterfield
State                           VA
Country                        USA
Half               0 days 01:38:46
40K                0 days 03:16:35
Pace                       0:07:57
TotalSeconds               11795.0
HalfSeconds                 5926.0
Name: 10707, dtype: object
North Chili
 Age                          25
M/F                           M
City                North Chili
State                        NY
Country                     USA
Half            0 days 01:15:01
40K             0 days 02:34:08
Pace                    0:06:16
TotalSeconds             9248.0
HalfSeconds              4501.0
Name: 346, dtype: object
North Dartmouth
 Age                          37
M/F                           F
City            North Dartmouth
State                        MA
Country                     USA
Half            0 days 01:40:15
40K             0 days 03:17:48
Pace                    0:07:59
TotalSeconds            11868.0
HalfSeconds              6015.0
Name: 10827, dtype: object
North Delta
 Age                          56
M/F                           M
City                North Delta
State                        BC
Country                     CAN
Half            0 days 01:42:26
40K             0 days 03:32:55
Pace                    0:08:41
TotalSeconds            12775.0
HalfSeconds              6146.0
Name: 17903, dtype: object
North Dighton
 Age                          46
M/F                           F
City              North Dighton
State                        MA
Country                     USA
Half            0 days 02:22:00
40K             0 days 04:35:52
Pace                    0:11:08
TotalSeconds            16552.0
HalfSeconds              8520.0
Name: 30110, dtype: object
North East
 Age                          46
M/F                           F
City                 North East
State                        MD
Country                     USA
Half            0 days 01:43:27
40K             0 days 03:21:00
Pace                    0:08:07
TotalSeconds            12060.0
HalfSeconds              6207.0
Name: 19659, dtype: object
North Easton
 Age                          20
M/F                           M
City               North Easton
State                        MA
Country                     USA
Half            0 days 01:19:58
40K             0 days 02:37:12
Pace                    0:06:20
TotalSeconds             9432.0
HalfSeconds              4798.0
Name: 1989, dtype: object
North Falmouth
 Age                          54
M/F                           M
City             North Falmouth
State                        MA
Country                     USA
Half            0 days 02:09:49
40K             0 days 04:29:39
Pace                    0:10:57
TotalSeconds            16179.0
HalfSeconds              7789.0
Name: 28044, dtype: object
North Fort Lauderdale
 Age                                45
M/F                                 M
City            North Fort Lauderdale
State                              FL
Country                           USA
Half                  0 days 01:45:58
40K                   0 days 03:29:49
Pace                          0:08:33
TotalSeconds                  12589.0
HalfSeconds                    6358.0
Name: 8197, dtype: object
North Grafton
 Age                          22
M/F                           F
City              North Grafton
State                        MA
Country                     USA
Half            0 days 01:37:23
40K             0 days 03:14:05
Pace                    0:07:52
TotalSeconds            11645.0
HalfSeconds              5843.0
Name: 9534, dtype: object
North Granby
 Age                          45
M/F                           F
City               North Granby
State                        CT
Country                     USA
Half            0 days 02:23:34
40K             0 days 05:34:37
Pace                    0:13:41
TotalSeconds            20077.0
HalfSeconds              8614.0
Name: 27640, dtype: object
North Grosvenordale
 Age                              34
M/F                               M
City            North Grosvenordale
State                            CT
Country                         USA
Half                0 days 02:11:51
40K                 0 days 04:29:12
Pace                        0:10:51
TotalSeconds                16152.0
HalfSeconds                  7911.0
Name: 27558, dtype: object
North Hampton
 Age                          31
M/F                           M
City              North Hampton
State                        NH
Country                     USA
Half            0 days 01:29:48
40K             0 days 02:56:15
Pace                    0:07:08
TotalSeconds            10575.0
HalfSeconds              5388.0
Name: 3893, dtype: object
North Hero
 Age                          61
M/F                           F
City                 North Hero
State                        VT
Country                     USA
Half            0 days 02:09:45
40K             0 days 04:38:25
Pace                    0:11:19
TotalSeconds            16705.0
HalfSeconds              7785.0
Name: 28865, dtype: object
North Hills
 Age                          20
M/F                           M
City                North Hills
State                        CA
Country                     USA
Half            0 days 01:39:22
40K             0 days 03:32:37
Pace                    0:08:35
TotalSeconds            12757.0
HalfSeconds              5962.0
Name: 3020, dtype: object
North Hollywood
 Age                          31
M/F                           M
City            North Hollywood
State                        CA
Country                     USA
Half            0 days 01:27:33
40K             0 days 02:49:14
Pace                    0:06:49
TotalSeconds            10154.0
HalfSeconds              5253.0
Name: 3238, dtype: object
North Huntingdon
 Age                           27
M/F                            M
City            North Huntingdon
State                         PA
Country                      USA
Half             0 days 01:24:48
40K              0 days 02:57:16
Pace                     0:07:13
TotalSeconds             10636.0
HalfSeconds               5088.0
Name: 2010, dtype: object
North Kingstown
 Age                          59
M/F                           F
City            North Kingstown
State                        RI
Country                     USA
Half            0 days 01:54:33
40K             0 days 03:48:00
Pace                    0:09:13
TotalSeconds            13680.0
HalfSeconds              6873.0
Name: 24977, dtype: object
North Lancaster
 Age                          46
M/F                           M
City            North Lancaster
State                        ON
Country                     CAN
Half            0 days 01:39:47
40K             0 days 03:26:41
Pace                    0:08:24
TotalSeconds            12401.0
HalfSeconds              5987.0
Name: 11829, dtype: object
North Las Vegas
 Age                          48
M/F                           M
City            North Las Vegas
State                        NV
Country                     USA
Half            0 days 01:31:35
40K             0 days 02:58:08
Pace                    0:07:11
TotalSeconds            10688.0
HalfSeconds              5495.0
Name: 3770, dtype: object
North Lawrence
 Age                          50
M/F                           F
City             North Lawrence
State                        OH
Country                     USA
Half            0 days 01:58:51
40K             0 days 04:08:03
Pace                    0:10:03
TotalSeconds            14883.0
HalfSeconds              7131.0
Name: 25068, dtype: object
North Little Rock
 Age                            39
M/F                             M
City            North Little Rock
State                          AR
Country                       USA
Half              0 days 01:30:34
40K               0 days 03:05:04
Pace                      0:07:29
TotalSeconds              11104.0
HalfSeconds                5434.0
Name: 2377, dtype: object
North Logan
 Age                          34
M/F                           F
City                North Logan
State                        UT
Country                     USA
Half            0 days 01:44:36
40K             0 days 03:22:48
Pace                    0:08:11
TotalSeconds            12168.0
HalfSeconds              6276.0
Name: 9784, dtype: object
North Mankato
 Age                          58
M/F                           M
City              North Mankato
State                        MN
Country                     USA
Half            0 days 01:43:39
40K             0 days 03:20:22
Pace                    0:08:06
TotalSeconds            12022.0
HalfSeconds              6219.0
Name: 18430, dtype: object
North Oaks
 Age                          41
M/F                           M
City                 North Oaks
State                        MN
Country                     USA
Half            0 days 01:31:47
40K             0 days 03:13:56
Pace                    0:07:52
TotalSeconds            11636.0
HalfSeconds              5507.0
Name: 3164, dtype: object
North Olmsted
 Age                          40
M/F                           M
City              North Olmsted
State                        OH
Country                     USA
Half            0 days 01:33:38
40K             0 days 03:16:59
Pace                    0:07:58
TotalSeconds            11819.0
HalfSeconds              5618.0
Name: 7121, dtype: object
North Palm Beach
 Age                           55
M/F                            F
City            North Palm Beach
State                         FL
Country                      USA
Half             0 days 01:43:27
40K              0 days 03:26:02
Pace                     0:08:20
TotalSeconds             12362.0
HalfSeconds               6207.0
Name: 21025, dtype: object
North Pole
 Age                          39
M/F                           M
City                 North Pole
State                        AK
Country                     USA
Half            0 days 01:44:42
40K             0 days 03:28:55
Pace                    0:08:28
TotalSeconds            12535.0
HalfSeconds              6282.0
Name: 6881, dtype: object
North Potomac
 Age                          40
M/F                           M
City              North Potomac
State                        MD
Country                     USA
Half            0 days 01:35:59
40K             0 days 03:21:05
Pace                    0:08:09
TotalSeconds            12065.0
HalfSeconds              5759.0
Name: 8488, dtype: object
North Quincy
 Age                          50
M/F                           F
City               North Quincy
State                        MA
Country                     USA
Half            0 days 02:31:18
40K             0 days 05:10:52
Pace                    0:12:34
TotalSeconds            18652.0
HalfSeconds              9078.0
Name: 29412, dtype: object
North Reading
 Age                          39
M/F                           M
City              North Reading
State                        MA
Country                     USA
Half            0 days 01:28:57
40K             0 days 03:04:06
Pace                    0:07:34
TotalSeconds            11046.0
HalfSeconds              5337.0
Name: 1329, dtype: object
North Richland Hills
 Age                               48
M/F                                F
City            North Richland Hills
State                             TX
Country                          USA
Half                 0 days 01:44:57
40K                  0 days 03:23:58
Pace                         0:08:14
TotalSeconds                 12238.0
HalfSeconds                   6297.0
Name: 19972, dtype: object
North Ridgeville
 Age                           59
M/F                            M
City            North Ridgeville
State                         OH

 Age                          36
M/F                           F
City            North Waterboro
State                        ME
Country                     USA
Half            0 days 01:46:03
40K             0 days 03:28:40
Pace                    0:08:24
TotalSeconds            12520.0
HalfSeconds              6363.0
Name: 17347, dtype: object
North Windham
 Age                          46
M/F                           F
City              North Windham
State                        CT
Country                     USA
Half            0 days 01:45:30
40K             0 days 03:26:45
Pace                    0:08:21
TotalSeconds            12405.0
HalfSeconds              6330.0
Name: 16809, dtype: object
North Woodstock
 Age                          47
M/F                           M
City            North Woodstock
State                        NH
Country                     USA
Half            0 days 01:44:54
40K             0 days 03:28:21
Pace                    0:08:25
TotalSeconds            12501.0
HalfSeconds              6294.0
Name: 12769, dtype: object
North Yarmouth
 Age                          41
M/F                           F
City             North Yarmouth
State                        ME
Country                     USA
Half            0 days 01:25:15
40K             0 days 02:47:55
Pace                    0:06:47
TotalSeconds            10075.0
HalfSeconds              5115.0
Name: F111, dtype: object
North York
 Age                          30
M/F                           F
City                 North York
State                        ON
Country                     CAN
Half            0 days 01:30:35
40K             0 days 02:59:35
Pace                    0:07:16
TotalSeconds            10775.0
HalfSeconds              5435.0
Name: 10470, dtype: object
North Yorkshire
 Age                          57
M/F                           M
City            North Yorkshire
State                       NaN
Country                     GBR
Half            0 days 01:57:24
40K             0 days 04:04:31
Pace                    0:09:52
TotalSeconds            14671.0
HalfSeconds              7044.0
Name: 31498, dtype: object
Northampton
 Age                          29
M/F                           M
City                Northampton
State                        MA
Country                     USA
Half            0 days 01:28:34
40K             0 days 02:50:44
Pace                    0:06:53
TotalSeconds            10244.0
HalfSeconds              5314.0
Name: 4739, dtype: object
Northboro
 Age                          23
M/F                           F
City                  Northboro
State                        MA
Country                     USA
Half            0 days 01:51:35
40K             0 days 03:34:38
Pace                    0:08:38
TotalSeconds            12878.0
HalfSeconds              6695.0
Name: 28495, dtype: object
Northborough
 Age                          38
M/F                           M
City               Northborough
State                        MA
Country                     USA
Half            0 days 01:25:27
40K             0 days 02:44:47
Pace                    0:06:39
TotalSeconds             9887.0
HalfSeconds              5127.0
Name: 1608, dtype: object
Northbridge
 Age                          58
M/F                           M
City                Northbridge
State                        MA
Country                     USA
Half            0 days 01:35:37
40K             0 days 03:13:01
Pace                    0:07:49
TotalSeconds            11581.0
HalfSeconds              5737.0
Name: 9607, dtype: object
Northbrook
 Age                          46
M/F                           M
City                 Northbrook
State                        IL
Country                     USA
Half            0 days 01:40:41
40K             0 days 03:14:01
Pace                    0:07:48
TotalSeconds            11641.0
HalfSeconds              6041.0
Name: 10274, dtype: object
Northern Ireland
 Age                           33
M/F                            F
City            Northern Ireland
State                        NaN
Country                      GBR
Half             0 days 01:39:04
40K              0 days 03:12:29
Pace                     0:07:45
TotalSeconds             11549.0
HalfSeconds               5944.0
Name: 12015, dtype: object
Northfield
 Age                          61
M/F                           M
City                 Northfield
State                        MN
Country                     USA
Half            0 days 01:50:46
40K             0 days 00:00:00
Pace                    0:08:54
TotalSeconds                0.0
HalfSeconds              6646.0
Name: 20906, dtype: object
Northlake
 Age                          65
M/F                           M
City                  Northlake
State                        IL
Country                     USA
Half            0 days 02:01:12
40K             0 days 04:24:50
Pace                    0:10:43
TotalSeconds            15890.0
HalfSeconds              7272.0
Name: 24601, dtype: object
Northport
 Age                          58
M/F                           M
City                  Northport
State                        NY
Country                     USA
Half            0 days 01:37:55
40K             0 days 03:25:14
Pace                    0:08:19
TotalSeconds            12314.0
HalfSeconds              5875.0
Name: 11276, dtype: object
Northriding
 Age                          48
M/F                           M
City                Northriding
State                       NaN
Country                     RSA
Half            0 days 01:42:33
40K             0 days 03:23:37
Pace                    0:08:16
TotalSeconds            12217.0
HalfSeconds              6153.0
Name: 11437, dtype: object
Northumberland
 Age                          63
M/F                           M
City             Northumberland
State                        PA
Country                     USA
Half            0 days 01:42:37
40K             0 days 03:24:40
Pace                    0:08:16
TotalSeconds            12280.0
HalfSeconds              6157.0
Name: 8840, dtype: object
Northville
 Age                          43
M/F                           M
City                 Northville
State                        MI
Country                     USA
Half            0 days 01:33:34
40K             0 days 03:00:51
Pace                    0:07:19
TotalSeconds            10851.0
HalfSeconds              5614.0
Name: 8149, dtype: object
Northwood
 Age                          47
M/F                           M
City                  Northwood
State                        NH
Country                     USA
Half            0 days 01:44:01
40K             0 days 03:25:22
Pace                    0:08:18
TotalSeconds            12322.0
HalfSeconds              6241.0
Name: 9337, dtype: object
Northyork
 Age                          49
M/F                           F
City                  Northyork
State                        ON
Country                     CAN
Half            0 days 01:58:00
40K             0 days 03:47:56
Pace                    0:09:09
TotalSeconds            13676.0
HalfSeconds              7080.0
Name: 17845, dtype: object
Norton
 Age                          55
M/F                           M
City                     Norton
State                        OH
Country                     USA
Half            0 days 01:38:39
40K             0 days 03:32:13
Pace                    0:08:34
TotalSeconds            12733.0
HalfSeconds              5919.0
Name: 10622, dtype: object
Norton Shores
 Age                          49
M/F                           M
City              Norton Shores
State                        MI
Country                     USA
Half            0 days 01:34:16
40K             0 days 03:01:33
Pace                    0:07:20
TotalSeconds            10893.0
HalfSeconds              5656.0
Name: 8402, dtype: object
Norwalk
 Age                          46
M/F                           M
City                    Norwalk
State                        CT
Country                     USA
Half            0 days 01:37:37
40K             0 days 03:12:18
Pace                    0:07:45
TotalSeconds            11538.0
HalfSeconds              5857.0
Name: 10762, dtype: object
Norwell
 Age                          40
M/F                           M
City                    Norwell
State                        MA
Country                     USA
Half            0 days 01:33:09
40K             0 days 03:11:02
Pace                    0:07:44
TotalSeconds            11462.0
HalfSeconds              5589.0
Name: 3028, dtype: object
Norwich
 Age                          42
M/F                           F
City                    Norwich
State                        VT
Country                     USA
Half            0 days 01:46:34
40K             0 days 03:29:57
Pace                    0:08:29
TotalSeconds            12597.0
HalfSeconds              6394.0
Name: 19320, dtype: object
Norwood
 Age                          42
M/F                           M
City                    Norwood
State                        MA
Country                     USA
Half            0 days 01:34:07
40K             0 days 03:01:39
Pace                    0:07:21
TotalSeconds            10899.0
HalfSeconds              5647.0
Name: 5791, dtype: object
Notre-Dame-De-L'Ile-Perrot
 Age                                     47
M/F                                      M
City            Notre-Dame-De-L'Ile-Perrot
State                                   QC
Country                                CAN
Half                       0 days 01:37:08
40K                        0 days 03:10:52
Pace                               0:07:41
TotalSeconds                       11452.0
HalfSeconds                         5828.0
Name: 9472, dtype: object
Nottingham
 Age                          41
M/F                           M
City                 Nottingham
State                       NaN
Country                     GBR
Half            0 days 01:32:12
40K             0 days 03:02:01
Pace                    0:07:21
TotalSeconds            10921.0
HalfSeconds              5532.0
Name: 3079, dtype: object
Nottinghamshire
 Age                          52
M/F                           M
City            Nottinghamshire
State                       NaN
Country                     GBR
Half            0 days 01:29:49
40K             0 days 03:05:27
Pace                    0:07:35
TotalSeconds            11127.0
HalfSeconds              5389.0
Name: 5515, dtype: object
Novato
 Age                          26
M/F                           F
City                     Novato
State                        CA
Country                     USA
Half            0 days 01:35:05
40K             0 days 03:10:54
Pace                    0:07:41
TotalSeconds            11454.0
HalfSeconds              5705.0
Name: 9458, dtype: object
Novi
 Age                          27
M/F                           M
City                       Novi
State                        MI
Country                     USA
Half            0 days 01:27:16
40K             0 days 02:49:42
Pace                    0:06:51
TotalSeconds            10182.0
HalfSeconds              5236.0
Name: 1812, dtype: object
Nsw
 Age                          39
M/F                           M
City                        Nsw
State                       NaN
Country                     AUS
Half            0 days 01:26:02
40K             0 days 03:01:21
Pace                    0:07:23
TotalSeconds            10881.0
HalfSeconds              5162.0
Name: 3593, dtype: object
Nt
 Age                          50
M/F                           M
City                         Nt
State                       NaN
Country                     HKG
Half            0 days 01:31:52
40K             0 days 03:02:39
Pace                    0:07:23
TotalSeconds            10959.0
HalfSeconds              5512.0
Name: 5729, dtype: object
Nuernberg
 Age                          54
M/F                           M
City                  Nuernberg
State                       NaN
Country                     GER
Half            0 days 02:11:33
40K             0 days 04:21:07
Pace                    0:10:31
TotalSeconds            15667.0
HalfSeconds              7893.0
Name: 30837, dtype: object
Nunawading
 Age                          33
M/F                           M
City                 Nunawading
State                       NaN
Country                     AUS
Half            0 days 01:29:40
40K             0 days 03:04:23
Pace                    0:07:32
TotalSeconds            11063.0
HalfSeconds              5380.0
Name: 2033, dtype: object
Nuremberg
 Age                          42
M/F                           M
City                  Nuremberg
State                       NaN
Country                     GER
Half            0 days 01:33:10
40K             0 days 03:13:56
Pace                    0:07:52
TotalSeconds            11636.0
HalfSeconds              5590.0
Name: 2547, dtype: object
Nutley
 Age                          47
M/F                           F
City                     Nutley
State                        NJ
Country                     USA
Half            0 days 01:46:53
40K             0 days 03:51:32
Pace                    0:09:24
TotalSeconds            13892.0
HalfSeconds              6413.0
Name: 23048, dtype: object
Ny
 Age                          47
M/F                           M
City                         Ny
State                        NY
Country                     USA
Half            0 days 01:40:22
40K             0 days 03:30:32
Pace                    0:08:33
TotalSeconds            12632.0
HalfSeconds              6022.0
Name: 12493, dtype: object
Nynashamn
 Age                          54
M/F                           F
City                  Nynashamn
State                       NaN
Country                     SWE
Half            0 days 02:24:01
40K             0 days 04:54:21
Pace                    0:11:51
TotalSeconds            17661.0
HalfSeconds              8641.0
Name: 31470, dtype: object
Nyon
 Age                          51
M/F                           M
City                       Nyon
State                       NaN
Country                     SUI
Half            0 days 01:42:37
40K             0 days 03:32:27
Pace                    0:08:39
TotalSeconds            12747.0
HalfSeconds              6157.0
Name: 14597, dtype: object
O'Fallon
 Age                          39
M/F                           M
City                   O'Fallon
State                        IL
Country                     USA
Half            0 days 01:28:37
40K             0 days 02:59:55
Pace                    0:07:20
TotalSeconds            10795.0
HalfSeconds              5317.0
Name: 3921, dtype: object
Oak Bluffs
 Age                          29
M/F                           M
City                 Oak Bluffs
State                        MA
Country                     USA
Half            0 days 01:27:26
40K             0 days 03:21:38
Pace                    0:08:09
TotalSeconds            12098.0
HalfSeconds              5246.0
Name: 1098, dtype: object
Oak Creek
 Age                          28
M/F                           F
City                  Oak Creek
State                        WI
Country                     USA
Half            0 days 01:46:51
40K             0 days 03:27:01
Pace                    0:08:20
TotalSeconds            12421.0
HalfSeconds              6411.0
Name: 15514, dtype: object
Oak Forest
 Age                          50
M/F                           M
City                 Oak Forest
State                        IL
Country                     USA
Half            0 days 01:30:36
40K             0 days 02:53:48
Pace                    0:07:00
TotalSeconds            10428.0
HalfSeconds              5436.0
Name: 9062, dtype: object
Oak Harbor
 Age                          50
M/F                           M
City                 Oak Harbor
State                        WA
Country                     USA
Half            0 days 01:48:10
40K             0 days 03:53:44
Pace                    0:09:29
TotalSeconds            14024.0
HalfSeconds              6490.0
Name: 4471, dtype: object
Oak Hill
 Age                          36
M/F                           M
City                   Oak Hill
State                        VA
Country                     USA
Half            0 days 01:34:23
40K             0 days 03:23:27
Pace                    0:08:13
TotalSeconds            12207.0
HalfSeconds              5663.0
Name: 5756, dtype: object
Oak Lawn
 Age                          29
M/F                           M
City                   Oak Lawn
State                        IL
Country                     USA
Half            0 days 01:15:29
40K             0 days 02:34:23
Pace                    0:06:17
TotalSeconds             9263.0
HalfSeconds              4529.0
Name: 337, dtype: object
Oak Park
 Age                          41
M/F                           M
City                   Oak Park
State                        IL
Country                     USA
Half            0 days 01:26:29
40K             0 days 02:48:57
Pace                    0:06:49
TotalSeconds            10137.0
HalfSeconds              5189.0
Name: 3305, dtype: object
Oak Ridge
 Age                          56
M/F                           F
City                  Oak Ridge
State                        NC
Country                     USA
Half            0 days 01:52:06
40K             0 days 03:40:25
Pace                    0:08:54
TotalSeconds            13225.0
HalfSeconds              6726.0
Name: 22338, dtype: object
Oak Run
 Age                          55
M/F                           M
City                    Oak Run
State                        CA
Country                     USA
Half            0 days 01:43:31
40K             0 days 03:47:28
Pace                    0:09:12
TotalSeconds            13648.0
HalfSeconds              6211.0
Name: 12435, dtype: object
Oakdale
 Age                          44
M/F                           M
City                    Oakdale
State                        CA
Country                     USA
Half            0 days 01:26:37
40K             0 days 02:47:08
Pace                    0:06:44
TotalSeconds            10028.0
HalfSeconds              5197.0
Name: 2991, dtype: object
Oakfield
 Age                          37
M/F                           M
City                   Oakfield
State                        NS
Country                     CAN
Half            0 days 01:22:57
40K             0 days 02:42:42
Pace                    0:06:35
TotalSeconds             9762.0
HalfSeconds              4977.0
Name: 1192, dtype: object
Oakham
 Age                          41
M/F                           F
City                     Oakham
State                       NaN
Country                     GBR
Half            0 days 01:52:21
40K             0 days 03:41:23
Pace                    0:08:57
TotalSeconds            13283.0
HalfSeconds              6741.0
Name: 21604, dtype: object
Oakhurst
 Age                          41
M/F                           M
City                   Oakhurst
State                        NJ
Country                     USA
Half            0 days 01:31:18
40K             0 days 02:59:10
Pace                    0:07:14
TotalSeconds            10750.0
HalfSeconds              5478.0
Name: 4922, dtype: object
Oakland
 Age                          32
M/F                           M
City                    Oakland
State                        CA
Country                     USA
Half            0 days 01:22:01
40K             0 days 02:36:44
Pace                    0:06:19
TotalSeconds             9404.0
HalfSeconds              4921.0
Name: 1792, dtype: object
Oakland Park
 Age                          50
M/F                           M
City               Oakland Park
State                        FL
Country                     USA
Half            0 days 01:58:41

Okayama
 Age                          43
M/F                           F
City                    Okayama
State                       NaN
Country                     JPN
Half            0 days 01:51:08
40K             0 days 03:41:26
Pace                    0:08:55
TotalSeconds            13286.0
HalfSeconds              6668.0
Name: 20983, dtype: object
Okemos
 Age                          45
M/F                           M
City                     Okemos
State                        MI
Country                     USA
Half            0 days 01:34:26
40K             0 days 03:10:28
Pace                    0:07:42
TotalSeconds            11428.0
HalfSeconds              5666.0
Name: 8856, dtype: object
Oklahoma City
 Age                          26
M/F                           M
City              Oklahoma City
State                        OK
Country                     USA
Half            0 days 01:17:46
40K             0 days 02:33:44
Pace                    0:06:13
TotalSeconds             9224.0
HalfSeconds              4666.0
Name: 709, dtype: object
Olathe
 Age                          34
M/F                           M
City                     Olathe
State                        KS
Country                     USA
Half            0 days 01:22:37
40K             0 days 02:42:14
Pace                    0:06:35
TotalSeconds             9734.0
HalfSeconds              4957.0
Name: 1717, dtype: object
Olbernhau
 Age                          53
M/F                           M
City                  Olbernhau
State                       NaN
Country                     GER
Half            0 days 02:18:53
40K             0 days 04:29:42
Pace                    0:10:52
TotalSeconds            16182.0
HalfSeconds              8333.0
Name: 31865, dtype: object
Olbia - Sassari
 Age                          40
M/F                           M
City            Olbia - Sassari
State                       NaN
Country                     ITA
Half            0 days 01:46:57
40K             0 days 03:45:44
Pace                    0:09:09
TotalSeconds            13544.0
HalfSeconds              6417.0
Name: 31521, dtype: object
Old Bridge
 Age                          49
M/F                           M
City                 Old Bridge
State                        NJ
Country                     USA
Half            0 days 01:47:48
40K             0 days 03:49:36
Pace                    0:09:16
TotalSeconds            13776.0
HalfSeconds              6468.0
Name: 7235, dtype: object
Old Forge
 Age                          46
M/F                           M
City                  Old Forge
State                        PA
Country                     USA
Half            0 days 01:36:35
40K             0 days 03:08:18
Pace                    0:07:41
TotalSeconds            11298.0
HalfSeconds              5795.0
Name: 9639, dtype: object
Old Greenwich
 Age                          46
M/F                           M
City              Old Greenwich
State                        CT
Country                     USA
Half            0 days 01:43:40
40K             0 days 03:18:40
Pace                    0:08:03
TotalSeconds            11920.0
HalfSeconds              6220.0
Name: 10711, dtype: object
Old Hickory
 Age                          47
M/F                           M
City                Old Hickory
State                        TN
Country                     USA
Half            0 days 01:40:32
40K             0 days 03:36:23
Pace                    0:08:46
TotalSeconds            12983.0
HalfSeconds              6032.0
Name: 9024, dtype: object
Old Lyme
 Age                          46
M/F                           F
City                   Old Lyme
State                        CT
Country                     USA
Half            0 days 01:43:09
40K             0 days 03:22:42
Pace                    0:08:12
TotalSeconds            12162.0
HalfSeconds              6189.0
Name: 17725, dtype: object
Old Orchard Beach
 Age                            46
M/F                             M
City            Old Orchard Beach
State                          ME
Country                       USA
Half              0 days 01:47:47
40K               0 days 03:43:48
Pace                      0:09:14
TotalSeconds              13428.0
HalfSeconds                6467.0
Name: 9796, dtype: object
Old Saybrook
 Age                          49
M/F                           F
City               Old Saybrook
State                        CT
Country                     USA
Half            0 days 01:49:53
40K             0 days 03:45:36
Pace                    0:09:08
TotalSeconds            13536.0
HalfSeconds              6593.0
Name: 24298, dtype: object
Old Tappan
 Age                          36
M/F                           M
City                 Old Tappan
State                        NJ
Country                     USA
Half            0 days 01:34:06
40K             0 days 03:08:55
Pace                    0:07:38
TotalSeconds            11335.0
HalfSeconds              5646.0
Name: 6646, dtype: object
Old Town
 Age                          62
M/F                           M
City                   Old Town
State                        ME
Country                     USA
Half            0 days 01:44:36
40K             0 days 03:25:49
Pace                    0:08:18
TotalSeconds            12349.0
HalfSeconds              6276.0
Name: 12816, dtype: object
Old Westbury
 Age                          57
M/F                           M
City               Old Westbury
State                        NY
Country                     USA
Half            0 days 01:51:53
40K             0 days 03:56:43
Pace                    0:09:41
TotalSeconds            14203.0
HalfSeconds              6713.0
Name: 14760, dtype: object
Olgod
 Age                          47
M/F                           M
City                      Olgod
State                       NaN
Country                     DEN
Half            0 days 01:35:14
40K             0 days 03:22:59
Pace                    0:08:13
TotalSeconds            12179.0
HalfSeconds              5714.0
Name: 8570, dtype: object
Olive Branch
 Age                          33
M/F                           F
City               Olive Branch
State                        MS
Country                     USA
Half            0 days 02:22:19
40K             0 days 06:04:38
Pace                    0:14:42
TotalSeconds            21878.0
HalfSeconds              8539.0
Name: 16021, dtype: object
Olivette
 Age                          46
M/F                           F
City                   Olivette
State                        MO
Country                     USA
Half            0 days 01:51:47
40K             0 days 03:45:27
Pace                    0:09:08
TotalSeconds            13527.0
HalfSeconds              6707.0
Name: 21734, dtype: object
Olmsted Falls
 Age                          45
M/F                           M
City              Olmsted Falls
State                        OH
Country                     USA
Half            0 days 01:56:02
40K             0 days 04:34:30
Pace                    0:11:02
TotalSeconds            16470.0
HalfSeconds              6962.0
Name: 1485, dtype: object
Olmsted Township
 Age                           46
M/F                            M
City            Olmsted Township
State                         OH
Country                      USA
Half             0 days 01:34:20
40K              0 days 03:12:15
Pace                     0:07:49
TotalSeconds             11535.0
HalfSeconds               5660.0
Name: 9558, dtype: object
Olmsted Twp
 Age                          43
M/F                           M
City                Olmsted Twp
State                        OH
Country                     USA
Half            0 days 01:35:54
40K             0 days 03:05:14
Pace                    0:07:29
TotalSeconds            11114.0
HalfSeconds              5754.0
Name: 4142, dtype: object
Olney
 Age                          42
M/F                           F
City                      Olney
State                        MD
Country                     USA
Half            0 days 01:36:40
40K             0 days 03:04:37
Pace                    0:07:26
TotalSeconds            11077.0
HalfSeconds              5800.0
Name: 3963, dtype: object
Olomouc
 Age                          33
M/F                           M
City                    Olomouc
State                       NaN
Country                     CZE
Half            0 days 01:21:35
40K             0 days 02:40:59
Pace                    0:06:31
TotalSeconds             9659.0
HalfSeconds              4895.0
Name: 1158, dtype: object
Olympia
 Age                          44
M/F                           M
City                    Olympia
State                        WA
Country                     USA
Half            0 days 01:36:48
40K             0 days 03:15:54
Pace                    0:07:58
TotalSeconds            11754.0
HalfSeconds              5808.0
Name: 8421, dtype: object
Olyphant
 Age                          42
M/F                           F
City                   Olyphant
State                        PA
Country                     USA
Half            0 days 02:04:11
40K             0 days 04:17:10
Pace                    0:10:19
TotalSeconds            15430.0
HalfSeconds              7451.0
Name: 19801, dtype: object
Omaha
 Age                          28
M/F                           M
City                      Omaha
State                        NE
Country                     USA
Half            0 days 01:15:19
40K             0 days 02:31:03
Pace                    0:06:06
TotalSeconds             9063.0
HalfSeconds              4519.0
Name: 161, dtype: object
Omsk
 Age                          43
M/F                           M
City                       Omsk
State                       NaN
Country                     RUS
Half            0 days 01:32:50
40K             0 days 03:05:18
Pace                    0:07:27
TotalSeconds            11118.0
HalfSeconds              5570.0
Name: 6951, dtype: object
Onalaska
 Age                          59
M/F                           M
City                   Onalaska
State                        WI
Country                     USA
Half            0 days 01:50:32
40K             0 days 03:27:11
Pace                    0:08:19
TotalSeconds            12431.0
HalfSeconds              6632.0
Name: 16650, dtype: object
Onda (Castellon)
 Age                           55
M/F                            M
City            Onda (Castellon)
State                        NaN
Country                      ESP
Half             0 days 02:04:15
40K              0 days 04:05:12
Pace                     0:09:55
TotalSeconds             14712.0
HalfSeconds               7455.0
Name: 31675, dtype: object
Oneida
 Age                          42
M/F                           F
City                     Oneida
State                        WI
Country                     USA
Half            0 days 01:51:10
40K             0 days 03:32:51
Pace                    0:08:34
TotalSeconds            12771.0
HalfSeconds              6670.0
Name: 21775, dtype: object
Onekama
 Age                          38
M/F                           M
City                    Onekama
State                        MI
Country                     USA
Half            0 days 01:28:23
40K             0 days 02:56:42
Pace                    0:07:09
TotalSeconds            10602.0
HalfSeconds              5303.0
Name: 3072, dtype: object
Onsted
 Age                          59
M/F                           F
City                     Onsted
State                        MI
Country                     USA
Half            0 days 02:13:14
40K             0 days 04:28:01
Pace                    0:10:46
TotalSeconds            16081.0
HalfSeconds              7994.0
Name: 25470, dtype: object
Ontario
 Age                          46
M/F                           F
City                    Ontario
State                        NY
Country                     USA
Half            0 days 01:55:00
40K             0 days 03:38:21
Pace                    0:08:46
TotalSeconds            13101.0
HalfSeconds              6900.0
Name: 23299, dtype: object
Ooltewah
 Age                          46
M/F                           M
City                   Ooltewah
State                        TN
Country                     USA
Half            0 days 01:31:00
40K             0 days 02:57:46
Pace                    0:07:12
TotalSeconds            10666.0
HalfSeconds              5460.0
Name: 4699, dtype: object
Oosaka
 Age                          49
M/F                           M
City                     Oosaka
State                       NaN
Country                     JPN
Half            0 days 01:42:29
40K             0 days 03:44:06
Pace                    0:09:06
TotalSeconds            13446.0
HalfSeconds              6149.0
Name: 10295, dtype: object
Opelika
 Age                          40
M/F                           M
City                    Opelika
State                        AL
Country                     USA
Half            0 days 02:00:24
40K             0 days 03:48:43
Pace                    0:09:11
TotalSeconds            13723.0
HalfSeconds              7224.0
Name: 29741, dtype: object
Opelousas
 Age                          35
M/F                           F
City                  Opelousas
State                        LA
Country                     USA
Half            0 days 01:56:30
40K             0 days 04:03:59
Pace                    0:09:51
TotalSeconds            14639.0
HalfSeconds              6990.0
Name: 17565, dtype: object
Oppaker
 Age                          42
M/F                           M
City                    Oppaker
State                       NaN
Country                     NOR
Half            0 days 01:35:15
40K             0 days 03:12:00
Pace                    0:07:47
TotalSeconds            11520.0
HalfSeconds              5715.0
Name: 6568, dtype: object
Oradell
 Age                          35
M/F                           F
City                    Oradell
State                        NJ
Country                     USA
Half            0 days 01:43:17
40K             0 days 03:24:05
Pace                    0:08:18
TotalSeconds            12245.0
HalfSeconds              6197.0
Name: 15064, dtype: object
Orange
 Age                          31
M/F                           M
City                     Orange
State                        CA
Country                     USA
Half            0 days 01:19:53
40K             0 days 02:35:01
Pace                    0:06:16
TotalSeconds             9301.0
HalfSeconds              4793.0
Name: 1317, dtype: object
Orange City
 Age                          46
M/F                           M
City                Orange City
State                        FL
Country                     USA
Half            0 days 01:39:34
40K             0 days 03:31:58
Pace                    0:08:32
TotalSeconds            12718.0
HalfSeconds              5974.0
Name: 10745, dtype: object
Orange Park
 Age                          30
M/F                           F
City                Orange Park
State                        FL
Country                     USA
Half            0 days 01:47:58
40K             0 days 03:38:22
Pace                    0:08:50
TotalSeconds            13102.0
HalfSeconds              6478.0
Name: 13480, dtype: object
Orangeburg
 Age                          47
M/F                           M
City                 Orangeburg
State                        NY
Country                     USA
Half            0 days 01:52:51
40K             0 days 04:03:06
Pace                    0:09:57
TotalSeconds            14586.0
HalfSeconds              6771.0
Name: 12565, dtype: object
Orangevale
 Age                          34
M/F                           F
City                 Orangevale
State                        CA
Country                     USA
Half            0 days 01:48:11
40K             0 days 03:32:39
Pace                    0:08:33
TotalSeconds            12759.0
HalfSeconds              6491.0
Name: 16950, dtype: object
Orangeville
 Age                          46
M/F                           F
City                Orangeville
State                        ON
Country                     CAN
Half            0 days 02:02:42
40K             0 days 04:06:54
Pace                    0:09:57
TotalSeconds            14814.0
HalfSeconds              7362.0
Name: 22484, dtype: object
Oranienburg
 Age                          58
M/F                           M
City                Oranienburg
State                       NaN
Country                     GER
Half            0 days 02:06:15
40K             0 days 04:39:40
Pace                    0:11:22
TotalSeconds            16780.0
HalfSeconds              7575.0
Name: 31870, dtype: object
Orchard Lake
 Age                          59
M/F                           M
City               Orchard Lake
State                        MI
Country                     USA
Half            0 days 01:27:06
40K             0 days 02:51:03
Pace                    0:06:54
TotalSeconds            10263.0
HalfSeconds              5226.0
Name: 1847, dtype: object
Orchard Park
 Age                          28
M/F                           F
City               Orchard Park
State                        NY
Country                     USA
Half            0 days 01:38:47
40K             0 days 03:11:07
Pace                    0:07:42
TotalSeconds            11467.0
HalfSeconds              5927.0
Name: 11782, dtype: object
Oregon
 Age                          45
M/F                           F
City                     Oregon
State                        WI
Country                     USA
Half            0 days 01:55:12
40K             0 days 03:50:04
Pace                    0:09:22
TotalSeconds            13804.0
HalfSeconds              6912.0
Name: 22688, dtype: object
Oreland
 Age                          61
M/F                           M
City                    Oreland
State                        PA
Country                     USA
Half            0 days 01:56:29
40K             0 days 03:46:57
Pace                    0:09:12
TotalSeconds            13617.0
HalfSeconds              6989.0
Name: 24328, dtype: object
Orem
 Age                          30
M/F                           M
City                       Orem
State                        UT
Country                     USA
Half            0 days 01:34:40
40K             0 days 03:17:07
Pace                    0:08:08
TotalSeconds            11827.0
HalfSeconds              5680.0
Name: 863, dtype: object
Orford
 Age                          64
M/F                           M
City                     Orford
State                        QC
Country                     CAN
Half            0 days 02:03:48
40K             0 days 03:59:32
Pace                    0:09:39
TotalSeconds            14372.0
HalfSeconds              7428.0
Name: 21960, dtype: object
Orillia
 Age                          60
M/F                           F
City                    Orillia
State                        ON
Country                     CAN
Half            0 days 01:43:03
40K             0 days 03:23:17
Pace                    0:08:13
TotalSeconds            12197.0
HalfSeconds              6183.0
Name: 12879, dtype: object
Orinda
 Age                          21
M/F                           M
City                     Orinda
State                        CA
Country                     USA
Half            0 days 01:19:14
40K             0 days 02:45:09
Pace                    0:06:41
TotalSeconds             9909.0
HalfSeconds              4754.0
Name: 393, dtype: object
Oriskany
 Age                          47
M/F                           M
City                   Oriskany
State                        NY
Country                     USA
Half            0 days 01:32:14
40K             0 days 03:03:59
Pace                    0:07:27
TotalSeconds            11039.0

Ottawa
 Age                          31
M/F                           M
City                     Ottawa
State                        ON
Country                     CAN
Half            0 days 01:16:36
40K             0 days 02:34:01
Pace                    0:06:13
TotalSeconds             9241.0
HalfSeconds              4596.0
Name: 722, dtype: object
Ottawa Hills
 Age                          47
M/F                           F
City               Ottawa Hills
State                        OH
Country                     USA
Half            0 days 01:47:17
40K             0 days 03:28:43
Pace                    0:08:27
TotalSeconds            12523.0
HalfSeconds              6437.0
Name: 18179, dtype: object
Ottawa Lake
 Age                          50
M/F                           M
City                Ottawa Lake
State                        MI
Country                     USA
Half            0 days 01:51:36
40K             0 days 04:21:55
Pace                    0:10:35
TotalSeconds            15715.0
HalfSeconds              6696.0
Name: 11115, dtype: object
Ottawa Ontario
 Age                          52
M/F                           M
City             Ottawa Ontario
State                        ON
Country                     CAN
Half            0 days 01:43:24
40K             0 days 03:22:16
Pace                    0:08:11
TotalSeconds            12136.0
HalfSeconds              6204.0
Name: 12681, dtype: object
Otterburn Park
 Age                          36
M/F                           M
City             Otterburn Park
State                        QC
Country                     CAN
Half            0 days 01:34:44
40K             0 days 03:25:23
Pace                    0:08:20
TotalSeconds            12323.0
HalfSeconds              5684.0
Name: 5761, dtype: object
Oume
 Age                          62
M/F                           M
City                       Oume
State                       NaN
Country                     JPN
Half            0 days 01:53:23
40K             0 days 03:51:22
Pace                    0:09:25
TotalSeconds            13882.0
HalfSeconds              6803.0
Name: 23119, dtype: object
Outremont
 Age                          27
M/F                           F
City                  Outremont
State                        QC
Country                     CAN
Half            0 days 01:41:10
40K             0 days 03:18:46
Pace                    0:08:03
TotalSeconds            11926.0
HalfSeconds              6070.0
Name: 17559, dtype: object
Overland Park
 Age                          25
M/F                           M
City              Overland Park
State                        KS
Country                     USA
Half            0 days 01:19:26
40K             0 days 02:51:20
Pace                    0:06:57
TotalSeconds            10280.0
HalfSeconds              4766.0
Name: 1339, dtype: object
Oviedo
 Age                          34
M/F                           M
City                     Oviedo
State                        FL
Country                     USA
Half            0 days 01:25:24
40K             0 days 02:52:19
Pace                    0:07:00
TotalSeconds            10339.0
HalfSeconds              5124.0
Name: 1419, dtype: object
Owasso
 Age                          29
M/F                           F
City                     Owasso
State                        OK
Country                     USA
Half            0 days 02:32:46
40K             0 days 05:18:15
Pace                    0:12:48
TotalSeconds            19095.0
HalfSeconds              9166.0
Name: 30175, dtype: object
Owatonna
 Age                          45
M/F                           M
City                   Owatonna
State                        MN
Country                     USA
Half            0 days 01:33:51
40K             0 days 03:06:53
Pace                    0:07:34
TotalSeconds            11213.0
HalfSeconds              5631.0
Name: 3622, dtype: object
Owens Cross Roads
 Age                            42
M/F                             F
City            Owens Cross Roads
State                          AL
Country                       USA
Half              0 days 01:48:42
40K               0 days 03:31:02
Pace                      0:08:31
TotalSeconds              12662.0
HalfSeconds                6522.0
Name: 19799, dtype: object
Owensboro
 Age                          45
M/F                           M
City                  Owensboro
State                        KY
Country                     USA
Half            0 days 01:41:23
40K             0 days 03:17:29
Pace                    0:07:55
TotalSeconds            11849.0
HalfSeconds              6083.0
Name: 7291, dtype: object
Owings Mills
 Age                          57
M/F                           M
City               Owings Mills
State                        MD
Country                     USA
Half            0 days 02:06:34
40K             0 days 04:22:08
Pace                    0:10:35
TotalSeconds            15728.0
HalfSeconds              7594.0
Name: 29355, dtype: object
Owosso
 Age                          37
M/F                           F
City                     Owosso
State                        MI
Country                     USA
Half            0 days 01:39:02
40K             0 days 03:13:01
Pace                    0:07:47
TotalSeconds            11581.0
HalfSeconds              5942.0
Name: 15088, dtype: object
Oxford
 Age                          41
M/F                           M
City                     Oxford
State                        MS
Country                     USA
Half            0 days 01:33:03
40K             0 days 02:57:19
Pace                    0:07:10
TotalSeconds            10639.0
HalfSeconds              5583.0
Name: 7238, dtype: object
Oxnard
 Age                          34
M/F                           M
City                     Oxnard
State                        CA
Country                     USA
Half            0 days 01:31:01
40K             0 days 03:00:59
Pace                    0:07:19
TotalSeconds            10859.0
HalfSeconds              5461.0
Name: 4918, dtype: object
Oyama, Tochigi
 Age                          51
M/F                           M
City             Oyama, Tochigi
State                       NaN
Country                     JPN
Half            0 days 01:28:44
40K             0 days 02:56:18
Pace                    0:07:09
TotalSeconds            10578.0
HalfSeconds              5324.0
Name: 4496, dtype: object
Oyster Bay
 Age                          37
M/F                           F
City                 Oyster Bay
State                        NY
Country                     USA
Half            0 days 01:52:51
40K             0 days 03:59:52
Pace                    0:09:42
TotalSeconds            14392.0
HalfSeconds              6771.0
Name: 18653, dtype: object
Oyster Bed Bridge
 Age                            28
M/F                             M
City            Oyster Bed Bridge
State                          PE
Country                       CAN
Half              0 days 01:32:49
40K               0 days 03:22:03
Pace                      0:08:11
TotalSeconds              12123.0
HalfSeconds                5569.0
Name: 3418, dtype: object
Ozark
 Age                          37
M/F                           F
City                      Ozark
State                        MO
Country                     USA
Half            0 days 01:44:17
40K             0 days 03:18:03
Pace                    0:07:57
TotalSeconds            11883.0
HalfSeconds              6257.0
Name: 19853, dtype: object
Ozone Park
 Age                          29
M/F                           M
City                 Ozone Park
State                        NY
Country                     USA
Half            0 days 01:27:53
40K             0 days 03:03:42
Pace                    0:07:28
TotalSeconds            11022.0
HalfSeconds              5273.0
Name: 2349, dtype: object
Pa.
 Age                          58
M/F                           M
City                        Pa.
State                        PA
Country                     USA
Half            0 days 01:49:44
40K             0 days 03:51:16
Pace                    0:09:20
TotalSeconds            13876.0
HalfSeconds              6584.0
Name: 8585, dtype: object
Pacifc Palisades
 Age                           49
M/F                            M
City            Pacifc Palisades
State                         CA
Country                      USA
Half             0 days 01:28:15
40K              0 days 03:01:17
Pace                     0:07:21
TotalSeconds             10877.0
HalfSeconds               5295.0
Name: 1161, dtype: object
Pacific Beach
 Age                          53
M/F                           M
City              Pacific Beach
State                        CA
Country                     USA
Half            0 days 01:55:43
40K             0 days 04:56:44
Pace                    0:12:13
TotalSeconds            17804.0
HalfSeconds              6943.0
Name: 11061, dtype: object
Pacific Grove
 Age                          46
M/F                           M
City              Pacific Grove
State                        CA
Country                     USA
Half            0 days 01:31:09
40K             0 days 02:57:39
Pace                    0:07:12
TotalSeconds            10659.0
HalfSeconds              5469.0
Name: 5432, dtype: object
Pacific Palisades
 Age                            37
M/F                             M
City            Pacific Palisades
State                          CA
Country                       USA
Half              0 days 01:28:39
40K               0 days 02:48:31
Pace                      0:06:47
TotalSeconds              10111.0
HalfSeconds                5319.0
Name: 4148, dtype: object
Pacific Palisdes
 Age                           43
M/F                            F
City            Pacific Palisdes
State                         CA
Country                      USA
Half             0 days 01:38:40
40K              0 days 03:14:30
Pace                     0:07:53
TotalSeconds             11670.0
HalfSeconds               5920.0
Name: 18252, dtype: object
Pacifica
 Age                          39
M/F                           F
City                   Pacifica
State                        CA
Country                     USA
Half            0 days 01:34:39
40K             0 days 03:07:57
Pace                    0:07:37
TotalSeconds            11277.0
HalfSeconds              5679.0
Name: 12000, dtype: object
Pacoima
 Age                          32
M/F                           M
City                    Pacoima
State                        CA
Country                     USA
Half            0 days 01:28:13
40K             0 days 02:55:54
Pace                    0:07:08
TotalSeconds            10554.0
HalfSeconds              5293.0
Name: 3567, dtype: object
Padova
 Age                          43
M/F                           M
City                     Padova
State                       NaN
Country                     ITA
Half            0 days 02:03:46
40K             0 days 03:57:07
Pace                    0:09:35
TotalSeconds            14227.0
HalfSeconds              7426.0
Name: 31509, dtype: object
Paducah
 Age                          28
M/F                           F
City                    Paducah
State                        KY
Country                     USA
Half            0 days 01:42:43
40K             0 days 03:24:27
Pace                    0:08:15
TotalSeconds            12267.0
HalfSeconds              6163.0
Name: 14807, dtype: object
Page
 Age                          33
M/F                           M
City                       Page
State                        AZ
Country                     USA
Half            0 days 01:26:17
40K             0 days 02:57:37
Pace                    0:07:16
TotalSeconds            10657.0
HalfSeconds              5177.0
Name: 2094, dtype: object
Paia
 Age                          45
M/F                           F
City                       Paia
State                        HI
Country                     USA
Half            0 days 01:55:31
40K             0 days 04:04:00
Pace                    0:09:49
TotalSeconds            14640.0
HalfSeconds              6931.0
Name: 22049, dtype: object
Pain Court
 Age                          55
M/F                           F
City                 Pain Court
State                        ON
Country                     CAN
Half            0 days 02:04:10
40K             0 days 04:08:58
Pace                    0:10:03
TotalSeconds            14938.0
HalfSeconds              7450.0
Name: 25576, dtype: object
Painesville
 Age                          35
M/F                           M
City                Painesville
State                        OH
Country                     USA
Half            0 days 01:31:15
40K             0 days 03:03:20
Pace                    0:07:27
TotalSeconds            11000.0
HalfSeconds              5475.0
Name: 2722, dtype: object
Palatine
 Age                          25
M/F                           F
City                   Palatine
State                        IL
Country                     USA
Half            0 days 01:32:04
40K             0 days 02:59:24
Pace                    0:07:13
TotalSeconds            10764.0
HalfSeconds              5524.0
Name: 5529, dtype: object
Palazzolo S/Oglio
 Age                            34
M/F                             F
City            Palazzolo S/Oglio
State                         NaN
Country                       ITA
Half              0 days 01:51:54
40K               0 days 03:54:52
Pace                      0:09:27
TotalSeconds              14092.0
HalfSeconds                6714.0
Name: 31457, dtype: object
Palisades Park
 Age                          65
M/F                           M
City             Palisades Park
State                        NJ
Country                     USA
Half            0 days 01:50:31
40K             0 days 03:35:53
Pace                    0:08:42
TotalSeconds            12953.0
HalfSeconds              6631.0
Name: 20720, dtype: object
Palm Bay
 Age                          63
M/F                           M
City                   Palm Bay
State                        FL
Country                     USA
Half            0 days 01:52:56
40K             0 days 03:36:12
Pace                    0:08:49
TotalSeconds            12972.0
HalfSeconds              6776.0
Name: 22545, dtype: object
Palm Beach Gardens
 Age                             50
M/F                              M
City            Palm Beach Gardens
State                           FL
Country                        USA
Half               0 days 01:49:03
40K                0 days 03:35:48
Pace                       0:08:45
TotalSeconds               12948.0
HalfSeconds                 6543.0
Name: 11024, dtype: object
Palm City
 Age                          27
M/F                           M
City                  Palm City
State                        FL
Country                     USA
Half            0 days 01:26:40
40K             0 days 02:47:48
Pace                    0:06:47
TotalSeconds            10068.0
HalfSeconds              5200.0
Name: 3437, dtype: object
Palm Coast
 Age                          47
M/F                           M
City                 Palm Coast
State                        FL
Country                     USA
Half            0 days 01:32:34
40K             0 days 03:01:33
Pace                    0:07:21
TotalSeconds            10893.0
HalfSeconds              5554.0
Name: 9625, dtype: object
Palm Harbor
 Age                          30
M/F                           M
City                Palm Harbor
State                        FL
Country                     USA
Half            0 days 01:21:02
40K             0 days 02:46:30
Pace                    0:06:44
TotalSeconds             9990.0
HalfSeconds              4862.0
Name: 1159, dtype: object
Palm Springs
 Age                          57
M/F                           M
City               Palm Springs
State                        CA
Country                     USA
Half            0 days 01:51:10
40K             0 days 03:43:31
Pace                    0:09:02
TotalSeconds            13411.0
HalfSeconds              6670.0
Name: 27972, dtype: object
Palma De Mallorca
 Age                            54
M/F                             M
City            Palma De Mallorca
State                         NaN
Country                       ESP
Half              0 days 01:44:47
40K               0 days 03:35:17
Pace                      0:08:43
TotalSeconds              12917.0
HalfSeconds                6287.0
Name: 31682, dtype: object
Palmdale
 Age                          49
M/F                           M
City                   Palmdale
State                        CA
Country                     USA
Half            0 days 01:28:25
40K             0 days 02:49:43
Pace                    0:06:50
TotalSeconds            10183.0
HalfSeconds              5305.0
Name: 4241, dtype: object
Palmer
 Age                          49
M/F                           F
City                     Palmer
State                        AK
Country                     USA
Half            0 days 01:47:52
40K             0 days 03:31:54
Pace                    0:08:34
TotalSeconds            12714.0
HalfSeconds              6472.0
Name: 19684, dtype: object
Palmer Lake
 Age                          40
M/F                           F
City                Palmer Lake
State                        CO
Country                     USA
Half            0 days 01:44:45
40K             0 days 03:22:14
Pace                    0:08:09
TotalSeconds            12134.0
HalfSeconds              6285.0
Name: 16144, dtype: object
Palmerton
 Age                          46
M/F                           M
City                  Palmerton
State                        PA
Country                     USA
Half            0 days 01:47:58
40K             0 days 04:37:11
Pace                    0:11:20
TotalSeconds            16631.0
HalfSeconds              6478.0
Name: 10773, dtype: object
Palmetto Bay
 Age                          41
M/F                           F
City               Palmetto Bay
State                        FL
Country                     USA
Half            0 days 01:43:15
40K             0 days 03:20:40
Pace                    0:08:06
TotalSeconds            12040.0
HalfSeconds              6195.0
Name: 16755, dtype: object
Palmyra
 Age                          38
M/F                           F
City                    Palmyra
State                        WI
Country                     USA
Half            0 days 01:33:48
40K             0 days 03:08:36
Pace                    0:07:34
TotalSeconds            11316.0
HalfSeconds              5628.0
Name: 2959, dtype: object
Palo Alto
 Age                          26
M/F                           M
City                  Palo Alto
State                        CA
Country                     USA
Half            0 days 01:29:20
40K             0 days 02:52:07
Pace                    0:06:58
TotalSeconds            10327.0
HalfSeconds              5360.0
Name: 5238, dtype: object
Palos Heights
 Age                          46
M/F                           M
City              Palos Heights
State                        IL
Country                     USA
Half            0 days 01:41:09
40K             0 days 03:18:19
Pace                    0:08:03
TotalSeconds            11899.0
HalfSeconds              6069.0
Name: 9663, dtype: object
Palos Park
 Age                          44
M/F                           F
City                 Palos Park
State                        IL
Country                     USA
Half            0 days 01:50:48
40K             0 days 03:55:45
Pace                    0:09:36
TotalSeconds            14145.0
HalfSeconds              6648.0
Name: 19792, dtype: object
Palos Verdes
 Age                          44
M/F                           M
City               Palos Verdes

Park City
 Age                          37
M/F                           F
City                  Park City
State                        UT
Country                     USA
Half            0 days 01:38:21
40K             0 days 03:10:20
Pace                    0:07:39
TotalSeconds            11420.0
HalfSeconds              5901.0
Name: 18297, dtype: object
Park Ridge
 Age                          45
M/F                           F
City                 Park Ridge
State                        IL
Country                     USA
Half            0 days 01:52:39
40K             0 days 03:35:44
Pace                    0:08:42
TotalSeconds            12944.0
HalfSeconds              6759.0
Name: 20585, dtype: object
Parker
 Age                          32
M/F                           M
City                     Parker
State                        CO
Country                     USA
Half            0 days 01:27:20
40K             0 days 02:47:48
Pace                    0:06:46
TotalSeconds            10068.0
HalfSeconds              5240.0
Name: 1971, dtype: object
Parkersburg
 Age                          37
M/F                           M
City                Parkersburg
State                        WV
Country                     USA
Half            0 days 01:33:33
40K             0 days 03:08:55
Pace                    0:07:41
TotalSeconds            11335.0
HalfSeconds              5613.0
Name: 6571, dtype: object
Parkesburg
 Age                          57
M/F                           F
City                 Parkesburg
State                        PA
Country                     USA
Half            0 days 02:29:50
40K             0 days 04:53:55
Pace                    0:11:51
TotalSeconds            17635.0
HalfSeconds              8990.0
Name: 26554, dtype: object
Parkland
 Age                          41
M/F                           F
City                   Parkland
State                        FL
Country                     USA
Half            0 days 01:44:58
40K             0 days 03:29:10
Pace                    0:08:28
TotalSeconds            12550.0
HalfSeconds              6298.0
Name: 16118, dtype: object
Parkside
 Age                          41
M/F                           M
City                   Parkside
State                       NaN
Country                     AUS
Half            0 days 01:30:15
40K             0 days 03:07:16
Pace                    0:07:41
TotalSeconds            11236.0
HalfSeconds              5415.0
Name: 6894, dtype: object
Parkton
 Age                          21
M/F                           M
City                    Parkton
State                        MD
Country                     USA
Half            0 days 01:32:05
40K             0 days 03:14:56
Pace                    0:07:50
TotalSeconds            11696.0
HalfSeconds              5525.0
Name: 2904, dtype: object
Parkview
 Age                          55
M/F                           M
City                   Parkview
State                       NaN
Country                     RSA
Half            0 days 02:08:51
40K             0 days 04:04:56
Pace                    0:09:54
TotalSeconds            14696.0
HalfSeconds              7731.0
Name: 31584, dtype: object
Parkville
 Age                          46
M/F                           M
City                  Parkville
State                        MO
Country                     USA
Half            0 days 01:35:56
40K             0 days 03:07:25
Pace                    0:07:35
TotalSeconds            11245.0
HalfSeconds              5756.0
Name: 6489, dtype: object
Parlin
 Age                          53
M/F                           M
City                     Parlin
State                        NJ
Country                     USA
Half            0 days 01:36:33
40K             0 days 03:07:58
Pace                    0:07:35
TotalSeconds            11278.0
HalfSeconds              5793.0
Name: 13158, dtype: object
Parma
 Age                          48
M/F                           M
City                      Parma
State                       NaN
Country                     ITA
Half            0 days 01:37:18
40K             0 days 03:06:24
Pace                    0:07:32
TotalSeconds            11184.0
HalfSeconds              5838.0
Name: 10120, dtype: object
Parry Sound
 Age                          55
M/F                           F
City                Parry Sound
State                        ON
Country                     CAN
Half            0 days 02:01:30
40K             0 days 04:07:04
Pace                    0:10:05
TotalSeconds            14824.0
HalfSeconds              7290.0
Name: 25626, dtype: object
Parsippany
 Age                          39
M/F                           M
City                 Parsippany
State                        NJ
Country                     USA
Half            0 days 01:31:49
40K             0 days 03:13:34
Pace                    0:07:54
TotalSeconds            11614.0
HalfSeconds              5509.0
Name: 6890, dtype: object
Partille
 Age                          58
M/F                           M
City                   Partille
State                       NaN
Country                     SWE
Half            0 days 01:50:21
40K             0 days 03:44:59
Pace                    0:09:06
TotalSeconds            13499.0
HalfSeconds              6621.0
Name: 13943, dtype: object
Pasadena
 Age                          24
M/F                           M
City                   Pasadena
State                        CA
Country                     USA
Half            0 days 01:13:38
40K             0 days 02:22:23
Pace                    0:05:45
TotalSeconds             8543.0
HalfSeconds              4418.0
Name: 1221, dtype: object
Pasco
 Age                          34
M/F                           F
City                      Pasco
State                        WA
Country                     USA
Half            0 days 01:56:07
40K             0 days 03:53:44
Pace                    0:09:31
TotalSeconds            14024.0
HalfSeconds              6967.0
Name: 14130, dtype: object
Pascoag
 Age                          47
M/F                           M
City                    Pascoag
State                        RI
Country                     USA
Half            0 days 01:58:32
40K             0 days 04:06:42
Pace                    0:09:58
TotalSeconds            14802.0
HalfSeconds              7112.0
Name: 31094, dtype: object
Pasig City
 Age                          27
M/F                           M
City                 Pasig City
State                       NaN
Country                     PHI
Half            0 days 01:15:14
40K             0 days 02:37:37
Pace                    0:06:23
TotalSeconds             9457.0
HalfSeconds              4514.0
Name: 295, dtype: object
Paso Robles
 Age                          58
M/F                           F
City                Paso Robles
State                        CA
Country                     USA
Half            0 days 02:10:49
40K             0 days 04:24:52
Pace                    0:10:40
TotalSeconds            15892.0
HalfSeconds              7849.0
Name: 25617, dtype: object
Pataskala
 Age                          43
M/F                           M
City                  Pataskala
State                        OH
Country                     USA
Half            0 days 01:41:02
40K             0 days 03:22:32
Pace                    0:08:15
TotalSeconds            12152.0
HalfSeconds              6062.0
Name: 8177, dtype: object
Patchogue
 Age                          43
M/F                           F
City                  Patchogue
State                        NY
Country                     USA
Half            0 days 01:45:43
40K             0 days 03:25:51
Pace                    0:08:18
TotalSeconds            12351.0
HalfSeconds              6343.0
Name: 20042, dtype: object
Patterson
 Age                          49
M/F                           F
City                  Patterson
State                        MO
Country                     USA
Half            0 days 01:58:12
40K             0 days 04:06:51
Pace                    0:10:04
TotalSeconds            14811.0
HalfSeconds              7092.0
Name: 24378, dtype: object
Pawtucket
 Age                          34
M/F                           F
City                  Pawtucket
State                        RI
Country                     USA
Half            0 days 01:39:21
40K             0 days 03:08:51
Pace                    0:07:38
TotalSeconds            11331.0
HalfSeconds              5961.0
Name: 14562, dtype: object
Paxton
 Age                          47
M/F                           F
City                     Paxton
State                        MA
Country                     USA
Half            0 days 01:59:24
40K             0 days 04:00:38
Pace                    0:09:43
TotalSeconds            14438.0
HalfSeconds              7164.0
Name: 22542, dtype: object
Payson
 Age                          59
M/F                           M
City                     Payson
State                        UT
Country                     USA
Half            0 days 01:40:58
40K             0 days 03:22:53
Pace                    0:08:16
TotalSeconds            12173.0
HalfSeconds              6058.0
Name: 8415, dtype: object
Peabody
 Age                          27
M/F                           F
City                    Peabody
State                        MA
Country                     USA
Half            0 days 01:25:46
40K             0 days 02:51:12
Pace                    0:06:55
TotalSeconds            10272.0
HalfSeconds              5146.0
Name: 2082, dtype: object
Peach Bottom
 Age                          54
M/F                           M
City               Peach Bottom
State                        PA
Country                     USA
Half            0 days 02:17:10
40K             0 days 05:12:11
Pace                    0:12:30
TotalSeconds            18731.0
HalfSeconds              8230.0
Name: 29564, dtype: object
Peachtree City
 Age                          45
M/F                           F
City             Peachtree City
State                        GA
Country                     USA
Half            0 days 01:49:25
40K             0 days 03:39:00
Pace                    0:08:51
TotalSeconds            13140.0
HalfSeconds              6565.0
Name: 22000, dtype: object
Peachtree Corners
 Age                            41
M/F                             M
City            Peachtree Corners
State                          GA
Country                       USA
Half              0 days 01:32:58
40K               0 days 03:05:32
Pace                      0:07:30
TotalSeconds              11132.0
HalfSeconds                5578.0
Name: 5071, dtype: object
Peaks Island
 Age                          39
M/F                           M
City               Peaks Island
State                        ME
Country                     USA
Half            0 days 01:31:53
40K             0 days 03:05:31
Pace                    0:07:29
TotalSeconds            11131.0
HalfSeconds              5513.0
Name: 4625, dtype: object
Pear River
 Age                          41
M/F                           M
City                 Pear River
State                        NY
Country                     USA
Half            0 days 02:07:21
40K             0 days 04:32:38
Pace                    0:10:57
TotalSeconds            16358.0
HalfSeconds              7641.0
Name: 26271, dtype: object
Pearl River
 Age                          47
M/F                           M
City                Pearl River
State                        NY
Country                     USA
Half            0 days 01:47:43
40K             0 days 03:46:42
Pace                    0:09:08
TotalSeconds            13602.0
HalfSeconds              6463.0
Name: 9748, dtype: object
Pearland
 Age                          24
M/F                           M
City                   Pearland
State                        TX
Country                     USA
Half            0 days 01:18:25
40K             0 days 02:45:59
Pace                    0:06:43
TotalSeconds             9959.0
HalfSeconds              4705.0
Name: 524, dtype: object
Pebble Beach
 Age                          68
M/F                           M
City               Pebble Beach
State                        CA
Country                     USA
Half            0 days 01:57:40
40K             0 days 04:01:11
Pace                    0:09:47
TotalSeconds            14471.0
HalfSeconds              7060.0
Name: 24953, dtype: object
Peckville
 Age                          24
M/F                           M
City                  Peckville
State                        PA
Country                     USA
Half            0 days 01:19:27
40K             0 days 02:42:27
Pace                    0:06:36
TotalSeconds             9747.0
HalfSeconds              4767.0
Name: 608, dtype: object
Peekskill
 Age                          26
M/F                           M
City                  Peekskill
State                        NY
Country                     USA
Half            0 days 01:22:42
40K             0 days 02:46:20
Pace                    0:06:44
TotalSeconds             9980.0
HalfSeconds              4962.0
Name: 932, dtype: object
Pekin
 Age                          48
M/F                           M
City                      Pekin
State                        IN
Country                     USA
Half            0 days 01:29:56
40K             0 days 03:05:18
Pace                    0:07:31
TotalSeconds            11118.0
HalfSeconds              5396.0
Name: 8433, dtype: object
Pelham
 Age                          42
M/F                           M
City                     Pelham
State                        NH
Country                     USA
Half            0 days 01:35:10
40K             0 days 03:07:06
Pace                    0:07:32
TotalSeconds            11226.0
HalfSeconds              5710.0
Name: 13328, dtype: object
Pell City
 Age                          53
M/F                           F
City                  Pell City
State                        AL
Country                     USA
Half            0 days 02:03:47
40K             0 days 04:02:50
Pace                    0:09:48
TotalSeconds            14570.0
HalfSeconds              7427.0
Name: 24964, dtype: object
Pella
 Age                          55
M/F                           M
City                      Pella
State                        IA
Country                     USA
Half            0 days 01:39:04
40K             0 days 03:19:40
Pace                    0:08:05
TotalSeconds            11980.0
HalfSeconds              5944.0
Name: 8063, dtype: object
Pellenberg
 Age                          33
M/F                           M
City                 Pellenberg
State                       NaN
Country                     BEL
Half            0 days 01:39:32
40K             0 days 03:12:19
Pace                    0:07:45
TotalSeconds            11539.0
HalfSeconds              5972.0
Name: 31285, dtype: object
Pelzer
 Age                          37
M/F                           M
City                     Pelzer
State                        SC
Country                     USA
Half            0 days 01:29:20
40K             0 days 02:58:07
Pace                    0:07:25
TotalSeconds            10687.0
HalfSeconds              5360.0
Name: 6760, dtype: object
Pembroke
 Age                          22
M/F                           M
City                   Pembroke
State                        MA
Country                     USA
Half            0 days 01:25:07
40K             0 days 02:50:43
Pace                    0:06:56
TotalSeconds            10243.0
HalfSeconds              5107.0
Name: 4138, dtype: object
Pembroke Pines
 Age                          51
M/F                           F
City             Pembroke Pines
State                        FL
Country                     USA
Half            0 days 01:59:09
40K             0 days 04:04:16
Pace                    0:09:51
TotalSeconds            14656.0
HalfSeconds              7149.0
Name: 19393, dtype: object
Penacook
 Age                          51
M/F                           M
City                   Penacook
State                        NH
Country                     USA
Half            0 days 01:36:49
40K             0 days 03:22:33
Pace                    0:08:24
TotalSeconds            12153.0
HalfSeconds              5809.0
Name: 8014, dtype: object
Penapolis, Sao Paulo
 Age                               34
M/F                                M
City            Penapolis, Sao Paulo
State                            NaN
Country                          BRA
Half                 0 days 01:06:47
40K                  0 days 02:16:29
Pace                         0:05:32
TotalSeconds                  8189.0
HalfSeconds                   4007.0
Name: 19, dtype: object
Pendleton
 Age                          43
M/F                           F
City                  Pendleton
State                        SC
Country                     USA
Half            0 days 01:40:28
40K             0 days 03:27:23
Pace                    0:08:24
TotalSeconds            12443.0
HalfSeconds              6028.0
Name: 7339, dtype: object
Penfeild
 Age                          40
M/F                           F
City                   Penfeild
State                        NY
Country                     USA
Half            0 days 01:48:16
40K             0 days 03:51:09
Pace                    0:09:24
TotalSeconds            13869.0
HalfSeconds              6496.0
Name: 16556, dtype: object
Penfield
 Age                          28
M/F                           F
City                   Penfield
State                        NY
Country                     USA
Half            0 days 01:47:06
40K             0 days 03:35:20
Pace                    0:08:42
TotalSeconds            12920.0
HalfSeconds              6426.0
Name: 17381, dtype: object
Penhold
 Age                          46
M/F                           M
City                    Penhold
State                        AB
Country                     CAN
Half            0 days 01:36:15
40K             0 days 03:09:37
Pace                    0:07:41
TotalSeconds            11377.0
HalfSeconds              5775.0
Name: 10221, dtype: object
Penn Valley
 Age                          44
M/F                           F
City                Penn Valley
State                        PA
Country                     USA
Half            0 days 01:45:04
40K             0 days 03:28:09
Pace                    0:08:26
TotalSeconds            12489.0
HalfSeconds              6304.0
Name: 19056, dtype: object
Penn Yan
 Age                          40
M/F                           F
City                   Penn Yan
State                        NY
Country                     USA
Half            0 days 01:44:37
40K             0 days 03:22:37
Pace                    0:08:10
TotalSeconds            12157.0
HalfSeconds              6277.0
Name: 16676, dtype: object
Penneshaw Sa
 Age                          51
M/F                           F
City               Penneshaw Sa
State                       NaN
Country                     AUS
Half            0 days 02:05:06
40K             0 days 04:07:34
Pace                    0:09:57
TotalSeconds            14854.0
HalfSeconds              7506.0
Name: 24337, dtype: object
Pennington
 Age                          46
M/F                           F
City                 Pennington
State                        NJ
Country                     USA
Half            0 days 01:43:11
40K             0 days 03:17:10
Pace                    0:07:56
TotalSeconds            11830.0
HalfSeconds              6191.0
Name: 16142, dtype: object
Pensacola
 Age                          34
M/F                           M
City                  Pensacola
State                        FL
Country                     USA
Half            0 days 01:16:57
40K             0 days 02:30:38

Name: 10540, dtype: object
Petropolis
 Age                          55
M/F                           M
City                 Petropolis
State                       NaN
Country                     BRA
Half            0 days 01:41:46
40K             0 days 03:18:54
Pace                    0:08:03
TotalSeconds            11934.0
HalfSeconds              6106.0
Name: 17498, dtype: object
Pewaukee
 Age                          55
M/F                           M
City                   Pewaukee
State                        WI
Country                     USA
Half            0 days 01:44:54
40K             0 days 03:26:56
Pace                    0:08:21
TotalSeconds            12416.0
HalfSeconds              6294.0
Name: 16844, dtype: object
Pfafftown
 Age                          23
M/F                           M
City                  Pfafftown
State                        NC
Country                     USA
Half            0 days 01:20:30
40K             0 days 02:51:28
Pace                    0:06:57
TotalSeconds            10288.0
HalfSeconds              4830.0
Name: 518, dtype: object
Pfeffingen
 Age                          37
M/F                           M
City                 Pfeffingen
State                       NaN
Country                     SUI
Half            0 days 01:43:44
40K             0 days 03:24:24
Pace                    0:08:16
TotalSeconds            12264.0
HalfSeconds              6224.0
Name: 31376, dtype: object
Pfinztal
 Age                          50
M/F                           M
City                   Pfinztal
State                       NaN
Country                     GER
Half            0 days 01:43:41
40K             0 days 03:32:13
Pace                    0:08:37
TotalSeconds            12733.0
HalfSeconds              6221.0
Name: 15190, dtype: object
Pflugerville
 Age                          39
M/F                           F
City               Pflugerville
State                        TX
Country                     USA
Half            0 days 01:35:15
40K             0 days 03:04:59
Pace                    0:07:29
TotalSeconds            11099.0
HalfSeconds              5715.0
Name: 8946, dtype: object
Pharr
 Age                          60
M/F                           F
City                      Pharr
State                        TX
Country                     USA
Half            0 days 01:44:20
40K             0 days 03:31:11
Pace                    0:08:32
TotalSeconds            12671.0
HalfSeconds              6260.0
Name: 15465, dtype: object
Phenix City
 Age                          34
M/F                           F
City                Phenix City
State                        AL
Country                     USA
Half            0 days 01:40:01
40K             0 days 03:33:53
Pace                    0:08:48
TotalSeconds            12833.0
HalfSeconds              6001.0
Name: 13195, dtype: object
Phila
 Age                          37
M/F                           M
City                      Phila
State                        PA
Country                     USA
Half            0 days 01:28:46
40K             0 days 02:50:57
Pace                    0:06:53
TotalSeconds            10257.0
HalfSeconds              5326.0
Name: 1552, dtype: object
Philadelphia
 Age                          25
M/F                           M
City               Philadelphia
State                        PA
Country                     USA
Half            0 days 01:14:31
40K             0 days 02:27:25
Pace                    0:05:58
TotalSeconds             8845.0
HalfSeconds              4471.0
Name: 452, dtype: object
Philadelphia,
 Age                          51
M/F                           F
City              Philadelphia,
State                        PA
Country                     USA
Half            0 days 01:52:19
40K             0 days 03:37:23
Pace                    0:08:46
TotalSeconds            13043.0
HalfSeconds              6739.0
Name: 21771, dtype: object
Philomath
 Age                          37
M/F                           F
City                  Philomath
State                        OR
Country                     USA
Half            0 days 01:44:32
40K             0 days 03:20:38
Pace                    0:08:04
TotalSeconds            12038.0
HalfSeconds              6272.0
Name: 13555, dtype: object
Phoenix
 Age                          43
M/F                           M
City                    Phoenix
State                        AZ
Country                     USA
Half            0 days 01:14:55
40K             0 days 02:26:58
Pace                    0:05:58
TotalSeconds             8818.0
HalfSeconds              4495.0
Name: 86, dtype: object
Phoenixville
 Age                          21
M/F                           M
City               Phoenixville
State                        PA
Country                     USA
Half            0 days 01:28:17
40K             0 days 02:57:14
Pace                    0:07:10
TotalSeconds            10634.0
HalfSeconds              5297.0
Name: 2321, dtype: object
Pichincha.quito
 Age                          56
M/F                           M
City            Pichincha.quito
State                       NaN
Country                     ECU
Half            0 days 02:04:33
40K             0 days 04:12:23
Pace                    0:10:08
TotalSeconds            15143.0
HalfSeconds              7473.0
Name: 30968, dtype: object
Pickens
 Age                          45
M/F                           M
City                    Pickens
State                        SC
Country                     USA
Half            0 days 01:37:38
40K             0 days 03:17:57
Pace                    0:08:05
TotalSeconds            11877.0
HalfSeconds              5858.0
Name: 8605, dtype: object
Pickering
 Age                          52
M/F                           M
City                  Pickering
State                        ON
Country                     CAN
Half            0 days 01:35:51
40K             0 days 03:09:33
Pace                    0:07:39
TotalSeconds            11373.0
HalfSeconds              5751.0
Name: 8076, dtype: object
Pickerington
 Age                          34
M/F                           M
City               Pickerington
State                        OH
Country                     USA
Half            0 days 01:32:45
40K             0 days 03:22:19
Pace                    0:08:15
TotalSeconds            12139.0
HalfSeconds              5565.0
Name: 4716, dtype: object
Pico Rivera
 Age                          48
M/F                           F
City                Pico Rivera
State                        CA
Country                     USA
Half            0 days 01:51:25
40K             0 days 03:40:49
Pace                    0:08:55
TotalSeconds            13249.0
HalfSeconds              6685.0
Name: 22645, dtype: object
Pictou
 Age                          47
M/F                           F
City                     Pictou
State                        NS
Country                     CAN
Half            0 days 02:01:52
40K             0 days 04:19:46
Pace                    0:10:27
TotalSeconds            15586.0
HalfSeconds              7312.0
Name: 23141, dtype: object
Piedmont
 Age                          40
M/F                           M
City                   Piedmont
State                        CA
Country                     USA
Half            0 days 01:19:06
40K             0 days 02:34:19
Pace                    0:06:13
TotalSeconds             9259.0
HalfSeconds              4746.0
Name: 473, dtype: object
Pierce
 Age                          45
M/F                           M
City                     Pierce
State                        NE
Country                     USA
Half            0 days 01:37:32
40K             0 days 03:07:34
Pace                    0:07:34
TotalSeconds            11254.0
HalfSeconds              5852.0
Name: 9137, dtype: object
Pierrefonds
 Age                          55
M/F                           M
City                Pierrefonds
State                        QC
Country                     CAN
Half            0 days 01:54:54
40K             0 days 04:05:58
Pace                    0:09:59
TotalSeconds            14758.0
HalfSeconds              6894.0
Name: 18677, dtype: object
Pigneto Di Prignano S/S
 Age                                  51
M/F                                   M
City            Pigneto Di Prignano S/S
State                               NaN
Country                             ITA
Half                    0 days 01:51:58
40K                     0 days 03:49:06
Pace                            0:09:14
TotalSeconds                    13746.0
HalfSeconds                      6718.0
Name: 12626, dtype: object
Pike Road
 Age                          42
M/F                           F
City                  Pike Road
State                        AL
Country                     USA
Half            0 days 02:05:14
40K             0 days 04:15:58
Pace                    0:10:22
TotalSeconds            15358.0
HalfSeconds              7514.0
Name: 19464, dtype: object
Pikesville
 Age                          48
M/F                           M
City                 Pikesville
State                        MD
Country                     USA
Half            0 days 01:33:52
40K             0 days 02:59:37
Pace                    0:07:13
TotalSeconds            10777.0
HalfSeconds              5632.0
Name: 8343, dtype: object
Pinckney
 Age                          21
M/F                           M
City                   Pinckney
State                        MI
Country                     USA
Half            0 days 01:25:58
40K             0 days 02:57:44
Pace                    0:07:12
TotalSeconds            10664.0
HalfSeconds              5158.0
Name: 833, dtype: object
Pincourt
 Age                          53
M/F                           M
City                   Pincourt
State                        QC
Country                     CAN
Half            0 days 01:47:49
40K             0 days 03:31:15
Pace                    0:08:32
TotalSeconds            12675.0
HalfSeconds              6469.0
Name: 12633, dtype: object
Pine Beach
 Age                          64
M/F                           M
City                 Pine Beach
State                        NJ
Country                     USA
Half            0 days 01:57:18
40K             0 days 04:02:58
Pace                    0:09:49
TotalSeconds            14578.0
HalfSeconds              7038.0
Name: 24195, dtype: object
Pine Bluff
 Age                          65
M/F                           F
City                 Pine Bluff
State                        AR
Country                     USA
Half            0 days 02:15:36
40K             0 days 04:28:08
Pace                    0:10:50
TotalSeconds            16088.0
HalfSeconds              8136.0
Name: 26025, dtype: object
Pine Brook
 Age                          50
M/F                           M
City                 Pine Brook
State                        NJ
Country                     USA
Half            0 days 02:05:17
40K             0 days 04:24:31
Pace                    0:10:41
TotalSeconds            15871.0
HalfSeconds              7517.0
Name: 30271, dtype: object
Pine Lake
 Age                          35
M/F                           F
City                  Pine Lake
State                        GA
Country                     USA
Half            0 days 01:42:45
40K             0 days 03:19:57
Pace                    0:08:03
TotalSeconds            11997.0
HalfSeconds              6165.0
Name: 16485, dtype: object
Pine Plains
 Age                          24
M/F                           F
City                Pine Plains
State                        NY
Country                     USA
Half            0 days 02:03:56
40K             0 days 04:02:42
Pace                    0:09:45
TotalSeconds            14562.0
HalfSeconds              7436.0
Name: 16408, dtype: object
Pine Valley
 Age                          58
M/F                           F
City                Pine Valley
State                        CA
Country                     USA
Half            0 days 01:41:05
40K             0 days 03:23:09
Pace                    0:08:12
TotalSeconds            12189.0
HalfSeconds              6065.0
Name: 21243, dtype: object
Pinedale
 Age                          37
M/F                           F
City                   Pinedale
State                        WY
Country                     USA
Half            0 days 01:43:13
40K             0 days 03:23:53
Pace                    0:08:14
TotalSeconds            12233.0
HalfSeconds              6193.0
Name: 14272, dtype: object
Pinehurst
 Age                          47
M/F                           F
City                  Pinehurst
State                        NC
Country                     USA
Half            0 days 01:40:36
40K             0 days 03:24:28
Pace                    0:08:18
TotalSeconds            12268.0
HalfSeconds              6036.0
Name: 17519, dtype: object
Pineville
 Age                          66
M/F                           M
City                  Pineville
State                        NC
Country                     USA
Half            0 days 01:53:34
40K             0 days 03:43:52
Pace                    0:09:02
TotalSeconds            13432.0
HalfSeconds              6814.0
Name: 21105, dtype: object
Piney Flats
 Age                          49
M/F                           M
City                Piney Flats
State                        TN
Country                     USA
Half            0 days 01:34:22
40K             0 days 03:13:04
Pace                    0:07:51
TotalSeconds            11584.0
HalfSeconds              5662.0
Name: 7266, dtype: object
Piqua
 Age                          34
M/F                           M
City                      Piqua
State                        OH
Country                     USA
Half            0 days 01:28:46
40K             0 days 03:01:25
Pace                    0:07:24
TotalSeconds            10885.0
HalfSeconds              5326.0
Name: 4237, dtype: object
Pisa
 Age                          52
M/F                           M
City                       Pisa
State                       NaN
Country                     ITA
Half            0 days 01:42:47
40K             0 days 03:19:43
Pace                    0:08:03
TotalSeconds            11983.0
HalfSeconds              6167.0
Name: 8815, dtype: object
Pitt Meadows
 Age                          51
M/F                           F
City               Pitt Meadows
State                        BC
Country                     CAN
Half            0 days 02:01:39
40K             0 days 03:57:32
Pace                    0:09:33
TotalSeconds            14252.0
HalfSeconds              7299.0
Name: 22965, dtype: object
Pittsbrugh
 Age                          30
M/F                           F
City                 Pittsbrugh
State                        PA
Country                     USA
Half            0 days 01:44:42
40K             0 days 03:23:31
Pace                    0:08:13
TotalSeconds            12211.0
HalfSeconds              6282.0
Name: 16535, dtype: object
Pittsburg
 Age                          30
M/F                           M
City                  Pittsburg
State                        KS
Country                     USA
Half            0 days 01:20:46
40K             0 days 02:33:55
Pace                    0:06:14
TotalSeconds             9235.0
HalfSeconds              4846.0
Name: 508, dtype: object
Pittsburgh
 Age                          23
M/F                           M
City                 Pittsburgh
State                        PA
Country                     USA
Half            0 days 01:15:53
40K             0 days 02:27:53
Pace                    0:06:00
TotalSeconds             8873.0
HalfSeconds              4553.0
Name: 221, dtype: object
Pittsfield
 Age                          47
M/F                           M
City                 Pittsfield
State                        ME
Country                     USA
Half            0 days 01:37:01
40K             0 days 03:15:40
Pace                    0:08:01
TotalSeconds            11740.0
HalfSeconds              5821.0
Name: 7634, dtype: object
Pittsford
 Age                          31
M/F                           M
City                  Pittsford
State                        NY
Country                     USA
Half            0 days 01:25:19
40K             0 days 02:55:55
Pace                    0:07:06
TotalSeconds            10555.0
HalfSeconds              5119.0
Name: 1091, dtype: object
Pittston Twp.
 Age                          24
M/F                           F
City              Pittston Twp.
State                        PA
Country                     USA
Half            0 days 01:48:07
40K             0 days 03:39:26
Pace                    0:08:53
TotalSeconds            13166.0
HalfSeconds              6487.0
Name: 18225, dtype: object
Pittstown
 Age                          48
M/F                           M
City                  Pittstown
State                        NJ
Country                     USA
Half            0 days 01:33:32
40K             0 days 03:06:11
Pace                    0:07:32
TotalSeconds            11171.0
HalfSeconds              5612.0
Name: 4876, dtype: object
Placentia
 Age                          34
M/F                           M
City                  Placentia
State                        CA
Country                     USA
Half            0 days 01:26:44
40K             0 days 02:56:33
Pace                    0:07:12
TotalSeconds            10593.0
HalfSeconds              5204.0
Name: 5183, dtype: object
Placerville
 Age                          48
M/F                           M
City                Placerville
State                        CA
Country                     USA
Half            0 days 01:36:42
40K             0 days 03:12:46
Pace                    0:07:47
TotalSeconds            11566.0
HalfSeconds              5802.0
Name: 9301, dtype: object
Placitas
 Age                          61
M/F                           M
City                   Placitas
State                        NM
Country                     USA
Half            0 days 01:54:42
40K             0 days 03:45:55
Pace                    0:09:05
TotalSeconds            13555.0
HalfSeconds              6882.0
Name: 24093, dtype: object
Plain City
 Age                          35
M/F                           F
City                 Plain City
State                        UT
Country                     USA
Half            0 days 01:58:53
40K             0 days 03:59:39
Pace                    0:09:41
TotalSeconds            14379.0
HalfSeconds              7133.0
Name: 19374, dtype: object
Plainfield
 Age                          42
M/F                           M
City                 Plainfield
State                        CT
Country                     USA
Half            0 days 01:17:31
40K             0 days 02:33:14
Pace                    0:06:11
TotalSeconds             9194.0
HalfSeconds              4651.0
Name: 252, dtype: object
Plains
 Age                          50
M/F                           M
City                     Plains
State                        PA
Country                     USA
Half            0 days 01:49:36
40K             0 days 04:37:50
Pace                    0:11:09
TotalSeconds            16670.0
HalfSeconds              6576.0
Name: 13206, dtype: object
Plainview
 Age                          33
M/F                           F
City                  Plainview
State                        NY
Country                     USA
Half            0 days 01:41:26
40K             0 days 03:21:00
Pace                    0:08:07
TotalSeconds            12060.0
HalfSeconds              6086.0
Name: 17322, dtype: object
Plainville
 Age                          26
M/F                           F
City                 Plainville
State                        MA
Country                     USA
Half            0 days 01:37:38

Pleasant View
 Age                          55
M/F                           F
City              Pleasant View
State                        TN
Country                     USA
Half            0 days 01:56:52
40K             0 days 03:45:45
Pace                    0:09:07
TotalSeconds            13545.0
HalfSeconds              7012.0
Name: 23006, dtype: object
Pleasanton
 Age                          40
M/F                           F
City                 Pleasanton
State                        CA
Country                     USA
Half            0 days 01:31:54
40K             0 days 02:59:06
Pace                    0:07:14
TotalSeconds            10746.0
HalfSeconds              5514.0
Name: 8084, dtype: object
Pleasantville
 Age                          42
M/F                           F
City              Pleasantville
State                        NY
Country                     USA
Half            0 days 01:48:25
40K             0 days 03:31:06
Pace                    0:08:32
TotalSeconds            12666.0
HalfSeconds              6505.0
Name: 14382, dtype: object
Pleboulle
 Age                          61
M/F                           M
City                  Pleboulle
State                       NaN
Country                     FRA
Half            0 days 01:59:48
40K             0 days 03:57:00
Pace                    0:09:35
TotalSeconds            14220.0
HalfSeconds              7188.0
Name: 22721, dtype: object
Plymouth
 Age                          49
M/F                           M
City                   Plymouth
State                        MN
Country                     USA
Half            0 days 01:33:27
40K             0 days 03:05:54
Pace                    0:07:32
TotalSeconds            11154.0
HalfSeconds              5607.0
Name: 6926, dtype: object
Plymouth Meeting
 Age                           58
M/F                            M
City            Plymouth Meeting
State                         PA
Country                      USA
Half             0 days 01:42:13
40K              0 days 03:23:35
Pace                     0:08:14
TotalSeconds             12215.0
HalfSeconds               6133.0
Name: 16785, dtype: object
Plympton
 Age                          48
M/F                           F
City                   Plympton
State                        MA
Country                     USA
Half            0 days 01:54:02
40K             0 days 03:43:45
Pace                    0:09:01
TotalSeconds            13425.0
HalfSeconds              6842.0
Name: 21823, dtype: object
Pocasset
 Age                          40
M/F                           M
City                   Pocasset
State                        MA
Country                     USA
Half            0 days 01:45:36
40K             0 days 03:46:57
Pace                    0:09:14
TotalSeconds            13617.0
HalfSeconds              6336.0
Name: 5470, dtype: object
Pocatello
 Age                          39
M/F                           M
City                  Pocatello
State                        ID
Country                     USA
Half            0 days 01:14:06
40K             0 days 02:24:17
Pace                    0:05:51
TotalSeconds             8657.0
HalfSeconds              4446.0
Name: 289, dtype: object
Pocono Lake
 Age                          38
M/F                           F
City                Pocono Lake
State                        PA
Country                     USA
Half            0 days 02:28:58
40K             0 days 05:12:53
Pace                    0:12:37
TotalSeconds            18773.0
HalfSeconds              8938.0
Name: 27583, dtype: object
Podington
 Age                          46
M/F                           M
City                  Podington
State                       NaN
Country                     GBR
Half            0 days 01:43:13
40K             0 days 03:22:30
Pace                    0:08:12
TotalSeconds            12150.0
HalfSeconds              6193.0
Name: 9528, dtype: object
Point Piper
 Age                          56
M/F                           F
City                Point Piper
State                       NaN
Country                     AUS
Half            0 days 02:43:06
40K             0 days 05:19:03
Pace                    0:12:50
TotalSeconds            19143.0
HalfSeconds              9786.0
Name: 31549, dtype: object
Point Pleasant Beach
 Age                               43
M/F                                M
City            Point Pleasant Beach
State                             NJ
Country                          USA
Half                 0 days 01:35:00
40K                  0 days 03:05:18
Pace                         0:07:29
TotalSeconds                 11118.0
HalfSeconds                   5700.0
Name: 7123, dtype: object
Pointe-Aux-Outardes
 Age                              34
M/F                               F
City            Pointe-Aux-Outardes
State                            QC
Country                         CAN
Half                0 days 01:40:44
40K                 0 days 03:11:41
Pace                        0:07:43
TotalSeconds                11501.0
HalfSeconds                  6044.0
Name: 11331, dtype: object
Pointe-Claire
 Age                          54
M/F                           M
City              Pointe-Claire
State                        QC
Country                     CAN
Half            0 days 01:37:41
40K             0 days 03:12:48
Pace                    0:07:48
TotalSeconds            11568.0
HalfSeconds              5861.0
Name: 10012, dtype: object
Pok Fu Lam
 Age                          39
M/F                           M
City                 Pok Fu Lam
State                       NaN
Country                     HKG
Half            0 days 01:30:29
40K             0 days 03:15:34
Pace                    0:07:56
TotalSeconds            11734.0
HalfSeconds              5429.0
Name: 5065, dtype: object
Pokemouche
 Age                          53
M/F                           M
City                 Pokemouche
State                        NB
Country                     CAN
Half            0 days 01:37:26
40K             0 days 03:08:22
Pace                    0:07:37
TotalSeconds            11302.0
HalfSeconds              5846.0
Name: 10444, dtype: object
Poland
 Age                          56
M/F                           M
City                     Poland
State                        ME
Country                     USA
Half            0 days 01:53:44
40K             0 days 03:56:02
Pace                    0:09:31
TotalSeconds            14162.0
HalfSeconds              6824.0
Name: 18983, dtype: object
Polcenigo-Pn
 Age                          59
M/F                           M
City               Polcenigo-Pn
State                       NaN
Country                     ITA
Half            0 days 02:22:53
40K             0 days 04:45:21
Pace                    0:11:30
TotalSeconds            17121.0
HalfSeconds              8573.0
Name: 31619, dtype: object
Polk City
 Age                          45
M/F                           F
City                  Polk City
State                        FL
Country                     USA
Half            0 days 01:47:37
40K             0 days 03:29:20
Pace                    0:08:25
TotalSeconds            12560.0
HalfSeconds              6457.0
Name: 18715, dtype: object
Pollionnay
 Age                          50
M/F                           M
City                 Pollionnay
State                       NaN
Country                     FRA
Half            0 days 02:00:31
40K             0 days 04:25:44
Pace                    0:10:43
TotalSeconds            15944.0
HalfSeconds              7231.0
Name: 30074, dtype: object
Pomfret
 Age                          25
M/F                           F
City                    Pomfret
State                        CT
Country                     USA
Half            0 days 01:45:24
40K             0 days 03:21:07
Pace                    0:08:05
TotalSeconds            12067.0
HalfSeconds              6324.0
Name: 17512, dtype: object
Pomona
 Age                          43
M/F                           M
City                     Pomona
State                        NY
Country                     USA
Half            0 days 01:30:17
40K             0 days 03:00:01
Pace                    0:07:16
TotalSeconds            10801.0
HalfSeconds              5417.0
Name: 2222, dtype: object
Pompano Beach
 Age                          44
M/F                           F
City              Pompano Beach
State                        FL
Country                     USA
Half            0 days 01:44:48
40K             0 days 03:23:35
Pace                    0:08:13
TotalSeconds            12215.0
HalfSeconds              6288.0
Name: 19466, dtype: object
Ponca City
 Age                          39
M/F                           F
City                 Ponca City
State                        OK
Country                     USA
Half            0 days 02:21:30
40K             0 days 04:41:07
Pace                    0:11:17
TotalSeconds            16867.0
HalfSeconds              8490.0
Name: 30595, dtype: object
Ponchatoula
 Age                          28
M/F                           F
City                Ponchatoula
State                        LA
Country                     USA
Half            0 days 01:48:03
40K             0 days 03:47:39
Pace                    0:09:13
TotalSeconds            13659.0
HalfSeconds              6483.0
Name: 13361, dtype: object
Pont-Rouge
 Age                          42
M/F                           M
City                 Pont-Rouge
State                        QC
Country                     CAN
Half            0 days 01:28:33
40K             0 days 02:50:22
Pace                    0:06:52
TotalSeconds            10222.0
HalfSeconds              5313.0
Name: 6285, dtype: object
Ponte Vedra
 Age                          45
M/F                           M
City                Ponte Vedra
State                        FL
Country                     USA
Half            0 days 01:52:53
40K             0 days 03:39:24
Pace                    0:08:52
TotalSeconds            13164.0
HalfSeconds              6773.0
Name: 11025, dtype: object
Ponte Vedra Beach
 Age                            35
M/F                             F
City            Ponte Vedra Beach
State                          FL
Country                       USA
Half              0 days 01:38:20
40K               0 days 03:09:40
Pace                      0:07:39
TotalSeconds              11380.0
HalfSeconds                5900.0
Name: 8454, dtype: object
Pontedera-Pi
 Age                          60
M/F                           M
City               Pontedera-Pi
State                       NaN
Country                     ITA
Half            0 days 02:00:29
40K             0 days 03:57:14
Pace                    0:09:34
TotalSeconds            14234.0
HalfSeconds              7229.0
Name: 31607, dtype: object
Pontefract
 Age                          64
M/F                           M
City                 Pontefract
State                       NaN
Country                     GBR
Half            0 days 01:55:09
40K             0 days 04:11:14
Pace                    0:10:12
TotalSeconds            15074.0
HalfSeconds              6909.0
Name: 19643, dtype: object
Pontiac
 Age                          55
M/F                           M
City                    Pontiac
State                        MI
Country                     USA
Half            0 days 01:43:59
40K             0 days 03:23:37
Pace                    0:08:13
TotalSeconds            12217.0
HalfSeconds              6239.0
Name: 12735, dtype: object
Pontresina
 Age                          65
M/F                           M
City                 Pontresina
State                       NaN
Country                     SUI
Half            0 days 02:11:27
40K             0 days 04:24:02
Pace                    0:10:40
TotalSeconds            15842.0
HalfSeconds              7887.0
Name: 31534, dtype: object
Poole
 Age                          49
M/F                           M
City                      Poole
State                       NaN
Country                     GBR
Half            0 days 01:42:31
40K             0 days 03:35:25
Pace                    0:08:44
TotalSeconds            12925.0
HalfSeconds              6151.0
Name: 12815, dtype: object
Pooler
 Age                          36
M/F                           M
City                     Pooler
State                        GA
Country                     USA
Half            0 days 01:49:47
40K             0 days 03:48:56
Pace                    0:09:15
TotalSeconds            13736.0
HalfSeconds              6587.0
Name: 26146, dtype: object
Poortugaal
 Age                          61
M/F                           M
City                 Poortugaal
State                       NaN
Country                     NED
Half            0 days 02:04:34
40K             0 days 04:15:48
Pace                    0:10:17
TotalSeconds            15348.0
HalfSeconds              7474.0
Name: 27873, dtype: object
Poplar
 Age                          45
M/F                           M
City                     Poplar
State                        WI
Country                     USA
Half            0 days 01:40:41
40K             0 days 03:29:57
Pace                    0:08:28
TotalSeconds            12597.0
HalfSeconds              6041.0
Name: 12380, dtype: object
Pori
 Age                          60
M/F                           M
City                       Pori
State                       NaN
Country                     FIN
Half            0 days 01:54:47
40K             0 days 03:43:26
Pace                    0:09:01
TotalSeconds            13406.0
HalfSeconds              6887.0
Name: 23462, dtype: object
Port Allegany
 Age                          45
M/F                           M
City              Port Allegany
State                        PA
Country                     USA
Half            0 days 01:32:56
40K             0 days 03:16:48
Pace                    0:08:04
TotalSeconds            11808.0
HalfSeconds              5576.0
Name: 4718, dtype: object
Port Angeles
 Age                          36
M/F                           M
City               Port Angeles
State                        WA
Country                     USA
Half            0 days 02:04:22
40K             0 days 04:06:45
Pace                    0:09:58
TotalSeconds            14805.0
HalfSeconds              7462.0
Name: 29408, dtype: object
Port Charlotte
 Age                          66
M/F                           M
City             Port Charlotte
State                        FL
Country                     USA
Half            0 days 01:59:45
40K             0 days 04:09:07
Pace                    0:10:07
TotalSeconds            14947.0
HalfSeconds              7185.0
Name: 24543, dtype: object
Port Coquitlam
 Age                          55
M/F                           M
City             Port Coquitlam
State                        BC
Country                     CAN
Half            0 days 02:03:24
40K             0 days 04:07:09
Pace                    0:10:01
TotalSeconds            14829.0
HalfSeconds              7404.0
Name: 16717, dtype: object
Port Dover
 Age                          52
M/F                           M
City                 Port Dover
State                        ON
Country                     CAN
Half            0 days 01:36:20
40K             0 days 03:01:44
Pace                    0:07:19
TotalSeconds            10904.0
HalfSeconds              5780.0
Name: 8634, dtype: object
Port Edwards
 Age                          51
M/F                           F
City               Port Edwards
State                        WI
Country                     USA
Half            0 days 01:40:39
40K             0 days 03:20:55
Pace                    0:08:07
TotalSeconds            12055.0
HalfSeconds              6039.0
Name: 11281, dtype: object
Port Elgin
 Age                          38
M/F                           M
City                 Port Elgin
State                        ON
Country                     CAN
Half            0 days 01:32:53
40K             0 days 03:03:53
Pace                    0:07:25
TotalSeconds            11033.0
HalfSeconds              5573.0
Name: 6108, dtype: object
Port Huron
 Age                          60
M/F                           M
City                 Port Huron
State                        MI
Country                     USA
Half            0 days 01:52:17
40K             0 days 03:41:01
Pace                    0:08:57
TotalSeconds            13261.0
HalfSeconds              6737.0
Name: 20663, dtype: object
Port Isabel
 Age                          39
M/F                           M
City                Port Isabel
State                        TX
Country                     USA
Half            0 days 01:55:50
40K             0 days 03:52:09
Pace                    0:09:25
TotalSeconds            13929.0
HalfSeconds              6950.0
Name: 31113, dtype: object
Port Jefferson Station
 Age                                 48
M/F                                  F
City            Port Jefferson Station
State                               NY
Country                            USA
Half                   0 days 01:56:43
40K                    0 days 03:56:52
Pace                           0:09:35
TotalSeconds                   14212.0
HalfSeconds                     7003.0
Name: 22563, dtype: object
Port Jervis
 Age                          33
M/F                           F
City                Port Jervis
State                        NY
Country                     USA
Half            0 days 01:49:41
40K             0 days 03:31:32
Pace                    0:08:31
TotalSeconds            12692.0
HalfSeconds              6581.0
Name: 17166, dtype: object
Port Matilda
 Age                          47
M/F                           M
City               Port Matilda
State                        PA
Country                     USA
Half            0 days 01:34:06
40K             0 days 03:10:43
Pace                    0:07:44
TotalSeconds            11443.0
HalfSeconds              5646.0
Name: 6690, dtype: object
Port Moody
 Age                          46
M/F                           F
City                 Port Moody
State                        BC
Country                     CAN
Half            0 days 01:51:19
40K             0 days 03:38:02
Pace                    0:08:46
TotalSeconds            13082.0
HalfSeconds              6679.0
Name: 19568, dtype: object
Port Of Spain
 Age                          49
M/F                           F
City              Port Of Spain
State                       NaN
Country                     TRI
Half            0 days 01:48:25
40K             0 days 03:34:17
Pace                    0:08:39
TotalSeconds            12857.0
HalfSeconds              6505.0
Name: 22866, dtype: object
Port Orange
 Age                          29
M/F                           M
City                Port Orange
State                        FL
Country                     USA
Half            0 days 01:56:01
40K             0 days 04:11:39
Pace                    0:10:08
TotalSeconds            15099.0
HalfSeconds              6961.0
Name: 26193, dtype: object
Port Perry
 Age                          37
M/F                           M
City                 Port Perry
State                        ON
Country                     CAN
Half            0 days 01:32:07
40K             0 days 03:05:31
Pace                    0:07:30
TotalSeconds            11131.0
HalfSeconds              5527.0
Name: 3942, dtype: object
Port Republic
 Age                          57
M/F                           M
City              Port Republic
State                        NJ
Country                     USA
Half            0 days 01:43:24
40K             0 days 03:25:44
Pace                    0:08:23
TotalSeconds            12344.0
HalfSeconds              6204.0
Name: 18429, dtype: object
Port Saint Lucie

Name: 21835, dtype: object
Portsmouth
 Age                          27
M/F                           F
City                 Portsmouth
State                        RI
Country                     USA
Half            0 days 01:28:45
40K             0 days 02:54:45
Pace                    0:07:04
TotalSeconds            10485.0
HalfSeconds              5325.0
Name: 11568, dtype: object
Portstmouth
 Age                          46
M/F                           F
City                Portstmouth
State                        NH
Country                     USA
Half            0 days 01:43:36
40K             0 days 03:23:21
Pace                    0:08:13
TotalSeconds            12201.0
HalfSeconds              6216.0
Name: 18801, dtype: object
Post Falls
 Age                          55
M/F                           M
City                 Post Falls
State                        ID
Country                     USA
Half            0 days 01:57:54
40K             0 days 04:03:23
Pace                    0:09:53
TotalSeconds            14603.0
HalfSeconds              7074.0
Name: 19831, dtype: object
Potomac
 Age                          24
M/F                           M
City                    Potomac
State                        MD
Country                     USA
Half            0 days 01:24:23
40K             0 days 02:40:02
Pace                    0:06:29
TotalSeconds             9602.0
HalfSeconds              5063.0
Name: 2383, dtype: object
Potomac Falls
 Age                          39
M/F                           M
City              Potomac Falls
State                        VA
Country                     USA
Half            0 days 01:37:57
40K             0 days 03:07:55
Pace                    0:07:34
TotalSeconds            11275.0
HalfSeconds              5877.0
Name: 5422, dtype: object
Potsdam
 Age                          49
M/F                           F
City                    Potsdam
State                        NY
Country                     USA
Half            0 days 02:05:25
40K             0 days 04:13:09
Pace                    0:10:10
TotalSeconds            15189.0
HalfSeconds              7525.0
Name: 24183, dtype: object
Potterville
 Age                          55
M/F                           M
City                Potterville
State                        MI
Country                     USA
Half            0 days 01:44:55
40K             0 days 04:56:26
Pace                    0:12:05
TotalSeconds            17786.0
HalfSeconds              6295.0
Name: 15510, dtype: object
Pottstown
 Age                          49
M/F                           M
City                  Pottstown
State                        PA
Country                     USA
Half            0 days 01:44:35
40K             0 days 03:32:05
Pace                    0:08:36
TotalSeconds            12725.0
HalfSeconds              6275.0
Name: 10050, dtype: object
Poughkeepsie
 Age                          51
M/F                           M
City               Poughkeepsie
State                        NY
Country                     USA
Half            0 days 01:42:36
40K             0 days 03:24:40
Pace                    0:08:15
TotalSeconds            12280.0
HalfSeconds              6156.0
Name: 10277, dtype: object
Poughquag
 Age                          61
M/F                           F
City                  Poughquag
State                        NY
Country                     USA
Half            0 days 02:00:10
40K             0 days 03:59:31
Pace                    0:09:42
TotalSeconds            14371.0
HalfSeconds              7210.0
Name: 25938, dtype: object
Poulsbo
 Age                          52
M/F                           M
City                    Poulsbo
State                        WA
Country                     USA
Half            0 days 01:35:19
40K             0 days 03:16:41
Pace                    0:08:00
TotalSeconds            11801.0
HalfSeconds              5719.0
Name: 5606, dtype: object
Pound Ridge
 Age                          61
M/F                           M
City                Pound Ridge
State                        NY
Country                     USA
Half            0 days 01:53:44
40K             0 days 04:00:22
Pace                    0:09:53
TotalSeconds            14422.0
HalfSeconds              6824.0
Name: 22969, dtype: object
Poway
 Age                          28
M/F                           F
City                      Poway
State                        CA
Country                     USA
Half            0 days 01:32:39
40K             0 days 03:02:56
Pace                    0:07:23
TotalSeconds            10976.0
HalfSeconds              5559.0
Name: 8480, dtype: object
Powder Springs
 Age                          59
M/F                           F
City             Powder Springs
State                        GA
Country                     USA
Half            0 days 02:00:43
40K             0 days 04:00:23
Pace                    0:09:42
TotalSeconds            14423.0
HalfSeconds              7243.0
Name: 25401, dtype: object
Powell
 Age                          39
M/F                           M
City                     Powell
State                        OH
Country                     USA
Half            0 days 01:20:15
40K             0 days 02:50:19
Pace                    0:06:56
TotalSeconds            10219.0
HalfSeconds              4815.0
Name: 551, dtype: object
Powhatan
 Age                          41
M/F                           F
City                   Powhatan
State                        VA
Country                     USA
Half            0 days 01:44:15
40K             0 days 03:21:20
Pace                    0:08:07
TotalSeconds            12080.0
HalfSeconds              6255.0
Name: 16789, dtype: object
Pownal
 Age                          56
M/F                           M
City                     Pownal
State                        ME
Country                     USA
Half            0 days 01:38:19
40K             0 days 03:13:11
Pace                    0:07:50
TotalSeconds            11591.0
HalfSeconds              5899.0
Name: 10338, dtype: object
Pozzuolo Del Friuli
 Age                              59
M/F                               M
City            Pozzuolo Del Friuli
State                           NaN
Country                         ITA
Half                0 days 01:41:57
40K                 0 days 03:26:54
Pace                        0:08:26
TotalSeconds                12414.0
HalfSeconds                  6117.0
Name: 10498, dtype: object
Prague
 Age                          66
M/F                           M
City                     Prague
State                       NaN
Country                     CZE
Half            0 days 02:29:24
40K             0 days 05:07:41
Pace                    0:12:33
TotalSeconds            18461.0
HalfSeconds              8964.0
Name: 31513, dtype: object
Prague 8 - Bohnice
 Age                             35
M/F                              M
City            Prague 8 - Bohnice
State                          NaN
Country                        CZE
Half               0 days 01:30:54
40K                0 days 03:06:45
Pace                       0:07:35
TotalSeconds               11205.0
HalfSeconds                 5454.0
Name: 7068, dtype: object
Prague 9
 Age                          30
M/F                           F
City                   Prague 9
State                       NaN
Country                     CZE
Half            0 days 01:51:51
40K             0 days 03:55:50
Pace                    0:09:32
TotalSeconds            14150.0
HalfSeconds              6711.0
Name: 17524, dtype: object
Praha 10
 Age                          40
M/F                           M
City                   Praha 10
State                       NaN
Country                     CZE
Half            0 days 01:34:01
40K             0 days 03:00:18
Pace                    0:07:16
TotalSeconds            10818.0
HalfSeconds              5641.0
Name: 8346, dtype: object
Praha 5
 Age                          56
M/F                           M
City                    Praha 5
State                       NaN
Country                     CZE
Half            0 days 01:46:27
40K             0 days 03:39:43
Pace                    0:08:55
TotalSeconds            13183.0
HalfSeconds              6387.0
Name: 16590, dtype: object
Praha 9
 Age                          33
M/F                           F
City                    Praha 9
State                       NaN
Country                     CZE
Half            0 days 01:42:37
40K             0 days 03:26:07
Pace                    0:08:21
TotalSeconds            12367.0
HalfSeconds              6157.0
Name: 17765, dtype: object
Prairie Village
 Age                          27
M/F                           M
City            Prairie Village
State                        KS
Country                     USA
Half            0 days 01:21:34
40K             0 days 02:42:12
Pace                    0:06:35
TotalSeconds             9732.0
HalfSeconds              4894.0
Name: 1677, dtype: object
Prairieville
 Age                          39
M/F                           M
City               Prairieville
State                        LA
Country                     USA
Half            0 days 01:29:26
40K             0 days 02:52:33
Pace                    0:06:59
TotalSeconds            10353.0
HalfSeconds              5366.0
Name: 4574, dtype: object
Prescott
 Age                          34
M/F                           M
City                   Prescott
State                        AZ
Country                     USA
Half            0 days 01:26:00
40K             0 days 02:50:58
Pace                    0:06:57
TotalSeconds            10258.0
HalfSeconds              5160.0
Name: 4401, dtype: object
Presque Isle
 Age                          29
M/F                           F
City               Presque Isle
State                        ME
Country                     USA
Half            0 days 01:48:41
40K             0 days 03:35:00
Pace                    0:08:42
TotalSeconds            12900.0
HalfSeconds              6521.0
Name: 18098, dtype: object
Preston
 Age                          34
M/F                           F
City                    Preston
State                        ID
Country                     USA
Half            0 days 01:42:23
40K             0 days 03:32:39
Pace                    0:08:37
TotalSeconds            12759.0
HalfSeconds              6143.0
Name: 9402, dtype: object
Prevost
 Age                          50
M/F                           M
City                    Prevost
State                        QC
Country                     CAN
Half            0 days 01:36:08
40K             0 days 03:11:50
Pace                    0:07:46
TotalSeconds            11510.0
HalfSeconds              5768.0
Name: 7307, dtype: object
Price
 Age                          34
M/F                           F
City                      Price
State                        UT
Country                     USA
Half            0 days 02:00:40
40K             0 days 04:04:32
Pace                    0:09:54
TotalSeconds            14672.0
HalfSeconds              7240.0
Name: 18105, dtype: object
Prides Crossing
 Age                          55
M/F                           F
City            Prides Crossing
State                        MA
Country                     USA
Half            0 days 02:40:44
40K             0 days 05:20:43
Pace                    0:12:52
TotalSeconds            19243.0
HalfSeconds              9644.0
Name: 30676, dtype: object
Prince George
 Age                          26
M/F                           F
City              Prince George
State                        BC
Country                     CAN
Half            0 days 01:27:22
40K             0 days 02:51:16
Pace                    0:06:55
TotalSeconds            10276.0
HalfSeconds              5242.0
Name: 3920, dtype: object
Princeton
 Age                          49
M/F                           M
City                  Princeton
State                        NJ
Country                     USA
Half            0 days 01:32:38
40K             0 days 03:02:40
Pace                    0:07:23
TotalSeconds            10960.0
HalfSeconds              5558.0
Name: 8163, dtype: object
Princeton Jct
 Age                          41
M/F                           M
City              Princeton Jct
State                        NJ
Country                     USA
Half            0 days 01:31:05
40K             0 days 03:09:27
Pace                    0:07:48
TotalSeconds            11367.0
HalfSeconds              5465.0
Name: 6106, dtype: object
Princeton Junction
 Age                             22
M/F                              M
City            Princeton Junction
State                           NJ
Country                        USA
Half               0 days 01:26:59
40K                0 days 03:18:23
Pace                       0:08:00
TotalSeconds               11903.0
HalfSeconds                 5219.0
Name: 1488, dtype: object
Princeville
 Age                          33
M/F                           F
City                Princeville
State                        IL
Country                     USA
Half            0 days 01:44:42
40K             0 days 03:26:07
Pace                    0:08:20
TotalSeconds            12367.0
HalfSeconds              6282.0
Name: 11414, dtype: object
Prineville
 Age                          46
M/F                           M
City                 Prineville
State                        OR
Country                     USA
Half            0 days 01:41:29
40K             0 days 03:28:45
Pace                    0:08:28
TotalSeconds            12525.0
HalfSeconds              6089.0
Name: 10468, dtype: object
Prinsenbeek
 Age                          46
M/F                           F
City                Prinsenbeek
State                       NaN
Country                     NED
Half            0 days 02:05:00
40K             0 days 03:59:24
Pace                    0:09:37
TotalSeconds            14364.0
HalfSeconds              7500.0
Name: 31278, dtype: object
Prior Lake
 Age                          38
M/F                           M
City                 Prior Lake
State                        MN
Country                     USA
Half            0 days 01:31:47
40K             0 days 02:56:54
Pace                    0:07:08
TotalSeconds            10614.0
HalfSeconds              5507.0
Name: 5004, dtype: object
Proctor
 Age                          40
M/F                           F
City                    Proctor
State                        MN
Country                     USA
Half            0 days 01:45:52
40K             0 days 03:29:23
Pace                    0:08:28
TotalSeconds            12563.0
HalfSeconds              6352.0
Name: 19694, dtype: object
Proctorsville
 Age                          42
M/F                           F
City              Proctorsville
State                        VT
Country                     USA
Half            0 days 01:58:45
40K             0 days 03:47:28
Pace                    0:09:10
TotalSeconds            13648.0
HalfSeconds              7125.0
Name: 26664, dtype: object
Prospect
 Age                          54
M/F                           M
City                   Prospect
State                        KY
Country                     USA
Half            0 days 01:34:08
40K             0 days 03:10:13
Pace                    0:07:43
TotalSeconds            11413.0
HalfSeconds              5648.0
Name: 11045, dtype: object
Prospect Heights
 Age                           49
M/F                            M
City            Prospect Heights
State                         IL
Country                      USA
Half             0 days 01:57:05
40K              0 days 03:56:31
Pace                     0:09:37
TotalSeconds             14191.0
HalfSeconds               7025.0
Name: 11672, dtype: object
Prosper
 Age                          37
M/F                           F
City                    Prosper
State                        TX
Country                     USA
Half            0 days 01:41:39
40K             0 days 03:20:02
Pace                    0:08:04
TotalSeconds            12002.0
HalfSeconds              6099.0
Name: 14753, dtype: object
Providence
 Age                          47
M/F                           M
City                 Providence
State                        RI
Country                     USA
Half            0 days 01:23:07
40K             0 days 02:43:27
Pace                    0:06:39
TotalSeconds             9807.0
HalfSeconds              4987.0
Name: 1248, dtype: object
Providencia, Santiago
 Age                                52
M/F                                 M
City            Providencia, Santiago
State                             NaN
Country                           CHI
Half                  0 days 01:35:30
40K                   0 days 03:08:20
Pace                          0:07:37
TotalSeconds                  11300.0
HalfSeconds                    5730.0
Name: 10369, dtype: object
Provo
 Age                          27
M/F                           M
City                      Provo
State                        UT
Country                     USA
Half            0 days 01:21:28
40K             0 days 02:36:30
Pace                    0:06:18
TotalSeconds             9390.0
HalfSeconds              4888.0
Name: 791, dtype: object
Provo Canyon
 Age                          61
M/F                           M
City               Provo Canyon
State                        UT
Country                     USA
Half            0 days 01:51:29
40K             0 days 03:38:03
Pace                    0:08:48
TotalSeconds            13083.0
HalfSeconds              6689.0
Name: 18908, dtype: object
Prunay
 Age                          49
M/F                           M
City                     Prunay
State                       NaN
Country                     FRA
Half            0 days 02:18:55
40K             0 days 04:44:32
Pace                    0:11:27
TotalSeconds            17072.0
HalfSeconds              8335.0
Name: 31583, dtype: object
Puebla
 Age                          35
M/F                           M
City                     Puebla
State                       NaN
Country                     MEX
Half            0 days 01:26:48
40K             0 days 02:51:18
Pace                    0:06:57
TotalSeconds            10278.0
HalfSeconds              5208.0
Name: 3130, dtype: object
Pueblo
 Age                          51
M/F                           M
City                     Pueblo
State                        CO
Country                     USA
Half            0 days 01:32:00
40K             0 days 02:58:38
Pace                    0:07:13
TotalSeconds            10718.0
HalfSeconds              5520.0
Name: 10078, dtype: object
Puerto Ordaz
 Age                          58
M/F                           M
City               Puerto Ordaz
State                       NaN
Country                     VEN
Half            0 days 01:49:52
40K             0 days 03:40:54
Pace                    0:09:00
TotalSeconds            13254.0
HalfSeconds              6592.0
Name: 20545, dtype: object
Pula
 Age                          45
M/F                           M
City                       Pula
State                       NaN
Country                     ITA
Half            0 days 01:30:34
40K             0 days 03:05:09
Pace                    0:07:30
TotalSeconds            11109.0
HalfSeconds              5434.0
Name: 8219, dtype: object
Pula (ca)
 Age                          38
M/F                           M
City                  Pula (ca)
State                       NaN
Country                     ITA
Half            0 days 01:19:13
40K             0 days 02:44:35
Pace                    0:06:38
TotalSeconds             9875.0
HalfSeconds              4753.0
Name: 308, dtype: object
Pulaski
 Age                          51
M/F                           F

Quevert
 Age                          59
M/F                           M
City                    Quevert
State                       NaN
Country                     FRA
Half            0 days 01:59:29
40K             0 days 04:28:21
Pace                    0:10:52
TotalSeconds            16101.0
HalfSeconds              7169.0
Name: 14743, dtype: object
Quezon City
 Age                          39
M/F                           M
City                Quezon City
State                       NaN
Country                     PHI
Half            0 days 02:16:37
40K             0 days 04:35:10
Pace                    0:11:06
TotalSeconds            16510.0
HalfSeconds              8197.0
Name: 30240, dtype: object
Quincy
 Age                          25
M/F                           M
City                     Quincy
State                        MA
Country                     USA
Half            0 days 01:21:29
40K             0 days 02:40:43
Pace                    0:06:29
TotalSeconds             9643.0
HalfSeconds              4889.0
Name: 1982, dtype: object
Quinton
 Age                          35
M/F                           F
City                    Quinton
State                        VA
Country                     USA
Half            0 days 01:54:57
40K             0 days 03:52:43
Pace                    0:09:31
TotalSeconds            13963.0
HalfSeconds              6897.0
Name: 18898, dtype: object
Quispamsis
 Age                          26
M/F                           M
City                 Quispamsis
State                        NB
Country                     CAN
Half            0 days 01:21:22
40K             0 days 02:43:05
Pace                    0:06:36
TotalSeconds             9785.0
HalfSeconds              4882.0
Name: 1236, dtype: object
Quito
 Age                          42
M/F                           M
City                      Quito
State                       NaN
Country                     ECU
Half            0 days 01:31:21
40K             0 days 02:56:28
Pace                    0:07:08
TotalSeconds            10588.0
HalfSeconds              5481.0
Name: 5630, dtype: object
Québec
 Age                          28
M/F                           M
City                     Québec
State                        QC
Country                     CAN
Half            0 days 01:24:35
40K             0 days 02:45:33
Pace                    0:06:42
TotalSeconds             9933.0
HalfSeconds              5075.0
Name: 1813, dtype: object
Raanana
 Age                          51
M/F                           M
City                    Raanana
State                       NaN
Country                     ISR
Half            0 days 02:42:16
40K             0 days 05:24:27
Pace                    0:13:04
TotalSeconds            19467.0
HalfSeconds              9736.0
Name: 30993, dtype: object
Raceland
 Age                          36
M/F                           F
City                   Raceland
State                        LA
Country                     USA
Half            0 days 01:57:20
40K             0 days 03:56:03
Pace                    0:09:33
TotalSeconds            14163.0
HalfSeconds              7040.0
Name: 11445, dtype: object
Racine
 Age                          50
M/F                           M
City                     Racine
State                        WI
Country                     USA
Half            0 days 01:46:08
40K             0 days 03:32:59
Pace                    0:08:39
TotalSeconds            12779.0
HalfSeconds              6368.0
Name: 12169, dtype: object
Radebeul
 Age                          36
M/F                           M
City                   Radebeul
State                       NaN
Country                     GER
Half            0 days 01:54:39
40K             0 days 03:51:54
Pace                    0:09:23
TotalSeconds            13914.0
HalfSeconds              6879.0
Name: 31773, dtype: object
Raeford
 Age                          50
M/F                           M
City                    Raeford
State                        NC
Country                     USA
Half            0 days 01:53:16
40K             0 days 03:43:49
Pace                    0:09:02
TotalSeconds            13429.0
HalfSeconds              6796.0
Name: 26150, dtype: object
Rahway
 Age                          24
M/F                           M
City                     Rahway
State                        NJ
Country                     USA
Half            0 days 01:34:24
40K             0 days 03:42:12
Pace                    0:08:58
TotalSeconds            13332.0
HalfSeconds              5664.0
Name: 617, dtype: object
Raleigh
 Age                          28
M/F                           M
City                    Raleigh
State                        NC
Country                     USA
Half            0 days 01:21:57
40K             0 days 02:44:14
Pace                    0:06:39
TotalSeconds             9854.0
HalfSeconds              4917.0
Name: 1019, dtype: object
Ralston
 Age                          48
M/F                           M
City                    Ralston
State                        NE
Country                     USA
Half            0 days 01:40:06
40K             0 days 03:17:04
Pace                    0:07:58
TotalSeconds            11824.0
HalfSeconds              6006.0
Name: 7564, dtype: object
Ramsey
 Age                          41
M/F                           M
City                     Ramsey
State                        NJ
Country                     USA
Half            0 days 02:02:21
40K             0 days 04:07:57
Pace                    0:10:05
TotalSeconds            14877.0
HalfSeconds              7341.0
Name: 30011, dtype: object
Rancho Cordova
 Age                          60
M/F                           F
City             Rancho Cordova
State                        CA
Country                     USA
Half            0 days 01:40:37
40K             0 days 03:21:31
Pace                    0:08:09
TotalSeconds            12091.0
HalfSeconds              6037.0
Name: 11639, dtype: object
Rancho Cucamonga
 Age                           47
M/F                            M
City            Rancho Cucamonga
State                         CA
Country                      USA
Half             0 days 01:31:14
40K              0 days 03:01:09
Pace                     0:07:19
TotalSeconds             10869.0
HalfSeconds               5474.0
Name: 4322, dtype: object
Rancho Palos Verdes
 Age                              26
M/F                               M
City            Rancho Palos Verdes
State                            CA
Country                         USA
Half                0 days 01:25:36
40K                 0 days 03:01:10
Pace                        0:07:19
TotalSeconds                10870.0
HalfSeconds                  5136.0
Name: 1368, dtype: object
Rancho Santa Fe
 Age                          22
M/F                           M
City            Rancho Santa Fe
State                        CA
Country                     USA
Half            0 days 01:18:22
40K             0 days 02:41:45
Pace                    0:06:31
TotalSeconds             9705.0
HalfSeconds              4702.0
Name: 214, dtype: object
Rancho Santa Margarita
 Age                                 53
M/F                                  M
City            Rancho Santa Margarita
State                               CA
Country                            USA
Half                   0 days 01:33:56
40K                    0 days 03:03:58
Pace                           0:07:27
TotalSeconds                   11038.0
HalfSeconds                     5636.0
Name: 8124, dtype: object
Randleman
 Age                          47
M/F                           M
City                  Randleman
State                        NC
Country                     USA
Half            0 days 01:36:26
40K             0 days 03:26:46
Pace                    0:08:23
TotalSeconds            12406.0
HalfSeconds              5786.0
Name: 8968, dtype: object
Randolph
 Age                          44
M/F                           M
City                   Randolph
State                        NJ
Country                     USA
Half            0 days 01:21:28
40K             0 days 02:38:31
Pace                    0:06:24
TotalSeconds             9511.0
HalfSeconds              4888.0
Name: 1656, dtype: object
Randolph Center
 Age                          43
M/F                           F
City            Randolph Center
State                        VT
Country                     USA
Half            0 days 01:38:07
40K             0 days 03:07:44
Pace                    0:07:33
TotalSeconds            11264.0
HalfSeconds              5887.0
Name: 6055, dtype: object
Randwick
 Age                          38
M/F                           F
City                   Randwick
State                       NaN
Country                     AUS
Half            0 days 01:33:11
40K             0 days 03:05:32
Pace                    0:07:31
TotalSeconds            11132.0
HalfSeconds              5591.0
Name: 8392, dtype: object
Ransomville
 Age                          36
M/F                           F
City                Ransomville
State                        NY
Country                     USA
Half            0 days 01:51:02
40K             0 days 03:50:32
Pace                    0:09:18
TotalSeconds            13832.0
HalfSeconds              6662.0
Name: 18580, dtype: object
Rapid City
 Age                          27
M/F                           F
City                 Rapid City
State                        SD
Country                     USA
Half            0 days 01:41:24
40K             0 days 03:15:33
Pace                    0:07:51
TotalSeconds            11733.0
HalfSeconds              6084.0
Name: 16293, dtype: object
Ratoath
 Age                          50
M/F                           M
City                    Ratoath
State                       NaN
Country                     IRL
Half            0 days 01:22:22
40K             0 days 03:16:50
Pace                    0:07:59
TotalSeconds            11810.0
HalfSeconds              4942.0
Name: 1119, dtype: object
Ravenna
 Age                          52
M/F                           M
City                    Ravenna
State                       NaN
Country                     ITA
Half            0 days 01:42:20
40K             0 days 03:44:20
Pace                    0:09:10
TotalSeconds            13460.0
HalfSeconds              6140.0
Name: 13496, dtype: object
Rayham
 Age                          38
M/F                           M
City                     Rayham
State                        MA
Country                     USA
Half            0 days 02:29:06
40K             0 days 04:59:06
Pace                    0:12:05
TotalSeconds            17946.0
HalfSeconds              8946.0
Name: 29370, dtype: object
Raymond
 Age                          31
M/F                           M
City                    Raymond
State                        NH
Country                     USA
Half            0 days 01:23:51
40K             0 days 02:52:56
Pace                    0:07:00
TotalSeconds            10376.0
HalfSeconds              5031.0
Name: 523, dtype: object
Raymore
 Age                          47
M/F                           M
City                    Raymore
State                        MO
Country                     USA
Half            0 days 01:34:53
40K             0 days 03:21:39
Pace                    0:08:08
TotalSeconds            12099.0
HalfSeconds              5693.0
Name: 9154, dtype: object
Raynham
 Age                          39
M/F                           M
City                    Raynham
State                        MA
Country                     USA
Half            0 days 01:58:56
40K             0 days 03:46:08
Pace                    0:09:05
TotalSeconds            13568.0
HalfSeconds              7136.0
Name: 27132, dtype: object
Raytown
 Age                          61
M/F                           M
City                    Raytown
State                        MO
Country                     USA
Half            0 days 01:57:00
40K             0 days 04:24:05
Pace                    0:10:48
TotalSeconds            15845.0
HalfSeconds              7020.0
Name: 22237, dtype: object
Reading
 Age                          42
M/F                           M
City                    Reading
State                        MA
Country                     USA
Half            0 days 01:22:58
40K             0 days 02:42:22
Pace                    0:06:35
TotalSeconds             9742.0
HalfSeconds              4978.0
Name: 3967, dtype: object
Readsboro
 Age                          55
M/F                           M
City                  Readsboro
State                        VT
Country                     USA
Half            0 days 01:58:28
40K             0 days 04:10:30
Pace                    0:10:09
TotalSeconds            15030.0
HalfSeconds              7108.0
Name: 15573, dtype: object
Readville
 Age                          37
M/F                           M
City                  Readville
State                        MA
Country                     USA
Half            0 days 01:58:26
40K             0 days 04:15:03
Pace                    0:10:27
TotalSeconds            15303.0
HalfSeconds              7106.0
Name: 32077, dtype: object
Recife
 Age                          53
M/F                           M
City                     Recife
State                       NaN
Country                     BRA
Half            0 days 01:45:08
40K             0 days 03:23:41
Pace                    0:08:13
TotalSeconds            12221.0
HalfSeconds              6308.0
Name: 30268, dtype: object
Red Bank
 Age                          27
M/F                           M
City                   Red Bank
State                        NJ
Country                     USA
Half            0 days 01:26:56
40K             0 days 02:53:05
Pace                    0:07:02
TotalSeconds            10385.0
HalfSeconds              5216.0
Name: 3453, dtype: object
Red Bluff
 Age                          57
M/F                           F
City                  Red Bluff
State                        CA
Country                     USA
Half            0 days 01:53:17
40K             0 days 03:52:46
Pace                    0:09:24
TotalSeconds            13966.0
HalfSeconds              6797.0
Name: 21776, dtype: object
Red Deer
 Age                          33
M/F                           M
City                   Red Deer
State                        AB
Country                     CAN
Half            0 days 01:26:18
40K             0 days 03:17:17
Pace                    0:08:07
TotalSeconds            11837.0
HalfSeconds              5178.0
Name: 3466, dtype: object
Red Hook
 Age                          49
M/F                           M
City                   Red Hook
State                        NY
Country                     USA
Half            0 days 01:43:53
40K             0 days 03:41:47
Pace                    0:08:58
TotalSeconds            13307.0
HalfSeconds              6233.0
Name: 11402, dtype: object
Red Rock
 Age                          51
M/F                           M
City                   Red Rock
State                        TX
Country                     USA
Half            0 days 01:37:31
40K             0 days 03:26:53
Pace                    0:08:27
TotalSeconds            12413.0
HalfSeconds              5851.0
Name: 7246, dtype: object
Redding
 Age                          50
M/F                           M
City                    Redding
State                        CA
Country                     USA
Half            0 days 01:39:32
40K             0 days 03:12:55
Pace                    0:07:49
TotalSeconds            11575.0
HalfSeconds              5972.0
Name: 10595, dtype: object
Redfern, Sydney
 Age                          57
M/F                           M
City            Redfern, Sydney
State                       NaN
Country                     AUS
Half            0 days 02:07:32
40K             0 days 05:04:00
Pace                    0:12:13
TotalSeconds            18240.0
HalfSeconds              7652.0
Name: 9262, dtype: object
Redlands
 Age                          38
M/F                           M
City                   Redlands
State                        CA
Country                     USA
Half            0 days 01:19:46
40K             0 days 02:41:12
Pace                    0:06:31
TotalSeconds             9672.0
HalfSeconds              4786.0
Name: 590, dtype: object
Redmond
 Age                          32
M/F                           M
City                    Redmond
State                        WA
Country                     USA
Half            0 days 01:27:03
40K             0 days 02:52:13
Pace                    0:06:58
TotalSeconds            10333.0
HalfSeconds              5223.0
Name: 4862, dtype: object
Redondo
 Age                          49
M/F                           M
City                    Redondo
State                        CA
Country                     USA
Half            0 days 01:49:57
40K             0 days 03:42:23
Pace                    0:09:05
TotalSeconds            13343.0
HalfSeconds              6597.0
Name: 7670, dtype: object
Redondo Beach
 Age                          28
M/F                           M
City              Redondo Beach
State                        CA
Country                     USA
Half            0 days 01:26:50
40K             0 days 02:48:26
Pace                    0:06:47
TotalSeconds            10106.0
HalfSeconds              5210.0
Name: 3565, dtype: object
Redwood City
 Age                          22
M/F                           M
City               Redwood City
State                        CA
Country                     USA
Half            0 days 01:20:49
40K             0 days 02:35:18
Pace                    0:06:15
TotalSeconds             9318.0
HalfSeconds              4849.0
Name: 1153, dtype: object
Reedsburg
 Age                          39
M/F                           M
City                  Reedsburg
State                        WI
Country                     USA
Half            0 days 03:37:49
40K             0 days 07:54:21
Pace                    0:19:13
TotalSeconds            28461.0
HalfSeconds             13069.0
Name: 29403, dtype: object
Reggio Emilia
 Age                          56
M/F                           M
City              Reggio Emilia
State                       NaN
Country                     ITA
Half            0 days 02:17:05
40K             0 days 04:42:36
Pace                    0:11:23
TotalSeconds            16956.0
HalfSeconds              8225.0
Name: 31511, dtype: object
Regina
 Age                          55
M/F                           M
City                     Regina
State                        SK
Country                     CAN
Half            0 days 01:37:53
40K             0 days 03:11:37
Pace                    0:07:44
TotalSeconds            11497.0
HalfSeconds              5873.0
Name: 12525, dtype: object
Rego Park
 Age                          38
M/F                           M
City                  Rego Park
State                        NY
Country                     USA
Half            0 days 01:34:37
40K             0 days 03:37:43
Pace                    0:08:53
TotalSeconds            13063.0
HalfSeconds              5677.0
Name: 4450, dtype: object
Rehoboth
 Age                          34
M/F                           F
City                   Rehoboth
State                        MA
Country                     USA
Half            0 days 01:39:35
40K             0 days 03:15:19
Pace                    0:07:52
TotalSeconds            11719.0
HalfSeconds              5975.0
Name: 10291, dtype: object
Rehoboth Beach
 Age                          65
M/F                           F
City             Rehoboth Beach
State                        DE
Country                     USA
Half            0 days 02:43:00

Richfield
 Age                          56
M/F                           M
City                  Richfield
State                        WI
Country                     USA
Half            0 days 01:43:07
40K             0 days 03:22:09
Pace                    0:08:08
TotalSeconds            12129.0
HalfSeconds              6187.0
Name: 13434, dtype: object
Richfield Springs
 Age                            56
M/F                             M
City            Richfield Springs
State                          NY
Country                       USA
Half              0 days 01:46:03
40K               0 days 03:28:20
Pace                      0:08:25
TotalSeconds              12500.0
HalfSeconds                6363.0
Name: 17233, dtype: object
Richland
 Age                          34
M/F                           M
City                   Richland
State                        WA
Country                     USA
Half            0 days 01:24:38
40K             0 days 03:03:28
Pace                    0:07:27
TotalSeconds            11008.0
HalfSeconds              5078.0
Name: 1245, dtype: object
Richland Center
 Age                          58
M/F                           F
City            Richland Center
State                        WI
Country                     USA
Half            0 days 01:49:18
40K             0 days 03:30:34
Pace                    0:08:31
TotalSeconds            12634.0
HalfSeconds              6558.0
Name: 22727, dtype: object
Richmond
 Age                          22
M/F                           M
City                   Richmond
State                        VA
Country                     USA
Half            0 days 01:17:33
40K             0 days 02:36:51
Pace                    0:06:23
TotalSeconds             9411.0
HalfSeconds              4653.0
Name: 250, dtype: object
Richmond Heights
 Age                           39
M/F                            M
City            Richmond Heights
State                         MO
Country                      USA
Half             0 days 01:19:52
40K              0 days 02:36:12
Pace                     0:06:19
TotalSeconds              9372.0
HalfSeconds               4792.0
Name: 759, dtype: object
Richmond Hill
 Age                          37
M/F                           M
City              Richmond Hill
State                        GA
Country                     USA
Half            0 days 01:27:44
40K             0 days 02:47:52
Pace                    0:06:46
TotalSeconds            10072.0
HalfSeconds              5264.0
Name: 2379, dtype: object
Ridgefield
 Age                          46
M/F                           M
City                 Ridgefield
State                        CT
Country                     USA
Half            0 days 01:35:55
40K             0 days 03:07:24
Pace                    0:07:33
TotalSeconds            11244.0
HalfSeconds              5755.0
Name: 9216, dtype: object
Ridgeley
 Age                          31
M/F                           M
City                   Ridgeley
State                        WV
Country                     USA
Half            0 days 01:16:29
40K             0 days 02:31:00
Pace                    0:06:06
TotalSeconds             9060.0
HalfSeconds              4589.0
Name: 297, dtype: object
Ridgetown
 Age                          61
M/F                           M
City                  Ridgetown
State                        ON
Country                     CAN
Half            0 days 02:08:43
40K             0 days 04:12:05
Pace                    0:10:11
TotalSeconds            15125.0
HalfSeconds              7723.0
Name: 22051, dtype: object
Ridgewood
 Age                          35
M/F                           M
City                  Ridgewood
State                        NJ
Country                     USA
Half            0 days 01:32:05
40K             0 days 03:06:41
Pace                    0:07:33
TotalSeconds            11201.0
HalfSeconds              5525.0
Name: 1786, dtype: object
Ridgway
 Age                          55
M/F                           F
City                    Ridgway
State                        CO
Country                     USA
Half            0 days 02:06:17
40K             0 days 04:18:47
Pace                    0:10:29
TotalSeconds            15527.0
HalfSeconds              7577.0
Name: 25599, dtype: object
Riedstadt
 Age                          60
M/F                           M
City                  Riedstadt
State                       NaN
Country                     GER
Half            0 days 02:18:23
40K             0 days 04:31:07
Pace                    0:10:53
TotalSeconds            16267.0
HalfSeconds              8303.0
Name: 31859, dtype: object
Riemerling
 Age                          47
M/F                           M
City                 Riemerling
State                       NaN
Country                     GER
Half            0 days 02:00:23
40K             0 days 04:00:58
Pace                    0:09:48
TotalSeconds            14458.0
HalfSeconds              7223.0
Name: 31876, dtype: object
Riga
 Age                          27
M/F                           M
City                       Riga
State                       NaN
Country                     LAT
Half            0 days 01:23:47
40K             0 days 02:41:29
Pace                    0:06:30
TotalSeconds             9689.0
HalfSeconds              5027.0
Name: 471, dtype: object
Rigewood
 Age                          50
M/F                           M
City                   Rigewood
State                        NJ
Country                     USA
Half            0 days 01:43:28
40K             0 days 03:34:57
Pace                    0:08:42
TotalSeconds            12897.0
HalfSeconds              6208.0
Name: 11440, dtype: object
Rimersburg
 Age                          25
M/F                           F
City                 Rimersburg
State                        PA
Country                     USA
Half            0 days 01:47:13
40K             0 days 03:36:06
Pace                    0:08:42
TotalSeconds            12966.0
HalfSeconds              6433.0
Name: 16971, dtype: object
Rimouski
 Age                          29
M/F                           M
City                   Rimouski
State                        QC
Country                     CAN
Half            0 days 00:00:00
40K             0 days 02:35:36
Pace                    0:06:16
TotalSeconds             9336.0
HalfSeconds                 0.0
Name: 663, dtype: object
Rindge
 Age                          41
M/F                           M
City                     Rindge
State                        NH
Country                     USA
Half            0 days 01:30:06
40K             0 days 02:56:56
Pace                    0:07:08
TotalSeconds            10616.0
HalfSeconds              5406.0
Name: 2338, dtype: object
Ringgold
 Age                          42
M/F                           F
City                   Ringgold
State                        GA
Country                     USA
Half            0 days 01:51:25
40K             0 days 03:41:12
Pace                    0:08:56
TotalSeconds            13272.0
HalfSeconds              6685.0
Name: 20718, dtype: object
Ringoes
 Age                          48
M/F                           F
City                    Ringoes
State                        NJ
Country                     USA
Half            0 days 01:40:46
40K             0 days 03:17:43
Pace                    0:07:59
TotalSeconds            11863.0
HalfSeconds              6046.0
Name: 9181, dtype: object
Ringwood
 Age                          64
M/F                           F
City                   Ringwood
State                        IL
Country                     USA
Half            0 days 02:04:26
40K             0 days 04:07:41
Pace                    0:10:00
TotalSeconds            14861.0
HalfSeconds              7466.0
Name: 25704, dtype: object
Rinteln
 Age                          44
M/F                           M
City                    Rinteln
State                       NaN
Country                     GER
Half            0 days 02:18:05
40K             0 days 04:33:08
Pace                    0:11:02
TotalSeconds            16388.0
HalfSeconds              8285.0
Name: 31120, dtype: object
Rio De Janeiro
 Age                          44
M/F                           M
City             Rio De Janeiro
State                       NaN
Country                     BRA
Half            0 days 01:19:48
40K             0 days 02:45:35
Pace                    0:06:45
TotalSeconds             9935.0
HalfSeconds              4788.0
Name: 342, dtype: object
Rio De Janeiro - Rj
 Age                              36
M/F                               F
City            Rio De Janeiro - Rj
State                           NaN
Country                         BRA
Half                0 days 01:51:36
40K                 0 days 03:40:46
Pace                        0:08:57
TotalSeconds                13246.0
HalfSeconds                  6696.0
Name: 20313, dtype: object
Rio De Janeiro Rj22450-080
 Age                                     52
M/F                                      F
City            Rio De Janeiro Rj22450-080
State                                  NaN
Country                                BRA
Half                       0 days 02:19:44
40K                        0 days 04:37:52
Pace                               0:11:13
TotalSeconds                       16672.0
HalfSeconds                         8384.0
Name: 20991, dtype: object
Rio Grande
 Age                          57
M/F                           M
City                 Rio Grande
State                        PR
Country                     USA
Half            0 days 01:45:55
40K             0 days 03:49:08
Pace                    0:09:21
TotalSeconds            13748.0
HalfSeconds              6355.0
Name: 19782, dtype: object
Rio Rancho
 Age                          37
M/F                           F
City                 Rio Rancho
State                        NM
Country                     USA
Half            0 days 01:35:59
40K             0 days 03:08:44
Pace                    0:07:37
TotalSeconds            11324.0
HalfSeconds              5759.0
Name: 7019, dtype: object
Ripley
 Age                          47
M/F                           M
City                     Ripley
State                        ON
Country                     CAN
Half            0 days 01:33:24
40K             0 days 03:08:38
Pace                    0:07:37
TotalSeconds            11318.0
HalfSeconds              5604.0
Name: 7544, dtype: object
Ripollet
 Age                          42
M/F                           M
City                   Ripollet
State                       NaN
Country                     ESP
Half            0 days 01:42:07
40K             0 days 03:40:48
Pace                    0:08:58
TotalSeconds            13248.0
HalfSeconds              6127.0
Name: 5547, dtype: object
Ripon
 Age                          48
M/F                           F
City                      Ripon
State                        CA
Country                     USA
Half            0 days 01:57:14
40K             0 days 04:01:18
Pace                    0:09:43
TotalSeconds            14478.0
HalfSeconds              7034.0
Name: 22472, dtype: object
Rising Sun
 Age                          69
M/F                           M
City                 Rising Sun
State                        MD
Country                     USA
Half            0 days 02:08:26
40K             0 days 04:10:41
Pace                    0:10:05
TotalSeconds            15041.0
HalfSeconds              7706.0
Name: 25173, dtype: object
Risskov
 Age                          60
M/F                           M
City                    Risskov
State                       NaN
Country                     DEN
Half            0 days 02:00:25
40K             0 days 04:15:47
Pace                    0:10:25
TotalSeconds            15347.0
HalfSeconds              7225.0
Name: 30297, dtype: object
Riva
 Age                          20
M/F                           M
City                       Riva
State                        MD
Country                     USA
Half            0 days 01:21:40
40K             0 days 03:00:13
Pace                    0:07:18
TotalSeconds            10813.0
HalfSeconds              4900.0
Name: 3510, dtype: object
River Edge
 Age                          49
M/F                           M
City                 River Edge
State                        NJ
Country                     USA
Half            0 days 01:39:16
40K             0 days 03:19:19
Pace                    0:08:04
TotalSeconds            11959.0
HalfSeconds              5956.0
Name: 11540, dtype: object
River Falls
 Age                          54
M/F                           F
City                River Falls
State                        WI
Country                     USA
Half            0 days 01:56:56
40K             0 days 03:49:30
Pace                    0:09:16
TotalSeconds            13770.0
HalfSeconds              7016.0
Name: 24365, dtype: object
River Forest
 Age                          36
M/F                           M
City               River Forest
State                        IL
Country                     USA
Half            0 days 01:26:29
40K             0 days 02:56:50
Pace                    0:07:11
TotalSeconds            10610.0
HalfSeconds              5189.0
Name: 2066, dtype: object
River Heights
 Age                          48
M/F                           F
City              River Heights
State                        UT
Country                     USA
Half            0 days 02:32:59
40K             0 days 05:16:11
Pace                    0:12:43
TotalSeconds            18971.0
HalfSeconds              9179.0
Name: 31401, dtype: object
River Vale
 Age                          50
M/F                           M
City                 River Vale
State                        NJ
Country                     USA
Half            0 days 01:41:52
40K             0 days 03:16:51
Pace                    0:07:57
TotalSeconds            11811.0
HalfSeconds              6112.0
Name: 12512, dtype: object
River Valley
 Age                          48
M/F                           M
City               River Valley
State                       NaN
Country                     SIN
Half            0 days 01:44:55
40K             0 days 03:45:05
Pace                    0:09:06
TotalSeconds            13505.0
HalfSeconds              6295.0
Name: 3362, dtype: object
Riverdale
 Age                          26
M/F                           M
City                  Riverdale
State                        GA
Country                     USA
Half            0 days 01:25:30
40K             0 days 02:59:28
Pace                    0:07:23
TotalSeconds            10768.0
HalfSeconds              5130.0
Name: 5318, dtype: object
Riverside
 Age                          24
M/F                           M
City                  Riverside
State                        IL
Country                     USA
Half            0 days 01:21:25
40K             0 days 02:39:24
Pace                    0:06:29
TotalSeconds             9564.0
HalfSeconds              4885.0
Name: 1771, dtype: object
Riverstick
 Age                          52
M/F                           M
City                 Riverstick
State                       NaN
Country                     IRL
Half            0 days 01:41:46
40K             0 days 03:18:18
Pace                    0:08:02
TotalSeconds            11898.0
HalfSeconds              6106.0
Name: 13530, dtype: object
Riverton
 Age                          54
M/F                           M
City                   Riverton
State                        UT
Country                     USA
Half            0 days 01:41:39
40K             0 days 03:17:51
Pace                    0:08:00
TotalSeconds            11871.0
HalfSeconds              6099.0
Name: 13284, dtype: object
Riverview
 Age                          40
M/F                           M
City                  Riverview
State                        NB
Country                     CAN
Half            0 days 01:22:01
40K             0 days 02:39:26
Pace                    0:06:26
TotalSeconds             9566.0
HalfSeconds              4921.0
Name: 1949, dtype: object
Rives Jct
 Age                          55
M/F                           M
City                  Rives Jct
State                        MI
Country                     USA
Half            0 days 01:51:40
40K             0 days 04:25:26
Pace                    0:10:46
TotalSeconds            15926.0
HalfSeconds              6700.0
Name: 15238, dtype: object
Rivesville
 Age                          32
M/F                           M
City                 Rivesville
State                        WV
Country                     USA
Half            0 days 01:28:23
40K             0 days 02:52:34
Pace                    0:06:58
TotalSeconds            10354.0
HalfSeconds              5303.0
Name: 3944, dtype: object
Riviere-Du-Loup
 Age                          47
M/F                           F
City            Riviere-Du-Loup
State                        QC
Country                     CAN
Half            0 days 01:46:31
40K             0 days 03:31:50
Pace                    0:08:32
TotalSeconds            12710.0
HalfSeconds              6391.0
Name: 17958, dtype: object
Rivignano - Udine
 Age                            61
M/F                             M
City            Rivignano - Udine
State                         NaN
Country                       ITA
Half              0 days 01:54:24
40K               0 days 04:07:30
Pace                      0:10:24
TotalSeconds              14850.0
HalfSeconds                6864.0
Name: 31427, dtype: object
Road Town, Tortola, British Virgin Islands
 Age                                                     37
M/F                                                      F
City            Road Town, Tortola, British Virgin Islands
State                                                  NaN
Country                                                VGB
Half                                       0 days 01:39:09
40K                                        0 days 03:20:31
Pace                                               0:08:08
TotalSeconds                                       12031.0
HalfSeconds                                         5949.0
Name: 11623, dtype: object
Roaming Shores
 Age                          54
M/F                           M
City             Roaming Shores
State                        OH
Country                     USA
Half            0 days 01:36:17
40K             0 days 03:11:16
Pace                    0:07:44
TotalSeconds            11476.0
HalfSeconds              5777.0
Name: 9835, dtype: object
Roan Mountain
 Age                          52
M/F                           M
City              Roan Mountain
State                        TN
Country                     USA
Half            0 days 01:43:24
40K             0 days 03:38:15
Pace                    0:08:53
TotalSeconds            13095.0
HalfSeconds              6204.0
Name: 13544, dtype: object
Roanoke
 Age                          52
M/F                           M
City                    Roanoke
State                        VA
Country                     USA
Half            0 days 01:39:34
40K             0 days 03:04:44
Pace                    0:07:24
TotalSeconds            11084.0
HalfSeconds              5974.0
Name: 9141, dtype: object
Roaring Spring
 Age                          51
M/F                           M
City             Roaring Spring
State                        PA
Country                     USA
Half            0 days 01:46:58
40K             0 days 03:38:55
Pace                    0:08:52
TotalSeconds            13135.0
HalfSeconds              6418.0
Name: 9863, dtype: object
Robbinsdale
 Age                          29
M/F                           F
City                Robbinsdale

Rockville Centre
 Age                           42
M/F                            M
City            Rockville Centre
State                         NY
Country                      USA
Half             0 days 01:32:13
40K              0 days 03:05:18
Pace                     0:07:31
TotalSeconds             11118.0
HalfSeconds               5533.0
Name: 6399, dtype: object
Rockwall
 Age                          46
M/F                           M
City                   Rockwall
State                        TX
Country                     USA
Half            0 days 01:21:23
40K             0 days 02:44:44
Pace                    0:06:40
TotalSeconds             9884.0
HalfSeconds              4883.0
Name: 1126, dtype: object
Rockwell
 Age                          33
M/F                           M
City                   Rockwell
State                        NC
Country                     USA
Half            0 days 01:31:55
40K             0 days 03:23:51
Pace                    0:08:23
TotalSeconds            12231.0
HalfSeconds              5515.0
Name: 4153, dtype: object
Rocky Hill
 Age                          52
M/F                           M
City                 Rocky Hill
State                        CT
Country                     USA
Half            0 days 01:39:33
40K             0 days 03:14:36
Pace                    0:07:51
TotalSeconds            11676.0
HalfSeconds              5973.0
Name: 10976, dtype: object
Rocky Mount
 Age                          53
M/F                           F
City                Rocky Mount
State                        VA
Country                     USA
Half            0 days 02:10:24
40K             0 days 04:23:17
Pace                    0:10:36
TotalSeconds            15797.0
HalfSeconds              7824.0
Name: 21258, dtype: object
Rocky Point
 Age                          56
M/F                           M
City                Rocky Point
State                        NC
Country                     USA
Half            0 days 01:43:13
40K             0 days 03:21:23
Pace                    0:08:10
TotalSeconds            12083.0
HalfSeconds              6193.0
Name: 16061, dtype: object
Rocky River
 Age                          31
M/F                           F
City                Rocky River
State                        OH
Country                     USA
Half            0 days 01:38:57
40K             0 days 03:13:06
Pace                    0:07:56
TotalSeconds            11586.0
HalfSeconds              5937.0
Name: 4435, dtype: object
Rodgau
 Age                          59
M/F                           M
City                     Rodgau
State                       NaN
Country                     GER
Half            0 days 01:56:49
40K             0 days 03:47:30
Pace                    0:09:11
TotalSeconds            13650.0
HalfSeconds              7009.0
Name: 31877, dtype: object
Roedermark
 Age                          60
M/F                           M
City                 Roedermark
State                       NaN
Country                     GER
Half            0 days 02:04:12
40K             0 days 04:10:19
Pace                    0:10:03
TotalSeconds            15019.0
HalfSeconds              7452.0
Name: 31744, dtype: object
Roeland Park
 Age                          40
M/F                           M
City               Roeland Park
State                        KS
Country                     USA
Half            0 days 01:46:05
40K             0 days 04:05:28
Pace                    0:09:59
TotalSeconds            14728.0
HalfSeconds              6365.0
Name: 7447, dtype: object
Rogers
 Age                          34
M/F                           M
City                     Rogers
State                        AR
Country                     USA
Half            0 days 01:27:39
40K             0 days 02:51:54
Pace                    0:06:57
TotalSeconds            10314.0
HalfSeconds              5259.0
Name: 2334, dtype: object
Rogersville
 Age                          41
M/F                           F
City                Rogersville
State                        MO
Country                     USA
Half            0 days 01:55:54
40K             0 days 03:51:30
Pace                    0:09:21
TotalSeconds            13890.0
HalfSeconds              6954.0
Name: 21697, dtype: object
Rohnert Park
 Age                          64
M/F                           M
City               Rohnert Park
State                        CA
Country                     USA
Half            0 days 02:09:00
40K             0 days 04:59:34
Pace                    0:12:19
TotalSeconds            17974.0
HalfSeconds              7740.0
Name: 19031, dtype: object
Rolesville
 Age                          34
M/F                           F
City                 Rolesville
State                        NC
Country                     USA
Half            0 days 01:57:16
40K             0 days 04:14:01
Pace                    0:10:17
TotalSeconds            15241.0
HalfSeconds              7036.0
Name: 16476, dtype: object
Rolla
 Age                          31
M/F                           F
City                      Rolla
State                        MO
Country                     USA
Half            0 days 01:28:51
40K             0 days 02:51:04
Pace                    0:06:53
TotalSeconds            10264.0
HalfSeconds              5331.0
Name: 8561, dtype: object
Rolling Meadows
 Age                          32
M/F                           F
City            Rolling Meadows
State                        IL
Country                     USA
Half            0 days 01:40:14
40K             0 days 03:20:38
Pace                    0:08:06
TotalSeconds            12038.0
HalfSeconds              6014.0
Name: 16881, dtype: object
Rollinsford
 Age                          34
M/F                           M
City                Rollinsford
State                        NH
Country                     USA
Half            0 days 01:58:19
40K             0 days 04:14:56
Pace                    0:10:22
TotalSeconds            15296.0
HalfSeconds              7099.0
Name: 27142, dtype: object
Roma
 Age                          51
M/F                           M
City                       Roma
State                       NaN
Country                     ITA
Half            0 days 01:29:07
40K             0 days 02:55:51
Pace                    0:07:05
TotalSeconds            10551.0
HalfSeconds              5347.0
Name: 2420, dtype: object
Rome
 Age                          40
M/F                           M
City                       Rome
State                        NY
Country                     USA
Half            0 days 01:31:25
40K             0 days 02:57:16
Pace                    0:07:10
TotalSeconds            10636.0
HalfSeconds              5485.0
Name: 6105, dtype: object
Romeoville
 Age                          55
M/F                           M
City                 Romeoville
State                        IL
Country                     USA
Half            0 days 01:45:03
40K             0 days 03:26:51
Pace                    0:08:17
TotalSeconds            12411.0
HalfSeconds              6303.0
Name: 8957, dtype: object
Romulus
 Age                          60
M/F                           F
City                    Romulus
State                        NY
Country                     USA
Half            0 days 02:06:20
40K             0 days 04:38:02
Pace                    0:11:15
TotalSeconds            16682.0
HalfSeconds              7580.0
Name: 25788, dtype: object
Roncadelle Brescia
 Age                             48
M/F                              F
City            Roncadelle Brescia
State                          NaN
Country                        ITA
Half               0 days 01:49:21
40K                0 days 03:50:32
Pace                       0:09:19
TotalSeconds               13832.0
HalfSeconds                 6561.0
Name: 13605, dtype: object
Ronda-Malaga
 Age                          56
M/F                           M
City               Ronda-Malaga
State                       NaN
Country                     ESP
Half            0 days 02:14:50
40K             0 days 04:56:15
Pace                    0:12:02
TotalSeconds            17775.0
HalfSeconds              8090.0
Name: 30973, dtype: object
Ronkonkoma
 Age                          44
M/F                           M
City                 Ronkonkoma
State                        NY
Country                     USA
Half            0 days 01:26:26
40K             0 days 02:52:21
Pace                    0:07:02
TotalSeconds            10341.0
HalfSeconds              5186.0
Name: 1108, dtype: object
Ronks
 Age                          25
M/F                           F
City                      Ronks
State                        PA
Country                     USA
Half            0 days 01:47:11
40K             0 days 03:41:02
Pace                    0:08:56
TotalSeconds            13262.0
HalfSeconds              6431.0
Name: 18041, dtype: object
Ronnang
 Age                          25
M/F                           M
City                    Ronnang
State                       NaN
Country                     SWE
Half            0 days 01:28:16
40K             0 days 03:00:37
Pace                    0:07:17
TotalSeconds            10837.0
HalfSeconds              5296.0
Name: 2230, dtype: object
Roodepoort, Johannesburg
 Age                                   42
M/F                                    F
City            Roodepoort, Johannesburg
State                                NaN
Country                              RSA
Half                     0 days 02:28:34
40K                      0 days 05:00:17
Pace                             0:12:07
TotalSeconds                     18017.0
HalfSeconds                       8914.0
Name: 31633, dtype: object
Roosevelt
 Age                          42
M/F                           M
City                  Roosevelt
State                        NY
Country                     USA
Half            0 days 01:27:48
40K             0 days 02:53:18
Pace                    0:07:00
TotalSeconds            10398.0
HalfSeconds              5268.0
Name: 2717, dtype: object
Roscoe
 Age                          53
M/F                           M
City                     Roscoe
State                        IL
Country                     USA
Half            0 days 01:41:55
40K             0 days 03:39:25
Pace                    0:08:54
TotalSeconds            13165.0
HalfSeconds              6115.0
Name: 13759, dtype: object
Rose Bay
 Age                          41
M/F                           M
City                   Rose Bay
State                       NaN
Country                     AUS
Half            0 days 01:33:59
40K             0 days 03:06:38
Pace                    0:07:32
TotalSeconds            11198.0
HalfSeconds              5639.0
Name: 6324, dtype: object
Rose Valley
 Age                          42
M/F                           F
City                Rose Valley
State                        PA
Country                     USA
Half            0 days 02:15:48
40K             0 days 04:46:28
Pace                    0:11:34
TotalSeconds            17188.0
HalfSeconds              8148.0
Name: 20784, dtype: object
Rosemere
 Age                          55
M/F                           M
City                   Rosemere
State                        QC
Country                     CAN
Half            0 days 01:44:50
40K             0 days 03:22:11
Pace                    0:08:10
TotalSeconds            12131.0
HalfSeconds              6290.0
Name: 14370, dtype: object
Rosemount
 Age                          51
M/F                           M
City                  Rosemount
State                        MN
Country                     USA
Half            0 days 01:45:05
40K             0 days 03:24:45
Pace                    0:08:16
TotalSeconds            12285.0
HalfSeconds              6305.0
Name: 11501, dtype: object
Roseville
 Age                          41
M/F                           M
City                  Roseville
State                        MN
Country                     USA
Half            0 days 01:29:11
40K             0 days 02:52:33
Pace                    0:06:59
TotalSeconds            10353.0
HalfSeconds              5351.0
Name: 3095, dtype: object
Rosheim
 Age                          51
M/F                           M
City                    Rosheim
State                       NaN
Country                     FRA
Half            0 days 01:28:39
40K             0 days 03:09:31
Pace                    0:07:40
TotalSeconds            11371.0
HalfSeconds              5319.0
Name: 1422, dtype: object
Roskilde
 Age                          46
M/F                           M
City                   Roskilde
State                       NaN
Country                     DEN
Half            0 days 01:38:50
40K             0 days 03:17:15
Pace                    0:07:59
TotalSeconds            11835.0
HalfSeconds              5930.0
Name: 9780, dtype: object
Roslin
 Age                          71
M/F                           F
City                     Roslin
State                        ON
Country                     CAN
Half            0 days 02:21:17
40K             0 days 04:51:49
Pace                    0:11:48
TotalSeconds            17509.0
HalfSeconds              8477.0
Name: 26086, dtype: object
Roslindale
 Age                          29
M/F                           M
City                 Roslindale
State                        MA
Country                     USA
Half            0 days 01:15:01
40K             0 days 02:29:18
Pace                    0:06:03
TotalSeconds             8958.0
HalfSeconds              4501.0
Name: 1286, dtype: object
Roslyn
 Age                          60
M/F                           M
City                     Roslyn
State                        NY
Country                     USA
Half            0 days 01:43:30
40K             0 days 03:29:07
Pace                    0:08:27
TotalSeconds            12547.0
HalfSeconds              6210.0
Name: 17538, dtype: object
Rosslyn
 Age                          49
M/F                           F
City                    Rosslyn
State                        ON
Country                     CAN
Half            0 days 01:48:35
40K             0 days 03:34:16
Pace                    0:08:41
TotalSeconds            12856.0
HalfSeconds              6515.0
Name: 19904, dtype: object
Rosslyn Farms
 Age                          47
M/F                           M
City              Rosslyn Farms
State                        PA
Country                     USA
Half            0 days 01:31:56
40K             0 days 02:54:44
Pace                    0:07:02
TotalSeconds            10484.0
HalfSeconds              5516.0
Name: 7126, dtype: object
Rossmoor
 Age                          46
M/F                           F
City                   Rossmoor
State                        CA
Country                     USA
Half            0 days 03:40:16
40K             0 days 00:00:00
Pace                    0:17:51
TotalSeconds                0.0
HalfSeconds             13216.0
Name: 31985, dtype: object
Rossville
 Age                          47
M/F                           M
City                  Rossville
State                        IN
Country                     USA
Half            0 days 01:39:33
40K             0 days 03:09:38
Pace                    0:07:38
TotalSeconds            11378.0
HalfSeconds              5973.0
Name: 12171, dtype: object
Rostock
 Age                          50
M/F                           M
City                    Rostock
State                       NaN
Country                     GER
Half            0 days 01:47:14
40K             0 days 03:30:35
Pace                    0:08:31
TotalSeconds            12635.0
HalfSeconds              6434.0
Name: 14859, dtype: object
Rosville
 Age                          24
M/F                           F
City                   Rosville
State                        GA
Country                     USA
Half            0 days 01:50:30
40K             0 days 03:39:09
Pace                    0:08:53
TotalSeconds            13149.0
HalfSeconds              6630.0
Name: 14441, dtype: object
Roswell
 Age                          44
M/F                           M
City                    Roswell
State                        GA
Country                     USA
Half            0 days 01:30:44
40K             0 days 02:54:00
Pace                    0:07:01
TotalSeconds            10440.0
HalfSeconds              5444.0
Name: 3827, dtype: object
Rotherham
 Age                          37
M/F                           F
City                  Rotherham
State                       NaN
Country                     GBR
Half            0 days 01:54:59
40K             0 days 03:48:53
Pace                    0:09:13
TotalSeconds            13733.0
HalfSeconds              6899.0
Name: 18561, dtype: object
Rothesay
 Age                          41
M/F                           F
City                   Rothesay
State                        NB
Country                     CAN
Half            0 days 01:55:54
40K             0 days 04:00:35
Pace                    0:09:43
TotalSeconds            14435.0
HalfSeconds              6954.0
Name: 20625, dtype: object
Rotterdam
 Age                          46
M/F                           M
City                  Rotterdam
State                       NaN
Country                     NED
Half            0 days 01:43:00
40K             0 days 03:19:01
Pace                    0:08:01
TotalSeconds            11941.0
HalfSeconds              6180.0
Name: 10513, dtype: object
Rouen
 Age                          43
M/F                           F
City                      Rouen
State                       NaN
Country                     FRA
Half            0 days 01:35:02
40K             0 days 03:11:06
Pace                    0:07:44
TotalSeconds            11466.0
HalfSeconds              5702.0
Name: 9281, dtype: object
Round Hill
 Age                          41
M/F                           F
City                 Round Hill
State                        VA
Country                     USA
Half            0 days 01:49:14
40K             0 days 03:38:48
Pace                    0:08:52
TotalSeconds            13128.0
HalfSeconds              6554.0
Name: 19902, dtype: object
Round Lake
 Age                          56
M/F                           M
City                 Round Lake
State                        NY
Country                     USA
Half            0 days 01:43:11
40K             0 days 03:25:14
Pace                    0:08:20
TotalSeconds            12314.0
HalfSeconds              6191.0
Name: 12036, dtype: object
Round Rock
 Age                          43
M/F                           M
City                 Round Rock
State                        TX
Country                     USA
Half            0 days 01:38:44
40K             0 days 03:18:22
Pace                    0:08:12
TotalSeconds            11902.0
HalfSeconds              5924.0
Name: 7533, dtype: object
Rouyn-Noranda
 Age                          44
M/F                           M
City              Rouyn-Noranda
State                        QC
Country                     CAN
Half            0 days 01:28:14
40K             0 days 02:56:04
Pace                    0:07:08
TotalSeconds            10564.0
HalfSeconds              5294.0
Name: 2713, dtype: object
Rowayton
 Age                          56
M/F                           M
City                   Rowayton
State                        CT
Country                     USA
Half            0 days 01:42:38
40K             0 days 03:24:03
Pace                    0:08:15
TotalSeconds            12243.0
HalfSeconds              6158.0
Name: 15445, dtype: object
Rowley
 Age                          48
M/F                           F
City                     Rowley
State                        MA
Country                     USA

Name: 2368, dtype: object
Rutesheim
 Age                          50
M/F                           M
City                  Rutesheim
State                       NaN
Country                     GER
Half            0 days 01:39:41
40K             0 days 03:15:45
Pace                    0:07:55
TotalSeconds            11745.0
HalfSeconds              5981.0
Name: 16886, dtype: object
Rutherford
 Age                          28
M/F                           F
City                 Rutherford
State                        NJ
Country                     USA
Half            0 days 01:33:51
40K             0 days 03:11:31
Pace                    0:07:45
TotalSeconds            11491.0
HalfSeconds              5631.0
Name: 6941, dtype: object
Rutland
 Age                          49
M/F                           F
City                    Rutland
State                        MA
Country                     USA
Half            0 days 01:47:00
40K             0 days 03:22:55
Pace                    0:08:13
TotalSeconds            12175.0
HalfSeconds              6420.0
Name: 22456, dtype: object
Ry
 Age                          46
M/F                           M
City                         Ry
State                       NaN
Country                     DEN
Half            0 days 01:40:03
40K             0 days 03:20:49
Pace                    0:08:06
TotalSeconds            12049.0
HalfSeconds              6003.0
Name: 9045, dtype: object
Rydal
 Age                          65
M/F                           M
City                      Rydal
State                        PA
Country                     USA
Half            0 days 01:47:56
40K             0 days 03:27:41
Pace                    0:08:21
TotalSeconds            12461.0
HalfSeconds              6476.0
Name: 20381, dtype: object
Rye
 Age                          43
M/F                           M
City                        Rye
State                        NH
Country                     USA
Half            0 days 01:29:20
40K             0 days 02:51:12
Pace                    0:06:55
TotalSeconds            10272.0
HalfSeconds              5360.0
Name: 5785, dtype: object
S. Lancaster
 Age                          43
M/F                           F
City               S. Lancaster
State                        MA
Country                     USA
Half            0 days 01:45:38
40K             0 days 03:29:54
Pace                    0:08:28
TotalSeconds            12594.0
HalfSeconds              6338.0
Name: 17470, dtype: object
Saarbruecken
 Age                          44
M/F                           M
City               Saarbruecken
State                       NaN
Country                     GER
Half            0 days 01:40:26
40K             0 days 03:25:47
Pace                    0:08:18
TotalSeconds            12347.0
HalfSeconds              6026.0
Name: 31733, dtype: object
Sachse
 Age                          51
M/F                           F
City                     Sachse
State                        TX
Country                     USA
Half            0 days 01:44:39
40K             0 days 03:24:46
Pace                    0:08:16
TotalSeconds            12286.0
HalfSeconds              6279.0
Name: 24078, dtype: object
Sacile
 Age                          59
M/F                           M
City                     Sacile
State                       NaN
Country                     ITA
Half            0 days 01:41:22
40K             0 days 03:13:42
Pace                    0:07:48
TotalSeconds            11622.0
HalfSeconds              6082.0
Name: 31819, dtype: object
Sackville
 Age                          38
M/F                           F
City                  Sackville
State                        NB
Country                     CAN
Half            0 days 01:44:48
40K             0 days 03:28:10
Pace                    0:08:23
TotalSeconds            12490.0
HalfSeconds              6288.0
Name: 18118, dtype: object
Saco
 Age                          35
M/F                           M
City                       Saco
State                        ME
Country                     USA
Half            0 days 01:28:49
40K             0 days 02:58:02
Pace                    0:07:12
TotalSeconds            10682.0
HalfSeconds              5329.0
Name: 5351, dtype: object
Sacramento
 Age                          33
M/F                           M
City                 Sacramento
State                        CA
Country                     USA
Half            0 days 01:32:00
40K             0 days 02:50:00
Pace                    0:06:49
TotalSeconds            10200.0
HalfSeconds              5520.0
Name: 622, dtype: object
Sag Harbor
 Age                          28
M/F                           M
City                 Sag Harbor
State                        NY
Country                     USA
Half            0 days 01:25:30
40K             0 days 02:57:44
Pace                    0:07:10
TotalSeconds            10664.0
HalfSeconds              5130.0
Name: 1440, dtype: object
Sagamihara Kanagawa
 Age                              60
M/F                               F
City            Sagamihara Kanagawa
State                           NaN
Country                         JPN
Half                0 days 02:07:19
40K                 0 days 04:09:09
Pace                        0:10:01
TotalSeconds                14949.0
HalfSeconds                  7639.0
Name: 25063, dtype: object
Sagamore Beach
 Age                          45
M/F                           F
City             Sagamore Beach
State                        MA
Country                     USA
Half            0 days 02:22:19
40K             0 days 04:57:04
Pace                    0:12:01
TotalSeconds            17824.0
HalfSeconds              8539.0
Name: 30753, dtype: object
Sagamore Hills
 Age                          29
M/F                           F
City             Sagamore Hills
State                        OH
Country                     USA
Half            0 days 01:47:50
40K             0 days 03:36:26
Pace                    0:08:44
TotalSeconds            12986.0
HalfSeconds              6470.0
Name: 17837, dtype: object
Saginaw
 Age                          41
M/F                           M
City                    Saginaw
State                        MI
Country                     USA
Half            0 days 01:27:22
40K             0 days 02:51:50
Pace                    0:06:57
TotalSeconds            10310.0
HalfSeconds              5242.0
Name: 1871, dtype: object
Saguenay
 Age                          39
M/F                           M
City                   Saguenay
State                        QC
Country                     CAN
Half            0 days 01:17:17
40K             0 days 02:35:16
Pace                    0:06:16
TotalSeconds             9316.0
HalfSeconds              4637.0
Name: 552, dtype: object
Saint -Georges
 Age                          37
M/F                           M
City             Saint -Georges
State                        QC
Country                     CAN
Half            0 days 01:33:24
40K             0 days 03:21:44
Pace                    0:08:09
TotalSeconds            12104.0
HalfSeconds              5604.0
Name: 4595, dtype: object
Saint Agatha
 Age                          35
M/F                           F
City               Saint Agatha
State                        ME
Country                     USA
Half            0 days 01:27:42
40K             0 days 02:48:19
Pace                    0:06:48
TotalSeconds            10099.0
HalfSeconds              5262.0
Name: 5438, dtype: object
Saint Albans
 Age                          37
M/F                           F
City               Saint Albans
State                        VT
Country                     USA
Half            0 days 01:52:00
40K             0 days 03:57:33
Pace                    0:09:33
TotalSeconds            14253.0
HalfSeconds              6720.0
Name: 19638, dtype: object
Saint Augusta
 Age                          36
M/F                           M
City              Saint Augusta
State                        MN
Country                     USA
Half            0 days 01:34:11
40K             0 days 03:16:03
Pace                    0:07:58
TotalSeconds            11763.0
HalfSeconds              5651.0
Name: 6818, dtype: object
Saint Augustine
 Age                          37
M/F                           M
City            Saint Augustine
State                        FL
Country                     USA
Half            0 days 01:29:18
40K             0 days 02:53:21
Pace                    0:07:00
TotalSeconds            10401.0
HalfSeconds              5358.0
Name: 5367, dtype: object
Saint Bernard
 Age                          26
M/F                           F
City              Saint Bernard
State                        OH
Country                     USA
Half            0 days 01:54:39
40K             0 days 03:49:27
Pace                    0:09:14
TotalSeconds            13767.0
HalfSeconds              6879.0
Name: 13968, dtype: object
Saint Bonifacius
 Age                           37
M/F                            F
City            Saint Bonifacius
State                         MN
Country                      USA
Half             0 days 01:58:47
40K              0 days 03:53:27
Pace                     0:09:24
TotalSeconds             14007.0
HalfSeconds               7127.0
Name: 19501, dtype: object
Saint Charles
 Age                          47
M/F                           M
City              Saint Charles
State                        IL
Country                     USA
Half            0 days 01:30:04
40K             0 days 03:00:49
Pace                    0:07:21
TotalSeconds            10849.0
HalfSeconds              5404.0
Name: 6011, dtype: object
Saint Clair
 Age                          39
M/F                           M
City                Saint Clair
State                        PA
Country                     USA
Half            0 days 01:29:10
40K             0 days 02:56:12
Pace                    0:07:10
TotalSeconds            10572.0
HalfSeconds              5350.0
Name: 5584, dtype: object
Saint Clair Shores
 Age                             27
M/F                              M
City            Saint Clair Shores
State                           MI
Country                        USA
Half               0 days 01:21:23
40K                0 days 02:36:59
Pace                       0:06:20
TotalSeconds                9419.0
HalfSeconds                 4883.0
Name: 629, dtype: object
Saint Clairsville
 Age                            25
M/F                             M
City            Saint Clairsville
State                          OH
Country                       USA
Half              0 days 01:17:29
40K               0 days 02:31:37
Pace                      0:06:07
TotalSeconds               9097.0
HalfSeconds                4649.0
Name: 600, dtype: object
Saint Cloud
 Age                          50
M/F                           M
City                Saint Cloud
State                        FL
Country                     USA
Half            0 days 01:33:29
40K             0 days 03:13:29
Pace                    0:07:51
TotalSeconds            11609.0
HalfSeconds              5609.0
Name: 7366, dtype: object
Saint Francis
 Age                          35
M/F                           F
City              Saint Francis
State                        WI
Country                     USA
Half            0 days 01:49:06
40K             0 days 03:27:18
Pace                    0:08:21
TotalSeconds            12438.0
HalfSeconds              6546.0
Name: 15185, dtype: object
Saint George
 Age                          35
M/F                           F
City               Saint George
State                        UT
Country                     USA
Half            0 days 01:30:39
40K             0 days 02:51:47
Pace                    0:06:54
TotalSeconds            10307.0
HalfSeconds              5439.0
Name: 991, dtype: object
Saint Helena
 Age                          49
M/F                           F
City               Saint Helena
State                        CA
Country                     USA
Half            0 days 01:41:25
40K             0 days 03:21:49
Pace                    0:08:08
TotalSeconds            12109.0
HalfSeconds              6085.0
Name: 10626, dtype: object
Saint James
 Age                          53
M/F                           M
City                Saint James
State                        NY
Country                     USA
Half            0 days 01:54:10
40K             0 days 03:45:17
Pace                    0:09:06
TotalSeconds            13517.0
HalfSeconds              6850.0
Name: 29906, dtype: object
Saint John
 Age                          36
M/F                           F
City                 Saint John
State                        NB
Country                     CAN
Half            0 days 01:38:31
40K             0 days 03:13:50
Pace                    0:07:50
TotalSeconds            11630.0
HalfSeconds              5911.0
Name: 10270, dtype: object
Saint John's
 Age                          40
M/F                           M
City               Saint John's
State                        NL
Country                     CAN
Half            0 days 01:21:39
40K             0 days 02:42:51
Pace                    0:06:37
TotalSeconds             9771.0
HalfSeconds              4899.0
Name: 1433, dtype: object
Saint Johns
 Age                          40
M/F                           M
City                Saint Johns
State                        FL
Country                     USA
Half            0 days 01:33:52
40K             0 days 03:04:31
Pace                    0:07:27
TotalSeconds            11071.0
HalfSeconds              5632.0
Name: 6944, dtype: object
Saint Joseph
 Age                          43
M/F                           M
City               Saint Joseph
State                        MI
Country                     USA
Half            0 days 01:29:51
40K             0 days 03:02:20
Pace                    0:07:22
TotalSeconds            10940.0
HalfSeconds              5391.0
Name: 5719, dtype: object
Saint Lambert
 Age                          52
M/F                           M
City              Saint Lambert
State                        QC
Country                     CAN
Half            0 days 01:37:20
40K             0 days 03:16:27
Pace                    0:07:56
TotalSeconds            11787.0
HalfSeconds              5840.0
Name: 7423, dtype: object
Saint Laurent
 Age                          45
M/F                           M
City              Saint Laurent
State                        QC
Country                     CAN
Half            0 days 01:28:02
40K             0 days 03:04:53
Pace                    0:07:26
TotalSeconds            11093.0
HalfSeconds              5282.0
Name: 1502, dtype: object
Saint Louis
 Age                          28
M/F                           M
City                Saint Louis
State                        MO
Country                     USA
Half            0 days 01:21:45
40K             0 days 02:34:23
Pace                    0:06:13
TotalSeconds             9263.0
HalfSeconds              4905.0
Name: 887, dtype: object
Saint Louis Park
 Age                           27
M/F                            M
City            Saint Louis Park
State                         MN
Country                      USA
Half             0 days 01:29:03
40K              0 days 02:54:08
Pace                     0:07:03
TotalSeconds             10448.0
HalfSeconds               5343.0
Name: 1811, dtype: object
Saint Paul
 Age                          34
M/F                           M
City                 Saint Paul
State                        MN
Country                     USA
Half            0 days 01:29:12
40K             0 days 02:48:48
Pace                    0:06:47
TotalSeconds            10128.0
HalfSeconds              5352.0
Name: 845, dtype: object
Saint Peters
 Age                          37
M/F                           F
City               Saint Peters
State                        MO
Country                     USA
Half            0 days 01:41:57
40K             0 days 03:22:18
Pace                    0:08:11
TotalSeconds            12138.0
HalfSeconds              6117.0
Name: 16818, dtype: object
Saint Petersburg
 Age                           33
M/F                            F
City            Saint Petersburg
State                         FL
Country                      USA
Half             0 days 01:36:18
40K              0 days 03:13:08
Pace                     0:07:49
TotalSeconds             11588.0
HalfSeconds               5778.0
Name: 10808, dtype: object
Saint Simons Island
 Age                              49
M/F                               M
City            Saint Simons Island
State                            GA
Country                         USA
Half                0 days 01:36:27
40K                 0 days 03:10:17
Pace                        0:07:43
TotalSeconds                11417.0
HalfSeconds                  5787.0
Name: 10482, dtype: object
Saint-Adelphe
 Age                          39
M/F                           F
City              Saint-Adelphe
State                        QC
Country                     CAN
Half            0 days 01:47:21
40K             0 days 03:26:35
Pace                    0:08:19
TotalSeconds            12395.0
HalfSeconds              6441.0
Name: 19075, dtype: object
Saint-Amable
 Age                          40
M/F                           M
City               Saint-Amable
State                        QC
Country                     CAN
Half            0 days 01:35:45
40K             0 days 03:09:54
Pace                    0:07:40
TotalSeconds            11394.0
HalfSeconds              5745.0
Name: 8861, dtype: object
Saint-Anaclet
 Age                          45
M/F                           M
City              Saint-Anaclet
State                        QC
Country                     CAN
Half            0 days 01:48:39
40K             0 days 03:35:07
Pace                    0:08:45
TotalSeconds            12907.0
HalfSeconds              6519.0
Name: 9316, dtype: object
Saint-Augustin-De-Desmaures
 Age                                      36
M/F                                       M
City            Saint-Augustin-De-Desmaures
State                                    QC
Country                                 CAN
Half                        0 days 01:29:03
40K                         0 days 03:09:23
Pace                                0:07:45
TotalSeconds                        11363.0
HalfSeconds                          5343.0
Name: 5403, dtype: object
Saint-Basile-Le-Grand
 Age                                53
M/F                                 M
City            Saint-Basile-Le-Grand
State                              QC
Country                           CAN
Half                  0 days 01:35:20
40K                   0 days 03:15:18
Pace                          0:07:57
TotalSeconds                  11718.0
HalfSeconds                    5720.0
Name: 10885, dtype: object
Saint-Eustache
 Age                          34
M/F                           M
City             Saint-Eustache
State                        QC
Country                     CAN
Half            0 days 01:29:40
40K             0 days 03:01:40
Pace                    0:07:22
TotalSeconds            10900.0
HalfSeconds              5380.0
Name: 5243, dtype: object
Saint-Georges-De-Champlain
 Age                                     41
M/F                                      F
City            Saint-Georges-De-Champlain
State                                   QC
Country                                CAN
Half                       0 days 01:45:58
40K                        0 days 03:27:09
Pace                               0:08:20
TotalSeconds                       12429.0
HalfSeconds                         6358.0
Name: 13305, dtype: object
Saint-Hippolyte
 Age                          50

Name: 14312, dtype: object
Saitama
 Age                          42
M/F                           M
City                    Saitama
State                       NaN
Country                     JPN
Half            0 days 01:22:35
40K             0 days 02:50:22
Pace                    0:07:00
TotalSeconds            10222.0
HalfSeconds              4955.0
Name: 262, dtype: object
Saitama-Shi
 Age                          51
M/F                           F
City                Saitama-Shi
State                       NaN
Country                     JPN
Half            0 days 01:54:25
40K             0 days 03:46:31
Pace                    0:09:06
TotalSeconds            13591.0
HalfSeconds              6865.0
Name: 22014, dtype: object
Sakai
 Age                          45
M/F                           F
City                      Sakai
State                       NaN
Country                     JPN
Half            0 days 02:11:11
40K             0 days 04:34:12
Pace                    0:10:59
TotalSeconds            16452.0
HalfSeconds              7871.0
Name: 24018, dtype: object
Sakura
 Age                          64
M/F                           M
City                     Sakura
State                       NaN
Country                     JPN
Half            0 days 01:53:02
40K             0 days 04:22:34
Pace                    0:10:34
TotalSeconds            15754.0
HalfSeconds              6782.0
Name: 15234, dtype: object
Salem
 Age                          24
M/F                           M
City                      Salem
State                        OR
Country                     USA
Half            0 days 01:22:31
40K             0 days 02:40:27
Pace                    0:06:29
TotalSeconds             9627.0
HalfSeconds              4951.0
Name: 1214, dtype: object
Salinas
 Age                          51
M/F                           F
City                    Salinas
State                        CA
Country                     USA
Half            0 days 01:47:12
40K             0 days 03:23:25
Pace                    0:08:12
TotalSeconds            12205.0
HalfSeconds              6432.0
Name: 20149, dtype: object
Saline
 Age                          44
M/F                           M
City                     Saline
State                        MI
Country                     USA
Half            0 days 01:31:09
40K             0 days 02:54:24
Pace                    0:07:01
TotalSeconds            10464.0
HalfSeconds              5469.0
Name: 5301, dtype: object
Salisbury
 Age                          33
M/F                           M
City                  Salisbury
State                        NC
Country                     USA
Half            0 days 01:24:42
40K             0 days 02:54:25
Pace                    0:07:04
TotalSeconds            10465.0
HalfSeconds              5082.0
Name: 1482, dtype: object
Salmon Arm
 Age                          37
M/F                           M
City                 Salmon Arm
State                        BC
Country                     CAN
Half            0 days 01:19:30
40K             0 days 02:37:24
Pace                    0:06:22
TotalSeconds             9444.0
HalfSeconds              4770.0
Name: 613, dtype: object
Salt Lake City
 Age                          25
M/F                           M
City             Salt Lake City
State                        UT
Country                     USA
Half            0 days 01:19:54
40K             0 days 02:39:20
Pace                    0:06:27
TotalSeconds             9560.0
HalfSeconds              4794.0
Name: 381, dtype: object
Salt Lake Cty
 Age                          55
M/F                           M
City              Salt Lake Cty
State                        UT
Country                     USA
Half            0 days 01:42:39
40K             0 days 03:27:40
Pace                    0:08:23
TotalSeconds            12460.0
HalfSeconds              6159.0
Name: 16202, dtype: object
Salta
 Age                          43
M/F                           F
City                      Salta
State                       NaN
Country                     ARG
Half            0 days 01:34:49
40K             0 days 03:09:42
Pace                    0:07:38
TotalSeconds            11382.0
HalfSeconds              5689.0
Name: 6786, dtype: object
Saltillo
 Age                          33
M/F                           F
City                   Saltillo
State                       NaN
Country                     MEX
Half            0 days 01:40:03
40K             0 days 03:29:34
Pace                    0:08:31
TotalSeconds            12574.0
HalfSeconds              6003.0
Name: 13575, dtype: object
Salvador
 Age                          48
M/F                           M
City                   Salvador
State                       NaN
Country                     BRA
Half            0 days 01:40:26
40K             0 days 03:16:32
Pace                    0:07:56
TotalSeconds            11792.0
HalfSeconds              6026.0
Name: 11933, dtype: object
Salyersville
 Age                          62
M/F                           M
City               Salyersville
State                        KY
Country                     USA
Half            0 days 02:30:20
40K             0 days 05:29:05
Pace                    0:13:25
TotalSeconds            19745.0
HalfSeconds              9020.0
Name: 22122, dtype: object
Samedan
 Age                          36
M/F                           F
City                    Samedan
State                       NaN
Country                     SUI
Half            0 days 01:45:58
40K             0 days 03:35:43
Pace                    0:08:44
TotalSeconds            12943.0
HalfSeconds              6358.0
Name: 19078, dtype: object
Sammamish
 Age                          45
M/F                           M
City                  Sammamish
State                        WA
Country                     USA
Half            0 days 01:33:42
40K             0 days 03:16:11
Pace                    0:07:58
TotalSeconds            11771.0
HalfSeconds              5622.0
Name: 11204, dtype: object
San Angelo
 Age                          25
M/F                           M
City                 San Angelo
State                        TX
Country                     USA
Half            0 days 01:31:18
40K             0 days 03:37:25
Pace                    0:08:47
TotalSeconds            13045.0
HalfSeconds              5478.0
Name: 1408, dtype: object
San Anselmo
 Age                          44
M/F                           M
City                San Anselmo
State                        CA
Country                     USA
Half            0 days 01:37:54
40K             0 days 03:34:01
Pace                    0:08:49
TotalSeconds            12841.0
HalfSeconds              5874.0
Name: 8016, dtype: object
San Antonio
 Age                          29
M/F                           M
City                San Antonio
State                        TX
Country                     USA
Half            0 days 01:19:47
40K             0 days 02:42:59
Pace                    0:06:36
TotalSeconds             9779.0
HalfSeconds              4787.0
Name: 3222, dtype: object
San Antono
 Age                          32
M/F                           M
City                 San Antono
State                        TX
Country                     USA
Half            0 days 02:30:26
40K             0 days 05:33:49
Pace                    0:13:27
TotalSeconds            20029.0
HalfSeconds              9026.0
Name: 29010, dtype: object
San Bernardino
 Age                          64
M/F                           M
City             San Bernardino
State                        CA
Country                     USA
Half            0 days 01:58:00
40K             0 days 04:08:19
Pace                    0:10:04
TotalSeconds            14899.0
HalfSeconds              7080.0
Name: 22978, dtype: object
San Bernardo
 Age                          44
M/F                           M
City               San Bernardo
State                       NaN
Country                     CHI
Half            0 days 01:22:07
40K             0 days 02:43:58
Pace                    0:06:38
TotalSeconds             9838.0
HalfSeconds              4927.0
Name: 1052, dtype: object
San Bruno
 Age                          37
M/F                           M
City                  San Bruno
State                        CA
Country                     USA
Half            0 days 01:36:16
40K             0 days 03:06:16
Pace                    0:07:28
TotalSeconds            11176.0
HalfSeconds              5776.0
Name: 5937, dtype: object
San Carlos
 Age                          45
M/F                           M
City                 San Carlos
State                        CA
Country                     USA
Half            0 days 01:41:04
40K             0 days 03:21:04
Pace                    0:08:06
TotalSeconds            12064.0
HalfSeconds              6064.0
Name: 12150, dtype: object
San Clemente
 Age                          41
M/F                           M
City               San Clemente
State                        CA
Country                     USA
Half            0 days 01:29:51
40K             0 days 02:55:11
Pace                    0:07:04
TotalSeconds            10511.0
HalfSeconds              5391.0
Name: 4116, dtype: object
San Diego
 Age                          29
M/F                           M
City                  San Diego
State                        CA
Country                     USA
Half            0 days 01:15:05
40K             0 days 02:26:46
Pace                    0:05:56
TotalSeconds             8806.0
HalfSeconds              4505.0
Name: 150, dtype: object
San Dimas
 Age                          23
M/F                           F
City                  San Dimas
State                        CA
Country                     USA
Half            0 days 01:31:00
40K             0 days 02:57:48
Pace                    0:07:11
TotalSeconds            10668.0
HalfSeconds              5460.0
Name: 7027, dtype: object
San Donato Milanese - Milano
 Age                                       45
M/F                                        M
City            San Donato Milanese - Milano
State                                    NaN
Country                                  ITA
Half                         0 days 01:46:32
40K                          0 days 03:42:36
Pace                                 0:09:13
TotalSeconds                         13356.0
HalfSeconds                           6392.0
Name: 31455, dtype: object
San Fernando, Buenos Aires
 Age                                     49
M/F                                      M
City            San Fernando, Buenos Aires
State                                  NaN
Country                                ARG
Half                       0 days 01:38:14
40K                        0 days 03:19:34
Pace                               0:08:12
TotalSeconds                       11974.0
HalfSeconds                         5894.0
Name: 11007, dtype: object
San Francisco
 Age                          28
M/F                           M
City              San Francisco
State                        CA
Country                     USA
Half            0 days 01:18:12
40K             0 days 02:29:21
Pace                    0:06:02
TotalSeconds             8961.0
HalfSeconds              4692.0
Name: 796, dtype: object
San Gabriel
 Age                          65
M/F                           M
City                San Gabriel
State                        CA
Country                     USA
Half            0 days 01:59:01
40K             0 days 04:22:36
Pace                    0:10:37
TotalSeconds            15756.0
HalfSeconds              7141.0
Name: 22878, dtype: object
San Gregorio Matese
 Age                              47
M/F                               M
City            San Gregorio Matese
State                           NaN
Country                         ITA
Half                0 days 01:44:08
40K                 0 days 03:25:07
Pace                        0:08:18
TotalSeconds                12307.0
HalfSeconds                  6248.0
Name: 9774, dtype: object
San Jose
 Age                          33
M/F                           M
City                   San Jose
State                        CA
Country                     USA
Half            0 days 01:22:22
40K             0 days 02:39:34
Pace                    0:06:25
TotalSeconds             9574.0
HalfSeconds              4942.0
Name: 1952, dtype: object
San Jose Costa Rica
 Age                              58
M/F                               F
City            San Jose Costa Rica
State                           NaN
Country                         CRC
Half                0 days 01:53:04
40K                 0 days 03:48:48
Pace                        0:09:15
TotalSeconds                13728.0
HalfSeconds                  6784.0
Name: 24796, dtype: object
San José
 Age                          26
M/F                           M
City                   San José
State                       NaN
Country                     CRC
Half            0 days 01:25:03
40K             0 days 02:45:21
Pace                    0:06:42
TotalSeconds             9921.0
HalfSeconds              5103.0
Name: 1468, dtype: object
San Juan
 Age                          37
M/F                           M
City                   San Juan
State                        PR
Country                     USA
Half            0 days 01:26:33
40K             0 days 02:51:03
Pace                    0:06:54
TotalSeconds            10263.0
HalfSeconds              5193.0
Name: 2741, dtype: object
San Juan Capistrano
 Age                              47
M/F                               F
City            San Juan Capistrano
State                            CA
Country                         USA
Half                0 days 01:41:50
40K                 0 days 03:19:46
Pace                        0:08:05
TotalSeconds                11986.0
HalfSeconds                  6110.0
Name: 10681, dtype: object
San Juan Del Rio
 Age                           33
M/F                            F
City            San Juan Del Rio
State                        NaN
Country                      MEX
Half             0 days 01:55:26
40K              0 days 03:46:03
Pace                     0:09:08
TotalSeconds             13563.0
HalfSeconds               6926.0
Name: 14354, dtype: object
San Leandro
 Age                          53
M/F                           F
City                San Leandro
State                        CA
Country                     USA
Half            0 days 02:08:11
40K             0 days 04:20:36
Pace                    0:10:30
TotalSeconds            15636.0
HalfSeconds              7691.0
Name: 24747, dtype: object
San Luis Obispo
 Age                          44
M/F                           M
City            San Luis Obispo
State                        CA
Country                     USA
Half            0 days 01:28:34
40K             0 days 02:59:24
Pace                    0:07:19
TotalSeconds            10764.0
HalfSeconds              5314.0
Name: 3701, dtype: object
San Luis Potosi
 Age                          39
M/F                           M
City            San Luis Potosi
State                       NaN
Country                     MEX
Half            0 days 02:01:26
40K             0 days 04:07:16
Pace                    0:10:01
TotalSeconds            14836.0
HalfSeconds              7286.0
Name: 26336, dtype: object
San Luis Potosi Slp
 Age                              56
M/F                               M
City            San Luis Potosi Slp
State                           NaN
Country                         MEX
Half                0 days 02:31:31
40K                 0 days 05:07:19
Pace                        0:12:24
TotalSeconds                18439.0
HalfSeconds                  9091.0
Name: 31837, dtype: object
San Marcos
 Age                          46
M/F                           M
City                 San Marcos
State                        CA
Country                     USA
Half            0 days 01:35:02
40K             0 days 03:02:06
Pace                    0:07:19
TotalSeconds            10926.0
HalfSeconds              5702.0
Name: 6344, dtype: object
San Marino
 Age                          23
M/F                           F
City                 San Marino
State                        CA
Country                     USA
Half            0 days 02:12:46
40K             0 days 04:17:19
Pace                    0:10:27
TotalSeconds            15439.0
HalfSeconds              7966.0
Name: 29440, dtype: object
San Martino Siccomario
 Age                                 66
M/F                                  F
City            San Martino Siccomario
State                              NaN
Country                            ITA
Half                   0 days 02:28:02
40K                    0 days 05:07:05
Pace                           0:12:15
TotalSeconds                   18425.0
HalfSeconds                     8882.0
Name: 26003, dtype: object
San Mateo
 Age                          29
M/F                           M
City                  San Mateo
State                        CA
Country                     USA
Half            0 days 01:28:13
40K             0 days 02:52:30
Pace                    0:06:57
TotalSeconds            10350.0
HalfSeconds              5293.0
Name: 3105, dtype: object
San Miguel De Allende Guanajuato
 Age                                           38
M/F                                            M
City            San Miguel De Allende Guanajuato
State                                        NaN
Country                                      MEX
Half                             0 days 01:31:45
40K                              0 days 03:10:43
Pace                                     0:07:45
TotalSeconds                             11443.0
HalfSeconds                               5505.0
Name: 7222, dtype: object
San Miguel Tucuman
 Age                             46
M/F                              M
City            San Miguel Tucuman
State                          NaN
Country                        ARG
Half               0 days 01:54:35
40K                0 days 03:47:22
Pace                       0:09:11
TotalSeconds               13642.0
HalfSeconds                 6875.0
Name: 31806, dtype: object
San Pablo
 Age                          60
M/F                           F
City                  San Pablo
State                        CA
Country                     USA
Half            0 days 02:09:55
40K             0 days 04:24:41
Pace                    0:10:40
TotalSeconds            15881.0
HalfSeconds              7795.0
Name: 20094, dtype: object
San Pedro
 Age                          40
M/F                           M
City                  San Pedro
State                       NaN
Country                     MEX
Half            0 days 01:35:38
40K             0 days 03:12:23
Pace                    0:07:48
TotalSeconds            11543.0
HalfSeconds              5738.0
Name: 7475, dtype: object
San Pedro Garza Garcia
 Age                                 47
M/F                                  M
City            San Pedro Garza Garcia
State                              NaN
Country                            MEX
Half                   0 days 01:42:07
40K                    0 days 03:20:26
Pace                           0:08:05
TotalSeconds                   12026.0
HalfSeconds                     6127.0
Name: 11541, dtype: object
San Pedro Garza Garcia N.l
 Age                                     48
M/F                                      M
City            San Pedro Garza Garcia N.l
State                                  NaN
Country                                MEX
Half                       0 days 02:07:44
40K                        0 days 04:25:35
Pace                               0:10:47
TotalSeconds                       15935.0
HalfSeconds                         7664.0

Name: 24488, dtype: object
Sankt Veit An Der Golsen
 Age                                   46
M/F                                    M
City            Sankt Veit An Der Golsen
State                                NaN
Country                              AUT
Half                     0 days 01:50:42
40K                      0 days 03:53:43
Pace                             0:09:32
TotalSeconds                     14023.0
HalfSeconds                       6642.0
Name: 5769, dtype: object
Santa Ana
 Age                          39
M/F                           M
City                  Santa Ana
State                        CA
Country                     USA
Half            0 days 01:36:48
40K             0 days 03:15:21
Pace                    0:07:54
TotalSeconds            11721.0
HalfSeconds              5808.0
Name: 6790, dtype: object
Santa Barbara
 Age                          47
M/F                           M
City              Santa Barbara
State                        CA
Country                     USA
Half            0 days 01:27:12
40K             0 days 02:50:48
Pace                    0:06:57
TotalSeconds            10248.0
HalfSeconds              5232.0
Name: 5702, dtype: object
Santa Catarina
 Age                          38
M/F                           M
City             Santa Catarina
State                       NaN
Country                     MEX
Half            0 days 01:34:04
40K             0 days 03:04:03
Pace                    0:07:26
TotalSeconds            11043.0
HalfSeconds              5644.0
Name: 6602, dtype: object
Santa Catarina N.l.
 Age                              46
M/F                               M
City            Santa Catarina N.l.
State                           NaN
Country                         MEX
Half                0 days 01:39:22
40K                 0 days 03:21:46
Pace                        0:08:13
TotalSeconds                12106.0
HalfSeconds                  5962.0
Name: 11931, dtype: object
Santa Clara
 Age                          33
M/F                           M
City                Santa Clara
State                        CA
Country                     USA
Half            0 days 01:20:43
40K             0 days 02:40:13
Pace                    0:06:28
TotalSeconds             9613.0
HalfSeconds              4843.0
Name: 1102, dtype: object
Santa Clarita
 Age                          55
M/F                           M
City              Santa Clarita
State                        CA
Country                     USA
Half            0 days 02:22:16
40K             0 days 04:35:23
Pace                    0:11:05
TotalSeconds            16523.0
HalfSeconds              8536.0
Name: 31245, dtype: object
Santa Cruz
 Age                          43
M/F                           M
City                 Santa Cruz
State                        CA
Country                     USA
Half            0 days 01:32:02
40K             0 days 03:01:17
Pace                    0:07:18
TotalSeconds            10877.0
HalfSeconds              5522.0
Name: 5862, dtype: object
Santa Fe
 Age                          30
M/F                           M
City                   Santa Fe
State                        NM
Country                     USA
Half            0 days 01:19:07
40K             0 days 02:38:28
Pace                    0:06:24
TotalSeconds             9508.0
HalfSeconds              4747.0
Name: 1920, dtype: object
Santa Fe Springs
 Age                           31
M/F                            F
City            Santa Fe Springs
State                         CA
Country                      USA
Half             0 days 01:44:27
40K              0 days 03:24:50
Pace                     0:08:14
TotalSeconds             12290.0
HalfSeconds               6267.0
Name: 11226, dtype: object
Santa Maria
 Age                          42
M/F                           M
City                Santa Maria
State                        CA
Country                     USA
Half            0 days 01:36:35
40K             0 days 03:16:44
Pace                    0:07:57
TotalSeconds            11804.0
HalfSeconds              5795.0
Name: 8574, dtype: object
Santa Monica
 Age                          45
M/F                           M
City               Santa Monica
State                        CA
Country                     USA
Half            0 days 01:20:51
40K             0 days 02:41:41
Pace                    0:06:31
TotalSeconds             9701.0
HalfSeconds              4851.0
Name: 860, dtype: object
Santa Rosa
 Age                          26
M/F                           M
City                 Santa Rosa
State                        CA
Country                     USA
Half            0 days 01:20:36
40K             0 days 02:42:24
Pace                    0:06:33
TotalSeconds             9744.0
HalfSeconds              4836.0
Name: 645, dtype: object
Santa Rosa Beach
 Age                           30
M/F                            M
City            Santa Rosa Beach
State                         FL
Country                      USA
Half             0 days 01:27:32
40K              0 days 02:47:53
Pace                     0:06:46
TotalSeconds             10073.0
HalfSeconds               5252.0
Name: 1709, dtype: object
Santana De Parnaiba
 Age                              40
M/F                               F
City            Santana De Parnaiba
State                           NaN
Country                         BRA
Half                0 days 01:34:15
40K                 0 days 03:04:32
Pace                        0:07:27
TotalSeconds                11072.0
HalfSeconds                  5655.0
Name: 9911, dtype: object
Santander
 Age                          52
M/F                           M
City                  Santander
State                       NaN
Country                     ESP
Half            0 days 02:14:13
40K             0 days 04:42:23
Pace                    0:11:26
TotalSeconds            16943.0
HalfSeconds              8053.0
Name: 30783, dtype: object
Santee
 Age                          55
M/F                           M
City                     Santee
State                        CA
Country                     USA
Half            0 days 01:44:36
40K             0 days 03:26:35
Pace                    0:08:21
TotalSeconds            12395.0
HalfSeconds              6276.0
Name: 14038, dtype: object
Santiago
 Age                          35
M/F                           M
City                   Santiago
State                       NaN
Country                     CHI
Half            0 days 01:19:04
40K             0 days 02:36:24
Pace                    0:06:20
TotalSeconds             9384.0
HalfSeconds              4744.0
Name: 606, dtype: object
Santiago, Las Condes
 Age                               39
M/F                                M
City            Santiago, Las Condes
State                            NaN
Country                          CHI
Half                 0 days 01:27:38
40K                  0 days 03:04:09
Pace                         0:07:30
TotalSeconds                 11049.0
HalfSeconds                   5258.0
Name: 4769, dtype: object
Santo Andre
 Age                          35
M/F                           M
City                Santo Andre
State                       NaN
Country                     BRA
Half            0 days 01:29:10
40K             0 days 02:55:57
Pace                    0:07:07
TotalSeconds            10557.0
HalfSeconds              5350.0
Name: 6389, dtype: object
Santo Antonio Dos Cavaleiros
 Age                                       44
M/F                                        M
City            Santo Antonio Dos Cavaleiros
State                                    NaN
Country                                  POR
Half                         0 days 01:56:59
40K                          0 days 03:51:02
Pace                                 0:09:21
TotalSeconds                         13862.0
HalfSeconds                           7019.0
Name: 31684, dtype: object
Santo Domingo
 Age                          37
M/F                           M
City              Santo Domingo
State                       NaN
Country                     DOM
Half            0 days 01:28:43
40K             0 days 02:51:14
Pace                    0:06:54
TotalSeconds            10274.0
HalfSeconds              5323.0
Name: 5242, dtype: object
Santo Domingo, Dn
 Age                            40
M/F                             M
City            Santo Domingo, Dn
State                         NaN
Country                       DOM
Half              0 days 01:44:33
40K               0 days 03:32:59
Pace                      0:08:34
TotalSeconds              12779.0
HalfSeconds                6273.0
Name: 8401, dtype: object
Santos, (sp)
 Age                          56
M/F                           M
City               Santos, (sp)
State                       NaN
Country                     BRA
Half            0 days 01:51:05
40K             0 days 03:52:43
Pace                    0:09:27
TotalSeconds            13963.0
HalfSeconds              6665.0
Name: 21024, dtype: object
Sao Bernardo Do Campo
 Age                                57
M/F                                 M
City            Sao Bernardo Do Campo
State                             NaN
Country                           BRA
Half                  0 days 01:56:18
40K                   0 days 04:08:22
Pace                          0:10:02
TotalSeconds                  14902.0
HalfSeconds                    6978.0
Name: 19138, dtype: object
Sao Jose Rio Preto
 Age                             55
M/F                              M
City            Sao Jose Rio Preto
State                          NaN
Country                        BRA
Half               0 days 01:44:44
40K                0 days 03:50:49
Pace                       0:09:22
TotalSeconds               13849.0
HalfSeconds                 6284.0
Name: 10388, dtype: object
Sao Mateus Do Sul
 Age                            47
M/F                             M
City            Sao Mateus Do Sul
State                         NaN
Country                       BRA
Half              0 days 01:33:22
40K               0 days 03:25:07
Pace                      0:08:23
TotalSeconds              12307.0
HalfSeconds                5602.0
Name: 12478, dtype: object
Sao Paulo
 Age                          43
M/F                           M
City                  Sao Paulo
State                       NaN
Country                     BRA
Half            0 days 01:24:07
40K             0 days 02:42:35
Pace                    0:06:34
TotalSeconds             9755.0
HalfSeconds              5047.0
Name: 1979, dtype: object
Sao Paulo - Sp
 Age                          43
M/F                           M
City             Sao Paulo - Sp
State                       NaN
Country                     BRA
Half            0 days 01:28:40
40K             0 days 02:49:51
Pace                    0:06:50
TotalSeconds            10191.0
HalfSeconds              5320.0
Name: 1461, dtype: object
Sao Paulo Sp Brazil
 Age                              40
M/F                               M
City            Sao Paulo Sp Brazil
State                           NaN
Country                         BRA
Half                0 days 01:29:34
40K                 0 days 03:07:19
Pace                        0:07:39
TotalSeconds                11239.0
HalfSeconds                  5374.0
Name: 7647, dtype: object
Sao Paulo, Sp
 Age                          44
M/F                           M
City              Sao Paulo, Sp
State                       NaN
Country                     BRA
Half            0 days 01:12:08
40K             0 days 02:23:37
Pace                    0:05:53
TotalSeconds             8617.0
HalfSeconds              4328.0
Name: 76, dtype: object
Sapporo
 Age                          59
M/F                           M
City                    Sapporo
State                       NaN
Country                     JPN
Half            0 days 01:55:23
40K             0 days 03:49:39
Pace                    0:09:18
TotalSeconds            13779.0
HalfSeconds              6923.0
Name: 20029, dtype: object
Sapporo Hokkaido
 Age                           55
M/F                            F
City            Sapporo Hokkaido
State                        NaN
Country                      JPN
Half             0 days 01:47:39
40K              0 days 03:43:26
Pace                     0:08:59
TotalSeconds             13406.0
HalfSeconds               6459.0
Name: 24214, dtype: object
Saranac
 Age                          30
M/F                           M
City                    Saranac
State                        NY
Country                     USA
Half            0 days 01:19:06
40K             0 days 02:35:25
Pace                    0:06:17
TotalSeconds             9325.0
HalfSeconds              4746.0
Name: 614, dtype: object
Sarasota
 Age                          49
M/F                           M
City                   Sarasota
State                        FL
Country                     USA
Half            0 days 01:26:51
40K             0 days 02:56:37
Pace                    0:07:13
TotalSeconds            10597.0
HalfSeconds              5211.0
Name: 4427, dtype: object
Saratoga
 Age                          43
M/F                           M
City                   Saratoga
State                        CA
Country                     USA
Half            0 days 01:44:42
40K             0 days 03:42:00
Pace                    0:09:01
TotalSeconds            13320.0
HalfSeconds              6282.0
Name: 8319, dtype: object
Saratoga Springs
 Age                           33
M/F                            M
City            Saratoga Springs
State                         NY
Country                      USA
Half             0 days 01:29:24
40K              0 days 02:55:14
Pace                     0:07:03
TotalSeconds             10514.0
HalfSeconds               5364.0
Name: 20993, dtype: object
Sarina
 Age                          39
M/F                           M
City                     Sarina
State                        ON
Country                     CAN
Half            0 days 01:44:50
40K             0 days 03:34:22
Pace                    0:08:40
TotalSeconds            12862.0
HalfSeconds              6290.0
Name: 29682, dtype: object
Sarnia
 Age                          61
M/F                           M
City                     Sarnia
State                        ON
Country                     CAN
Half            0 days 01:44:51
40K             0 days 03:22:47
Pace                    0:08:12
TotalSeconds            12167.0
HalfSeconds              6291.0
Name: 13049, dtype: object
Sartell
 Age                          48
M/F                           M
City                    Sartell
State                        MN
Country                     USA
Half            0 days 01:32:38
40K             0 days 03:10:05
Pace                    0:07:42
TotalSeconds            11405.0
HalfSeconds              5558.0
Name: 2777, dtype: object
Sarver
 Age                          29
M/F                           F
City                     Sarver
State                        PA
Country                     USA
Half            0 days 01:46:41
40K             0 days 04:06:41
Pace                    0:10:05
TotalSeconds            14801.0
HalfSeconds              6401.0
Name: 10915, dtype: object
Sarzeau
 Age                          50
M/F                           M
City                    Sarzeau
State                       NaN
Country                     FRA
Half            0 days 01:33:38
40K             0 days 03:00:58
Pace                    0:07:19
TotalSeconds            10858.0
HalfSeconds              5618.0
Name: 8944, dtype: object
Saskatoon
 Age                          34
M/F                           M
City                  Saskatoon
State                        SK
Country                     CAN
Half            0 days 01:30:39
40K             0 days 02:56:50
Pace                    0:07:07
TotalSeconds            10610.0
HalfSeconds              5439.0
Name: 2536, dtype: object
Satellite Beach
 Age                          47
M/F                           M
City            Satellite Beach
State                        FL
Country                     USA
Half            0 days 01:28:28
40K             0 days 02:51:41
Pace                    0:06:56
TotalSeconds            10301.0
HalfSeconds              5308.0
Name: 3901, dtype: object
Saugerties
 Age                          24
M/F                           F
City                 Saugerties
State                        NY
Country                     USA
Half            0 days 01:44:31
40K             0 days 03:24:13
Pace                    0:08:14
TotalSeconds            12253.0
HalfSeconds              6271.0
Name: 13663, dtype: object
Saugus
 Age                          51
M/F                           M
City                     Saugus
State                        MA
Country                     USA
Half            0 days 01:55:39
40K             0 days 03:50:09
Pace                    0:09:19
TotalSeconds            13809.0
HalfSeconds              6939.0
Name: 16908, dtype: object
Sauk City
 Age                          49
M/F                           F
City                  Sauk City
State                        WI
Country                     USA
Half            0 days 01:56:48
40K             0 days 03:47:03
Pace                    0:09:08
TotalSeconds            13623.0
HalfSeconds              7008.0
Name: 21681, dtype: object
Sauk Rapids
 Age                          33
M/F                           F
City                Sauk Rapids
State                        MN
Country                     USA
Half            0 days 01:40:48
40K             0 days 03:18:57
Pace                    0:08:01
TotalSeconds            11937.0
HalfSeconds              6048.0
Name: 9886, dtype: object
Sault Ste. Marie
 Age                           39
M/F                            M
City            Sault Ste. Marie
State                         ON
Country                      CAN
Half             0 days 01:50:59
40K              0 days 03:45:58
Pace                     0:09:11
TotalSeconds             13558.0
HalfSeconds               6659.0
Name: 5376, dtype: object
Sausalito
 Age                          46
M/F                           M
City                  Sausalito
State                        CA
Country                     USA
Half            0 days 01:28:54
40K             0 days 03:00:34
Pace                    0:07:18
TotalSeconds            10834.0
HalfSeconds              5334.0
Name: 3205, dtype: object
Savage
 Age                          58
M/F                           M
City                     Savage
State                        MN
Country                     USA
Half            0 days 01:39:32
40K             0 days 03:21:05
Pace                    0:08:08
TotalSeconds            12065.0
HalfSeconds              5972.0
Name: 9418, dtype: object
Savannah
 Age                          36
M/F                           M
City                   Savannah
State                        GA
Country                     USA
Half            0 days 01:30:49
40K             0 days 03:08:48
Pace                    0:07:39
TotalSeconds            11328.0
HalfSeconds              5449.0
Name: 3815, dtype: object
Savona
 Age                          59
M/F                           M
City                     Savona
State                       NaN
Country                     ITA
Half            0 days 02:19:37
40K             0 days 04:49:10
Pace                    0:11:38
TotalSeconds            17350.0
HalfSeconds              8377.0
Name: 31616, dtype: object
Savoy
 Age                          48
M/F                           M
City                      Savoy
State                        IL
Country                     USA
Half            0 days 01:38:43
40K             0 days 03:09:50
Pace                    0:07:39
TotalSeconds            11390.0

Schenectady
 Age                          49
M/F                           M
City                Schenectady
State                        NY
Country                     USA
Half            0 days 01:30:02
40K             0 days 03:07:19
Pace                    0:07:38
TotalSeconds            11239.0
HalfSeconds              5402.0
Name: 5643, dtype: object
Schnecksville
 Age                          47
M/F                           F
City              Schnecksville
State                        PA
Country                     USA
Half            0 days 01:54:31
40K             0 days 03:53:37
Pace                    0:09:30
TotalSeconds            14017.0
HalfSeconds              6871.0
Name: 23475, dtype: object
Schoelcher
 Age                          35
M/F                           M
City                 Schoelcher
State                       NaN
Country                     FRA
Half            0 days 01:33:11
40K             0 days 04:42:26
Pace                    0:11:26
TotalSeconds            16946.0
HalfSeconds              5591.0
Name: 4421, dtype: object
Schoolcraft
 Age                          46
M/F                           M
City                Schoolcraft
State                        MI
Country                     USA
Half            0 days 01:41:54
40K             0 days 03:19:53
Pace                    0:08:04
TotalSeconds            11993.0
HalfSeconds              6114.0
Name: 9923, dtype: object
Schuttrange
 Age                          40
M/F                           M
City                Schuttrange
State                       NaN
Country                     LUX
Half            0 days 01:35:34
40K             0 days 03:18:13
Pace                    0:08:05
TotalSeconds            11893.0
HalfSeconds              5734.0
Name: 7259, dtype: object
Schuylkill Haven
 Age                           61
M/F                            M
City            Schuylkill Haven
State                         PA
Country                      USA
Half             0 days 02:02:24
40K              0 days 03:56:39
Pace                     0:09:33
TotalSeconds             14199.0
HalfSeconds               7344.0
Name: 25531, dtype: object
Schwenksville
 Age                          37
M/F                           M
City              Schwenksville
State                        PA
Country                     USA
Half            0 days 01:26:21
40K             0 days 02:46:24
Pace                    0:06:42
TotalSeconds             9984.0
HalfSeconds              5181.0
Name: 5294, dtype: object
Scituate
 Age                          37
M/F                           M
City                   Scituate
State                        MA
Country                     USA
Half            0 days 01:25:33
40K             0 days 02:43:28
Pace                    0:06:36
TotalSeconds             9808.0
HalfSeconds              5133.0
Name: 1241, dtype: object
Scorze
 Age                          60
M/F                           M
City                     Scorze
State                       NaN
Country                     ITA
Half            0 days 02:01:33
40K             0 days 04:43:32
Pace                    0:11:29
TotalSeconds            17012.0
HalfSeconds              7293.0
Name: 18972, dtype: object
Scotch Plains
 Age                          34
M/F                           M
City              Scotch Plains
State                        NJ
Country                     USA
Half            0 days 01:28:03
40K             0 days 02:56:34
Pace                    0:07:06
TotalSeconds            10594.0
HalfSeconds              5283.0
Name: 1427, dtype: object
Scotia
 Age                          50
M/F                           M
City                     Scotia
State                        NY
Country                     USA
Half            0 days 01:35:30
40K             0 days 03:21:45
Pace                    0:08:08
TotalSeconds            12105.0
HalfSeconds              5730.0
Name: 4346, dtype: object
Scott Depot
 Age                          54
M/F                           F
City                Scott Depot
State                        WV
Country                     USA
Half            0 days 01:55:21
40K             0 days 03:43:39
Pace                    0:09:00
TotalSeconds            13419.0
HalfSeconds              6921.0
Name: 23140, dtype: object
Scott Township
 Age                          37
M/F                           F
City             Scott Township
State                        PA
Country                     USA
Half            0 days 01:44:53
40K             0 days 03:23:37
Pace                    0:08:12
TotalSeconds            12217.0
HalfSeconds              6293.0
Name: 13465, dtype: object
Scott Twp
 Age                          64
M/F                           M
City                  Scott Twp
State                        PA
Country                     USA
Half            0 days 01:52:05
40K             0 days 03:33:49
Pace                    0:08:37
TotalSeconds            12829.0
HalfSeconds              6725.0
Name: 22511, dtype: object
Scottdale
 Age                          36
M/F                           F
City                  Scottdale
State                        PA
Country                     USA
Half            0 days 02:00:40
40K             0 days 04:05:14
Pace                    0:09:57
TotalSeconds            14714.0
HalfSeconds              7240.0
Name: 19341, dtype: object
Scottosdale
 Age                          40
M/F                           F
City                Scottosdale
State                        AZ
Country                     USA
Half            0 days 01:49:05
40K             0 days 03:37:39
Pace                    0:08:45
TotalSeconds            13059.0
HalfSeconds              6545.0
Name: 19316, dtype: object
Scottsdale
 Age                          52
M/F                           M
City                 Scottsdale
State                        AZ
Country                     USA
Half            0 days 01:20:59
40K             0 days 02:38:54
Pace                    0:06:25
TotalSeconds             9534.0
HalfSeconds              4859.0
Name: 403, dtype: object
Scottsville
 Age                          39
M/F                           F
City                Scottsville
State                        KY
Country                     USA
Half            0 days 01:42:43
40K             0 days 03:18:52
Pace                    0:08:01
TotalSeconds            11932.0
HalfSeconds              6163.0
Name: 14021, dtype: object
Scranton
 Age                          43
M/F                           M
City                   Scranton
State                        PA
Country                     USA
Half            0 days 01:25:21
40K             0 days 02:43:53
Pace                    0:06:36
TotalSeconds             9833.0
HalfSeconds              5121.0
Name: 1674, dtype: object
Sea Cliff
 Age                          57
M/F                           M
City                  Sea Cliff
State                        NY
Country                     USA
Half            0 days 01:54:30
40K             0 days 03:44:14
Pace                    0:09:06
TotalSeconds            13454.0
HalfSeconds              6870.0
Name: 15170, dtype: object
Seabrook
 Age                          35
M/F                           F
City                   Seabrook
State                        TX
Country                     USA
Half            0 days 01:55:55
40K             0 days 03:47:49
Pace                    0:09:10
TotalSeconds            13669.0
HalfSeconds              6955.0
Name: 19185, dtype: object
Seal Beach
 Age                          50
M/F                           M
City                 Seal Beach
State                        CA
Country                     USA
Half            0 days 01:32:25
40K             0 days 03:10:57
Pace                    0:07:45
TotalSeconds            11457.0
HalfSeconds              5545.0
Name: 5953, dtype: object
Seattle
 Age                          44
M/F                           M
City                    Seattle
State                        WA
Country                     USA
Half            0 days 01:14:19
40K             0 days 02:29:09
Pace                    0:06:01
TotalSeconds             8949.0
HalfSeconds              4459.0
Name: 82, dtype: object
Sebastian
 Age                          54
M/F                           F
City                  Sebastian
State                        FL
Country                     USA
Half            0 days 02:40:20
40K             0 days 05:15:21
Pace                    0:12:42
TotalSeconds            18921.0
HalfSeconds              9620.0
Name: 26668, dtype: object
Sebastopol
 Age                          47
M/F                           M
City                 Sebastopol
State                        CA
Country                     USA
Half            0 days 01:51:29
40K             0 days 03:35:59
Pace                    0:08:53
TotalSeconds            12959.0
HalfSeconds              6689.0
Name: 9526, dtype: object
Sebring
 Age                          36
M/F                           M
City                    Sebring
State                        FL
Country                     USA
Half            0 days 01:32:50
40K             0 days 03:11:36
Pace                    0:07:44
TotalSeconds            11496.0
HalfSeconds              5570.0
Name: 6353, dtype: object
Sechelt
 Age                          58
M/F                           M
City                    Sechelt
State                        BC
Country                     CAN
Half            0 days 01:58:02
40K             0 days 04:02:59
Pace                    0:09:48
TotalSeconds            14579.0
HalfSeconds              7082.0
Name: 19483, dtype: object
Sedalia
 Age                          63
M/F                           M
City                    Sedalia
State                        MO
Country                     USA
Half            0 days 01:47:14
40K             0 days 03:38:17
Pace                    0:08:52
TotalSeconds            13097.0
HalfSeconds              6434.0
Name: 22147, dtype: object
Sedona
 Age                          58
M/F                           M
City                     Sedona
State                        AZ
Country                     USA
Half            0 days 01:39:38
40K             0 days 03:37:55
Pace                    0:09:03
TotalSeconds            13075.0
HalfSeconds              5978.0
Name: 16522, dtype: object
Sedro Woolley
 Age                          28
M/F                           M
City              Sedro Woolley
State                        WA
Country                     USA
Half            0 days 01:32:28
40K             0 days 03:04:43
Pace                    0:07:28
TotalSeconds            11083.0
HalfSeconds              5548.0
Name: 1438, dtype: object
Selah
 Age                          25
M/F                           F
City                      Selah
State                        WA
Country                     USA
Half            0 days 02:27:54
40K             0 days 04:57:34
Pace                    0:11:57
TotalSeconds            17854.0
HalfSeconds              8874.0
Name: 30024, dtype: object
Selfridge
 Age                          35
M/F                           M
City                  Selfridge
State                        ND
Country                     USA
Half            0 days 01:52:04
40K             0 days 03:48:09
Pace                    0:09:13
TotalSeconds            13689.0
HalfSeconds              6724.0
Name: 4870, dtype: object
Selinsgrove
 Age                          24
M/F                           M
City                Selinsgrove
State                        PA
Country                     USA
Half            0 days 01:31:34
40K             0 days 03:15:22
Pace                    0:07:58
TotalSeconds            11722.0
HalfSeconds              5494.0
Name: 3631, dtype: object
Selkirk
 Age                          50
M/F                           F
City                    Selkirk
State                        NY
Country                     USA
Half            0 days 01:49:21
40K             0 days 03:31:04
Pace                    0:08:31
TotalSeconds            12664.0
HalfSeconds              6561.0
Name: 13353, dtype: object
Sellersburg
 Age                          53
M/F                           F
City                Sellersburg
State                        IN
Country                     USA
Half            0 days 01:43:55
40K             0 days 03:17:19
Pace                    0:07:56
TotalSeconds            11839.0
HalfSeconds              6235.0
Name: 16576, dtype: object
Sellersville
 Age                          31
M/F                           M
City               Sellersville
State                        PA
Country                     USA
Half            0 days 00:00:00
40K             0 days 00:00:00
Pace                    0:08:23
TotalSeconds                0.0
HalfSeconds                 0.0
Name: 31326, dtype: object
Sendai
 Age                          69
M/F                           M
City                     Sendai
State                       NaN
Country                     JPN
Half            0 days 02:05:54
40K             0 days 04:08:00
Pace                    0:10:01
TotalSeconds            14880.0
HalfSeconds              7554.0
Name: 25184, dtype: object
Seneca Falls
 Age                          51
M/F                           M
City               Seneca Falls
State                        NY
Country                     USA
Half            0 days 01:38:46
40K             0 days 03:25:39
Pace                    0:08:19
TotalSeconds            12339.0
HalfSeconds              5926.0
Name: 11334, dtype: object
Seoul
 Age                          53
M/F                           M
City                      Seoul
State                       NaN
Country                     KOR
Half            0 days 01:22:37
40K             0 days 02:46:01
Pace                    0:06:43
TotalSeconds             9961.0
HalfSeconds              4957.0
Name: 379, dtype: object
Sept-Iles
 Age                          51
M/F                           M
City                  Sept-Iles
State                        QC
Country                     CAN
Half            0 days 01:31:29
40K             0 days 02:59:42
Pace                    0:07:15
TotalSeconds            10782.0
HalfSeconds              5489.0
Name: 8513, dtype: object
Setagaya-Ku, Tokyo
 Age                             51
M/F                              M
City            Setagaya-Ku, Tokyo
State                          NaN
Country                        JPN
Half               0 days 01:34:26
40K                0 days 03:08:21
Pace                       0:07:37
TotalSeconds               11301.0
HalfSeconds                 5666.0
Name: 5639, dtype: object
Setauket
 Age                          54
M/F                           M
City                   Setauket
State                        NY
Country                     USA
Half            0 days 01:33:58
40K             0 days 03:01:22
Pace                    0:07:18
TotalSeconds            10882.0
HalfSeconds              5638.0
Name: 6502, dtype: object
Seven Fields
 Age                          43
M/F                           M
City               Seven Fields
State                        PA
Country                     USA
Half            0 days 01:37:21
40K             0 days 03:07:21
Pace                    0:07:33
TotalSeconds            11241.0
HalfSeconds              5841.0
Name: 8273, dtype: object
Seven Hills
 Age                          26
M/F                           M
City                Seven Hills
State                        OH
Country                     USA
Half            0 days 01:17:33
40K             0 days 02:42:48
Pace                    0:06:39
TotalSeconds             9768.0
HalfSeconds              4653.0
Name: 157, dtype: object
Sevenoaks, Kent
 Age                          51
M/F                           M
City            Sevenoaks, Kent
State                       NaN
Country                     GBR
Half            0 days 01:40:21
40K             0 days 03:17:31
Pace                    0:07:59
TotalSeconds            11851.0
HalfSeconds              6021.0
Name: 14781, dtype: object
Severn
 Age                          26
M/F                           M
City                     Severn
State                        ON
Country                     CAN
Half            0 days 01:26:41
40K             0 days 03:01:49
Pace                    0:07:27
TotalSeconds            10909.0
HalfSeconds              5201.0
Name: 3413, dtype: object
Severna Park
 Age                          20
M/F                           M
City               Severna Park
State                        MD
Country                     USA
Half            0 days 01:32:55
40K             0 days 03:09:38
Pace                    0:07:42
TotalSeconds            11378.0
HalfSeconds              5575.0
Name: 5002, dtype: object
Sewell
 Age                          46
M/F                           M
City                     Sewell
State                        NJ
Country                     USA
Half            0 days 01:33:52
40K             0 days 03:25:02
Pace                    0:08:25
TotalSeconds            12302.0
HalfSeconds              5632.0
Name: 3613, dtype: object
Sewickley
 Age                          39
M/F                           M
City                  Sewickley
State                        PA
Country                     USA
Half            0 days 01:31:20
40K             0 days 03:11:33
Pace                    0:07:46
TotalSeconds            11493.0
HalfSeconds              5480.0
Name: 3980, dtype: object
Seymour
 Age                          40
M/F                           M
City                    Seymour
State                       NaN
Country                     AUS
Half            0 days 01:36:13
40K             0 days 03:12:43
Pace                    0:07:47
TotalSeconds            11563.0
HalfSeconds              5773.0
Name: 6395, dtype: object
Shaker Heights
 Age                          43
M/F                           M
City             Shaker Heights
State                        OH
Country                     USA
Half            0 days 01:32:29
40K             0 days 02:59:34
Pace                    0:07:16
TotalSeconds            10774.0
HalfSeconds              5549.0
Name: 7086, dtype: object
Shakopee
 Age                          30
M/F                           M
City                   Shakopee
State                        MN
Country                     USA
Half            0 days 01:22:03
40K             0 days 02:42:01
Pace                    0:06:34
TotalSeconds             9721.0
HalfSeconds              4923.0
Name: 1099, dtype: object
Shallow Lake
 Age                          40
M/F                           F
City               Shallow Lake
State                        ON
Country                     CAN
Half            0 days 01:58:02
40K             0 days 03:51:41
Pace                    0:09:21
TotalSeconds            13901.0
HalfSeconds              7082.0
Name: 20403, dtype: object
Shamokin
 Age                          46
M/F                           F
City                   Shamokin
State                        PA
Country                     USA
Half            0 days 01:54:57
40K             0 days 03:46:12
Pace                    0:09:07
TotalSeconds            13572.0
HalfSeconds              6897.0
Name: 22307, dtype: object
Shanghai
 Age                          35
M/F                           M
City                   Shanghai
State                       NaN
Country                     CHN
Half            0 days 01:25:47
40K             0 days 02:51:53
Pace                    0:06:57
TotalSeconds            10313.0
HalfSeconds              5147.0
Name: 4783, dtype: object
Sharon
 Age                          35
M/F                           M
City                     Sharon
State                        MA
Country                     USA
Half            0 days 01:28:52
40K             0 days 02:50:08
Pace                    0:06:51

Shelburne Falls
 Age                          56
M/F                           M
City            Shelburne Falls
State                        MA
Country                     USA
Half            0 days 01:47:38
40K             0 days 03:36:23
Pace                    0:08:48
TotalSeconds            12983.0
HalfSeconds              6458.0
Name: 19127, dtype: object
Shelby
 Age                          38
M/F                           M
City                     Shelby
State                        NC
Country                     USA
Half            0 days 01:34:33
40K             0 days 03:02:58
Pace                    0:07:25
TotalSeconds            10978.0
HalfSeconds              5673.0
Name: 6208, dtype: object
Shelby Township
 Age                          35
M/F                           F
City            Shelby Township
State                        MI
Country                     USA
Half            0 days 01:42:14
40K             0 days 03:16:59
Pace                    0:07:57
TotalSeconds            11819.0
HalfSeconds              6134.0
Name: 16560, dtype: object
Shelby Twp
 Age                          57
M/F                           M
City                 Shelby Twp
State                        MI
Country                     USA
Half            0 days 01:39:53
40K             0 days 03:19:19
Pace                    0:08:01
TotalSeconds            11959.0
HalfSeconds              5993.0
Name: 11846, dtype: object
Shelbyville
 Age                          33
M/F                           F
City                Shelbyville
State                        IL
Country                     USA
Half            0 days 01:45:21
40K             0 days 03:29:21
Pace                    0:08:26
TotalSeconds            12561.0
HalfSeconds              6321.0
Name: 16459, dtype: object
Shell Beach
 Age                          46
M/F                           M
City                Shell Beach
State                        CA
Country                     USA
Half            0 days 01:36:43
40K             0 days 03:19:38
Pace                    0:08:09
TotalSeconds            11978.0
HalfSeconds              5803.0
Name: 10929, dtype: object
Shell Lake
 Age                          35
M/F                           M
City                 Shell Lake
State                        WI
Country                     USA
Half            0 days 01:20:23
40K             0 days 02:40:24
Pace                    0:06:28
TotalSeconds             9624.0
HalfSeconds              4823.0
Name: 1004, dtype: object
Shelter Island
 Age                          27
M/F                           F
City             Shelter Island
State                        NY
Country                     USA
Half            0 days 02:04:11
40K             0 days 04:14:50
Pace                    0:10:19
TotalSeconds            15290.0
HalfSeconds              7451.0
Name: 28415, dtype: object
Shelton
 Age                          47
M/F                           M
City                    Shelton
State                        WA
Country                     USA
Half            0 days 01:43:15
40K             0 days 03:23:00
Pace                    0:08:14
TotalSeconds            12180.0
HalfSeconds              6195.0
Name: 10300, dtype: object
Shen Zhen
 Age                          65
M/F                           M
City                  Shen Zhen
State                       NaN
Country                     CHN
Half            0 days 01:39:03
40K             0 days 03:12:24
Pace                    0:07:46
TotalSeconds            11544.0
HalfSeconds              5943.0
Name: 13853, dtype: object
Shenfield
 Age                          40
M/F                           F
City                  Shenfield
State                       NaN
Country                     GBR
Half            0 days 01:39:59
40K             0 days 03:16:36
Pace                    0:07:56
TotalSeconds            11796.0
HalfSeconds              5999.0
Name: 12289, dtype: object
Shenzhen
 Age                          52
M/F                           M
City                   Shenzhen
State                       NaN
Country                     CHN
Half            0 days 01:34:25
40K             0 days 03:06:13
Pace                    0:07:31
TotalSeconds            11173.0
HalfSeconds              5665.0
Name: 8687, dtype: object
Shenzhen, Guangdong
 Age                              52
M/F                               M
City            Shenzhen, Guangdong
State                           NaN
Country                         CHN
Half                0 days 01:44:02
40K                 0 days 03:24:19
Pace                        0:08:19
TotalSeconds                12259.0
HalfSeconds                  6242.0
Name: 15095, dtype: object
Shepherd
 Age                          24
M/F                           M
City                   Shepherd
State                        MI
Country                     USA
Half            0 days 01:21:52
40K             0 days 02:47:26
Pace                    0:06:48
TotalSeconds            10046.0
HalfSeconds              4912.0
Name: 2088, dtype: object
Shepherdstown
 Age                          49
M/F                           M
City              Shepherdstown
State                        WV
Country                     USA
Half            0 days 01:27:35
40K             0 days 02:47:47
Pace                    0:06:46
TotalSeconds            10067.0
HalfSeconds              5255.0
Name: 1405, dtype: object
Shepherdsville
 Age                          52
M/F                           F
City             Shepherdsville
State                        KY
Country                     USA
Half            0 days 01:49:10
40K             0 days 03:41:35
Pace                    0:08:54
TotalSeconds            13295.0
HalfSeconds              6550.0
Name: 13347, dtype: object
Sherborn
 Age                          40
M/F                           M
City                   Sherborn
State                        MA
Country                     USA
Half            0 days 01:44:36
40K             0 days 03:24:48
Pace                    0:08:15
TotalSeconds            12288.0
HalfSeconds              6276.0
Name: 27174, dtype: object
Sherbrooke
 Age                          42
M/F                           M
City                 Sherbrooke
State                        QC
Country                     CAN
Half            0 days 01:20:35
40K             0 days 02:38:26
Pace                    0:06:24
TotalSeconds             9506.0
HalfSeconds              4835.0
Name: 1216, dtype: object
Sheridan
 Age                          66
M/F                           M
City                   Sheridan
State                        WY
Country                     USA
Half            0 days 01:58:47
40K             0 days 03:53:21
Pace                    0:09:25
TotalSeconds            14001.0
HalfSeconds              7127.0
Name: 21059, dtype: object
Sherman
 Age                          50
M/F                           M
City                    Sherman
State                        TX
Country                     USA
Half            0 days 01:35:27
40K             0 days 03:06:49
Pace                    0:07:32
TotalSeconds            11209.0
HalfSeconds              5727.0
Name: 7578, dtype: object
Sherman Oaks
 Age                          42
M/F                           F
City               Sherman Oaks
State                        CA
Country                     USA
Half            0 days 01:36:42
40K             0 days 03:08:03
Pace                    0:07:36
TotalSeconds            11283.0
HalfSeconds              5802.0
Name: 9158, dtype: object
Sherrodsville
 Age                          52
M/F                           M
City              Sherrodsville
State                        OH
Country                     USA
Half            0 days 01:26:34
40K             0 days 02:58:05
Pace                    0:07:16
TotalSeconds            10685.0
HalfSeconds              5194.0
Name: 3591, dtype: object
Sherwood
 Age                          37
M/F                           F
City                   Sherwood
State                        OR
Country                     USA
Half            0 days 01:41:23
40K             0 days 03:17:25
Pace                    0:07:56
TotalSeconds            11845.0
HalfSeconds              6083.0
Name: 11507, dtype: object
Sherwood Park
 Age                          45
M/F                           M
City              Sherwood Park
State                        AB
Country                     CAN
Half            0 days 01:23:39
40K             0 days 02:43:23
Pace                    0:06:35
TotalSeconds             9803.0
HalfSeconds              5019.0
Name: 1555, dtype: object
Shillington
 Age                          34
M/F                           F
City                Shillington
State                        PA
Country                     USA
Half            0 days 01:43:18
40K             0 days 03:20:03
Pace                    0:08:05
TotalSeconds            12003.0
HalfSeconds              6198.0
Name: 16837, dtype: object
Shirley
 Age                          52
M/F                           M
City                    Shirley
State                        MA
Country                     USA
Half            0 days 01:48:30
40K             0 days 04:18:37
Pace                    0:10:27
TotalSeconds            15517.0
HalfSeconds              6510.0
Name: 14391, dtype: object
Shizuoka
 Age                          58
M/F                           M
City                   Shizuoka
State                       NaN
Country                     JPN
Half            0 days 01:52:23
40K             0 days 03:40:27
Pace                    0:08:55
TotalSeconds            13227.0
HalfSeconds              6743.0
Name: 20332, dtype: object
Shoreham
 Age                          54
M/F                           M
City                   Shoreham
State                        NY
Country                     USA
Half            0 days 01:35:21
40K             0 days 03:13:26
Pace                    0:07:50
TotalSeconds            11606.0
HalfSeconds              5721.0
Name: 9080, dtype: object
Shoreline
 Age                          39
M/F                           M
City                  Shoreline
State                        WA
Country                     USA
Half            0 days 01:24:16
40K             0 days 02:44:55
Pace                    0:06:40
TotalSeconds             9895.0
HalfSeconds              5056.0
Name: 3181, dtype: object
Shoreview
 Age                          47
M/F                           M
City                  Shoreview
State                        MN
Country                     USA
Half            0 days 01:27:38
40K             0 days 02:50:17
Pace                    0:06:52
TotalSeconds            10217.0
HalfSeconds              5258.0
Name: 4371, dtype: object
Shorewood
 Age                          24
M/F                           M
City                  Shorewood
State                        WI
Country                     USA
Half            0 days 01:17:07
40K             0 days 02:30:07
Pace                    0:06:05
TotalSeconds             9007.0
HalfSeconds              4627.0
Name: 838, dtype: object
Short Hills
 Age                          57
M/F                           M
City                Short Hills
State                        NJ
Country                     USA
Half            0 days 01:44:48
40K             0 days 03:24:09
Pace                    0:08:14
TotalSeconds            12249.0
HalfSeconds              6288.0
Name: 15017, dtype: object
Shreveport
 Age                          55
M/F                           M
City                 Shreveport
State                        LA
Country                     USA
Half            0 days 01:45:59
40K             0 days 03:26:41
Pace                    0:08:22
TotalSeconds            12401.0
HalfSeconds              6359.0
Name: 16901, dtype: object
Shrewsbury
 Age                          37
M/F                           M
City                 Shrewsbury
State                        MA
Country                     USA
Half            0 days 01:30:39
40K             0 days 02:52:20
Pace                    0:06:56
TotalSeconds            10340.0
HalfSeconds              5439.0
Name: 3030, dtype: object
Shumway
 Age                          60
M/F                           M
City                    Shumway
State                        IL
Country                     USA
Half            0 days 02:00:26
40K             0 days 04:00:56
Pace                    0:09:49
TotalSeconds            14456.0
HalfSeconds              7226.0
Name: 24382, dtype: object
Sicklerville
 Age                          55
M/F                           M
City               Sicklerville
State                        NJ
Country                     USA
Half            0 days 01:44:21
40K             0 days 03:27:32
Pace                    0:08:22
TotalSeconds            12452.0
HalfSeconds              6261.0
Name: 17097, dtype: object
Sidney
 Age                          22
M/F                           M
City                     Sidney
State                        OH
Country                     USA
Half            0 days 01:24:49
40K             0 days 02:46:41
Pace                    0:06:46
TotalSeconds            10001.0
HalfSeconds              5089.0
Name: 2093, dtype: object
Siehdichum
 Age                          57
M/F                           M
City                 Siehdichum
State                       NaN
Country                     GER
Half            0 days 02:26:11
40K             0 days 05:02:01
Pace                    0:12:12
TotalSeconds            18121.0
HalfSeconds              8771.0
Name: 31125, dtype: object
Siero
 Age                          65
M/F                           M
City                      Siero
State                       NaN
Country                     ESP
Half            0 days 02:02:31
40K             0 days 04:28:39
Pace                    0:10:59
TotalSeconds            16119.0
HalfSeconds              7351.0
Name: 24817, dtype: object
Sierra Madre
 Age                          52
M/F                           F
City               Sierra Madre
State                        CA
Country                     USA
Half            0 days 01:48:13
40K             0 days 03:30:52
Pace                    0:08:30
TotalSeconds            12652.0
HalfSeconds              6493.0
Name: 22532, dtype: object
Sierra Vista
 Age                          27
M/F                           M
City               Sierra Vista
State                        AZ
Country                     USA
Half            0 days 01:19:16
40K             0 days 02:32:28
Pace                    0:06:09
TotalSeconds             9148.0
HalfSeconds              4756.0
Name: 701, dtype: object
Signal Mountai
 Age                          38
M/F                           F
City             Signal Mountai
State                        TN
Country                     USA
Half            0 days 01:31:00
40K             0 days 03:00:04
Pace                    0:07:18
TotalSeconds            10804.0
HalfSeconds              5460.0
Name: 11968, dtype: object
Signal Mountain
 Age                          37
M/F                           M
City            Signal Mountain
State                        TN
Country                     USA
Half            0 days 01:32:16
40K             0 days 03:05:44
Pace                    0:07:29
TotalSeconds            11144.0
HalfSeconds              5536.0
Name: 3490, dtype: object
Siksika
 Age                          20
M/F                           M
City                    Siksika
State                        AB
Country                     CAN
Half            0 days 01:37:59
40K             0 days 03:31:51
Pace                    0:08:33
TotalSeconds            12711.0
HalfSeconds              5879.0
Name: 9993, dtype: object
Silang, Cavite
 Age                          45
M/F                           M
City             Silang, Cavite
State                       NaN
Country                     PHI
Half            0 days 01:54:21
40K             0 days 03:52:27
Pace                    0:09:30
TotalSeconds            13947.0
HalfSeconds              6861.0
Name: 30242, dtype: object
Silver Bay
 Age                          61
M/F                           F
City                 Silver Bay
State                        MN
Country                     USA
Half            0 days 02:03:53
40K             0 days 04:07:47
Pace                    0:10:02
TotalSeconds            14867.0
HalfSeconds              7433.0
Name: 24837, dtype: object
Silver City
 Age                          54
M/F                           M
City                Silver City
State                        NM
Country                     USA
Half            0 days 01:37:16
40K             0 days 03:10:13
Pace                    0:07:40
TotalSeconds            11413.0
HalfSeconds              5836.0
Name: 11171, dtype: object
Silver Spring
 Age                          33
M/F                           M
City              Silver Spring
State                        MD
Country                     USA
Half            0 days 01:26:04
40K             0 days 02:47:17
Pace                    0:06:45
TotalSeconds            10037.0
HalfSeconds              5164.0
Name: 2430, dtype: object
Silverado
 Age                          37
M/F                           M
City                  Silverado
State                        CA
Country                     USA
Half            0 days 01:24:22
40K             0 days 02:43:51
Pace                    0:06:39
TotalSeconds             9831.0
HalfSeconds              5062.0
Name: 4602, dtype: object
Silverdale
 Age                          45
M/F                           M
City                 Silverdale
State                        WA
Country                     USA
Half            0 days 01:29:55
40K             0 days 03:03:15
Pace                    0:07:26
TotalSeconds            10995.0
HalfSeconds              5395.0
Name: 3710, dtype: object
Silverton
 Age                          28
M/F                           M
City                  Silverton
State                        OR
Country                     USA
Half            0 days 01:21:57
40K             0 days 02:42:31
Pace                    0:06:35
TotalSeconds             9751.0
HalfSeconds              4917.0
Name: 1511, dtype: object
Simancas
 Age                          37
M/F                           M
City                   Simancas
State                       NaN
Country                     ESP
Half            0 days 01:33:32
40K             0 days 03:07:09
Pace                    0:07:33
TotalSeconds            11229.0
HalfSeconds              5612.0
Name: 4855, dtype: object
Simcoe
 Age                          60
M/F                           F
City                     Simcoe
State                        ON
Country                     CAN
Half            0 days 02:01:41
40K             0 days 04:06:19
Pace                    0:09:55
TotalSeconds            14779.0
HalfSeconds              7301.0
Name: 25240, dtype: object
Simi Valley
 Age                          49
M/F                           M
City                Simi Valley
State                        CA
Country                     USA
Half            0 days 01:31:40
40K             0 days 03:07:58
Pace                    0:07:42
TotalSeconds            11278.0
HalfSeconds              5500.0
Name: 10786, dtype: object
Simpsonville
 Age                          24
M/F                           M
City               Simpsonville
State                        SC
Country                     USA
Half            0 days 01:25:09
40K             0 days 02:47:32
Pace                    0:06:50
TotalSeconds            10052.0
HalfSeconds              5109.0
Name: 2340, dtype: object
Simsbury
 Age                          41
M/F                           F
City                   Simsbury
State                        CT
Country                     USA
Half            0 days 01:29:58

Name: 31739, dtype: object
Smithfield
 Age                          46
M/F                           M
City                 Smithfield
State                        RI
Country                     USA
Half            0 days 01:34:08
40K             0 days 03:04:58
Pace                    0:07:27
TotalSeconds            11098.0
HalfSeconds              5648.0
Name: 5384, dtype: object
Smiths
 Age                          43
M/F                           M
City                     Smiths
State                       NaN
Country                     BER
Half            0 days 01:49:23
40K             0 days 03:30:51
Pace                    0:08:29
TotalSeconds            12651.0
HalfSeconds              6563.0
Name: 31461, dtype: object
Smithsburg
 Age                          48
M/F                           F
City                 Smithsburg
State                        MD
Country                     USA
Half            0 days 02:00:36
40K             0 days 04:16:06
Pace                    0:10:18
TotalSeconds            15366.0
HalfSeconds              7236.0
Name: 24301, dtype: object
Smithtown
 Age                          56
M/F                           M
City                  Smithtown
State                        NY
Country                     USA
Half            0 days 01:47:26
40K             0 days 03:34:25
Pace                    0:08:40
TotalSeconds            12865.0
HalfSeconds              6446.0
Name: 12797, dtype: object
Smyna
 Age                          29
M/F                           M
City                      Smyna
State                        TN
Country                     USA
Half            0 days 02:07:11
40K             0 days 04:23:55
Pace                    0:10:38
TotalSeconds            15835.0
HalfSeconds              7631.0
Name: 29015, dtype: object
Smyrna
 Age                          27
M/F                           M
City                     Smyrna
State                        GA
Country                     USA
Half            0 days 01:18:42
40K             0 days 02:34:00
Pace                    0:06:13
TotalSeconds             9240.0
HalfSeconds              4722.0
Name: 904, dtype: object
Sneads Ferry
 Age                          26
M/F                           F
City               Sneads Ferry
State                        NC
Country                     USA
Half            0 days 01:38:27
40K             0 days 03:19:22
Pace                    0:08:05
TotalSeconds            11962.0
HalfSeconds              5907.0
Name: 6077, dtype: object
Snellville
 Age                          50
M/F                           F
City                 Snellville
State                        GA
Country                     USA
Half            0 days 01:43:29
40K             0 days 03:24:31
Pace                    0:08:14
TotalSeconds            12271.0
HalfSeconds              6209.0
Name: 18835, dtype: object
Snohomish
 Age                          35
M/F                           M
City                  Snohomish
State                        WA
Country                     USA
Half            0 days 01:30:16
40K             0 days 02:58:47
Pace                    0:07:16
TotalSeconds            10727.0
HalfSeconds              5416.0
Name: 6615, dtype: object
Snoqualmie
 Age                          43
M/F                           M
City                 Snoqualmie
State                        WA
Country                     USA
Half            0 days 01:36:18
40K             0 days 03:24:41
Pace                    0:08:27
TotalSeconds            12281.0
HalfSeconds              5778.0
Name: 7261, dtype: object
Snowflake
 Age                          33
M/F                           F
City                  Snowflake
State                        AZ
Country                     USA
Half            0 days 02:03:38
40K             0 days 04:11:40
Pace                    0:10:10
TotalSeconds            15100.0
HalfSeconds              7418.0
Name: 22314, dtype: object
So. Weymouth
 Age                          46
M/F                           M
City               So. Weymouth
State                        MA
Country                     USA
Half            0 days 01:36:09
40K             0 days 03:10:09
Pace                    0:07:42
TotalSeconds            11409.0
HalfSeconds              5769.0
Name: 6779, dtype: object
Sobieski
 Age                          39
M/F                           F
City                   Sobieski
State                        WI
Country                     USA
Half            0 days 01:40:31
40K             0 days 03:27:21
Pace                    0:08:22
TotalSeconds            12441.0
HalfSeconds              6031.0
Name: 14368, dtype: object
Socorro
 Age                          25
M/F                           M
City                    Socorro
State                        NM
Country                     USA
Half            0 days 01:22:52
40K             0 days 02:38:24
Pace                    0:06:23
TotalSeconds             9504.0
HalfSeconds              4972.0
Name: 2275, dtype: object
Soka
 Age                          48
M/F                           F
City                       Soka
State                       NaN
Country                     JPN
Half            0 days 01:36:06
40K             0 days 03:04:43
Pace                    0:07:27
TotalSeconds            11083.0
HalfSeconds              5766.0
Name: 9225, dtype: object
Solana Beach
 Age                          32
M/F                           F
City               Solana Beach
State                        CA
Country                     USA
Half            0 days 01:41:58
40K             0 days 03:22:26
Pace                    0:08:11
TotalSeconds            12146.0
HalfSeconds              6118.0
Name: 14736, dtype: object
Soldotna
 Age                          47
M/F                           F
City                   Soldotna
State                        AK
Country                     USA
Half            0 days 02:03:15
40K             0 days 04:09:38
Pace                    0:10:03
TotalSeconds            14978.0
HalfSeconds              7395.0
Name: 22214, dtype: object
Solna
 Age                          44
M/F                           F
City                      Solna
State                       NaN
Country                     SWE
Half            0 days 01:58:38
40K             0 days 03:56:33
Pace                    0:09:36
TotalSeconds            14193.0
HalfSeconds              7118.0
Name: 17213, dtype: object
Solon
 Age                          44
M/F                           M
City                      Solon
State                        OH
Country                     USA
Half            0 days 01:30:04
40K             0 days 02:57:02
Pace                    0:07:09
TotalSeconds            10622.0
HalfSeconds              5404.0
Name: 4762, dtype: object
Somerdale
 Age                          48
M/F                           M
City                  Somerdale
State                        NJ
Country                     USA
Half            0 days 02:07:59
40K             0 days 04:44:32
Pace                    0:11:40
TotalSeconds            17072.0
HalfSeconds              7679.0
Name: 10392, dtype: object
Somers
 Age                          53
M/F                           F
City                     Somers
State                        CT
Country                     USA
Half            0 days 01:36:30
40K             0 days 03:14:09
Pace                    0:07:53
TotalSeconds            11649.0
HalfSeconds              5790.0
Name: 23093, dtype: object
Somers Point
 Age                          50
M/F                           M
City               Somers Point
State                        NJ
Country                     USA
Half            0 days 01:42:10
40K             0 days 03:39:42
Pace                    0:08:54
TotalSeconds            13182.0
HalfSeconds              6130.0
Name: 10204, dtype: object
Somerset
 Age                          46
M/F                           M
City                   Somerset
State                        KY
Country                     USA
Half            0 days 01:40:24
40K             0 days 03:13:13
Pace                    0:07:48
TotalSeconds            11593.0
HalfSeconds              6024.0
Name: 11927, dtype: object
Somersworth
 Age                          29
M/F                           F
City                Somersworth
State                        NH
Country                     USA
Half            0 days 01:49:33
40K             0 days 03:26:01
Pace                    0:08:17
TotalSeconds            12361.0
HalfSeconds              6573.0
Name: 14672, dtype: object
Somerville
 Age                          39
M/F                           M
City                 Somerville
State                        MA
Country                     USA
Half            0 days 01:12:48
40K             0 days 02:26:36
Pace                    0:05:55
TotalSeconds             8796.0
HalfSeconds              4368.0
Name: 986, dtype: object
Sondrio
 Age                          59
M/F                           M
City                    Sondrio
State                       NaN
Country                     ITA
Half            0 days 02:12:26
40K             0 days 04:25:16
Pace                    0:10:46
TotalSeconds            15916.0
HalfSeconds              7946.0
Name: 31443, dtype: object
Sonoma
 Age                          44
M/F                           M
City                     Sonoma
State                        CA
Country                     USA
Half            0 days 01:34:50
40K             0 days 03:06:53
Pace                    0:07:32
TotalSeconds            11213.0
HalfSeconds              5690.0
Name: 6452, dtype: object
Sonora
 Age                          55
M/F                           F
City                     Sonora
State                        CA
Country                     USA
Half            0 days 01:51:13
40K             0 days 03:46:35
Pace                    0:09:09
TotalSeconds            13595.0
HalfSeconds              6673.0
Name: 24986, dtype: object
Sooke
 Age                          64
M/F                           F
City                      Sooke
State                        BC
Country                     CAN
Half            0 days 02:14:10
40K             0 days 04:37:35
Pace                    0:11:15
TotalSeconds            16655.0
HalfSeconds              8050.0
Name: 25695, dtype: object
Sopo
 Age                          50
M/F                           M
City                       Sopo
State                       NaN
Country                     COL
Half            0 days 01:32:27
40K             0 days 02:57:43
Pace                    0:07:09
TotalSeconds            10663.0
HalfSeconds              5547.0
Name: 9163, dtype: object
Soquel
 Age                          54
M/F                           M
City                     Soquel
State                        CA
Country                     USA
Half            0 days 01:37:15
40K             0 days 03:17:53
Pace                    0:08:01
TotalSeconds            11873.0
HalfSeconds              5835.0
Name: 11660, dtype: object
Sorel-Tracy
 Age                          48
M/F                           M
City                Sorel-Tracy
State                        QC
Country                     CAN
Half            0 days 01:25:11
40K             0 days 02:42:50
Pace                    0:06:35
TotalSeconds             9770.0
HalfSeconds              5111.0
Name: 1706, dtype: object
Soro
 Age                          36
M/F                           M
City                       Soro
State                       NaN
Country                     DEN
Half            0 days 01:41:38
40K             0 days 03:41:49
Pace                    0:08:59
TotalSeconds            13309.0
HalfSeconds              6098.0
Name: 3299, dtype: object
Sorocaba
 Age                          41
M/F                           M
City                   Sorocaba
State                       NaN
Country                     BRA
Half            0 days 01:33:03
40K             0 days 03:26:17
Pace                    0:08:19
TotalSeconds            12377.0
HalfSeconds              5583.0
Name: 3808, dtype: object
Souderton
 Age                          40
M/F                           M
City                  Souderton
State                        PA
Country                     USA
Half            0 days 01:32:34
40K             0 days 03:02:57
Pace                    0:07:32
TotalSeconds            10977.0
HalfSeconds              5554.0
Name: 4033, dtype: object
Souderton Ave
 Age                          41
M/F                           M
City              Souderton Ave
State                        PA
Country                     USA
Half            0 days 01:23:42
40K             0 days 02:41:05
Pace                    0:06:29
TotalSeconds             9665.0
HalfSeconds              5022.0
Name: 1763, dtype: object
Sour Lake
 Age                          48
M/F                           F
City                  Sour Lake
State                        TX
Country                     USA
Half            0 days 02:25:00
40K             0 days 05:01:12
Pace                    0:12:12
TotalSeconds            18072.0
HalfSeconds              8700.0
Name: 27704, dtype: object
South Amboy
 Age                          42
M/F                           F
City                South Amboy
State                        NJ
Country                     USA
Half            0 days 02:21:30
40K             0 days 04:39:34
Pace                    0:11:16
TotalSeconds            16774.0
HalfSeconds              8490.0
Name: 31910, dtype: object
South Barrington
 Age                           48
M/F                            M
City            South Barrington
State                         IL
Country                      USA
Half             0 days 01:44:53
40K              0 days 03:18:19
Pace                     0:07:59
TotalSeconds             11899.0
HalfSeconds               6293.0
Name: 12790, dtype: object
South Beloit
 Age                          44
M/F                           F
City               South Beloit
State                        IL
Country                     USA
Half            0 days 02:02:42
40K             0 days 03:58:42
Pace                    0:09:37
TotalSeconds            14322.0
HalfSeconds              7362.0
Name: 20905, dtype: object
South Bend
 Age                          30
M/F                           M
City                 South Bend
State                        IN
Country                     USA
Half            0 days 01:17:21
40K             0 days 02:26:29
Pace                    0:05:54
TotalSeconds             8789.0
HalfSeconds              4641.0
Name: 306, dtype: object
South Berwick
 Age                          52
M/F                           F
City              South Berwick
State                        ME
Country                     USA
Half            0 days 01:59:05
40K             0 days 03:46:51
Pace                    0:09:07
TotalSeconds            13611.0
HalfSeconds              7145.0
Name: 22723, dtype: object
South Boston
 Age                          28
M/F                           M
City               South Boston
State                        MA
Country                     USA
Half            0 days 01:25:55
40K             0 days 02:45:35
Pace                    0:06:40
TotalSeconds             9935.0
HalfSeconds              5155.0
Name: 2505, dtype: object
South Burlington
 Age                           42
M/F                            M
City            South Burlington
State                         VT
Country                      USA
Half             0 days 01:33:15
40K              0 days 03:01:32
Pace                     0:07:20
TotalSeconds             10892.0
HalfSeconds               5595.0
Name: 8275, dtype: object
South Charleston
 Age                           32
M/F                            M
City            South Charleston
State                         WV
Country                      USA
Half             0 days 01:28:21
40K              0 days 02:55:13
Pace                     0:07:04
TotalSeconds             10513.0
HalfSeconds               5301.0
Name: 1711, dtype: object
South Chittenden
 Age                           53
M/F                            F
City            South Chittenden
State                         VT
Country                      USA
Half             0 days 01:49:08
40K              0 days 03:34:41
Pace                     0:08:40
TotalSeconds             12881.0
HalfSeconds               6548.0
Name: 24814, dtype: object
South Dartmouth
 Age                          34
M/F                           F
City            South Dartmouth
State                        MA
Country                     USA
Half            0 days 01:43:24
40K             0 days 03:33:36
Pace                    0:08:39
TotalSeconds            12816.0
HalfSeconds              6204.0
Name: 15370, dtype: object
South Deerfield
 Age                          36
M/F                           F
City            South Deerfield
State                        MA
Country                     USA
Half            0 days 01:36:49
40K             0 days 03:10:06
Pace                    0:07:41
TotalSeconds            11406.0
HalfSeconds              5809.0
Name: 17207, dtype: object
South Dennis
 Age                          39
M/F                           M
City               South Dennis
State                        MA
Country                     USA
Half            0 days 01:36:14
40K             0 days 03:08:51
Pace                    0:07:37
TotalSeconds            11331.0
HalfSeconds              5774.0
Name: 6596, dtype: object
South Easton
 Age                          39
M/F                           M
City               South Easton
State                        MA
Country                     USA
Half            0 days 01:54:20
40K             0 days 03:57:22
Pace                    0:09:39
TotalSeconds            14242.0
HalfSeconds              6860.0
Name: 28772, dtype: object
South Elgin
 Age                          36
M/F                           M
City                South Elgin
State                        IL
Country                     USA
Half            0 days 01:27:54
40K             0 days 03:03:14
Pace                    0:07:29
TotalSeconds            10994.0
HalfSeconds              5274.0
Name: 4575, dtype: object
South Esk
 Age                          47
M/F                           M
City                  South Esk
State                        NB
Country                     CAN
Half            0 days 01:33:51
40K             0 days 03:05:00
Pace                    0:07:29
TotalSeconds            11100.0
HalfSeconds              5631.0
Name: 7179, dtype: object
South Gate
 Age                          51
M/F                           M
City                 South Gate
State                        CA
Country                     USA
Half            0 days 02:08:39
40K             0 days 04:42:10
Pace                    0:11:19
TotalSeconds            16930.0
HalfSeconds              7719.0
Name: 3910, dtype: object
South Glastonbury
 Age                            55
M/F                             F
City            South Glastonbury
State                          CT
Country                       USA
Half              0 days 01:53:24
40K               0 days 03:48:48
Pace                      0:09:15
TotalSeconds              13728.0
HalfSeconds                6804.0
Name: 21735, dtype: object
South Hadley
 Age                          36
M/F                           M
City               South Hadley
State                        MA
Country                     USA
Half            0 days 01:31:00
40K             0 days 03:02:57
Pace                    0:07:32
TotalSeconds            10977.0
HalfSeconds              5460.0
Name: 7317, dtype: object
South Hamilton
 Age                          22
M/F                           M
City             South Hamilton
State                        MA
Country                     USA
Half            0 days 01:27:54

South Park
 Age                          26
M/F                           F
City                 South Park
State                        PA
Country                     USA
Half            0 days 01:39:31
40K             0 days 03:16:29
Pace                    0:07:55
TotalSeconds            11789.0
HalfSeconds              5971.0
Name: 8229, dtype: object
South Pasadena
 Age                          25
M/F                           F
City             South Pasadena
State                        CA
Country                     USA
Half            0 days 01:37:23
40K             0 days 03:13:26
Pace                    0:07:48
TotalSeconds            11606.0
HalfSeconds              5843.0
Name: 16362, dtype: object
South Perth
 Age                          46
M/F                           F
City                South Perth
State                       NaN
Country                     AUS
Half            0 days 01:52:15
40K             0 days 03:39:01
Pace                    0:08:53
TotalSeconds            13141.0
HalfSeconds              6735.0
Name: 21460, dtype: object
South Portland
 Age                          37
M/F                           F
City             South Portland
State                        ME
Country                     USA
Half            0 days 01:40:17
40K             0 days 03:27:52
Pace                    0:08:23
TotalSeconds            12472.0
HalfSeconds              6017.0
Name: 15089, dtype: object
South Riding
 Age                          30
M/F                           M
City               South Riding
State                        VA
Country                     USA
Half            0 days 01:25:59
40K             0 days 02:51:15
Pace                    0:06:54
TotalSeconds            10275.0
HalfSeconds              5159.0
Name: 2361, dtype: object
South Salem
 Age                          58
M/F                           M
City                South Salem
State                        NY
Country                     USA
Half            0 days 01:43:54
40K             0 days 03:20:04
Pace                    0:08:05
TotalSeconds            12004.0
HalfSeconds              6234.0
Name: 15261, dtype: object
South Salt Lake
 Age                          30
M/F                           F
City            South Salt Lake
State                        UT
Country                     USA
Half            0 days 02:06:43
40K             0 days 04:34:08
Pace                    0:11:03
TotalSeconds            16448.0
HalfSeconds              7603.0
Name: 17705, dtype: object
South San Francisco
 Age                              26
M/F                               F
City            South San Francisco
State                            CA
Country                         USA
Half                0 days 01:43:56
40K                 0 days 03:35:06
Pace                        0:08:45
TotalSeconds                12906.0
HalfSeconds                  6236.0
Name: 15413, dtype: object
South Surrey
 Age                          55
M/F                           M
City               South Surrey
State                        BC
Country                     CAN
Half            0 days 01:40:24
40K             0 days 03:15:30
Pace                    0:07:55
TotalSeconds            11730.0
HalfSeconds              6024.0
Name: 16055, dtype: object
South Wales
 Age                          39
M/F                           F
City                South Wales
State                        NY
Country                     USA
Half            0 days 01:37:20
40K             0 days 03:10:59
Pace                    0:07:44
TotalSeconds            11459.0
HalfSeconds              5840.0
Name: 10263, dtype: object
South Weber
 Age                          37
M/F                           F
City                South Weber
State                        UT
Country                     USA
Half            0 days 01:27:40
40K             0 days 02:52:29
Pace                    0:06:58
TotalSeconds            10349.0
HalfSeconds              5260.0
Name: 1613, dtype: object
South Weymouth
 Age                          30
M/F                           M
City             South Weymouth
State                        MA
Country                     USA
Half            0 days 02:07:53
40K             0 days 04:15:50
Pace                    0:10:21
TotalSeconds            15350.0
HalfSeconds              7673.0
Name: 27486, dtype: object
South Windsor
 Age                          55
M/F                           M
City              South Windsor
State                        CT
Country                     USA
Half            0 days 02:27:28
40K             0 days 05:09:51
Pace                    0:12:30
TotalSeconds            18591.0
HalfSeconds              8848.0
Name: 31368, dtype: object
South Woodslee
 Age                          48
M/F                           M
City             South Woodslee
State                        ON
Country                     CAN
Half            0 days 01:31:39
40K             0 days 03:10:45
Pace                    0:07:42
TotalSeconds            11445.0
HalfSeconds              5499.0
Name: 4356, dtype: object
South Yarmouth
 Age                          41
M/F                           M
City             South Yarmouth
State                        MA
Country                     USA
Half            0 days 01:32:30
40K             0 days 03:06:07
Pace                    0:07:34
TotalSeconds            11167.0
HalfSeconds              5550.0
Name: 8518, dtype: object
Southampton
 Age                          32
M/F                           M
City                Southampton
State                        MA
Country                     USA
Half            0 days 01:18:15
40K             0 days 02:34:53
Pace                    0:06:15
TotalSeconds             9293.0
HalfSeconds              4695.0
Name: 2835, dtype: object
Southaven
 Age                          51
M/F                           F
City                  Southaven
State                        MS
Country                     USA
Half            0 days 02:06:36
40K             0 days 04:38:19
Pace                    0:11:13
TotalSeconds            16699.0
HalfSeconds              7596.0
Name: 25058, dtype: object
Southboro
 Age                          27
M/F                           F
City                  Southboro
State                        MA
Country                     USA
Half            0 days 02:04:03
40K             0 days 04:19:10
Pace                    0:10:29
TotalSeconds            15550.0
HalfSeconds              7443.0
Name: 30738, dtype: object
Southborough
 Age                          28
M/F                           F
City               Southborough
State                        MA
Country                     USA
Half            0 days 01:25:10
40K             0 days 02:46:40
Pace                    0:06:43
TotalSeconds            10000.0
HalfSeconds              5110.0
Name: 1879, dtype: object
Southbury
 Age                          39
M/F                           F
City                  Southbury
State                        CT
Country                     USA
Half            0 days 01:49:20
40K             0 days 03:40:12
Pace                    0:08:53
TotalSeconds            13212.0
HalfSeconds              6560.0
Name: 20009, dtype: object
Southern Pines
 Age                          35
M/F                           M
City             Southern Pines
State                        NC
Country                     USA
Half            0 days 01:32:58
40K             0 days 03:06:46
Pace                    0:07:35
TotalSeconds            11206.0
HalfSeconds              5578.0
Name: 5757, dtype: object
Southgate
 Age                          37
M/F                           F
City                  Southgate
State                        MI
Country                     USA
Half            0 days 01:38:26
40K             0 days 03:13:58
Pace                    0:07:49
TotalSeconds            11638.0
HalfSeconds              5906.0
Name: 10023, dtype: object
Southington
 Age                          33
M/F                           F
City                Southington
State                        CT
Country                     USA
Half            0 days 01:36:35
40K             0 days 03:08:12
Pace                    0:07:35
TotalSeconds            11292.0
HalfSeconds              5795.0
Name: 11379, dtype: object
Southlake
 Age                          35
M/F                           F
City                  Southlake
State                        TX
Country                     USA
Half            0 days 01:41:16
40K             0 days 03:15:45
Pace                    0:07:52
TotalSeconds            11745.0
HalfSeconds              6076.0
Name: 16613, dtype: object
Southport
 Age                          44
M/F                           M
City                  Southport
State                        CT
Country                     USA
Half            0 days 01:31:37
40K             0 days 03:07:40
Pace                    0:07:34
TotalSeconds            11260.0
HalfSeconds              5497.0
Name: 6520, dtype: object
Southport Park
 Age                          42
M/F                           F
City             Southport Park
State                       NaN
Country                     AUS
Half            0 days 01:43:58
40K             0 days 03:23:00
Pace                    0:08:11
TotalSeconds            12180.0
HalfSeconds              6238.0
Name: 14515, dtype: object
Southside
 Age                          30
M/F                           M
City                  Southside
State                        AL
Country                     USA
Half            0 days 01:24:53
40K             0 days 03:07:11
Pace                    0:07:37
TotalSeconds            11231.0
HalfSeconds              5093.0
Name: 1538, dtype: object
Southwest Harbor
 Age                           47
M/F                            M
City            Southwest Harbor
State                         ME
Country                      USA
Half             0 days 01:30:57
40K              0 days 02:56:34
Pace                     0:07:09
TotalSeconds             10594.0
HalfSeconds               5457.0
Name: 7034, dtype: object
Southwest Ranches
 Age                            56
M/F                             F
City            Southwest Ranches
State                          FL
Country                       USA
Half              0 days 01:54:44
40K               0 days 04:06:33
Pace                      0:10:01
TotalSeconds              14793.0
HalfSeconds                6884.0
Name: 22098, dtype: object
Southwick
 Age                          54
M/F                           M
City                  Southwick
State                        MA
Country                     USA
Half            0 days 01:42:26
40K             0 days 03:26:51
Pace                    0:08:21
TotalSeconds            12411.0
HalfSeconds              6146.0
Name: 13767, dtype: object
Spanaway
 Age                          63
M/F                           M
City                   Spanaway
State                        WA
Country                     USA
Half            0 days 01:46:34
40K             0 days 03:40:18
Pace                    0:09:01
TotalSeconds            13218.0
HalfSeconds              6394.0
Name: 19232, dtype: object
Spanish Fork
 Age                          20
M/F                           F
City               Spanish Fork
State                        UT
Country                     USA
Half            0 days 01:42:33
40K             0 days 03:15:43
Pace                    0:07:52
TotalSeconds            11743.0
HalfSeconds              6153.0
Name: 11816, dtype: object
Spanish Fort
 Age                          37
M/F                           M
City               Spanish Fort
State                        AL
Country                     USA
Half            0 days 01:59:44
40K             0 days 04:00:16
Pace                    0:09:43
TotalSeconds            14416.0
HalfSeconds              7184.0
Name: 568, dtype: object
Sparks
 Age                          33
M/F                           M
City                     Sparks
State                        NV
Country                     USA
Half            0 days 01:24:44
40K             0 days 02:46:56
Pace                    0:06:45
TotalSeconds            10016.0
HalfSeconds              5084.0
Name: 227, dtype: object
Sparr
 Age                          47
M/F                           M
City                      Sparr
State                        FL
Country                     USA
Half            0 days 01:44:13
40K             0 days 03:18:35
Pace                    0:07:59
TotalSeconds            11915.0
HalfSeconds              6253.0
Name: 11909, dtype: object
Sparta
 Age                          35
M/F                           M
City                     Sparta
State                        WI
Country                     USA
Half            0 days 01:34:49
40K             0 days 03:06:51
Pace                    0:07:34
TotalSeconds            11211.0
HalfSeconds              5689.0
Name: 4430, dtype: object
Spartanburg
 Age                          39
M/F                           M
City                Spartanburg
State                        SC
Country                     USA
Half            0 days 01:34:09
40K             0 days 03:12:45
Pace                    0:07:50
TotalSeconds            11565.0
HalfSeconds              5649.0
Name: 5350, dtype: object
Speculator
 Age                          25
M/F                           F
City                 Speculator
State                        NY
Country                     USA
Half            0 days 01:43:55
40K             0 days 03:19:23
Pace                    0:08:07
TotalSeconds            11963.0
HalfSeconds              6235.0
Name: 16850, dtype: object
Spencer
 Age                          72
M/F                           M
City                    Spencer
State                        TN
Country                     USA
Half            0 days 02:08:40
40K             0 days 04:22:57
Pace                    0:10:39
TotalSeconds            15777.0
HalfSeconds              7720.0
Name: 25861, dtype: object
Spencerport
 Age                          55
M/F                           M
City                Spencerport
State                        NY
Country                     USA
Half            0 days 01:32:32
40K             0 days 03:04:37
Pace                    0:07:28
TotalSeconds            11077.0
HalfSeconds              5552.0
Name: 2259, dtype: object
Spencerville
 Age                          45
M/F                           M
City               Spencerville
State                        ON
Country                     CAN
Half            0 days 01:42:53
40K             0 days 03:40:50
Pace                    0:08:57
TotalSeconds            13250.0
HalfSeconds              6173.0
Name: 9339, dtype: object
Spicer
 Age                          42
M/F                           F
City                     Spicer
State                        MN
Country                     USA
Half            0 days 01:44:43
40K             0 days 03:22:58
Pace                    0:08:11
TotalSeconds            12178.0
HalfSeconds              6283.0
Name: 19873, dtype: object
Spijkenisse
 Age                          39
M/F                           M
City                Spijkenisse
State                       NaN
Country                     NED
Half            0 days 01:42:13
40K             0 days 03:41:06
Pace                    0:09:00
TotalSeconds            13266.0
HalfSeconds              6133.0
Name: 4709, dtype: object
Spokane
 Age                          39
M/F                           M
City                    Spokane
State                        WA
Country                     USA
Half            0 days 01:26:50
40K             0 days 02:49:56
Pace                    0:06:52
TotalSeconds            10196.0
HalfSeconds              5210.0
Name: 3600, dtype: object
Spokane Valley
 Age                          26
M/F                           F
City             Spokane Valley
State                        WA
Country                     USA
Half            0 days 01:48:11
40K             0 days 03:58:49
Pace                    0:09:47
TotalSeconds            14329.0
HalfSeconds              6491.0
Name: 16378, dtype: object
Spotswood
 Age                          30
M/F                           M
City                  Spotswood
State                        NJ
Country                     USA
Half            0 days 02:38:57
40K             0 days 05:45:49
Pace                    0:13:52
TotalSeconds            20749.0
HalfSeconds              9537.0
Name: 29716, dtype: object
Sprakers
 Age                          52
M/F                           M
City                   Sprakers
State                        NY
Country                     USA
Half            0 days 01:32:52
40K             0 days 03:10:52
Pace                    0:07:41
TotalSeconds            11452.0
HalfSeconds              5572.0
Name: 5882, dtype: object
Spring
 Age                          26
M/F                           M
City                     Spring
State                        TX
Country                     USA
Half            0 days 01:18:10
40K             0 days 02:42:56
Pace                    0:06:35
TotalSeconds             9776.0
HalfSeconds              4690.0
Name: 409, dtype: object
Spring Arbor
 Age                          51
M/F                           M
City               Spring Arbor
State                        MI
Country                     USA
Half            0 days 01:42:20
40K             0 days 03:28:38
Pace                    0:08:29
TotalSeconds            12518.0
HalfSeconds              6140.0
Name: 10299, dtype: object
Spring Hill
 Age                          49
M/F                           M
City                Spring Hill
State                        KS
Country                     USA
Half            0 days 01:42:45
40K             0 days 03:41:08
Pace                    0:09:00
TotalSeconds            13268.0
HalfSeconds              6165.0
Name: 11580, dtype: object
Spring Lake
 Age                          48
M/F                           M
City                Spring Lake
State                        MI
Country                     USA
Half            0 days 01:34:16
40K             0 days 03:01:41
Pace                    0:07:22
TotalSeconds            10901.0
HalfSeconds              5656.0
Name: 7403, dtype: object
Spring Lake Heights
 Age                              60
M/F                               F
City            Spring Lake Heights
State                            NJ
Country                         USA
Half                0 days 02:02:17
40K                 0 days 03:59:21
Pace                        0:09:40
TotalSeconds                14361.0
HalfSeconds                  7337.0
Name: 25768, dtype: object
Spring Valley
 Age                          38
M/F                           M
City              Spring Valley
State                        CA
Country                     USA
Half            0 days 01:32:02
40K             0 days 03:14:43
Pace                    0:07:55
TotalSeconds            11683.0
HalfSeconds              5522.0
Name: 6246, dtype: object
Springboro
 Age                          39
M/F                           F
City                 Springboro
State                        OH
Country                     USA
Half            0 days 01:45:54
40K             0 days 03:27:27
Pace                    0:08:24
TotalSeconds            12447.0
HalfSeconds              6354.0
Name: 18904, dtype: object
Springfield
 Age                          19
M/F                           M
City                Springfield
State                        NY
Country                     USA
Half            0 days 01:23:44
40K             0 days 02:44:39
Pace                    0:06:42
TotalSeconds             9879.0
HalfSeconds              5024.0
Name: 1188, dtype: object
Springhill
 Age                          43
M/F                           M
City                 Springhill

St Louis Park
 Age                          29
M/F                           F
City              St Louis Park
State                        MN
Country                     USA
Half            0 days 01:39:19
40K             0 days 03:07:10
Pace                    0:07:31
TotalSeconds            11230.0
HalfSeconds              5959.0
Name: 10985, dtype: object
St Michaels
 Age                          50
M/F                           M
City                St Michaels
State                        AZ
Country                     USA
Half            0 days 01:49:03
40K             0 days 03:47:37
Pace                    0:09:10
TotalSeconds            13657.0
HalfSeconds              6543.0
Name: 14105, dtype: object
St Paul
 Age                          37
M/F                           M
City                    St Paul
State                        MN
Country                     USA
Half            0 days 01:18:50
40K             0 days 02:37:41
Pace                    0:06:24
TotalSeconds             9461.0
HalfSeconds              4730.0
Name: 501, dtype: object
St Peters
 Age                          44
M/F                           F
City                  St Peters
State                        MO
Country                     USA
Half            0 days 01:49:26
40K             0 days 03:31:56
Pace                    0:08:34
TotalSeconds            12716.0
HalfSeconds              6566.0
Name: 19526, dtype: object
St Petersburg
 Age                          42
M/F                           M
City              St Petersburg
State                        FL
Country                     USA
Half            0 days 01:25:47
40K             0 days 02:49:11
Pace                    0:06:52
TotalSeconds            10151.0
HalfSeconds              5147.0
Name: 3458, dtype: object
St Stephen
 Age                          40
M/F                           M
City                 St Stephen
State                        MN
Country                     USA
Half            0 days 01:37:39
40K             0 days 03:22:44
Pace                    0:08:18
TotalSeconds            12164.0
HalfSeconds              5859.0
Name: 6638, dtype: object
St Thomas
 Age                          41
M/F                           F
City                  St Thomas
State                        ON
Country                     CAN
Half            0 days 02:01:13
40K             0 days 04:00:06
Pace                    0:09:40
TotalSeconds            14406.0
HalfSeconds              7273.0
Name: 21446, dtype: object
St-Ambroise
 Age                          54
M/F                           M
City                St-Ambroise
State                        QC
Country                     CAN
Half            0 days 01:28:33
40K             0 days 02:49:58
Pace                    0:06:51
TotalSeconds            10198.0
HalfSeconds              5313.0
Name: 3025, dtype: object
St-Andre Du Lac-St-Jean
 Age                                  71
M/F                                   M
City            St-Andre Du Lac-St-Jean
State                                QC
Country                             CAN
Half                    0 days 02:04:40
40K                     0 days 04:20:20
Pace                            0:10:39
TotalSeconds                    15620.0
HalfSeconds                      7480.0
Name: 25412, dtype: object
St-Armand
 Age                          61
M/F                           F
City                  St-Armand
State                        QC
Country                     CAN
Half            0 days 01:37:05
40K             0 days 03:06:42
Pace                    0:07:32
TotalSeconds            11202.0
HalfSeconds              5825.0
Name: 10146, dtype: object
St-Augustin De Desmaures
 Age                                   38
M/F                                    M
City            St-Augustin De Desmaures
State                                 QC
Country                              CAN
Half                     0 days 01:24:33
40K                      0 days 02:44:53
Pace                             0:06:40
TotalSeconds                      9893.0
HalfSeconds                       5073.0
Name: 1340, dtype: object
St-Augustin-De-Desmaures
 Age                                   35
M/F                                    F
City            St-Augustin-De-Desmaures
State                                 QC
Country                              CAN
Half                     0 days 01:42:49
40K                      0 days 03:19:49
Pace                             0:08:04
TotalSeconds                     11989.0
HalfSeconds                       6169.0
Name: 13160, dtype: object
St-Barnabe
 Age                          53
M/F                           M
City                 St-Barnabe
State                        QC
Country                     CAN
Half            0 days 01:39:03
40K             0 days 03:12:58
Pace                    0:07:47
TotalSeconds            11578.0
HalfSeconds              5943.0
Name: 12906, dtype: object
St-Basile-Le-Grand
 Age                             57
M/F                              M
City            St-Basile-Le-Grand
State                           QC
Country                        CAN
Half               0 days 01:26:04
40K                0 days 02:49:38
Pace                       0:06:51
TotalSeconds               10178.0
HalfSeconds                 5164.0
Name: 2346, dtype: object
St-Bruno
 Age                          46
M/F                           M
City                   St-Bruno
State                        QC
Country                     CAN
Half            0 days 01:25:32
40K             0 days 02:48:09
Pace                    0:06:48
TotalSeconds            10089.0
HalfSeconds              5132.0
Name: 2203, dtype: object
St-Bruno De Montarville
 Age                                  54
M/F                                   F
City            St-Bruno De Montarville
State                                QC
Country                             CAN
Half                    0 days 01:55:22
40K                     0 days 03:43:35
Pace                            0:09:01
TotalSeconds                    13415.0
HalfSeconds                      6922.0
Name: 22864, dtype: object
St-Bruno-De-Montarville
 Age                                  45
M/F                                   F
City            St-Bruno-De-Montarville
State                                QC
Country                             CAN
Half                    0 days 01:30:42
40K                     0 days 03:01:45
Pace                            0:07:21
TotalSeconds                    10905.0
HalfSeconds                      5442.0
Name: 8665, dtype: object
St-Constant
 Age                          46
M/F                           M
City                St-Constant
State                        QC
Country                     CAN
Half            0 days 01:35:04
40K             0 days 03:20:04
Pace                    0:08:03
TotalSeconds            12004.0
HalfSeconds              5704.0
Name: 7218, dtype: object
St-Elie-De-Caxton
 Age                            53
M/F                             M
City            St-Elie-De-Caxton
State                          QC
Country                       CAN
Half              0 days 01:49:33
40K               0 days 03:53:17
Pace                      0:09:29
TotalSeconds              13997.0
HalfSeconds                6573.0
Name: 14486, dtype: object
St-Gabriel-De-Valcartier
 Age                                   39
M/F                                    F
City            St-Gabriel-De-Valcartier
State                                 QC
Country                              CAN
Half                     0 days 01:49:36
40K                      0 days 03:35:37
Pace                             0:08:40
TotalSeconds                     12937.0
HalfSeconds                       6576.0
Name: 19365, dtype: object
St-Gedeon
 Age                          56
M/F                           M
City                  St-Gedeon
State                        QC
Country                     CAN
Half            0 days 01:41:29
40K             0 days 03:21:37
Pace                    0:08:09
TotalSeconds            12097.0
HalfSeconds              6089.0
Name: 12227, dtype: object
St-Hilaire
 Age                          37
M/F                           F
City                 St-Hilaire
State                        QC
Country                     CAN
Half            0 days 01:44:11
40K             0 days 03:33:46
Pace                    0:08:39
TotalSeconds            12826.0
HalfSeconds              6251.0
Name: 18309, dtype: object
St-Hippolyte
 Age                          53
M/F                           M
City               St-Hippolyte
State                        QC
Country                     CAN
Half            0 days 01:41:56
40K             0 days 03:22:03
Pace                    0:08:10
TotalSeconds            12123.0
HalfSeconds              6116.0
Name: 9730, dtype: object
St-Hubert
 Age                          59
M/F                           F
City                  St-Hubert
State                        QC
Country                     CAN
Half            0 days 01:53:26
40K             0 days 03:53:19
Pace                    0:09:24
TotalSeconds            13999.0
HalfSeconds              6806.0

Name: 24571, dtype: object
St-Jean-Sur-Richelieu
 Age                                43
M/F                                 M
City            St-Jean-Sur-Richelieu
State                              QC
Country                           CAN
Half                  0 days 01:29:08
40K                   0 days 03:10:42
Pace                          0:07:40
TotalSeconds                  11442.0
HalfSeconds                    5348.0
Name: 3861, dtype: object
St-Jerome
 Age                          50
M/F                           F
City                  St-Jerome
State                        QC
Country                     CAN
Half            0 days 01:52:26
40K             0 days 03:34:59
Pace                    0:08:38
TotalSeconds            12899.0
HalfSeconds              6746.0
Name: 23348, dtype: object
St-Joseph De Coleraine
 Age                                 57
M/F                                  M
City            St-Joseph De Coleraine
State                               QC
Country                            CAN
Half                   0 days 01:47:53
40K                    0 days 03:38:10
Pace                           0:08:50
TotalSeconds                   13090.0
HalfSeconds                     6473.0
Name: 19978, dtype: object
St-Lambert
 Age                          44
M/F                           F
City                 St-Lambert
State                        QC
Country                     CAN
Half            0 days 01:40:45
40K             0 days 03:22:09
Pace                    0:08:11
TotalSeconds            12129.0
HalfSeconds              6045.0
Name: 11230, dtype: object
St-Laurent
 Age                          45
M/F                           M
City                 St-Laurent
State                        QC
Country                     CAN
Half            0 days 01:31:21
40K             0 days 02:59:18
Pace                    0:07:14
TotalSeconds            10758.0
HalfSeconds              5481.0
Name: 2481, dtype: object
St-Laurent - I.o.
 Age                            61
M/F                             M
City            St-Laurent - I.o.
State                          QC
Country                       CAN
Half              0 days 01:39:31
40K               0 days 03:21:09
Pace                      0:08:10
TotalSeconds              12069.0
HalfSeconds                5971.0
Name: 9839, dtype: object
St-Laurent-Ile-Orleans
 Age                                 29
M/F                                  F
City            St-Laurent-Ile-Orleans
State                               QC
Country                            CAN
Half                   0 days 01:37:35
40K                    0 days 03:12:35
Pace                           0:07:46
TotalSeconds                   11555.0
HalfSeconds                     5855.0
Name: 16525, dtype: object
St-Lazare
 Age                          42
M/F                           M
City                  St-Lazare
State                        QC
Country                     CAN
Half            0 days 01:34:48
40K             0 days 03:26:59
Pace                    0:08:25
TotalSeconds            12419.0
HalfSeconds              5688.0
Name: 8528, dtype: object
St-Leonard-D'Aston
 Age                             37
M/F                              M
City            St-Leonard-D'Aston
State                           QC
Country                        CAN
Half               0 days 01:18:29
40K                0 days 02:40:11
Pace                       0:06:31
TotalSeconds                9611.0
HalfSeconds                 4709.0
Name: 355, dtype: object
St-Paul
 Age                          29
M/F                           M
City                    St-Paul
State                        QC
Country                     CAN
Half            0 days 01:26:34
40K             0 days 02:55:39
Pace                    0:07:08
TotalSeconds            10539.0
HalfSeconds              5194.0
Name: 1870, dtype: object
St-Paul-De-Montminy
 Age                              72
M/F                               M
City            St-Paul-De-Montminy
State                            QC
Country                         CAN
Half                0 days 02:12:29
40K                 0 days 04:30:11
Pace                        0:10:59
TotalSeconds                16211.0
HalfSeconds                  7949.0
Name: 25209, dtype: object
St-Remi
 Age                          58
M/F                           M
City                    St-Remi
State                        QC
Country                     CAN
Half            0 days 01:47:45
40K             0 days 03:38:37
Pace                    0:08:50
TotalSeconds            13117.0
HalfSeconds              6465.0
Name: 15398, dtype: object
St-Romuald
 Age                          42
M/F                           M
City                 St-Romuald
State                        QC
Country                     CAN
Half            0 days 01:34:03
40K             0 days 03:18:35
Pace                    0:08:03
TotalSeconds            11915.0
HalfSeconds              5643.0
Name: 6107, dtype: object
St. Albert
 Age                          53
M/F                           M
City                 St. Albert
State                        AB
Country                     CAN
Half            0 days 01:33:26
40K             0 days 03:09:18
Pace                    0:07:42
TotalSeconds            11358.0
HalfSeconds              5606.0
Name: 9960, dtype: object
St. Augustine
 Age                          44
M/F                           F
City              St. Augustine
State                        FL
Country                     USA
Half            0 days 01:49:30
40K             0 days 03:29:10
Pace                    0:08:25
TotalSeconds            12550.0
HalfSeconds              6570.0
Name: 20161, dtype: object
St. Catharines
 Age                          41
M/F                           F
City             St. Catharines
State                        ON
Country                     CAN
Half            0 days 01:29:31
40K             0 days 03:02:13
Pace                    0:07:21
TotalSeconds            10933.0
HalfSeconds              5371.0
Name: 3526, dtype: object
St. Charles
 Age                          40
M/F                           F
City                St. Charles
State                        IL
Country                     USA
Half            0 days 01:29:01
40K             0 days 02:54:57
Pace                    0:07:04
TotalSeconds            10497.0
HalfSeconds              5341.0
Name: 4760, dtype: object
St. Cloud
 Age                          22
M/F                           M
City                  St. Cloud
State                        MN
Country                     USA
Half            0 days 01:18:52
40K             0 days 02:57:33
Pace                    0:08:02
TotalSeconds            10653.0
HalfSeconds              4732.0
Name: 146, dtype: object
St. Edward
 Age                          57
M/F                           M
City                 St. Edward
State                        PE
Country                     CAN
Half            0 days 01:53:55
40K             0 days 04:14:40
Pace                    0:10:13
TotalSeconds            15280.0
HalfSeconds              6835.0
Name: 13114, dtype: object
St. George
 Age                          36
M/F                           F
City                 St. George
State                        UT
Country                     USA
Half            0 days 01:30:39
40K             0 days 02:51:48
Pace                    0:06:54
TotalSeconds            10308.0
HalfSeconds              5439.0
Name: 7167, dtype: object
St. George's
 Age                          42
M/F                           M
City               St. George's
State                       NaN
Country                     BER
Half            0 days 01:47:28
40K             0 days 03:44:39
Pace                    0:09:11
TotalSeconds            13479.0
HalfSeconds              6448.0
Name: 30932, dtype: object
St. Helena
 Age                          29
M/F                           F
City                 St. Helena
State                        CA
Country                     USA
Half            0 days 01:48:51
40K             0 days 03:29:40
Pace                    0:08:26
TotalSeconds            12580.0
HalfSeconds              6531.0
Name: 16487, dtype: object
St. Jacobs
 Age                          41
M/F                           F
City                 St. Jacobs
State                        ON
Country                     CAN
Half            0 days 02:07:07
40K             0 days 04:16:15
Pace                    0:10:15
TotalSeconds            15375.0
HalfSeconds              7627.0
Name: 21465, dtype: object
St. John'S
 Age                          44
M/F                           F
City                 St. John'S
State                        NL
Country                     CAN
Half            0 days 01:53:01
40K             0 days 03:42:51
Pace                    0:09:00
TotalSeconds            13371.0
HalfSeconds              6781.0
Name: 21119, dtype: object
St. John's
 Age                          44
M/F                           F
City                 St. John's
State                        NL
Country                     CAN
Half            0 days 01:34:36
40K             0 days 03:07:57
Pace                    0:07:35
TotalSeconds            11277.0
HalfSeconds              5676.0
Name: 16017, dtype: object
St. Johns
 Age                          35
M/F                           F
City                  St. Johns
State                        NL
Country                     CAN
Half            0 days 01:32:38
40K             0 days 03:05:32
Pace                    0:07:31
TotalSeconds            11132.0
HalfSeconds              5558.0
Name: 14421, dtype: object
St. Johnsville
 Age                          57
M/F                           M
City             St. Johnsville
State                        NY
Country                     USA
Half            0 days 01:39:29
40K             0 days 03:21:42
Pace                    0:08:09
TotalSeconds            12102.0
HalfSeconds              5969.0
Name: 10824, dtype: object
St. Joseph
 Age                          39
M/F                           M
City                 St. Joseph
State                        MO
Country                     USA
Half            0 days 01:31:06
40K             0 days 03:08:43
Pace                    0:07:38
TotalSeconds            11323.0
HalfSeconds              5466.0
Name: 2567, dtype: object
St. Louis
 Age                          30
M/F                           M
City                  St. Louis
State                        MO
Country                     USA
Half            0 days 01:12:31
40K             0 days 02:26:30
Pace                    0:05:57
TotalSeconds             8790.0
HalfSeconds              4351.0
Name: 195, dtype: object
St. Louis Park
 Age                          29
M/F                           M
City             St. Louis Park
State                        MN
Country                     USA
Half            0 days 01:33:11
40K             0 days 03:08:43
Pace                    0:07:37
TotalSeconds            11323.0
HalfSeconds              5591.0
Name: 1049, dtype: object
St. Paul
 Age                          32
M/F                           M
City                   St. Paul
State                        MN
Country                     USA
Half            0 days 01:24:26
40K             0 days 02:46:11
Pace                    0:06:43
TotalSeconds             9971.0
HalfSeconds              5066.0
Name: 2114, dtype: object
St. Petersburg
 Age                          33
M/F                           M
City             St. Petersburg
State                        FL
Country                     USA
Half            0 days 01:17:12
40K             0 days 02:38:48
Pace                    0:06:28
TotalSeconds             9528.0
HalfSeconds              4632.0
Name: 1087, dtype: object
St. Thomas
 Age                          38
M/F                           F
City                 St. Thomas
State                        ON
Country                     CAN
Half            0 days 01:47:08
40K             0 days 03:26:44
Pace                    0:08:21
TotalSeconds            12404.0
HalfSeconds              6428.0
Name: 20111, dtype: object
St. Veit An Der Goelsen
 Age                                  43
M/F                                   M
City            St. Veit An Der Goelsen
State                               NaN
Country                             AUT
Half                    0 days 01:54:29
40K                     0 days 03:34:26
Pace                            0:08:37
TotalSeconds                    12866.0
HalfSeconds                      6869.0
Name: 31768, dtype: object
St.charles
 Age                          51
M/F                           F
City                 St.charles
State                        IL
Country                     USA
Half            0 days 01:53:12
40K             0 days 03:41:56
Pace                    0:08:56
TotalSeconds            13316.0
HalfSeconds              6792.0
Name: 13922, dtype: object
St.john'S
 Age                          38
M/F                           M
City                  St.john'S
State                        NL
Country                     CAN
Half            0 days 01:33:37
40K             0 days 03:22:26
Pace                    0:08:09
TotalSeconds            12146.0
HalfSeconds              5617.0
Name: 6235, dtype: object
St.malo
 Age                          49
M/F                           F
City                    St.malo
State                        MB
Country                     CAN
Half            0 days 01:41:12
40K             0 days 03:18:02
Pace                    0:08:01
TotalSeconds            11882.0
HalfSeconds              6072.0
Name: 21617, dtype: object
Stabekk
 Age                          41
M/F                           M
City                    Stabekk
State                       NaN
Country                     NOR
Half            0 days 01:30:31
40K             0 days 03:06:55
Pace                    0:07:38
TotalSeconds            11215.0
HalfSeconds              5431.0
Name: 6217, dtype: object
Stafford
 Age                          30
M/F                           M
City                   Stafford
State                        VA
Country                     USA
Half            0 days 01:27:18
40K             0 days 02:50:33
Pace                    0:06:56
TotalSeconds            10233.0
HalfSeconds              5238.0
Name: 875, dtype: object
Stafford Springs
 Age                           46
M/F                            M
City            Stafford Springs
State                         CT
Country                      USA
Half             0 days 01:37:09
40K              0 days 03:17:29
Pace                     0:08:00
TotalSeconds             11849.0
HalfSeconds               5829.0
Name: 12296, dtype: object
Stamford
 Age                          30
M/F                           M
City                   Stamford
State                        CT
Country                     USA
Half            0 days 01:22:40
40K             0 days 02:46:08
Pace                    0:06:45
TotalSeconds             9968.0
HalfSeconds              4960.0
Name: 2201, dtype: object
Stamullen
 Age                          42
M/F                           M
City                  Stamullen
State                       NaN
Country                     IRL
Half            0 days 01:34:01
40K             0 days 03:16:58
Pace                    0:07:58
TotalSeconds            11818.0
HalfSeconds              5641.0
Name: 6179, dtype: object
Stanford
 Age                          28
M/F                           M
City                   Stanford
State                        CA
Country                     USA
Half            0 days 01:22:03
40K             0 days 02:49:02
Pace                    0:06:50
TotalSeconds            10142.0
HalfSeconds              4923.0
Name: 1096, dtype: object
Stanley
 Age                          25
M/F                           M
City                    Stanley
State                        WI
Country                     USA
Half            0 days 01:21:06
40K             0 days 02:38:26
Pace                    0:06:23
TotalSeconds             9506.0
HalfSeconds              4866.0
Name: 974, dtype: object
Stansstad
 Age                          41
M/F                           M
City                  Stansstad
State                       NaN
Country                     SUI
Half            0 days 01:34:51
40K             0 days 03:06:57
Pace                    0:07:33
TotalSeconds            11217.0
HalfSeconds              5691.0
Name: 9587, dtype: object
Stanton
 Age                          62
M/F                           M
City                    Stanton
State                        CA
Country                     USA
Half            0 days 01:55:28
40K             0 days 04:20:16
Pace                    0:10:36
TotalSeconds            15616.0
HalfSeconds              6928.0
Name: 23202, dtype: object
Star City
 Age                          37
M/F                           F
City                  Star City
State                        WV
Country                     USA
Half            0 days 01:39:16
40K             0 days 03:07:31
Pace                    0:07:33
TotalSeconds            11251.0
HalfSeconds              5956.0
Name: 15196, dtype: object
Starkville
 Age                          43
M/F                           M
City                 Starkville
State                        MI
Country                     USA
Half            0 days 02:06:34
40K             0 days 04:13:42
Pace                    0:10:15
TotalSeconds            15222.0
HalfSeconds              7594.0
Name: 29394, dtype: object
State College
 Age                          22
M/F                           M
City              State College
State                        PA
Country                     USA
Half            0 days 01:22:46
40K             0 days 02:41:08
Pace                    0:06:30
TotalSeconds             9668.0
HalfSeconds              4966.0
Name: 1852, dtype: object
State Of Mexico , Mexico , Cp
 Age                                        43
M/F                                         F
City            State Of Mexico , Mexico , Cp
State                                     NaN
Country                                   MEX
Half                          0 days 01:41:41
40K                           0 days 03:27:25
Pace                                  0:08:25
TotalSeconds                          12445.0
HalfSeconds                            6101.0

Name: 16935, dtype: object
State Road
 Age                          50
M/F                           M
City                 State Road
State                        NC
Country                     USA
Half            0 days 01:35:55
40K             0 days 03:05:54
Pace                    0:07:30
TotalSeconds            11154.0
HalfSeconds              5755.0
Name: 10093, dtype: object
Staten Island
 Age                          33
M/F                           M
City              Staten Island
State                        NY
Country                     USA
Half            0 days 01:18:49
40K             0 days 02:33:23
Pace                    0:06:11
TotalSeconds             9203.0
HalfSeconds              4729.0
Name: 408, dtype: object
Statesville
 Age                          33
M/F                           M
City                Statesville
State                        NC
Country                     USA
Half            0 days 01:28:09
40K             0 days 02:54:49
Pace                    0:07:05
TotalSeconds            10489.0
HalfSeconds              5289.0
Name: 2742, dtype: object
Staunton
 Age                          29
M/F                           M
City                   Staunton
State                        VA
Country                     USA
Half            0 days 01:27:29
40K             0 days 02:49:11
Pace                    0:06:48
TotalSeconds            10151.0
HalfSeconds              5249.0
Name: 3117, dtype: object
Ste-Anne-De-Bellevue
 Age                               44
M/F                                M
City            Ste-Anne-De-Bellevue
State                             QC
Country                          CAN
Half                 0 days 01:28:42
40K                  0 days 02:53:37
Pace                         0:07:03
TotalSeconds                 10417.0
HalfSeconds                   5322.0
Name: 5261, dtype: object
Ste-Catherine De Hatley
 Age                                  48
M/F                                   F
City            Ste-Catherine De Hatley
State                                QC
Country                             CAN
Half                    0 days 01:53:43
40K                     0 days 03:56:08
Pace                            0:09:33
TotalSeconds                    14168.0
HalfSeconds                      6823.0
Name: 22829, dtype: object
Ste-Ceciledemilton
 Age                             60
M/F                              M
City            Ste-Ceciledemilton
State                           QC
Country                        CAN
Half               0 days 01:51:21
40K                0 days 03:41:55
Pace                       0:09:00
TotalSeconds               13315.0
HalfSeconds                 6681.0
Name: 16672, dtype: object
Ste-Germaine Boule
 Age                             61
M/F                              M
City            Ste-Germaine Boule
State                           QC
Country                        CAN
Half               0 days 01:43:19
40K                0 days 03:18:30
Pace                       0:08:03
TotalSeconds               11910.0
HalfSeconds                 6199.0
Name: 11957, dtype: object
Ste-Henedine
 Age                          61
M/F                           M
City               Ste-Henedine
State                        QC
Country                     CAN
Half            0 days 01:44:17
40K             0 days 03:26:43
Pace                    0:08:22
TotalSeconds            12403.0
HalfSeconds              6257.0
Name: 16683, dtype: object
Ste-Julie
 Age                          45
M/F                           F
City                  Ste-Julie
State                        QC
Country                     CAN
Half            0 days 01:58:18
40K             0 days 03:50:47
Pace                    0:09:18
TotalSeconds            13847.0
HalfSeconds              7098.0
Name: 24009, dtype: object
Ste-Therese
 Age                          53
M/F                           M
City                Ste-Therese
State                        QC
Country                     CAN
Half            0 days 01:41:06
40K             0 days 03:30:49
Pace                    0:08:29
TotalSeconds            12649.0
HalfSeconds              6066.0
Name: 12690, dtype: object
Steamboat
 Age                          24
M/F                           F
City                  Steamboat
State                        CO
Country                     USA
Half            0 days 01:34:50
40K             0 days 03:07:01
Pace                    0:07:33
TotalSeconds            11221.0
HalfSeconds              5690.0
Name: 6440, dtype: object
Steamboat Springs
 Age                            58
M/F                             F
City            Steamboat Springs
State                          CO
Country                       USA
Half              0 days 01:57:56
40K               0 days 03:44:04
Pace                      0:09:03
TotalSeconds              13444.0
HalfSeconds                7076.0
Name: 25185, dtype: object
Steele
 Age                          50
M/F                           F
City                     Steele
State                        ND
Country                     USA
Half            0 days 01:59:54
40K             0 days 04:02:30
Pace                    0:09:46
TotalSeconds            14550.0
HalfSeconds              7194.0
Name: 21882, dtype: object
Stellarton
 Age                          35
M/F                           M
City                 Stellarton
State                        NS
Country                     CAN
Half            0 days 01:36:32
40K             0 days 03:10:18
Pace                    0:07:43
TotalSeconds            11418.0
HalfSeconds              5792.0
Name: 5015, dtype: object
Stephens City
 Age                          40
M/F                           M
City              Stephens City
State                        VA
Country                     USA
Half            0 days 01:31:17
40K             0 days 03:00:17
Pace                    0:07:18
TotalSeconds            10817.0
HalfSeconds              5477.0
Name: 5461, dtype: object
Stephenville
 Age                          61
M/F                           M
City               Stephenville
State                        TX
Country                     USA
Half            0 days 02:14:24
40K             0 days 04:22:44
Pace                    0:10:32
TotalSeconds            15764.0
HalfSeconds              8064.0
Name: 21949, dtype: object
Stepney
 Age                          44
M/F                           F
City                    Stepney
State                       NaN
Country                     AUS
Half            0 days 01:42:56
40K             0 days 03:36:14
Pace                    0:08:46
TotalSeconds            12974.0
HalfSeconds              6176.0
Name: 19624, dtype: object
Stepney, South Australia
 Age                                   40
M/F                                    F
City            Stepney, South Australia
State                                NaN
Country                              AUS
Half                     0 days 01:53:58
40K                      0 days 03:46:34
Pace                             0:09:08
TotalSeconds                     13594.0
HalfSeconds                       6838.0
Name: 21092, dtype: object
Sterling
 Age                          45
M/F                           M
City                   Sterling
State                        VA
Country                     USA
Half            0 days 01:28:13
40K             0 days 03:03:19
Pace                    0:07:26
TotalSeconds            10999.0
HalfSeconds              5293.0
Name: 1166, dtype: object
Sterling Heights
 Age                           40
M/F                            F
City            Sterling Heights
State                         MI
Country                      USA
Half             0 days 01:51:21
40K              0 days 03:42:43
Pace                     0:09:00
TotalSeconds             13363.0
HalfSeconds               6681.0
Name: 16877, dtype: object
Sterling Hieghts
 Age                           61
M/F                            M
City            Sterling Hieghts
State                         MI
Country                      USA
Half             0 days 01:42:14
40K              0 days 03:16:17
Pace                     0:07:56
TotalSeconds             11777.0
HalfSeconds               6134.0
Name: 12530, dtype: object
Sterrett

 Age                          29
M/F                           M
City                   Sterrett
State                        AL
Country                     USA
Half            0 days 01:21:09
40K             0 days 02:44:24
Pace                    0:06:39
TotalSeconds             9864.0
HalfSeconds              4869.0
Name: 407, dtype: object
Stevens Point
 Age                          52
M/F                           M
City              Stevens Point
State                        WI
Country                     USA
Half            0 days 01:34:26
40K             0 days 03:10:02
Pace                    0:07:42
TotalSeconds            11402.0
HalfSeconds              5666.0
Name: 6876, dtype: object
Stevenson Ranch
 Age                          40
M/F                           M
City            Stevenson Ranch
State                        CA
Country                     USA
Half            0 days 01:39:33
40K             0 days 03:22:23
Pace                    0:08:13
TotalSeconds            12143.0
HalfSeconds              5973.0
Name: 8556, dtype: object
Stevensville
 Age                          54
M/F                           M
City               Stevensville
State                        MT
Country                     USA
Half            0 days 02:00:13
40K             0 days 04:04:03
Pace                    0:09:50
TotalSeconds            14643.0
HalfSeconds              7213.0
Name: 14180, dtype: object
Stewartsville
 Age                          46
M/F                           F
City              Stewartsville
State                        NJ
Country                     USA
Half            0 days 01:50:38
40K             0 days 03:39:48
Pace                    0:08:53
TotalSeconds            13188.0
HalfSeconds              6638.0
Name: 21471, dtype: object
Stewartville
 Age                          48
M/F                           F
City               Stewartville
State                        MN
Country                     USA
Half            0 days 02:05:12
40K             0 days 04:29:04
Pace                    0:11:03
TotalSeconds            16144.0
HalfSeconds              7512.0
Name: 22565, dtype: object
Stillwater
 Age                          25
M/F                           M
City                 Stillwater
State                        MN
Country                     USA
Half            0 days 01:31:15
40K             0 days 02:52:16
Pace                    0:06:57
TotalSeconds            10336.0
HalfSeconds              5475.0
Name: 3684, dtype: object
Stillwater Lake
 Age                          53
M/F                           M
City            Stillwater Lake
State                        NS
Country                     CAN
Half            0 days 01:40:06
40K             0 days 03:21:49
Pace                    0:08:10
TotalSeconds            12109.0
HalfSeconds              6006.0
Name: 14136, dtype: object
Stilwell
 Age                          50
M/F                           M
City                   Stilwell
State                        KS
Country                     USA
Half            0 days 02:46:24
40K             0 days 05:40:19
Pace                    0:13:44
TotalSeconds            20419.0
HalfSeconds              9984.0
Name: 27510, dtype: object
Stirling
 Age                          48
M/F                           M
City                   Stirling
State                       NaN
Country                     GBR
Half            0 days 01:29:42
40K             0 days 03:02:29
Pace                    0:07:24
TotalSeconds            10949.0
HalfSeconds              5382.0
Name: 7472, dtype: object
Stittsville
 Age                          41
M/F                           M
City                Stittsville
State                        ON
Country                     CAN
Half            0 days 01:33:22
40K             0 days 03:06:55
Pace                    0:07:32
TotalSeconds            11215.0
HalfSeconds              5602.0
Name: 2812, dtype: object
Stockholm
 Age                          40
M/F                           M
City                  Stockholm
State                       NaN
Country                     SWE
Half            0 days 01:27:20
40K             0 days 02:50:20
Pace                    0:06:54
TotalSeconds            10220.0
HalfSeconds              5240.0
Name: 8143, dtype: object
Stockport
 Age                          29
M/F                           M
City                  Stockport
State                       NaN
Country                     GBR
Half            0 days 01:24:26
40K             0 days 02:57:31
Pace                    0:07:15
TotalSeconds            10651.0
HalfSeconds              5066.0
Name: 2154, dtype: object
Stockton
 Age                          53
M/F                           M
City                   Stockton
State                        CA
Country                     USA
Half            0 days 01:42:56
40K             0 days 03:21:19
Pace                    0:08:07
TotalSeconds            12079.0
HalfSeconds              6176.0
Name: 11194, dtype: object
Stoke
 Age                          46
M/F                           M
City                      Stoke
State                        QC
Country                     CAN
Half            0 days 01:38:39
40K             0 days 03:10:28
Pace                    0:07:41
TotalSeconds            11428.0
HalfSeconds              5919.0
Name: 10447, dtype: object
Stoke On Trent
 Age                          55
M/F                           M
City             Stoke On Trent
State                       NaN
Country                     GBR
Half            0 days 01:47:11
40K             0 days 03:35:42
Pace                    0:08:46
TotalSeconds            12942.0
HalfSeconds              6431.0
Name: 18714, dtype: object
Stone
 Age                          44
M/F                           M
City                      Stone
State                       NaN
Country                     GBR
Half            0 days 01:26:43
40K             0 days 03:11:22
Pace                    0:07:52
TotalSeconds            11482.0
HalfSeconds              5203.0
Name: 2288, dtype: object
Stoneham
 Age                          43
M/F                           M
City                   Stoneham
State                        MA
Country                     USA
Half            0 days 01:38:36
40K             0 days 03:42:51
Pace                    0:09:04
TotalSeconds            13371.0
HalfSeconds              5916.0
Name: 7658, dtype: object
Stoneville
 Age                          38
M/F                           F
City                 Stoneville
State                       NaN
Country                     AUS
Half            0 days 01:36:30
40K             0 days 03:11:41
Pace                    0:07:44
TotalSeconds            11501.0
HalfSeconds              5790.0
Name: 9798, dtype: object
Stoney Creek
 Age                          62
M/F                           M
City               Stoney Creek
State                        ON
Country                     CAN
Half            0 days 01:51:32
40K             0 days 03:52:47
Pace                    0:09:21
TotalSeconds            13967.0
HalfSeconds              6692.0
Name: 11679, dtype: object
Stonington
 Age                          28
M/F                           F
City                 Stonington
State                        CT
Country                     USA
Half            0 days 01:47:16
40K             0 days 03:22:48
Pace                    0:08:08
TotalSeconds            12168.0
HalfSeconds              6436.0
Name: 15493, dtype: object
Stony Brook
 Age                          40
M/F                           M
City                Stony Brook
State                        NY
Country                     USA
Half            0 days 01:27:08
40K             0 days 02:49:36
Pace                    0:06:50
TotalSeconds            10176.0
HalfSeconds              5228.0
Name: 2517, dtype: object
Stony Plain
 Age                          61
M/F                           M
City                Stony Plain
State                        AB
Country                     CAN
Half            0 days 01:48:00
40K             0 days 04:08:03
Pace                    0:10:02
TotalSeconds            14883.0
HalfSeconds              6480.0
Name: 20735, dtype: object
Stony Point
 Age                          63
M/F                           M
City                Stony Point
State                        NY
Country                     USA
Half            0 days 01:51:40
40K             0 days 03:43:31
Pace                    0:09:03
TotalSeconds            13411.0
HalfSeconds              6700.0
Name: 21670, dtype: object
Storm Lake
 Age                          52
M/F                           M
City                 Storm Lake
State                        IA
Country                     USA
Half            0 days 01:42:18
40K             0 days 03:20:19
Pace                    0:08:05
TotalSeconds            12019.0
HalfSeconds              6138.0
Name: 13073, dtype: object
Stouffville
 Age                          52
M/F                           M
City                Stouffville
State                        ON
Country                     CAN
Half            0 days 01:39:28
40K             0 days 03:22:40
Pace                    0:08:20
TotalSeconds            12160.0
HalfSeconds              5968.0
Name: 9256, dtype: object
Stoughton
 Age                          28
M/F                           F
City                  Stoughton
State                        MA
Country                     USA
Half            0 days 01:38:15
40K             0 days 03:20:56
Pace                    0:08:08
TotalSeconds            12056.0
HalfSeconds              5895.0
Name: 3962, dtype: object
Stow
 Age                          30
M/F                           M
City                       Stow
State                        OH
Country                     USA
Half            0 days 01:26:30
40K             0 days 02:49:55
Pace                    0:06:52
TotalSeconds            10195.0
HalfSeconds              5190.0
Name: 226, dtype: object
Stowe
 Age                          40
M/F                           M
City                      Stowe
State                        PA
Country                     USA
Half            0 days 01:22:05
40K             0 days 02:45:22
Pace                    0:06:44
TotalSeconds             9922.0
HalfSeconds              4925.0
Name: 917, dtype: object
Strafford
 Age                          66
M/F                           M
City                  Strafford
State                        NH
Country                     USA
Half            0 days 01:52:49
40K             0 days 03:42:35
Pace                    0:09:00
TotalSeconds            13355.0
HalfSeconds              6769.0
Name: 22101, dtype: object
Strasbourg
 Age                          46
M/F                           M
City                 Strasbourg
State                       NaN
Country                     FRA
Half            0 days 01:25:36
40K             0 days 02:49:00
Pace                    0:06:51
TotalSeconds            10140.0
HalfSeconds              5136.0
Name: 1224, dtype: object
Strassen
 Age                          63
M/F                           M
City                   Strassen
State                       NaN
Country                     LUX
Half            0 days 02:00:28
40K             0 days 04:02:01
Pace                    0:09:52
TotalSeconds            14521.0
HalfSeconds              7228.0
Name: 23448, dtype: object
Stratford
 Age                          33
M/F                           F
City                  Stratford
State                        PE
Country                     CAN
Half            0 days 01:44:28
40K             0 days 03:23:58
Pace                    0:08:13
TotalSeconds            12238.0
HalfSeconds              6268.0
Name: 16370, dtype: object
Stratham
 Age                          31
M/F                           F
City                   Stratham
State                        NH
Country                     USA
Half            0 days 01:30:08
40K             0 days 02:54:23
Pace                    0:07:02
TotalSeconds            10463.0
HalfSeconds              5408.0
Name: 6569, dtype: object
Strathmore
 Age                          44
M/F                           M
City                 Strathmore
State                        AB
Country                     CAN
Half            0 days 01:33:50
40K             0 days 03:05:48
Pace                    0:07:33
TotalSeconds            11148.0
HalfSeconds              5630.0
Name: 5284, dtype: object
Streamwood
 Age                          43
M/F                           M
City                 Streamwood
State                        IL
Country                     USA
Half            0 days 01:30:59
40K             0 days 03:06:04
Pace                    0:07:36
TotalSeconds            11164.0
HalfSeconds              5459.0
Name: 5746, dtype: object
Streetsboro
 Age                          35
M/F                           F
City                Streetsboro
State                        OH
Country                     USA
Half            0 days 01:50:44
40K             0 days 03:43:08
Pace                    0:09:01
TotalSeconds            13388.0
HalfSeconds              6644.0
Name: 17431, dtype: object
Strongsville
 Age                          45
M/F                           M
City               Strongsville
State                        OH
Country                     USA
Half            0 days 01:25:32
40K             0 days 02:44:08
Pace                    0:06:37
TotalSeconds             9848.0
HalfSeconds              5132.0
Name: 956, dtype: object
Stroudsburg
 Age                          55
M/F                           F
City                Stroudsburg
State                        PA
Country                     USA
Half            0 days 02:05:04
40K             0 days 04:06:21
Pace                    0:09:56
TotalSeconds            14781.0
HalfSeconds              7504.0
Name: 25526, dtype: object
Stthomas
 Age                          55
M/F                           F
City                   Stthomas
State                        ON
Country                     CAN
Half            0 days 02:07:09
40K             0 days 04:10:37
Pace                    0:10:04
TotalSeconds            15037.0
HalfSeconds              7629.0
Name: 25282, dtype: object
Stuart
 Age                          50
M/F                           F
City                     Stuart
State                        FL
Country                     USA
Half            0 days 01:47:59
40K             0 days 03:34:26
Pace                    0:08:40
TotalSeconds            12866.0
HalfSeconds              6479.0
Name: 22800, dtype: object
Stupava
 Age                          41
M/F                           M
City                    Stupava
State                       NaN
Country                     SVK
Half            0 days 01:31:04
40K             0 days 03:21:45
Pace                    0:08:13
TotalSeconds            12105.0
HalfSeconds              5464.0
Name: 6511, dtype: object
Sturbridge
 Age                          38
M/F                           F
City                 Sturbridge
State                        MA
Country                     USA
Half            0 days 02:02:44
40K             0 days 03:48:06
Pace                    0:09:08
TotalSeconds            13686.0
HalfSeconds              7364.0
Name: 31138, dtype: object

Sturgeon Bay
 Age                          54
M/F                           F
City               Sturgeon Bay
State                        WI
Country                     USA
Half            0 days 02:04:34
40K             0 days 04:06:42
Pace                    0:09:59
TotalSeconds            14802.0
HalfSeconds              7474.0
Name: 24918, dtype: object
Sturgeon County
 Age                          52
M/F                           F
City            Sturgeon County
State                        AB
Country                     CAN
Half            0 days 02:07:25
40K             0 days 04:28:34
Pace                    0:10:53
TotalSeconds            16114.0
HalfSeconds              7645.0
Name: 24674, dtype: object
Sturgis
 Age                          64
M/F                           F
City                    Sturgis
State                        MI
Country                     USA
Half            0 days 02:39:13
40K             0 days 05:24:14
Pace                    0:13:03
TotalSeconds            19454.0
HalfSeconds              9553.0
Name: 25987, dtype: object
Stuttgart
 Age                          41
M/F                           M
City                  Stuttgart
State                       NaN
Country                     GER
Half            0 days 01:22:59
40K             0 days 02:44:07
Pace                    0:06:39
TotalSeconds             9847.0
HalfSeconds              4979.0
Name: 1703, dtype: object
Subang Jaya
 Age                          36
M/F                           M
City                Subang Jaya
State                       NaN
Country                     MAS
Half            0 days 02:35:37
40K             0 days 05:25:08
Pace                    0:13:12
TotalSeconds            19508.0
HalfSeconds              9337.0
Name: 28636, dtype: object
Subiaco
 Age                          28
M/F                           M
City                    Subiaco
State                       NaN
Country                     AUS
Half            0 days 01:29:15
40K             0 days 03:05:16
Pace                    0:07:37
TotalSeconds            11116.0
HalfSeconds              5355.0
Name: 3495, dtype: object
Succasunna
 Age                          37
M/F                           M
City                 Succasunna
State                        NJ
Country                     USA
Half            0 days 01:25:16
40K             0 days 02:45:10
Pace                    0:06:39
TotalSeconds             9910.0
HalfSeconds              5116.0
Name: 1003, dtype: object
Sudbury
 Age                          32
M/F                           M
City                    Sudbury
State                        MA
Country                     USA
Half            0 days 01:31:35
40K             0 days 02:52:41
Pace                    0:06:57
TotalSeconds            10361.0
HalfSeconds              5495.0
Name: 4426, dtype: object
Suffield
 Age                          35
M/F                           M
City                   Suffield
State                        CT
Country                     USA
Half            0 days 01:26:35
40K             0 days 02:51:04
Pace                    0:06:53
TotalSeconds            10264.0
HalfSeconds              5195.0
Name: 2057, dtype: object
Suffolk
 Age                          49
M/F                           M
City                    Suffolk
State                       NaN
Country                     GBR
Half            0 days 01:19:21
40K             0 days 02:36:16
Pace                    0:06:19
TotalSeconds             9376.0
HalfSeconds              4761.0
Name: 674, dtype: object
Sugar Grove
 Age                          51
M/F                           F
City                Sugar Grove
State                        IL
Country                     USA
Half            0 days 02:00:55
40K             0 days 04:09:02
Pace                    0:10:06
TotalSeconds            14942.0
HalfSeconds              7255.0
Name: 24969, dtype: object
Sugar Land
 Age                          36
M/F                           M
City                 Sugar Land
State                        TX
Country                     USA
Half            0 days 01:30:15
40K             0 days 02:56:43
Pace                    0:07:07
TotalSeconds            10603.0
HalfSeconds              5415.0
Name: 2018, dtype: object
Sugar Run
 Age                          50
M/F                           M
City                  Sugar Run
State                        PA
Country                     USA
Half            0 days 01:43:07
40K             0 days 03:17:59
Pace                    0:07:59
TotalSeconds            11879.0
HalfSeconds              6187.0
Name: 14154, dtype: object
Sugarcreek
 Age                          40
M/F                           M
City                 Sugarcreek
State                        OH
Country                     USA
Half            0 days 01:28:18
40K             0 days 02:51:34
Pace                    0:06:59
TotalSeconds            10294.0
HalfSeconds              5298.0
Name: 4073, dtype: object
Sugarland
 Age                          54
M/F                           F
City                  Sugarland
State                        TX
Country                     USA
Half            0 days 02:05:26
40K             0 days 04:31:49
Pace                    0:10:58
TotalSeconds            16309.0
HalfSeconds              7526.0
Name: 26581, dtype: object
Sullivan'S Island
 Age                            33
M/F                             F
City            Sullivan'S Island
State                          SC
Country                       USA
Half              0 days 01:44:18
40K               0 days 03:19:46
Pace                      0:08:02
TotalSeconds              11986.0
HalfSeconds                6258.0
Name: 18001, dtype: object
Sullivans Island
 Age                           61
M/F                            M
City            Sullivans Island
State                         SC
Country                      USA
Half             0 days 01:55:04
40K              0 days 04:03:48
Pace                     0:09:54
TotalSeconds             14628.0
HalfSeconds               6904.0
Name: 22787, dtype: object
Sulzbach
 Age                          44
M/F                           M
City                   Sulzbach
State                       NaN
Country                     GER
Half            0 days 02:00:15
40K             0 days 03:56:00
Pace                    0:09:31
TotalSeconds            14160.0
HalfSeconds              7215.0
Name: 31864, dtype: object
Summerside
 Age                          53
M/F                           M
City                 Summerside
State                        PE
Country                     CAN
Half            0 days 01:39:27
40K             0 days 03:29:02
Pace                    0:08:26
TotalSeconds            12542.0
HalfSeconds              5967.0
Name: 11642, dtype: object
Summerville
 Age                          35
M/F                           F
City                Summerville
State                        SC
Country                     USA
Half            0 days 01:52:26
40K             0 days 03:57:52
Pace                    0:09:35
TotalSeconds            14272.0
HalfSeconds              6746.0
Name: 18394, dtype: object
Summit
 Age                          30
M/F                           M
City                     Summit
State                        NJ
Country                     USA
Half            0 days 01:22:21
40K             0 days 02:41:25
Pace                    0:06:31
TotalSeconds             9685.0
HalfSeconds              4941.0
Name: 1964, dtype: object
Sumter
 Age                          49
M/F                           M
City                     Sumter
State                        SC
Country                     USA
Half            0 days 01:59:36
40K             0 days 03:49:33
Pace                    0:09:13
TotalSeconds            13773.0
HalfSeconds              7176.0
Name: 10670, dtype: object
Sun Prairie
 Age                          47
M/F                           M
City                Sun Prairie
State                        WI
Country                     USA
Half            0 days 01:41:15
40K             0 days 03:22:57
Pace                    0:08:15
TotalSeconds            12177.0
HalfSeconds              6075.0
Name: 11392, dtype: object
Sun Valley
 Age                          45
M/F                           M
City                 Sun Valley
State                        CA
Country                     USA
Half            0 days 01:38:45
40K             0 days 03:20:31
Pace                    0:08:09
TotalSeconds            12031.0
HalfSeconds              5925.0
Name: 6971, dtype: object
Sunbury
 Age                          30
M/F                           F
City                    Sunbury
State                        PA
Country                     USA
Half            0 days 01:40:14
40K             0 days 03:08:08
Pace                    0:07:33
TotalSeconds            11288.0
HalfSeconds              6014.0
Name: 11867, dtype: object
Sundbyberg
 Age                          35
M/F                           M
City                 Sundbyberg
State                       NaN
Country                     SWE
Half            0 days 02:05:39
40K             0 days 04:09:25
Pace                    0:10:02
TotalSeconds            14965.0
HalfSeconds              7539.0
Name: 31502, dtype: object
Sunderland
 Age                          53
M/F                           M
City                 Sunderland
State                       NaN
Country                     GBR
Half            0 days 01:35:09
40K             0 days 03:20:13
Pace                    0:08:11
TotalSeconds            12013.0
HalfSeconds              5709.0
Name: 15015, dtype: object
Sundsvall
 Age                          46
M/F                           M
City                  Sundsvall
State                       NaN
Country                     SWE
Half            0 days 01:48:32
40K             0 days 03:40:07
Pace                    0:08:52
TotalSeconds            13207.0
HalfSeconds              6512.0
Name: 12615, dtype: object
Sunland
 Age                          25
M/F                           F
City                    Sunland
State                        CA
Country                     USA
Half            0 days 02:02:05
40K             0 days 03:48:03
Pace                    0:09:07
TotalSeconds            13683.0
HalfSeconds              7325.0
Name: 15068, dtype: object
Sunny Isles Brach
 Age                            39
M/F                             F
City            Sunny Isles Brach
State                          FL
Country                       USA
Half              0 days 02:05:05
40K               0 days 04:34:43
Pace                      0:10:59
TotalSeconds              16483.0
HalfSeconds                7505.0
Name: 19627, dtype: object
Sunnyside
 Age                          47
M/F                           F
City                  Sunnyside
State                        NY
Country                     USA
Half            0 days 01:45:26
40K             0 days 03:26:15
Pace                    0:08:17
TotalSeconds            12375.0
HalfSeconds              6326.0
Name: 11967, dtype: object
Sunnyvale
 Age                          26
M/F                           M
City                  Sunnyvale
State                        CA
Country                     USA
Half            0 days 01:21:53
40K             0 days 02:40:56
Pace                    0:06:29
TotalSeconds             9656.0
HalfSeconds              4913.0
Name: 1244, dtype: object
Sunrise
 Age                          42
M/F                           F
City                    Sunrise
State                        FL
Country                     USA
Half            0 days 01:45:24
40K             0 days 03:22:38
Pace                    0:08:09
TotalSeconds            12158.0
HalfSeconds              6324.0
Name: 20610, dtype: object
Superior
 Age                          26
M/F                           F
City                   Superior
State                        CO
Country                     USA
Half            0 days 01:17:01
40K             0 days 02:27:15
Pace                    0:05:55
TotalSeconds             8835.0
HalfSeconds              4621.0
Name: F18, dtype: object
Superior Township
 Age                            50
M/F                             M
City            Superior Township
State                          MI
Country                       USA
Half              0 days 01:39:05
40K               0 days 03:26:43
Pace                      0:08:25
TotalSeconds              12403.0
HalfSeconds                5945.0
Name: 12306, dtype: object
Suquamish
 Age                          40
M/F                           F
City                  Suquamish
State                        WA
Country                     USA
Half            0 days 02:08:53
40K             0 days 04:44:25
Pace                    0:11:31
TotalSeconds            17065.0
HalfSeconds              7733.0
Name: 29397, dtype: object
Surf City
 Age                          45
M/F                           F
City                  Surf City
State                        NC
Country                     USA
Half            0 days 02:40:46
40K             0 days 05:27:10
Pace                    0:13:09
TotalSeconds            19630.0
HalfSeconds              9646.0
Name: 26989, dtype: object
Surfside
 Age                          45
M/F                           M
City                   Surfside
State                        SC
Country                     USA
Half            0 days 01:37:58
40K             0 days 03:23:07
Pace                    0:08:15
TotalSeconds            12187.0
HalfSeconds              5878.0
Name: 9614, dtype: object
Surprise
 Age                          40
M/F                           M
City                   Surprise
State                        AZ
Country                     USA
Half            0 days 01:33:24
40K             0 days 03:07:17
Pace                    0:07:36
TotalSeconds            11237.0
HalfSeconds              5604.0
Name: 7058, dtype: object
Surrey
 Age                          58
M/F                           M
City                     Surrey
State                       NaN
Country                     GBR
Half            0 days 01:27:20
40K             0 days 02:58:43
Pace                    0:07:23
TotalSeconds            10723.0
HalfSeconds              5240.0
Name: 2515, dtype: object
Sussex
 Age                          46
M/F                           M
City                     Sussex
State                        NJ
Country                     USA
Half            0 days 01:39:01
40K             0 days 03:20:09
Pace                    0:08:16
TotalSeconds            12009.0
HalfSeconds              5941.0
Name: 10005, dtype: object
Sutton
 Age                          36
M/F                           F
City                     Sutton
State                        MA
Country                     USA
Half            0 days 01:48:03
40K             0 days 03:32:04
Pace                    0:08:34
TotalSeconds            12724.0
HalfSeconds              6483.0
Name: 19631, dtype: object
Sutton Courtenay
 Age                           39
M/F                            M
City            Sutton Courtenay
State                        NaN
Country                      GBR
Half             0 days 01:26:34
40K              0 days 02:49:39
Pace                     0:06:51
TotalSeconds             10179.0
HalfSeconds               5194.0
Name: 2344, dtype: object
Suttons Bay
 Age                          53
M/F                           M
City                Suttons Bay
State                        MI
Country                     USA
Half            0 days 01:43:09
40K             0 days 03:39:49
Pace                    0:08:55
TotalSeconds            13189.0
HalfSeconds              6189.0
Name: 9927, dtype: object
Suwanee
 Age                          47
M/F                           M
City                    Suwanee
State                        GA
Country                     USA
Half            0 days 01:39:55
40K             0 days 03:09:56
Pace                    0:07:38
TotalSeconds            11396.0
HalfSeconds              5995.0
Name: 8374, dtype: object
Suzhou
 Age                          43
M/F                           M
City                     Suzhou
State                       NaN
Country                     CHN
Half            0 days 01:34:42
40K             0 days 03:23:07
Pace                    0:08:13
TotalSeconds            12187.0
HalfSeconds              5682.0
Name: 5374, dtype: object
Suzhou, Jiangsu
 Age                          38
M/F                           M
City            Suzhou, Jiangsu
State                       NaN
Country                     CHN
Half            0 days 02:13:43
40K             0 days 04:27:52
Pace                    0:10:51
TotalSeconds            16072.0
HalfSeconds              8023.0
Name: 28305, dtype: object
Swampscott
 Age                          22
M/F                           M
City                 Swampscott
State                        MA
Country                     USA
Half            0 days 01:27:40
40K             0 days 03:14:59
Pace                    0:07:54
TotalSeconds            11699.0
HalfSeconds              5260.0
Name: 4099, dtype: object
Swannanoa
 Age                          23
M/F                           M
City                  Swannanoa
State                        NC
Country                     USA
Half            0 days 01:32:46
40K             0 days 03:16:32
Pace                    0:08:00
TotalSeconds            11792.0
HalfSeconds              5566.0
Name: 5236, dtype: object
Swansea
 Age                          48
M/F                           F
City                    Swansea
State                       NaN
Country                     GBR
Half            0 days 02:00:52
40K             0 days 03:51:50
Pace                    0:09:19
TotalSeconds            13910.0
HalfSeconds              7252.0
Name: 24027, dtype: object
Swarthmore
 Age                          35
M/F                           M
City                 Swarthmore
State                        PA
Country                     USA
Half            0 days 01:27:38
40K             0 days 02:56:46
Pace                    0:07:09
TotalSeconds            10606.0
HalfSeconds              5258.0
Name: 6886, dtype: object
Swartz Creek
 Age                          52
M/F                           M
City               Swartz Creek
State                        MI
Country                     USA
Half            0 days 01:31:41
40K             0 days 02:59:18
Pace                    0:07:12
TotalSeconds            10758.0
HalfSeconds              5501.0
Name: 2868, dtype: object
Swedesboro
 Age                          38
M/F                           F
City                 Swedesboro
State                        NJ
Country                     USA
Half            0 days 01:41:01
40K             0 days 03:19:58
Pace                    0:08:04
TotalSeconds            11998.0
HalfSeconds              6061.0
Name: 14301, dtype: object
Syacuse
 Age                          27
M/F                           F
City                    Syacuse
State                        NY
Country                     USA
Half            0 days 01:43:11
40K             0 days 03:39:22
Pace                    0:08:53
TotalSeconds            13162.0
HalfSeconds              6191.0
Name: 13771, dtype: object
Sycamore
 Age                          40
M/F                           M
City                   Sycamore
State                        IL
Country                     USA
Half            0 days 01:32:09
40K             0 days 03:04:33
Pace                    0:07:28
TotalSeconds            11073.0
HalfSeconds              5529.0
Name: 4324, dtype: object
Sydney
 Age                          35
M/F                           M
City                     Sydney
State                       NaN
Country                     AUS
Half            0 days 01:26:04

São Paulo
 Age                          45
M/F                           M
City                  São Paulo
State                       NaN
Country                     BRA
Half            0 days 01:30:44
40K             0 days 03:00:52
Pace                    0:07:18
TotalSeconds            10852.0
HalfSeconds              5444.0
Name: 3857, dtype: object
Tabernacle
 Age                          45
M/F                           F
City                 Tabernacle
State                        NJ
Country                     USA
Half            0 days 01:53:32
40K             0 days 03:45:58
Pace                    0:09:08
TotalSeconds            13558.0
HalfSeconds              6812.0
Name: 22251, dtype: object
Taby
 Age                          48
M/F                           M
City                       Taby
State                       NaN
Country                     SWE
Half            0 days 01:51:40
40K             0 days 03:48:16
Pace                    0:09:14
TotalSeconds            13696.0
HalfSeconds              6700.0
Name: 9291, dtype: object
Tacoma
 Age                          47
M/F                           M
City                     Tacoma
State                        WA
Country                     USA
Half            0 days 01:35:05
40K             0 days 03:01:45
Pace                    0:07:19
TotalSeconds            10905.0
HalfSeconds              5705.0
Name: 5790, dtype: object
Tacoma Park
 Age                          26
M/F                           M
City                Tacoma Park
State                        MD
Country                     USA
Half            0 days 01:22:46
40K             0 days 02:39:18
Pace                    0:06:25
TotalSeconds             9558.0
HalfSeconds              4966.0
Name: 688, dtype: object
Taguatinga
 Age                          41
M/F                           M
City                 Taguatinga
State                       NaN
Country                     BRA
Half            0 days 01:37:51
40K             0 days 03:13:51
Pace                    0:07:48
TotalSeconds            11631.0
HalfSeconds              5871.0
Name: 7629, dtype: object
Taichung
 Age                          40
M/F                           M
City                   Taichung
State                       NaN
Country                     TWN
Half            0 days 01:29:48
40K             0 days 02:57:56
Pace                    0:07:14
TotalSeconds            10676.0
HalfSeconds              5388.0
Name: 7232, dtype: object
Taipei
 Age                          40
M/F                           M
City                     Taipei
State                       NaN
Country                     TWN
Half            0 days 01:25:11
40K             0 days 02:48:00
Pace                    0:06:47
TotalSeconds            10080.0
HalfSeconds              5111.0
Name: 4551, dtype: object
Taipei City
 Age                          56
M/F                           M
City                Taipei City
State                       NaN
Country                     TWN
Half            0 days 01:40:35
40K             0 days 03:18:15
Pace                    0:08:00
TotalSeconds            11895.0
HalfSeconds              6035.0
Name: 11506, dtype: object
Taipei New Taipei City
 Age                                 36
M/F                                  M
City            Taipei New Taipei City
State                              NaN
Country                            TWN
Half                   0 days 01:26:56
40K                    0 days 03:00:56
Pace                           0:07:20
TotalSeconds                   10856.0
HalfSeconds                     5216.0
Name: 2909, dtype: object
Taito-Ku
 Age                          27
M/F                           M
City                   Taito-Ku
State                       NaN
Country                     JPN
Half            0 days 01:25:52
40K             0 days 02:54:40
Pace                    0:07:03
TotalSeconds            10480.0
HalfSeconds              5152.0
Name: 1981, dtype: object
Taiyuan City,shanxi Province
 Age                                       56
M/F                                        M
City            Taiyuan City,shanxi Province
State                                    NaN
Country                                  CHN
Half                         0 days 01:57:23
40K                          0 days 04:03:40
Pace                                 0:09:48
TotalSeconds                         14620.0
HalfSeconds                           7043.0
Name: 18180, dtype: object
Takoma Park
 Age                          38
M/F                           M
City                Takoma Park
State                        MD
Country                     USA
Half            0 days 01:19:25
40K             0 days 02:33:17
Pace                    0:06:12
TotalSeconds             9197.0
HalfSeconds              4765.0
Name: 450, dtype: object
Tallahassee
 Age                          24
M/F                           M
City                Tallahassee
State                        FL
Country                     USA
Half            0 days 01:18:15
40K             0 days 02:37:27
Pace                    0:06:21
TotalSeconds             9447.0
HalfSeconds              4695.0
Name: 512, dtype: object
Tallinn
 Age                          46
M/F                           M
City                    Tallinn
State                       NaN
Country                     EST
Half            0 days 01:46:24
40K             0 days 03:37:39
Pace                    0:08:46
TotalSeconds            13059.0
HalfSeconds              6384.0
Name: 7384, dtype: object
Tallmadge
 Age                          54
M/F                           M
City                  Tallmadge
State                        OH
Country                     USA
Half            0 days 01:32:55
40K             0 days 02:59:32
Pace                    0:07:14
TotalSeconds            10772.0
HalfSeconds              5575.0
Name: 5271, dtype: object
Tama, Tokyo
 Age                          44
M/F                           M
City                Tama, Tokyo
State                       NaN
Country                     JPN
Half            0 days 01:21:36
40K             0 days 02:50:20
Pace                    0:06:57
TotalSeconds            10220.0
HalfSeconds              4896.0
Name: 1848, dtype: object
Tampa
 Age                          46
M/F                           M
City                      Tampa
State                        FL
Country                     USA
Half            0 days 01:22:11
40K             0 days 02:43:42
Pace                    0:06:39
TotalSeconds             9822.0
HalfSeconds              4931.0
Name: 720, dtype: object
Tampere
 Age                          50
M/F                           M
City                    Tampere
State                       NaN
Country                     FIN
Half            0 days 01:35:54
40K             0 days 03:11:11
Pace                    0:07:44
TotalSeconds            11471.0
HalfSeconds              5754.0
Name: 5607, dtype: object
Tamuning
 Age                          39
M/F                           M
City                   Tamuning
State                        GU
Country                     USA
Half            0 days 01:29:57
40K             0 days 03:01:23
Pace                    0:07:21
TotalSeconds            10883.0
HalfSeconds              5397.0
Name: 6197, dtype: object
Taneytown
 Age                          26
M/F                           M
City                  Taneytown
State                        MD
Country                     USA
Half            0 days 01:21:20
40K             0 days 03:36:08
Pace                    0:08:38
TotalSeconds            12968.0
HalfSeconds              4880.0
Name: 1261, dtype: object
Tangent
 Age                          61
M/F                           M
City                    Tangent
State                        OR
Country                     USA
Half            0 days 01:58:41
40K             0 days 03:53:38
Pace                    0:09:26
TotalSeconds            14018.0
HalfSeconds              7121.0
Name: 20790, dtype: object
Taranto
 Age                          57
M/F                           M
City                    Taranto
State                       NaN
Country                     ITA
Half            0 days 01:46:45
40K             0 days 03:34:55
Pace                    0:08:41
TotalSeconds            12895.0
HalfSeconds              6405.0
Name: 31519, dtype: object
Tarboro
 Age                          52
M/F                           F
City                    Tarboro
State                        NC
Country                     USA
Half            0 days 02:02:03
40K             0 days 04:09:45
Pace                    0:10:04
TotalSeconds            14985.0
HalfSeconds              7323.0
Name: 22936, dtype: object
Taringa
 Age                          65
M/F                           M
City                    Taringa
State                       NaN
Country                     AUS
Half            0 days 02:04:10
40K             0 days 04:07:18
Pace                    0:10:02
TotalSeconds            14838.0
HalfSeconds              7450.0
Name: 23438, dtype: object
Tarnow
 Age                          72
M/F                           F
City                     Tarnow
State                       NaN
Country                     POL
Half            0 days 02:05:58
40K             0 days 04:17:42
Pace                    0:10:24
TotalSeconds            15462.0
HalfSeconds              7558.0
Name: 26028, dtype: object
Tarnowo
 Age                          40
M/F                           M
City                    Tarnowo
State                       NaN
Country                     POL
Half            0 days 01:28:15
40K             0 days 03:09:15
Pace                    0:07:40
TotalSeconds            11355.0
HalfSeconds              5295.0
Name: 4296, dtype: object
Tarpon Springs
 Age                          58
M/F                           F
City             Tarpon Springs
State                        FL
Country                     USA
Half            0 days 02:13:01
40K             0 days 04:36:54
Pace                    0:11:09
TotalSeconds            16614.0
HalfSeconds              7981.0
Name: 25584, dtype: object
Tarrytown
 Age                          40
M/F                           F
City                  Tarrytown
State                        NY
Country                     USA
Half            0 days 01:50:33
40K             0 days 03:38:39
Pace                    0:08:51
TotalSeconds            13119.0
HalfSeconds              6633.0
Name: 20975, dtype: object
Tasmania
 Age                          44
M/F                           M
City                   Tasmania
State                       NaN
Country                     AUS
Half            0 days 01:30:55
40K             0 days 03:00:37
Pace                    0:07:18
TotalSeconds            10837.0
HalfSeconds              5455.0
Name: 4105, dtype: object
Taunton
 Age                          30
M/F                           M
City                    Taunton
State                        MA
Country                     USA
Half            0 days 01:17:48
40K             0 days 02:35:01
Pace                    0:06:16
TotalSeconds             9301.0
HalfSeconds              4668.0
Name: 320, dtype: object
Tauranga
 Age                          47
M/F                           F
City                   Tauranga
State                       NaN
Country                     NZL
Half            0 days 01:43:43
40K             0 days 03:16:01
Pace                    0:07:53
TotalSeconds            11761.0
HalfSeconds              6223.0
Name: 19223, dtype: object
Tavernier
 Age                          28
M/F                           F
City                  Tavernier
State                        FL
Country                     USA
Half            0 days 02:16:46
40K             0 days 04:37:42
Pace                    0:11:11
TotalSeconds            16662.0
HalfSeconds              8206.0
Name: 30144, dtype: object
Tavistock
 Age                          30
M/F                           M
City                  Tavistock
State                       NaN
Country                     GBR
Half            0 days 01:28:03
40K             0 days 02:59:56
Pace                    0:07:20
TotalSeconds            10796.0
HalfSeconds              5283.0
Name: 2721, dtype: object
Taylor
 Age                          51
M/F                           M
City                     Taylor
State                        UT
Country                     USA
Half            0 days 01:39:27
40K             0 days 03:21:42
Pace                    0:08:13
TotalSeconds            12102.0
HalfSeconds              5967.0
Name: 11675, dtype: object
Taylorsville
 Age                          46
M/F                           M
City               Taylorsville
State                        GA
Country                     USA
Half            0 days 01:30:34
40K             0 days 02:56:16
Pace                    0:07:07
TotalSeconds            10576.0
HalfSeconds              5434.0
Name: 7481, dtype: object
Taylorville
 Age                          32
M/F                           M
City                Taylorville
State                        IL
Country                     USA
Half            0 days 01:22:23
40K             0 days 02:43:16
Pace                    0:06:36
TotalSeconds             9796.0
HalfSeconds              4943.0
Name: 2341, dtype: object
Tazewell
 Age                          55
M/F                           F
City                   Tazewell
State                        VA
Country                     USA
Half            0 days 01:55:28
40K             0 days 03:47:31
Pace                    0:09:11
TotalSeconds            13651.0
HalfSeconds              6928.0
Name: 25060, dtype: object
Teaneck
 Age                          50
M/F                           M
City                    Teaneck
State                        NJ
Country                     USA
Half            0 days 01:28:27
40K             0 days 02:53:38
Pace                    0:07:01
TotalSeconds            10418.0
HalfSeconds              5307.0
Name: 9599, dtype: object
Teaticket
 Age                          29
M/F                           M
City                  Teaticket
State                        MA
Country                     USA
Half            0 days 01:25:50
40K             0 days 03:00:51
Pace                    0:07:21
TotalSeconds            10851.0
HalfSeconds              5150.0
Name: 1807, dtype: object
Tecumseh
 Age                          48
M/F                           M
City                   Tecumseh
State                        ON
Country                     CAN
Half            0 days 01:31:14
40K             0 days 03:21:12
Pace                    0:08:12
TotalSeconds            12072.0
HalfSeconds              5474.0
Name: 4631, dtype: object
Teddington
 Age                          44
M/F                           M
City                 Teddington
State                       NaN
Country                     GBR
Half            0 days 01:30:51
40K             0 days 02:58:45
Pace                    0:07:13
TotalSeconds            10725.0
HalfSeconds              5451.0
Name: 6151, dtype: object
Tega Cay
 Age                          46
M/F                           M
City                   Tega Cay
State                        SC
Country                     USA
Half            0 days 01:32:33
40K             0 days 03:24:29
Pace                    0:08:30
TotalSeconds            12269.0
HalfSeconds              5553.0
Name: 8626, dtype: object
Tegucigalpa
 Age                          43
M/F                           M
City                Tegucigalpa
State                       NaN
Country                     HON
Half            0 days 01:28:19
40K             0 days 02:50:11
Pace                    0:06:51
TotalSeconds            10211.0
HalfSeconds              5299.0
Name: 4819, dtype: object
Tehuacan
 Age                          29
M/F                           F
City                   Tehuacan
State                       NaN
Country                     MEX
Half            0 days 01:51:01
40K             0 days 03:40:27
Pace                    0:08:52
TotalSeconds            13227.0
HalfSeconds              6661.0
Name: 17294, dtype: object
Tel - Aviv
 Age                          51
M/F                           M
City                 Tel - Aviv
State                       NaN
Country                     ISR
Half            0 days 01:41:20
40K             0 days 03:27:51
Pace                    0:08:29
TotalSeconds            12471.0
HalfSeconds              6080.0
Name: 14411, dtype: object
Tel Aviv
 Age                          37
M/F                           F
City                   Tel Aviv
State                       NaN
Country                     ISR
Half            0 days 01:39:51
40K             0 days 03:12:59
Pace                    0:07:47
TotalSeconds            11579.0
HalfSeconds              5991.0
Name: 13478, dtype: object
Telford
 Age                          48
M/F                           M
City                    Telford
State                        PA
Country                     USA
Half            0 days 01:46:38
40K             0 days 03:45:46
Pace                    0:09:06
TotalSeconds            13546.0
HalfSeconds              6398.0
Name: 10982, dtype: object
Telluride
 Age                          28
M/F                           F
City                  Telluride
State                        CO
Country                     USA
Half            0 days 02:01:03
40K             0 days 04:04:58
Pace                    0:09:48
TotalSeconds            14698.0
HalfSeconds              7263.0
Name: 13429, dtype: object
Temecula
 Age                          44
M/F                           M
City                   Temecula
State                        CA
Country                     USA
Half            0 days 01:31:21
40K             0 days 02:58:10
Pace                    0:07:12
TotalSeconds            10690.0
HalfSeconds              5481.0
Name: 6705, dtype: object
Tempe
 Age                          28
M/F                           M
City                      Tempe
State                        AZ
Country                     USA
Half            0 days 01:26:25
40K             0 days 02:54:42
Pace                    0:07:03
TotalSeconds            10482.0
HalfSeconds              5185.0
Name: 4272, dtype: object
Temple
 Age                          25
M/F                           F
City                     Temple
State                        TX
Country                     USA
Half            0 days 01:36:54
40K             0 days 02:58:39
Pace                    0:07:11
TotalSeconds            10719.0
HalfSeconds              5814.0
Name: 14492, dtype: object
Temple City
 Age                          38
M/F                           M
City                Temple City
State                        CA
Country                     USA
Half            0 days 01:27:43
40K             0 days 02:55:54
Pace                    0:07:06
TotalSeconds            10554.0
HalfSeconds              5263.0
Name: 2550, dtype: object
Templeton
 Age                          43
M/F                           M
City                  Templeton
State                        MA
Country                     USA
Half            0 days 01:25:11
40K             0 days 02:45:31
Pace                    0:06:41
TotalSeconds             9931.0
HalfSeconds              5111.0
Name: 1283, dtype: object
Tenafly
 Age                          47
M/F                           M
City                    Tenafly
State                        NJ
Country                     USA
Half            0 days 01:40:09
40K             0 days 03:22:50
Pace                    0:08:13
TotalSeconds            12170.0
HalfSeconds              6009.0
Name: 11662, dtype: object
Teneriffe, Qld
 Age                          35
M/F                           F
City             Teneriffe, Qld
State                       NaN

Name: 16559, dtype: object
The Village
 Age                          60
M/F                           F
City                The Village
State                        OK
Country                     USA
Half            0 days 02:03:38
40K             0 days 04:11:41
Pace                    0:10:08
TotalSeconds            15101.0
HalfSeconds              7418.0
Name: 25590, dtype: object
The Villages
 Age                          68
M/F                           M
City               The Villages
State                        FL
Country                     USA
Half            0 days 02:00:44
40K             0 days 03:57:52
Pace                    0:09:35
TotalSeconds            14272.0
HalfSeconds              7244.0
Name: 25224, dtype: object
The Woodlands
 Age                          45
M/F                           M
City              The Woodlands
State                        TX
Country                     USA
Half            0 days 01:28:11
40K             0 days 03:06:40
Pace                    0:07:40
TotalSeconds            11200.0
HalfSeconds              5291.0
Name: 2197, dtype: object
Thebarton
 Age                          46
M/F                           M
City                  Thebarton
State                       NaN
Country                     AUS
Half            0 days 01:41:36
40K             0 days 03:37:27
Pace                    0:08:50
TotalSeconds            13047.0
HalfSeconds              6096.0
Name: 9529, dtype: object
Theresa
 Age                          57
M/F                           F
City                    Theresa
State                        NY
Country                     USA
Half            0 days 01:57:36
40K             0 days 04:03:02
Pace                    0:09:52
TotalSeconds            14582.0
HalfSeconds              7056.0
Name: 24514, dtype: object
Therwil
 Age                          59
M/F                           M
City                    Therwil
State                       NaN
Country                     SUI
Half            0 days 01:58:55
40K             0 days 04:00:43
Pace                    0:09:42
TotalSeconds            14443.0
HalfSeconds              7135.0
Name: 31539, dtype: object
Thetford
 Age                          30
M/F                           M
City                   Thetford
State                        VT
Country                     USA
Half            0 days 01:21:05
40K             0 days 02:38:34
Pace                    0:06:24
TotalSeconds             9514.0
HalfSeconds              4865.0
Name: 535, dtype: object
Thetford Mines
 Age                          43
M/F                           M
City             Thetford Mines
State                        QC
Country                     CAN
Half            0 days 01:27:40
40K             0 days 02:58:42
Pace                    0:07:14
TotalSeconds            10722.0
HalfSeconds              5260.0
Name: 4689, dtype: object
Thiene
 Age                          49
M/F                           M
City                     Thiene
State                       NaN
Country                     ITA
Half            0 days 01:29:07
40K             0 days 02:56:08
Pace                    0:07:08
TotalSeconds            10568.0
HalfSeconds              5347.0
Name: 3433, dtype: object
Thiensville
 Age                          25
M/F                           F
City                Thiensville
State                        WI
Country                     USA
Half            0 days 01:41:49
40K             0 days 03:23:08
Pace                    0:08:13
TotalSeconds            12188.0
HalfSeconds              6109.0
Name: 9897, dtype: object
Thirroul, New South Wales
 Age                                    28
M/F                                     F
City            Thirroul, New South Wales
State                                 NaN
Country                               AUS
Half                      0 days 01:44:34
40K                       0 days 03:18:28
Pace                              0:07:57
TotalSeconds                      11908.0
HalfSeconds                        6274.0
Name: 16048, dtype: object
Thisted
 Age                          40
M/F                           M
City                    Thisted
State                       NaN
Country                     DEN
Half            0 days 01:35:39
40K             0 days 03:16:48
Pace                    0:07:57
TotalSeconds            11808.0
HalfSeconds              5739.0
Name: 5475, dtype: object
Thomaston
 Age                          54
M/F                           M
City                  Thomaston
State                        CT
Country                     USA
Half            0 days 01:38:05
40K             0 days 03:18:37
Pace                    0:08:03
TotalSeconds            11917.0
HalfSeconds              5885.0
Name: 10452, dtype: object
Thompson
 Age                          25
M/F                           F
City                   Thompson
State                        CT
Country                     USA
Half            0 days 01:31:25
40K             0 days 03:01:03
Pace                    0:07:17
TotalSeconds            10863.0
HalfSeconds              5485.0
Name: 8763, dtype: object
Thoreau
 Age                          33
M/F                           M
City                    Thoreau
State                        NM
Country                     USA
Half            0 days 01:18:20
40K             0 days 02:40:03
Pace                    0:06:32
TotalSeconds             9603.0
HalfSeconds              4700.0
Name: 108, dtype: object
Thornhill
 Age                          47
M/F                           M
City                  Thornhill
State                        ON
Country                     CAN
Half            0 days 01:41:12
40K             0 days 03:30:37
Pace                    0:08:32
TotalSeconds            12637.0
HalfSeconds              6072.0
Name: 11542, dtype: object
Thornton
 Age                          39
M/F                           M
City                   Thornton
State                        CO
Country                     USA
Half            0 days 01:29:31
40K             0 days 03:01:33
Pace                    0:07:19
TotalSeconds            10893.0
HalfSeconds              5371.0
Name: 5595, dtype: object
Thousand Oaks
 Age                          41
M/F                           M
City              Thousand Oaks
State                        CA
Country                     USA
Half            0 days 01:33:00
40K             0 days 03:08:52
Pace                    0:07:46
TotalSeconds            11332.0
HalfSeconds              5580.0
Name: 7279, dtype: object
Three Rivers
 Age                          55
M/F                           M
City               Three Rivers
State                        MA
Country                     USA
Half            0 days 01:42:46
40K             0 days 03:20:19
Pace                    0:08:05
TotalSeconds            12019.0
HalfSeconds              6166.0
Name: 16804, dtype: object
Thunder Bay
 Age                          42
M/F                           M
City                Thunder Bay
State                        ON
Country                     CAN
Half            0 days 01:34:10
40K             0 days 03:06:48
Pace                    0:07:34
TotalSeconds            11208.0
HalfSeconds              5650.0
Name: 3673, dtype: object
Tiburon
 Age                          54
M/F                           M
City                    Tiburon
State                        CA
Country                     USA
Half            0 days 01:36:07
40K             0 days 03:10:02
Pace                    0:07:42
TotalSeconds            11402.0
HalfSeconds              5767.0
Name: 7094, dtype: object
Tichborne
 Age                          50
M/F                           M
City                  Tichborne
State                       NaN
Country                     GBR
Half            0 days 01:31:16
40K             0 days 03:02:43
Pace                    0:07:24
TotalSeconds            10963.0
HalfSeconds              5476.0
Name: 10550, dtype: object
Tierra Verde
 Age                          48
M/F                           M
City               Tierra Verde
State                        FL
Country                     USA
Half            0 days 01:38:30
40K             0 days 03:25:39
Pace                    0:08:20
TotalSeconds            12339.0
HalfSeconds              5910.0
Name: 9484, dtype: object

Tierrs Verde
 Age                          55
M/F                           M
City               Tierrs Verde
State                        FL
Country                     USA
Half            0 days 01:52:45
40K             0 days 04:14:58
Pace                    0:10:21
TotalSeconds            15298.0
HalfSeconds              6765.0
Name: 13366, dtype: object
Tieton
 Age                          31
M/F                           F
City                     Tieton
State                        WA
Country                     USA
Half            0 days 01:36:35
40K             0 days 03:05:59
Pace                    0:07:29
TotalSeconds            11159.0
HalfSeconds              5795.0
Name: 10870, dtype: object
Tiffin
 Age                          63
M/F                           F
City                     Tiffin
State                        OH
Country                     USA
Half            0 days 02:14:29
40K             0 days 04:28:07
Pace                    0:10:51
TotalSeconds            16087.0
HalfSeconds              8069.0
Name: 30620, dtype: object
Tifton
 Age                          59
M/F                           M
City                     Tifton
State                        GA
Country                     USA
Half            0 days 01:58:24
40K             0 days 03:59:47
Pace                    0:09:48
TotalSeconds            14387.0
HalfSeconds              7104.0
Name: 15521, dtype: object
Tigard
 Age                          37
M/F                           F
City                     Tigard
State                        OR
Country                     USA
Half            0 days 01:28:46
40K             0 days 02:56:29
Pace                    0:07:08
TotalSeconds            10589.0
HalfSeconds              5326.0
Name: F34, dtype: object
Tigre
 Age                          41
M/F                           F
City                      Tigre
State                       NaN
Country                     ARG
Half            0 days 01:50:02
40K             0 days 03:31:26
Pace                    0:08:31
TotalSeconds            12686.0
HalfSeconds              6602.0
Name: 20498, dtype: object
Tilburg
 Age                          46
M/F                           F
City                    Tilburg
State                       NaN
Country                     NED
Half            0 days 02:03:49
40K             0 days 04:03:49
Pace                    0:09:51
TotalSeconds            14629.0
HalfSeconds              7429.0
Name: 31271, dtype: object
Tillamook
 Age                          31
M/F                           F
City                  Tillamook
State                        OR
Country                     USA
Half            0 days 01:55:37
40K             0 days 03:42:11
Pace                    0:08:56
TotalSeconds            13331.0
HalfSeconds              6937.0
Name: 14728, dtype: object
Tilles
 Age                          30
M/F                           M
City                     Tilles
State                       NaN
Country                     NOR
Half            0 days 01:52:21
40K             0 days 03:38:58
Pace                    0:08:49
TotalSeconds            13138.0
HalfSeconds              6741.0
Name: 28509, dtype: object
Timberlea
 Age                          34
M/F                           F
City                  Timberlea
State                        NS
Country                     CAN
Half            0 days 01:45:04
40K             0 days 03:27:10
Pace                    0:08:21
TotalSeconds            12430.0
HalfSeconds              6304.0
Name: 17552, dtype: object
Timmins
 Age                          31
M/F                           M
City                    Timmins
State                        ON
Country                     CAN
Half            0 days 01:27:29
40K             0 days 02:49:47
Pace                    0:06:51
TotalSeconds            10187.0
HalfSeconds              5249.0
Name: 2246, dtype: object
Timonium
 Age                          23
M/F                           M
City                   Timonium
State                        MD
Country                     USA
Half            0 days 01:19:24
40K             0 days 02:41:41
Pace                    0:06:33
TotalSeconds             9701.0
HalfSeconds              4764.0
Name: 449, dtype: object
Tingwick
 Age                          53
M/F                           M
City                   Tingwick
State                        QC
Country                     CAN
Half            0 days 01:45:44
40K             0 days 03:37:02
Pace                    0:08:54
TotalSeconds            13022.0
HalfSeconds              6344.0
Name: 13885, dtype: object
Tinley Park
 Age                          27
M/F                           M
City                Tinley Park
State                        IL
Country                     USA
Half            0 days 01:24:40
40K             0 days 02:57:08
Pace                    0:07:10
TotalSeconds            10628.0
HalfSeconds              5080.0
Name: 1000, dtype: object
Tinton Falls
 Age                          31
M/F                           M
City               Tinton Falls
State                        NJ
Country                     USA
Half            0 days 01:15:18
40K             0 days 02:44:17
Pace                    0:06:39
TotalSeconds             9857.0
HalfSeconds              4518.0
Name: 136, dtype: object
Tiny
 Age                          45
M/F                           M
City                       Tiny
State                        ON
Country                     CAN
Half            0 days 01:30:07
40K             0 days 03:03:58
Pace                    0:07:26
TotalSeconds            11038.0
HalfSeconds              5407.0
Name: 3101, dtype: object
Tipp City
 Age                          41
M/F                           M
City                  Tipp City
State                        OH
Country                     USA
Half            0 days 01:28:56
40K             0 days 03:10:01
Pace                    0:07:55
TotalSeconds            11401.0
HalfSeconds              5336.0
Name: 3940, dtype: object
Tipperary
 Age                          40
M/F                           M
City                  Tipperary
State                       NaN
Country                     IRL
Half            0 days 01:45:16
40K             0 days 03:36:24
Pace                    0:08:47
TotalSeconds            12984.0
HalfSeconds              6316.0
Name: 8969, dtype: object
Tirana
 Age                          48
M/F                           M
City                     Tirana
State                       NaN
Country                     ALB
Half            0 days 01:42:13
40K             0 days 03:32:10
Pace                    0:08:37
TotalSeconds            12730.0
HalfSeconds              6133.0
Name: 11449, dtype: object
Tisbury
 Age                          48
M/F                           F
City                    Tisbury
State                        MA
Country                     USA
Half            0 days 02:00:59
40K             0 days 04:04:40
Pace                    0:09:51
TotalSeconds            14680.0
HalfSeconds              7259.0
Name: 22730, dtype: object
Titusville
 Age                          48
M/F                           M
City                 Titusville
State                        FL
Country                     USA
Half            0 days 01:44:16
40K             0 days 03:28:57
Pace                    0:08:27
TotalSeconds            12537.0
HalfSeconds              6256.0
Name: 11620, dtype: object
Tiverton
 Age                          35
M/F                           F
City                   Tiverton
State                        RI
Country                     USA
Half            0 days 01:32:36
40K             0 days 03:00:31
Pace                    0:07:16
TotalSeconds            10831.0
HalfSeconds              5556.0
Name: 8649, dtype: object
Tlalnepantla
 Age                          60
M/F                           M
City               Tlalnepantla
State                       NaN
Country                     MEX
Half            0 days 01:43:34
40K             0 days 03:35:03
Pace                    0:08:50
TotalSeconds            12903.0
HalfSeconds              6214.0
Name: 20748, dtype: object
Tlalnepantla De Baz
 Age                              63
M/F                               M
City            Tlalnepantla De Baz
State                           NaN
Country                         MEX
Half                0 days 01:36:00
40K                 0 days 03:09:27
Pace                        0:07:38
TotalSeconds                11367.0
HalfSeconds                  5760.0
Name: 7099, dtype: object
Tlalnepantla Estado De México C.p.
 Age                                             41
M/F                                              F
City            Tlalnepantla Estado De México C.p.
State                                          NaN
Country                                        MEX
Half                               0 days 01:44:23
40K                                0 days 03:29:46
Pace                                       0:08:28
TotalSeconds                               12586.0
HalfSeconds                                 6263.0
Name: 20419, dtype: object
Toano
 Age                          43
M/F                           M
City                      Toano
State                        VA
Country                     USA
Half            0 days 01:41:11
40K             0 days 03:29:29
Pace                    0:08:29
TotalSeconds            12569.0
HalfSeconds              6071.0
Name: 8737, dtype: object
Tochigi
 Age                          47
M/F                           M
City                    Tochigi
State                       NaN
Country                     JPN
Half            0 days 01:40:37
40K             0 days 03:16:39
Pace                    0:07:56
TotalSeconds            11799.0
HalfSeconds              6037.0
Name: 10477, dtype: object
Tokyo
 Age                          32
M/F                           M
City                      Tokyo
State                       NaN
Country                     JPN
Half            0 days 01:06:47
40K             0 days 02:17:06
Pace                    0:05:33
TotalSeconds             8226.0
HalfSeconds              4007.0
Name: 30, dtype: object
Tokyo Chiyodaku
 Age                          38
M/F                           M
City            Tokyo Chiyodaku
State                       NaN
Country                     JPN
Half            0 days 01:49:36
40K             0 days 03:36:24
Pace                    0:08:46
TotalSeconds            12984.0
HalfSeconds              6576.0
Name: 29158, dtype: object
Tokyo Katsushika
 Age                           62
M/F                            F
City            Tokyo Katsushika
State                        NaN
Country                      JPN
Half             0 days 01:44:54
40K              0 days 03:28:56
Pace                     0:08:27
TotalSeconds             12536.0
HalfSeconds               6294.0
Name: 12910, dtype: object
Tokyo Nerima
 Age                          64
M/F                           F
City               Tokyo Nerima
State                       NaN
Country                     JPN
Half            0 days 02:17:11
40K             0 days 05:27:38
Pace                    0:13:04
TotalSeconds            19658.0
HalfSeconds              8231.0
Name: 25952, dtype: object
Toledo
 Age                          39
M/F                           M
City                     Toledo
State                        OH
Country                     USA
Half            0 days 01:33:59
40K             0 days 03:08:18
Pace                    0:07:37
TotalSeconds            11298.0
HalfSeconds              5639.0
Name: 5021, dtype: object
Tolland
 Age                          37
M/F                           F
City                    Tolland
State                        CT
Country                     USA
Half            0 days 01:38:34
40K             0 days 03:13:15
Pace                    0:07:48
TotalSeconds            11595.0
HalfSeconds              5914.0
Name: 14932, dtype: object
Toluca
 Age                          36
M/F                           M
City                     Toluca
State                       NaN
Country                     MEX
Half            0 days 01:24:27
40K             0 days 02:51:25
Pace                    0:06:57
TotalSeconds            10285.0
HalfSeconds              5067.0
Name: 4365, dtype: object
Toluca Lake
 Age                          44
M/F                           F
City                Toluca Lake
State                        CA
Country                     USA
Half            0 days 01:34:49
40K             0 days 03:05:06
Pace                    0:07:29
TotalSeconds            11106.0
HalfSeconds              5689.0
Name: 12802, dtype: object
Tomball
 Age                          44
M/F                           M
City                    Tomball
State                        TX
Country                     USA
Half            0 days 01:20:24
40K             0 days 02:37:06
Pace                    0:06:21
TotalSeconds             9426.0
HalfSeconds              4824.0
Name: 714, dtype: object
Toms River
 Age                          39
M/F                           F
City                 Toms River
State                        NJ
Country                     USA
Half            0 days 01:40:59
40K             0 days 03:35:13
Pace                    0:08:45
TotalSeconds            12913.0
HalfSeconds              6059.0
Name: 16483, dtype: object
Tonalea
 Age                          36
M/F                           M
City                    Tonalea
State                        AZ
Country                     USA
Half            0 days 01:33:58
40K             0 days 03:02:28
Pace                    0:07:21
TotalSeconds            10948.0
HalfSeconds              5638.0
Name: 5502, dtype: object
Tonawanda
 Age                          52
M/F                           M
City                  Tonawanda
State                        NY
Country                     USA
Half            0 days 01:44:53
40K             0 days 03:19:52
Pace                    0:08:03
TotalSeconds            11992.0
HalfSeconds              6293.0
Name: 12415, dtype: object
Tonsberg
 Age                          45
M/F                           M
City                   Tonsberg
State                       NaN
Country                     NOR
Half            0 days 01:33:17
40K             0 days 03:04:07
Pace                    0:07:27
TotalSeconds            11047.0
HalfSeconds              5597.0
Name: 9290, dtype: object
Tooele
 Age                          60
M/F                           M
City                     Tooele
State                        UT
Country                     USA
Half            0 days 01:55:52
40K             0 days 03:46:57
Pace                    0:09:09
TotalSeconds            13617.0
HalfSeconds              6952.0
Name: 22759, dtype: object
Toomebridge
 Age                          53
M/F                           F
City                Toomebridge
State                       NaN
Country                     GBR
Half            0 days 01:47:03
40K             0 days 03:26:49
Pace                    0:08:20
TotalSeconds            12409.0
HalfSeconds              6423.0
Name: 21608, dtype: object
Topanga
 Age                          59
M/F                           M
City                    Topanga
State                        CA
Country                     USA
Half            0 days 01:56:26
40K             0 days 04:10:53
Pace                    0:10:11
TotalSeconds            15053.0
HalfSeconds              6986.0
Name: 5362, dtype: object
Topeka
 Age                          34
M/F                           M
City                     Topeka
State                        IN
Country                     USA
Half            0 days 01:20:51
40K             0 days 02:38:50
Pace                    0:06:24
TotalSeconds             9530.0
HalfSeconds              4851.0
Name: 710, dtype: object
Topsfield
 Age                          25
M/F                           F
City                  Topsfield
State                        MA
Country                     USA
Half            0 days 01:42:48
40K             0 days 03:23:00
Pace                    0:08:11
TotalSeconds            12180.0
HalfSeconds              6168.0
Name: 13793, dtype: object

Topsham
 Age                          32
M/F                           F
City                    Topsham
State                        ME
Country                     USA
Half            0 days 01:49:58
40K             0 days 03:32:16
Pace                    0:08:32
TotalSeconds            12736.0
HalfSeconds              6598.0
Name: 16962, dtype: object
Topton
 Age                          45
M/F                           M
City                     Topton
State                        PA
Country                     USA
Half            0 days 01:44:53
40K             0 days 03:28:34
Pace                    0:08:24
TotalSeconds            12514.0
HalfSeconds              6293.0
Name: 11719, dtype: object
Torbay
 Age                          40
M/F                           M
City                     Torbay
State                        NL
Country                     CAN
Half            0 days 01:22:06
40K             0 days 02:46:29
Pace                    0:06:45
TotalSeconds             9989.0
HalfSeconds              4926.0
Name: 773, dtype: object
Torino
 Age                          39
M/F                           M
City                     Torino
State                       NaN
Country                     ITA
Half            0 days 01:29:41
40K             0 days 03:04:17
Pace                    0:07:27
TotalSeconds            11057.0
HalfSeconds              5381.0
Name: 3637, dtype: object
Toronto
 Age                          30
M/F                           M
City                    Toronto
State                        ON
Country                     CAN
Half            0 days 01:16:32
40K             0 days 02:31:35
Pace                    0:06:10
TotalSeconds             9095.0
HalfSeconds              4592.0
Name: 239, dtype: object
Torrance
 Age                          30
M/F                           M
City                   Torrance
State                        CA
Country                     USA
Half            0 days 01:25:21
40K             0 days 02:52:34
Pace                    0:06:59
TotalSeconds            10354.0
HalfSeconds              5121.0
Name: 3223, dtype: object
Torreon
 Age                          35
M/F                           F
City                    Torreon
State                       NaN
Country                     MEX
Half            0 days 01:43:08
40K             0 days 03:23:54
Pace                    0:08:14
TotalSeconds            12234.0
HalfSeconds              6188.0
Name: 18589, dtype: object
Torreon, Coahuila Mexico
 Age                                   58
M/F                                    M
City            Torreon, Coahuila Mexico
State                                NaN
Country                              MEX
Half                     0 days 01:50:03
40K                      0 days 03:40:48
Pace                             0:08:57
TotalSeconds                     13248.0
HalfSeconds                       6603.0
Name: 19738, dtype: object
Torrington
 Age                          24
M/F                           M
City                 Torrington
State                        CT
Country                     USA
Half            0 days 01:23:05
40K             0 days 02:44:07
Pace                    0:06:38
TotalSeconds             9847.0
HalfSeconds              4985.0
Name: 1132, dtype: object
Toulouse
 Age                          42
M/F                           M
City                   Toulouse
State                       NaN
Country                     FRA
Half            0 days 01:32:01
40K             0 days 03:07:53
Pace                    0:07:36
TotalSeconds            11273.0
HalfSeconds              5521.0
Name: 4330, dtype: object
Toumi City Nagano Pre
 Age                                34
M/F                                 F
City            Toumi City Nagano Pre
State                             NaN
Country                           JPN
Half                  0 days 01:45:08
40K                   0 days 03:37:33
Pace                          0:08:45
TotalSeconds                  13053.0
HalfSeconds                    6308.0
Name: 14519, dtype: object
Towaco
 Age                          55
M/F                           F
City                     Towaco
State                        NJ
Country                     USA
Half            0 days 01:53:14
40K             0 days 03:42:14
Pace                    0:08:57
TotalSeconds            13334.0
HalfSeconds              6794.0
Name: 25204, dtype: object
Towanda
 Age                          49
M/F                           F
City                    Towanda
State                        PA
Country                     USA
Half            0 days 02:04:52
40K             0 days 04:20:50
Pace                    0:10:30
TotalSeconds            15650.0
HalfSeconds              7492.0
Name: 24415, dtype: object
Townsend
 Age                          51
M/F                           M
City                   Townsend
State                        MA
Country                     USA
Half            0 days 01:47:40
40K             0 days 03:46:57
Pace                    0:09:11
TotalSeconds            13617.0
HalfSeconds              6460.0
Name: 16107, dtype: object
Towson
 Age                          31
M/F                           M
City                     Towson
State                        MD
Country                     USA
Half            0 days 01:31:34
40K             0 days 02:51:11
Pace                    0:06:52
TotalSeconds            10271.0
HalfSeconds              5494.0
Name: 5742, dtype: object
Toyonaka
 Age                          74
M/F                           M
City                   Toyonaka
State                       NaN
Country                     JPN
Half            0 days 02:11:44
40K             0 days 04:45:51
Pace                    0:11:45
TotalSeconds            17151.0
HalfSeconds              7904.0
Name: 25580, dtype: object
Toyonaka Osaka
 Age                          46
M/F                           F
City             Toyonaka Osaka
State                       NaN
Country                     JPN
Half            0 days 01:50:30
40K             0 days 03:38:50
Pace                    0:08:50
TotalSeconds            13130.0
HalfSeconds              6630.0
Name: 15195, dtype: object
Toyota City, Aichi
 Age                             67
M/F                              M
City            Toyota City, Aichi
State                          NaN
Country                        JPN
Half               0 days 02:12:06
40K                0 days 04:12:51
Pace                       0:10:10
TotalSeconds               15171.0
HalfSeconds                 7926.0
Name: 31704, dtype: object
Trabuco Canyon
 Age                          53
M/F                           M
City             Trabuco Canyon
State                        CA
Country                     USA
Half            0 days 01:25:56
40K             0 days 03:07:58
Pace                    0:07:57
TotalSeconds            11278.0
HalfSeconds              5156.0
Name: 938, dtype: object
Tracadie-Sheila,
 Age                           61
M/F                            F
City            Tracadie-Sheila,
State                         NB
Country                      CAN
Half             0 days 01:58:31
40K              0 days 03:57:38
Pace                     0:09:39
TotalSeconds             14258.0
HalfSeconds               7111.0
Name: 25964, dtype: object
Tracy
 Age                          49
M/F                           M
City                      Tracy
State                        CA
Country                     USA
Half            0 days 01:34:33
40K             0 days 03:13:43
Pace                    0:07:51
TotalSeconds            11623.0
HalfSeconds              5673.0
Name: 6154, dtype: object
Trail
 Age                          62
M/F                           M
City                      Trail
State                        BC
Country                     CAN
Half            0 days 01:55:29
40K             0 days 03:48:11
Pace                    0:09:15
TotalSeconds            13691.0
HalfSeconds              6929.0
Name: 21978, dtype: object
Trappe
 Age                          35
M/F                           M
City                     Trappe
State                        MD
Country                     USA
Half            0 days 01:28:37
40K             0 days 02:56:47
Pace                    0:07:10
TotalSeconds            10607.0
HalfSeconds              5317.0
Name: 5553, dtype: object
Travelers Rest
 Age                          61
M/F                           F
City             Travelers Rest
State                        SC
Country                     USA
Half            0 days 02:07:04
40K             0 days 04:22:27
Pace                    0:10:38
TotalSeconds            15747.0
HalfSeconds              7624.0
Name: 25806, dtype: object
Traverse City
 Age                          44
M/F                           M
City              Traverse City
State                        MI
Country                     USA
Half            0 days 01:33:41
40K             0 days 03:01:32
Pace                    0:07:20
TotalSeconds            10892.0
HalfSeconds              5621.0
Name: 7639, dtype: object
Travis Afb
 Age                          35
M/F                           M
City                 Travis Afb
State                        CA
Country                     USA
Half            0 days 01:26:28
40K             0 days 02:53:27
Pace                    0:07:03
TotalSeconds            10407.0
HalfSeconds              5188.0
Name: 3782, dtype: object
Trelex
 Age                          40
M/F                           M
City                     Trelex
State                       NaN
Country                     SUI
Half            0 days 02:12:01
40K             0 days 04:43:43
Pace                    0:11:24
TotalSeconds            17023.0
HalfSeconds              7921.0
Name: 31588, dtype: object
Trenton
 Age                          31
M/F                           M
City                    Trenton
State                        MI
Country                     USA
Half            0 days 01:25:19
40K             0 days 03:08:03
Pace                    0:07:39
TotalSeconds            11283.0
HalfSeconds              5119.0
Name: 1520, dtype: object
Treuenbrietzen
 Age                          53
M/F                           M
City             Treuenbrietzen
State                       NaN
Country                     GER
Half            0 days 02:01:05
40K             0 days 04:54:36
Pace                    0:12:04
TotalSeconds            17676.0
HalfSeconds              7265.0
Name: 13180, dtype: object
Treviso
 Age                          61
M/F                           M
City                    Treviso
State                       NaN
Country                     ITA
Half            0 days 01:47:02
40K             0 days 03:36:36
Pace                    0:08:44
TotalSeconds            12996.0
HalfSeconds              6422.0
Name: 16811, dtype: object
Triadelphia
 Age                          41
M/F                           F
City                Triadelphia
State                        WV
Country                     USA
Half            0 days 01:51:24
40K             0 days 03:40:31
Pace                    0:08:54
TotalSeconds            13231.0
HalfSeconds              6684.0
Name: 18699, dtype: object
Trieste
 Age                          43
M/F                           M
City                    Trieste
State                       NaN
Country                     ITA
Half            0 days 01:21:13
40K             0 days 02:47:02
Pace                    0:06:47
TotalSeconds            10022.0
HalfSeconds              4873.0
Name: 783, dtype: object
Trinity
 Age                          32
M/F                           F
City                    Trinity
State                        FL
Country                     USA
Half            0 days 01:36:51
40K             0 days 03:07:25
Pace                    0:07:35
TotalSeconds            11245.0
HalfSeconds              5811.0
Name: 14041, dtype: object
Trois Rivieres
 Age                          46
M/F                           M
City             Trois Rivieres
State                        QC
Country                     CAN
Half            0 days 01:37:11
40K             0 days 03:14:45
Pace                    0:07:54
TotalSeconds            11685.0
HalfSeconds              5831.0
Name: 9196, dtype: object
Trois-Rivieres
 Age                          43
M/F                           M
City             Trois-Rivieres
State                        QC
Country                     CAN
Half            0 days 01:25:52
40K             0 days 02:45:47
Pace                    0:06:42
TotalSeconds             9947.0
HalfSeconds              5152.0
Name: 2198, dtype: object
Trois-Rivietes
 Age                          49
M/F                           M
City             Trois-Rivietes
State                        QC
Country                     CAN
Half            0 days 01:44:46
40K             0 days 03:32:04
Pace                    0:08:35
TotalSeconds            12724.0
HalfSeconds              6286.0
Name: 11850, dtype: object
Trophy Club
 Age                          25
M/F                           F
City                Trophy Club
State                        TX
Country                     USA
Half            0 days 01:40:27
40K             0 days 03:15:14
Pace                    0:07:53
TotalSeconds            11714.0
HalfSeconds              6027.0
Name: 12268, dtype: object
Troy
 Age                          36
M/F                           M
City                       Troy
State                        NY
Country                     USA
Half            0 days 01:24:16
40K             0 days 02:40:37
Pace                    0:06:28
TotalSeconds             9637.0
HalfSeconds              5056.0
Name: 3141, dtype: object
Truckee
 Age                          45
M/F                           F
City                    Truckee
State                        CA
Country                     USA
Half            0 days 01:51:23
40K             0 days 03:40:12
Pace                    0:08:52
TotalSeconds            13212.0
HalfSeconds              6683.0
Name: 20880, dtype: object
Trujillo Alto
 Age                          49
M/F                           M
City              Trujillo Alto
State                        PR
Country                     USA
Half            0 days 01:39:59
40K             0 days 03:14:31
Pace                    0:07:51
TotalSeconds            11671.0
HalfSeconds              5999.0
Name: 10547, dtype: object
Truro
 Age                          53
M/F                           M
City                      Truro
State                       NaN
Country                     GBR
Half            0 days 01:45:46
40K             0 days 03:53:41
Pace                    0:09:29
TotalSeconds            14021.0
HalfSeconds              6346.0
Name: 14758, dtype: object
Truro Heights
 Age                          46
M/F                           F
City              Truro Heights
State                        NS
Country                     CAN
Half            0 days 01:54:02
40K             0 days 03:40:25
Pace                    0:08:53
TotalSeconds            13225.0
HalfSeconds              6842.0
Name: 21557, dtype: object
Trussville
 Age                          34
M/F                           F
City                 Trussville
State                        AL
Country                     USA
Half            0 days 01:59:03
40K             0 days 03:58:41
Pace                    0:09:38
TotalSeconds            14321.0
HalfSeconds              7143.0
Name: 17569, dtype: object
Tseung Kwan O
 Age                          55
M/F                           F
City              Tseung Kwan O
State                       NaN
Country                     HKG
Half            0 days 01:53:55
40K             0 days 03:38:17
Pace                    0:08:46
TotalSeconds            13097.0
HalfSeconds              6835.0
Name: 22574, dtype: object
Tseung Kwan O, Hong Kong
 Age                                   50
M/F                                    M
City            Tseung Kwan O, Hong Kong
State                                NaN
Country                              HKG
Half                     0 days 01:42:36
40K                      0 days 03:38:31
Pace                             0:08:47
TotalSeconds                     13111.0
HalfSeconds                       6156.0
Name: 13182, dtype: object
Tsing Lung Tau, Tsuen Wan, N.t.,
 Age                                           52
M/F                                            M
City            Tsing Lung Tau, Tsuen Wan, N.t.,
State                                        NaN
Country                                      HKG
Half                             0 days 01:45:30
40K                              0 days 04:05:19
Pace                                     0:09:55
TotalSeconds                             14719.0
HalfSeconds                               6330.0
Name: 8111, dtype: object
Tsing Yi
 Age                          41
M/F                           M
City                   Tsing Yi
State                       NaN
Country                     HKG
Half            0 days 01:31:17
40K             0 days 03:25:00
Pace                    0:08:19
TotalSeconds            12300.0
HalfSeconds              5477.0
Name: 8798, dtype: object
Tsuen Wan
 Age                          46
M/F                           F
City                  Tsuen Wan
State                       NaN
Country                     HKG
Half            0 days 01:46:18
40K             0 days 03:54:22
Pace                    0:09:32
TotalSeconds            14062.0
HalfSeconds              6378.0
Name: 18893, dtype: object
Tualatin
 Age                          49
M/F                           M
City                   Tualatin
State                        OR
Country                     USA
Half            0 days 01:39:26
40K             0 days 03:26:42
Pace                    0:08:25
TotalSeconds            12402.0
HalfSeconds              5966.0
Name: 10455, dtype: object
Tuba City
 Age                          57
M/F                           M
City                  Tuba City
State                        AZ
Country                     USA
Half            0 days 01:46:33
40K             0 days 03:25:37
Pace                    0:08:16
TotalSeconds            12337.0
HalfSeconds              6393.0
Name: 15222, dtype: object
Tubingen
 Age                          42
M/F                           M
City                   Tubingen
State                       NaN
Country                     GER
Half            0 days 01:36:08
40K             0 days 03:44:59
Pace                    0:09:09
TotalSeconds            13499.0
HalfSeconds              5768.0
Name: 8204, dtype: object
Tuckahoe
 Age                          55
M/F                           M
City                   Tuckahoe
State                        NY
Country                     USA
Half            0 days 01:43:47
40K             0 days 03:30:39
Pace                    0:08:31
TotalSeconds            12639.0
HalfSeconds              6227.0
Name: 14361, dtype: object
Tucker
 Age                          56
M/F                           F
City                     Tucker
State                        GA
Country                     USA
Half            0 days 02:02:34
40K             0 days 04:02:59
Pace                    0:09:47
TotalSeconds            14579.0
HalfSeconds              7354.0
Name: 25153, dtype: object
Tucson
 Age                          51
M/F                           M
City                     Tucson
State                        AZ
Country                     USA
Half            0 days 01:26:50
40K             0 days 02:50:19
Pace                    0:06:54
TotalSeconds            10219.0
HalfSeconds              5210.0
Name: 1311, dtype: object
Tujunga
 Age                          61
M/F                           M
City                    Tujunga
State                        CA
Country                     USA

Name: 14609, dtype: object
Ulm
 Age                          53
M/F                           M
City                        Ulm
State                       NaN
Country                     GER
Half            0 days 01:35:55
40K             0 days 03:17:44
Pace                    0:08:02
TotalSeconds            11864.0
HalfSeconds              5755.0
Name: 5029, dtype: object
Umea
 Age                          52
M/F                           M
City                       Umea
State                       NaN
Country                     SWE
Half            0 days 02:18:13
40K             0 days 04:34:42
Pace                    0:11:03
TotalSeconds            16482.0
HalfSeconds              8293.0
Name: 31467, dtype: object
Uncasville
 Age                          45
M/F                           F
City                 Uncasville
State                        CT
Country                     USA
Half            0 days 01:57:44
40K             0 days 04:00:25
Pace                    0:09:57
TotalSeconds            14425.0
HalfSeconds              7064.0
Name: 21896, dtype: object
Underhill
 Age                          42
M/F                           F
City                  Underhill
State                        VT
Country                     USA
Half            0 days 01:48:12
40K             0 days 03:35:39
Pace                    0:08:43
TotalSeconds            12939.0
HalfSeconds              6492.0
Name: 14637, dtype: object
Union
 Age                          32
M/F                           M
City                      Union
State                        KY
Country                     USA
Half            0 days 01:18:43
40K             0 days 02:34:25
Pace                    0:06:16
TotalSeconds             9265.0
HalfSeconds              4723.0
Name: 4866, dtype: object
Union City
 Age                          25
M/F                           M
City                 Union City
State                        NJ
Country                     USA
Half            0 days 01:34:01
40K             0 days 03:02:30
Pace                    0:07:21
TotalSeconds            10950.0
HalfSeconds              5641.0
Name: 2559, dtype: object
Uniontown
 Age                          35
M/F                           F
City                  Uniontown
State                        OH
Country                     USA
Half            0 days 01:34:01
40K             0 days 03:04:49
Pace                    0:07:28
TotalSeconds            11089.0
HalfSeconds              5641.0
Name: 7156, dtype: object
Unionville
 Age                          37
M/F                           F
City                 Unionville
State                        CT
Country                     USA
Half            0 days 01:26:57
40K             0 days 02:58:39
Pace                    0:07:16
TotalSeconds            10719.0
HalfSeconds              5217.0
Name: 5076, dtype: object
University Heights
 Age                             50
M/F                              M
City            University Heights
State                           OH
Country                        USA
Half               0 days 01:33:49
40K                0 days 03:08:08
Pace                       0:07:36
TotalSeconds               11288.0
HalfSeconds                 5629.0
Name: 5789, dtype: object
University Hts
 Age                          35
M/F                           M
City             University Hts
State                        OH
Country                     USA
Half            0 days 01:21:11
40K             0 days 02:48:02
Pace                    0:06:49
TotalSeconds            10082.0
HalfSeconds              4871.0
Name: 627, dtype: object
University Park
 Age                          38
M/F                           F
City            University Park
State                        MD
Country                     USA
Half            0 days 01:46:48
40K             0 days 03:31:10
Pace                    0:08:32
TotalSeconds            12670.0
HalfSeconds              6408.0
Name: 15314, dtype: object
University Place
 Age                           54
M/F                            M
City            University Place
State                         WA
Country                      USA
Half             0 days 01:31:50
40K              0 days 02:57:07
Pace                     0:07:08
TotalSeconds             10627.0
HalfSeconds               5510.0
Name: 8090, dtype: object
Unterschleissheim
 Age                            32
M/F                             M
City            Unterschleissheim
State                         NaN
Country                       GER
Half              0 days 01:33:46
40K               0 days 03:04:29
Pace                      0:07:26
TotalSeconds              11069.0
HalfSeconds                5626.0
Name: 8701, dtype: object
Upland
 Age                          35
M/F                           M
City                     Upland
State                        CA
Country                     USA
Half            0 days 01:22:47
40K             0 days 02:43:58
Pace                    0:06:37
TotalSeconds             9838.0
HalfSeconds              4967.0
Name: 1203, dtype: object
Upper Arlington
 Age                          46
M/F                           M
City            Upper Arlington
State                        OH
Country                     USA
Half            0 days 01:20:24
40K             0 days 02:49:30
Pace                    0:06:50
TotalSeconds            10170.0
HalfSeconds              4824.0
Name: 305, dtype: object
Upper Black Eddy
 Age                           43
M/F                            F
City            Upper Black Eddy
State                         PA
Country                      USA
Half             0 days 01:54:33
40K              0 days 03:39:57
Pace                     0:08:50
TotalSeconds             13197.0
HalfSeconds               6873.0
Name: 18042, dtype: object
Upper Darby
 Age                          37
M/F                           M
City                Upper Darby
State                        PA
Country                     USA
Half            0 days 01:27:25
40K             0 days 02:55:30
Pace                    0:07:06
TotalSeconds            10530.0
HalfSeconds              5245.0
Name: 4449, dtype: object
Upper Ferntree Gully
 Age                               27
M/F                                F
City            Upper Ferntree Gully
State                            NaN
Country                          AUS
Half                 0 days 01:35:12
40K                  0 days 03:05:52
Pace                         0:07:30
TotalSeconds                 11152.0
HalfSeconds                   5712.0
Name: 16148, dtype: object
Upper Marlboro
 Age                          64
M/F                           M
City             Upper Marlboro
State                        MD
Country                     USA
Half            0 days 01:46:42
40K             0 days 03:27:42
Pace                    0:08:28
TotalSeconds            12462.0
HalfSeconds              6402.0
Name: 21828, dtype: object
Upper Montclair
 Age                          48
M/F                           M
City            Upper Montclair
State                        NJ
Country                     USA
Half            0 days 01:29:57
40K             0 days 02:52:33
Pace                    0:06:57
TotalSeconds            10353.0
HalfSeconds              5397.0
Name: 3135, dtype: object
Upper Nyack
 Age                          46
M/F                           M
City                Upper Nyack
State                        NY
Country                     USA
Half            0 days 01:30:18
40K             0 days 02:53:26
Pace                    0:06:59
TotalSeconds            10406.0
HalfSeconds              5418.0
Name: 4482, dtype: object
Upper Saddle River
 Age                             54
M/F                              F
City            Upper Saddle River
State                           NJ
Country                        USA
Half               0 days 01:46:07
40K                0 days 03:31:53
Pace                       0:08:35
TotalSeconds               12713.0
HalfSeconds                 6367.0
Name: 20491, dtype: object
Upper Tantallon
 Age                          46
M/F                           F
City            Upper Tantallon
State                        NS
Country                     CAN
Half            0 days 01:58:21
40K             0 days 03:50:19
Pace                    0:09:18
TotalSeconds            13819.0
HalfSeconds              7101.0
Name: 23171, dtype: object

Uppsala
 Age                          46
M/F                           M
City                    Uppsala
State                       NaN
Country                     SWE
Half            0 days 01:33:26
40K             0 days 03:07:06
Pace                    0:07:33
TotalSeconds            11226.0
HalfSeconds              5606.0
Name: 3973, dtype: object
Upton
 Age                          58
M/F                           F
City                      Upton
State                        MA
Country                     USA
Half            0 days 02:18:35
40K             0 days 00:00:00
Pace                    0:11:07
TotalSeconds                0.0
HalfSeconds              8315.0
Name: 27421, dtype: object
Urbana
 Age                          29
M/F                           M
City                     Urbana
State                        IL
Country                     USA
Half            0 days 01:29:36
40K             0 days 02:59:06
Pace                    0:07:15
TotalSeconds            10746.0
HalfSeconds              5376.0
Name: 3062, dtype: object
Urbandale
 Age                          50
M/F                           M
City                  Urbandale
State                        IA
Country                     USA
Half            0 days 01:27:59
40K             0 days 03:05:59
Pace                    0:07:37
TotalSeconds            11159.0
HalfSeconds              5279.0
Name: 2529, dtype: object
Urique
 Age                          33
M/F                           M
City                     Urique
State                       NaN
Country                     MEX
Half            0 days 01:38:40
40K             0 days 03:24:40
Pace                    0:08:20
TotalSeconds            12280.0
HalfSeconds              5920.0
Name: 11543, dtype: object
Uruapan Mich
 Age                          35
M/F                           M
City               Uruapan Mich
State                       NaN
Country                     MEX
Half            0 days 01:26:13
40K             0 days 02:45:45
Pace                    0:06:41
TotalSeconds             9945.0
HalfSeconds              5173.0
Name: 4688, dtype: object
Usaf Academy
 Age                          21
M/F                           M
City               Usaf Academy
State                        CO
Country                     USA
Half            0 days 01:24:29
40K             0 days 02:54:20
Pace                    0:07:05
TotalSeconds            10460.0
HalfSeconds              5069.0
Name: 1360, dtype: object
Usafa
 Age                          22
M/F                           M
City                      Usafa
State                        CO
Country                     USA
Half            0 days 01:16:17
40K             0 days 02:34:18
Pace                    0:06:14
TotalSeconds             9258.0
HalfSeconds              4577.0
Name: 459, dtype: object
Ushiku
 Age                          71
M/F                           M
City                     Ushiku
State                       NaN
Country                     JPN
Half            0 days 02:04:51
40K             0 days 04:56:01
Pace                    0:11:59
TotalSeconds            17761.0
HalfSeconds              7491.0
Name: 22266, dtype: object
Ustron
 Age                          49
M/F                           M
City                     Ustron
State                       NaN
Country                     POL
Half            0 days 01:57:36
40K             0 days 04:12:28
Pace                    0:10:17
TotalSeconds            15148.0
HalfSeconds              7056.0
Name: 5887, dtype: object
Utica
 Age                          26
M/F                           M
City                      Utica
State                        NY
Country                     USA
Half            0 days 01:25:31
40K             0 days 02:43:31
Pace                    0:06:35
TotalSeconds             9811.0
HalfSeconds              5131.0
Name: 3436, dtype: object
Uxbridge
 Age                          31
M/F                           F
City                   Uxbridge
State                        MA
Country                     USA
Half            0 days 01:42:03
40K             0 days 03:21:39
Pace                    0:08:08
TotalSeconds            12099.0
HalfSeconds              6123.0
Name: 16443, dtype: object
Vaasa
 Age                          38
M/F                           F
City                      Vaasa
State                       NaN
Country                     FIN
Half            0 days 01:58:35
40K             0 days 03:55:43
Pace                    0:09:31
TotalSeconds            14143.0
HalfSeconds              7115.0
Name: 18592, dtype: object
Vacaville
 Age                          20
M/F                           M
City                  Vacaville
State                        CA
Country                     USA
Half            0 days 01:18:59
40K             0 days 02:37:13
Pace                    0:06:22
TotalSeconds             9433.0
HalfSeconds              4739.0
Name: 920, dtype: object
Vadnais Heights
 Age                          21
M/F                           M
City            Vadnais Heights
State                        MN
Country                     USA
Half            0 days 01:25:55
40K             0 days 03:14:36
Pace                    0:07:58
TotalSeconds            11676.0
HalfSeconds              5155.0
Name: 1940, dtype: object
Vaerloese
 Age                          45
M/F                           M
City                  Vaerloese
State                       NaN
Country                     DEN
Half            0 days 01:55:13
40K             0 days 03:51:42
Pace                    0:09:22
TotalSeconds            13902.0
HalfSeconds              6913.0
Name: 30427, dtype: object
Vail
 Age                          48
M/F                           F
City                       Vail
State                        AZ
Country                     USA
Half            0 days 01:46:58
40K             0 days 03:37:49
Pace                    0:08:48
TotalSeconds            13069.0
HalfSeconds              6418.0
Name: 16773, dtype: object
Val-D'Or
 Age                          48
M/F                           M
City                   Val-D'Or
State                        QC
Country                     CAN
Half            0 days 01:37:16
40K             0 days 03:07:53
Pace                    0:07:34
TotalSeconds            11273.0
HalfSeconds              5836.0
Name: 8535, dtype: object
Val-David
 Age                          39
M/F                           F
City                  Val-David
State                        QC
Country                     CAN
Half            0 days 01:52:25
40K             0 days 03:34:59
Pace                    0:08:38
TotalSeconds            12899.0
HalfSeconds              6745.0
Name: 20184, dtype: object
Valatie
 Age                          45
M/F                           F
City                    Valatie
State                        NY
Country                     USA
Half            0 days 01:32:13
40K             0 days 02:59:49
Pace                    0:07:16
TotalSeconds            10789.0
HalfSeconds              5533.0
Name: 6540, dtype: object
Valby
 Age                          26
M/F                           F
City                      Valby
State                       NaN
Country                     DEN
Half            0 days 01:58:33
40K             0 days 03:50:38
Pace                    0:09:17
TotalSeconds            13838.0
HalfSeconds              7113.0
Name: 18522, dtype: object
Valdosta
 Age                          55
M/F                           M
City                   Valdosta
State                        GA
Country                     USA
Half            0 days 01:46:17
40K             0 days 03:27:18
Pace                    0:08:20
TotalSeconds            12438.0
HalfSeconds              6377.0
Name: 18670, dtype: object
Valencia
 Age                          35
M/F                           M
City                   Valencia
State                        CA
Country                     USA
Half            0 days 01:29:30
40K             0 days 03:11:22
Pace                    0:07:48
TotalSeconds            11482.0
HalfSeconds              5370.0
Name: 5925, dtype: object
Valhalla
 Age                          24
M/F                           M
City                   Valhalla
State                        NY
Country                     USA
Half            0 days 01:28:33
40K             0 days 03:00:46
Pace                    0:07:17
TotalSeconds            10846.0
HalfSeconds              5313.0
Name: 3283, dtype: object
Valle Mosso - Bi
 Age                           47
M/F                            M
City            Valle Mosso - Bi
State                        NaN
Country                      ITA
Half             0 days 01:29:49
40K              0 days 03:00:05
Pace                     0:07:18
TotalSeconds             10805.0
HalfSeconds               5389.0
Name: 4744, dtype: object
Vallensbaek Strand
 Age                             48
M/F                              F
City            Vallensbaek Strand
State                          NaN
Country                        DEN
Half               0 days 01:57:14
40K                0 days 04:02:01
Pace                       0:09:47
TotalSeconds               14521.0
HalfSeconds                 7034.0
Name: 24028, dtype: object
Vallentuna
 Age                          41
M/F                           F
City                 Vallentuna
State                       NaN
Country                     SWE
Half            0 days 01:45:37
40K             0 days 03:36:20
Pace                    0:08:42
TotalSeconds            12980.0
HalfSeconds              6337.0
Name: 18704, dtype: object
Valley Center
 Age                          27
M/F                           M
City              Valley Center
State                        KS
Country                     USA
Half            0 days 01:24:22
40K             0 days 02:44:23
Pace                    0:06:40
TotalSeconds             9863.0
HalfSeconds              5062.0
Name: 691, dtype: object
Valley Cottage
 Age                          52
M/F                           F
City             Valley Cottage
State                        NY
Country                     USA
Half            0 days 02:00:50
40K             0 days 04:17:27
Pace                    0:10:26
TotalSeconds            15447.0
HalfSeconds              7250.0
Name: 23356, dtype: object
Valley Falls
 Age                          62
M/F                           M
City               Valley Falls
State                        NY
Country                     USA
Half            0 days 01:47:18
40K             0 days 03:27:57
Pace                    0:08:24
TotalSeconds            12477.0
HalfSeconds              6438.0
Name: 20064, dtype: object
Valley Glen
 Age                          35
M/F                           M
City                Valley Glen
State                        CA
Country                     USA
Half            0 days 01:34:38
40K             0 days 03:24:59
Pace                    0:08:18
TotalSeconds            12299.0
HalfSeconds              5678.0
Name: 1264, dtype: object
Valley Grove
 Age                          29
M/F                           M
City               Valley Grove
State                        WV
Country                     USA
Half            0 days 01:26:03
40K             0 days 02:48:07
Pace                    0:06:49
TotalSeconds            10087.0
HalfSeconds              5163.0
Name: 1808, dtype: object
Valley Stream
 Age                          24
M/F                           M
City              Valley Stream
State                        NY
Country                     USA
Half            0 days 01:14:19
40K             0 days 02:49:45
Pace                    0:06:51
TotalSeconds            10185.0
HalfSeconds              4459.0
Name: 184, dtype: object
Valmontone
 Age                          61
M/F                           M
City                 Valmontone
State                       NaN
Country                     ITA
Half            0 days 02:08:07
40K             0 days 04:29:37
Pace                    0:10:52
TotalSeconds            16177.0
HalfSeconds              7687.0
Name: 14345, dtype: object
Valparaiso
 Age                          23
M/F                           M
City                 Valparaiso
State                        IN
Country                     USA
Half            0 days 01:28:06
40K             0 days 02:52:06
Pace                    0:06:57
TotalSeconds            10326.0
HalfSeconds              5286.0
Name: 198, dtype: object
Valparsiso
 Age                          66
M/F                           M
City                 Valparsiso
State                        IN
Country                     USA
Half            0 days 01:50:47
40K             0 days 03:45:51
Pace                    0:09:14
TotalSeconds            13551.0
HalfSeconds              6647.0
Name: 21758, dtype: object
Valrico
 Age                          24
M/F                           M
City                    Valrico
State                        FL
Country                     USA
Half            0 days 01:23:08
40K             0 days 02:57:47
Pace                    0:07:16
TotalSeconds            10667.0
HalfSeconds              4988.0
Name: 1148, dtype: object
Vancouver
 Age                          31
M/F                           M
City                  Vancouver
State                        BC
Country                     CAN
Half            0 days 01:17:13
40K             0 days 02:29:29
Pace                    0:06:03
TotalSeconds             8969.0
HalfSeconds              4633.0
Name: 1155, dtype: object
Vandalia
 Age                          50
M/F                           M
City                   Vandalia
State                        OH
Country                     USA
Half            0 days 01:37:09
40K             0 days 03:12:23
Pace                    0:07:47
TotalSeconds            11543.0
HalfSeconds              5829.0
Name: 13198, dtype: object
Vanderhoof
 Age                          54
M/F                           M
City                 Vanderhoof
State                        BC
Country                     CAN
Half            0 days 01:30:20
40K             0 days 03:06:36
Pace                    0:07:40
TotalSeconds            11196.0
HalfSeconds              5420.0
Name: 6028, dtype: object
Vandoeuvre Les Nancy
 Age                               56
M/F                                M
City            Vandoeuvre Les Nancy
State                            NaN
Country                          FRA
Half                 0 days 02:11:37
40K                  0 days 04:22:43
Pace                         0:10:36
TotalSeconds                 15763.0
HalfSeconds                   7897.0
Name: 31579, dtype: object
Vandyne
 Age                          34
M/F                           F
City                    Vandyne
State                        WI
Country                     USA
Half            0 days 01:44:30
40K             0 days 03:23:49
Pace                    0:08:13
TotalSeconds            12229.0
HalfSeconds              6270.0
Name: 12826, dtype: object
Vanlose
 Age                          31
M/F                           M
City                    Vanlose
State                       NaN
Country                     DEN
Half            0 days 01:28:58
40K             0 days 02:51:53
Pace                    0:06:58
TotalSeconds            10313.0
HalfSeconds              5338.0
Name: 3389, dtype: object
Vantaa
 Age                          49
M/F                           M
City                     Vantaa
State                       NaN
Country                     FIN
Half            0 days 01:42:02
40K             0 days 03:23:47
Pace                    0:08:14
TotalSeconds            12227.0
HalfSeconds              6122.0
Name: 10407, dtype: object
Varberg
 Age                          43
M/F                           M
City                    Varberg
State                       NaN
Country                     SWE
Half            0 days 01:31:56
40K             0 days 03:09:16
Pace                    0:07:39
TotalSeconds            11356.0
HalfSeconds              5516.0
Name: 5492, dtype: object
Varennes
 Age                          35
M/F                           M
City                   Varennes
State                        QC
Country                     CAN
Half            0 days 01:32:17
40K             0 days 03:04:32
Pace                    0:07:28
TotalSeconds            11072.0
HalfSeconds              5537.0
Name: 6653, dtype: object
Varna
 Age                          56
M/F                           F
City                      Varna
State                        IL
Country                     USA
Half            0 days 01:57:40
40K             0 days 03:59:30
Pace                    0:09:41
TotalSeconds            14370.0
HalfSeconds              7060.0

Name: 25471, dtype: object
Vashon
 Age                          65
M/F                           M
City                     Vashon
State                        WA
Country                     USA
Half            0 days 01:50:01
40K             0 days 03:51:16
Pace                    0:09:22
TotalSeconds            13876.0
HalfSeconds              6601.0
Name: 18500, dtype: object
Vashon Island
 Age                          57
M/F                           M
City              Vashon Island
State                        WA
Country                     USA
Half            0 days 01:45:24
40K             0 days 03:17:23
Pace                    0:07:56
TotalSeconds            11843.0
HalfSeconds              6324.0
Name: 18134, dtype: object
Vass
 Age                          62
M/F                           M
City                       Vass
State                        NC
Country                     USA
Half            0 days 01:47:40
40K             0 days 03:26:42
Pace                    0:08:19
TotalSeconds            12402.0
HalfSeconds              6460.0
Name: 20150, dtype: object
Vasteras
 Age                          34
M/F                           M
City                   Vasteras
State                       NaN
Country                     SWE
Half            0 days 01:30:34
40K             0 days 03:04:11
Pace                    0:07:24
TotalSeconds            11051.0
HalfSeconds              5434.0
Name: 735, dtype: object
Vaudreuil Sur Le Lac
 Age                               41
M/F                                M
City            Vaudreuil Sur Le Lac
State                             QC
Country                          CAN
Half                 0 days 01:33:17
40K                  0 days 03:10:55
Pace                         0:07:46
TotalSeconds                 11455.0
HalfSeconds                   5597.0
Name: 3598, dtype: object
Vaudreuil-Dorion
 Age                           45
M/F                            F
City            Vaudreuil-Dorion
State                         QC
Country                      CAN
Half             0 days 02:03:38
40K              0 days 03:58:09
Pace                     0:09:33
TotalSeconds             14289.0
HalfSeconds               7418.0
Name: 23261, dtype: object
Vaughan
 Age                          54
M/F                           F
City                    Vaughan
State                        ON
Country                     CAN
Half            0 days 01:56:45
40K             0 days 03:53:43
Pace                    0:09:26
TotalSeconds            14023.0
HalfSeconds              7005.0
Name: 23310, dtype: object
Veggiano - Pd
 Age                          52
M/F                           F
City              Veggiano - Pd
State                       NaN
Country                     ITA
Half            0 days 02:00:19
40K             0 days 04:05:44
Pace                    0:09:56
TotalSeconds            14744.0
HalfSeconds              7219.0
Name: 23003, dtype: object
Vejle
 Age                          47
M/F                           M
City                      Vejle
State                       NaN
Country                     DEN
Half            0 days 01:36:24
40K             0 days 03:19:31
Pace                    0:08:04
TotalSeconds            11971.0
HalfSeconds              5784.0
Name: 7187, dtype: object
Velletri
 Age                          46
M/F                           M
City                   Velletri
State                       NaN
Country                     ITA
Half            0 days 01:41:07
40K             0 days 03:22:36
Pace                    0:08:15
TotalSeconds            12156.0
HalfSeconds              6067.0
Name: 11753, dtype: object
Velletri (roma)
 Age                          57
M/F                           M
City            Velletri (roma)
State                       NaN
Country                     ITA
Half            0 days 01:33:25
40K             0 days 03:12:53
Pace                    0:07:51
TotalSeconds            11573.0
HalfSeconds              5605.0
Name: 6198, dtype: object
Venetia
 Age                          40
M/F                           M
City                    Venetia
State                        PA
Country                     USA
Half            0 days 01:36:23
40K             0 days 03:17:48
Pace                    0:08:02
TotalSeconds            11868.0
HalfSeconds              5783.0
Name: 7321, dtype: object
Venice
 Age                          43
M/F                           M
City                     Venice
State                        CA
Country                     USA
Half            0 days 01:23:07
40K             0 days 02:56:08
Pace                    0:07:11
TotalSeconds            10568.0
HalfSeconds              4987.0
Name: 835, dtype: object
Ventura
 Age                          29
M/F                           F
City                    Ventura
State                        CA
Country                     USA
Half            0 days 01:39:42
40K             0 days 03:11:59
Pace                    0:07:44
TotalSeconds            11519.0
HalfSeconds              5982.0
Name: 12500, dtype: object
Verdi
 Age                          21
M/F                           M
City                      Verdi
State                        NV
Country                     USA
Half            0 days 01:24:38
40K             0 days 02:44:08
Pace                    0:06:37
TotalSeconds             9848.0
HalfSeconds              5078.0
Name: 1008, dtype: object
Verdun
 Age                          32
M/F                           M
City                     Verdun
State                        QC
Country                     CAN
Half            0 days 01:18:34
40K             0 days 02:34:11
Pace                    0:06:14
TotalSeconds             9251.0
HalfSeconds              4714.0
Name: 660, dtype: object
Vergas
 Age                          50
M/F                           F
City                     Vergas
State                        MN
Country                     USA
Half            0 days 01:52:37
40K             0 days 03:50:23
Pace                    0:09:20
TotalSeconds            13823.0
HalfSeconds              6757.0
Name: 23519, dtype: object
Vernal
 Age                          44
M/F                           M
City                     Vernal
State                        UT
Country                     USA
Half            0 days 01:32:40
40K             0 days 03:03:23
Pace                    0:07:28
TotalSeconds            11003.0
HalfSeconds              5560.0
Name: 7628, dtype: object
Verner Ontario
 Age                          60
M/F                           M
City             Verner Ontario
State                        ON
Country                     CAN
Half            0 days 01:57:21
40K             0 days 04:03:28
Pace                    0:09:51
TotalSeconds            14608.0
HalfSeconds              7041.0
Name: 21871, dtype: object
Vernon
 Age                          42
M/F                           F
City                     Vernon
State                        NY
Country                     USA
Half            0 days 01:51:53
40K             0 days 03:42:39
Pace                    0:09:01
TotalSeconds            13359.0
HalfSeconds              6713.0
Name: 20758, dtype: object
Vernon Hills
 Age                          23
M/F                           M
City               Vernon Hills
State                        IL
Country                     USA
Half            0 days 01:17:16
40K             0 days 02:29:11
Pace                    0:06:01
TotalSeconds             8951.0
HalfSeconds              4636.0
Name: 461, dtype: object
Vernonia
 Age                          26
M/F                           F
City                   Vernonia
State                        OR
Country                     USA
Half            0 days 01:46:56
40K             0 days 03:30:02
Pace                    0:08:28
TotalSeconds            12602.0
HalfSeconds              6416.0
Name: 15201, dtype: object
Vero Beach
 Age                          30
M/F                           F
City                 Vero Beach
State                        FL
Country                     USA
Half            0 days 01:44:24
40K             0 days 03:23:26
Pace                    0:08:12
TotalSeconds            12206.0
HalfSeconds              6264.0
Name: 17432, dtype: object
Verona
 Age                          46
M/F                           M
City                     Verona
State                        NJ
Country                     USA
Half            0 days 01:36:42
40K             0 days 03:14:21
Pace                    0:07:55
TotalSeconds            11661.0
HalfSeconds              5802.0
Name: 9405, dtype: object
Vestal
 Age                          41
M/F                           M
City                     Vestal
State                        NY
Country                     USA
Half            0 days 01:38:57
40K             0 days 03:17:41
Pace                    0:08:01
TotalSeconds            11861.0
HalfSeconds              5937.0
Name: 8132, dtype: object

Vestavia
 Age                          33
M/F                           F
City                   Vestavia
State                        AL
Country                     USA
Half            0 days 01:36:29
40K             0 days 03:08:12
Pace                    0:07:34
TotalSeconds            11292.0
HalfSeconds              5789.0
Name: 5346, dtype: object
Vestavia Hills
 Age                          41
M/F                           M
City             Vestavia Hills
State                        AL
Country                     USA
Half            0 days 01:32:55
40K             0 days 03:22:03
Pace                    0:08:13
TotalSeconds            12123.0
HalfSeconds              5575.0
Name: 6129, dtype: object
Viby J
 Age                          40
M/F                           M
City                     Viby J
State                       NaN
Country                     DEN
Half            0 days 01:19:08
40K             0 days 02:38:05
Pace                    0:06:25
TotalSeconds             9485.0
HalfSeconds              4748.0
Name: 1785, dtype: object
Vicenza
 Age                          42
M/F                           M
City                    Vicenza
State                       NaN
Country                     ITA
Half            0 days 01:30:01
40K             0 days 03:02:45
Pace                    0:07:23
TotalSeconds            10965.0
HalfSeconds              5401.0
Name: 7007, dtype: object
Vicksburg
 Age                          51
M/F                           F
City                  Vicksburg
State                        MS
Country                     USA
Half            0 days 01:54:04
40K             0 days 03:34:53
Pace                    0:08:38
TotalSeconds            12893.0
HalfSeconds              6844.0
Name: 23371, dtype: object
Victor
 Age                          42
M/F                           M
City                     Victor
State                        NY
Country                     USA
Half            0 days 01:47:01
40K             0 days 03:27:33
Pace                    0:08:22
TotalSeconds            12453.0
HalfSeconds              6421.0
Name: 30577, dtype: object
Victoria
 Age                          47
M/F                           M
City                   Victoria
State                        BC
Country                     CAN
Half            0 days 01:26:22
40K             0 days 02:46:17
Pace                    0:06:42
TotalSeconds             9977.0
HalfSeconds              5182.0
Name: 2754, dtype: object
Victoriaville
 Age                          55
M/F                           M
City              Victoriaville
State                        QC
Country                     CAN
Half            0 days 01:53:43
40K             0 days 03:57:19
Pace                    0:09:39
TotalSeconds            14239.0
HalfSeconds              6823.0
Name: 16571, dtype: object
Victorville
 Age                          41
M/F                           F
City                Victorville
State                        CA
Country                     USA
Half            0 days 01:41:08
40K             0 days 03:20:11
Pace                    0:08:04
TotalSeconds            12011.0
HalfSeconds              6068.0
Name: 18386, dtype: object
Vienna
 Age                          48
M/F                           M
City                     Vienna
State                        VA
Country                     USA
Half            0 days 01:24:34
40K             0 days 02:44:27
Pace                    0:06:37
TotalSeconds             9867.0
HalfSeconds              5074.0
Name: 1048, dtype: object
Viens
 Age                          44
M/F                           F
City                      Viens
State                       NaN
Country                     FRA
Half            0 days 01:48:18
40K             0 days 03:47:50
Pace                    0:09:18
TotalSeconds            13670.0
HalfSeconds              6498.0
Name: 19669, dtype: object
Viera
 Age                          38
M/F                           M
City                      Viera
State                        FL
Country                     USA
Half            0 days 01:19:48
40K             0 days 02:43:29
Pace                    0:06:38
TotalSeconds             9809.0
HalfSeconds              4788.0
Name: 601, dtype: object
Vigevano
 Age                          40
M/F                           M
City                   Vigevano
State                       NaN
Country                     ITA
Half            0 days 01:37:24
40K             0 days 03:43:19
Pace                    0:08:59
TotalSeconds            13399.0
HalfSeconds              5844.0
Name: 3954, dtype: object
Vila Velha
 Age                          46
M/F                           M
City                 Vila Velha
State                       NaN
Country                     BRA
Half            0 days 01:40:01
40K             0 days 03:28:43
Pace                    0:08:30
TotalSeconds            12523.0
HalfSeconds              6001.0
Name: 9893, dtype: object
Vilafranca Del Penedes
 Age                                 43
M/F                                  M
City            Vilafranca Del Penedes
State                              NaN
Country                            ESP
Half                   0 days 01:42:29
40K                    0 days 03:35:37
Pace                           0:08:45
TotalSeconds                   12937.0
HalfSeconds                     6149.0
Name: 6832, dtype: object
Vilar Formoso
 Age                          43
M/F                           F
City              Vilar Formoso
State                       NaN
Country                     POR
Half            0 days 01:39:18
40K             0 days 03:20:21
Pace                    0:08:05
TotalSeconds            12021.0
HalfSeconds              5958.0
Name: 9710, dtype: object
Villa Guerrero, Edo De Mex.
 Age                                      43
M/F                                       M
City            Villa Guerrero, Edo De Mex.
State                                   NaN
Country                                 MEX
Half                        0 days 01:31:42
40K                         0 days 02:59:48
Pace                                0:07:14
TotalSeconds                        10788.0
HalfSeconds                          5502.0
Name: 8938, dtype: object
Villa Park
 Age                          39
M/F                           F
City                 Villa Park
State                        IL
Country                     USA
Half            0 days 01:32:49
40K             0 days 02:59:33
Pace                    0:07:16
TotalSeconds            10773.0
HalfSeconds              5569.0
Name: 13089, dtype: object
Villanueva De La Cañada
 Age                                  40
M/F                                   M
City            Villanueva De La Cañada
State                               NaN
Country                             ESP
Half                    0 days 01:26:32
40K                     0 days 02:53:48
Pace                            0:07:03
TotalSeconds                    10428.0
HalfSeconds                      5192.0
Name: 2260, dtype: object
Villaviciosa De Odon-Madrid
 Age                                      25
M/F                                       M
City            Villaviciosa De Odon-Madrid
State                                   NaN
Country                                 ESP
Half                        0 days 02:14:12
40K                         0 days 04:31:11
Pace                                0:10:52
TotalSeconds                        16271.0
HalfSeconds                          8052.0
Name: 30979, dtype: object
Ville Mont Royal
 Age                           44
M/F                            M
City            Ville Mont Royal
State                         QC
Country                      CAN
Half             0 days 01:34:46
40K              0 days 03:13:27
Pace                     0:07:53
TotalSeconds             11607.0
HalfSeconds               5686.0
Name: 6674, dtype: object
Villongo - Bergamo
 Age                             33
M/F                              F
City            Villongo - Bergamo
State                          NaN
Country                        ITA
Half               0 days 01:56:28
40K                0 days 03:46:35
Pace                       0:09:06
TotalSeconds               13595.0
HalfSeconds                 6988.0
Name: 31441, dtype: object
Villorba
 Age                          42
M/F                           M
City                   Villorba
State                       NaN
Country                     ITA
Half            0 days 01:31:45
40K             0 days 03:04:35
Pace                    0:07:29
TotalSeconds            11075.0
HalfSeconds              5505.0
Name: 4319, dtype: object
Vilnius
 Age                          40
M/F                           M
City                    Vilnius
State                       NaN
Country                     LTU
Half            0 days 01:21:41
40K             0 days 02:40:08
Pace                    0:06:29
TotalSeconds             9608.0
HalfSeconds              4901.0
Name: 1094, dtype: object
Vilvoorde
 Age                          56
M/F                           M
City                  Vilvoorde
State                       NaN
Country                     BEL
Half            0 days 02:41:05
40K             0 days 05:13:55
Pace                    0:12:39
TotalSeconds            18835.0
HalfSeconds              9665.0
Name: 31284, dtype: object
Vina Del Mar
 Age                          27
M/F                           M
City               Vina Del Mar
State                       NaN
Country                     CHI
Half            0 days 01:24:22
40K             0 days 02:42:32
Pace                    0:06:34
TotalSeconds             9752.0
HalfSeconds              5062.0
Name: 1896, dtype: object
Vincennes
 Age                          52
M/F                           M
City                  Vincennes
State                       NaN
Country                     FRA
Half            0 days 01:40:56
40K             0 days 03:29:50
Pace                    0:08:30
TotalSeconds            12590.0
HalfSeconds              6056.0
Name: 19348, dtype: object
Vineyard Haven
 Age                          58
M/F                           M
City             Vineyard Haven
State                        MA
Country                     USA
Half            0 days 01:48:34
40K             0 days 03:40:29
Pace                    0:08:58
TotalSeconds            13229.0
HalfSeconds              6514.0
Name: 16756, dtype: object
Virginia Beach
 Age                          43
M/F                           M
City             Virginia Beach
State                        VA
Country                     USA
Half            0 days 01:26:46
40K             0 days 02:59:15
Pace                    0:07:15
TotalSeconds            10755.0
HalfSeconds              5206.0
Name: 2008, dtype: object
Virgnia Beach
 Age                          41
M/F                           M
City              Virgnia Beach
State                        VA
Country                     USA
Half            0 days 01:44:09
40K             0 days 03:21:59
Pace                    0:08:11
TotalSeconds            12119.0
HalfSeconds              6249.0
Name: 5448, dtype: object
Virum
 Age                          59
M/F                           M
City                      Virum
State                       NaN
Country                     DEN
Half            0 days 02:01:08
40K             0 days 03:52:11
Pace                    0:09:21
TotalSeconds            13931.0
HalfSeconds              7268.0
Name: 30354, dtype: object
Visalia
 Age                          39
M/F                           F
City                    Visalia
State                        CA
Country                     USA
Half            0 days 01:48:36
40K             0 days 03:29:40
Pace                    0:08:28
TotalSeconds            12580.0
HalfSeconds              6516.0
Name: 19456, dtype: object
Vista
 Age                          57
M/F                           M
City                      Vista
State                        CA
Country                     USA
Half            0 days 01:42:06
40K             0 days 03:25:12
Pace                    0:08:18
TotalSeconds            12312.0
HalfSeconds              6126.0
Name: 12418, dtype: object
Vitorchiano
 Age                          45
M/F                           M
City                Vitorchiano
State                       NaN
Country                     ITA
Half            0 days 01:42:24
40K             0 days 03:21:20
Pace                    0:08:10
TotalSeconds            12080.0
HalfSeconds              6144.0
Name: 12214, dtype: object
Vitoria
 Age                          46
M/F                           M
City                    Vitoria
State                       NaN
Country                     BRA
Half            0 days 01:37:12
40K             0 days 03:15:42
Pace                    0:08:13
TotalSeconds            11742.0
HalfSeconds              5832.0
Name: 12657, dtype: object
Vitoria Gasteiz (Alava)
 Age                                  53
M/F                                   M
City            Vitoria Gasteiz (Alava)
State                               NaN
Country                             ESP
Half                    0 days 01:53:56
40K                     0 days 03:54:26
Pace                            0:09:30
TotalSeconds                    14066.0
HalfSeconds                      6836.0
Name: 31636, dtype: object
Vitoria Gasteiz (alava)
 Age                                  49
M/F                                   F
City            Vitoria Gasteiz (alava)
State                               NaN
Country                             ESP
Half                    0 days 02:19:25
40K                     0 days 04:22:21
Pace                            0:10:32
TotalSeconds                    15741.0
HalfSeconds                      8365.0
Name: 31671, dtype: object
Vitoria-Gasteiz
 Age                          53
M/F                           M
City            Vitoria-Gasteiz
State                       NaN
Country                     ESP
Half            0 days 01:13:20
40K             0 days 02:22:44
Pace                    0:05:46
TotalSeconds             8564.0
HalfSeconds              4400.0
Name: 84, dtype: object
Vitoria-Gasteiz (alava)
 Age                                  52
M/F                                   M
City            Vitoria-Gasteiz (alava)
State                               NaN
Country                             ESP
Half                    0 days 01:32:54
40K                     0 days 03:01:47
Pace                            0:07:22
TotalSeconds                    10907.0
HalfSeconds                      5574.0
Name: 5957, dtype: object
Vitória Da Conquista
 Age                               30
M/F                                M
City            Vitória Da Conquista
State                            NaN
Country                          BRA
Half                 0 days 01:29:38
40K                  0 days 03:02:41
Pace                         0:07:25
TotalSeconds                 10961.0
HalfSeconds                   5378.0
Name: 4439, dtype: object
Viña Del Mar
 Age                          57
M/F                           M
City               Viña Del Mar
State                       NaN
Country                     CHI
Half            0 days 01:42:23
40K             0 days 03:19:50
Pace                    0:08:05
TotalSeconds            11990.0
HalfSeconds              6143.0
Name: 16976, dtype: object
Vlaeberg
 Age                          31
M/F                           M
City                   Vlaeberg
State                       NaN
Country                     RSA
Half            0 days 01:29:42
40K             0 days 02:57:30
Pace                    0:07:11
TotalSeconds            10650.0
HalfSeconds              5382.0
Name: 3669, dtype: object

Volcano
 Age                          39
M/F                           F
City                    Volcano
State                        HI
Country                     USA
Half            0 days 01:39:44
40K             0 days 03:19:53
Pace                    0:08:05
TotalSeconds            11993.0
HalfSeconds              5984.0
Name: 10623, dtype: object
Volo
 Age                          35
M/F                           M
City                       Volo
State                        IL
Country                     USA
Half            0 days 01:29:27
40K             0 days 02:54:39
Pace                    0:07:05
TotalSeconds            10479.0
HalfSeconds              5367.0
Name: 3541, dtype: object
Voorhees
 Age                          47
M/F                           M
City                   Voorhees
State                        NJ
Country                     USA
Half            0 days 01:37:18
40K             0 days 03:11:48
Pace                    0:07:46
TotalSeconds            11508.0
HalfSeconds              5838.0
Name: 9300, dtype: object
W. Sussex
 Age                          41
M/F                           M
City                  W. Sussex
State                       NaN
Country                     GBR
Half            0 days 01:39:50
40K             0 days 03:29:40
Pace                    0:08:25
TotalSeconds            12580.0
HalfSeconds              5990.0
Name: 31465, dtype: object
Waban
 Age                          38
M/F                           M
City                      Waban
State                        MA
Country                     USA
Half            0 days 01:25:17
40K             0 days 02:46:55
Pace                    0:06:44
TotalSeconds            10015.0
HalfSeconds              5117.0
Name: 1927, dtype: object
Wabush
 Age                          45
M/F                           F
City                     Wabush
State                        NL
Country                     CAN
Half            0 days 01:48:29
40K             0 days 03:31:30
Pace                    0:08:31
TotalSeconds            12690.0
HalfSeconds              6509.0
Name: 14160, dtype: object
Waco
 Age                          24
M/F                           F
City                       Waco
State                        TX
Country                     USA
Half            0 days 01:37:55
40K             0 days 03:12:05
Pace                    0:07:44
TotalSeconds            11525.0
HalfSeconds              5875.0
Name: 10465, dtype: object
Waconia
 Age                          44
M/F                           M
City                    Waconia
State                        MN
Country                     USA
Half            0 days 01:32:39
40K             0 days 03:03:00
Pace                    0:07:24
TotalSeconds            10980.0
HalfSeconds              5559.0
Name: 7142, dtype: object
Wading River
 Age                          42
M/F                           F
City               Wading River
State                        NY
Country                     USA
Half            0 days 01:42:41
40K             0 days 03:32:14
Pace                    0:08:35
TotalSeconds            12734.0
HalfSeconds              6161.0
Name: 15004, dtype: object
Wadsworth
 Age                          35
M/F                           M
City                  Wadsworth
State                        OH
Country                     USA
Half            0 days 01:34:33
40K             0 days 03:10:31
Pace                    0:07:40
TotalSeconds            11431.0
HalfSeconds              5673.0
Name: 1562, dtype: object
Waedenswil
 Age                          62
M/F                           F
City                 Waedenswil
State                       NaN
Country                     SUI
Half            0 days 01:59:10
40K             0 days 03:54:01
Pace                    0:09:27
TotalSeconds            14041.0
HalfSeconds              7150.0
Name: 25374, dtype: object
Wahoo
 Age                          60
M/F                           M
City                      Wahoo
State                        NE
Country                     USA
Half            0 days 01:51:51
40K             0 days 03:37:32
Pace                    0:08:46
TotalSeconds            13052.0
HalfSeconds              6711.0
Name: 20531, dtype: object
Waianae
 Age                          38
M/F                           M
City                    Waianae
State                        HI
Country                     USA
Half            0 days 02:31:05
40K             0 days 05:34:41
Pace                    0:13:24
TotalSeconds            20081.0
HalfSeconds              9065.0
Name: 26129, dtype: object
Wailuku
 Age                          37
M/F                           F
City                    Wailuku
State                        HI
Country                     USA
Half            0 days 01:42:17
40K             0 days 03:20:19
Pace                    0:08:04
TotalSeconds            12019.0
HalfSeconds              6137.0
Name: 14582, dtype: object
Waite Park
 Age                          53
M/F                           F
City                 Waite Park
State                        MN
Country                     USA
Half            0 days 01:52:15
40K             0 days 04:01:37
Pace                    0:09:45
TotalSeconds            14497.0
HalfSeconds              6735.0
Name: 22357, dtype: object
Wake Forest
 Age                          35
M/F                           F
City                Wake Forest
State                        NC
Country                     USA
Half            0 days 01:44:41
40K             0 days 03:18:03
Pace                    0:07:57
TotalSeconds            11883.0
HalfSeconds              6281.0
Name: 18116, dtype: object
Wakefield
 Age                          28
M/F                           F
City                  Wakefield
State                        RI
Country                     USA
Half            0 days 01:28:43
40K             0 days 02:53:58
Pace                    0:07:01
TotalSeconds            10438.0
HalfSeconds              5323.0
Name: 2006, dtype: object
Wakeman
 Age                          38
M/F                           F
City                    Wakeman
State                        OH
Country                     USA
Half            0 days 01:44:45
40K             0 days 03:30:42
Pace                    0:08:28
TotalSeconds            12642.0
HalfSeconds              6285.0
Name: 17116, dtype: object
Walchwil
 Age                          55
M/F                           M
City                   Walchwil
State                       NaN
Country                     SUI
Half            0 days 01:53:56
40K             0 days 03:59:52
Pace                    0:09:44
TotalSeconds            14392.0
HalfSeconds              6836.0
Name: 17950, dtype: object
Walden
 Age                          54
M/F                           M
City                     Walden
State                        NY
Country                     USA
Half            0 days 01:39:02
40K             0 days 03:16:18
Pace                    0:07:54
TotalSeconds            11778.0
HalfSeconds              5942.0
Name: 6526, dtype: object
Waldorf
 Age                          43
M/F                           M
City                    Waldorf
State                        MD
Country                     USA
Half            0 days 02:11:17
40K             0 days 04:12:17
Pace                    0:10:08
TotalSeconds            15137.0
HalfSeconds              7877.0
Name: 28641, dtype: object
Waldwick
 Age                          41
M/F                           F
City                   Waldwick
State                        NJ
Country                     USA
Half            0 days 01:52:11
40K             0 days 03:31:34
Pace                    0:08:31
TotalSeconds            12694.0
HalfSeconds              6731.0
Name: 17637, dtype: object
Wales
 Age                          40
M/F                           M
City                      Wales
State                        ME
Country                     USA
Half            0 days 01:31:45
40K             0 days 03:09:33
Pace                    0:07:45
TotalSeconds            11373.0
HalfSeconds              5505.0
Name: 4805, dtype: object
Walferdange
 Age                          64
M/F                           F
City                Walferdange
State                       NaN
Country                     LUX
Half            0 days 01:46:22
40K             0 days 03:26:35
Pace                    0:08:20
TotalSeconds            12395.0
HalfSeconds              6382.0
Name: 19963, dtype: object

Wall
 Age                          43
M/F                           F
City                       Wall
State                        NJ
Country                     USA
Half            0 days 01:40:09
40K             0 days 03:16:10
Pace                    0:07:55
TotalSeconds            11770.0
HalfSeconds              6009.0
Name: 11010, dtype: object
Wall Township
 Age                          44
M/F                           F
City              Wall Township
State                        NJ
Country                     USA
Half            0 days 01:56:42
40K             0 days 03:47:07
Pace                    0:09:09
TotalSeconds            13627.0
HalfSeconds              7002.0
Name: 21323, dtype: object
Walla Walla
 Age                          41
M/F                           M
City                Walla Walla
State                        WA
Country                     USA
Half            0 days 01:31:12
40K             0 days 02:58:03
Pace                    0:07:11
TotalSeconds            10683.0
HalfSeconds              5472.0
Name: 8540, dtype: object
Wallaceburg
 Age                          47
M/F                           M
City                Wallaceburg
State                        ON
Country                     CAN
Half            0 days 01:38:58
40K             0 days 03:17:23
Pace                    0:07:59
TotalSeconds            11843.0
HalfSeconds              5938.0
Name: 12216, dtype: object
Wallenhorst
 Age                          49
M/F                           M
City                Wallenhorst
State                       NaN
Country                     GER
Half            0 days 01:40:46
40K             0 days 03:32:13
Pace                    0:08:34
TotalSeconds            12733.0
HalfSeconds              6046.0
Name: 10124, dtype: object
Wallingford
 Age                          44
M/F                           F
City                Wallingford
State                        PA
Country                     USA
Half            0 days 01:42:55
40K             0 days 03:22:34
Pace                    0:08:13
TotalSeconds            12154.0
HalfSeconds              6175.0
Name: 14327, dtype: object
Walnut
 Age                          34
M/F                           M
City                     Walnut
State                        CA
Country                     USA
Half            0 days 01:34:25
40K             0 days 03:06:20
Pace                    0:07:31
TotalSeconds            11180.0
HalfSeconds              5665.0
Name: 2847, dtype: object
Walnut Creek
 Age                          27
M/F                           M
City               Walnut Creek
State                        CA
Country                     USA
Half            0 days 01:23:09
40K             0 days 02:47:51
Pace                    0:06:48
TotalSeconds            10071.0
HalfSeconds              4989.0
Name: 1484, dtype: object
Walnutport
 Age                          48
M/F                           F
City                 Walnutport
State                        PA
Country                     USA
Half            0 days 01:57:09
40K             0 days 03:54:37
Pace                    0:09:30
TotalSeconds            14077.0
HalfSeconds              7029.0
Name: 24001, dtype: object
Walpole
 Age                          25
M/F                           M
City                    Walpole
State                        MA
Country                     USA
Half            0 days 01:21:14
40K             0 days 02:56:03
Pace                    0:07:13
TotalSeconds            10563.0
HalfSeconds              4874.0
Name: 797, dtype: object
Waltham
 Age                          47
M/F                           M
City                    Waltham
State                        MA
Country                     USA
Half            0 days 01:26:39
40K             0 days 02:50:02
Pace                    0:06:55
TotalSeconds            10202.0
HalfSeconds              5199.0
Name: 1423, dtype: object
Walton
 Age                          44
M/F                           M
City                     Walton
State                        KY
Country                     USA
Half            0 days 01:39:35
40K             0 days 03:13:44
Pace                    0:07:48
TotalSeconds            11624.0
HalfSeconds              5975.0
Name: 3279, dtype: object
Wappingers Falls
 Age                           30
M/F                            M
City            Wappingers Falls
State                         NY
Country                      USA
Half             0 days 01:18:50
40K              0 days 02:48:12
Pace                     0:06:47
TotalSeconds             10092.0
HalfSeconds               4730.0
Name: 534, dtype: object
Waquoit
 Age                          44
M/F                           M
City                    Waquoit
State                        MA
Country                     USA
Half            0 days 01:32:40
40K             0 days 03:10:34
Pace                    0:07:42
TotalSeconds            11434.0
HalfSeconds              5560.0
Name: 5856, dtype: object
Warden
 Age                          30
M/F                           F
City                     Warden
State                        WA
Country                     USA
Half            0 days 01:37:22
40K             0 days 03:13:23
Pace                    0:07:47
TotalSeconds            11603.0
HalfSeconds              5842.0
Name: 16114, dtype: object
Ware
 Age                          36
M/F                           M
City                       Ware
State                       NaN
Country                     GBR
Half            0 days 01:25:39
40K             0 days 02:46:52
Pace                    0:06:44
TotalSeconds            10012.0
HalfSeconds              5139.0
Name: 4958, dtype: object
Warner
 Age                          44
M/F                           M
City                     Warner
State                        SD
Country                     USA
Half            0 days 01:34:21
40K             0 days 03:29:21
Pace                    0:08:24
TotalSeconds            12561.0
HalfSeconds              5661.0
Name: 6096, dtype: object
Warner Robins
 Age                          30
M/F                           M
City              Warner Robins
State                        GA
Country                     USA
Half            0 days 01:36:42
40K             0 days 03:10:55
Pace                    0:07:44
TotalSeconds            11455.0
HalfSeconds              5802.0
Name: 4244, dtype: object
Warrandyte, Vic
 Age                          41
M/F                           F
City            Warrandyte, Vic
State                       NaN
Country                     AUS
Half            0 days 01:43:51
40K             0 days 03:22:16
Pace                    0:08:10
TotalSeconds            12136.0
HalfSeconds              6231.0
Name: 20525, dtype: object
Warren
 Age                          23
M/F                           M
City                     Warren
State                        MI
Country                     USA
Half            0 days 01:25:23
40K             0 days 02:58:52
Pace                    0:07:18
TotalSeconds            10732.0
HalfSeconds              5123.0
Name: 656, dtype: object
Warrensburg
 Age                          30
M/F                           M
City                Warrensburg
State                        MO
Country                     USA
Half            0 days 01:29:19
40K             0 days 03:00:57
Pace                    0:07:22
TotalSeconds            10857.0
HalfSeconds              5359.0
Name: 4452, dtype: object
Warrenville
 Age                          40
M/F                           F
City                Warrenville
State                        IL
Country                     USA
Half            0 days 01:57:30
40K             0 days 03:49:08
Pace                    0:09:15
TotalSeconds            13748.0
HalfSeconds              7050.0
Name: 21369, dtype: object
Warrington
 Age                          57
M/F                           M
City                 Warrington
State                       NaN
Country                     GBR
Half            0 days 01:35:24
40K             0 days 03:09:10
Pace                    0:07:42
TotalSeconds            11350.0
HalfSeconds              5724.0
Name: 9236, dtype: object
Warrior
 Age                          41
M/F                           F
City                    Warrior
State                        AL
Country                     USA
Half            0 days 01:49:30
40K             0 days 03:34:14
Pace                    0:08:40
TotalSeconds            12854.0
HalfSeconds              6570.0
Name: 20963, dtype: object
Warrnambool
 Age                          29
M/F                           M
City                Warrnambool
State                       NaN
Country                     AUS
Half            0 days 01:29:24
40K             0 days 03:11:00
Pace                    0:07:48
TotalSeconds            11460.0
HalfSeconds              5364.0
Name: 4020, dtype: object
Warsaw
 Age                          39
M/F                           M
City                     Warsaw
State                       NaN
Country                     POL
Half            0 days 01:23:53
40K             0 days 02:39:57
Pace                    0:06:27
TotalSeconds             9597.0
HalfSeconds              5033.0
Name: 5149, dtype: object
Warszawa
 Age                          47
M/F                           M
City                   Warszawa
State                       NaN
Country                     POL
Half            0 days 01:20:43
40K             0 days 02:39:22
Pace                    0:06:26
TotalSeconds             9562.0
HalfSeconds              4843.0
Name: 560, dtype: object
Warwick
 Age                          33
M/F                           M
City                    Warwick
State                        RI
Country                     USA
Half            0 days 01:23:35
40K             0 days 02:52:43
Pace                    0:06:59
TotalSeconds            10363.0
HalfSeconds              5015.0
Name: 299, dtype: object
Wasaga Beach
 Age                          45
M/F                           M
City               Wasaga Beach
State                        ON
Country                     CAN
Half            0 days 01:33:45
40K             0 days 03:21:02
Pace                    0:08:19
TotalSeconds            12062.0
HalfSeconds              5625.0
Name: 8873, dtype: object
Washington
 Age                          29
M/F                           M
City                 Washington
State                        DC
Country                     USA
Half            0 days 01:14:00
40K             0 days 02:23:21
Pace                    0:05:47
TotalSeconds             8601.0
HalfSeconds              4440.0
Name: 122, dtype: object
Washington Dc
 Age                          49
M/F                           M
City              Washington Dc
State                        DC
Country                     USA
Half            0 days 02:15:55
40K             0 days 04:54:05
Pace                    0:11:51
TotalSeconds            17645.0
HalfSeconds              8155.0
Name: 27429, dtype: object
Washington Grove
 Age                           57
M/F                            M
City            Washington Grove
State                         MD
Country                      USA
Half             0 days 01:43:32
40K              0 days 03:39:51
Pace                     0:09:00
TotalSeconds             13191.0
HalfSeconds               6212.0
Name: 11549, dtype: object
Washington Twp
 Age                          46
M/F                           M
City             Washington Twp
State                        MI
Country                     USA
Half            0 days 01:51:07
40K             0 days 03:36:22
Pace                    0:08:42
TotalSeconds            12982.0
HalfSeconds              6667.0
Name: 11167, dtype: object
Washington, Dc
 Age                          35
M/F                           F
City             Washington, Dc
State                        DC
Country                     USA
Half            0 days 01:50:16
40K             0 days 03:38:59
Pace                    0:08:52
TotalSeconds            13139.0
HalfSeconds              6616.0
Name: 19401, dtype: object
Washougal
 Age                          40
M/F                           F
City                  Washougal
State                        WA
Country                     USA
Half            0 days 01:41:27
40K             0 days 03:21:46
Pace                    0:08:12
TotalSeconds            12106.0
HalfSeconds              6087.0
Name: 13963, dtype: object
Wasilla
 Age                          39
M/F                           M
City                    Wasilla
State                        AK
Country                     USA
Half            0 days 01:28:23
40K             0 days 03:17:38
Pace                    0:08:03
TotalSeconds            11858.0
HalfSeconds              5303.0
Name: 2023, dtype: object
Wassenaar
 Age                          46
M/F                           M
City                  Wassenaar
State                       NaN
Country                     NED
Half            0 days 01:40:27
40K             0 days 03:27:41
Pace                    0:08:27
TotalSeconds            12461.0
HalfSeconds              6027.0
Name: 11810, dtype: object
Watauga
 Age                          40
M/F                           F
City                    Watauga
State                        TX
Country                     USA
Half            0 days 02:03:09
40K             0 days 03:55:17
Pace                    0:09:28
TotalSeconds            14117.0
HalfSeconds              7389.0
Name: 19918, dtype: object
Waterbury
 Age                          29
M/F                           F
City                  Waterbury
State                        VT
Country                     USA
Half            0 days 01:41:21
40K             0 days 03:18:36
Pace                    0:08:00
TotalSeconds            11916.0
HalfSeconds              6081.0
Name: 10895, dtype: object
Waterbury Center
 Age                           40
M/F                            F
City            Waterbury Center
State                         VT
Country                      USA
Half             0 days 01:50:22
40K              0 days 03:52:20
Pace                     0:09:26
TotalSeconds             13940.0
HalfSeconds               6622.0
Name: 21188, dtype: object
Waterdown
 Age                          43
M/F                           M
City                  Waterdown
State                        ON
Country                     CAN
Half            0 days 01:28:12
40K             0 days 02:52:54
Pace                    0:06:59
TotalSeconds            10374.0
HalfSeconds              5292.0
Name: 5653, dtype: object
Waterford
 Age                          24
M/F                           M
City                  Waterford
State                        MI
Country                     USA
Half            0 days 01:26:24
40K             0 days 02:52:41
Pace                    0:06:59
TotalSeconds            10361.0
HalfSeconds              5184.0

Name: 4190, dtype: object
Waterloo
 Age                          27
M/F                           M
City                   Waterloo
State                        SC
Country                     USA
Half            0 days 01:25:51
40K             0 days 02:44:54
Pace                    0:06:39
TotalSeconds             9894.0
HalfSeconds              5151.0
Name: 2129, dtype: object
Watertown
 Age                          41
M/F                           M
City                  Watertown
State                        MA
Country                     USA
Half            0 days 01:22:16
40K             0 days 02:42:01
Pace                    0:06:35
TotalSeconds             9721.0
HalfSeconds              4936.0
Name: 1292, dtype: object
Waterville
 Age                          40
M/F                           M
City                 Waterville
State                        ME
Country                     USA
Half            0 days 01:29:42
40K             0 days 02:54:25
Pace                    0:07:03
TotalSeconds            10465.0
HalfSeconds              5382.0
Name: 2450, dtype: object
Watham
 Age                          25
M/F                           M
City                     Watham
State                        MA
Country                     USA
Half            0 days 02:32:40
40K             0 days 05:12:44
Pace                    0:12:30
TotalSeconds            18764.0
HalfSeconds              9160.0
Name: 30589, dtype: object
Watkins Glen
 Age                          40
M/F                           F
City               Watkins Glen
State                        NY
Country                     USA
Half            0 days 01:52:06
40K             0 days 03:37:24
Pace                    0:08:46
TotalSeconds            13044.0
HalfSeconds              6726.0
Name: 20744, dtype: object
Watsonville
 Age                          45
M/F                           M
City                Watsonville
State                        CA
Country                     USA
Half            0 days 01:34:22
40K             0 days 03:08:39
Pace                    0:07:39
TotalSeconds            11319.0
HalfSeconds              5662.0
Name: 6374, dtype: object
Wattsburg
 Age                          51
M/F                           F
City                  Wattsburg
State                        PA
Country                     USA
Half            0 days 01:57:35
40K             0 days 03:41:53
Pace                    0:08:55
TotalSeconds            13313.0
HalfSeconds              7055.0
Name: 21887, dtype: object
Waukee
 Age                          47
M/F                           M
City                     Waukee
State                        IA
Country                     USA
Half            0 days 01:42:54
40K             0 days 03:27:05
Pace                    0:08:23
TotalSeconds            12425.0
HalfSeconds              6174.0
Name: 12642, dtype: object
Waukegan
 Age                          46
M/F                           M
City                   Waukegan
State                        IL
Country                     USA
Half            0 days 01:41:43
40K             0 days 03:18:13
Pace                    0:08:01
TotalSeconds            11893.0
HalfSeconds              6103.0
Name: 9944, dtype: object
Waukesha
 Age                          40
M/F                           M
City                   Waukesha
State                        WI
Country                     USA
Half            0 days 01:21:35
40K             0 days 02:52:00
Pace                    0:06:57
TotalSeconds            10320.0
HalfSeconds              4895.0
Name: 618, dtype: object
Waunakee
 Age                          61
M/F                           M
City                   Waunakee
State                        WI
Country                     USA
Half            0 days 01:53:46
40K             0 days 04:03:45
Pace                    0:09:51
TotalSeconds            14625.0
HalfSeconds              6826.0
Name: 22347, dtype: object
Waupaca
 Age                          60
M/F                           M
City                    Waupaca
State                        WI
Country                     USA
Half            0 days 01:59:31
40K             0 days 04:00:54
Pace                    0:09:46
TotalSeconds            14454.0
HalfSeconds              7171.0
Name: 23118, dtype: object
Wauregan
 Age                          52
M/F                           M
City                   Wauregan
State                        CT
Country                     USA
Half            0 days 01:43:13
40K             0 days 03:17:59
Pace                    0:07:58
TotalSeconds            11879.0
HalfSeconds              6193.0
Name: 12877, dtype: object
Wausau
 Age                          38
M/F                           F
City                     Wausau
State                        WI
Country                     USA
Half            0 days 01:36:19
40K             0 days 03:07:21
Pace                    0:07:33
TotalSeconds            11241.0
HalfSeconds              5779.0
Name: 10303, dtype: object
Wauseon
 Age                          50
M/F                           F
City                    Wauseon
State                        OH
Country                     USA
Half            0 days 01:54:02
40K             0 days 04:10:06
Pace                    0:10:16
TotalSeconds            15006.0
HalfSeconds              6842.0
Name: 24550, dtype: object
Wauwatosa
 Age                          35
M/F                           M
City                  Wauwatosa
State                        WI
Country                     USA
Half            0 days 01:19:16
40K             0 days 02:39:09
Pace                    0:06:27
TotalSeconds             9549.0
HalfSeconds              4756.0
Name: 509, dtype: object
Waverly
 Age                          44
M/F                           M
City                    Waverly
State                        IA
Country                     USA
Half            0 days 01:29:15
40K             0 days 02:53:44
Pace                    0:06:59
TotalSeconds            10424.0
HalfSeconds              5355.0
Name: 6282, dtype: object
Waxahachie
 Age                          34
M/F                           M
City                 Waxahachie
State                        TX
Country                     USA
Half            0 days 01:29:37
40K             0 days 02:56:30
Pace                    0:07:08
TotalSeconds            10590.0
HalfSeconds              5377.0
Name: 4947, dtype: object
Waxhaw
 Age                          50
M/F                           M
City                     Waxhaw
State                        NC
Country                     USA
Half            0 days 01:39:04
40K             0 days 03:11:32
Pace                    0:07:42
TotalSeconds            11492.0
HalfSeconds              5944.0
Name: 11942, dtype: object
Wayland
 Age                          47
M/F                           M
City                    Wayland
State                        MA
Country                     USA
Half            0 days 01:37:22
40K             0 days 03:07:38
Pace                    0:07:35
TotalSeconds            11258.0
HalfSeconds              5842.0
Name: 11321, dtype: object
Wayne
 Age                          38
M/F                           M
City                      Wayne
State                        PA
Country                     USA
Half            0 days 01:24:28
40K             0 days 02:54:25
Pace                    0:07:07
TotalSeconds            10465.0
HalfSeconds              5068.0
Name: 2910, dtype: object
Waynesboro
 Age                          63
M/F                           M
City                 Waynesboro
State                        VA
Country                     USA
Half            0 days 02:07:01
40K             0 days 04:11:25
Pace                    0:10:11
TotalSeconds            15085.0
HalfSeconds              7621.0
Name: 22498, dtype: object
Wayzata
 Age                          25
M/F                           M
City                    Wayzata
State                        MN
Country                     USA
Half            0 days 01:29:37
40K             0 days 02:50:51
Pace                    0:06:54
TotalSeconds            10251.0
HalfSeconds              5377.0
Name: 3829, dtype: object
Weare
 Age                          41
M/F                           F
City                      Weare
State                        NH
Country                     USA
Half            0 days 01:54:09
40K             0 days 03:40:12
Pace                    0:08:53
TotalSeconds            13212.0
HalfSeconds              6849.0
Name: 20794, dtype: object
Weatherford
 Age                          45
M/F                           M
City                Weatherford
State                        TX
Country                     USA
Half            0 days 01:42:00
40K             0 days 03:36:14
Pace                    0:08:48
TotalSeconds            12974.0
HalfSeconds              6120.0
Name: 10831, dtype: object
Weatogue
 Age                          31
M/F                           F
City                   Weatogue
State                        CT
Country                     USA
Half            0 days 02:09:11
40K             0 days 04:27:26
Pace                    0:10:49
TotalSeconds            16046.0
HalfSeconds              7751.0
Name: 16696, dtype: object
Weaverville
 Age                          46
M/F                           M
City                Weaverville
State                        NC
Country                     USA
Half            0 days 01:30:25
40K             0 days 03:01:09
Pace                    0:07:26
TotalSeconds            10869.0
HalfSeconds              5425.0
Name: 3646, dtype: object

Webster
 Age                          33
M/F                           M
City                    Webster
State                        NY
Country                     USA
Half            0 days 01:25:34
40K             0 days 02:55:12
Pace                    0:07:11
TotalSeconds            10512.0
HalfSeconds              5134.0
Name: 3295, dtype: object
Weddington
 Age                          39
M/F                           M
City                 Weddington
State                        NC
Country                     USA
Half            0 days 01:40:58
40K             0 days 03:09:02
Pace                    0:07:34
TotalSeconds            11342.0
HalfSeconds              6058.0
Name: 6097, dtype: object
Weehawken
 Age                          61
M/F                           M
City                  Weehawken
State                        NJ
Country                     USA
Half            0 days 01:49:13
40K             0 days 03:31:10
Pace                    0:08:29
TotalSeconds            12670.0
HalfSeconds              6553.0
Name: 18014, dtype: object
Weiningen
 Age                          36
M/F                           M
City                  Weiningen
State                       NaN
Country                     SUI
Half            0 days 01:47:15
40K             0 days 03:32:58
Pace                    0:08:37
TotalSeconds            12778.0
HalfSeconds              6435.0
Name: 31785, dtype: object
Weirton
 Age                          59
M/F                           F
City                    Weirton
State                        WV
Country                     USA
Half            0 days 02:03:41
40K             0 days 03:57:22
Pace                    0:09:33
TotalSeconds            14242.0
HalfSeconds              7421.0
Name: 25001, dtype: object
Weldon Spring
 Age                          51
M/F                           F
City              Weldon Spring
State                        MO
Country                     USA
Half            0 days 02:07:04
40K             0 days 04:32:08
Pace                    0:11:04
TotalSeconds            16328.0
HalfSeconds              7624.0
Name: 22598, dtype: object
Welland
 Age                          51
M/F                           M
City                    Welland
State                        ON
Country                     CAN
Half            0 days 01:50:58
40K             0 days 03:42:23
Pace                    0:08:59
TotalSeconds            13343.0
HalfSeconds              6658.0
Name: 13671, dtype: object
Wellesley
 Age                          49
M/F                           M
City                  Wellesley
State                        MA
Country                     USA
Half            0 days 01:33:19
40K             0 days 03:07:49
Pace                    0:07:37
TotalSeconds            11269.0
HalfSeconds              5599.0
Name: 7021, dtype: object
Wellesley Hills
 Age                          40
M/F                           M
City            Wellesley Hills
State                        MA
Country                     USA
Half            0 days 01:42:45
40K             0 days 03:41:18
Pace                    0:08:56
TotalSeconds            13278.0
HalfSeconds              6165.0
Name: 7415, dtype: object
Wellington
 Age                          44
M/F                           M
City                 Wellington
State                       NaN
Country                     NZL
Half            0 days 01:28:15
40K             0 days 02:59:15
Pace                    0:07:16
TotalSeconds            10755.0
HalfSeconds              5295.0
Name: 3185, dtype: object
Wells
 Age                          36
M/F                           M
City                      Wells
State                        ME
Country                     USA
Half            0 days 02:25:56
40K             0 days 04:40:47
Pace                    0:11:16
TotalSeconds            16847.0
HalfSeconds              8756.0
Name: 27480, dtype: object
Wellsburg
 Age                          65
M/F                           M
City                  Wellsburg
State                        WV
Country                     USA
Half            0 days 01:57:48
40K             0 days 03:47:19
Pace                    0:09:10
TotalSeconds            13639.0
HalfSeconds              7068.0
Name: 22962, dtype: object
Wellsville
 Age                          33
M/F                           M
City                 Wellsville
State                        PA
Country                     USA
Half            0 days 01:28:30
40K             0 days 02:58:44
Pace                    0:07:17
TotalSeconds            10724.0
HalfSeconds              5310.0
Name: 2607, dtype: object
Wellton
 Age                          57
M/F                           F
City                    Wellton
State                        AZ
Country                     USA
Half            0 days 02:01:47
40K             0 days 04:08:58
Pace                    0:10:02
TotalSeconds            14938.0
HalfSeconds              7307.0
Name: 24934, dtype: object
Welwyn Garden City
 Age                             55
M/F                              M
City            Welwyn Garden City
State                          NaN
Country                        GBR
Half               0 days 01:54:44
40K                0 days 04:08:39
Pace                       0:10:05
TotalSeconds               14919.0
HalfSeconds                 6884.0
Name: 12255, dtype: object
Wembley Downs
 Age                          45
M/F                           M
City              Wembley Downs
State                       NaN
Country                     AUS
Half            0 days 01:29:37
40K             0 days 03:05:58
Pace                    0:07:31
TotalSeconds            11158.0
HalfSeconds              5377.0
Name: 9715, dtype: object
Wendell
 Age                          32
M/F                           F
City                    Wendell
State                        MA
Country                     USA
Half            0 days 01:29:41
40K             0 days 02:54:23
Pace                    0:07:02
TotalSeconds            10463.0
HalfSeconds              5381.0
Name: 8381, dtype: object
Wenham
 Age                          21
M/F                           M
City                     Wenham
State                        MA
Country                     USA
Half            0 days 01:30:08
40K             0 days 03:05:46
Pace                    0:07:32
TotalSeconds            11146.0
HalfSeconds              5408.0
Name: 4932, dtype: object
Wenshan Dist., Taipei City
 Age                                     62
M/F                                      M
City            Wenshan Dist., Taipei City
State                                  NaN
Country                                TWN
Half                       0 days 01:36:10
40K                        0 days 03:14:32
Pace                               0:07:54
TotalSeconds                       11672.0
HalfSeconds                         5770.0
Name: 8509, dtype: object
Wenzhou, Zhejiang
 Age                            40
M/F                             M
City            Wenzhou, Zhejiang
State                         NaN
Country                       CHN
Half              0 days 01:27:49
40K               0 days 02:58:22
Pace                      0:07:15
TotalSeconds              10702.0
HalfSeconds                5269.0
Name: 2897, dtype: object
Wermatswil
 Age                          61
M/F                           M
City                 Wermatswil
State                       NaN
Country                     SUI
Half            0 days 01:58:34
40K             0 days 03:47:32
Pace                    0:09:10
TotalSeconds            13652.0
HalfSeconds              7114.0
Name: 17918, dtype: object
Weslaco
 Age                          38
M/F                           F
City                    Weslaco
State                        TX
Country                     USA
Half            0 days 01:49:27
40K             0 days 03:37:00
Pace                    0:08:46
TotalSeconds            13020.0
HalfSeconds              6567.0
Name: 18890, dtype: object
Wesley Chapel
 Age                          29
M/F                           F
City              Wesley Chapel
State                        FL
Country                     USA
Half            0 days 01:29:55
40K             0 days 02:58:42
Pace                    0:07:12
TotalSeconds            10722.0
HalfSeconds              5395.0
Name: 5051, dtype: object
Wesley Hills
 Age                          58
M/F                           M
City               Wesley Hills
State                        NY
Country                     USA
Half            0 days 01:44:32
40K             0 days 03:40:35
Pace                    0:09:04
TotalSeconds            13235.0
HalfSeconds              6272.0
Name: 19925, dtype: object
West Allis
 Age                          27
M/F                           M
City                 West Allis
State                        WI
Country                     USA
Half            0 days 01:18:22
40K             0 days 02:32:11
Pace                    0:06:09
TotalSeconds             9131.0
HalfSeconds              4702.0
Name: 685, dtype: object
West Babylon
 Age                          46
M/F                           M
City               West Babylon
State                        NY
Country                     USA
Half            0 days 01:35:10
40K             0 days 03:10:04
Pace                    0:07:41
TotalSeconds            11404.0
HalfSeconds              5710.0
Name: 2965, dtype: object
West Barnstable
 Age                          40
M/F                           F
City            West Barnstable
State                        MA
Country                     USA
Half            0 days 01:39:38
40K             0 days 03:19:20
Pace                    0:08:04
TotalSeconds            11960.0
HalfSeconds              5978.0
Name: 16529, dtype: object
West Bend
 Age                          41
M/F                           F
City                  West Bend
State                        WI
Country                     USA
Half            0 days 01:29:04
40K             0 days 03:00:06
Pace                    0:07:18
TotalSeconds            10806.0
HalfSeconds              5344.0
Name: 3974, dtype: object
West Bloomfield
 Age                          43
M/F                           M
City            West Bloomfield
State                        MI
Country                     USA
Half            0 days 01:32:41
40K             0 days 03:00:13
Pace                    0:07:19
TotalSeconds            10813.0
HalfSeconds              5561.0
Name: 6824, dtype: object
West Boylston
 Age                          50
M/F                           M
City              West Boylston
State                        MA
Country                     USA
Half            0 days 01:32:49
40K             0 days 03:09:17
Pace                    0:07:40
TotalSeconds            11357.0
HalfSeconds              5569.0
Name: 4507, dtype: object
West Bridgewater
 Age                           39
M/F                            F
City            West Bridgewater
State                         MA
Country                      USA
Half             0 days 01:56:28
40K              0 days 03:45:00
Pace                     0:09:05
TotalSeconds             13500.0
HalfSeconds               6988.0
Name: 32048, dtype: object
West Caldwell
 Age                          22
M/F                           F
City              West Caldwell
State                        NJ
Country                     USA
Half            0 days 01:58:17
40K             0 days 04:02:46
Pace                    0:09:44
TotalSeconds            14566.0
HalfSeconds              7097.0
Name: 16883, dtype: object
West Chazy
 Age                          38
M/F                           M
City                 West Chazy
State                        NY
Country                     USA
Half            0 days 01:19:11
40K             0 days 02:43:08
Pace                    0:06:37
TotalSeconds             9788.0
HalfSeconds              4751.0
Name: 419, dtype: object
West Chester
 Age                          43
M/F                           M
City               West Chester
State                        PA
Country                     USA
Half            0 days 01:29:52
40K             0 days 02:59:10
Pace                    0:07:13
TotalSeconds            10750.0
HalfSeconds              5392.0
Name: 6579, dtype: object
West Chesterfield
 Age                            41
M/F                             M
City            West Chesterfield
State                          NH
Country                       USA
Half              0 days 01:41:10
40K               0 days 03:29:34
Pace                      0:08:31
TotalSeconds              12574.0
HalfSeconds                6070.0
Name: 6965, dtype: object
West Chicago
 Age                          44
M/F                           M
City               West Chicago
State                        IL
Country                     USA
Half            0 days 01:41:29
40K             0 days 03:34:56
Pace                    0:08:42
TotalSeconds            12896.0
HalfSeconds              6089.0
Name: 8548, dtype: object
West Columbia
 Age                          38
M/F                           M
City              West Columbia
State                        SC
Country                     USA
Half            0 days 01:28:54
40K             0 days 02:58:15
Pace                    0:07:16
TotalSeconds            10695.0
HalfSeconds              5334.0
Name: 6062, dtype: object
West Covina
 Age                          57
M/F                           M
City                West Covina
State                        CA
Country                     USA
Half            0 days 01:41:00
40K             0 days 03:40:51
Pace                    0:09:07
TotalSeconds            13251.0
HalfSeconds              6060.0
Name: 7570, dtype: object
West Des Moines
 Age                          37
M/F                           M
City            West Des Moines
State                        IA
Country                     USA
Half            0 days 01:27:23
40K             0 days 03:09:39
Pace                    0:07:45
TotalSeconds            11379.0
HalfSeconds              5243.0
Name: 1506, dtype: object
West Dundee
 Age                          24
M/F                           F
City                West Dundee
State                        IL
Country                     USA
Half            0 days 01:35:17
40K             0 days 03:03:58
Pace                    0:07:27
TotalSeconds            11038.0
HalfSeconds              5717.0
Name: 9602, dtype: object
West Fargo
 Age                          32
M/F                           M
City                 West Fargo
State                        ND
Country                     USA
Half            0 days 01:33:53
40K             0 days 03:09:28
Pace                    0:07:43
TotalSeconds            11368.0
HalfSeconds              5633.0
Name: 5112, dtype: object
West Gardiner
 Age                          33
M/F                           F
City              West Gardiner
State                        ME
Country                     USA
Half            0 days 01:43:34
40K             0 days 03:14:40
Pace                    0:07:49
TotalSeconds            11680.0
HalfSeconds              6214.0
Name: 14687, dtype: object
West Grove
 Age                          45
M/F                           F
City                 West Grove
State                        PA
Country                     USA
Half            0 days 01:49:00
40K             0 days 03:32:19
Pace                    0:08:35
TotalSeconds            12739.0
HalfSeconds              6540.0
Name: 22366, dtype: object
West Harrison
 Age                          35
M/F                           F
City              West Harrison
State                        IN
Country                     USA
Half            0 days 01:52:29
40K             0 days 03:43:52
Pace                    0:09:03
TotalSeconds            13432.0
HalfSeconds              6749.0
Name: 20265, dtype: object
West Hartford
 Age                          34
M/F                           M
City              West Hartford
State                        CT
Country                     USA
Half            0 days 01:27:12
40K             0 days 02:53:34
Pace                    0:07:02
TotalSeconds            10414.0
HalfSeconds              5232.0
Name: 1219, dtype: object
West Hartland
 Age                          51
M/F                           F
City              West Hartland
State                        CT
Country                     USA
Half            0 days 01:53:56
40K             0 days 03:40:50
Pace                    0:08:53
TotalSeconds            13250.0
HalfSeconds              6836.0
Name: 21637, dtype: object
West Haven
 Age                          48
M/F                           M
City                 West Haven
State                        CT
Country                     USA
Half            0 days 01:40:18
40K             0 days 03:23:22
Pace                    0:08:16
TotalSeconds            12202.0
HalfSeconds              6018.0
Name: 5436, dtype: object
West Hempstead
 Age                          26
M/F                           F
City             West Hempstead
State                        NY
Country                     USA
Half            0 days 01:40:35
40K             0 days 03:30:07
Pace                    0:08:30
TotalSeconds            12607.0
HalfSeconds              6035.0
Name: 17545, dtype: object
West Hollywood
 Age                          40
M/F                           M
City             West Hollywood
State                        CA
Country                     USA
Half            0 days 02:17:46
40K             0 days 04:19:12
Pace                    0:10:25
TotalSeconds            15552.0
HalfSeconds              8266.0
Name: 27766, dtype: object
West Islip
 Age                          31
M/F                           M
City                 West Islip
State                        NY
Country                     USA
Half            0 days 01:25:44
40K             0 days 03:00:03
Pace                    0:07:16
TotalSeconds            10803.0
HalfSeconds              5144.0
Name: 2009, dtype: object
West Jordan
 Age                          39
M/F                           M
City                West Jordan
State                        UT
Country                     USA
Half            0 days 01:29:31
40K             0 days 03:01:20
Pace                    0:07:20
TotalSeconds            10880.0
HalfSeconds              5371.0
Name: 6384, dtype: object
West Kingston
 Age                          47
M/F                           M
City              West Kingston
State                        RI
Country                     USA
Half            0 days 01:37:28
40K             0 days 03:18:10
Pace                    0:08:13
TotalSeconds            11890.0
HalfSeconds              5848.0
Name: 11698, dtype: object
West Lafayette
 Age                          22
M/F                           F
City             West Lafayette
State                        IN
Country                     USA
Half            0 days 01:36:25
40K             0 days 03:09:16
Pace                    0:07:39
TotalSeconds            11356.0
HalfSeconds              5785.0
Name: 7436, dtype: object
West Lake Hills
 Age                          35
M/F                           M
City            West Lake Hills
State                        TX
Country                     USA
Half            0 days 01:24:47
40K             0 days 02:42:02
Pace                    0:06:32
TotalSeconds             9722.0
HalfSeconds              5087.0
Name: 1902, dtype: object

West Lakes Shore, Sa
 Age                               45
M/F                                F
City            West Lakes Shore, Sa
State                            NaN
Country                          AUS
Half                 0 days 01:52:46
40K                  0 days 03:48:08
Pace                         0:09:13
TotalSeconds                 13688.0
HalfSeconds                   6766.0
Name: 20614, dtype: object
West Lawn
 Age                          40
M/F                           F
City                  West Lawn
State                        PA
Country                     USA
Half            0 days 01:45:56
40K             0 days 03:32:33
Pace                    0:08:36
TotalSeconds            12753.0
HalfSeconds              6356.0
Name: 19293, dtype: object
West Lebanon
 Age                          28
M/F                           F
City               West Lebanon
State                        NH
Country                     USA
Half            0 days 01:44:06
40K             0 days 03:18:42
Pace                    0:07:59
TotalSeconds            11922.0
HalfSeconds              6246.0
Name: 16461, dtype: object
West Linn
 Age                          46
M/F                           M
City                  West Linn
State                        OR
Country                     USA
Half            0 days 01:18:10
40K             0 days 02:36:39
Pace                    0:06:20
TotalSeconds             9399.0
HalfSeconds              4690.0
Name: 637, dtype: object
West Long Branch
 Age                           46
M/F                            M
City            West Long Branch
State                         NJ
Country                      USA
Half             0 days 01:22:02
40K              0 days 02:48:20
Pace                     0:06:49
TotalSeconds             10100.0
HalfSeconds               4922.0
Name: 933, dtype: object
West Mifflin
 Age                          38
M/F                           M
City               West Mifflin
State                        PA
Country                     USA
Half            0 days 01:47:42
40K             0 days 03:33:28
Pace                    0:08:33
TotalSeconds            12808.0
HalfSeconds              6462.0
Name: 5229, dtype: object
West Milwaukee
 Age                          35
M/F                           M
City             West Milwaukee
State                        WI
Country                     USA
Half            0 days 01:15:10
40K             0 days 02:33:22
Pace                    0:06:15
TotalSeconds             9202.0
HalfSeconds              4510.0
Name: 125, dtype: object
West Newbury
 Age                          57
M/F                           M
City               West Newbury
State                        MA
Country                     USA
Half            0 days 01:47:58
40K             0 days 03:40:48
Pace                    0:08:54
TotalSeconds            13248.0
HalfSeconds              6478.0
Name: 15010, dtype: object
West Newton
 Age                          37
M/F                           M
City                West Newton
State                        MA
Country                     USA
Half            0 days 01:23:33
40K             0 days 02:54:01
Pace                    0:07:14
TotalSeconds            10441.0
HalfSeconds              5013.0
Name: 1997, dtype: object
West Nyack
 Age                          41
M/F                           F
City                 West Nyack
State                        NY
Country                     USA
Half            0 days 02:01:19
40K             0 days 04:16:12
Pace                    0:10:21
TotalSeconds            15372.0
HalfSeconds              7279.0
Name: 20832, dtype: object
West Olive
 Age                          46
M/F                           F
City                 West Olive
State                        MI
Country                     USA
Half            0 days 01:48:58
40K             0 days 03:28:52
Pace                    0:08:24
TotalSeconds            12532.0
HalfSeconds              6538.0
Name: 19833, dtype: object
West Orange
 Age                          45
M/F                           F
City                West Orange
State                        NJ
Country                     USA
Half            0 days 01:57:49
40K             0 days 04:12:31
Pace                    0:10:13
TotalSeconds            15151.0
HalfSeconds              7069.0
Name: 22769, dtype: object
West Palm Beach
 Age                          47
M/F                           M
City            West Palm Beach
State                        FL
Country                     USA
Half            0 days 01:30:09
40K             0 days 02:58:35
Pace                    0:07:13
TotalSeconds            10715.0
HalfSeconds              5409.0
Name: 9447, dtype: object
West Point
 Age                          53
M/F                           M
City                 West Point
State                        UT
Country                     USA
Half            0 days 01:17:46
40K             0 days 02:32:34
Pace                    0:06:12
TotalSeconds             9154.0
HalfSeconds              4666.0
Name: 517, dtype: object
West Pokot
 Age                          33
M/F                           F
City                 West Pokot
State                       NaN
Country                     KEN
Half            0 days 01:15:33
40K             0 days 02:24:49
Pace                    0:05:52
TotalSeconds             8689.0
HalfSeconds              4533.0
Name: F7, dtype: object
West Richland
 Age                          41
M/F                           F
City              West Richland
State                        WA
Country                     USA
Half            0 days 01:57:25
40K             0 days 03:53:28
Pace                    0:09:25
TotalSeconds            14008.0
HalfSeconds              7045.0
Name: 18915, dtype: object
West Roxbury
 Age                          55
M/F                           M
City               West Roxbury
State                        MA
Country                     USA
Half            0 days 01:28:26
40K             0 days 03:00:02
Pace                    0:07:18
TotalSeconds            10802.0
HalfSeconds              5306.0
Name: 5439, dtype: object
West Sacramento
 Age                          41
M/F                           M
City            West Sacramento
State                        CA
Country                     USA
Half            0 days 01:29:59
40K             0 days 02:52:33
Pace                    0:06:57
TotalSeconds            10353.0
HalfSeconds              5399.0
Name: 4594, dtype: object
West Salem
 Age                          61
M/F                           M
City                 West Salem
State                        OH
Country                     USA
Half            0 days 01:53:37
40K             0 days 03:43:41
Pace                    0:09:01
TotalSeconds            13421.0
HalfSeconds              6817.0
Name: 19243, dtype: object
West Sayville
 Age                          40
M/F                           M
City              West Sayville
State                        NY
Country                     USA
Half            0 days 01:26:23
40K             0 days 02:51:53
Pace                    0:06:58
TotalSeconds            10313.0
HalfSeconds              5183.0
Name: 6721, dtype: object
West Seneca
 Age                          51
M/F                           M
City                West Seneca
State                        NY
Country                     USA
Half            0 days 01:51:12
40K             0 days 04:00:50
Pace                    0:09:50
TotalSeconds            14450.0
HalfSeconds              6672.0
Name: 29669, dtype: object
West Simsbury
 Age                          27
M/F                           F
City              West Simsbury
State                        CT
Country                     USA
Half            0 days 01:41:26
40K             0 days 03:16:39
Pace                    0:07:56
TotalSeconds            11799.0
HalfSeconds              6086.0
Name: 14252, dtype: object
West Springfield
 Age                           41
M/F                            F
City            West Springfield
State                         MA
Country                      USA
Half             0 days 01:54:36
40K              0 days 03:47:16
Pace                     0:09:09
TotalSeconds             13636.0
HalfSeconds               6876.0
Name: 19372, dtype: object
West Stockbridge
 Age                           60
M/F                            F
City            West Stockbridge
State                         MA
Country                      USA
Half             0 days 01:56:03
40K              0 days 03:47:20
Pace                     0:09:14
TotalSeconds             13640.0
HalfSeconds               6963.0
Name: 25247, dtype: object
West Suffield
 Age                          44
M/F                           F
City              West Suffield
State                        CT
Country                     USA
Half            0 days 01:40:39
40K             0 days 03:14:03
Pace                    0:07:50
TotalSeconds            11643.0
HalfSeconds              6039.0
Name: 14931, dtype: object

West Sussex
 Age                          52
M/F                           F
City                West Sussex
State                       NaN
Country                     GBR
Half            0 days 01:53:20
40K             0 days 03:45:56
Pace                    0:09:13
TotalSeconds            13556.0
HalfSeconds              6800.0
Name: 18089, dtype: object
West Tisbury
 Age                          51
M/F                           F
City               West Tisbury
State                        MA
Country                     USA
Half            0 days 01:52:17
40K             0 days 03:41:53
Pace                    0:08:58
TotalSeconds            13313.0
HalfSeconds              6737.0
Name: 16928, dtype: object
West Union
 Age                          53
M/F                           M
City                 West Union
State                        WV
Country                     USA
Half            0 days 01:36:44
40K             0 days 03:09:22
Pace                    0:09:05
TotalSeconds            11362.0
HalfSeconds              5804.0
Name: 10715, dtype: object
West Valley City
 Age                           66
M/F                            M
City            West Valley City
State                         UT
Country                      USA
Half             0 days 01:35:33
40K              0 days 03:05:58
Pace                     0:07:31
TotalSeconds             11158.0
HalfSeconds               5733.0
Name: 6369, dtype: object
West Vancouver
 Age                          55
M/F                           M
City             West Vancouver
State                        BC
Country                     CAN
Half            0 days 01:34:30
40K             0 days 03:04:22
Pace                    0:07:28
TotalSeconds            11062.0
HalfSeconds              5670.0
Name: 8608, dtype: object
West Wareham
 Age                          38
M/F                           F
City               West Wareham
State                        MA
Country                     USA
Half            0 days 01:46:39
40K             0 days 03:32:24
Pace                    0:08:34
TotalSeconds            12744.0
HalfSeconds              6399.0
Name: 19490, dtype: object
West Warwick
 Age                          53
M/F                           M
City               West Warwick
State                        RI
Country                     USA
Half            0 days 01:34:16
40K             0 days 03:04:00
Pace                    0:07:26
TotalSeconds            11040.0
HalfSeconds              5656.0
Name: 12292, dtype: object
West Yarmouth
 Age                          63
M/F                           M
City              West Yarmouth
State                        MA
Country                     USA
Half            0 days 01:51:25
40K             0 days 03:33:59
Pace                    0:08:37
TotalSeconds            12839.0
HalfSeconds              6685.0
Name: 20532, dtype: object
Westborough
 Age                          45
M/F                           M
City                Westborough
State                        MA
Country                     USA
Half            0 days 01:25:26
40K             0 days 02:45:13
Pace                    0:06:40
TotalSeconds             9913.0
HalfSeconds              5126.0
Name: 1992, dtype: object
Westbrook
 Age                          48
M/F                           M
City                  Westbrook
State                        ME
Country                     USA
Half            0 days 01:26:57
40K             0 days 02:47:01
Pace                    0:06:44
TotalSeconds            10021.0
HalfSeconds              5217.0
Name: 3515, dtype: object
Westchester
 Age                          35
M/F                           F
City                Westchester
State                        IL
Country                     USA
Half            0 days 01:56:02
40K             0 days 03:43:33
Pace                    0:09:00
TotalSeconds            13413.0
HalfSeconds              6962.0
Name: 20106, dtype: object
Westerly
 Age                          26
M/F                           F
City                   Westerly
State                        RI
Country                     USA
Half            0 days 01:29:54
40K             0 days 03:14:15
Pace                    0:07:55
TotalSeconds            11655.0
HalfSeconds              5394.0
Name: 10064, dtype: object
Western Springs
 Age                          27
M/F                           F
City            Western Springs
State                        IL
Country                     USA
Half            0 days 01:39:29
40K             0 days 03:20:35
Pace                    0:08:06
TotalSeconds            12035.0
HalfSeconds              5969.0
Name: 11983, dtype: object
Westerville
 Age                          50
M/F                           M
City                Westerville
State                        OH
Country                     USA
Half            0 days 01:32:49
40K             0 days 03:03:47
Pace                    0:07:25
TotalSeconds            11027.0
HalfSeconds              5569.0
Name: 6354, dtype: object
Westfield
 Age                          46
M/F                           M
City                  Westfield
State                        NJ
Country                     USA
Half            0 days 01:25:30
40K             0 days 02:57:51
Pace                    0:07:14
TotalSeconds            10671.0
HalfSeconds              5130.0
Name: 1961, dtype: object
Westfield Center
 Age                           48
M/F                            M
City            Westfield Center
State                         OH
Country                      USA
Half             0 days 01:45:21
40K              0 days 03:21:00
Pace                     0:08:04
TotalSeconds             12060.0
HalfSeconds               6321.0
Name: 10551, dtype: object
Westford
 Age                          23
M/F                           M
City                   Westford
State                        MA
Country                     USA
Half            0 days 01:23:01
40K             0 days 02:43:21
Pace                    0:06:35
TotalSeconds             9801.0
HalfSeconds              4981.0
Name: 1269, dtype: object
Westhampton Beach
 Age                            45
M/F                             M
City            Westhampton Beach
State                          NY
Country                       USA
Half              0 days 02:30:10
40K               0 days 05:03:00
Pace                      0:12:11
TotalSeconds              18180.0
HalfSeconds                9010.0
Name: 31035, dtype: object
Westlake
 Age                          49
M/F                           M
City                   Westlake
State                        OH
Country                     USA
Half            0 days 01:38:11
40K             0 days 03:06:54
Pace                    0:07:31
TotalSeconds            11214.0
HalfSeconds              5891.0
Name: 9204, dtype: object
Westlake Hills
 Age                          63
M/F                           M
City             Westlake Hills
State                        TX
Country                     USA
Half            0 days 02:20:37
40K             0 days 04:56:51
Pace                    0:12:02
TotalSeconds            17811.0
HalfSeconds              8437.0
Name: 27807, dtype: object
Westlake Vilalge
 Age                           69
M/F                            M
City            Westlake Vilalge
State                         CA
Country                      USA
Half             0 days 02:02:28
40K              0 days 04:07:27
Pace                     0:09:57
TotalSeconds             14847.0
HalfSeconds               7348.0
Name: 25302, dtype: object
Westlake Village
 Age                           23
M/F                            M
City            Westlake Village
State                         CA
Country                      USA
Half             0 days 01:31:08
40K              0 days 03:03:52
Pace                     0:07:25
TotalSeconds             11032.0
HalfSeconds               5468.0
Name: 2595, dtype: object
Westland
 Age                          25
M/F                           M
City                   Westland
State                        MI
Country                     USA
Half            0 days 01:28:31
40K             0 days 03:03:23
Pace                    0:07:26
TotalSeconds            11003.0
HalfSeconds              5311.0
Name: 4168, dtype: object
Westmeath
 Age                          46
M/F                           M
City                  Westmeath
State                       NaN
Country                     IRL
Half            0 days 01:39:59
40K             0 days 03:25:47
Pace                    0:08:21
TotalSeconds            12347.0
HalfSeconds              5999.0
Name: 7627, dtype: object
Westminster
 Age                          40
M/F                           M
City                Westminster
State                        CO
Country                     USA
Half            0 days 01:21:09
40K             0 days 02:35:40
Pace                    0:06:16
TotalSeconds             9340.0
HalfSeconds              4869.0
Name: 8575, dtype: object
Westmont
 Age                          28
M/F                           M
City                   Westmont
State                        IL
Country                     USA
Half            0 days 01:34:28
40K             0 days 03:03:55
Pace                    0:07:25
TotalSeconds            11035.0
HalfSeconds              5668.0
Name: 3694, dtype: object
Westmoreland
 Age                          27
M/F                           F
City               Westmoreland
State                        NH
Country                     USA
Half            0 days 01:41:47
40K             0 days 03:12:45
Pace                    0:07:43
TotalSeconds            11565.0
HalfSeconds              6107.0
Name: 16072, dtype: object
Westmount
 Age                          39
M/F                           M
City                  Westmount
State                        QC
Country                     CAN
Half            0 days 01:30:58
40K             0 days 02:55:44
Pace                    0:07:05
TotalSeconds            10544.0
HalfSeconds              5458.0
Name: 6137, dtype: object
Weston
 Age                          24
M/F                           M
City                     Weston
State                        MA
Country                     USA
Half            0 days 01:20:53
40K             0 days 02:36:57
Pace                    0:06:22
TotalSeconds             9417.0
HalfSeconds              4853.0
Name: 2483, dtype: object
Weston-Super-Mare
 Age                            55
M/F                             M
City            Weston-Super-Mare
State                         NaN
Country                       GBR
Half              0 days 02:05:36
40K               0 days 04:08:39
Pace                      0:10:01
TotalSeconds              14919.0
HalfSeconds                7536.0
Name: 14243, dtype: object
Westport
 Age                          30
M/F                           M
City                   Westport
State                        CT
Country                     USA
Half            0 days 01:18:46
40K             0 days 02:35:08
Pace                    0:06:16
TotalSeconds             9308.0
HalfSeconds              4726.0
Name: 1093, dtype: object
Westville
 Age                          54
M/F                           M
City                  Westville
State                        IN
Country                     USA
Half            0 days 01:56:22
40K             0 days 03:42:35
Pace                    0:08:58
TotalSeconds            13355.0
HalfSeconds              6982.0
Name: 14700, dtype: object
Westwood
 Age                          37
M/F                           M
City                   Westwood
State                        MA
Country                     USA
Half            0 days 01:20:19
40K             0 days 02:38:23
Pace                    0:06:26
TotalSeconds             9503.0
HalfSeconds              4819.0
Name: 503, dtype: object
Wethersfield
 Age                          31
M/F                           M
City               Wethersfield
State                        CT
Country                     USA
Half            0 days 01:32:06
40K             0 days 03:08:34
Pace                    0:07:38
TotalSeconds            11314.0
HalfSeconds              5526.0
Name: 4721, dtype: object
Wexford
 Age                          45
M/F                           M
City                    Wexford
State                        PA
Country                     USA
Half            0 days 01:27:45
40K             0 days 02:50:36
Pace                    0:06:53
TotalSeconds            10236.0
HalfSeconds              5265.0
Name: 3446, dtype: object
Weybridge
 Age                          62
M/F                           M
City                  Weybridge
State                       NaN
Country                     GBR
Half            0 days 01:55:00
40K             0 days 03:42:02
Pace                    0:08:57
TotalSeconds            13322.0
HalfSeconds              6900.0
Name: 21345, dtype: object
Weyburn
 Age                          47
M/F                           M
City                    Weyburn
State                        SK
Country                     CAN
Half            0 days 01:35:18
40K             0 days 03:19:23
Pace                    0:08:06
TotalSeconds            11963.0
HalfSeconds              5718.0
Name: 11177, dtype: object
Weymouth
 Age                          21
M/F                           M
City                   Weymouth
State                        MA
Country                     USA
Half            0 days 01:28:17
40K             0 days 02:47:29
Pace                    0:06:44
TotalSeconds            10049.0
HalfSeconds              5297.0
Name: 5330, dtype: object
Weymouth Ma
 Age                          41
M/F                           M
City                Weymouth Ma
State                        MA
Country                     USA
Half            0 days 01:28:21
40K             0 days 02:48:28
Pace                    0:06:47
TotalSeconds            10108.0
HalfSeconds              5301.0
Name: 5079, dtype: object
Wharton
 Age                          46
M/F                           M
City                    Wharton
State                        NJ
Country                     USA
Half            0 days 01:31:30
40K             0 days 02:57:19
Pace                    0:07:10
TotalSeconds            10639.0
HalfSeconds              5490.0
Name: 8937, dtype: object
Wheat Ridge
 Age                          46
M/F                           M
City                Wheat Ridge
State                        CO
Country                     USA
Half            0 days 02:01:21
40K             0 days 03:56:14
Pace                    0:09:27
TotalSeconds            14174.0
HalfSeconds              7281.0
Name: 27774, dtype: object
Wheaton
 Age                          24
M/F                           M
City                    Wheaton
State                        IL
Country                     USA
Half            0 days 01:17:51
40K             0 days 02:34:15
Pace                    0:06:14
TotalSeconds             9255.0
HalfSeconds              4671.0
Name: 335, dtype: object
Wheeling
 Age                          30
M/F                           M
City                   Wheeling
State                        WV
Country                     USA
Half            0 days 01:28:12
40K             0 days 02:51:34
Pace                    0:06:56
TotalSeconds            10294.0
HalfSeconds              5292.0
Name: 3345, dtype: object
Whispering Pines
 Age                           36
M/F                            F
City            Whispering Pines
State                         NC
Country                      USA
Half             0 days 01:32:42
40K              0 days 03:01:31
Pace                     0:07:23
TotalSeconds             10891.0
HalfSeconds               5562.0
Name: 5830, dtype: object
Whistler
 Age                          47
M/F                           F
City                   Whistler
State                        BC
Country                     CAN
Half            0 days 02:10:01
40K             0 days 04:06:59
Pace                    0:09:56
TotalSeconds            14819.0
HalfSeconds              7801.0
Name: 29437, dtype: object
Whitby
 Age                          41
M/F                           M
City                     Whitby
State                        ON
Country                     CAN
Half            0 days 01:24:52
40K             0 days 02:41:19
Pace                    0:06:31
TotalSeconds             9679.0
HalfSeconds              5092.0
Name: 2108, dtype: object

White Bear Lake
 Age                          41
M/F                           M
City            White Bear Lake
State                        MN
Country                     USA
Half            0 days 01:48:32
40K             0 days 03:50:18
Pace                    0:09:21
TotalSeconds            13818.0
HalfSeconds              6512.0
Name: 8851, dtype: object
White Cloud
 Age                          28
M/F                           F
City                White Cloud
State                        MI
Country                     USA
Half            0 days 01:43:36
40K             0 days 03:17:47
Pace                    0:07:59
TotalSeconds            11867.0
HalfSeconds              6216.0
Name: 14408, dtype: object
White Hills
 Age                          54
M/F                           M
City                White Hills
State                       NaN
Country                     AUS
Half            0 days 01:31:18
40K             0 days 03:02:37
Pace                    0:07:25
TotalSeconds            10957.0
HalfSeconds              5478.0
Name: 6713, dtype: object
White House
 Age                          35
M/F                           F
City                White House
State                        TN
Country                     USA
Half            0 days 01:58:15
40K             0 days 04:23:33
Pace                    0:10:45
TotalSeconds            15813.0
HalfSeconds              7095.0
Name: 20169, dtype: object
White Lake
 Age                          45
M/F                           M
City                 White Lake
State                        MI
Country                     USA
Half            0 days 01:33:00
40K             0 days 03:02:14
Pace                    0:07:22
TotalSeconds            10934.0
HalfSeconds              5580.0
Name: 5677, dtype: object
White Plains
 Age                          38
M/F                           F
City               White Plains
State                        NY
Country                     USA
Half            0 days 01:40:46
40K             0 days 03:16:23
Pace                    0:07:54
TotalSeconds            11783.0
HalfSeconds              6046.0
Name: 14286, dtype: object
White Sands
 Age                          33
M/F                           M
City                White Sands
State                        NM
Country                     USA
Half            0 days 01:21:25
40K             0 days 02:44:52
Pace                    0:06:40
TotalSeconds             9892.0
HalfSeconds              4885.0
Name: 757, dtype: object
White Shield
 Age                          27
M/F                           F
City               White Shield
State                        ND
Country                     USA
Half            0 days 01:57:27
40K             0 days 03:57:58
Pace                    0:09:36
TotalSeconds            14278.0
HalfSeconds              7047.0
Name: 20452, dtype: object
Whitecourt
 Age                          47
M/F                           F
City                 Whitecourt
State                        AB
Country                     CAN
Half            0 days 02:09:49
40K             0 days 04:24:08
Pace                    0:10:42
TotalSeconds            15848.0
HalfSeconds              7789.0
Name: 21890, dtype: object
Whitefish Bay
 Age                          49
M/F                           M
City              Whitefish Bay
State                        WI
Country                     USA
Half            0 days 01:43:12
40K             0 days 03:14:34
Pace                    0:07:50
TotalSeconds            11674.0
HalfSeconds              6192.0
Name: 9332, dtype: object
Whitehall
 Age                          41
M/F                           F
City                  Whitehall
State                        PA
Country                     USA
Half            0 days 01:43:02
40K             0 days 03:18:03
Pace                    0:07:58
TotalSeconds            11883.0
HalfSeconds              6182.0
Name: 14078, dtype: object
Whitehorse
 Age                          54
M/F                           M
City                 Whitehorse
State                        YT
Country                     CAN
Half            0 days 01:45:58
40K             0 days 03:26:41
Pace                    0:08:19
TotalSeconds            12401.0
HalfSeconds              6358.0
Name: 8151, dtype: object
Whitehouse
 Age                          26
M/F                           F
City                 Whitehouse
State                        OH
Country                     USA
Half            0 days 01:41:55
40K             0 days 03:16:36
Pace                    0:07:58
TotalSeconds            11796.0
HalfSeconds              6115.0
Name: 14202, dtype: object
Whitehouse Station
 Age                             50
M/F                              M
City            Whitehouse Station
State                           NJ
Country                        USA
Half               0 days 01:40:27
40K                0 days 03:09:48
Pace                       0:07:38
TotalSeconds               11388.0
HalfSeconds                 6027.0
Name: 12222, dtype: object
Whiteriver
 Age                          31
M/F                           M
City                 Whiteriver
State                        AZ
Country                     USA
Half            0 days 01:27:23
40K             0 days 03:03:49
Pace                    0:07:31
TotalSeconds            11029.0
HalfSeconds              5243.0
Name: 2133, dtype: object
Whitesboro
 Age                          28
M/F                           F
City                 Whitesboro
State                        NY
Country                     USA
Half            0 days 02:25:42
40K             0 days 05:27:32
Pace                    0:13:10
TotalSeconds            19652.0
HalfSeconds              8742.0
Name: 26130, dtype: object
Whitestone
 Age                          65
M/F                           M
City                 Whitestone
State                        NY
Country                     USA
Half            0 days 02:08:35
40K             0 days 04:10:53
Pace                    0:10:07
TotalSeconds            15053.0
HalfSeconds              7715.0
Name: 25622, dtype: object
Whitesville
 Age                          52
M/F                           M
City                Whitesville
State                        KY
Country                     USA
Half            0 days 01:46:38
40K             0 days 03:50:01
Pace                    0:09:18
TotalSeconds            13801.0
HalfSeconds              6398.0
Name: 14526, dtype: object
Whitinsville
 Age                          42
M/F                           F
City               Whitinsville
State                        MA
Country                     USA
Half            0 days 01:47:54
40K             0 days 03:34:32
Pace                    0:08:53
TotalSeconds            12872.0
HalfSeconds              6474.0
Name: 21302, dtype: object
Whitman
 Age                          34
M/F                           M
City                    Whitman
State                        MA
Country                     USA
Half            0 days 01:14:13
40K             0 days 02:25:30
Pace                    0:05:53
TotalSeconds             8730.0
HalfSeconds              4453.0
Name: 196, dtype: object
Whitmore
 Age                          58
M/F                           M
City                   Whitmore
State                        CA
Country                     USA
Half            0 days 01:30:10
40K             0 days 02:52:42
Pace                    0:06:57
TotalSeconds            10362.0
HalfSeconds              5410.0
Name: 4536, dtype: object
Whitmore Lake
 Age                          44
M/F                           M
City              Whitmore Lake
State                        MI
Country                     USA
Half            0 days 01:37:53
40K             0 days 03:29:21
Pace                    0:08:29
TotalSeconds            12561.0
HalfSeconds              5873.0
Name: 8648, dtype: object
Whittier
 Age                          27
M/F                           M
City                   Whittier
State                        CA
Country                     USA
Half            0 days 01:31:13
40K             0 days 02:55:32
Pace                    0:07:03
TotalSeconds            10532.0
HalfSeconds              5473.0
Name: 5003, dtype: object
Wichita
 Age                          26
M/F                           M
City                    Wichita
State                        KS
Country                     USA
Half            0 days 01:38:08
40K             0 days 03:06:02
Pace                    0:07:27
TotalSeconds            11162.0
HalfSeconds              5888.0
Name: 756, dtype: object
Wien
 Age                          36
M/F                           M
City                       Wien
State                       NaN
Country                     AUT
Half            0 days 01:24:15
40K             0 days 02:55:23
Pace                    0:07:08
TotalSeconds            10523.0
HalfSeconds              5055.0

Name: 1011, dtype: object
Wiener Neustadt
 Age                          52
M/F                           M
City            Wiener Neustadt
State                       NaN
Country                     AUT
Half            0 days 01:46:00
40K             0 days 03:39:02
Pace                    0:08:53
TotalSeconds            13142.0
HalfSeconds              6360.0
Name: 14256, dtype: object
Wiesbaden
 Age                          53
M/F                           M
City                  Wiesbaden
State                       NaN
Country                     GER
Half            0 days 01:45:35
40K             0 days 03:28:32
Pace                    0:08:22
TotalSeconds            12512.0
HalfSeconds              6335.0
Name: 31207, dtype: object
Wilbraham
 Age                          26
M/F                           M
City                  Wilbraham
State                        MA
Country                     USA
Half            0 days 01:25:52
40K             0 days 03:00:35
Pace                    0:07:21
TotalSeconds            10835.0
HalfSeconds              5152.0
Name: 3755, dtype: object
Wilburton
 Age                          46
M/F                           M
City                  Wilburton
State                        OK
Country                     USA
Half            0 days 01:32:32
40K             0 days 03:10:07
Pace                    0:07:41
TotalSeconds            11407.0
HalfSeconds              5552.0
Name: 4706, dtype: object
Wildwood
 Age                          46
M/F                           F
City                   Wildwood
State                        MO
Country                     USA
Half            0 days 01:41:31
40K             0 days 03:14:01
Pace                    0:07:52
TotalSeconds            11641.0
HalfSeconds              6091.0
Name: 22687, dtype: object
Wilkes-Barre
 Age                          22
M/F                           M
City               Wilkes-Barre
State                        PA
Country                     USA
Half            0 days 01:24:39
40K             0 days 02:43:54
Pace                    0:06:38
TotalSeconds             9834.0
HalfSeconds              5079.0
Name: 1189, dtype: object
Willebroek
 Age                          44
M/F                           F
City                 Willebroek
State                       NaN
Country                     BEL
Half            0 days 02:22:03
40K             0 days 04:47:37
Pace                    0:11:38
TotalSeconds            17257.0
HalfSeconds              8523.0
Name: 31283, dtype: object
Williamsburg
 Age                          21
M/F                           M
City               Williamsburg
State                        VA
Country                     USA
Half            0 days 01:26:03
40K             0 days 02:41:08
Pace                    0:06:29
TotalSeconds             9668.0
HalfSeconds              5163.0
Name: 4130, dtype: object
Williamson
 Age                          30
M/F                           F
City                 Williamson
State                        NY
Country                     USA
Half            0 days 01:58:37
40K             0 days 03:54:40
Pace                    0:09:26
TotalSeconds            14080.0
HalfSeconds              7117.0
Name: 18231, dtype: object
Williamsport
 Age                          39
M/F                           M
City               Williamsport
State                        PA
Country                     USA
Half            0 days 01:30:08
40K             0 days 03:04:52
Pace                    0:07:30
TotalSeconds            11092.0
HalfSeconds              5408.0
Name: 6254, dtype: object
Williamston
 Age                          48
M/F                           F
City                Williamston
State                        MI
Country                     USA
Half            0 days 01:46:46
40K             0 days 03:27:38
Pace                    0:08:24
TotalSeconds            12458.0
HalfSeconds              6406.0
Name: 20114, dtype: object
Williamstown
 Age                          34
M/F                           M
City               Williamstown
State                        NJ
Country                     USA
Half            0 days 01:28:23
40K             0 days 02:54:26
Pace                    0:07:05
TotalSeconds            10466.0
HalfSeconds              5303.0
Name: 4191, dtype: object
Williamsville
 Age                          42
M/F                           F
City              Williamsville
State                        VT
Country                     USA
Half            0 days 01:28:40
40K             0 days 02:55:58
Pace                    0:07:06
TotalSeconds            10558.0
HalfSeconds              5320.0
Name: 2809, dtype: object
Willimantic
 Age                          65
M/F                           M
City                Willimantic
State                        CT
Country                     USA
Half            0 days 01:55:32
40K             0 days 03:43:22
Pace                    0:09:13
TotalSeconds            13402.0
HalfSeconds              6932.0
Name: 23437, dtype: object
Willington
 Age                          51
M/F                           M
City                 Willington
State                        CT
Country                     USA
Half            0 days 01:35:44
40K             0 days 03:07:00
Pace                    0:07:33
TotalSeconds            11220.0
HalfSeconds              5744.0
Name: 8521, dtype: object
Williston
 Age                          42
M/F                           M
City                  Williston
State                        VT
Country                     USA
Half            0 days 01:37:56
40K             0 days 03:06:53
Pace                    0:07:31
TotalSeconds            11213.0
HalfSeconds              5876.0
Name: 8043, dtype: object
Willmar
 Age                          34
M/F                           M
City                    Willmar
State                        MN
Country                     USA
Half            0 days 01:23:11
40K             0 days 02:52:46
Pace                    0:07:02
TotalSeconds            10366.0
HalfSeconds              4991.0
Name: 2089, dtype: object
Willoughby
 Age                          54
M/F                           M
City                 Willoughby
State                       NaN
Country                     AUS
Half            0 days 01:31:15
40K             0 days 03:07:12
Pace                    0:07:40
TotalSeconds            11232.0
HalfSeconds              5475.0
Name: 9501, dtype: object
Willoughby Hills
 Age                           25
M/F                            M
City            Willoughby Hills
State                         OH
Country                      USA
Half             0 days 01:25:37
40K              0 days 03:36:20
Pace                     0:08:50
TotalSeconds             12980.0
HalfSeconds               5137.0
Name: 2671, dtype: object
Willow
 Age                          46
M/F                           M
City                     Willow
State                        AK
Country                     USA
Half            0 days 01:38:30
40K             0 days 03:24:27
Pace                    0:08:15
TotalSeconds            12267.0
HalfSeconds              5910.0
Name: 7596, dtype: object
Willow Grove
 Age                          42
M/F                           M
City               Willow Grove
State                        PA
Country                     USA
Half            0 days 01:27:53
40K             0 days 02:56:52
Pace                    0:07:10
TotalSeconds            10612.0
HalfSeconds              5273.0
Name: 1174, dtype: object
Willowbrook
 Age                          30
M/F                           M
City                Willowbrook
State                        IL
Country                     USA
Half            0 days 01:24:52
40K             0 days 02:42:54
Pace                    0:06:34
TotalSeconds             9774.0
HalfSeconds              5092.0
Name: 1436, dtype: object
Wilmette
 Age                          40
M/F                           F
City                   Wilmette
State                        IL
Country                     USA
Half            0 days 01:41:47
40K             0 days 03:28:48
Pace                    0:08:24
TotalSeconds            12528.0
HalfSeconds              6107.0
Name: 11316, dtype: object
Wilmington
 Age                          33
M/F                           M
City                 Wilmington
State                        DE
Country                     USA
Half            0 days 01:19:08
40K             0 days 02:40:20
Pace                    0:06:30
TotalSeconds             9620.0
HalfSeconds              4748.0
Name: 575, dtype: object
Wilsele
 Age                          46
M/F                           M
City                    Wilsele
State                       NaN
Country                     BEL
Half            0 days 01:28:37
40K             0 days 03:21:40
Pace                    0:08:47
TotalSeconds            12100.0
HalfSeconds              5317.0
Name: 10371, dtype: object
Wilsonville
 Age                          50
M/F                           M
City                Wilsonville
State                        OR
Country                     USA
Half            0 days 01:42:49
40K             0 days 03:26:40
Pace                    0:08:23
TotalSeconds            12400.0
HalfSeconds              6169.0
Name: 14719, dtype: object
Wilston
 Age                          46
M/F                           M
City                    Wilston
State                       NaN
Country                     AUS
Half            0 days 01:29:37
40K             0 days 02:59:58
Pace                    0:07:16
TotalSeconds            10798.0
HalfSeconds              5377.0
Name: 4370, dtype: object
Wilton
 Age                          38
M/F                           M
City                     Wilton
State                        CT
Country                     USA
Half            0 days 01:20:19
40K             0 days 02:41:22
Pace                    0:06:34
TotalSeconds             9682.0
HalfSeconds              4819.0
Name: 5468, dtype: object
Wimberley
 Age                          37
M/F                           M
City                  Wimberley
State                        TX
Country                     USA
Half            0 days 01:27:30
40K             0 days 02:53:51
Pace                    0:07:03
TotalSeconds            10431.0
HalfSeconds              5250.0
Name: 2947, dtype: object
Winchester
 Age                          34
M/F                           M
City                 Winchester
State                        MA
Country                     USA
Half            0 days 01:21:05
40K             0 days 02:39:03
Pace                    0:06:26
TotalSeconds             9543.0
HalfSeconds              4865.0
Name: 894, dtype: object
Wind Lake
 Age                          23
M/F                           F
City                  Wind Lake
State                        WI
Country                     USA
Half            0 days 01:33:21
40K             0 days 03:07:00
Pace                    0:07:36
TotalSeconds            11220.0
HalfSeconds              5601.0
Name: 7364, dtype: object
Windber
 Age                          30
M/F                           M
City                    Windber
State                        PA
Country                     USA
Half            0 days 01:30:53
40K             0 days 03:09:52
Pace                    0:07:40
TotalSeconds            11392.0
HalfSeconds              5453.0
Name: 2357, dtype: object
Windermere
 Age                          42
M/F                           F
City                 Windermere
State                        FL
Country                     USA
Half            0 days 01:39:36
40K             0 days 03:14:23
Pace                    0:07:51
TotalSeconds            11663.0
HalfSeconds              5976.0
Name: 19321, dtype: object
Windham
 Age                          50
M/F                           F
City                    Windham
State                        ME
Country                     USA
Half            0 days 01:52:25
40K             0 days 03:36:09
Pace                    0:08:42
TotalSeconds            12969.0
HalfSeconds              6745.0
Name: 19844, dtype: object
Windsor
 Age                          36
M/F                           M
City                    Windsor
State                        WI
Country                     USA
Half            0 days 01:26:38
40K             0 days 03:09:00
Pace                    0:07:38
TotalSeconds            11340.0
HalfSeconds              5198.0
Name: 2639, dtype: object
Windsor Mill
 Age                          39
M/F                           F
City               Windsor Mill
State                        MD
Country                     USA
Half            0 days 02:06:52
40K             0 days 04:23:19
Pace                    0:10:43
TotalSeconds            15799.0
HalfSeconds              7612.0
Name: 19689, dtype: object
Winfield
 Age                          26
M/F                           M
City                   Winfield
State                        KS
Country                     USA
Half            0 days 01:28:53
40K             0 days 02:55:56
Pace                    0:07:10
TotalSeconds            10556.0
HalfSeconds              5333.0
Name: 2031, dtype: object
Winneconne
 Age                          47
M/F                           M
City                 Winneconne
State                        WI
Country                     USA
Half            0 days 02:00:26
40K             0 days 04:13:27
Pace                    0:10:17
TotalSeconds            15207.0
HalfSeconds              7226.0
Name: 10293, dtype: object
Winnetka
 Age                          30
M/F                           M
City                   Winnetka
State                        IL
Country                     USA
Half            0 days 01:30:18
40K             0 days 02:54:35
Pace                    0:07:02
TotalSeconds            10475.0
HalfSeconds              5418.0

Name: 4907, dtype: object
Winnipeg
 Age                          31
M/F                           M
City                   Winnipeg
State                        MB
Country                     CAN
Half            0 days 01:19:46
40K             0 days 02:39:51
Pace                    0:06:28
TotalSeconds             9591.0
HalfSeconds              4786.0
Name: 659, dtype: object
Winnnipeg
 Age                          65
M/F                           M
City                  Winnnipeg
State                        MB
Country                     CAN
Half            0 days 02:22:33
40K             0 days 05:05:09
Pace                    0:12:16
TotalSeconds            18309.0
HalfSeconds              8553.0
Name: 21917, dtype: object
Winona
 Age                          38
M/F                           M
City                     Winona
State                        MN
Country                     USA
Half            0 days 01:27:58
40K             0 days 03:10:35
Pace                    0:07:46
TotalSeconds            11435.0
HalfSeconds              5278.0
Name: 2630, dtype: object
Winsdor
 Age                          56
M/F                           M
City                    Winsdor
State                        CT
Country                     USA
Half            0 days 01:37:20
40K             0 days 03:17:40
Pace                    0:08:03
TotalSeconds            11860.0
HalfSeconds              5840.0
Name: 10443, dtype: object
Winsted
 Age                          52
M/F                           M
City                    Winsted
State                        CT
Country                     USA
Half            0 days 01:38:40
40K             0 days 03:13:22
Pace                    0:07:49
TotalSeconds            11602.0
HalfSeconds              5920.0
Name: 11456, dtype: object
Winston Salem
 Age                          35
M/F                           M
City              Winston Salem
State                        NC
Country                     USA
Half            0 days 01:16:05
40K             0 days 02:38:20
Pace                    0:06:27
TotalSeconds             9500.0
HalfSeconds              4565.0
Name: 620, dtype: object
Winston-Salem
 Age                          43
M/F                           M
City              Winston-Salem
State                        NC
Country                     USA
Half            0 days 01:24:07
40K             0 days 02:47:28
Pace                    0:06:49
TotalSeconds            10048.0
HalfSeconds              5047.0
Name: 1744, dtype: object
Winter Garden
 Age                          43
M/F                           F
City              Winter Garden
State                        FL
Country                     USA
Half            0 days 01:49:58
40K             0 days 03:32:08
Pace                    0:08:34
TotalSeconds            12728.0
HalfSeconds              6598.0
Name: 21216, dtype: object
Winter Haven
 Age                          50
M/F                           F
City               Winter Haven
State                        FL
Country                     USA
Half            0 days 02:03:00
40K             0 days 04:24:15
Pace                    0:10:38
TotalSeconds            15855.0
HalfSeconds              7380.0
Name: 23122, dtype: object
Winter Park
 Age                          39
M/F                           M
City                Winter Park
State                        FL
Country                     USA
Half            0 days 01:28:30
40K             0 days 02:56:17
Pace                    0:07:08
TotalSeconds            10577.0
HalfSeconds              5310.0
Name: 4034, dtype: object
Winter Springs
 Age                          38
M/F                           M
City             Winter Springs
State                        FL
Country                     USA
Half            0 days 01:24:08
40K             0 days 03:11:55
Pace                    0:07:46
TotalSeconds            11515.0
HalfSeconds              5048.0
Name: 1937, dtype: object
Winthrop
 Age                          45
M/F                           M
City                   Winthrop
State                        MA
Country                     USA
Half            0 days 01:32:06
40K             0 days 03:04:42
Pace                    0:07:29
TotalSeconds            11082.0
HalfSeconds              5526.0
Name: 8199, dtype: object
Wirral
 Age                          32
M/F                           M
City                     Wirral
State                       NaN
Country                     GBR
Half            0 days 01:25:47
40K             0 days 03:07:31
Pace                    0:07:35
TotalSeconds            11251.0
HalfSeconds              5147.0
Name: 1963, dtype: object
Wiscasset
 Age                          68
M/F                           M
City                  Wiscasset
State                        ME
Country                     USA
Half            0 days 02:51:09
40K             0 days 05:47:21
Pace                    0:14:04
TotalSeconds            20841.0
HalfSeconds             10269.0
Name: 15575, dtype: object
Wisconsin Rapids
 Age                           57
M/F                            M
City            Wisconsin Rapids
State                         WI
Country                      USA
Half             0 days 01:38:00
40K              0 days 03:12:18
Pace                     0:07:46
TotalSeconds             11538.0
HalfSeconds               5880.0
Name: 8144, dtype: object
Wixom
 Age                          25
M/F                           F
City                      Wixom
State                        MI
Country                     USA
Half            0 days 01:34:26
40K             0 days 03:08:38
Pace                    0:07:40
TotalSeconds            11318.0
HalfSeconds              5666.0
Name: 4021, dtype: object
Woburn
 Age                          25
M/F                           M
City                     Woburn
State                        MA
Country                     USA
Half            0 days 01:43:54
40K             0 days 03:19:14
Pace                    0:08:03
TotalSeconds            11954.0
HalfSeconds              6234.0
Name: 26273, dtype: object
Woellersdorf
 Age                          48
M/F                           M
City               Woellersdorf
State                       NaN
Country                     AUT
Half            0 days 01:34:51
40K             0 days 03:10:38
Pace                    0:07:47
TotalSeconds            11438.0
HalfSeconds              5691.0
Name: 10607, dtype: object
Woking
 Age                          40
M/F                           M
City                     Woking
State                       NaN
Country                     GBR
Half            0 days 01:33:35
40K             0 days 03:03:07
Pace                    0:07:25
TotalSeconds            10987.0
HalfSeconds              5615.0
Name: 7061, dtype: object
Wolcottville
 Age                          28
M/F                           M
City               Wolcottville
State                        IN
Country                     USA
Half            0 days 01:11:40
40K             0 days 02:19:24
Pace                    0:05:37
TotalSeconds             8364.0
HalfSeconds              4300.0
Name: 38, dtype: object
Wolfeboro
 Age                          38
M/F                           F
City                  Wolfeboro
State                        NH
Country                     USA
Half            0 days 01:45:38
40K             0 days 03:21:32
Pace                    0:08:07
TotalSeconds            12092.0
HalfSeconds              6338.0
Name: 19427, dtype: object
Wolfville
 Age                          76
M/F                           M
City                  Wolfville
State                        NS
Country                     CAN
Half            0 days 02:28:49
40K             0 days 05:01:24
Pace                    0:12:09
TotalSeconds            18084.0
HalfSeconds              8929.0
Name: 26093, dtype: object
Woluwé-Saint-Pierre
 Age                              48
M/F                               M
City            Woluwé-Saint-Pierre
State                           NaN
Country                         BEL
Half                0 days 01:33:19
40K                 0 days 03:09:52
Pace                        0:07:42
TotalSeconds                11392.0
HalfSeconds                  5599.0
Name: 3272, dtype: object
Wolverine Lake
 Age                          32
M/F                           M
City             Wolverine Lake
State                        MI
Country                     USA
Half            0 days 01:20:17
40K             0 days 03:00:54
Pace                    0:07:22
TotalSeconds            10854.0
HalfSeconds              4817.0
Name: 1487, dtype: object
Woodbine
 Age                          38
M/F                           F
City                   Woodbine
State                        NJ
Country                     USA
Half            0 days 01:46:25
40K             0 days 03:30:32
Pace                    0:08:31
TotalSeconds            12632.0
HalfSeconds              6385.0
Name: 18857, dtype: object
Woodbridge
 Age                          26
M/F                           M
City                 Woodbridge
State                        VA
Country                     USA
Half            0 days 01:22:52
40K             0 days 02:47:56
Pace                    0:06:49
TotalSeconds            10076.0
HalfSeconds              4972.0

Name: 2832, dtype: object
Woodbury
 Age                          40
M/F                           M
City                   Woodbury
State                        NJ
Country                     USA
Half            0 days 01:19:03
40K             0 days 02:39:08
Pace                    0:06:27
TotalSeconds             9548.0
HalfSeconds              4743.0
Name: 323, dtype: object
Woodcliff Lake
 Age                          54
M/F                           M
City             Woodcliff Lake
State                        NJ
Country                     USA
Half            0 days 01:38:18
40K             0 days 03:18:23
Pace                    0:08:00
TotalSeconds            11903.0
HalfSeconds              5898.0
Name: 3092, dtype: object
Woodinville
 Age                          34
M/F                           M
City                Woodinville
State                        WA
Country                     USA
Half            0 days 01:26:10
40K             0 days 02:53:22
Pace                    0:07:03
TotalSeconds            10402.0
HalfSeconds              5170.0
Name: 3630, dtype: object
Woodland
 Age                          65
M/F                           M
City                   Woodland
State                        CA
Country                     USA
Half            0 days 02:30:12
40K             0 days 04:50:38
Pace                    0:11:37
TotalSeconds            17438.0
HalfSeconds              9012.0
Name: 25261, dtype: object
Woodland Hills
 Age                          37
M/F                           F
City             Woodland Hills
State                        CA
Country                     USA
Half            0 days 01:43:01
40K             0 days 03:19:49
Pace                    0:08:04
TotalSeconds            11989.0
HalfSeconds              6181.0
Name: 18595, dtype: object
Woodlands
 Age                          23
M/F                           F
City                  Woodlands
State                        TX
Country                     USA
Half            0 days 01:44:38
40K             0 days 03:19:55
Pace                    0:08:02
TotalSeconds            11995.0
HalfSeconds              6278.0
Name: 14216, dtype: object
Woodlawn
 Age                          48
M/F                           M
City                   Woodlawn
State                        TN
Country                     USA
Half            0 days 02:00:17
40K             0 days 04:04:53
Pace                    0:09:55
TotalSeconds            14693.0
HalfSeconds              7217.0
Name: 26145, dtype: object
Woodley
 Age                          41
M/F                           F
City                    Woodley
State                       NaN
Country                     GBR
Half            0 days 02:04:50
40K             0 days 04:08:05
Pace                    0:10:01
TotalSeconds            14885.0
HalfSeconds              7490.0
Name: 21576, dtype: object
Woodridge
 Age                          35
M/F                           F
City                  Woodridge
State                        IL
Country                     USA
Half            0 days 01:56:20
40K             0 days 03:50:22
Pace                    0:09:19
TotalSeconds            13822.0
HalfSeconds              6980.0
Name: 19857, dtype: object
Woods Cross
 Age                          32
M/F                           M
City                Woods Cross
State                        UT
Country                     USA
Half            0 days 01:26:38
40K             0 days 02:51:51
Pace                    0:06:53
TotalSeconds            10311.0
HalfSeconds              5198.0
Name: 2584, dtype: object
Woodsboro
 Age                          21
M/F                           F
City                  Woodsboro
State                        MD
Country                     USA
Half            0 days 00:00:00
40K             0 days 03:20:09
Pace                    0:08:05
TotalSeconds            12009.0
HalfSeconds                 0.0
Name: 17345, dtype: object
Woodside
 Age                          46
M/F                           M
City                   Woodside
State                        CA
Country                     USA
Half            0 days 01:27:22
40K             0 days 02:47:00
Pace                    0:06:44
TotalSeconds            10020.0
HalfSeconds              5242.0
Name: 731, dtype: object
Woodslee
 Age                          52
M/F                           F
City                   Woodslee
State                        ON
Country                     CAN
Half            0 days 01:56:44
40K             0 days 03:53:03
Pace                    0:09:24
TotalSeconds            13983.0
HalfSeconds              7004.0
Name: 24552, dtype: object
Woodstock
 Age                          29
M/F                           M
City                  Woodstock
State                        GA
Country                     USA
Half            0 days 01:26:27
40K             0 days 02:50:00
Pace                    0:06:50
TotalSeconds            10200.0
HalfSeconds              5187.0
Name: 1128, dtype: object
Woodway
 Age                          49
M/F                           F
City                    Woodway
State                        TX
Country                     USA
Half            0 days 01:37:08
40K             0 days 03:12:58
Pace                    0:07:48
TotalSeconds            11578.0
HalfSeconds              5828.0
Name: 9845, dtype: object
Woolford
 Age                          52
M/F                           F
City                   Woolford
State                        MD
Country                     USA
Half            0 days 01:59:45
40K             0 days 03:55:10
Pace                    0:09:29
TotalSeconds            14110.0
HalfSeconds              7185.0
Name: 24483, dtype: object
Woolloomooloo
 Age                          39
M/F                           M
City              Woolloomooloo
State                       NaN
Country                     AUS
Half            0 days 01:32:08
40K             0 days 03:02:01
Pace                    0:07:21
TotalSeconds            10921.0
HalfSeconds              5528.0
Name: 6835, dtype: object
Wooloowin
 Age                          42
M/F                           M
City                  Wooloowin
State                       NaN
Country                     AUS
Half            0 days 01:26:31
40K             0 days 02:47:46
Pace                    0:06:45
TotalSeconds            10066.0
HalfSeconds              5191.0
Name: 3505, dtype: object
Wooster
 Age                          55
M/F                           M
City                    Wooster
State                        OH
Country                     USA
Half            0 days 01:47:36
40K             0 days 03:42:08
Pace                    0:08:59
TotalSeconds            13328.0
HalfSeconds              6456.0
Name: 12024, dtype: object
Worcester
 Age                          26
M/F                           M
City                  Worcester
State                        MA
Country                     USA
Half            0 days 01:19:54
40K             0 days 02:33:34
Pace                    0:06:12
TotalSeconds             9214.0
HalfSeconds              4794.0
Name: 492, dtype: object
Worcestershire
 Age                          65
M/F                           M
City             Worcestershire
State                       NaN
Country                     GBR
Half            0 days 01:55:05
40K             0 days 03:52:54
Pace                    0:09:29
TotalSeconds            13974.0
HalfSeconds              6905.0
Name: 22920, dtype: object
Worden
 Age                          51
M/F                           M
City                     Worden
State                        IL
Country                     USA
Half            0 days 01:50:41
40K             0 days 04:02:21
Pace                    0:09:53
TotalSeconds            14541.0
HalfSeconds              6641.0
Name: 13137, dtype: object
Worthington
 Age                          44
M/F                           M
City                Worthington
State                        MN
Country                     USA
Half            0 days 01:32:59
40K             0 days 03:11:25
Pace                    0:07:43
TotalSeconds            11485.0
HalfSeconds              5579.0
Name: 4905, dtype: object
Wrentham
 Age                          47
M/F                           M
City                   Wrentham
State                        MA
Country                     USA
Half            0 days 01:40:06
40K             0 days 03:12:26
Pace                    0:07:45
TotalSeconds            11546.0
HalfSeconds              6006.0
Name: 11457, dtype: object
Wrightsville Beach
 Age                             39
M/F                              F
City            Wrightsville Beach
State                           NC
Country                        USA
Half               0 days 01:45:25
40K                0 days 03:27:17
Pace                       0:08:21
TotalSeconds               12437.0
HalfSeconds                 6325.0
Name: 18741, dtype: object
Wrightwood
 Age                          46
M/F                           F
City                 Wrightwood
State                        CA
Country                     USA
Half            0 days 01:41:07
40K             0 days 03:15:31
Pace                    0:07:53
TotalSeconds            11731.0
HalfSeconds              6067.0
Name: 10927, dtype: object
Wroclaw
 Age                          58
M/F                           M
City                    Wroclaw
State                       NaN
Country                     POL
Half            0 days 01:45:42
40K             0 days 03:37:39
Pace                    0:08:48
TotalSeconds            13059.0
HalfSeconds              6342.0
Name: 15215, dtype: object
Wuhu City, Anhui
 Age                           67
M/F                            M
City            Wuhu City, Anhui
State                        NaN
Country                      CHN
Half             0 days 01:50:09
40K              0 days 03:53:08
Pace                     0:09:29
TotalSeconds             13988.0
HalfSeconds               6609.0
Name: 20745, dtype: object
Wuxi, Jiangsu
 Age                          37
M/F                           F
City              Wuxi, Jiangsu
State                       NaN
Country                     CHN
Half            0 days 01:56:36
40K             0 days 03:54:11
Pace                    0:09:29
TotalSeconds            14051.0
HalfSeconds              6996.0
Name: 16878, dtype: object
Wyandotte
 Age                          24
M/F                           F
City                  Wyandotte
State                        MI
Country                     USA
Half            0 days 01:38:13
40K             0 days 03:12:32
Pace                    0:07:47
TotalSeconds            11552.0
HalfSeconds              5893.0
Name: 9763, dtype: object
Wyckoff
 Age                          39
M/F                           M
City                    Wyckoff
State                        NJ
Country                     USA
Half            0 days 02:28:33
40K             0 days 05:05:25
Pace                    0:12:21
TotalSeconds            18325.0
HalfSeconds              8913.0
Name: 29379, dtype: object
Wykoff
 Age                          37
M/F                           F
City                     Wykoff
State                        MN
Country                     USA
Half            0 days 01:55:41
40K             0 days 03:36:28
Pace                    0:08:41
TotalSeconds            12988.0
HalfSeconds              6941.0
Name: 19686, dtype: object
Wylie
 Age                          49
M/F                           M
City                      Wylie
State                        TX
Country                     USA
Half            0 days 01:21:22
40K             0 days 02:43:12
Pace                    0:06:39
TotalSeconds             9792.0
HalfSeconds              4882.0
Name: 922, dtype: object
Wyncote
 Age                          45
M/F                           M
City                    Wyncote
State                        PA
Country                     USA
Half            0 days 01:29:04
40K             0 days 02:54:07
Pace                    0:07:03
TotalSeconds            10447.0
HalfSeconds              5344.0
Name: 3784, dtype: object
Wynnewood
 Age                          34
M/F                           M
City                  Wynnewood
State                        PA
Country                     USA
Half            0 days 01:25:01
40K             0 days 03:00:50
Pace                    0:07:19
TotalSeconds            10850.0
HalfSeconds              5101.0
Name: 3692, dtype: object
Wyoming
 Age                          25
M/F                           M
City                    Wyoming
State                        RI
Country                     USA
Half            0 days 01:19:42
40K             0 days 02:30:13
Pace                    0:06:05
TotalSeconds             9013.0
HalfSeconds              4782.0
Name: 2864, dtype: object
Wyomissing
 Age                          37
M/F                           F
City                 Wyomissing
State                        PA
Country                     USA
Half            0 days 01:37:53
40K             0 days 03:24:29
Pace                    0:08:37
TotalSeconds            12269.0
HalfSeconds              5873.0
Name: 16083, dtype: object
Wytheville
 Age                          35
M/F                           M
City                 Wytheville
State                        VA
Country                     USA
Half            0 days 01:28:46
40K             0 days 03:05:57
Pace                    0:07:37
TotalSeconds            11157.0
HalfSeconds              5326.0
Name: 5210, dtype: object
Xalapa
 Age                          44
M/F                           M
City                     Xalapa
State                       NaN
Country                     MEX
Half            0 days 01:19:03
40K             0 days 02:32:21
Pace                    0:06:09
TotalSeconds             9141.0
HalfSeconds              4743.0
Name: 6065, dtype: object
Xenia
 Age                          51
M/F                           M
City                      Xenia
State                        OH
Country                     USA
Half            0 days 01:48:12
40K             0 days 03:45:09
Pace                    0:09:07
TotalSeconds            13509.0
HalfSeconds              6492.0
Name: 15101, dtype: object
Xi'An
 Age                          45
M/F                           M
City                      Xi'An
State                       NaN
Country                     CHN
Half            0 days 01:47:18
40K             0 days 03:44:30
Pace                    0:09:02
TotalSeconds            13470.0
HalfSeconds              6438.0
Name: 3826, dtype: object
Yangpu, Shanghai
 Age                           28
M/F                            M
City            Yangpu, Shanghai
State                        NaN
Country                      CHN
Half             0 days 01:12:38
40K              0 days 02:33:57
Pace                     0:06:19
TotalSeconds              9237.0
HalfSeconds               4358.0
Name: 118, dtype: object
Yaphank
 Age                          45
M/F                           M
City                    Yaphank
State                        NY
Country                     USA
Half            0 days 01:38:04
40K             0 days 03:07:35
Pace                    0:07:35
TotalSeconds            11255.0
HalfSeconds              5884.0
Name: 11319, dtype: object
Yardley
 Age                          42
M/F                           M
City                    Yardley
State                        PA
Country                     USA
Half            0 days 01:32:36
40K             0 days 03:27:59
Pace                    0:08:29
TotalSeconds            12479.0
HalfSeconds              5556.0
Name: 8672, dtype: object
Yarmouth
 Age                          42
M/F                           M
City                   Yarmouth
State                        NS
Country                     CAN
Half            0 days 01:28:28
40K             0 days 02:54:15
Pace                    0:07:04
TotalSeconds            10455.0
HalfSeconds              5308.0
Name: 3193, dtype: object
Yarmouth Port
 Age                          62
M/F                           F
City              Yarmouth Port
State                        MA
Country                     USA
Half            0 days 02:18:39
40K             0 days 04:51:39
Pace                    0:11:54
TotalSeconds            17499.0
HalfSeconds              8319.0
Name: 25761, dtype: object
Yarmouthport
 Age                          26
M/F                           M
City               Yarmouthport
State                        MA
Country                     USA
Half            0 days 01:20:17
40K             0 days 02:34:35
Pace                    0:06:14
TotalSeconds             9275.0
HalfSeconds              4817.0
Name: 1839, dtype: object
Yatton
 Age                          31
M/F                           M
City                     Yatton
State                       NaN
Country                     GBR
Half            0 days 01:28:54
40K             0 days 02:59:17
Pace                    0:07:16
TotalSeconds            10757.0
HalfSeconds              5334.0
Name: 2499, dtype: object
Yigo
 Age                          27
M/F                           F
City                       Yigo
State                        GU
Country                     USA
Half            0 days 01:52:25
40K             0 days 03:51:28
Pace                    0:09:22
TotalSeconds            13888.0
HalfSeconds              6745.0
Name: 15470, dtype: object
Yilan County
 Age                          70
M/F                           M
City               Yilan County
State                       NaN
Country                     TWN
Half            0 days 01:46:10
40K             0 days 03:34:24
Pace                    0:08:44
TotalSeconds            12864.0
HalfSeconds              6370.0
Name: 20086, dtype: object
Yokohama
 Age                          42
M/F                           M
City                   Yokohama
State                       NaN
Country                     JPN
Half            0 days 01:18:57
40K             0 days 02:55:28
Pace                    0:07:08
TotalSeconds            10528.0
HalfSeconds              4737.0
Name: 316, dtype: object
Yokohama City
 Age                          57
M/F                           M
City              Yokohama City
State                       NaN
Country                     JPN
Half            0 days 01:47:55
40K             0 days 03:50:49
Pace                    0:09:25
TotalSeconds            13849.0
HalfSeconds              6475.0
Name: 19009, dtype: object
Yokohama- City. Kanagawa
 Age                                   28
M/F                                    M
City            Yokohama- City. Kanagawa
State                                NaN
Country                              JPN
Half                     0 days 02:38:43
40K                      0 days 05:18:34
Pace                             0:12:53
TotalSeconds                     19114.0
HalfSeconds                       9523.0
Name: 31709, dtype: object
Yonkers
 Age                          32
M/F                           F
City                    Yonkers
State                        NY
Country                     USA
Half            0 days 01:29:42
40K             0 days 03:00:56
Pace                    0:07:20
TotalSeconds            10856.0
HalfSeconds              5382.0
Name: 14093, dtype: object
Yorba Linda
 Age                          48
M/F                           F
City                Yorba Linda
State                        CA
Country                     USA
Half            0 days 01:46:29
40K             0 days 03:36:51
Pace                    0:08:46
TotalSeconds            13011.0
HalfSeconds              6389.0
Name: 20755, dtype: object

Yorba Lnda
 Age                          55
M/F                           M
City                 Yorba Lnda
State                        CA
Country                     USA
Half            0 days 01:39:31
40K             0 days 03:16:36
Pace                    0:07:56
TotalSeconds            11796.0
HalfSeconds              5971.0
Name: 10198, dtype: object
York
 Age                          37
M/F                           M
City                       York
State                        PA
Country                     USA
Half            0 days 01:27:47
40K             0 days 02:51:29
Pace                    0:06:57
TotalSeconds            10289.0
HalfSeconds              5267.0
Name: 3356, dtype: object
York Beach
 Age                          45
M/F                           F
City                 York Beach
State                        ME
Country                     USA
Half            0 days 01:49:59
40K             0 days 03:35:46
Pace                    0:08:44
TotalSeconds            12946.0
HalfSeconds              6599.0
Name: 22457, dtype: object
York Haven
 Age                          48
M/F                           M
City                 York Haven
State                        PA
Country                     USA
Half            0 days 01:39:57
40K             0 days 03:16:40
Pace                    0:07:56
TotalSeconds            11800.0
HalfSeconds              5997.0
Name: 10184, dtype: object
Yorkton
 Age                          26
M/F                           F
City                    Yorkton
State                        SK
Country                     CAN
Half            0 days 01:43:15
40K             0 days 03:45:13
Pace                    0:09:07
TotalSeconds            13513.0
HalfSeconds              6195.0
Name: 11537, dtype: object
Yorktown
 Age                          40
M/F                           M
City                   Yorktown
State                        IN
Country                     USA
Half            0 days 01:25:35
40K             0 days 03:07:37
Pace                    0:07:37
TotalSeconds            11257.0
HalfSeconds              5135.0
Name: 2942, dtype: object
Yorkville
 Age                          39
M/F                           F
City                  Yorkville
State                        IL
Country                     USA
Half            0 days 01:53:47
40K             0 days 03:49:48
Pace                    0:09:19
TotalSeconds            13788.0
HalfSeconds              6827.0
Name: 20059, dtype: object
Youngstown
 Age                          46
M/F                           F
City                 Youngstown
State                        OH
Country                     USA
Half            0 days 01:52:34
40K             0 days 03:39:40
Pace                    0:08:52
TotalSeconds            13180.0
HalfSeconds              6754.0
Name: 23495, dtype: object
Ypsilanti
 Age                          37
M/F                           F
City                  Ypsilanti
State                        MI
Country                     USA
Half            0 days 01:45:09
40K             0 days 03:33:35
Pace                    0:08:38
TotalSeconds            12815.0
HalfSeconds              6309.0
Name: 19303, dtype: object
Yreka
 Age                          30
M/F                           M
City                      Yreka
State                        CA
Country                     USA
Half            0 days 01:25:06
40K             0 days 02:42:25
Pace                    0:06:32
TotalSeconds             9745.0
HalfSeconds              5106.0
Name: 2208, dtype: object
Yuba City
 Age                          32
M/F                           M
City                  Yuba City
State                        CA
Country                     USA
Half            0 days 01:30:53
40K             0 days 03:56:06
Pace                    0:09:46
TotalSeconds            14166.0
HalfSeconds              5453.0
Name: 4059, dtype: object
Yucaipa
 Age                          26
M/F                           M
City                    Yucaipa
State                        CA
Country                     USA
Half            0 days 01:10:37
40K             0 days 02:23:48
Pace                    0:05:54
TotalSeconds             8628.0
HalfSeconds              4237.0
Name: 117, dtype: object
Yuen Long, Hong Kong
 Age                               55
M/F                                F
City            Yuen Long, Hong Kong
State                            NaN
Country                          HKG
Half                 0 days 02:04:56
40K                  0 days 04:12:47
Pace                         0:10:13
TotalSeconds                 15167.0
HalfSeconds                   7496.0
Name: 25346, dtype: object
Yuma
 Age                          22
M/F                           M
City                       Yuma
State                        AZ
Country                     USA
Half            0 days 01:22:42
40K             0 days 02:42:53
Pace                    0:06:34
TotalSeconds             9773.0
HalfSeconds              4962.0
Name: 2409, dtype: object
Zaamslag
 Age                          44
M/F                           M
City                   Zaamslag
State                       NaN
Country                     NED
Half            0 days 01:55:11
40K             0 days 03:45:36
Pace                    0:09:05
TotalSeconds            13536.0
HalfSeconds              6911.0
Name: 30245, dtype: object
Zaandam
 Age                          32
M/F                           F
City                    Zaandam
State                       NaN
Country                     NED
Half            0 days 01:37:23
40K             0 days 03:21:48
Pace                    0:08:10
TotalSeconds            12108.0
HalfSeconds              5843.0
Name: 9799, dtype: object
Zabrze
 Age                          45
M/F                           M
City                     Zabrze
State                       NaN
Country                     POL
Half            0 days 01:31:50
40K             0 days 02:59:27
Pace                    0:07:16
TotalSeconds            10767.0
HalfSeconds              5510.0
Name: 7482, dtype: object
Zacatecas Zacatecas
 Age                              46
M/F                               M
City            Zacatecas Zacatecas
State                           NaN
Country                         MEX
Half                0 days 01:38:59
40K                 0 days 03:15:06
Pace                        0:07:58
TotalSeconds                11706.0
HalfSeconds                  5939.0
Name: 9950, dtype: object
Zagreb
 Age                          39
M/F                           M
City                     Zagreb
State                       NaN
Country                     CRO
Half            0 days 01:28:22
40K             0 days 02:48:00
Pace                    0:06:45
TotalSeconds            10080.0
HalfSeconds              5302.0
Name: 4377, dtype: object
Zamora, Michoacan
 Age                            30
M/F                             F
City            Zamora, Michoacan
State                         NaN
Country                       MEX
Half              0 days 01:35:22
40K               0 days 03:07:16
Pace                      0:07:35
TotalSeconds              11236.0
HalfSeconds                5722.0
Name: 13576, dtype: object
Zane
 Age                          41
M/F                           M
City                       Zane
State                       NaN
Country                     ITA
Half            0 days 01:34:45
40K             0 days 03:17:52
Pace                    0:08:03
TotalSeconds            11872.0
HalfSeconds              5685.0
Name: 5875, dtype: object
Zapopan
 Age                          45
M/F                           M
City                    Zapopan
State                       NaN
Country                     MEX
Half            0 days 01:26:18
40K             0 days 02:47:51
Pace                    0:06:47
TotalSeconds            10071.0
HalfSeconds              5178.0
Name: 1356, dtype: object
Zapopan Jalisco
 Age                          57
M/F                           M
City            Zapopan Jalisco
State                       NaN
Country                     MEX
Half            0 days 02:04:14
40K             0 days 04:33:50
Pace                    0:11:04
TotalSeconds            16430.0
HalfSeconds              7454.0
Name: 31836, dtype: object
Zapopan, Jal.
 Age                          63
M/F                           M
City              Zapopan, Jal.
State                       NaN
Country                     MEX
Half            0 days 01:35:06
40K             0 days 03:37:00
Pace                    0:08:59
TotalSeconds            13020.0
HalfSeconds              5706.0
Name: 12801, dtype: object
Zarautz – Gipuzkoa
 Age                             46
M/F                              M
City            Zarautz – Gipuzkoa
State                          NaN
Country                        ESP
Half               0 days 02:00:51
40K                0 days 04:20:48
Pace                       0:10:31
TotalSeconds               15648.0
HalfSeconds                 7251.0
Name: 31679, dtype: object
Zebulon
 Age                          60
M/F                           M
City                    Zebulon
State                        NC
Country                     USA
Half            0 days 01:55:49
40K             0 days 03:56:03
Pace                    0:09:38
TotalSeconds            14163.0
HalfSeconds              6949.0
Name: 22919, dtype: object
Zeeland
 Age                          46
M/F                           M
City                    Zeeland
State                        MI
Country                     USA
Half            0 days 01:28:34
40K             0 days 02:49:06
Pace                    0:06:48
TotalSeconds            10146.0
HalfSeconds              5314.0
Name: 4492, dtype: object
Zephyrhills
 Age                          42
M/F                           M
City                Zephyrhills
State                        FL
Country                     USA
Half            0 days 01:35:26
40K             0 days 03:05:40
Pace                    0:07:31
TotalSeconds            11140.0
HalfSeconds              5726.0
Name: 7164, dtype: object
Zhubei City, Hsinchu County
 Age                                      44
M/F                                       M
City            Zhubei City, Hsinchu County
State                                   NaN
Country                                 TWN
Half                        0 days 01:29:14
40K                         0 days 02:51:30
Pace                                0:06:56
TotalSeconds                        10290.0
HalfSeconds                          5354.0
Name: 6123, dtype: object
Zhuhai
 Age                          46
M/F                           M
City                     Zhuhai
State                       NaN
Country                     CHN
Half            0 days 01:29:03
40K             0 days 03:12:21
Pace                    0:07:52
TotalSeconds            11541.0
HalfSeconds              5343.0
Name: 5996, dtype: object
Zichron Yaakov
 Age                          67
M/F                           M
City             Zichron Yaakov
State                       NaN
Country                     ISR
Half            0 days 01:58:42
40K             0 days 03:51:20
Pace                    0:09:22
TotalSeconds            13880.0
HalfSeconds              7122.0
Name: 25480, dtype: object
Zimmerman
 Age                          40
M/F                           F
City                  Zimmerman
State                        MN
Country                     USA
Half            0 days 01:51:46
40K             0 days 03:39:02
Pace                    0:08:49
TotalSeconds            13142.0
HalfSeconds              6706.0
Name: 14617, dtype: object
Zionsville
 Age                          30
M/F                           M
City                 Zionsville
State                        IN
Country                     USA
Half            0 days 01:22:35
40K             0 days 02:40:41
Pace                    0:06:29
TotalSeconds             9641.0
HalfSeconds              4955.0
Name: 1410, dtype: object
Zonhoven
 Age                          35
M/F                           M
City                   Zonhoven
State                       NaN
Country                     BEL
Half            0 days 01:33:13
40K             0 days 03:04:35
Pace                    0:07:26
TotalSeconds            11075.0
HalfSeconds              5593.0
Name: 6859, dtype: object
Zuerich
 Age                          46
M/F                           M
City                    Zuerich
State                       NaN
Country                     SUI
Half            0 days 01:27:54
40K             0 days 02:51:08
Pace                    0:06:53
TotalSeconds            10268.0
HalfSeconds              5274.0
Name: 4728, dtype: object
Zug
 Age                          56
M/F                           M
City                        Zug
State                       NaN
Country                     SUI
Half            0 days 01:46:17
40K             0 days 03:41:54
Pace                    0:09:01
TotalSeconds            13314.0
HalfSeconds              6377.0
Name: 15158, dtype: object
Zumikon
 Age                          42
M/F                           M
City                    Zumikon
State                       NaN
Country                     SUI
Half            0 days 01:28:17
40K             0 days 03:02:12
Pace                    0:07:24
TotalSeconds            10932.0
HalfSeconds              5297.0
Name: 4465, dtype: object
Zurich
 Age                          42
M/F                           M
City                     Zurich
State                       NaN
Country                     SUI
Half            0 days 01:32:09
40K             0 days 03:03:15
Pace                    0:07:26
TotalSeconds            10995.0
HalfSeconds              5529.0
Name: 2978, dtype: object
Zweibruecken
 Age                          58
M/F                           F
City               Zweibruecken
State                       NaN
Country                     GER
Half            0 days 02:22:22
40K             0 days 04:56:52
Pace                    0:11:57
TotalSeconds            17812.0
HalfSeconds              8542.0
Name: 31756, dtype: object
Zwevegem
 Age                          61
M/F                           M
City                   Zwevegem
State                       NaN
Country                     BEL
Half            0 days 02:15:30
40K             0 days 04:42:02
Pace                    0:11:18
TotalSeconds            16922.0
HalfSeconds              8130.0
Name: 31280, dtype: object
Zwolle
 Age                          46
M/F                           M
City                     Zwolle
State                       NaN
Country                     NED
Half            0 days 01:33:21
40K             0 days 03:04:11
Pace                    0:07:27
TotalSeconds            11051.0
HalfSeconds              5601.0
Name: 4052, dtype: object
hingham
 Age                          32
M/F                           M
City                    hingham
State                        MA
Country                     USA
Half            0 days 01:24:38
40K             0 days 02:45:08
Pace                    0:06:39
TotalSeconds             9908.0
HalfSeconds              5078.0
Name: 1507, dtype: object

In [41]:
theBestPerCity=pd.DataFrame()

In [42]:
for row, content in groupCity:
    theBestPerCity=theBestPerCity.append(content.nsmallest(1,"TotalSeconds"))

In [43]:
theBestPerCity.head()

,Age,M/F,City,State,Country,Half,40K,Pace,TotalSeconds,HalfSeconds
Bib,,,,,,,,,,
6229,39,F,0851 Oslo,NaN,NOR,0 days 01:35:31,0 days 03:15:24,0:07:55,11724.0,5731.0
4186,35,M,20832,MD,USA,0 days 01:35:57,0 days 03:14:00,0:07:51,11640.0,5757.0
31786,44,F,34-120 Andrychow,NaN,POL,0 days 01:58:39,0 days 03:55:09,0:09:28,14109.0,7119.0
15350,58,M,5700 Svendborg,NaN,DEN,0 days 01:49:12,0 days 03:44:58,0:09:05,13498.0,6552.0
20668,46,F,95630,CA,USA,0 days 01:50:25,0 days 03:37:23,0:08:44,13043.0,6625.0